// Prüferfragen zu Sicherheitskontrollen und Fahrzeugtechnik für die praktische Prüfung Klasse B
// (eigene Formulierungen, Stand September 2026). Die Stichpunkte beschreiben eine vollständige Antwort.
import { CLASS_B_CODES } from "./topics.js";
import { CONTENT_SOURCE, LEGAL_BASIS_DATE, type PracticalCategory, type PracticalQuestion, type ReviewStatus } from "./types.js";

function p(category: PracticalCategory, question: string, expectedPoints: string[], explanation: string, reviewStatus: ReviewStatus = "published"): PracticalQuestion {
  return { category, question, expectedPoints, explanation, licenseCodes: [...CLASS_B_CODES], legalBasisDate: LEGAL_BASIS_DATE, source: CONTENT_SOURCE, reviewStatus };
}

export const practicalQuestions: readonly PracticalQuestion[] = [
  // Beleuchtung
  p("lighting", "Prüfen Sie die Funktion des Abblendlichts.",
    ["Zündung einschalten", "Lichtschalter auf Abblendlicht stellen", "Kontrollleuchte im Kombiinstrument prüfen", "Sichtkontrolle beider Scheinwerfer außen oder Reflexion an einer Wand"],
    "Das Abblendlicht ist die Grundbeleuchtung bei Dunkelheit und schlechter Sicht. Beide Scheinwerfer müssen leuchten, ohne zu blenden."),
  p("lighting", "Prüfen Sie die Funktion des Fernlichts.",
    ["Abblendlicht einschalten", "Lenkstockhebel nach vorn oder zum Körper ziehen", "Blaue Kontrollleuchte prüfen", "Sichtkontrolle, dass beide Scheinwerfer heller und weiter leuchten"],
    "Fernlicht wird über den Lenkstockhebel geschaltet. Die blaue Kontrollleuchte zeigt an, dass es eingeschaltet ist."),
  p("lighting", "Zeigen Sie, wie Sie die Nebelschlussleuchte einschalten, und erklären Sie, wann sie benutzt werden darf.",
    ["Schalter oder Ring am Lichtschalter betätigen", "Gelbe oder orange Kontrollleuchte prüfen", "Nur bei Nebel mit Sichtweite unter 50 Metern", "Dann gilt höchstens 50 km/h"],
    "Die Nebelschlussleuchte blendet stark und darf nur bei Nebel mit weniger als 50 Metern Sicht eingeschaltet werden."),
  p("lighting", "Prüfen Sie die Funktion der Fahrtrichtungsanzeiger.",
    ["Zündung einschalten", "Blinkerhebel nach oben und unten betätigen", "Kontrollleuchte und Taktgeräusch beachten", "Sichtkontrolle vorn, hinten und seitlich", "Schneller Blinktakt weist auf eine defekte Lampe hin"],
    "Blinkt der Fahrtrichtungsanzeiger doppelt so schnell wie üblich, ist in der Regel eine Lampe ausgefallen."),
  p("lighting", "Prüfen Sie das Warnblinklicht.",
    ["Roten Warnblinkschalter drücken", "Alle Blinker müssen gleichzeitig blinken", "Kontrollleuchte im Schalter oder Kombiinstrument", "Funktioniert auch ohne Zündung"],
    "Das Warnblinklicht muss unabhängig von der Zündung funktionieren, damit ein liegen gebliebenes Fahrzeug abgesichert werden kann."),
  p("lighting", "Prüfen Sie die Bremsleuchten.",
    ["Zündung einschalten", "Bremspedal treten", "Zweite Person kontrolliert oder Reflexion an Wand oder Garagentor nutzen", "Alle Bremsleuchten einschließlich der dritten Bremsleuchte müssen leuchten"],
    "Die Bremsleuchten lassen sich nur mit Hilfe einer zweiten Person oder über eine Spiegelung prüfen."),
  p("lighting", "Prüfen Sie den Rückfahrscheinwerfer.",
    ["Zündung einschalten", "Rückwärtsgang einlegen beziehungsweise Wählhebel auf R", "Weißes Licht am Heck prüfen", "Zweite Person oder Spiegelung nutzen"],
    "Der Rückfahrscheinwerfer leuchtet weiß und schaltet sich automatisch mit dem Rückwärtsgang ein."),
  p("lighting", "Prüfen Sie das Standlicht und die Kennzeichenbeleuchtung.",
    ["Lichtschalter auf Standlicht stellen", "Vorn weiße, hinten rote Leuchten prüfen", "Hinteres Kennzeichen muss beleuchtet sein", "Kontrollleuchte im Kombiinstrument"],
    "Standlicht dient dem Kenntlichmachen eines stehenden Fahrzeugs; die Kennzeichenbeleuchtung gehört dazu."),
  p("lighting", "Wie stellen Sie die Leuchtweite ein und wann ist das nötig?",
    ["Rändelrad oder Taste für die Leuchtweitenregulierung im Armaturenbrett", "Bei schwerer Beladung des Kofferraums oder voller Besetzung", "Lichtkegel absenken, damit der Gegenverkehr nicht geblendet wird", "Nach dem Entladen zurückstellen"],
    "Bei Beladung senkt sich das Heck und die Scheinwerfer leuchten höher. Die Leuchtweitenregulierung gleicht das aus."),
  // Reifen
  p("tires", "Prüfen Sie die Profiltiefe der Reifen und nennen Sie die gesetzliche Mindestprofiltiefe.",
    ["Mindestprofiltiefe 1,6 mm", "Prüfung mit Profiltiefenmesser oder an den Verschleißanzeigern (TWI) in den Profilrillen", "Über die gesamte Lauffläche prüfen", "Empfehlung 3 mm bei Sommer- und 4 mm bei Winterreifen"],
    "Die gesetzliche Mindestprofiltiefe beträgt 1,6 mm. Die Verschleißanzeiger im Profil zeigen an, wenn dieser Wert erreicht ist."),
  p("tires", "Worauf achten Sie bei einer Sichtkontrolle der Reifen?",
    ["Beschädigungen wie Risse, Beulen und Schnitte", "Fremdkörper wie Nägel oder Steine", "Gleichmäßige Abnutzung des Profils", "Ausreichende Profiltiefe", "Reifen des gleichen Typs auf einer Achse"],
    "Sichtbare Schäden an der Reifenflanke oder ungleichmäßiger Verschleiß deuten auf Gefahren oder Fahrwerksprobleme hin."),
  p("tires", "Wo finden Sie den richtigen Reifendruck und wie prüfen Sie ihn?",
    ["Betriebsanleitung, Aufkleber im Tankdeckel oder im Türholm", "Bei kalten Reifen prüfen", "Werte für Beladung beachten", "Ventilkappen wieder aufschrauben", "Ersatzrad nicht vergessen"],
    "Der Reifendruck wird bei kalten Reifen geprüft, weil warme Reifen einen zu hohen Wert anzeigen."),
  p("tires", "Welche Folgen hat ein zu niedriger Reifendruck?",
    ["Höherer Kraftstoffverbrauch", "Stärkerer und ungleichmäßiger Reifenverschleiß", "Schlechteres Lenk- und Bremsverhalten", "Gefahr der Überhitzung bis zum Reifenplatzer"],
    "Zu wenig Druck erhöht den Rollwiderstand und lässt den Reifen walken, was ihn erhitzt und beschädigen kann."),
  p("tires", "Woran erkennen Sie einen Winterreifen und wann ist er vorgeschrieben?",
    ["Alpine-Symbol: Bergpiktogramm mit Schneeflocke", "Reine M+S-Kennzeichnung reicht seit dem 1. Oktober 2024 nicht mehr", "Pflicht bei Glatteis, Schneeglätte, Schneematsch, Eis- und Reifglätte", "Empfohlene Profiltiefe mindestens 4 mm"],
    "Bei winterlichen Straßenverhältnissen dürfen nur Reifen mit Alpine-Symbol gefahren werden."),
  p("tires", "Erklären Sie die Reifenkennzeichnung 205/55 R 16 91 V.",
    ["205 = Reifenbreite in Millimetern", "55 = Verhältnis Flankenhöhe zu Breite in Prozent", "R = Radialbauart, 16 = Felgendurchmesser in Zoll", "91 = Tragfähigkeitsindex", "V = Geschwindigkeitsindex"],
    "Die Kennzeichnung auf der Reifenflanke beschreibt Größe, Bauart, Tragfähigkeit und zulässige Höchstgeschwindigkeit des Reifens."),
  // Bremsen
  p("brakes", "Prüfen Sie die Betriebsbremse im Stand.",
    ["Bremspedal treten: Es muss nach kurzem Weg fest stehen", "Pedal darf bei gehaltenem Druck nicht nachgeben", "Bei laufendem Motor sinkt das Pedal durch den Bremskraftverstärker etwas ab", "Bei Fahrtbeginn Bremsprobe bei langsamer Fahrt"],
    "Ein weiches oder durchsinkendes Pedal deutet auf Luft im System oder eine Undichtigkeit hin."),
  p("brakes", "Wie prüfen Sie die Feststellbremse?",
    ["Hebel anziehen oder Taste der elektrischen Feststellbremse betätigen", "Kontrollleuchte im Kombiinstrument prüfen", "Bei Handhebel: nach wenigen Zähnen fester Widerstand", "Fahrzeug muss auch am Gefälle sicher stehen"],
    "Die Feststellbremse sichert das geparkte Fahrzeug gegen Wegrollen und dient als Notbremse bei Ausfall der Betriebsbremse."),
  p("brakes", "Prüfen Sie den Bremskraftverstärker.",
    ["Bei stehendem Motor Bremspedal mehrmals treten, bis es hart wird", "Pedal getreten halten und Motor starten", "Das Pedal muss spürbar nachgeben", "Gibt es nicht nach, arbeitet der Verstärker nicht"],
    "Der Bremskraftverstärker nutzt den Unterdruck des laufenden Motors. Ohne ihn ist eine sehr hohe Pedalkraft nötig."),
  p("brakes", "Was bedeutet es, wenn die Bremsleuchte im Kombiinstrument rot leuchtet?",
    ["Feststellbremse angezogen", "Bremsflüssigkeitsstand zu niedrig", "Störung im Bremssystem", "Sicher anhalten und Ursache klären, nicht weiterfahren"],
    "Die rote Bremswarnleuchte kann mehrere Ursachen haben; leuchtet sie bei gelöster Feststellbremse, ist das Bremssystem zu prüfen."),
  p("brakes", "Was ist die Bremsflüssigkeit und warum muss sie gewechselt werden?",
    ["Überträgt den Pedaldruck hydraulisch auf die Radbremsen", "Nimmt Wasser auf, der Siedepunkt sinkt", "Dampfblasenbildung kann die Bremse ausfallen lassen", "Wechsel nach Herstellervorgabe, meist etwa alle zwei Jahre"],
    "Bremsflüssigkeit ist hygroskopisch. Mit zunehmendem Wasseranteil sinkt der Siedepunkt und die Bremse kann bei Hitze versagen."),
  // Flüssigkeiten
  p("fluids", "Prüfen Sie den Motorölstand.",
    ["Fahrzeug auf ebener Fläche, Motor betriebswarm und einige Minuten abgestellt", "Peilstab herausziehen, abwischen, einstecken und erneut ablesen", "Stand muss zwischen Minimum und Maximum liegen", "Bei Bedarf vorgeschriebenes Öl nachfüllen, nicht überfüllen", "Bei elektronischer Anzeige Menü im Bordcomputer"],
    "Der Ölstand wird auf ebener Fläche bei abgestelltem Motor gemessen, damit das Öl in die Ölwanne zurückgelaufen ist."),
  p("fluids", "Prüfen Sie den Stand der Bremsflüssigkeit.",
    ["Vorratsbehälter im Motorraum, meist vor dem Fahrer", "Stand zwischen Minimum und Maximum ablesen", "Behälter nicht öffnen", "Sinkender Stand deutet auf Belagverschleiß oder Undichtigkeit hin"],
    "Der Bremsflüssigkeitsstand wird am durchsichtigen Behälter von außen abgelesen."),
  p("fluids", "Prüfen Sie den Kühlmittelstand.",
    ["Ausgleichsbehälter im Motorraum", "Bei kaltem Motor prüfen", "Stand zwischen Minimum und Maximum", "Deckel bei heißem Motor nicht öffnen, Verbrühungsgefahr", "Nur vorgeschriebenes Kühlmittel nachfüllen"],
    "Das Kühlsystem steht unter Druck. Der Deckel darf nur bei kaltem Motor geöffnet werden."),
  p("fluids", "Prüfen Sie die Scheibenwaschanlage und füllen Sie sie nach.",
    ["Behälter mit Scheibensymbol im Motorraum", "Wasser mit Reinigungszusatz, im Winter mit Frostschutz", "Funktion der Waschanlage vorn und hinten prüfen", "Wischerblätter auf Beschädigung prüfen"],
    "Eine funktionierende Scheibenwaschanlage ist Voraussetzung für klare Sicht, besonders bei Schmutz und Salz im Winter."),
  p("fluids", "Was bedeutet es, wenn die Kühlmitteltemperaturanzeige in den roten Bereich steigt?",
    ["Motor überhitzt", "Sofort sicher anhalten und Motor abstellen", "Mögliche Ursachen: Kühlmittelmangel, defekter Lüfter, Undichtigkeit", "Motor abkühlen lassen, Deckel nicht sofort öffnen"],
    "Überhitzung kann den Motor schwer beschädigen. Weiterfahren ist nicht zulässig, bis die Ursache behoben ist."),
  // Kontrollleuchten
  p("warning_lights", "Was bedeutet die rote Öldruck-Kontrollleuchte während der Fahrt?",
    ["Kein ausreichender Öldruck, Motor wird nicht mehr geschmiert", "Sofort sicher anhalten und Motor abstellen", "Ölstand prüfen", "Nicht weiterfahren, Pannendienst rufen"],
    "Die Öldruckleuchte zeigt nicht den Ölstand, sondern den Druck an. Ohne Druck droht innerhalb kurzer Zeit ein Motorschaden."),
  p("warning_lights", "Was bedeutet die rote Kontrollleuchte mit dem Batteriesymbol?",
    ["Batterie wird nicht mehr geladen", "Mögliche Ursache: Generator oder Keilriemen defekt", "Fahrzeug fährt nur noch mit Batteriestrom", "Unnötige Verbraucher ausschalten und Werkstatt aufsuchen"],
    "Leuchtet die Ladekontrollleuchte während der Fahrt, lädt der Generator nicht mehr. Das Fahrzeug bleibt nach kurzer Zeit liegen."),
  p("warning_lights", "Was bedeutet die gelbe ABS-Kontrollleuchte?",
    ["Störung im Antiblockiersystem", "Normale Bremse funktioniert weiter, aber ohne ABS", "Räder können bei Vollbremsung blockieren", "Werkstatt aufsuchen"],
    "Bei einer ABS-Störung bleibt die Betriebsbremse erhalten, die Lenkfähigkeit bei Vollbremsung ist aber nicht mehr gesichert."),
  p("warning_lights", "Was bedeutet die gelbe Motorkontrollleuchte?",
    ["Störung in der Motorsteuerung oder Abgasreinigung", "Dauerlicht: baldige Werkstattprüfung", "Blinken: schwere Störung, Leistung reduzieren und Werkstatt aufsuchen", "Fehlerspeicher auslesen lassen"],
    "Die Motorkontrollleuchte weist auf Fehler hin, die Verbrauch, Abgas oder Motorlauf betreffen."),
  p("warning_lights", "Welche Kontrollleuchten müssen nach dem Einschalten der Zündung kurz aufleuchten und wieder erlöschen?",
    ["Airbag", "ABS und ESP", "Motorkontrolle", "Öldruck und Ladekontrolle", "Leuchten sie nach dem Motorstart weiter, liegt eine Störung vor"],
    "Der Selbsttest nach dem Einschalten der Zündung zeigt, dass die Warnleuchten funktionieren. Bleibt eine an, ist die Ursache zu klären."),
  p("warning_lights", "Was bedeutet die Kontrollleuchte für den Reifendruck?",
    ["Druckverlust an mindestens einem Reifen", "Anhalten und Reifen prüfen", "Druck korrigieren und System zurücksetzen", "Bei Beschädigung nicht weiterfahren"],
    "Das Reifendruckkontrollsystem warnt bei Druckverlust. Der Reifen ist zu prüfen, bevor die Fahrt fortgesetzt wird."),
  // Lenkung
  p("steering", "Prüfen Sie das Lenkspiel.",
    ["Motor laufen lassen, Räder in Geradeausstellung", "Lenkrad leicht hin- und herbewegen", "Räder müssen fast ohne Verzögerung mitgehen", "Großes Spiel oder Geräusche deuten auf Verschleiß hin"],
    "Zu großes Lenkspiel bedeutet, dass die Lenkbewegung erst verspätet an den Rädern ankommt."),
  p("steering", "Wie prüfen Sie die Servolenkung?",
    ["Bei stehendem Motor ist die Lenkung schwergängig", "Nach dem Motorstart muss sie leichtgängig sein", "Bei Hydrauliklenkung Stand des Servoöls prüfen", "Bei elektrischer Servolenkung Kontrollleuchte beachten"],
    "Fällt die Servounterstützung aus, bleibt das Fahrzeug lenkbar, aber mit deutlich höherem Kraftaufwand."),
  p("steering", "Was ist zu tun, wenn die Lenkung während der Fahrt schwergängig wird?",
    ["Ruhe bewahren, Fahrzeug bleibt mit mehr Kraft lenkbar", "Warnblinklicht einschalten", "Sicher anhalten", "Ursache prüfen lassen, etwa Keilriemen, Servoöl oder Elektronik"],
    "Ein Ausfall der Servounterstützung ist kein Totalausfall der Lenkung, erfordert aber ein sofortiges kontrolliertes Anhalten."),
  p("steering", "Wie stellen Sie Sitz, Lenkrad und Spiegel richtig ein?",
    ["Sitz so, dass die Pedale voll durchgetreten werden können und das Bein leicht angewinkelt bleibt", "Lenkrad so, dass die Handgelenke bei gestreckten Armen auf dem Lenkradkranz liegen", "Kopfstütze auf Höhe des Hinterkopfs", "Innenspiegel zeigt die ganze Heckscheibe, Außenspiegel zeigen den Fahrbahnrand und wenig Fahrzeugflanke"],
    "Die richtige Sitzposition ist Voraussetzung für sicheres Lenken, Bremsen und die Wirkung von Gurt und Airbag."),
  // Sicherheitsausrüstung
  p("safety_equipment", "Welche Ausrüstung muss im Pkw mitgeführt werden und wo befindet sie sich?",
    ["Warndreieck", "Verbandkasten nach DIN 13164", "Warnweste", "Aufbewahrungsort im Fahrzeug zeigen können"],
    "Warndreieck, Verbandkasten und Warnweste sind Pflicht. Sie müssen im Notfall schnell erreichbar sein."),
  p("safety_equipment", "Wie sichern Sie eine Unfall- oder Pannenstelle ab?",
    ["Warnblinklicht einschalten", "Warnweste vor dem Aussteigen anlegen", "Warndreieck in ausreichender Entfernung aufstellen, Faustregel: innerorts etwa 50 m, Landstraße etwa 100 m, Autobahn 150 bis 200 m", "Mitfahrende in Sicherheit bringen, auf der Autobahn hinter die Schutzplanke"],
    "Die Absicherung schützt Helfer und nachfolgenden Verkehr. Auf der Autobahn ist die Entfernung wegen der hohen Geschwindigkeiten größer."),
  p("safety_equipment", "Wie prüfen Sie den Sicherheitsgurt?",
    ["Gurt muss sich leicht ausziehen lassen", "Bei ruckartigem Ziehen muss er blockieren", "Gurtschloss muss hörbar einrasten", "Gurtband auf Beschädigungen prüfen", "Gurt darf nicht verdreht sein"],
    "Der Gurt schützt nur, wenn er bei plötzlicher Verzögerung sofort blockiert und unbeschädigt ist."),
  p("safety_equipment", "Wie stellen Sie die Kopfstütze richtig ein?",
    ["Oberkante der Kopfstütze etwa auf Höhe der Oberkante des Kopfes", "Abstand zum Hinterkopf möglichst gering", "Verhindert Verletzungen der Halswirbelsäule beim Auffahrunfall", "Auch für Mitfahrende einstellen"],
    "Eine zu niedrige Kopfstütze schützt nicht vor dem Schleudertrauma beim Auffahrunfall."),
  p("safety_equipment", "Wann und wie deaktivieren Sie den Beifahrerairbag?",
    ["Bei rückwärtsgerichtetem Kindersitz auf dem Beifahrersitz", "Schlüsselschalter meist im Handschuhfach oder an der Beifahrertür", "Kontrollleuchte PASSENGER AIRBAG OFF beachten", "Nach dem Ausbau des Kindersitzes wieder aktivieren"],
    "Ein auslösender Frontairbag kann für ein Kind in einer rückwärtsgerichteten Schale tödlich sein."),
  // Allgemein
  p("general", "Öffnen Sie die Motorhaube und benennen Sie die wichtigsten Bauteile.",
    ["Entriegelung im Fußraum oder unter dem Armaturenbrett", "Sicherungshebel an der Haubenvorderkante", "Haube abstützen oder Gasdruckdämpfer", "Ölpeilstab, Öleinfüllstutzen, Kühlmittelbehälter, Bremsflüssigkeitsbehälter, Scheibenwaschbehälter, Batterie zeigen"],
    "Der Prüfer erwartet, dass die Bauteile für die Sicherheitskontrollen ohne Suchen gefunden werden."),
  p("general", "Prüfen Sie die Scheibenwischer und die Hupe.",
    ["Wischer in allen Stufen einschalten", "Wischerblätter auf Schlieren und Beschädigungen prüfen", "Heckwischer prüfen", "Hupe kurz betätigen"],
    "Wischer und Hupe gehören zu den Sicherheitseinrichtungen, die vor Fahrtantritt funktionieren müssen."),
  p("general", "Wo finden Sie die Angaben zur zulässigen Gesamtmasse und Anhängelast?",
    ["Zulassungsbescheinigung Teil I", "Typschild am Fahrzeug, meist im Türholm oder Motorraum", "Betriebsanleitung", "Gebremste und ungebremste Anhängelast unterscheiden"],
    "Die Zulassungsbescheinigung Teil I enthält die technischen Daten, die auch für die Frage nach der Klasse B relevant sind."),
  p("general", "Was prüfen Sie vor Fahrtantritt bei einem Rundgang um das Fahrzeug?",
    ["Reifen und Räder auf Schäden und Druck", "Beleuchtung und Kennzeichen sauber und unbeschädigt", "Scheiben und Spiegel sauber", "Keine Flüssigkeiten unter dem Fahrzeug", "Ladung und Türen gesichert"],
    "Der kurze Rundgang erkennt viele Mängel, bevor sie unterwegs gefährlich werden."),
  p("general", "Welche Fahrzeugpapiere müssen Sie mitführen?",
    ["Führerschein", "Zulassungsbescheinigung Teil I", "Bei Anhänger dessen Zulassungsbescheinigung", "Zulassungsbescheinigung Teil II bleibt zu Hause"],
    "Führerschein und Zulassungsbescheinigung Teil I müssen auf Verlangen vorgezeigt werden."),
];
