// Übungsfragen zum Thema "alkohol_drogen" (eigene Formulierungen, kein amtlicher Prüfungsinhalt).
import type { Question } from "../types";
import { q, t, f } from "./_helpers";

export const alkoholDrogen: readonly Question[] = [
  q({
    code: "own-alkohol_drogen-001", topic: "alkohol_drogen", points: 3, difficulty: 0.2, tags: ["alkohol", "promille", "ordnungswidrigkeit"],
    text: "Ab welcher Blutalkoholkonzentration liegt beim Führen eines Kraftfahrzeugs eine Ordnungswidrigkeit vor, auch ohne Ausfallerscheinungen?",
    answers: [t("Ab 0,5 Promille"), f("Ab 0,8 Promille", "Diese Grenze galt früher; heute liegt sie niedriger."), f("Ab 1,1 Promille", "Ab 1,1 Promille liegt bereits eine Straftat vor.")],
    explanation: "Ab 0,5 Promille handelt ordnungswidrig, wer ein Kraftfahrzeug führt, auch ohne Fahrfehler. Es drohen Bußgeld, Punkte und Fahrverbot.",
    legalReference: "§ 24a StVG",
  }),
  q({
    code: "own-alkohol_drogen-002", topic: "alkohol_drogen", points: 3, difficulty: 0.2, tags: ["alkohol", "probezeit", "fahranfaenger"],
    text: "Welche Alkoholgrenze gilt für Fahranfänger in der Probezeit und für Fahrer unter 21 Jahren?",
    answers: [t("0,0 Promille, also absolutes Alkoholverbot"), f("0,3 Promille", "Für diese Gruppe gilt ein vollständiges Verbot."), f("0,5 Promille wie für alle anderen", "Fahranfänger unterliegen einer strengeren Regel.")],
    explanation: "In der Probezeit und bis zum 21. Geburtstag gilt ein absolutes Alkoholverbot am Steuer. Verstöße kosten Bußgeld, einen Punkt und verlängern die Probezeit.",
    legalReference: "§ 24c StVG",
  }),
  q({
    code: "own-alkohol_drogen-003", topic: "alkohol_drogen", points: 3, difficulty: 0.3, tags: ["alkohol", "straftat", "fahruntuechtigkeit"],
    text: "Ab welcher Blutalkoholkonzentration gilt ein Kraftfahrer als absolut fahruntüchtig?",
    answers: [t("Ab 1,1 Promille"), f("Ab 0,5 Promille", "Ab 0,5 Promille liegt eine Ordnungswidrigkeit vor, absolute Fahruntüchtigkeit beginnt höher."), f("Ab 1,6 Promille", "Ab 1,6 Promille wird zusätzlich eine medizinisch-psychologische Untersuchung angeordnet.")],
    explanation: "Ab 1,1 Promille gilt ein Kraftfahrer unabhängig von Ausfallerscheinungen als absolut fahruntüchtig. Das ist eine Straftat mit Entzug der Fahrerlaubnis.",
    legalReference: "§ 316 StGB",
  }),
  q({
    code: "own-alkohol_drogen-004", topic: "alkohol_drogen", points: 3, difficulty: 0.4, tags: ["alkohol", "straftat", "relative_fahruntuechtigkeit"],
    text: "Ein Fahrer hat 0,4 Promille und fährt in Schlangenlinien. Wie wird das bewertet?",
    answers: [t("Als Straftat wegen relativer Fahruntüchtigkeit, da ab 0,3 Promille mit Ausfallerscheinungen"), f("Gar nicht, weil 0,5 Promille nicht erreicht sind", "Mit Ausfallerscheinungen beginnt die Strafbarkeit bereits ab 0,3 Promille."), f("Nur als Ordnungswidrigkeit", "Ausfallerscheinungen machen daraus eine Straftat.")],
    explanation: "Schon ab 0,3 Promille kann eine Straftat vorliegen, wenn alkoholbedingte Ausfallerscheinungen wie Schlangenlinien oder ein Unfall hinzukommen.",
    legalReference: "§ 316 StGB",
  }),
  q({
    code: "own-alkohol_drogen-005", topic: "alkohol_drogen", points: 2, difficulty: 0.3, tags: ["alkohol", "abbau"],
    text: "Wie schnell baut der Körper Alkohol ab?",
    answers: [t("Etwa 0,1 Promille pro Stunde; der Abbau lässt sich nicht beschleunigen"), f("Etwa 0,5 Promille pro Stunde", "Der Abbau ist deutlich langsamer."), f("Kaffee und kalte Duschen beschleunigen den Abbau deutlich", "Sie machen höchstens wacher, senken aber die Konzentration nicht.")],
    explanation: "Der Körper baut nur etwa 0,1 Promille pro Stunde ab. Kaffee, Schlaf oder Bewegung ändern daran nichts; nur Zeit hilft.",
  }),
  q({
    code: "own-alkohol_drogen-006", topic: "alkohol_drogen", points: 3, difficulty: 0.3, tags: ["alkohol", "restalkohol"],
    text: "Sie haben bis 2 Uhr nachts reichlich Alkohol getrunken und wollen um 7 Uhr zur Arbeit fahren. Was gilt?",
    answers: [t("Mit Restalkohol muss gerechnet werden; die Fahrt ist möglicherweise nicht erlaubt"), f("Nach fünf Stunden Schlaf ist der Alkohol sicher abgebaut", "Bei etwa 0,1 Promille Abbau pro Stunde können noch erhebliche Werte vorliegen."), f("Ein kräftiges Frühstück neutralisiert den Alkohol", "Essen beschleunigt den Abbau nicht.")],
    explanation: "Restalkohol ist eine häufige Ursache für Unfälle am Morgen. Wer spät und viel getrunken hat, kann am nächsten Vormittag noch über der Grenze liegen.",
  }),
  q({
    code: "own-alkohol_drogen-007", topic: "alkohol_drogen", points: 3, difficulty: 0.5, tags: ["cannabis", "thc", "drogen"],
    text: "Was gilt seit 2024 für Cannabis im Straßenverkehr?",
    answers: [t("Ab 3,5 Nanogramm THC pro Milliliter Blutserum liegt eine Ordnungswidrigkeit vor"), t("Für Fahranfänger in der Probezeit und Fahrer unter 21 Jahren gilt ein vollständiges Cannabisverbot am Steuer"), t("Wer mit 3,5 ng/ml THC oder mehr fährt und zusätzlich Alkohol getrunken hat, wird wegen Mischkonsums deutlich strenger geahndet"), f("Cannabis ist am Steuer seit der Legalisierung ohne Grenzwert erlaubt", "Es gibt einen festen Grenzwert und strenge Regeln für Fahranfänger.")],
    explanation: "Für THC gilt seit August 2024 ein Grenzwert von 3,5 ng/ml im Blutserum. Für Fahranfänger in der Probezeit und unter 21-Jährige gilt ein vollständiges Cannabisverbot am Steuer. Wer den THC-Grenzwert erreicht und zugleich Alkohol getrunken hat, wird wegen Mischkonsums mit einem höheren Bußgeld belegt.",
    legalReference: "§ 24a Abs. 1a StVG; § 24c StVG",
  }),
  q({
    code: "own-alkohol_drogen-008", topic: "alkohol_drogen", points: 2, difficulty: 0.2, tags: ["medikamente"],
    text: "Sie nehmen ein neues, rezeptfreies Medikament gegen Erkältung. Was sollten Sie beachten?",
    answers: [t("Beipackzettel lesen und im Zweifel Arzt oder Apotheke fragen, ob die Fahrtüchtigkeit beeinträchtigt wird"), f("Rezeptfreie Medikamente beeinträchtigen die Fahrtüchtigkeit nie", "Auch frei verkäufliche Mittel können müde machen oder die Reaktion verlangsamen."), f("Nur verschreibungspflichtige Medikamente sind relevant", "Die Verschreibungspflicht sagt nichts über die Wirkung auf das Fahren aus.")],
    explanation: "Viele Medikamente, auch rezeptfreie, wirken sich auf Aufmerksamkeit und Reaktionsvermögen aus. Wer unter Medikamenteneinfluss fahruntüchtig ist, macht sich strafbar.",
    legalReference: "§ 316 StGB; § 24a StVG",
  }),
  q({
    code: "own-alkohol_drogen-009", topic: "alkohol_drogen", points: 3, difficulty: 0.2, tags: ["alkohol", "wirkung"],
    text: "Wie wirkt sich Alkohol auf das Fahren aus?",
    answers: [t("Die Reaktionszeit verlängert sich"), t("Die Risikobereitschaft steigt"), t("Das Blickfeld verengt sich (Tunnelblick)"), f("Die Konzentration nimmt zu", "Alkohol senkt die Konzentrationsfähigkeit.")],
    explanation: "Alkohol verlängert die Reaktionszeit, engt das Sehfeld ein und lässt Gefahren kleiner erscheinen. Gleichzeitig steigt die Bereitschaft zu riskantem Verhalten.",
  }),
  q({
    code: "own-alkohol_drogen-010", topic: "alkohol_drogen", points: 2, difficulty: 0.4, tags: ["alkohol", "mpu"],
    text: "Ab welcher Blutalkoholkonzentration wird bei einer Trunkenheitsfahrt in der Regel eine medizinisch-psychologische Untersuchung (MPU) angeordnet?",
    answers: [t("Ab 1,6 Promille"), f("Ab 0,5 Promille", "Bei 0,5 Promille gibt es Bußgeld, Punkte und Fahrverbot, aber in der Regel keine MPU."), f("Ab 2,5 Promille", "Die MPU wird bereits bei niedrigeren Werten angeordnet.")],
    explanation: "Ab 1,6 Promille geht die Behörde von einem Alkoholproblem aus und ordnet vor der Neuerteilung der Fahrerlaubnis eine MPU an.",
    legalReference: "§ 13 FeV",
  }),
  q({
    code: "own-alkohol_drogen-011", topic: "alkohol_drogen", points: 2, difficulty: 0.4, tags: ["alkohol", "fahrrad"],
    text: "Ab welcher Blutalkoholkonzentration gelten Radfahrer als absolut fahruntüchtig?",
    answers: [t("Ab 1,6 Promille"), f("Ab 0,5 Promille", "Diese Grenze gilt für Kraftfahrzeuge."), f("Für Radfahrer gibt es keine Grenze", "Auch Radfahrer können sich strafbar machen und ihre Fahrerlaubnis verlieren.")],
    explanation: "Radfahrer gelten ab 1,6 Promille als absolut fahruntüchtig. Eine Trunkenheitsfahrt mit dem Rad kann zur MPU und zum Verlust der Pkw-Fahrerlaubnis führen.",
    legalReference: "§ 316 StGB",
  }),
  q({
    code: "own-alkohol_drogen-012", topic: "alkohol_drogen", points: 4, difficulty: 0.7, tags: ["alkohol", "promille", "bussgeld", "fahrverbot"],
    text: "Ein Fahrer wird erstmals mit 0,6 Promille ohne Ausfallerscheinungen kontrolliert. Welche Folgen hat das in der Regel?",
    answers: [t("Bußgeld von 500 Euro"), t("Ein Monat Fahrverbot"), t("Zwei Punkte im Fahreignungsregister"), f("Entziehung der Fahrerlaubnis mit Sperrfrist", "Die Entziehung ist Folge einer Straftat; hier liegt eine Ordnungswidrigkeit vor.")],
    explanation: "Ab 0,5 Promille ohne Ausfallerscheinungen liegt eine Ordnungswidrigkeit vor. Beim ersten Verstoß drohen 500 Euro Bußgeld, ein Monat Fahrverbot und zwei Punkte. Wiederholungen werden mit höheren Bußgeldern und drei Monaten Fahrverbot geahndet.",
    legalReference: "§ 24a Abs. 1 StVG; § 25 StVG; BKatV",
  }),
  q({
    code: "own-alkohol_drogen-013", topic: "alkohol_drogen", points: 4, difficulty: 0.7, tags: ["alkohol", "straftat", "entziehung", "sperrfrist"],
    text: "Ein Fahrer wird mit 1,2 Promille angehalten, ohne einen Unfall verursacht zu haben. Welche Folgen hat das?",
    answers: [t("Es liegt eine Straftat wegen Trunkenheit im Verkehr vor"), t("In der Regel wird die Fahrerlaubnis entzogen und eine Sperrfrist für die Neuerteilung festgesetzt"), f("Es handelt sich um eine Ordnungswidrigkeit mit Bußgeld und Fahrverbot", "Ab 1,1 Promille liegt absolute Fahruntüchtigkeit und damit eine Straftat vor."), f("Ohne Unfall bleibt die Fahrt folgenlos", "Die Trunkenheitsfahrt ist auch ohne Unfall strafbar.")],
    explanation: "Ab 1,1 Promille gilt ein Kraftfahrer als absolut fahruntüchtig. Das Gericht verhängt eine Geld- oder Freiheitsstrafe, entzieht in der Regel die Fahrerlaubnis und setzt eine Sperrfrist von mindestens sechs Monaten fest, vor deren Ablauf keine neue Fahrerlaubnis erteilt werden darf.",
    legalReference: "§ 316 StGB; § 69 und § 69a StGB",
  }),
  q({
    code: "own-alkohol_drogen-014", topic: "alkohol_drogen", points: 4, difficulty: 0.7, tags: ["alkohol", "probezeit", "fahranfaenger", "aufbauseminar"],
    text: "Eine Fahranfängerin in der Probezeit fährt mit 0,2 Promille. Welche Folgen hat das?",
    answers: [t("Bußgeld und ein Punkt wegen Verstoßes gegen das Alkoholverbot für Fahranfänger"), t("Anordnung eines Aufbauseminars"), t("Verlängerung der Probezeit von zwei auf vier Jahre"), f("Keine Folgen, weil 0,5 Promille nicht erreicht sind", "In der Probezeit und unter 21 Jahren gilt ein absolutes Alkoholverbot.")],
    explanation: "Für Fahranfänger in der Probezeit und unter 21 Jahren gilt die Null-Promille-Grenze. Ein Verstoß ist ein schwerwiegender Verstoß: Er kostet Bußgeld und einen Punkt, führt zur Anordnung eines Aufbauseminars und verlängert die Probezeit auf vier Jahre.",
    legalReference: "§ 24c StVG; § 2a StVG",
  }),
  q({
    code: "own-alkohol_drogen-015", topic: "alkohol_drogen", points: 3, difficulty: 0.6, tags: ["alkohol", "atemalkohol", "kontrolle"], kind: "numeric", numericAnswer: 0.25, tolerance: 0, unit: "mg/l",
    text: "Welcher Atemalkoholkonzentration entspricht die Grenze von 0,5 Promille Blutalkohol? Angabe in Milligramm je Liter Atemluft.",
    answers: [],
    explanation: "Die 0,5-Promille-Grenze entspricht 0,25 Milligramm Alkohol je Liter Atemluft. Das Gesetz nennt beide Werte nebeneinander, sodass eine beweissichere Atemalkoholmessung für die Ordnungswidrigkeit ausreicht.",
    legalReference: "§ 24a Abs. 1 StVG",
  }),
  q({
    code: "own-alkohol_drogen-016", topic: "alkohol_drogen", points: 3, difficulty: 0.6, tags: ["alkohol", "kontrolle", "blutprobe", "atemtest"],
    text: "Bei einer Verkehrskontrolle bittet die Polizei Sie, in ein Atemalkoholtestgerät zu blasen. Was gilt?",
    answers: [t("Der Atemtest vor Ort ist freiwillig; Sie dürfen ihn ablehnen"), t("Bei Verdacht kann die Polizei eine Blutentnahme anordnen, die Sie nicht verweigern können"), f("Wer den Atemtest verweigert, verliert automatisch die Fahrerlaubnis", "Die Verweigerung allein hat keine Sanktion; sie führt aber häufig zur Blutentnahme."), f("Eine Blutentnahme ist nur mit Ihrer Zustimmung erlaubt", "Die Blutentnahme kann bei Verdacht angeordnet und auch gegen den Willen durchgeführt werden.")],
    explanation: "Der Atemalkoholtest ist eine freiwillige Mitwirkung. Verweigert man ihn, kann bei entsprechendem Verdacht eine Blutentnahme angeordnet werden, die von einem Arzt durchgeführt wird und nicht verweigert werden kann.",
    legalReference: "§ 81a StPO; § 24a StVG",
  }),
  q({
    code: "own-alkohol_drogen-017", topic: "alkohol_drogen", points: 3, difficulty: 0.65, tags: ["alkohol", "e_scooter", "elektrokleinstfahrzeug"],
    text: "Sie fahren nach zwei Bier mit einem E-Tretroller (Elektrokleinstfahrzeug) nach Hause. Welche Regeln gelten?",
    answers: [t("Die gleichen Alkoholgrenzen wie für Autofahrer, weil der E-Tretroller ein Kraftfahrzeug ist"), t("In der Probezeit und unter 21 Jahren gilt auch auf dem E-Tretroller das absolute Alkoholverbot"), f("Die Grenze für Radfahrer von 1,6 Promille", "Elektrokleinstfahrzeuge sind Kraftfahrzeuge, keine Fahrräder."), f("Keine Grenze, weil kein Führerschein nötig ist", "Auch ohne Fahrerlaubnispflicht gelten die Alkoholvorschriften für Kraftfahrzeuge.")],
    explanation: "E-Tretroller sind Kraftfahrzeuge. Deshalb gelten die 0,5-Promille-Grenze, die Straftatgrenzen ab 0,3 Promille mit Ausfallerscheinungen und 1,1 Promille sowie das Alkoholverbot für Fahranfänger. Eine Trunkenheitsfahrt auf dem E-Tretroller kann zum Entzug der Pkw-Fahrerlaubnis führen.",
    legalReference: "§ 24a und § 24c StVG; § 316 StGB; § 1 eKFV",
  }),
  q({
    code: "own-alkohol_drogen-018", topic: "alkohol_drogen", points: 3, difficulty: 0.6, tags: ["drogen", "ordnungswidrigkeit", "nachweis"],
    text: "Ein Fahrer hat am Vorabend Kokain konsumiert und fährt am nächsten Tag ohne erkennbare Ausfallerscheinungen. Im Blut wird die Substanz nachgewiesen. Was gilt?",
    answers: [t("Es liegt eine Ordnungswidrigkeit vor, weil für Kokain kein Grenzwert wie bei Alkohol gilt, sondern der Nachweis genügt"), t("Es drohen Bußgeld, Fahrverbot und Punkte; zudem prüft die Fahrerlaubnisbehörde die Fahreignung"), f("Ohne Ausfallerscheinungen bleibt die Fahrt folgenlos", "Bei den in der Anlage zu § 24a StVG genannten Drogen reicht der Nachweis im Blut."), f("Es gilt der gleiche Grenzwert wie bei Cannabis", "Der Grenzwert von 3,5 ng/ml gilt nur für THC.")],
    explanation: "Für Drogen wie Kokain, Heroin, Amphetamin oder MDMA gibt es keinen Toleranzwert. Wird die Substanz im Blut nachgewiesen, liegt eine Ordnungswidrigkeit mit Bußgeld, Fahrverbot und Punkten vor. Der Konsum harter Drogen führt zudem regelmäßig zur Entziehung der Fahrerlaubnis wegen fehlender Eignung.",
    legalReference: "§ 24a Abs. 2 StVG und Anlage; Anlage 4 FeV",
  }),
  q({
    code: "own-alkohol_drogen-019", topic: "alkohol_drogen", points: 3, difficulty: 0.65, tags: ["cannabis", "thc", "grenzwert", "wirkung"],
    text: "Welche Aussagen zu Cannabis und Fahren treffen zu?",
    answers: [t("THC kann die Reaktionszeit verlängern, die Aufmerksamkeit verringern und die Wahrnehmung von Zeit und Entfernung verzerren"), t("Wer den Grenzwert von 3,5 ng/ml THC erreicht, begeht eine Ordnungswidrigkeit, auch ohne Ausfallerscheinungen"), t("Bei Ausfallerscheinungen kann eine Straftat vorliegen, auch unterhalb des Grenzwerts"), f("Nach dem Rauchen eines Joints ist man nach einer Stunde sicher wieder fahrtüchtig", "Die Wirkung und Nachweisbarkeit halten deutlich länger an; eine feste Wartezeit gibt es nicht.")],
    explanation: "Cannabis beeinträchtigt Konzentration, Reaktion und Wahrnehmung. Der Grenzwert von 3,5 Nanogramm THC je Milliliter Blutserum markiert die Ordnungswidrigkeit; wer darunter liegt, aber Ausfallerscheinungen zeigt, kann sich strafbar machen. Wie lange die Wirkung anhält, ist individuell sehr verschieden.",
    legalReference: "§ 24a Abs. 1a StVG; § 316 StGB",
  }),
  q({
    code: "own-alkohol_drogen-020", topic: "alkohol_drogen", points: 3, difficulty: 0.65, tags: ["medikamente", "verschreibung", "cannabis", "ordnungswidrigkeit"],
    text: "Ein Patient nimmt ein ärztlich verschriebenes Schmerzmittel mit Morphin bestimmungsgemäß ein und fährt Auto. Was gilt?",
    answers: [t("Die Ordnungswidrigkeit nach § 24a StVG gilt nicht, wenn die Substanz aus der bestimmungsgemäßen Einnahme eines für einen konkreten Krankheitsfall verschriebenen Arzneimittels stammt"), t("Zeigt er dennoch Ausfallerscheinungen, kann er sich wegen Trunkenheit im Verkehr strafbar machen"), f("Jede Fahrt unter Morphin ist automatisch eine Straftat", "Bei bestimmungsgemäßer Einnahme ohne Beeinträchtigung ist die Fahrt zulässig."), f("Verschriebene Medikamente beeinträchtigen die Fahrtüchtigkeit nie", "Auch verschriebene Mittel können müde machen oder die Reaktion verlangsamen.")],
    explanation: "Die Ordnungswidrigkeit des Fahrens unter Drogeneinfluss greift nicht, wenn die Substanz aus der bestimmungsgemäßen Einnahme eines verschriebenen Medikaments stammt. Fahrtüchtig muss man trotzdem sein: Wer beeinträchtigt fährt, macht sich strafbar. Arzt und Beipackzettel geben Auskunft.",
    legalReference: "§ 24a Abs. 2 Satz 3 StVG; § 316 StGB",
  }),
  q({
    code: "own-alkohol_drogen-021", topic: "alkohol_drogen", points: 3, difficulty: 0.6, tags: ["alkohol", "restalkohol", "abbau", "rechnen"],
    text: "Um 1 Uhr nachts hat eine Person 1,0 Promille. Sie will um 7 Uhr morgens fahren. Wie ist die Lage nach der Faustregel von 0,1 Promille Abbau pro Stunde?",
    answers: [t("Um 7 Uhr können noch etwa 0,4 Promille vorhanden sein; die Fahrt ist bei Ausfallerscheinungen strafbar und für Fahranfänger ohnehin verboten"), f("Der Alkohol ist nach sechs Stunden Schlaf vollständig abgebaut", "Bei 0,1 Promille pro Stunde bleiben nach sechs Stunden etwa 0,4 Promille."), f("Nach dem Schlafen liegt der Wert unter 0,3 Promille, daher ist die Fahrt für jeden erlaubt", "Der Wert liegt rechnerisch bei etwa 0,4 Promille."), f("Ein Frühstück und Kaffee senken den Wert auf null", "Essen und Kaffee beschleunigen den Abbau nicht.")],
    explanation: "Der Körper baut nur etwa 0,1 Promille pro Stunde ab, im Schlaf nicht schneller. Von 1,0 Promille bleiben nach sechs Stunden rechnerisch 0,4 Promille. Für Fahranfänger ist die Fahrt verboten, für alle anderen bei Ausfallerscheinungen strafbar und in jedem Fall riskant.",
    legalReference: "§ 24c StVG; § 316 StGB",
  }),
  q({
    code: "own-alkohol_drogen-022", topic: "alkohol_drogen", points: 3, difficulty: 0.6, tags: ["alkohol", "wirkung", "individuell"],
    text: "Welche Faktoren beeinflussen, wie hoch die Blutalkoholkonzentration nach dem Trinken derselben Menge ausfällt?",
    answers: [t("Körpergewicht und Geschlecht: leichtere Personen und Frauen erreichen in der Regel höhere Werte"), t("Ob auf leeren Magen getrunken wurde"), t("Müdigkeit, Krankheit und Medikamente verstärken die Wirkung bei gleichem Wert"), f("Die Sorte des Getränks: Bier wirkt grundsätzlich nicht auf die Promille", "Entscheidend ist die aufgenommene Alkoholmenge, auch bei Bier.")],
    explanation: "Die Blutalkoholkonzentration hängt vom Körpergewicht, vom Anteil des Körperwassers, vom Geschlecht und vom Mageninhalt ab. Wie stark sich ein bestimmter Wert auswirkt, wird zusätzlich von Müdigkeit, Krankheit und Medikamenten beeinflusst. Verlässliche Rechenspiele gibt es nicht.",
  }),
  q({
    code: "own-alkohol_drogen-023", topic: "alkohol_drogen", points: 3, difficulty: 0.6, tags: ["alkohol", "fahrrad", "fahrerlaubnis", "mpu"],
    text: "Ein Pkw-Fahrerlaubnisinhaber fährt mit 1,7 Promille Fahrrad und wird kontrolliert. Welche Folgen sind möglich?",
    answers: [t("Strafverfahren wegen Trunkenheit im Verkehr, weil Radfahrer ab 1,6 Promille absolut fahruntüchtig sind"), t("Anordnung einer medizinisch-psychologischen Untersuchung durch die Fahrerlaubnisbehörde"), t("Bei negativem Ergebnis der MPU kann die Pkw-Fahrerlaubnis entzogen werden"), f("Keine Folgen für die Pkw-Fahrerlaubnis, weil kein Kraftfahrzeug geführt wurde", "Die Behörde prüft die Eignung unabhängig vom Fahrzeug.")],
    explanation: "Trunkenheit auf dem Fahrrad ist ab 1,6 Promille eine Straftat. Weil ein solcher Wert auf ein Alkoholproblem hindeutet, ordnet die Fahrerlaubnisbehörde eine MPU an. Wird die Eignung nicht nachgewiesen, kann auch die Fahrerlaubnis für Kraftfahrzeuge entzogen werden.",
    legalReference: "§ 316 StGB; § 13 FeV",
  }),
  q({
    code: "own-alkohol_drogen-024", topic: "alkohol_drogen", points: 3, difficulty: 0.55, tags: ["alkohol", "wirkung", "sehen", "blendung"],
    text: "Wie wirkt sich Alkohol auf das Sehen und Wahrnehmen im Straßenverkehr aus?",
    answers: [t("Das Gesichtsfeld verengt sich, seitliche Gefahren werden später erkannt"), t("Die Blendempfindlichkeit nimmt zu und die Anpassung an Dunkelheit verschlechtert sich"), t("Entfernungen und Geschwindigkeiten werden falsch eingeschätzt"), f("Die Sehschärfe verbessert sich durch die entspannende Wirkung", "Alkohol verschlechtert die Sehleistung in jeder Hinsicht.")],
    explanation: "Schon geringe Mengen Alkohol verengen das Blickfeld, erhöhen die Blendempfindlichkeit und stören das räumliche Sehen. Gefahren werden später erkannt und falsch eingeschätzt, während die Selbsteinschätzung besser wird als die tatsächliche Leistung.",
  }),
  q({
    code: "own-alkohol_drogen-025", topic: "alkohol_drogen", points: 3, difficulty: 0.55, tags: ["drogen", "amphetamin", "wirkung"],
    text: "Welche Wirkungen aufputschender Drogen wie Amphetamin oder Ecstasy sind für das Fahren gefährlich?",
    answers: [t("Selbstüberschätzung und erhöhte Risikobereitschaft"), t("Nachlassen der Wirkung mit plötzlicher Erschöpfung und Sekundenschlaf"), t("Verengte Wahrnehmung und aggressive Fahrweise"), f("Verbesserte Aufmerksamkeit über viele Stunden ohne Nachteile", "Die scheinbare Wachheit täuscht; Konzentration und Urteilsvermögen sind gestört.")],
    explanation: "Aufputschende Drogen erzeugen scheinbare Wachheit und Selbstsicherheit, verschlechtern aber Urteilsvermögen und Wahrnehmung. Wenn die Wirkung nachlässt, drohen Erschöpfung und Sekundenschlaf. Auch hier genügt der Nachweis im Blut für eine Ordnungswidrigkeit.",
    legalReference: "§ 24a Abs. 2 StVG",
  }),
  q({
    code: "own-alkohol_drogen-026", topic: "alkohol_drogen", points: 3, difficulty: 0.6, tags: ["alkohol", "wiederholung", "fahrverbot", "bussgeld"],
    text: "Ein Fahrer wird zum zweiten Mal innerhalb weniger Jahre mit 0,7 Promille ohne Ausfallerscheinungen erwischt. Was gilt?",
    answers: [t("Das Bußgeld ist höher als beim ersten Verstoß und das Fahrverbot beträgt drei Monate"), f("Es gelten dieselben Folgen wie beim ersten Mal", "Wiederholungstäter werden strenger sanktioniert."), f("Beim zweiten Verstoß wird die Fahrerlaubnis immer für mindestens fünf Jahre entzogen", "Der Verstoß bleibt eine Ordnungswidrigkeit; die Behörde kann aber die Eignung prüfen.")],
    explanation: "Wiederholte Alkoholfahrten im Ordnungswidrigkeitenbereich werden mit steigenden Bußgeldern und einem Fahrverbot von drei Monaten geahndet, jeweils mit zwei Punkten. Zudem kann die Fahrerlaubnisbehörde bei wiederholten Verstößen eine MPU anordnen.",
    legalReference: "§ 24a StVG; BKatV; § 13 FeV",
  }),
  q({
    code: "own-alkohol_drogen-027", topic: "alkohol_drogen", points: 3, difficulty: 0.6, tags: ["alkohol", "unfall", "gefaehrdung", "straftat"],
    text: "Ein Fahrer verursacht mit 0,8 Promille einen Unfall mit Sachschaden. Wie wird die Fahrt rechtlich bewertet?",
    answers: [t("Als Straftat, weil ab 0,3 Promille mit alkoholbedingtem Fahrfehler relative Fahruntüchtigkeit vorliegt"), t("Bei Gefährdung anderer kommt Gefährdung des Straßenverkehrs in Betracht, was schwerer wiegt als Trunkenheit im Verkehr"), f("Nur als Ordnungswidrigkeit, weil 1,1 Promille nicht erreicht sind", "Mit Ausfallerscheinungen wie einem Unfall ist die Fahrt ab 0,3 Promille strafbar."), f("Als Ordnungswidrigkeit, weil nur Sachschaden entstand", "Die Art des Schadens ändert nichts an der Fahruntüchtigkeit.")],
    explanation: "Ein alkoholbedingter Unfall ist eine typische Ausfallerscheinung. Ab 0,3 Promille liegt dann relative Fahruntüchtigkeit und damit eine Straftat vor. Wurden Menschen oder fremde Sachen von bedeutendem Wert gefährdet, greift der schwerere Tatbestand der Gefährdung des Straßenverkehrs.",
    legalReference: "§ 316 StGB; § 315c StGB",
  }),
  q({
    code: "own-alkohol_drogen-028", topic: "alkohol_drogen", points: 3, difficulty: 0.6, tags: ["alkohol", "versicherung", "haftung"],
    text: "Welche Folgen kann eine Alkoholfahrt mit Unfall für den Versicherungsschutz haben?",
    answers: [t("Die Kfz-Haftpflichtversicherung zahlt dem Geschädigten, kann aber vom Fahrer einen Teil zurückfordern"), t("Die Kaskoversicherung kann die Leistung für den eigenen Schaden kürzen oder verweigern"), f("Alle Schäden werden ohne Einschränkung übernommen", "Alkohol am Steuer ist eine grobe Pflichtverletzung mit Folgen für den Versicherungsschutz."), f("Die Haftpflichtversicherung lehnt die Zahlung an den Geschädigten vollständig ab", "Der Geschädigte wird geschützt; der Regress richtet sich gegen den Fahrer.")],
    explanation: "Die Haftpflichtversicherung schützt zunächst den Geschädigten, nimmt den alkoholisierten Fahrer aber in Regress. Bei der Kaskoversicherung drohen Kürzung oder Wegfall der Leistung wegen grober Fahrlässigkeit. Dazu kommen Straf- oder Bußgeldverfahren.",
    legalReference: "§ 81 VVG; Kfz-Versicherungsbedingungen",
  }),
  q({
    code: "own-alkohol_drogen-029", topic: "alkohol_drogen", points: 3, difficulty: 0.55, tags: ["alkohol", "party", "planung", "verantwortung"],
    text: "Sie planen, auf einer Feier Alkohol zu trinken. Was ist verantwortungsvoll?",
    answers: [t("Vorher festlegen, wie Sie nach Hause kommen: Fahrgemeinschaft mit nüchternem Fahrer, Taxi oder öffentliche Verkehrsmittel"), t("Das Auto stehen lassen und auch am nächsten Morgen Restalkohol einkalkulieren"), f("Nur so viel trinken, dass Sie sich noch fahrtüchtig fühlen", "Das eigene Gefühl täuscht; Alkohol verbessert die Selbsteinschätzung, nicht die Leistung."), f("Vor der Rückfahrt zwei Stunden Pause machen, dann ist der Alkohol abgebaut", "Zwei Stunden bauen nur etwa 0,2 Promille ab.")],
    explanation: "Die Entscheidung gegen das Fahren fällt am besten vor dem ersten Glas. Wer Alkohol getrunken hat, kann seine Fahrtüchtigkeit nicht mehr zuverlässig beurteilen. Auch am nächsten Morgen ist mit Restalkohol zu rechnen.",
  }),
  q({
    code: "own-alkohol_drogen-030", topic: "alkohol_drogen", points: 3, difficulty: 0.6, tags: ["medikamente", "erkaeltung", "schlafmittel", "wirkung"],
    text: "Welche Medikamentengruppen können die Fahrtüchtigkeit deutlich beeinträchtigen?",
    answers: [t("Schlaf- und Beruhigungsmittel"), t("Starke Schmerzmittel und viele Erkältungs- und Allergiemittel mit müde machenden Wirkstoffen"), t("Manche Mittel gegen Bluthochdruck oder Diabetes, wenn sie zu Schwindel oder Unterzuckerung führen"), f("Vitaminpräparate", "Vitamine beeinträchtigen die Fahrtüchtigkeit nicht.")],
    explanation: "Viele Medikamente machen müde, verlangsamen die Reaktion oder verursachen Schwindel, darunter Schlafmittel, Beruhigungsmittel, starke Schmerzmittel und Antihistaminika in Erkältungs- und Allergiemitteln. Wer unter Medikamenteneinfluss fahruntüchtig ist, macht sich strafbar. Beipackzettel lesen und im Zweifel den Arzt fragen.",
    legalReference: "§ 316 StGB; § 2 FeV",
  }),
  q({
    code: "own-alkohol_drogen-031", topic: "alkohol_drogen", points: 3, difficulty: 0.6, tags: ["alkohol", "mischkonsum", "cannabis", "bussgeld"],
    text: "Ein Fahrer erreicht 3,5 ng/ml THC und hat zusätzlich 0,3 Promille Alkohol im Blut, ohne Ausfallerscheinungen. Was gilt?",
    answers: [t("Es liegt eine Ordnungswidrigkeit vor, die wegen des Mischkonsums mit einem höheren Bußgeld belegt wird als eine reine Cannabisfahrt"), f("Es liegt keine Ordnungswidrigkeit vor, weil 0,5 Promille nicht erreicht sind", "Der THC-Grenzwert ist erreicht; der zusätzliche Alkohol verschärft die Sanktion."), f("Es liegt automatisch eine Straftat vor", "Ohne Ausfallerscheinungen bleibt es eine Ordnungswidrigkeit; sie wird aber strenger geahndet.")],
    explanation: "Wer den THC-Grenzwert erreicht und zusätzlich Alkohol getrunken hat, verstößt gegen das Mischkonsumverbot. Das Gesetz sieht dafür ein deutlich höheres Bußgeld vor als für die reine Cannabisfahrt, dazu Fahrverbot und Punkte. Mit Ausfallerscheinungen wäre die Fahrt strafbar.",
    legalReference: "§ 24a Abs. 1a StVG; BKatV", reviewStatus: "needs_verification",
  }),
  q({
    code: "own-alkohol_drogen-032", topic: "alkohol_drogen", points: 3, difficulty: 0.55, tags: ["drogen", "nachweis", "kontrolle", "speicheltest"],
    text: "Bei einer Kontrolle bietet die Polizei einen Drogenschnelltest mit Speichel oder Urin an. Was gilt?",
    answers: [t("Der Schnelltest ist freiwillig; bei Verdacht kann aber eine Blutentnahme angeordnet werden"), t("Beweiskräftig ist erst die Blutuntersuchung im Labor"), f("Der Schnelltest ist verpflichtend und sein Ergebnis reicht für ein Bußgeld", "Der Schnelltest ist freiwillig und nur ein Vortest."), f("Wird der Schnelltest verweigert, gilt das als Geständnis", "Die Verweigerung hat keine rechtliche Bedeutung als Schuldeingeständnis.")],
    explanation: "Drogenvortests mit Speichel oder Urin sind freiwillige Vortests. Sie ersetzen nicht die Blutuntersuchung, die als Beweismittel dient und bei entsprechendem Verdacht auch ohne Einwilligung angeordnet werden kann.",
    legalReference: "§ 81a StPO; § 24a Abs. 2 StVG",
  }),
  q({
    code: "own-alkohol_drogen-033", topic: "alkohol_drogen", points: 3, difficulty: 0.6, tags: ["alkohol", "mpu", "neuerteilung", "abstinenz"],
    text: "Nach einer Trunkenheitsfahrt mit 1,8 Promille wurde die Fahrerlaubnis entzogen. Was ist für die Neuerteilung erforderlich?",
    answers: [t("Ein positives Gutachten der medizinisch-psychologischen Untersuchung"), t("Die Sperrfrist des Gerichts muss abgelaufen sein; der Antrag kann bereits einige Monate vorher gestellt werden"), f("Nur das erneute Bestehen der theoretischen Prüfung", "Bei 1,6 Promille und mehr ist eine MPU vorgeschrieben."), f("Nichts, nach Ablauf der Sperrfrist lebt die Fahrerlaubnis automatisch wieder auf", "Eine entzogene Fahrerlaubnis muss neu beantragt werden.")],
    explanation: "Ab 1,6 Promille geht die Behörde von einem Alkoholproblem aus und verlangt vor der Neuerteilung eine MPU. Der Antrag kann frühestens einige Monate vor Ablauf der Sperrfrist gestellt werden. Häufig muss zudem eine Abstinenz oder ein kontrollierter Konsum nachgewiesen werden.",
    legalReference: "§ 13 FeV; § 20 FeV; § 69a StGB",
  }),
  q({
    code: "own-alkohol_drogen-034", topic: "alkohol_drogen", points: 3, difficulty: 0.55, tags: ["alkohol", "beifahrer", "verantwortung", "halter"],
    text: "Ihr Freund hat getrunken und will mit Ihrem Auto nach Hause fahren. Was gilt für Sie als Halter?",
    answers: [t("Sie sollten die Fahrt verhindern und ihm die Schlüssel nicht überlassen"), t("Wer als Halter zulässt, dass ein erkennbar fahruntüchtiger Fahrer das Fahrzeug führt, kann strafrechtlich mitverantwortlich sein"), f("Der Fahrer allein trägt jede Verantwortung", "Auch der Halter kann belangt werden, wenn er die Fahrt zulässt."), f("Als Halter dürfen Sie das Fahrzeug jederzeit jedem überlassen", "Der Halter muss sicherstellen, dass der Fahrer geeignet und fahrtüchtig ist.")],
    explanation: "Der Halter darf sein Fahrzeug nicht jemandem überlassen, der erkennbar fahruntüchtig ist. Er kann sich wegen Beihilfe oder Zulassens der Trunkenheitsfahrt strafbar machen und haftet zivilrechtlich mit. Freunde vor einer Alkoholfahrt abzuhalten, ist auch moralisch geboten.",
    legalReference: "§ 316 StGB; § 27 StGB; § 7 StVG",
  }),
  q({
    code: "own-alkohol_drogen-035", topic: "alkohol_drogen", points: 2, difficulty: 0.45, tags: ["alkohol", "promille", "grenzen", "uebersicht"],
    text: "Ordnen Sie zu: Welcher Promillewert markiert für Kraftfahrer die absolute Fahruntüchtigkeit?",
    answers: [t("1,1 Promille"), f("0,5 Promille", "Ab 0,5 Promille liegt eine Ordnungswidrigkeit vor."), f("0,3 Promille", "Ab 0,3 Promille kann mit Ausfallerscheinungen relative Fahruntüchtigkeit vorliegen."), f("1,6 Promille", "Ab 1,6 Promille wird die MPU angeordnet; die absolute Fahruntüchtigkeit beginnt früher.")],
    explanation: "Die wichtigsten Grenzen: 0,0 für Fahranfänger und unter 21-Jährige, ab 0,3 Straftat bei Ausfallerscheinungen, ab 0,5 Ordnungswidrigkeit, ab 1,1 absolute Fahruntüchtigkeit und ab 1,6 MPU sowie absolute Fahruntüchtigkeit für Radfahrer.",
    mnemonic: "0,0 Anfänger, 0,3 mit Fehler, 0,5 Bußgeld, 1,1 Straftat, 1,6 MPU.",
    legalReference: "§ 24a und § 24c StVG; § 316 StGB; § 13 FeV",
  }),
  q({
    code: "own-alkohol_drogen-036", topic: "alkohol_drogen", points: 2, difficulty: 0.4, tags: ["muedigkeit", "wirkung", "alkohol"],
    text: "Warum ist Alkohol in Verbindung mit Müdigkeit besonders gefährlich?",
    answers: [t("Alkohol verstärkt die Müdigkeit und erhöht die Gefahr von Sekundenschlaf erheblich"), f("Müdigkeit hebt die Wirkung von Alkohol auf", "Beides verstärkt sich gegenseitig."), f("Alkohol macht wach und gleicht die Müdigkeit aus", "Die kurze Anregung schlägt schnell in Ermüdung um.")],
    explanation: "Alkohol dämpft das zentrale Nervensystem. Bei ohnehin müden Fahrern verstärkt er die Schläfrigkeit, sodass Sekundenschlaf droht. Auch geringe Mengen sind nach langen Tagen oder in der Nacht besonders riskant.",
  }),
  q({
    code: "own-alkohol_drogen-037", topic: "alkohol_drogen", points: 2, difficulty: 0.4, tags: ["alkohol", "mofa", "fahrerlaubnisfrei"],
    text: "Gelten die Alkoholgrenzen für Kraftfahrer auch für Mofafahrer?",
    answers: [t("Ja, das Mofa ist ein Kraftfahrzeug; es gelten 0,5 Promille und die Straftatgrenzen"), f("Nein, für Mofas gilt wie für Fahrräder 1,6 Promille", "Mofas sind Kraftfahrzeuge."), f("Nein, weil für das Mofa keine Fahrerlaubnis nötig ist", "Die Alkoholregeln hängen vom Fahrzeug ab, nicht von der Fahrerlaubnispflicht.")],
    explanation: "Mofas, E-Tretroller und andere Kraftfahrzeuge unterliegen den Alkoholgrenzen für Kraftfahrer, unabhängig davon, ob eine Fahrerlaubnis erforderlich ist. Nur für Radfahrer liegt die Grenze der absoluten Fahruntüchtigkeit bei 1,6 Promille.",
    legalReference: "§ 24a StVG; § 316 StGB",
  }),
  q({
    code: "own-alkohol_drogen-038", topic: "alkohol_drogen", points: 2, difficulty: 0.35, tags: ["alkohol", "wirkung", "risikobereitschaft"],
    text: "Warum unterschätzen alkoholisierte Fahrer ihre Beeinträchtigung häufig?",
    answers: [t("Alkohol enthemmt, hebt die Stimmung und steigert das Selbstvertrauen, während die Leistungsfähigkeit sinkt"), f("Weil Alkohol die Reaktionsfähigkeit tatsächlich verbessert", "Die Reaktionszeit verlängert sich."), f("Weil die Wirkung erst nach dem Aussteigen einsetzt", "Die Wirkung setzt schon während des Trinkens ein.")],
    explanation: "Die enthemmende Wirkung des Alkohols führt dazu, dass sich Betroffene fit und sicher fühlen, obwohl Reaktion, Wahrnehmung und Urteilsvermögen bereits eingeschränkt sind. Diese Schere zwischen Gefühl und Leistung macht Alkohol am Steuer so gefährlich.",
  }),
  q({
    code: "own-alkohol_drogen-039", topic: "alkohol_drogen", points: 2, difficulty: 0.4, tags: ["cannabis", "probezeit", "fahranfaenger"],
    text: "Was gilt für Cannabis bei Fahranfängern in der Probezeit und unter 21 Jahren?",
    answers: [t("Es gilt ein vollständiges Cannabisverbot am Steuer, unabhängig vom Grenzwert von 3,5 ng/ml"), f("Es gilt der allgemeine Grenzwert von 3,5 ng/ml", "Für diese Gruppe gilt ein absolutes Verbot."), f("Cannabis ist für Fahranfänger nur nachts verboten", "Das Verbot gilt zu jeder Tageszeit.")],
    explanation: "Ähnlich dem Alkoholverbot gilt für Fahranfänger in der Probezeit und unter 21 Jahren ein vollständiges Verbot, unter der Wirkung von Cannabis zu fahren. Ein Verstoß kostet Bußgeld und einen Punkt und verlängert die Probezeit.",
    legalReference: "§ 24c StVG",
  }),
  q({
    code: "own-alkohol_drogen-040", topic: "alkohol_drogen", points: 2, difficulty: 0.4, tags: ["drogen", "fahreignung", "entziehung"],
    text: "Ein Fahrerlaubnisinhaber konsumiert regelmäßig Amphetamin, ohne jemals unter Einfluss gefahren zu sein. Kann das Folgen für die Fahrerlaubnis haben?",
    answers: [t("Ja, der Konsum harter Drogen schließt die Fahreignung in der Regel aus, sodass die Behörde die Fahrerlaubnis entziehen kann"), f("Nein, entscheidend ist nur das Fahren unter Einfluss", "Die Eignung betrifft die Person, nicht nur die einzelne Fahrt."), f("Nur, wenn ein Gericht eine Straftat feststellt", "Die Fahrerlaubnisbehörde prüft die Eignung unabhängig von einem Strafverfahren.")],
    explanation: "Wer sogenannte harte Drogen wie Amphetamin, Kokain oder Heroin konsumiert, ist nach der Fahrerlaubnis-Verordnung in der Regel nicht geeignet, Kraftfahrzeuge zu führen. Die Behörde kann die Fahrerlaubnis auch ohne eine Drogenfahrt entziehen.",
    legalReference: "§ 46 FeV; Anlage 4 FeV",
  }),
  q({
    code: "own-alkohol_drogen-041", topic: "alkohol_drogen", points: 3, difficulty: 0.5, tags: ["alkohol", "abbau", "rechnen"], kind: "numeric", numericAnswer: 8, tolerance: 0, unit: "Stunden",
    text: "Eine Person hat 0,8 Promille. Wie viele Stunden dauert es nach der Faustregel von 0,1 Promille Abbau pro Stunde mindestens, bis der Alkohol vollständig abgebaut ist?",
    answers: [],
    explanation: "Bei einem Abbau von etwa 0,1 Promille pro Stunde dauert der Abbau von 0,8 Promille mindestens acht Stunden. Der Abbau beginnt zudem erst mit Verzögerung und lässt sich weder durch Schlaf noch durch Kaffee beschleunigen.",
  }),
];
