// Übungsfragen zum Thema "andere_teilnehmer" (eigene Formulierungen, kein amtlicher Prüfungsinhalt).
import type { Question } from "../types";
import { q, t, f } from "./_helpers";

export const andereTeilnehmer: readonly Question[] = [
  q({
    code: "own-andere_teilnehmer-001", topic: "andere_teilnehmer", points: 3, difficulty: 0.2, tags: ["radverkehr", "ueberholen", "innerorts", "ausserorts"],
    text: "Welchen seitlichen Mindestabstand müssen Sie beim Überholen von Radfahrenden einhalten?",
    answers: [t("Innerorts 1,5 Meter und außerorts 2 Meter"), f("Innerorts 1 Meter und außerorts 1,5 Meter", "Die vorgeschriebenen Abstände sind größer."), f("Es gibt keinen festen Mindestabstand", "Seit 2020 sind feste Mindestabstände vorgeschrieben.")],
    explanation: "Beim Überholen von Radfahrenden, zu Fuß Gehenden und Elektrokleinstfahrzeugen gilt ein seitlicher Mindestabstand von 1,5 Metern innerorts und 2 Metern außerorts.",
    legalReference: "§ 5 Abs. 4 StVO",
  }),
  q({
    code: "own-andere_teilnehmer-002", topic: "andere_teilnehmer", points: 4, difficulty: 0.3, tags: ["fussgaengerueberweg", "zebrastreifen", "halten"],
    text: "Ein Fußgänger steht am Zebrastreifen und will erkennbar die Straße überqueren. Was gilt?",
    answers: [t("Sie müssen dem Fußgänger das Überqueren ermöglichen, notfalls anhalten"), t("Am Fußgängerüberweg dürfen Sie nicht überholen"), f("Sie dürfen hupen, damit der Fußgänger wartet", "Fußgänger haben am Zebrastreifen Vorrang.")],
    explanation: "Am Fußgängerüberweg haben Fußgänger, die ihn erkennbar benutzen wollen, Vorrang. Fahrzeuge dürfen sich nur mit mäßiger Geschwindigkeit nähern und müssen nötigenfalls warten; Überholen ist dort verboten.",
    legalReference: "§ 26 StVO",
  }),
  q({
    code: "own-andere_teilnehmer-003", topic: "andere_teilnehmer", points: 3, difficulty: 0.3, tags: ["linienbus", "warnblinklicht", "haltestelle"],
    text: "Ein Linienbus steht mit eingeschaltetem Warnblinklicht an einer Haltestelle. Was gilt?",
    answers: [t("Sie dürfen nur mit Schrittgeschwindigkeit und mit ausreichendem Abstand vorbeifahren"), t("Das gilt auch für den Gegenverkehr"), f("Sie dürfen normal weiterfahren, das Warnblinklicht betrifft nur den nachfolgenden Verkehr", "Das Warnblinklicht verpflichtet beide Richtungen zur Schrittgeschwindigkeit.")],
    explanation: "Steht ein Bus mit Warnblinklicht an der Haltestelle, darf nur mit Schrittgeschwindigkeit und so vorbeigefahren werden, dass Fahrgäste nicht gefährdet werden. Nähert sich der Bus mit Warnblinklicht der Haltestelle, darf er nicht überholt werden.",
    legalReference: "§ 20 Abs. 4 StVO",
  }),
  q({
    code: "own-andere_teilnehmer-004", topic: "andere_teilnehmer", points: 3, difficulty: 0.3, tags: ["linienbus", "haltestelle", "innerorts"],
    text: "Ein Linienbus blinkt links und will innerorts von der Haltestelle abfahren. Wie verhalten Sie sich?",
    answers: [t("Dem Bus das Abfahren ermöglichen, notfalls warten"), f("Zügig vorbeifahren, weil Sie Vorrang haben", "Innerorts müssen Linienbusse beim Abfahren von Haltestellen durchgelassen werden."), f("Hupen, damit der Bus wartet", "Der Bus darf abfahren; Hupen ist hier unzulässig.")],
    explanation: "Innerhalb geschlossener Ortschaften ist Linienbussen und Schulbussen das Abfahren von gekennzeichneten Haltestellen zu ermöglichen. Wenn nötig, muss man warten.",
    legalReference: "§ 20 Abs. 5 StVO",
  }),
  q({
    code: "own-andere_teilnehmer-005", topic: "andere_teilnehmer", points: 3, difficulty: 0.2, tags: ["kinder", "innerorts", "bremsbereitschaft"],
    text: "Am Fahrbahnrand spielen Kinder mit einem Ball. Wie verhalten Sie sich?",
    answers: [t("Geschwindigkeit deutlich verringern, bremsbereit sein und mit plötzlichem Betreten der Fahrbahn rechnen"), f("Hupen und mit unveränderter Geschwindigkeit weiterfahren", "Kinder reagieren auf Hupen oft unvorhersehbar."), f("Auf die Gegenfahrbahn ausweichen und normal weiterfahren", "Das schafft neue Gefahren und löst das Problem nicht.")],
    explanation: "Kinder handeln spontan und können Geschwindigkeiten schlecht einschätzen. Gegenüber Kindern, Hilfsbedürftigen und älteren Menschen ist besondere Rücksicht durch geringere Geschwindigkeit und Bremsbereitschaft Pflicht.",
    legalReference: "§ 3 Abs. 2a StVO",
  }),
  q({
    code: "own-andere_teilnehmer-006", topic: "andere_teilnehmer", points: 2, difficulty: 0.3, tags: ["e_scooter", "elektrokleinstfahrzeuge"],
    text: "Welche Regeln gelten für E-Scooter (Elektrokleinstfahrzeuge)?",
    answers: [t("Sie dürfen ab 14 Jahren gefahren werden"), t("Die bauartbedingte Höchstgeschwindigkeit beträgt 20 km/h"), t("Sie müssen Radwege benutzen, wenn vorhanden, sonst die Fahrbahn"), f("Es besteht Helmpflicht", "Ein Helm ist empfohlen, aber nicht vorgeschrieben.")],
    explanation: "E-Scooter dürfen ab 14 Jahren gefahren werden, sind auf 20 km/h begrenzt und gehören auf Radwege oder die Fahrbahn, nicht auf den Gehweg. Eine Helmpflicht besteht nicht, Mitfahrer sind verboten.",
    legalReference: "Elektrokleinstfahrzeuge-Verordnung (eKFV)",
  }),
  q({
    code: "own-andere_teilnehmer-007", topic: "andere_teilnehmer", points: 2, difficulty: 0.4, tags: ["lkw", "rechtsabbiegen", "innerorts", "radverkehr"],
    text: "Ein Lkw über 3,5 t biegt innerorts rechts ab, Radverkehr ist zu erwarten. Wie schnell darf er dabei höchstens fahren?",
    answers: [t("Schrittgeschwindigkeit"), f("30 km/h", "Die vorgeschriebene Geschwindigkeit ist deutlich niedriger."), f("50 km/h", "Innerorts gilt beim Rechtsabbiegen mit Lkw eine besondere Grenze.")],
    explanation: "Kraftfahrzeuge über 3,5 t dürfen innerorts beim Rechtsabbiegen nur Schrittgeschwindigkeit fahren, wenn mit Rad- oder Fußverkehr zu rechnen ist. Als Radfahrer oder Pkw-Fahrer sollte man den toten Winkel neben Lkw meiden.",
    legalReference: "§ 9 Abs. 6 StVO",
  }),
  q({
    code: "own-andere_teilnehmer-008", topic: "andere_teilnehmer", points: 4, difficulty: 0.4, tags: ["strassenbahn", "haltestelle", "fahrgaeste"],
    text: "An einer Straßenbahnhaltestelle ohne Verkehrsinsel steigen Fahrgäste ein und aus. Wie fahren Sie rechts an der Straßenbahn vorbei?",
    answers: [t("Nur mit Schrittgeschwindigkeit und mit so großem Abstand, dass Fahrgäste nicht gefährdet werden; wenn nötig, warten"), t("Fahrgäste dürfen weder behindert noch gefährdet werden"), f("Links an der Straßenbahn vorbei, weil rechts die Fahrgäste stehen", "Straßenbahnen werden grundsätzlich rechts überholt.")],
    explanation: "An Haltestellen ohne Verkehrsinsel darf rechts an Schienenfahrzeugen nur mit Schrittgeschwindigkeit und ausreichendem Abstand vorbeigefahren werden. Wenn Fahrgäste ein- oder aussteigen, ist zu warten.",
    legalReference: "§ 20 Abs. 2 und 3 StVO",
  }),
  q({
    code: "own-andere_teilnehmer-009", topic: "andere_teilnehmer", points: 2, difficulty: 0.2, tags: ["aeltere_menschen", "menschen_mit_behinderung"],
    text: "Eine Person mit weißem Stock möchte die Straße überqueren. Wie verhalten Sie sich?",
    answers: [t("Anhalten und der Person ausreichend Zeit zum Überqueren geben"), f("Vorbeifahren, wenn die Person noch nicht auf der Fahrbahn ist", "Blinde und sehbehinderte Menschen können den Verkehr nicht einschätzen; sie brauchen besondere Rücksicht."), f("Kurz hupen, um auf sich aufmerksam zu machen", "Hupen erschreckt und hilft der Person nicht.")],
    explanation: "Ein weißer Stock oder eine gelbe Armbinde mit schwarzen Punkten kennzeichnet blinde oder sehbehinderte Menschen. Ihnen gegenüber ist besondere Rücksicht Pflicht, auch durch Anhalten.",
    legalReference: "§ 3 Abs. 2a StVO",
  }),
  q({
    code: "own-andere_teilnehmer-010", topic: "andere_teilnehmer", points: 2, difficulty: 0.3, tags: ["radverkehr", "nebeneinander"],
    text: "Dürfen Radfahrende nebeneinander fahren?",
    answers: [t("Ja, wenn dadurch der übrige Verkehr nicht behindert wird"), f("Nein, niemals außerhalb von Fahrradstraßen", "Seit 2020 ist das Nebeneinanderfahren grundsätzlich erlaubt, solange niemand behindert wird."), f("Nur auf Radwegen", "Auch auf der Fahrbahn ist es unter der genannten Bedingung erlaubt.")],
    explanation: "Radfahrende dürfen nebeneinander fahren, wenn sie den übrigen Verkehr dadurch nicht behindern. Autofahrer müssen beim Überholen auch dann den vollen Seitenabstand einhalten.",
    legalReference: "§ 2 Abs. 4 StVO",
  }),
  q({
    code: "own-andere_teilnehmer-011", topic: "andere_teilnehmer", points: 2, difficulty: 0.3, tags: ["motorrad", "wahrnehmung"],
    text: "Warum werden Motorräder im Verkehr häufig übersehen oder falsch eingeschätzt?",
    answers: [t("Ihre schmale Silhouette lässt Entfernung und Geschwindigkeit schwer abschätzen"), f("Weil sie immer langsamer fahren als Pkw", "Motorräder beschleunigen oft schneller als Pkw."), f("Weil sie kein Licht führen müssen", "Motorräder fahren mit eingeschaltetem Licht.")],
    explanation: "Motorräder sind schmal, können sich in der Wahrnehmung mit dem Hintergrund vermischen und beschleunigen schnell. Beim Abbiegen und Fahrstreifenwechsel besonders auf sie achten.",
  }),
  q({
    code: "own-andere_teilnehmer-012", topic: "andere_teilnehmer", points: 3, difficulty: 0.65, tags: ["radverkehr", "ueberholen", "ueberholabstand", "durchgezogene_linie"],
    text: "Innerorts fährt vor Ihnen ein Radfahrer auf der Fahrbahn. Die Fahrbahnmitte ist durch eine durchgezogene Linie markiert; für 1,5 m Seitenabstand müssten Sie diese überfahren. Was gilt?",
    answers: [t("Sie dürfen nicht überholen und müssen hinter dem Radfahrer bleiben, bis das Überholen mit 1,5 m Abstand ohne Überfahren der Linie möglich ist"), f("Sie dürfen mit weniger Abstand überholen, wenn Sie langsam fahren", "Der Mindestabstand von 1,5 m gilt unabhängig von der Geschwindigkeit."), f("Sie dürfen die durchgezogene Linie zum Überholen des Radfahrers überfahren", "Die Fahrstreifenbegrenzung darf nicht überfahren werden, auch nicht zum Überholen von Radfahrern.")],
    explanation: "Beim Überholen von Radfahrenden ist innerorts ein Seitenabstand von mindestens 1,5 m einzuhalten. Ist das ohne Überfahren der durchgezogenen Linie nicht möglich, muss auf das Überholen verzichtet werden.",
    legalReference: "§ 5 Abs. 4 StVO; Zeichen 295",
  }),
  q({
    code: "own-andere_teilnehmer-013", topic: "andere_teilnehmer", points: 3, difficulty: 0.6, tags: ["radverkehr", "ueberholverbot", "einspurige_fahrzeuge", "verkehrszeichen"],
    text: "Welches Zeichen verbietet Ihnen mit dem Pkw das Überholen von Radfahrenden und Krafträdern, während das Zeichen 276 das nicht tut?",
    answers: [t("Das Zeichen 277.1 (Verbot des Überholens von einspurigen Fahrzeugen)"), f("Das Zeichen 276 (Überholverbot für Kraftfahrzeuge aller Art)", "Zeichen 276 verbietet nur das Überholen mehrspuriger Kraftfahrzeuge und von Krafträdern mit Beiwagen."), f("Das Zeichen 277 (Überholverbot für Kraftfahrzeuge über 3,5 t)", "Zeichen 277 richtet sich an schwere Fahrzeuge.")],
    explanation: "Zeichen 277.1 wurde 2020 eingeführt: Es verbietet mehrspurigen Kraftfahrzeugen und Krafträdern mit Beiwagen das Überholen von einspurigen Fahrzeugen wie Fahrrädern und Motorrädern, etwa auf engen Strecken. Zeichen 276 erlaubt das Überholen einspuriger Fahrzeuge weiterhin.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 277.1)",
  }),
  q({
    code: "own-andere_teilnehmer-014", topic: "andere_teilnehmer", points: 4, difficulty: 0.7, tags: ["radverkehr", "zweirichtungsradweg", "rechtsabbiegen", "vorfahrt"],
    text: "Sie wollen rechts in eine Straße einbiegen, die von einem Radweg begleitet wird, der in beiden Richtungen befahren werden darf. Womit müssen Sie rechnen?",
    answers: [t("Mit Radfahrenden, die von rechts kommen und den Radweg entgegen der üblichen Richtung befahren"), t("Radfahrende auf dem Radweg müssen beim Abbiegen durchgelassen werden, aus beiden Richtungen"), f("Nur mit Radfahrenden, die von links kommen", "Auf Zweirichtungsradwegen kommen Radfahrende aus beiden Richtungen."), f("Radfahrende, die von rechts kommen, müssen Ihnen Vorfahrt gewähren", "Wer abbiegt, muss den Radverkehr auf dem begleitenden Radweg durchfahren lassen.")],
    explanation: "Zweirichtungsradwege sind eine häufige Unfallursache, weil Autofahrer beim Abbiegen nur nach links schauen. Beim Abbiegen sind Radfahrende auf dem begleitenden Radweg aus beiden Richtungen durchzulassen.",
    legalReference: "§ 9 Abs. 3 StVO",
  }),
  q({
    code: "own-andere_teilnehmer-015", topic: "andere_teilnehmer", points: 3, difficulty: 0.65, tags: ["radverkehr", "rechts_vor_links", "radweg", "kreuzung"],
    text: "An einer Kreuzung mit rechts vor links kommt von rechts ein Radfahrer, der auf dem straßenbegleitenden Radweg fährt. Hat er Vorfahrt?",
    answers: [t("Ja, der Radweg gehört zur Straße; der Radfahrer von rechts hat wie ein Fahrzeug auf der Fahrbahn Vorfahrt"), f("Nein, Radwege sind keine Straßen im Sinne der Vorfahrtregel", "Der straßenbegleitende Radweg teilt die Vorfahrt der Straße."), f("Nein, Radfahrende müssen an Kreuzungen immer warten", "Eine solche Regel gibt es nicht.")],
    explanation: "Ein straßenbegleitender Radweg gehört zur Straße und hat deren Vorfahrt. Bei rechts vor links hat der Radfahrer von rechts also Vorfahrt wie ein Auto auf der Fahrbahn.",
    legalReference: "§ 8 Abs. 1 StVO",
  }),
  q({
    code: "own-andere_teilnehmer-016", topic: "andere_teilnehmer", points: 3, difficulty: 0.6, tags: ["radverkehr", "zebrastreifen", "vorrang", "fussgaengerueberweg"],
    text: "Ein Radfahrer will fahrend den Zebrastreifen überqueren. Ein zweiter schiebt sein Fahrrad. Wer hat Vorrang?",
    answers: [t("Nur der Schiebende, weil er als Fußgänger gilt; der fahrende Radfahrer hat am Zebrastreifen keinen Vorrang"), f("Beide, weil der Zebrastreifen für alle gilt", "Der Vorrang am Fußgängerüberweg gilt nur für Fußgänger und Personen in Rollstühlen."), f("Keiner, weil Fahrräder den Zebrastreifen nicht benutzen dürfen", "Das Überqueren ist erlaubt, nur der Vorrang fehlt beim Fahren.")],
    explanation: "Der Vorrang am Fußgängerüberweg gilt für zu Fuß Gehende und Rollstuhlfahrende. Wer sein Fahrrad schiebt, ist Fußgänger. Fahrende Radfahrer haben keinen Vorrang; aus Rücksicht sollte man sie dennoch nicht gefährden.",
    legalReference: "§ 26 Abs. 1 StVO",
  }),
  q({
    code: "own-andere_teilnehmer-017", topic: "andere_teilnehmer", points: 3, difficulty: 0.65, tags: ["e_scooter", "elektrokleinstfahrzeuge", "alkohol", "versicherung"],
    text: "Welche Regeln gelten zusätzlich für E-Scooter (Elektrokleinstfahrzeuge)?",
    answers: [t("Es gelten die Alkoholgrenzen wie für Kraftfahrzeuge, in der Probezeit also das absolute Alkoholverbot"), t("Eine Versicherungsplakette ist Pflicht"), t("Die Mitnahme einer weiteren Person ist verboten"), f("Es ist eine Fahrerlaubnis der Klasse AM erforderlich", "Eine Fahrerlaubnis ist nicht nötig, nur das Mindestalter von 14 Jahren.")],
    explanation: "E-Scooter sind Kraftfahrzeuge: Es gelten die Promillegrenzen für Kraftfahrer, die Versicherungspflicht mit Plakette und das Verbot, Personen mitzunehmen. Eine Fahrerlaubnis ist nicht erforderlich, das Mindestalter beträgt 14 Jahre.",
    legalReference: "Elektrokleinstfahrzeuge-Verordnung (eKFV); § 24a StVG; § 24c StVG", reviewStatus: "needs_verification",
  }),
  q({
    code: "own-andere_teilnehmer-018", topic: "andere_teilnehmer", points: 2, difficulty: 0.5, tags: ["e_scooter", "elektrokleinstfahrzeuge", "hoechstgeschwindigkeit"], kind: "numeric", numericAnswer: 20, tolerance: 0, unit: "km/h",
    text: "Wie hoch ist die bauartbedingte Höchstgeschwindigkeit, die ein E-Scooter (Elektrokleinstfahrzeug) höchstens haben darf? Angabe in km/h.",
    answers: [],
    explanation: "Elektrokleinstfahrzeuge dürfen bauartbedingt höchstens 20 km/h fahren. Sie müssen Radwege benutzen und dürfen ohne Radweg auf der Fahrbahn fahren, nicht auf dem Gehweg.",
    legalReference: "§ 1 eKFV",
  }),
  q({
    code: "own-andere_teilnehmer-019", topic: "andere_teilnehmer", points: 3, difficulty: 0.6, tags: ["pedelec", "s_pedelec", "radverkehr", "radweg"],
    text: "Worin unterscheiden sich Pedelec und S-Pedelec im Straßenverkehr?",
    answers: [t("Das Pedelec mit Unterstützung bis 25 km/h gilt als Fahrrad und darf Radwege benutzen"), t("Das S-Pedelec mit Unterstützung bis 45 km/h ist ein Kleinkraftrad: Es braucht Versicherungskennzeichen, eine Fahrerlaubnis mindestens der Klasse AM und darf Radwege nicht benutzen"), f("Beide dürfen ohne Helm und ohne Kennzeichen auf Radwegen fahren", "Das S-Pedelec unterliegt Helm- und Kennzeichenpflicht und darf nicht auf den Radweg."), f("Für das Pedelec ist eine Fahrerlaubnis der Klasse AM erforderlich", "Das Pedelec bis 25 km/h ist rechtlich ein Fahrrad.")],
    explanation: "Pedelecs mit Tretunterstützung bis 25 km/h sind Fahrräder. S-Pedelecs bis 45 km/h sind Kleinkrafträder und benötigen Versicherungskennzeichen, Helm und Fahrerlaubnis; Radwege sind für sie tabu.",
    legalReference: "§ 1 Abs. 3 StVG; § 2 Abs. 4 StVO; § 21a StVO",
  }),
  q({
    code: "own-andere_teilnehmer-020", topic: "andere_teilnehmer", points: 3, difficulty: 0.6, tags: ["linienbus", "schulbus", "warnblinklicht", "ausserorts"],
    text: "Außerorts nähert sich vor Ihnen ein Schulbus mit eingeschaltetem Warnblinklicht einer Haltestelle. Was gilt?",
    answers: [t("Sie dürfen den Bus nicht überholen"), t("Steht der Bus mit Warnblinklicht an der Haltestelle, dürfen Sie nur mit Schrittgeschwindigkeit und ausreichendem Abstand vorbeifahren"), f("Sie dürfen den Bus überholen, solange er noch fährt", "Bussen mit Warnblinklicht, die sich einer Haltestelle nähern, darf nicht überholt werden."), f("Außerorts gelten die Regeln zum Warnblinklicht nicht", "Sie gelten innerorts und außerorts.")],
    explanation: "Ein Linien- oder Schulbus, der sich mit Warnblinklicht einer Haltestelle nähert, darf nicht überholt werden. Steht er mit Warnblinklicht, darf nur mit Schrittgeschwindigkeit und so vorbeigefahren werden, dass Fahrgäste nicht gefährdet werden; das gilt auch für den Gegenverkehr.",
    legalReference: "§ 20 Abs. 2 und 4 StVO",
  }),
  q({
    code: "own-andere_teilnehmer-021", topic: "andere_teilnehmer", points: 3, difficulty: 0.6, tags: ["linienbus", "haltestelle", "ausserorts", "abfahren"],
    text: "Außerorts will ein Linienbus von einer Haltestelle abfahren und blinkt links. Müssen Sie ihm das Abfahren ermöglichen?",
    answers: [t("Die Pflicht, das Abfahren zu ermöglichen, gilt nur innerorts; außerorts sollten Sie es aus Rücksicht dennoch tun, wenn es gefahrlos möglich ist"), f("Ja, die Pflicht gilt innerorts und außerorts gleichermaßen", "Die gesetzliche Pflicht ist auf geschlossene Ortschaften beschränkt."), f("Nein, außerorts hat der Bus keinerlei Rechte an Haltestellen", "Die Regeln zum Warnblinklicht gelten auch außerorts.")],
    explanation: "Das Abfahren von Linien- und Schulbussen an gekennzeichneten Haltestellen ist innerorts zu ermöglichen. Außerorts besteht diese Pflicht nicht, Rücksicht nach § 1 StVO ist aber immer geboten.",
    legalReference: "§ 20 Abs. 5 StVO",
  }),
  q({
    code: "own-andere_teilnehmer-022", topic: "andere_teilnehmer", points: 3, difficulty: 0.6, tags: ["kinder", "haltestelle", "linienbus", "innerorts"],
    text: "Ein Linienbus hält innerorts an einer Haltestelle ohne Warnblinklicht. Kinder steigen aus. Wie fahren Sie vorbei?",
    answers: [t("Vorsichtig und bremsbereit mit ausreichendem Abstand, weil Kinder plötzlich vor oder hinter dem Bus auf die Fahrbahn laufen können"), f("Mit unveränderter Geschwindigkeit, weil ohne Warnblinklicht keine Schrittgeschwindigkeit vorgeschrieben ist", "Auch ohne Warnblinklicht müssen Fahrgäste durch Vorsicht geschützt werden."), f("Sie müssen anhalten, bis alle Kinder den Bus verlassen haben", "Eine Anhaltepflicht besteht nicht, solange niemand gefährdet wird.")],
    explanation: "An haltenden Bussen darf nur vorsichtig vorbeigefahren werden; ein- und aussteigende Fahrgäste dürfen nicht gefährdet werden. Bei Kindern ist besondere Bremsbereitschaft nötig, weil sie unvermittelt die Fahrbahn betreten.",
    legalReference: "§ 20 Abs. 1 StVO; § 3 Abs. 2a StVO",
  }),
  q({
    code: "own-andere_teilnehmer-023", topic: "andere_teilnehmer", points: 3, difficulty: 0.55, tags: ["reiter", "pferde", "ausserorts", "ruecksicht"],
    text: "Auf einer Landstraße reiten zwei Personen am rechten Fahrbahnrand. Wie überholen Sie?",
    answers: [t("Langsam, mit großem Seitenabstand und ohne zu hupen oder unnötig Gas zu geben"), f("Zügig mit knappem Abstand, damit die Pferde nur kurz beunruhigt werden", "Schnelle, laute Fahrzeuge in unmittelbarer Nähe erschrecken Pferde."), f("Nach kurzem Hupen, damit die Reiter nach rechts ausweichen", "Hupen kann Pferde scheuen lassen und ist hier verboten.")],
    explanation: "Pferde können scheuen und unvermittelt zur Seite oder auf die Fahrbahn springen. Deshalb Reiter langsam, mit großem Abstand und ohne laute Geräusche überholen.",
    legalReference: "§ 1 StVO; § 5 Abs. 4 StVO",
  }),
  q({
    code: "own-andere_teilnehmer-024", topic: "andere_teilnehmer", points: 3, difficulty: 0.6, tags: ["landwirtschaft", "traktor", "ausserorts", "ueberholen"],
    text: "Auf einer Landstraße fährt vor Ihnen ein Traktor mit breitem Anbaugerät und etwa 25 km/h. Was ist beim Überholen zu beachten?",
    answers: [t("Das Anbaugerät kann breiter sein als das Fahrzeug und kann Ihre Sicht auf den Gegenverkehr verdecken"), t("Der Traktor kann unvermittelt nach links in einen Feldweg abbiegen; achten Sie auf Blinker und Verhalten"), t("Überholen Sie nur mit ausreichend Sicht und wesentlich höherer Geschwindigkeit"), f("Landwirtschaftliche Fahrzeuge dürfen immer sofort überholt werden, weil sie langsam sind", "Es gelten die allgemeinen Überholregeln.")],
    explanation: "Landwirtschaftliche Fahrzeuge sind langsam, breit und biegen oft in Feldwege ab. Vor dem Überholen genügend Sicht abwarten, auf Blinker achten und den Vorgang zügig abschließen.",
    legalReference: "§ 5 Abs. 2 StVO",
  }),
  q({
    code: "own-andere_teilnehmer-025", topic: "andere_teilnehmer", points: 3, difficulty: 0.6, tags: ["motorrad", "kurve", "abstand", "ausserorts"],
    text: "Ein Motorrad überholt Sie auf der Landstraße und schert vor Ihnen ein. Kurz darauf folgt eine Kurve. Worauf sollten Sie sich einstellen?",
    answers: [t("Motorräder können in Kurven stürzen oder abrupt bremsen; halten Sie deshalb ausreichenden Abstand"), t("Ein Motorrad kann stärker verzögern und braucht in Schräglage einen größeren Sicherheitsraum"), f("Motorräder bremsen immer schlechter als Pkw, deshalb kann der Abstand geringer sein", "Motorräder verzögern oft genauso stark wie Pkw."), f("Der Abstand ist unerheblich, weil Motorräder schmal sind", "Auch ein schmales Fahrzeug braucht bei Sturz oder Bremsung Raum.")],
    explanation: "Motorräder sind in Kurven sturzgefährdet und bremsen oft stark. Wer dahinterfährt, braucht ausreichenden Abstand, um bei einem Sturz oder einer Vollbremsung anhalten zu können.",
    legalReference: "§ 4 Abs. 1 StVO",
  }),
  q({
    code: "own-andere_teilnehmer-026", topic: "andere_teilnehmer", points: 3, difficulty: 0.65, tags: ["strassenbahn", "schienenfahrzeuge", "rechts_vor_links", "vorfahrt"],
    text: "An einer Kreuzung mit rechts vor links nähert sich von links eine Straßenbahn. Wer hat Vorfahrt?",
    answers: [t("Sie, weil rechts vor links auch für Straßenbahnen gilt; im Zweifel sollten Sie der Straßenbahn wegen ihres langen Bremswegs dennoch den Vortritt lassen"), f("Die Straßenbahn, weil Schienenfahrzeuge immer Vorfahrt haben", "Straßenbahnen haben nur dann Vorrang, wenn Zeichen oder Lichtzeichen es anordnen oder sie von rechts kommen."), f("Die Straßenbahn, weil sie nicht ausweichen kann", "Das ist ein Grund zur Vorsicht, aber keine Vorfahrtregel.")],
    explanation: "Die Regel rechts vor links gilt auch für Straßenbahnen, wenn keine Zeichen etwas anderes anordnen. Wegen des langen Bremswegs von Schienenfahrzeugen ist trotzdem besondere Vorsicht geboten.",
    legalReference: "§ 8 Abs. 1 StVO",
  }),
  q({
    code: "own-andere_teilnehmer-027", topic: "andere_teilnehmer", points: 3, difficulty: 0.55, tags: ["strassenbahn", "schienenfahrzeuge", "platz_machen"],
    text: "Sie fahren auf einer Straße mit Straßenbahnschienen in der Fahrbahn. Hinter Ihnen klingelt eine Straßenbahn. Was ist richtig?",
    answers: [t("Sie müssen der Straßenbahn Platz machen, weil Schienenfahrzeuge auf Schienen nicht ausweichen können"), f("Die Straßenbahn muss warten, weil Sie zuerst da waren", "Schienenfahrzeugen ist Platz zu machen."), f("Sie dürfen auf den Schienen bleiben, wenn Sie schneller fahren als die Bahn", "Das behindert die Straßenbahn.")],
    explanation: "Schienenfahrzeugen ist Platz zu machen, weil sie an die Schienen gebunden sind und nicht ausweichen können. Wer auf den Schienen fährt, muss sie freimachen, sobald eine Straßenbahn kommt.",
    legalReference: "§ 2 Abs. 3 StVO",
  }),
  q({
    code: "own-andere_teilnehmer-028", topic: "andere_teilnehmer", points: 3, difficulty: 0.6, tags: ["aeltere_menschen", "fussgaenger", "wahrnehmung", "innerorts"],
    text: "Ein älterer Fußgänger beginnt weit vor Ihnen, langsam die Straße zu überqueren, obwohl kein Überweg vorhanden ist. Wie verhalten Sie sich?",
    answers: [t("Geschwindigkeit deutlich verringern, bremsbereit sein und ihm das Überqueren ermöglichen"), f("Hupen, damit er stehen bleibt oder zurückgeht", "Hupen erschreckt und kann zu unvorhersehbaren Reaktionen führen."), f("Mit unveränderter Geschwindigkeit weiterfahren, weil er außerhalb eines Überwegs keinen Vorrang hat", "Gegenüber älteren Menschen ist besondere Rücksicht Pflicht, unabhängig vom Vorrang.")],
    explanation: "Ältere Menschen reagieren langsamer, schätzen Geschwindigkeiten schlechter ein und können nicht schnell ausweichen. Gegenüber ihnen ist die Geschwindigkeit zu verringern und Bremsbereitschaft Pflicht.",
    legalReference: "§ 3 Abs. 2a StVO",
  }),
  q({
    code: "own-andere_teilnehmer-029", topic: "andere_teilnehmer", points: 3, difficulty: 0.6, tags: ["menschen_mit_behinderung", "rollstuhl", "fussgaengerueberweg", "vorrang"],
    text: "Am Zebrastreifen wartet eine Person im Rollstuhl. Was gilt?",
    answers: [t("Sie hat wie Fußgänger Vorrang; Sie müssen anhalten und ihr das Überqueren ermöglichen"), t("Rechnen Sie damit, dass das Überqueren länger dauert als bei anderen Fußgängern"), f("Rollstuhlfahrende gelten als Fahrzeugführer und haben am Zebrastreifen keinen Vorrang", "Personen in Rollstühlen haben am Fußgängerüberweg ausdrücklich Vorrang."), f("Sie dürfen weiterfahren, wenn die Person noch auf dem Gehweg ist", "Der Vorrang gilt bereits, wenn erkennbar ist, dass die Person überqueren will.")],
    explanation: "Am Fußgängerüberweg haben zu Fuß Gehende und Rollstuhlfahrende Vorrang. Fahrzeuge müssen sich mit mäßiger Geschwindigkeit nähern und warten. Menschen mit Behinderung brauchen oft mehr Zeit.",
    legalReference: "§ 26 Abs. 1 StVO; § 3 Abs. 2a StVO",
  }),
  q({
    code: "own-andere_teilnehmer-030", topic: "andere_teilnehmer", points: 3, difficulty: 0.55, tags: ["fussgaenger", "kinder", "gefahrzeichen", "innerorts"],
    text: "Sie sehen das Gefahrzeichen 136 (Kinder). Wie verhalten Sie sich?",
    answers: [t("Geschwindigkeit verringern und mit spielenden oder plötzlich auf die Fahrbahn laufenden Kindern rechnen"), t("Besonders auf Bereiche hinter parkenden Fahrzeugen achten"), f("Anhalten und warten, bis keine Kinder mehr zu sehen sind", "Eine Anhaltepflicht besteht nicht; gefordert sind angepasste Geschwindigkeit und Bremsbereitschaft."), f("Das Zeichen gilt nur zu Schulzeiten", "Ohne Zusatzzeichen gilt es jederzeit.")],
    explanation: "Zeichen 136 warnt vor Kindern, etwa in der Nähe von Schulen, Kindergärten und Spielplätzen. Kinder sind klein, unberechenbar und tauchen oft zwischen parkenden Autos auf. Deshalb langsam und bremsbereit fahren.",
    legalReference: "§ 40 StVO, Anlage 1 (Zeichen 136); § 3 Abs. 2a StVO",
  }),
  q({
    code: "own-andere_teilnehmer-031", topic: "andere_teilnehmer", points: 3, difficulty: 0.65, tags: ["radverkehr", "radweg_ende", "einordnen", "innerorts"],
    text: "Ein benutzungspflichtiger Radweg endet vor Ihnen und der Radfahrer muss auf die Fahrbahn wechseln. Was gilt?",
    answers: [t("Der Radfahrer darf auf die Fahrbahn einfahren; er muss dabei den Fahrzeugverkehr beachten, Sie sollten ihm das Einordnen ermöglichen"), f("Der Radfahrer muss absteigen und auf dem Gehweg weiterschieben", "Endet der Radweg, fährt der Radverkehr auf der Fahrbahn weiter."), f("Sie haben Vorrang und dürfen den Radfahrer knapp überholen", "Der Mindestabstand von 1,5 m gilt auch hier.")],
    explanation: "Endet ein Radweg, wechselt der Radverkehr auf die Fahrbahn. Autofahrer müssen damit rechnen, den Radfahrer einfädeln lassen und beim Überholen den Seitenabstand einhalten.",
    legalReference: "§ 2 Abs. 4 StVO; § 5 Abs. 4 StVO; § 1 StVO",
  }),
  q({
    code: "own-andere_teilnehmer-032", topic: "andere_teilnehmer", points: 3, difficulty: 0.55, tags: ["lkw", "toter_winkel", "kreuzung", "abstand"],
    text: "Sie stehen mit dem Pkw an einer roten Ampel rechts neben einem Lkw, der rechts blinkt. Welche Gefahr besteht und wie verhalten Sie sich?",
    answers: [t("Sie befinden sich möglicherweise im toten Winkel des Lkw; halten Sie Abstand und lassen Sie den Lkw zuerst abbiegen"), f("Keine, weil der Lkw-Fahrer Sie im Spiegel sehen muss", "Trotz Spiegeln bleibt der Bereich rechts neben dem Fahrerhaus teilweise unsichtbar."), f("Sie sollten schnell vor dem Lkw losfahren, um nicht eingeklemmt zu werden", "Ein Wettrennen mit dem Lkw ist gefährlich; besser zurückbleiben.")],
    explanation: "Rechts neben einem abbiegenden Lkw ist der gefährlichste Platz, weil der Fahrer dort kaum etwas sieht und der Lkw beim Abbiegen ausschwenkt. Abstand halten und den Lkw abbiegen lassen.",
    legalReference: "§ 1 StVO; § 9 Abs. 6 StVO",
  }),
  q({
    code: "own-andere_teilnehmer-033", topic: "andere_teilnehmer", points: 3, difficulty: 0.6, tags: ["radverkehr", "kinder", "gehweg", "einfahren"],
    text: "Ein achtjähriges Kind fährt mit dem Fahrrad auf dem Gehweg und will an einer Einmündung die Fahrbahn überqueren. Was gilt?",
    answers: [t("Das Kind muss vor dem Überqueren absteigen und schieben; Sie müssen aber damit rechnen, dass es das nicht tut"), t("Sie sollten die Geschwindigkeit verringern und bremsbereit sein"), f("Das Kind hat Vorfahrt, weil es von rechts kommt", "Kinder auf dem Gehweg müssen beim Überqueren der Fahrbahn absteigen und haben keine Vorfahrt."), f("Kinder dürfen mit dem Rad nicht auf dem Gehweg fahren", "Kinder bis zum vollendeten zehnten Lebensjahr dürfen den Gehweg benutzen.")],
    explanation: "Kinder, die auf dem Gehweg Rad fahren, müssen vor dem Überqueren einer Fahrbahn absteigen. Weil sie das oft vergessen, müssen Autofahrer besonders aufmerksam und bremsbereit sein.",
    legalReference: "§ 2 Abs. 5 StVO; § 3 Abs. 2a StVO",
  }),
  q({
    code: "own-andere_teilnehmer-034", topic: "andere_teilnehmer", points: 3, difficulty: 0.55, tags: ["fussgaenger", "verkehrshelfer", "schulweg", "kinder"],
    text: "Sie sehen das Zeichen 356 (Verkehrshelfer). Was bedeutet das für Sie?",
    answers: [t("Mit Schülerlotsen und querenden Kindern rechnen und die Geschwindigkeit deutlich verringern"), t("Halten die Verkehrshelfer die Kelle hoch, um Kindern das Überqueren zu ermöglichen, halten Sie an"), f("Das Zeichen gilt nur für Schulbusse", "Es richtet sich an alle Fahrzeugführer."), f("Verkehrshelfer haben keinerlei Bedeutung für den Fahrzeugverkehr", "Verkehrshelfer sichern Schulwege; ihre Zeichen dienen der Sicherheit der Kinder.")],
    explanation: "Zeichen 356 weist auf Verkehrshelfer wie Schülerlotsen hin, die Kinder sicher über die Straße bringen. Fahrzeugführer müssen dort besonders vorsichtig fahren und den Kindern das Überqueren ermöglichen.",
    legalReference: "§ 42 StVO, Anlage 3 (Zeichen 356); § 3 Abs. 2a StVO",
  }),
  q({
    code: "own-andere_teilnehmer-035", topic: "andere_teilnehmer", points: 3, difficulty: 0.6, tags: ["radverkehr", "ueberholen", "ausserorts", "ueberholabstand"],
    text: "Außerorts überholen Sie einen Radfahrer. Ihnen kommt ein Fahrzeug entgegen, sodass Sie mit 2 m Seitenabstand nicht vorbeikämen. Was ist richtig?",
    answers: [t("Sie brechen den Überholvorgang ab und warten hinter dem Radfahrer, bis Gegenverkehr und Sicht das Überholen mit 2 m Abstand zulassen"), f("Sie überholen mit weniger Abstand, weil der Radfahrer am Rand fährt", "Außerorts sind 2 m Mindestabstand vorgeschrieben."), f("Sie hupen, damit der Radfahrer auf den Grünstreifen ausweicht", "Der Radfahrer darf die Fahrbahn benutzen; Hupen ist nicht erlaubt.")],
    explanation: "Außerorts beträgt der Mindestabstand zu Radfahrenden 2 m. Kann er wegen Gegenverkehrs nicht eingehalten werden, darf nicht überholt werden. Radfahrende dürfen nicht abgedrängt werden.",
    legalReference: "§ 5 Abs. 4 StVO",
  }),
  q({
    code: "own-andere_teilnehmer-036", topic: "andere_teilnehmer", points: 3, difficulty: 0.55, tags: ["fussgaenger", "gehweg", "ausparken", "rueckwaertsfahren"],
    text: "Sie fahren rückwärts aus einer Parklücke über den Gehweg. Was gilt gegenüber Fußgängern?",
    answers: [t("Fußgänger auf dem Gehweg haben Vorrang; Sie müssen sich nötigenfalls einweisen lassen"), f("Fußgänger müssen warten, weil Sie schlechte Sicht haben", "Schlechte Sicht verpflichtet den Fahrer zu besonderer Vorsicht, nicht die Fußgänger zum Warten."), f("Sie dürfen hupen, damit die Fußgänger stehen bleiben", "Hupen ist hier nicht zulässig; die Gefährdung muss durch Vorsicht ausgeschlossen werden.")],
    explanation: "Beim Rückwärtsfahren und beim Einfahren aus einem Grundstück oder Parkplatz auf den Gehweg muss jede Gefährdung anderer ausgeschlossen sein. Fußgänger haben Vorrang; bei fehlender Sicht ist ein Einweiser nötig.",
    legalReference: "§ 9 Abs. 5 StVO; § 10 StVO",
  }),
  q({
    code: "own-andere_teilnehmer-037", topic: "andere_teilnehmer", points: 3, difficulty: 0.65, tags: ["radverkehr", "fahrradstrasse", "nebeneinander", "innerorts"],
    text: "Sie dürfen eine Fahrradstraße mit dem Pkw befahren. Vor Ihnen fahren zwei Radfahrende nebeneinander und Sie kommen nicht vorbei. Was gilt?",
    answers: [t("Sie müssen dahinter bleiben; in Fahrradstraßen dürfen Radfahrende nebeneinander fahren und dürfen nicht behindert oder gefährdet werden"), f("Die Radfahrenden müssen hintereinander fahren, damit Sie überholen können", "In Fahrradstraßen ist das Nebeneinanderfahren ausdrücklich erlaubt."), f("Sie dürfen hupen, damit Platz gemacht wird", "Das wäre eine unzulässige Behinderung des Radverkehrs.")],
    explanation: "In Fahrradstraßen hat der Radverkehr Vorrang vor dem zugelassenen Kraftfahrzeugverkehr. Radfahrende dürfen nebeneinander fahren; Kraftfahrzeuge müssen sich anpassen und dürfen höchstens 30 km/h fahren.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 244.1)",
  }),
  q({
    code: "own-andere_teilnehmer-038", topic: "andere_teilnehmer", points: 3, difficulty: 0.5, tags: ["fussgaenger", "nacht", "ausserorts", "sichtbarkeit"],
    text: "Nachts auf einer unbeleuchteten Landstraße geht ein dunkel gekleideter Fußgänger am Fahrbahnrand. Ab welcher Entfernung ist er mit Abblendlicht in der Regel erkennbar und was folgt daraus?",
    answers: [t("Oft erst auf wenige Dutzend Meter; deshalb muss die Geschwindigkeit so gewählt werden, dass innerhalb der Leuchtweite angehalten werden kann"), f("Auf mehrere hundert Meter, weil das Abblendlicht weit reicht", "Das Abblendlicht leuchtet nur einen begrenzten Bereich aus; dunkle Kleidung reflektiert kaum."), f("Die Entfernung ist unwichtig, weil Fußgänger außerorts links gehen und Ihnen entgegenkommen", "Auch entgegenkommende Fußgänger werden bei Dunkelheit spät erkannt.")],
    explanation: "Dunkel gekleidete Fußgänger werden mit Abblendlicht erst spät sichtbar, oft zu spät für einen Anhalteweg bei 100 km/h. Nachts muss deshalb langsamer gefahren werden, als es die Höchstgeschwindigkeit erlaubt.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-andere_teilnehmer-039", topic: "andere_teilnehmer", points: 3, difficulty: 0.55, tags: ["motorrad", "fahrstreifenwechsel", "toter_winkel", "autobahn"],
    text: "Warum müssen Sie beim Fahrstreifenwechsel auf der Autobahn besonders auf Motorräder achten?",
    answers: [t("Sie sind schmal, verschwinden leicht im toten Winkel und nähern sich oft schneller, als es scheint"), t("Ein Schulterblick ist deshalb auch auf der Autobahn unverzichtbar"), f("Motorräder dürfen auf der Autobahn nur den rechten Fahrstreifen benutzen", "Motorräder dürfen alle Fahrstreifen nutzen."), f("Motorräder fahren auf der Autobahn immer langsamer als Pkw", "Motorräder sind häufig schneller unterwegs.")],
    explanation: "Motorräder sind wegen ihrer schmalen Silhouette im Spiegel leicht zu übersehen, und ihre Geschwindigkeit wird unterschätzt. Vor jedem Fahrstreifenwechsel gehören Spiegel und Schulterblick dazu.",
    legalReference: "§ 7 Abs. 5 StVO",
  }),
  q({
    code: "own-andere_teilnehmer-040", topic: "andere_teilnehmer", points: 2, difficulty: 0.45, tags: ["radverkehr", "gefahrzeichen", "kreuzung"],
    text: "Das Gefahrzeichen 138 (Radverkehr) steht vor einer Stelle, an der ein Radweg die Straße kreuzt. Was ist richtig?",
    answers: [t("Sie müssen mit kreuzenden Radfahrenden rechnen und die Geschwindigkeit anpassen"), f("Radfahrende haben an dieser Stelle immer Vorfahrt", "Das Gefahrzeichen regelt keine Vorfahrt; sie ergibt sich aus den Vorfahrtregeln und -zeichen."), f("Radfahrende dürfen die Straße hier nicht überqueren", "Das Zeichen warnt gerade davor, dass sie es tun.")],
    explanation: "Zeichen 138 warnt vor Radverkehr, der die Fahrbahn kreuzt oder auf sie einfährt. Wer Vorfahrt hat, ergibt sich aus den Vorfahrtregeln, nicht aus dem Gefahrzeichen; in jedem Fall ist Vorsicht geboten.",
    legalReference: "§ 40 StVO, Anlage 1 (Zeichen 138)",
  }),
  q({
    code: "own-andere_teilnehmer-041", topic: "andere_teilnehmer", points: 3, difficulty: 0.6, tags: ["fussgaenger", "innerorts", "fussgaengerzone", "einfahren"],
    text: "Sie dürfen mit dem Pkw eine Fußgängerzone (Zeichen 242.1) befahren, weil ein Zusatzzeichen Lieferverkehr zu bestimmten Zeiten freigibt. Was gilt beim Fahren?",
    answers: [t("Sie dürfen nur mit Schrittgeschwindigkeit fahren und müssen Fußgängern jederzeit den Vorrang lassen"), t("Beim Verlassen der Fußgängerzone müssen Sie allen anderen Verkehrsteilnehmern Vorfahrt gewähren"), f("Es gilt eine Höchstgeschwindigkeit von 30 km/h", "In der Fußgängerzone ist Schrittgeschwindigkeit vorgeschrieben."), f("Fußgänger müssen den Fahrzeugen ausweichen", "In der Fußgängerzone haben Fußgänger Vorrang.")],
    explanation: "In einer Fußgängerzone darf freigegebener Fahrzeugverkehr nur mit Schrittgeschwindigkeit fahren und muss auf Fußgänger Rücksicht nehmen. Wer aus einer Fußgängerzone auf eine Straße fährt, muss allen anderen Vorfahrt gewähren.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 242.1); § 10 StVO",
  }),
];
