// Übungsfragen zum Thema "befoerderung" (eigene Formulierungen, kein amtlicher Prüfungsinhalt).
import type { Question } from "../types";
import { q, t, f } from "./_helpers";

export const befoerderung: readonly Question[] = [
  q({
    code: "own-befoerderung-001", topic: "befoerderung", points: 3, difficulty: 0.2, tags: ["kindersitz", "kinder", "gurt"],
    text: "Bis zu welchem Alter und welcher Körpergröße müssen Kinder im Auto in einer Rückhalteeinrichtung (Kindersitz) gesichert werden?",
    answers: [t("Kinder unter 12 Jahren, die kleiner als 150 cm sind"), f("Alle Kinder unter 14 Jahren unabhängig von der Größe", "Maßgeblich sind Alter und Größe zusammen."), f("Nur Kinder unter 6 Jahren", "Die Pflicht gilt deutlich länger.")],
    explanation: "Kinder bis zum vollendeten 12. Lebensjahr, die kleiner als 150 cm sind, müssen in einem geeigneten und zugelassenen Kindersitz mitfahren. Der Fahrer ist dafür verantwortlich.",
    legalReference: "§ 21 Abs. 1a StVO",
  }),
  q({
    code: "own-befoerderung-002", topic: "befoerderung", points: 3, difficulty: 0.3, tags: ["ladung", "ueberstand", "kennzeichnung"],
    text: "Ihre Ladung ragt mehr als einen Meter über die Rückstrahler des Fahrzeugs hinaus. Wie ist sie zu kennzeichnen?",
    answers: [t("Mit einer hellroten Fahne oder einem hellroten Schild von mindestens 30 mal 30 cm; bei Dunkelheit zusätzlich mit roter Leuchte und rotem Rückstrahler"), f("Gar nicht, solange die Ladung gesichert ist", "Ab einem Meter Überstand ist die Kennzeichnung Pflicht."), f("Mit einem weißen Tuch beliebiger Größe", "Vorgeschrieben ist hellrot und eine Mindestgröße.")],
    explanation: "Ragt Ladung mehr als einen Meter über die Rückstrahler hinaus, muss das Ende mit einer hellroten Fahne oder einem hellroten Schild von mindestens 30 mal 30 cm kenntlich gemacht werden. Bei Dunkelheit kommen rote Leuchte und roter Rückstrahler hinzu.",
    legalReference: "§ 22 Abs. 4 StVO",
  }),
  q({
    code: "own-befoerderung-003", topic: "befoerderung", points: 2, difficulty: 0.4, tags: ["ladung", "ueberstand"],
    text: "Wie weit darf Ladung nach hinten über das Fahrzeug hinausragen?",
    answers: [t("Bis zu 1,5 Meter; bei Fahrten bis 100 km bis zu 3 Meter"), f("Unbegrenzt, wenn sie gekennzeichnet ist", "Es gibt feste Höchstmaße."), f("Höchstens 50 cm", "Erlaubt ist mehr, sofern die Kennzeichnung erfolgt.")],
    explanation: "Ladung darf nach hinten bis 1,5 Meter über das Fahrzeug hinausragen, bei Fahrten bis 100 Kilometer bis zu 3 Meter. Ab einem Meter Überstand ist sie zu kennzeichnen.",
    legalReference: "§ 22 Abs. 4 StVO",
  }),
  q({
    code: "own-befoerderung-004", topic: "befoerderung", points: 3, difficulty: 0.4, tags: ["anhaenger", "klasse_b"],
    text: "Welche Anhänger dürfen Sie mit der Klasse B ziehen?",
    answers: [t("Anhänger bis 750 kg zulässiger Gesamtmasse immer"), t("Schwerere Anhänger, wenn die zulässige Gesamtmasse der Kombination 3.500 kg nicht übersteigt"), f("Jeden Anhänger bis 3.500 kg zulässiger Gesamtmasse", "Dafür ist die Klasse BE erforderlich.")],
    explanation: "Mit Klasse B sind Anhänger bis 750 kg immer erlaubt. Schwerere Anhänger nur, wenn Zugfahrzeug und Anhänger zusammen höchstens 3.500 kg zulässige Gesamtmasse haben; für mehr braucht man B96 oder BE.",
    legalReference: "§ 6 FeV",
  }),
  q({
    code: "own-befoerderung-005", topic: "befoerderung", points: 3, difficulty: 0.3, tags: ["ladungssicherung", "ladung"],
    text: "Wie muss Ladung im Fahrzeug gesichert sein?",
    answers: [t("So, dass sie auch bei Vollbremsung oder Ausweichmanöver nicht verrutschen, umfallen oder herabfallen kann"), f("Nur so, dass sie beim normalen Fahren nicht klappert", "Ladung muss auch bei Vollbremsung und Ausweichmanöver sicher bleiben."), f("Schwere Gegenstände gehören auf die Hutablage, damit sie sichtbar bleiben", "Lose Gegenstände auf der Hutablage werden bei einer Bremsung zu Geschossen.")],
    explanation: "Ladung ist so zu verstauen und zu sichern, dass sie selbst bei Vollbremsung oder plötzlicher Ausweichbewegung nicht verrutschen kann. Zurrgurte, Antirutschmatten und Trennnetze helfen dabei.",
    legalReference: "§ 22 Abs. 1 StVO",
  }),
  q({
    code: "own-befoerderung-006", topic: "befoerderung", points: 2, difficulty: 0.2, tags: ["gurt", "gurtpflicht"],
    text: "Was gilt zur Gurtpflicht im Pkw?",
    answers: [t("Alle Insassen müssen sich anschnallen, auch auf den Rücksitzen"), t("Der Fahrer ist dafür verantwortlich, dass Kinder vorschriftsmäßig gesichert sind"), f("Auf dem Rücksitz besteht keine Gurtpflicht", "Die Gurtpflicht gilt auf allen Sitzplätzen mit Gurten.")],
    explanation: "Alle Insassen müssen während der Fahrt angeschnallt sein. Erwachsene sind selbst verantwortlich, für Kinder trägt der Fahrer die Verantwortung.",
    legalReference: "§ 21a StVO; § 21 Abs. 1a StVO",
  }),
  q({
    code: "own-befoerderung-007", topic: "befoerderung", points: 3, difficulty: 0.3, tags: ["kindersitz", "airbag"],
    text: "Sie wollen eine rückwärtsgerichtete Babyschale auf dem Beifahrersitz befestigen. Was müssen Sie beachten?",
    answers: [t("Der Beifahrer-Frontairbag muss deaktiviert sein"), f("Nichts, der Airbag schützt das Kind zusätzlich", "Ein auslösender Airbag kann für ein Kind in einer rückwärtsgerichteten Schale tödlich sein."), f("Rückwärtsgerichtete Sitze sind auf dem Beifahrersitz generell verboten", "Sie sind erlaubt, wenn der Airbag abgeschaltet ist.")],
    explanation: "Rückwärtsgerichtete Kindersitze dürfen auf dem Beifahrersitz nur benutzt werden, wenn der Frontairbag deaktiviert ist. Andernfalls droht bei Auslösung schwere Verletzungsgefahr.",
    legalReference: "§ 35a StVZO; § 21 StVO",
  }),
  q({
    code: "own-befoerderung-008", topic: "befoerderung", points: 2, difficulty: 0.4, tags: ["ladung", "abmessungen"],
    text: "Welche Höhe und Breite dürfen Fahrzeug und Ladung zusammen höchstens haben?",
    answers: [t("Höchstens 4 Meter hoch und 2,55 Meter breit"), f("Höchstens 3 Meter hoch und 2 Meter breit", "Die erlaubten Maße sind größer."), f("Es gibt keine Begrenzung, wenn die Ladung gekennzeichnet ist", "Es gelten feste Höchstmaße.")],
    explanation: "Fahrzeug und Ladung dürfen zusammen höchstens 4 Meter hoch und 2,55 Meter breit sein. Bei größeren Abmessungen ist eine Ausnahmegenehmigung nötig.",
    legalReference: "§ 22 Abs. 2 StVO",
  }),
  q({
    code: "own-befoerderung-009", topic: "befoerderung", points: 2, difficulty: 0.2, tags: ["tiere", "ladung"],
    text: "Sie nehmen Ihren Hund im Auto mit. Was ist richtig?",
    answers: [t("Der Hund muss gesichert werden, etwa mit Gurtsystem, Transportbox oder Trenngitter"), f("Der Hund darf frei auf der Rückbank liegen", "Ungesicherte Tiere werden bei einer Bremsung zur Gefahr für alle Insassen."), f("Der Hund darf auf dem Schoß des Beifahrers sitzen", "Das gefährdet Beifahrer und Tier bei Airbagauslösung.")],
    explanation: "Tiere gelten rechtlich als Ladung und müssen so gesichert werden, dass sie weder den Fahrer ablenken noch bei einer Bremsung durch das Fahrzeug geschleudert werden.",
    legalReference: "§ 22 Abs. 1 StVO; § 23 Abs. 1 StVO",
  }),
  q({
    code: "own-befoerderung-010", topic: "befoerderung", points: 2, difficulty: 0.4, tags: ["anhaenger", "abreissseil"],
    text: "Wozu dient das Abreißseil an einem Anhänger mit Auflaufbremse?",
    answers: [t("Es betätigt die Bremse des Anhängers, wenn sich der Anhänger vom Zugfahrzeug löst"), f("Es hält den Anhänger zusätzlich an der Kupplung fest", "Das Seil ist kein zweiter Halt, sondern löst die Bremse aus."), f("Es verbindet die Elektrik von Anhänger und Zugfahrzeug", "Dafür gibt es den Stecker der Anhängerkupplung.")],
    explanation: "Das Abreißseil wird am Zugfahrzeug eingehängt. Löst sich der Anhänger, zieht das Seil die Feststellbremse des Anhängers und bremst ihn ab.",
    legalReference: "§ 41 StVZO",
  }),
  q({
    code: "own-befoerderung-011", topic: "befoerderung", points: 3, difficulty: 0.6, tags: ["zuladung", "gesamtmasse", "leermasse", "fahrzeugpapiere"], kind: "numeric", numericAnswer: 550, tolerance: 0, unit: "kg",
    text: "In der Zulassungsbescheinigung Teil I stehen für Ihren Pkw eine zulässige Gesamtmasse von 2.100 kg und eine Leermasse von 1.550 kg. Wie viel Kilogramm dürfen Sie höchstens zuladen (Personen und Gepäck zusammen)?",
    answers: [],
    explanation: "Zuladung = zulässige Gesamtmasse minus Leermasse = 2.100 kg minus 1.550 kg = 550 kg. Die Leermasse nach EU-Recht enthält bereits den Fahrer mit 75 kg und den zu 90 Prozent gefüllten Tank. Alle weiteren Insassen, Gepäck, Dachbox und Zubehör zählen zur Zuladung.",
    legalReference: "§ 34 StVZO",
  }),
  q({
    code: "own-befoerderung-012", topic: "befoerderung", points: 3, difficulty: 0.65, tags: ["anhaenger", "klasse_b", "gesamtmasse", "fahrerlaubnis"], kind: "numeric", numericAnswer: 1200, tolerance: 0, unit: "kg",
    text: "Ihr Zugfahrzeug hat eine zulässige Gesamtmasse von 2.300 kg. Welche zulässige Gesamtmasse darf ein Anhänger höchstens haben, damit Sie das Gespann noch mit der Klasse B (ohne Schlüsselzahl 96 und ohne BE) fahren dürfen? Angabe in Kilogramm.",
    answers: [],
    explanation: "Mit Klasse B darf ein Anhänger über 750 kg gezogen werden, wenn die zulässigen Gesamtmassen von Zugfahrzeug und Anhänger zusammen 3.500 kg nicht übersteigen. 3.500 kg minus 2.300 kg ergibt 1.200 kg. Maßgeblich sind immer die zulässigen Gesamtmassen aus den Papieren, nicht die tatsächliche Beladung.",
    legalReference: "§ 6 Abs. 1 FeV",
  }),
  q({
    code: "own-befoerderung-013", topic: "befoerderung", points: 3, difficulty: 0.7, tags: ["anhaenger", "klasse_b", "gesamtmasse", "fahrerlaubnis"],
    text: "Sie besitzen nur die Klasse B. Ihr Pkw hat eine zulässige Gesamtmasse von 2.400 kg, der Anhänger eine zulässige Gesamtmasse von 1.000 kg. Dürfen Sie das Gespann fahren?",
    answers: [t("Ja, weil die zulässigen Gesamtmassen zusammen 3.400 kg ergeben und damit 3.500 kg nicht überschreiten"), f("Nein, Anhänger über 750 kg erfordern immer die Klasse BE", "Anhänger über 750 kg sind mit Klasse B erlaubt, solange die Kombination höchstens 3.500 kg zulässige Gesamtmasse hat."), f("Nein, dafür ist mindestens die Schlüsselzahl 96 erforderlich", "B96 wird erst nötig, wenn die Kombination mehr als 3.500 kg, aber höchstens 4.250 kg zulässige Gesamtmasse hat."), f("Nur, wenn der Anhänger leer ist", "Es zählen die zulässigen Gesamtmassen, nicht die tatsächliche Beladung.")],
    explanation: "Für die Klasse B werden die zulässigen Gesamtmassen von Zugfahrzeug und Anhänger addiert. Bleibt die Summe bei höchstens 3.500 kg, darf der Anhänger auch schwerer als 750 kg sein. Hier ergeben sich 3.400 kg, das Gespann ist mit Klasse B erlaubt.",
    legalReference: "§ 6 Abs. 1 FeV",
  }),
  q({
    code: "own-befoerderung-014", topic: "befoerderung", points: 3, difficulty: 0.7, tags: ["anhaenger", "b96", "klasse_be", "fahrerlaubnis"],
    text: "Ihr Pkw hat eine zulässige Gesamtmasse von 2.000 kg, der Wohnanhänger ebenfalls 2.000 kg. Mit welcher Fahrerlaubnis dürfen Sie das Gespann fahren?",
    answers: [t("Mit Klasse B und der Schlüsselzahl 96, weil die Kombination 4.250 kg nicht überschreitet"), t("Mit der Klasse BE"), f("Mit der Klasse B allein", "Die zulässigen Gesamtmassen ergeben zusammen 4.000 kg und überschreiten damit die 3.500-kg-Grenze der Klasse B."), f("Mit Klasse B, wenn der Anhänger nur leicht beladen ist", "Maßgeblich sind die zulässigen Gesamtmassen, nicht das tatsächliche Gewicht.")],
    explanation: "Die Kombination hat zusammen 4.000 kg zulässige Gesamtmasse. Das übersteigt die 3.500 kg der Klasse B, liegt aber innerhalb der 4.250 kg, die mit der Schlüsselzahl 96 erlaubt sind. Alternativ deckt die Klasse BE Anhänger bis 3.500 kg zulässige Gesamtmasse ab.",
    legalReference: "§ 6 Abs. 1 FeV; Anlage 9 FeV",
  }),
  q({
    code: "own-befoerderung-015", topic: "befoerderung", points: 2, difficulty: 0.45, tags: ["anhaenger", "stuetzlast", "fahrzeugpapiere"],
    text: "Was ist die Stützlast und woraus ergibt sich ihr zulässiger Höchstwert?",
    answers: [t("Die Stützlast ist die Kraft, mit der die Anhängerdeichsel senkrecht auf die Kupplung des Zugfahrzeugs drückt"), t("Der zulässige Höchstwert ergibt sich aus den Angaben für Zugfahrzeug, Anhängerkupplung und Anhänger; der kleinste dieser Werte gilt"), f("Die Stützlast ist die Masse, die der Anhänger insgesamt wiegen darf", "Das ist die zulässige Gesamtmasse des Anhängers, nicht die Stützlast.")],
    explanation: "Die Stützlast wirkt senkrecht auf den Kugelkopf der Anhängerkupplung. Ihr Höchstwert steht in den Papieren des Zugfahrzeugs sowie auf den Typschildern von Kupplung und Anhänger; der niedrigste Wert ist verbindlich. Eine ausreichende Stützlast ist wichtig für die Fahrstabilität des Gespanns.",
    legalReference: "§ 44 StVZO",
  }),
  q({
    code: "own-befoerderung-016", topic: "befoerderung", points: 3, difficulty: 0.75, tags: ["anhaenger", "stuetzlast", "gesamtmasse", "fahrstabilitaet"],
    text: "Ihr Wohnanhänger hat beladen eine tatsächliche Gesamtmasse von 1.200 kg. Welche Stützlast ist nach der StVZO mindestens erforderlich?",
    answers: [t("Mindestens 25 kg; 4 Prozent wären zwar 48 kg, mehr als 25 kg werden aber nicht verlangt"), f("Mindestens 48 kg, also 4 Prozent der tatsächlichen Gesamtmasse", "Die 4-Prozent-Regel ist auf 25 kg gedeckelt; mehr muss die Stützlast nicht betragen."), f("Mindestens 120 kg, also 10 Prozent der Gesamtmasse", "Eine 10-Prozent-Regel gibt es in der StVZO nicht."), f("Es gibt keine Mindeststützlast, nur einen Höchstwert", "Die StVZO verlangt eine Mindeststützlast, weil das Gespann sonst instabil wird.")],
    explanation: "Die Stützlast eines Starrdeichselanhängers muss mindestens 4 Prozent seiner tatsächlichen Gesamtmasse betragen, mehr als 25 kg braucht sie jedoch nicht zu betragen. Bei 1.200 kg wären 4 Prozent 48 kg, verlangt werden also mindestens 25 kg. Für die Fahrstabilität sollte die Stützlast trotzdem möglichst nahe am zulässigen Höchstwert liegen.",
    legalReference: "§ 44 Abs. 3 StVZO",
  }),
  q({
    code: "own-befoerderung-017", topic: "befoerderung", points: 3, difficulty: 0.6, tags: ["anhaenger", "beladung", "stuetzlast", "ladungssicherung"],
    text: "Wie beladen Sie einen Anhänger richtig?",
    answers: [t("Schwere Gegenstände möglichst tief und über der Achse, leichte darüber"), t("Nach dem Beladen die Stützlast prüfen; sie darf den zulässigen Wert nicht überschreiten und sollte ihm möglichst nahekommen"), f("Schwere Gegenstände ganz nach hinten, damit die Deichsel entlastet wird", "Eine hecklastige Beladung verringert die Stützlast und führt zum Pendeln des Anhängers."), f("Ladung im Anhänger muss nicht gesichert werden, weil die Bordwände sie halten", "Auch im Anhänger muss Ladung gegen Verrutschen, Umfallen und Herabfallen gesichert sein.")],
    explanation: "Ein Anhänger fährt am stabilsten, wenn schwere Ladung tief und über der Achse liegt und die Stützlast nahe am zulässigen Maximum bleibt. Hecklastige oder ungesicherte Ladung macht das Gespann instabil und kann zum gefährlichen Pendeln führen.",
    legalReference: "§ 22 Abs. 1 StVO; § 44 Abs. 3 StVZO",
  }),
  q({
    code: "own-befoerderung-018", topic: "befoerderung", points: 3, difficulty: 0.6, tags: ["anhaenger", "tempo_100", "autobahn", "geschwindigkeit"],
    text: "Unter welchen Voraussetzungen dürfen Sie mit Ihrem Pkw und Anhänger auf der Autobahn 100 km/h fahren?",
    answers: [t("Nur mit einer Tempo-100-Plakette am Anhänger; dafür muss unter anderem das Zugfahrzeug ABS haben und die Anhängerreifen dürfen nicht älter als sechs Jahre sein"), f("Immer, weil auf Autobahnen für Pkw keine allgemeine Höchstgeschwindigkeit gilt", "Für Pkw mit Anhänger gilt auch auf Autobahnen grundsätzlich 80 km/h."), f("Sobald der Anhänger leer ist", "Die Beladung ändert nichts an der Höchstgeschwindigkeit von 80 km/h.")],
    explanation: "Für Pkw mit Anhänger gilt außerorts und auf Autobahnen eine Höchstgeschwindigkeit von 80 km/h. Nur mit einer Ausnahmegenehmigung (Tempo-100-Plakette) dürfen auf Autobahnen und Kraftfahrstraßen 100 km/h gefahren werden. Voraussetzungen sind unter anderem ABS am Zugfahrzeug, ein geeigneter Anhänger und Anhängerreifen, die nicht älter als sechs Jahre sind und mindestens für 120 km/h zugelassen sind.",
    legalReference: "§ 3 Abs. 3 Nr. 2 StVO; 9. Ausnahmeverordnung zur StVO",
  }),
  q({
    code: "own-befoerderung-019", topic: "befoerderung", points: 2, difficulty: 0.4, tags: ["anhaenger", "geschwindigkeit", "ausserorts", "autobahn"], kind: "numeric", numericAnswer: 80, tolerance: 0, unit: "km/h",
    text: "Sie fahren mit Ihrem Pkw und einem Anhänger ohne Tempo-100-Plakette auf der Autobahn. Wie schnell dürfen Sie höchstens fahren? Angabe in km/h.",
    answers: [],
    explanation: "Pkw mit Anhänger dürfen außerorts, auf Kraftfahrstraßen und auf Autobahnen höchstens 80 km/h fahren. Nur mit der Tempo-100-Plakette sind auf Autobahnen und Kraftfahrstraßen 100 km/h zulässig.",
    legalReference: "§ 3 Abs. 3 Nr. 2 StVO",
  }),
  q({
    code: "own-befoerderung-020", topic: "befoerderung", points: 3, difficulty: 0.6, tags: ["anhaenger", "rueckwaertsfahren", "rangieren"],
    text: "Sie rangieren rückwärts mit einem Anhänger. Welche Aussagen treffen zu?",
    answers: [t("Das Anhängerheck schwenkt zunächst in die dem Lenkeinschlag entgegengesetzte Richtung: Lenkrad nach rechts, Anhänger schwenkt nach links"), t("Kurze Anhänger reagieren schneller auf Lenkbewegungen und knicken leichter ein"), f("Der Anhänger folgt dem Lenkeinschlag genau wie das Zugfahrzeug", "Beim Rückwärtsfahren wird der Anhänger geschoben und läuft der Lenkbewegung entgegen."), f("Rückwärtsfahren mit Anhänger ist nur mit Einweiser erlaubt", "Ein Einweiser ist bei unübersichtlicher Lage sinnvoll, aber nicht generell vorgeschrieben.")],
    explanation: "Beim Rückwärtsfahren wird der Anhänger geschoben und bewegt sich entgegen dem Lenkeinschlag. Kleine, langsame Lenkbewegungen und ein gutes Beobachten über die Außenspiegel sind entscheidend. Wer keine ausreichende Sicht hat, muss sich einweisen lassen.",
    legalReference: "§ 9 Abs. 5 StVO",
  }),
  q({
    code: "own-befoerderung-021", topic: "befoerderung", points: 3, difficulty: 0.6, tags: ["anhaenger", "kennzeichen", "rueckstrahler", "zulassung"],
    text: "Welche Aussagen zu Kennzeichen und Ausrüstung eines Pkw-Anhängers treffen zu?",
    answers: [t("Der Anhänger braucht eine eigene Zulassung und ein eigenes amtliches Kennzeichen"), t("Anhänger sind hinten mit dreieckigen roten Rückstrahlern ausgerüstet, an Kraftfahrzeugen sind dreieckige Rückstrahler nicht zulässig"), f("Am Anhänger wird einfach das Kennzeichen des Zugfahrzeugs wiederholt", "Anhänger führen ein eigenes Kennzeichen; nur an Ladungsträgern wie Fahrradträgern wird das Kennzeichen des Pkw wiederholt."), f("Ein Anhänger bis 750 kg braucht keine eigene Beleuchtung", "Auch leichte Anhänger benötigen Schlussleuchten, Bremsleuchten, Blinker und Rückstrahler.")],
    explanation: "Anhänger sind eigenständige Fahrzeuge mit eigener Zulassungsbescheinigung und eigenem Kennzeichen. Ihre roten Rückstrahler sind dreieckig, damit sie im Dunkeln als Anhänger erkennbar sind; an Kraftfahrzeugen sind dreieckige Rückstrahler verboten. Die Beleuchtung des Anhängers ist unabhängig von seiner Masse vorgeschrieben.",
    legalReference: "§ 53 StVZO; § 3 FZV",
  }),
  q({
    code: "own-befoerderung-022", topic: "befoerderung", points: 3, difficulty: 0.5, tags: ["anhaenger", "abfahrtkontrolle", "abreissseil", "beleuchtung"],
    text: "Was prüfen Sie, bevor Sie mit einem Anhänger losfahren?",
    answers: [t("Kupplung eingerastet und verriegelt, Abreißseil am Zugfahrzeug eingehängt"), t("Elektrostecker verbunden, Beleuchtung geprüft, Stützrad hochgekurbelt und gesichert, Ladung gesichert"), f("Das Abreißseil muss nur bei Fahrten über 100 km eingehängt werden", "Das Abreißseil ist bei jeder Fahrt einzuhängen, sonst bremst der Anhänger beim Abreißen nicht."), f("Der Reifendruck des Anhängers ist unwichtig, weil er nicht angetrieben wird", "Zu niedriger Druck lässt Anhängerreifen überhitzen und begünstigt Pendeln und Reifenplatzer.")],
    explanation: "Der Fahrer ist dafür verantwortlich, dass Zug und Ladung vorschriftsmäßig und verkehrssicher sind. Zur Abfahrtkontrolle gehören Kupplung, Abreißseil, Elektrik und Beleuchtung, Stützrad, Reifendruck und Ladungssicherung.",
    legalReference: "§ 23 Abs. 1 StVO",
  }),
  q({
    code: "own-befoerderung-023", topic: "befoerderung", points: 3, difficulty: 0.6, tags: ["anhaenger", "verkehrszeichen", "zeichen_253", "gesamtmasse"],
    text: "Sie fahren mit Ihrem Pkw (zulässige Gesamtmasse 2.000 kg) und einem Anhänger (zulässige Gesamtmasse 2.000 kg). Vor Ihnen steht das Zeichen 253 (Verbot für Kraftfahrzeuge über 3,5 t). Was gilt?",
    answers: [t("Sie dürfen weiterfahren, denn das Zeichen gilt nicht für Pkw, auch nicht mit Anhänger"), f("Sie dürfen nicht weiterfahren, weil das Gespann zusammen über 3,5 t hat", "Das Zeichen richtet sich an Kraftfahrzeuge über 3,5 t zulässiger Gesamtmasse und nimmt Pkw und Kraftomnibusse ausdrücklich aus."), f("Sie dürfen nur weiterfahren, wenn der Anhänger leer ist", "Auf die Beladung kommt es nicht an; Pkw sind vom Verbot ausgenommen.")],
    explanation: "Zeichen 253 verbietet die Durchfahrt für Kraftfahrzeuge mit einer zulässigen Gesamtmasse über 3,5 t einschließlich ihrer Anhänger sowie für Zugmaschinen. Personenkraftwagen und Kraftomnibusse sind ausgenommen, auch wenn sie einen Anhänger ziehen.",
    legalReference: "Anlage 2 StVO, Zeichen 253",
  }),
  q({
    code: "own-befoerderung-024", topic: "befoerderung", points: 3, difficulty: 0.6, tags: ["anhaenger", "verkehrszeichen", "zusatzzeichen", "zeichen_250"],
    text: "Ein Zeichen 250 (Verbot für Fahrzeuge aller Art) trägt das Zusatzzeichen mit dem Sinnbild Pkw mit Anhänger (Nr. 1010-59). Was gilt?",
    answers: [t("Das Verbot gilt nur für Pkw mit Anhänger; ohne Anhänger dürfen Sie einfahren"), f("Kein Fahrzeug darf einfahren", "Das Zusatzzeichen beschränkt das Verbot auf die dargestellte Fahrzeugart."), f("Pkw mit Anhänger sind vom Verbot ausgenommen", "Eine Ausnahme zeigt das Zusatzzeichen mit dem Wort frei (Nr. 1024-11); das Sinnbild allein beschränkt das Verbot auf diese Fahrzeuge.")],
    explanation: "Ein Zusatzzeichen mit einem Sinnbild ohne den Zusatz frei beschränkt das Verbot auf die abgebildete Fahrzeugart. Zeichen 250 mit dem Sinnbild Pkw mit Anhänger verbietet also nur Gespannen die Einfahrt. Steht dagegen frei auf dem Zusatzzeichen, sind diese Fahrzeuge vom Verbot ausgenommen.",
    legalReference: "§ 39 Abs. 3 StVO; Anlage 2 StVO, Zeichen 250",
  }),
  q({
    code: "own-befoerderung-025", topic: "befoerderung", points: 3, difficulty: 0.65, tags: ["abmessungen", "hoehe", "verkehrszeichen", "zeichen_265", "dachlast"],
    text: "Vor einer Unterführung steht das Zeichen 265 mit der Angabe 2,5 m. Ihr Pkw ist laut Papieren 1,6 m hoch, mit der beladenen Dachbox misst er tatsächlich 2,6 m. Dürfen Sie durchfahren?",
    answers: [t("Nein, denn maßgeblich ist die tatsächliche Höhe einschließlich Ladung und Dachbox"), f("Ja, weil die Fahrzeughöhe laut Papieren unter 2,5 m liegt", "Das Zeichen bezieht sich auf die tatsächliche Höhe von Fahrzeug und Ladung."), f("Ja, wenn Sie mit Schrittgeschwindigkeit durchfahren", "Die Geschwindigkeit ändert nichts an der Höhe; die Ladung würde anstoßen.")],
    explanation: "Zeichen 265 verbietet die Durchfahrt für Fahrzeuge, deren tatsächliche Höhe einschließlich Ladung den angegebenen Wert überschreitet. Wer eine Dachbox oder Dachlast fährt, muss die Gesamthöhe kennen und bei Unterführungen und Parkhäusern einplanen.",
    legalReference: "Anlage 2 StVO, Zeichen 265",
  }),
  q({
    code: "own-befoerderung-026", topic: "befoerderung", points: 3, difficulty: 0.6, tags: ["ladung", "ueberstand", "breite", "beleuchtung"],
    text: "Ihre Ladung ragt seitlich 60 cm über die Begrenzungsleuchten des Fahrzeugs hinaus. Sie fahren bei Dunkelheit. Was gilt?",
    answers: [t("Die Ladung muss seitlich nach vorn mit einer weißen und nach hinten mit einer roten Leuchte kenntlich gemacht werden"), t("Fahrzeug und Ladung dürfen zusammen nicht breiter als 2,55 m sein"), f("Seitlicher Überstand von Ladung ist grundsätzlich verboten", "Er ist innerhalb der Höchstbreite erlaubt; ab 40 cm über die Leuchten hinaus ist bei Dunkelheit eine Kennzeichnung nötig."), f("Eine hellrote Fahne am Rand genügt auch bei Dunkelheit", "Die Fahne ist für den Überstand nach hinten vorgesehen; seitlich sind bei Dunkelheit Leuchten vorgeschrieben.")],
    explanation: "Ragt Ladung seitlich mehr als 40 cm über die Begrenzungs- oder Schlussleuchten hinaus, ist sie bei Dunkelheit nach vorn durch eine Leuchte mit weißem und nach hinten durch eine Leuchte mit rotem Licht kenntlich zu machen, höchstens 40 cm vom Ladungsrand und höchstens 1,5 m über der Fahrbahn. Die Gesamtbreite von 2,55 m darf dabei nicht überschritten werden.",
    legalReference: "§ 22 Abs. 2 und 5 StVO",
  }),
  q({
    code: "own-befoerderung-027", topic: "befoerderung", points: 3, difficulty: 0.7, tags: ["ladung", "ueberstand", "dachlast"],
    text: "Auf dem Dachgepäckträger Ihres Pkw (Ladung in 1,8 m Höhe) transportieren Sie lange Latten. Dürfen sie nach vorn über das Fahrzeug hinausragen?",
    answers: [t("Nein, bis zu einer Höhe von 2,5 m darf Ladung nach vorn nicht über das Fahrzeug hinausragen"), f("Ja, bis zu 50 cm", "Die 50 cm gelten nur für Ladung, die höher als 2,5 m über der Fahrbahn liegt."), f("Ja, bis zu 1 m mit einer hellroten Fahne", "Die Fahne kennzeichnet den Überstand nach hinten; nach vorn gilt in dieser Höhe ein Verbot.")],
    explanation: "Ladung darf bis zu einer Höhe von 2,5 m nicht nach vorn über das Fahrzeug hinausragen. Nur Ladung oberhalb von 2,5 m darf bis zu 50 cm nach vorn überstehen. Lange Gegenstände auf einem Pkw-Dach müssen deshalb nach hinten ausgerichtet und ab 1 m Überstand gekennzeichnet werden.",
    legalReference: "§ 22 Abs. 3 StVO",
  }),
  q({
    code: "own-befoerderung-028", topic: "befoerderung", points: 3, difficulty: 0.7, tags: ["ladung", "ueberstand", "kennzeichnung", "fahrtstrecke"],
    text: "Sie transportieren Rohre, die 2,5 m über das Fahrzeugheck hinausragen. Die Fahrt geht über 60 km. Welche Aussagen treffen zu?",
    answers: [t("Der Überstand ist zulässig, weil bei Fahrten bis 100 km bis zu 3 m nach hinten erlaubt sind"), t("Das Ende ist mit einer hellroten Fahne, einem hellroten Schild oder einem hellroten zylindrischen Körper zu kennzeichnen, bei Dunkelheit zusätzlich mit roter Leuchte und rotem Rückstrahler"), f("Der Überstand ist unzulässig, weil nach hinten höchstens 1,5 m erlaubt sind", "1,5 m gelten für längere Strecken; bei Fahrten bis 100 km sind 3 m zulässig."), f("Die Kennzeichnung darf beliebig hoch angebracht werden", "Fahne, Schild oder Körper dürfen nicht höher als 1,5 m über der Fahrbahn angebracht sein.")],
    explanation: "Nach hinten darf Ladung bis 1,5 m hinausragen, bei Fahrten bis 100 km bis zu 3 m. Ragt sie mehr als 1 m über die Rückstrahler hinaus, ist das Ende mit einer hellroten Fahne oder einem hellroten Schild von mindestens 30 mal 30 cm oder einem hellroten zylindrischen Körper zu kennzeichnen, höchstens 1,5 m über der Fahrbahn. Bei Dunkelheit kommen eine rote Leuchte und ein roter Rückstrahler hinzu.",
    legalReference: "§ 22 Abs. 4 StVO",
  }),
  q({
    code: "own-befoerderung-029", topic: "befoerderung", points: 2, difficulty: 0.35, tags: ["ladung", "ueberstand", "kennzeichnung"], kind: "numeric", numericAnswer: 1, tolerance: 0, unit: "m",
    text: "Ab welchem Überstand nach hinten über die Rückstrahler des Fahrzeugs muss das Ende der Ladung gekennzeichnet werden? Angabe in Metern.",
    answers: [],
    explanation: "Ragt das äußerste Ende der Ladung mehr als 1 m über die Rückstrahler hinaus, muss es mit einer hellroten Fahne, einem hellroten Schild oder einem hellroten zylindrischen Körper kenntlich gemacht werden. Bei Dunkelheit sind zusätzlich eine rote Leuchte und ein roter Rückstrahler nötig.",
    legalReference: "§ 22 Abs. 4 StVO",
  }),
  q({
    code: "own-befoerderung-030", topic: "befoerderung", points: 3, difficulty: 0.6, tags: ["gurt", "gurtpflicht", "ausnahmen"],
    text: "In welchen Fällen besteht keine Gurtpflicht?",
    answers: [t("Beim Rückwärtsfahren und bei Fahrten mit Schrittgeschwindigkeit, etwa auf Parkplätzen"), t("Für Personen, die aus gesundheitlichen Gründen eine Ausnahmegenehmigung von der Gurtpflicht besitzen; die Bescheinigung ist mitzuführen"), f("Für Taxifahrer während der Beförderung von Fahrgästen", "Diese frühere Ausnahme gilt nicht mehr; auch Taxifahrer müssen sich anschnallen."), t("Im Haus-zu-Haus-Verkehr, wenn das Fahrzeug im Auslieferungsbezirk regelmäßig in kurzen Abständen verlassen werden muss")],
    explanation: "Die Gurtpflicht gilt grundsätzlich für alle Insassen. Ausnahmen bestehen unter anderem bei Fahrten mit Schrittgeschwindigkeit wie Rückwärtsfahren und Rangieren auf Parkplätzen sowie im Haus-zu-Haus-Lieferverkehr. Wer aus gesundheitlichen Gründen keinen Gurt tragen kann, braucht eine Ausnahmegenehmigung der Straßenverkehrsbehörde auf Grundlage einer ärztlichen Bescheinigung und muss die Bescheinigung mitführen.",
    legalReference: "§ 21a Abs. 1 Satz 2 Nr. 2 und 3 StVO; § 46 Abs. 1 Nr. 5b StVO",
  }),
  q({
    code: "own-befoerderung-031", topic: "befoerderung", points: 3, difficulty: 0.6, tags: ["personenbefoerderung", "wohnanhaenger", "ladeflaeche"],
    text: "Wo dürfen Personen nicht mitgenommen werden?",
    answers: [t("In Wohnanhängern hinter Kraftfahrzeugen"), t("Auf der Ladefläche oder im Laderaum eines Pkw"), f("Auf dem Beifahrersitz eines Pkw mit Frontairbag", "Das ist erlaubt; nur bei rückwärtsgerichteten Kindersitzen muss der Airbag deaktiviert sein."), f("Auf Rücksitzen ohne Kopfstützen", "Die StVO verbietet das nicht; vorhandene Kopfstützen sollten aber richtig eingestellt sein.")],
    explanation: "Die Mitnahme von Personen in Wohnanhängern sowie auf Ladeflächen und in Laderäumen von Kraftfahrzeugen ist verboten, weil dort weder Sitze noch Gurte Schutz bieten. Ausnahmen gibt es nur für bestimmte Betriebsfahrten mit Lkw. In Pkw dürfen nur so viele Personen mitfahren, wie gurtgesicherte Sitzplätze vorhanden sind.",
    legalReference: "§ 21 Abs. 1 und 2 StVO",
  }),
  q({
    code: "own-befoerderung-032", topic: "befoerderung", points: 3, difficulty: 0.55, tags: ["personenbefoerderung", "sitzplaetze", "gurt", "kinder"],
    text: "Ihr Pkw hat fünf mit Sicherheitsgurten ausgerüstete Sitzplätze. Sechs Personen wollen mitfahren, darunter ein Kleinkind. Was gilt?",
    answers: [t("Die Fahrt ist so nicht erlaubt; es dürfen nicht mehr Personen befördert werden, als mit Gurten ausgerüstete Sitzplätze vorhanden sind"), f("Die Fahrt ist erlaubt, wenn das Kleinkind auf dem Schoß eines Erwachsenen gehalten wird", "Ein Kind auf dem Schoß kann bei einem Aufprall nicht gehalten werden und ist nicht vorschriftsmäßig gesichert."), f("Die Fahrt ist erlaubt, solange sie innerorts bleibt", "Die Regel gilt unabhängig von Strecke und Geschwindigkeit.")],
    explanation: "In Kraftfahrzeugen dürfen nicht mehr Personen befördert werden, als mit Sicherheitsgurten ausgerüstete Sitzplätze vorhanden sind. Jedes Kind braucht zudem einen eigenen Platz mit passender Rückhalteeinrichtung. Ein Kind auf dem Schoß wird bei einem Aufprall zum Geschoss.",
    legalReference: "§ 21 Abs. 1 und 1a StVO",
  }),
  q({
    code: "own-befoerderung-033", topic: "befoerderung", points: 3, difficulty: 0.7, tags: ["kindersitz", "kinder", "ausnahmen", "ruecksitz"],
    text: "Auf der Rückbank Ihres Pkw sind bereits zwei Kindersitze befestigt, für einen dritten ist kein Platz. Ein dreijähriges Kind mit 100 cm Körpergröße soll zusätzlich mitfahren. Was gilt?",
    answers: [t("Das Kind darf ausnahmsweise auf dem Rücksitz mit dem vorhandenen Sicherheitsgurt gesichert werden, weil kein Platz für eine weitere Rückhalteeinrichtung ist"), f("Das Kind darf ungesichert in der Mitte sitzen", "Eine Beförderung ohne jede Sicherung ist nie zulässig."), f("Das Kind darf auf dem Beifahrersitz ohne Kindersitz mitfahren", "Die Ausnahme gilt nur für Rücksitze."), f("Das Kind darf nicht mitfahren", "Die StVO lässt für diesen Fall eine Ausnahme für Kinder ab drei Jahren zu.")],
    explanation: "Ist wegen bereits befestigter Kindersitze auf den Rücksitzen kein Platz für eine weitere Rückhalteeinrichtung, darf ein Kind ab dem vollendeten dritten Lebensjahr dort mit dem Sicherheitsgurt gesichert werden. Diese Ausnahme gilt nur für Rücksitze; sicherer bleibt immer ein passender Kindersitz.",
    legalReference: "§ 21 Abs. 1a StVO",
    reviewStatus: "needs_verification",
  }),
  q({
    code: "own-befoerderung-034", topic: "befoerderung", points: 2, difficulty: 0.45, tags: ["kindersitz", "kinder", "isofix", "zulassung"],
    text: "Welche Anforderungen muss ein Kindersitz erfüllen?",
    answers: [t("Er muss amtlich genehmigt sein, etwa nach der ECE-Regelung 44 oder der ECE-Regelung 129 (i-Size), und zu Größe beziehungsweise Gewicht des Kindes passen"), t("Er muss nach Herstellerangaben für das Fahrzeug und den Sitzplatz geeignet sein, zum Beispiel über Isofix oder den Fahrzeuggurt korrekt befestigt werden"), f("Jedes Kissen, das das Kind höher setzt, ist ausreichend", "Nur genehmigte Rückhalteeinrichtungen mit Prüfzeichen sind zulässig."), f("Kindersitze dürfen nur auf dem Beifahrersitz verwendet werden", "Kindersitze dürfen auf allen geeigneten Plätzen verwendet werden; der Rücksitz gilt als sicherster Platz.")],
    explanation: "Kinder unter zwölf Jahren, die kleiner als 150 cm sind, müssen in einer amtlich genehmigten Rückhalteeinrichtung sitzen. Das Prüfzeichen nach ECE-R 44 oder ECE-R 129 muss am Sitz vorhanden sein, und der Sitz muss nach Herstellerangaben zu Kind und Fahrzeug passen. Der Fahrer ist für die richtige Sicherung verantwortlich.",
    legalReference: "§ 21 Abs. 1a StVO",
  }),
  q({
    code: "own-befoerderung-035", topic: "befoerderung", points: 3, difficulty: 0.6, tags: ["kindersitz", "kinder", "beifahrersitz", "airbag"],
    text: "Ein achtjähriges Kind mit 130 cm Körpergröße soll auf dem Beifahrersitz mitfahren. Was gilt?",
    answers: [t("Erlaubt, wenn das Kind in einer passenden, vorwärtsgerichteten Rückhalteeinrichtung sitzt; der Beifahrersitz sollte möglichst weit zurückgestellt werden"), f("Verboten, Kinder unter zwölf Jahren dürfen nicht auf dem Beifahrersitz mitfahren", "Ein solches Verbot gibt es nicht; entscheidend ist die richtige Sicherung."), f("Erlaubt ohne Kindersitz, weil das Kind älter als sechs Jahre ist", "Bis zum zwölften Geburtstag und unter 150 cm ist eine Rückhalteeinrichtung Pflicht.")],
    explanation: "Kinder dürfen auf dem Beifahrersitz mitfahren, wenn sie vorschriftsmäßig gesichert sind. Ein achtjähriges Kind unter 150 cm braucht eine passende Rückhalteeinrichtung, zum Beispiel eine Sitzerhöhung mit Rückenlehne. Der Frontairbag muss nur bei rückwärtsgerichteten Systemen deaktiviert werden; dennoch sollte der Sitz weit zurückgestellt werden.",
    legalReference: "§ 21 Abs. 1a StVO",
  }),
  q({
    code: "own-befoerderung-036", topic: "befoerderung", points: 3, difficulty: 0.65, tags: ["gurt", "gurtpflicht", "schwangere", "sicherheit"],
    text: "Welche Aussagen zum richtigen Anlegen des Sicherheitsgurts treffen zu?",
    answers: [t("Der Beckengurt muss straff und tief über dem Becken liegen, nicht über dem Bauch"), t("Der Schultergurt verläuft über die Schultermitte und nicht am Hals; dicke Kleidung verringert die Schutzwirkung"), f("Ein verdrehter Gurt ist unproblematisch, solange er einrastet", "Ein verdrehter Gurt verteilt die Kräfte auf eine schmale Fläche und kann schwere Verletzungen verursachen."), f("Schwangere sind generell von der Gurtpflicht befreit", "Schwangere müssen sich anschnallen; der Beckengurt liegt unterhalb des Bauches. Eine Befreiung gibt es nur mit ärztlicher Bescheinigung.")],
    explanation: "Nur ein richtig angelegter Gurt schützt: Beckengurt tief über den Hüftknochen, Schultergurt über die Schultermitte, alles straff und unverdreht. Dicke Jacken und Gurtclips lockern den Gurt und erhöhen die Belastung beim Aufprall. Schwangere schnallen sich mit dem Beckengurt unterhalb des Bauches an.",
    legalReference: "§ 21a Abs. 1 StVO",
  }),
  q({
    code: "own-befoerderung-037", topic: "befoerderung", points: 3, difficulty: 0.6, tags: ["fahrradtraeger", "stuetzlast", "kennzeichen", "ladung"],
    text: "Sie montieren einen Fahrradträger auf der Anhängerkupplung Ihres Pkw. Welche Aussagen treffen zu?",
    answers: [t("Träger und Fahrräder dürfen zusammen die zulässige Stützlast der Anhängerkupplung nicht überschreiten"), t("Verdeckte Leuchten und das verdeckte Kennzeichen müssen am Träger wiederholt werden"), f("Es genügt, das Kennzeichen des Fahrzeugs auf ein Schild zu schreiben und am Träger zu befestigen", "Am Träger muss ein amtliches Kennzeichen mit derselben Aufschrift angebracht sein."), f("Der Träger darf beliebig weit nach hinten hinausragen", "Auch für Ladungsträger gelten die Regeln über Überstand und Kennzeichnung nach hinten.")],
    explanation: "Ein Heckträger belastet die Kupplung wie ein Anhänger: Eigengewicht des Trägers plus Fahrräder dürfen die zulässige Stützlast nicht überschreiten. Werden Kennzeichen oder Leuchten verdeckt, müssen sie am Träger vorhanden und funktionsfähig sein. Das Fahrverhalten ändert sich spürbar, deshalb Geschwindigkeit und Ladungssicherung regelmäßig kontrollieren.",
    legalReference: "§ 22 StVO; § 23 Abs. 1 StVO; § 44 StVZO",
  }),
  q({
    code: "own-befoerderung-038", topic: "befoerderung", points: 2, difficulty: 0.5, tags: ["ladung", "ladungssicherung", "kofferraum", "kombi"],
    text: "Wie beladen Sie den Kofferraum eines Kombis richtig?",
    answers: [t("Schwere Gegenstände nach unten und dicht an die Rückenlehne, leichte Gegenstände darüber"), t("Ladung nicht über die Oberkante der Rücksitzlehne stapeln; wenn doch, Trenngitter oder Trennnetz verwenden"), f("Schwere Gegenstände nach oben, damit sie leichter ausgeladen werden können", "Hohe schwere Ladung hebt den Schwerpunkt und wird bei einer Bremsung nach vorn geschleudert."), f("Ladung möglichst weit hinten platzieren, damit die Vorderachse entlastet wird", "Hecklastige Beladung verschlechtert Lenkung und Fahrstabilität; Ladung gehört möglichst weit nach vorn.")],
    explanation: "Ladung wird so verstaut, dass sie bei Vollbremsung oder Ausweichmanöver nicht verrutscht: schwer nach unten und nach vorn an die Rücksitzlehne, formschlüssig und mit Zurrgurten oder Antirutschmatten gesichert. Ragt Ladung über die Lehne hinaus, schützt ein Trenngitter oder -netz die Insassen.",
    legalReference: "§ 22 Abs. 1 StVO",
  }),
  q({
    code: "own-befoerderung-039", topic: "befoerderung", points: 2, difficulty: 0.4, tags: ["tiere", "ladung", "transportbox", "ladungssicherung"],
    text: "Sie transportieren eine Katze in einer Transportbox. Wo bringen Sie die Box am sichersten unter?",
    answers: [t("Im Fußraum hinter einem Vordersitz oder im Kofferraum quer zur Fahrtrichtung, gegen Verrutschen gesichert"), f("Auf dem Beifahrersitz ohne Befestigung", "Bei einer Bremsung wird die Box nach vorn geschleudert und kann beim Airbagauslösen gefährlich werden."), f("Auf der Hutablage, damit das Tier hinaussehen kann", "Gegenstände auf der Hutablage werden bei einem Aufprall zu Geschossen.")],
    explanation: "Tiere gelten als Ladung und müssen gesichert werden. Eine Transportbox steht sicher im Fußraum hinter einem Vordersitz oder im Kofferraum, dort quer zur Fahrtrichtung und mit Gurt oder Zurrgurt gegen Verrutschen gesichert. So wird weder der Fahrer abgelenkt noch das Tier bei einer Bremsung verletzt.",
    legalReference: "§ 22 Abs. 1 StVO; § 23 Abs. 1 StVO",
  }),
  q({
    code: "own-befoerderung-040", topic: "befoerderung", points: 3, difficulty: 0.6, tags: ["ladung", "sicht", "spiegel", "verkehrssicherheit"],
    text: "Sie transportieren einen Schrank, der die Sicht durch die Heckscheibe vollständig versperrt und den Innenspiegel unbrauchbar macht. Dürfen Sie so fahren?",
    answers: [t("Ja, wenn beide Außenspiegel eine ausreichende Sicht nach hinten ermöglichen und die Ladung sicher verstaut ist"), f("Nein, die Sicht durch die Heckscheibe muss immer frei bleiben", "Wie bei Kastenwagen genügt die Sicht über zwei Außenspiegel, wenn der Innenspiegel keine Sicht mehr bietet."), f("Nur, wenn ein Beifahrer die Beobachtung nach hinten übernimmt", "Ein Beifahrer ersetzt keine vorgeschriebene Spiegelsicht.")],
    explanation: "Der Fahrer muss dafür sorgen, dass seine Sicht durch die Ladung nicht unzulässig beeinträchtigt wird. Bietet der Innenspiegel keine ausreichende Sicht nach hinten, muss diese über den linken und rechten Außenspiegel möglich sein, wie bei Kastenwagen ohne Heckscheibe. Die Ladung selbst muss zusätzlich gegen Verrutschen gesichert sein.",
    legalReference: "§ 23 Abs. 1 StVO; § 56 StVZO",
  }),
];
