// Übungsfragen zum Thema "beleuchtung" (eigene Formulierungen, kein amtlicher Prüfungsinhalt).
import type { Question } from "../types";
import { q, t, f } from "./_helpers";

export const beleuchtung: readonly Question[] = [
  q({
    code: "own-beleuchtung-001", topic: "beleuchtung", points: 3, difficulty: 0.2, tags: ["nebelschlussleuchte", "nebel", "sichtweite"],
    text: "Wann dürfen Sie die Nebelschlussleuchte einschalten?",
    answers: [t("Nur bei Nebel, wenn die Sichtweite weniger als 50 Meter beträgt"), f("Bei jedem Regen", "Bei Regen blendet die Nebelschlussleuchte nachfolgende Fahrer."), f("Immer bei Dunkelheit auf der Autobahn", "Sie ist ausschließlich bei Nebel mit geringer Sichtweite erlaubt.")],
    explanation: "Die Nebelschlussleuchte darf nur bei Nebel mit Sichtweite unter 50 Metern eingeschaltet werden. Dann gilt zugleich die Höchstgeschwindigkeit von 50 km/h.",
    mnemonic: "Nebelschlussleuchte: unter 50 Meter Sicht, höchstens 50 km/h.",
    legalReference: "§ 17 Abs. 3 StVO",
  }),
  q({
    code: "own-beleuchtung-002", topic: "beleuchtung", points: 3, difficulty: 0.3, tags: ["tagfahrlicht", "abblendlicht", "regen"],
    text: "Bei starkem Regen am Tag ist das Tagfahrlicht eingeschaltet. Ist das ausreichend?",
    answers: [t("Nein, bei Sichtbehinderung muss Abblendlicht eingeschaltet werden, weil beim Tagfahrlicht die Rückleuchten meist aus bleiben"), f("Ja, Tagfahrlicht reicht bei jeder Witterung am Tag", "Bei Regen, Nebel oder Schnee ist Abblendlicht vorgeschrieben."), f("Nein, es muss Fernlicht eingeschaltet werden", "Fernlicht würde bei Regen blenden.")],
    explanation: "Tagfahrlicht macht nur nach vorn sichtbar. Wenn Regen, Nebel oder Schneefall die Sicht behindern, ist auch am Tag Abblendlicht Pflicht, damit auch die Rückleuchten leuchten.",
    legalReference: "§ 17 Abs. 3 StVO",
  }),
  q({
    code: "own-beleuchtung-003", topic: "beleuchtung", points: 3, difficulty: 0.3, tags: ["fernlicht", "blenden", "dunkelheit"],
    text: "Wann müssen Sie das Fernlicht abblenden?",
    answers: [t("Bei Gegenverkehr"), t("Wenn Sie dicht hinter einem anderen Fahrzeug fahren"), t("Innerorts auf ausreichend beleuchteten Straßen"), f("Bei Nebel, weil Fernlicht die Sicht verbessert", "Fernlicht wird vom Nebel reflektiert und verschlechtert die Sicht.")],
    explanation: "Fernlicht darf niemanden blenden. Es ist abzublenden bei Gegenverkehr, beim Auffahren auf andere und auf innerorts ausreichend beleuchteten Straßen.",
    legalReference: "§ 17 Abs. 2 StVO",
  }),
  q({
    code: "own-beleuchtung-004", topic: "beleuchtung", points: 2, difficulty: 0.3, tags: ["lichthupe", "ueberholen", "ausserorts"],
    text: "Wozu dürfen Sie die Lichthupe benutzen?",
    answers: [t("Außerorts zum Ankündigen des Überholens und zum Warnen vor Gefahren"), f("Um Vorfahrt zu erzwingen", "Die Lichthupe gibt kein Vorrecht."), f("Um andere auf Blitzer hinzuweisen", "Das ist keine zulässige Verwendung.")],
    explanation: "Die Lichthupe darf als Warnzeichen benutzt werden, außerorts auch um das Überholen anzukündigen. Sie darf niemanden blenden oder nötigen.",
    legalReference: "§ 16 Abs. 1 StVO; § 5 Abs. 5 StVO",
  }),
  q({
    code: "own-beleuchtung-005", topic: "beleuchtung", points: 3, difficulty: 0.3, tags: ["warnblinklicht"],
    text: "Wann dürfen Sie das Warnblinklicht einschalten?",
    answers: [t("Wenn Sie sich einem Stauende nähern und andere warnen wollen"), t("Wenn Ihr Fahrzeug liegen geblieben ist"), t("Beim Abschleppen, und zwar an beiden Fahrzeugen"), f("Beim Halten in zweiter Reihe zum Ausladen", "Das Warnblinklicht macht verbotenes Halten nicht erlaubt.")],
    explanation: "Das Warnblinklicht ist für Gefahrensituationen vorgesehen: Stauende, liegen gebliebenes Fahrzeug, Abschleppen. Zum Absichern von Parkverstößen ist es nicht erlaubt.",
    legalReference: "§ 15 StVO; § 16 Abs. 2 StVO",
  }),
  q({
    code: "own-beleuchtung-006", topic: "beleuchtung", points: 2, difficulty: 0.4, tags: ["parken", "standlicht", "ausserorts", "dunkelheit"],
    text: "Muss ein geparktes Fahrzeug bei Dunkelheit beleuchtet werden?",
    answers: [t("Außerorts ja, mit Standlicht oder Parkleuchten"), t("Innerorts nicht, wenn die Straßenbeleuchtung das Fahrzeug auf ausreichende Entfernung erkennbar macht"), f("Nie, ein geparktes Fahrzeug braucht keine Beleuchtung", "Außerorts und auf unbeleuchteten Straßen ist die Beleuchtung Pflicht.")],
    explanation: "Haltende und parkende Fahrzeuge müssen bei Dunkelheit beleuchtet sein, außer innerorts, wo die Straßenbeleuchtung sie ausreichend sichtbar macht oder ein beleuchteter Parkplatz genutzt wird.",
    legalReference: "§ 17 Abs. 4 StVO",
  }),
  q({
    code: "own-beleuchtung-007", topic: "beleuchtung", points: 2, difficulty: 0.3, tags: ["nebelscheinwerfer", "nebel"],
    text: "Wann dürfen Nebelscheinwerfer eingeschaltet werden?",
    answers: [t("Bei erheblicher Sichtbehinderung durch Nebel, Schneefall oder Regen"), f("Immer bei Dunkelheit zusätzlich zum Abblendlicht", "Ohne Sichtbehinderung blenden sie unnötig."), f("Nur zusammen mit dem Fernlicht", "Nebelscheinwerfer werden mit Abblendlicht oder Standlicht kombiniert.")],
    explanation: "Nebelscheinwerfer dürfen nur bei erheblicher Sichtbehinderung durch Nebel, Schneefall oder Regen benutzt werden, anders als die Nebelschlussleuchte auch bei Sichtweiten über 50 Metern.",
    legalReference: "§ 17 Abs. 3 StVO",
  }),
  q({
    code: "own-beleuchtung-008", topic: "beleuchtung", points: 2, difficulty: 0.2, tags: ["standlicht", "abblendlicht", "dunkelheit"],
    text: "Dürfen Sie bei Dunkelheit nur mit Standlicht fahren?",
    answers: [t("Nein, während der Fahrt ist mindestens Abblendlicht erforderlich"), f("Ja, innerorts auf beleuchteten Straßen", "Auch innerorts muss mit Abblendlicht gefahren werden."), f("Ja, wenn die Geschwindigkeit unter 30 km/h liegt", "Die Geschwindigkeit ändert nichts an der Pflicht.")],
    explanation: "Standlicht dient nur zum Kenntlichmachen eines stehenden Fahrzeugs. Wer bei Dunkelheit fährt, muss mindestens Abblendlicht einschalten.",
    legalReference: "§ 17 Abs. 1 StVO",
  }),
  q({
    code: "own-beleuchtung-009", topic: "beleuchtung", points: 2, difficulty: 0.3, tags: ["leuchtweitenregulierung", "beladung"],
    text: "Sie haben den Kofferraum schwer beladen. Was ist bei der Beleuchtung zu beachten?",
    answers: [t("Die Leuchtweite anpassen, damit die Scheinwerfer den Gegenverkehr nicht blenden"), f("Nichts, die Beladung hat keinen Einfluss auf die Scheinwerfer", "Das Heck senkt sich, die Scheinwerfer leuchten höher."), f("Das Fernlicht dauerhaft einschalten, um die Absenkung auszugleichen", "Fernlicht würde erst recht blenden.")],
    explanation: "Bei schwerer Beladung senkt sich das Heck und die Scheinwerfer leuchten nach oben. Mit der Leuchtweitenregulierung wird der Lichtkegel wieder abgesenkt.",
    legalReference: "§ 50 StVZO",
  }),
  q({
    code: "own-beleuchtung-010", topic: "beleuchtung", points: 3, difficulty: 0.6, tags: ["nebelschlussleuchte", "geschwindigkeit", "sichtweite"], kind: "numeric", numericAnswer: 50, tolerance: 0, unit: "km/h",
    text: "Sie fahren bei Nebel mit eingeschalteter Nebelschlussleuchte. Welche Höchstgeschwindigkeit dürfen Sie dabei nicht überschreiten? Angabe in km/h.",
    answers: [],
    explanation: "Die Nebelschlussleuchte darf nur bei Nebel mit einer Sichtweite unter 50 Metern eingeschaltet werden. Bei so geringer Sichtweite gilt zugleich die Höchstgeschwindigkeit von 50 km/h. Bessert sich die Sicht, muss die Nebelschlussleuchte wieder ausgeschaltet werden.",
    legalReference: "§ 17 Abs. 3 StVO; § 3 Abs. 1 StVO",
  }),
  q({
    code: "own-beleuchtung-011", topic: "beleuchtung", points: 3, difficulty: 0.65, tags: ["lichtautomatik", "abblendlicht", "nebel", "assistenzsysteme"],
    text: "Ihr Fahrzeug hat eine Lichtautomatik mit Lichtsensor. Bei dichtem Nebel am Tag leuchtet nur das Tagfahrlicht. Was ist richtig?",
    answers: [t("Der Sensor erkennt Nebel häufig nicht; Sie müssen das Abblendlicht von Hand einschalten"), t("Bei Sichtweiten unter 50 Metern dürfen Sie zusätzlich die Nebelschlussleuchte einschalten"), f("Die Lichtautomatik erfüllt immer die gesetzlichen Vorgaben, ein Eingreifen ist nicht nötig", "Lichtsensoren reagieren auf Helligkeit, nicht auf Sichtweite."), f("Tagfahrlicht ist bei Nebel ausreichend", "Bei erheblicher Sichtbehinderung ist Abblendlicht Pflicht, damit auch die Rückleuchten leuchten.")],
    explanation: "Lichtautomatiken messen die Umgebungshelligkeit. Bei hellem Nebel schalten sie oft nicht auf Abblendlicht, sodass das Fahrzeug von hinten unbeleuchtet ist. Der Fahrer bleibt dafür verantwortlich, bei Sichtbehinderung Abblendlicht und bei Sicht unter 50 Metern gegebenenfalls die Nebelschlussleuchte einzuschalten.",
    legalReference: "§ 17 Abs. 1 und 3 StVO",
  }),
  q({
    code: "own-beleuchtung-012", topic: "beleuchtung", points: 3, difficulty: 0.65, tags: ["fernlicht", "fernlichtassistent", "blenden", "assistenzsysteme"],
    text: "Ihr Fahrzeug hat einen Fernlichtassistenten, der automatisch auf- und abblendet. Welche Aussagen treffen zu?",
    answers: [t("Der Fahrer bleibt dafür verantwortlich, dass niemand geblendet wird, und muss notfalls von Hand abblenden"), t("Unbeleuchtete oder schwach beleuchtete Verkehrsteilnehmer wie Radfahrende oder Fußgänger werden vom System nicht immer rechtzeitig erkannt"), f("Mit Fernlichtassistent darf das Fernlicht auch innerorts auf beleuchteten Straßen dauerhaft genutzt werden", "Auf ausreichend beleuchteten Straßen ist Fernlicht unzulässig."), f("Der Assistent macht das Abblenden bei Gegenverkehr überflüssig, Blendung ist ausgeschlossen", "Das System kann verzögert reagieren; der Fahrer muss aufmerksam bleiben.")],
    explanation: "Fernlichtassistenten erkennen Scheinwerfer und Rückleuchten anderer Fahrzeuge, aber nicht zuverlässig Fußgänger, Radfahrende oder Fahrzeuge hinter Kuppen. Die Pflicht, rechtzeitig abzublenden, bleibt beim Fahrer. Auf beleuchteten Straßen innerorts ist Fernlicht nicht erlaubt.",
    legalReference: "§ 17 Abs. 2 StVO",
  }),
  q({
    code: "own-beleuchtung-013", topic: "beleuchtung", points: 3, difficulty: 0.6, tags: ["abblendlicht", "defekt", "dunkelheit", "scheinwerfer"],
    text: "Bei Dunkelheit stellen Sie fest, dass ein Abblendscheinwerfer ausgefallen ist. Was gilt?",
    answers: [t("Das Fahrzeug darf bei Dunkelheit so nicht weitergefahren werden, weil die vorgeschriebene Beleuchtung nicht funktioniert und es mit einem Kraftrad verwechselt werden kann"), t("Der Mangel ist unverzüglich zu beheben; bei Tageslicht kann die Fahrt zur Werkstatt fortgesetzt werden"), f("Mit einem Scheinwerfer darf bei Dunkelheit normal weitergefahren werden, weil ein Licht ausreicht", "Die vorgeschriebene Beleuchtung muss vollständig funktionieren; einseitiges Licht täuscht andere über die Fahrzeugbreite."), f("Stattdessen darf das Fernlicht des defekten Scheinwerfers dauerhaft genutzt werden", "Fernlicht blendet und ersetzt das Abblendlicht nicht.")],
    explanation: "Die vorgeschriebenen Beleuchtungseinrichtungen müssen bei Dunkelheit funktionsfähig sein. Ein Pkw mit nur einem Scheinwerfer kann für ein Kraftrad gehalten werden, was die Einschätzung der Fahrzeugbreite verfälscht. Der Defekt ist sofort zu beheben, gegebenenfalls mit Ersatzlampe an Ort und Stelle.",
    legalReference: "§ 17 Abs. 1 StVO; § 23 Abs. 1 StVO; § 49a StVZO",
  }),
  q({
    code: "own-beleuchtung-014", topic: "beleuchtung", points: 3, difficulty: 0.6, tags: ["parken", "parkleuchte", "standlicht", "innerorts"],
    text: "Sie parken nachts innerorts in einer unbeleuchteten Nebenstraße am rechten Fahrbahnrand. Wie muss das Fahrzeug kenntlich gemacht werden?",
    answers: [t("Mit Standlicht oder Parkleuchten; innerorts genügt es, nur die der Fahrbahn zugewandte Seite zu beleuchten"), f("Gar nicht, weil innerorts nie eine Beleuchtungspflicht besteht", "Die Pflicht entfällt nur bei ausreichender Straßenbeleuchtung."), f("Mit eingeschaltetem Warnblinklicht", "Warnblinklicht ist Gefahrensituationen vorbehalten."), f("Mit Abblendlicht während der gesamten Parkdauer", "Standlicht oder Parkleuchten genügen und schonen die Batterie.")],
    explanation: "Haltende und parkende Fahrzeuge müssen bei Dunkelheit mit eigener Lichtquelle sichtbar sein, sofern die Straßenbeleuchtung sie nicht auf ausreichende Entfernung erkennbar macht. Innerorts genügt eine Parkleuchte auf der Fahrbahnseite. Außerorts ist beidseitiges Standlicht nötig.",
    legalReference: "§ 17 Abs. 4 StVO",
  }),
  q({
    code: "own-beleuchtung-015", topic: "beleuchtung", points: 3, difficulty: 0.6, tags: ["nebelscheinwerfer", "nebelschlussleuchte", "regen", "blenden"],
    text: "Bei starkem Regen auf der Autobahn beträgt die Sichtweite etwa 100 Meter. Welche Beleuchtung ist zulässig?",
    answers: [t("Abblendlicht"), t("Zusätzlich Nebelscheinwerfer, weil der Regen die Sicht erheblich behindert"), f("Die Nebelschlussleuchte, damit Sie von hinten besser gesehen werden", "Die Nebelschlussleuchte ist nur bei Nebel mit Sicht unter 50 Metern erlaubt und blendet sonst stark."), f("Fernlicht, um weiter zu sehen", "Fernlicht wird vom Regen reflektiert und blendet.")],
    explanation: "Bei erheblicher Sichtbehinderung durch Regen ist Abblendlicht Pflicht, Nebelscheinwerfer sind erlaubt. Die Nebelschlussleuchte bleibt Nebel mit Sichtweiten unter 50 Metern vorbehalten, weil ihre starke Leuchtkraft nachfolgende Fahrer blendet.",
    legalReference: "§ 17 Abs. 3 StVO",
  }),
  q({
    code: "own-beleuchtung-016", topic: "beleuchtung", points: 3, difficulty: 0.55, tags: ["nebelschlussleuchte", "nebel", "ausschalten"],
    text: "Der Nebel lichtet sich, die Sichtweite steigt auf über 100 Meter. Ihre Nebelschlussleuchte ist noch an. Was gilt?",
    answers: [t("Sie müssen die Nebelschlussleuchte sofort ausschalten, weil sie nachfolgende Fahrer blendet"), f("Sie dürfen sie eingeschaltet lassen, bis der Nebel vollständig weg ist", "Erlaubt ist sie nur bei Sichtweiten unter 50 Metern."), f("Sie dürfen sie bis zum Ende der Fahrt eingeschaltet lassen", "Das Einschalten außerhalb der Voraussetzungen ist eine Ordnungswidrigkeit.")],
    explanation: "Die Nebelschlussleuchte darf nur bei Nebel mit Sichtweite unter 50 Metern leuchten. Sobald die Sicht besser wird, ist sie auszuschalten. Ihre hohe Lichtstärke blendet sonst und macht das Bremslicht schlechter erkennbar.",
    legalReference: "§ 17 Abs. 3 StVO",
  }),
  q({
    code: "own-beleuchtung-017", topic: "beleuchtung", points: 3, difficulty: 0.6, tags: ["fernlicht", "abblenden", "schienenfahrzeug", "auffahren"],
    text: "In welchen Situationen müssen Sie außerorts vom Fernlicht auf Abblendlicht wechseln?",
    answers: [t("Wenn Sie einem anderen Fahrzeug so dicht folgen, dass Sie den Fahrer über die Spiegel blenden würden"), t("Wenn Schienenfahrzeuge oder Wasserfahrzeuge entgegenkommen, deren Führer geblendet werden könnten"), t("Wenn entgegenkommende Fußgänger oder Radfahrende geblendet würden"), f("Grundsätzlich auf jeder Landstraße, weil Fernlicht außerorts verboten ist", "Fernlicht ist außerorts erlaubt, solange niemand geblendet wird.")],
    explanation: "Fernlicht muss abgeblendet werden, sobald jemand geblendet werden könnte: bei Gegenverkehr aller Art, beim Auffahren auf vorausfahrende Fahrzeuge und wenn Schienen- oder Wasserfahrzeuge entgegenkommen. Auf unbeleuchteten Straßen ohne andere Verkehrsteilnehmer sollte Fernlicht genutzt werden, um die Sichtweite zu vergrößern.",
    legalReference: "§ 17 Abs. 2 StVO",
  }),
  q({
    code: "own-beleuchtung-018", topic: "beleuchtung", points: 3, difficulty: 0.6, tags: ["warnblinklicht", "schulbus", "abschleppen", "verwendung"],
    text: "In welchen Fällen ist das Warnblinklicht vorgeschrieben oder erlaubt?",
    answers: [t("Wenn ein Linien- oder Schulbus eine Haltestelle anfährt, an der Kinder ein- oder aussteigen und die entsprechend gekennzeichnet ist"), t("Bei beiden Fahrzeugen während des Abschleppens"), t("Wenn Sie andere vor einer Gefahr warnen wollen, etwa vor einem Stauende oder als Letzter im Stau"), f("Wenn Sie kurz in zweiter Reihe halten, um Brötchen zu holen", "Das Warnblinklicht erlaubt kein verbotenes Halten.")],
    explanation: "Das Warnblinklicht dient dem Warnen: bei Gefahr für den nachfolgenden Verkehr, bei liegen gebliebenen Fahrzeugen, beim Abschleppen und bei Bussen an gekennzeichneten Haltestellen. Als Entschuldigung für verbotenes Halten ist es nicht vorgesehen.",
    legalReference: "§ 16 Abs. 2 StVO; § 15 StVO; § 15a Abs. 3 StVO; § 20 Abs. 3 StVO",
  }),
  q({
    code: "own-beleuchtung-019", topic: "beleuchtung", points: 3, difficulty: 0.6, tags: ["leuchten", "farben", "rueckfahrscheinwerfer"],
    text: "Welche Aussagen zu Farbe und Bedeutung der Fahrzeugleuchten treffen zu?",
    answers: [t("Nach vorn leuchten Begrenzungs- und Scheinwerfer weiß, nach hinten Schluss- und Bremsleuchten rot"), t("Der Rückfahrscheinwerfer ist weiß und darf nur beim Rückwärtsfahren leuchten"), t("Blinker leuchten gelb und werden auch als Warnblinklicht genutzt"), f("Die Nebelschlussleuchte ist gelb und darf dauerhaft bei Dunkelheit leuchten", "Die Nebelschlussleuchte ist rot und nur bei Nebel unter 50 m Sicht erlaubt.")],
    explanation: "Die Lichtfarben sind vorgeschrieben: weiß nach vorn, rot nach hinten, gelb für Fahrtrichtungsanzeiger. Der weiße Rückfahrscheinwerfer signalisiert Rückwärtsfahren und darf sonst nicht leuchten. Blaues und gelbes Blinklicht sind Sonderfahrzeugen vorbehalten.",
    legalReference: "§ 49a bis § 54 StVZO",
  }),
  q({
    code: "own-beleuchtung-020", topic: "beleuchtung", points: 3, difficulty: 0.6, tags: ["scheinwerfer", "verschmutzung", "winter", "sicht"],
    text: "Auf winterlicher Straße mit Salz und Matsch sind Ihre Scheinwerfer und Rückleuchten nach kurzer Zeit verschmutzt. Was ist richtig?",
    answers: [t("Die Leuchtweite und Sichtbarkeit sinken stark; bei Pausen sollten Scheinwerfer, Rückleuchten und Kennzeichen gereinigt werden"), t("Verschmutzte Scheinwerfer streuen das Licht und können den Gegenverkehr blenden"), f("Die Lichtstärke moderner Scheinwerfer gleicht die Verschmutzung aus", "Schmutz schluckt und streut das Licht unabhängig von der Lichtquelle."), f("Nur die Scheinwerfer sind wichtig, die Rückleuchten spielen keine Rolle", "Verdreckte Rückleuchten machen das Fahrzeug von hinten unsichtbar.")],
    explanation: "Schmutz auf Scheinwerfern kann die Lichtleistung erheblich verringern und das Licht streuen, sodass andere geblendet werden. Verschmutzte Rückleuchten und Kennzeichen sind ebenso ein Sicherheits- und Rechtsproblem. Im Winter deshalb regelmäßig alle Leuchten reinigen.",
    legalReference: "§ 23 Abs. 1 StVO",
  }),
  q({
    code: "own-beleuchtung-021", topic: "beleuchtung", points: 3, difficulty: 0.6, tags: ["lichthupe", "hupe", "ueberholen", "innerorts"],
    text: "Sie wollen innerorts ein langsam fahrendes Fahrzeug überholen. Dürfen Sie das mit Lichthupe oder Hupe ankündigen?",
    answers: [t("Nein, innerorts dürfen Schall- und Leuchtzeichen nur als Warnung vor einer Gefahr gegeben werden, nicht zur Überholankündigung"), f("Ja, die Lichthupe ist innerorts immer erlaubt", "Innerorts sind Lichthupe und Hupe nur als Warnzeichen zulässig."), f("Ja, aber nur mit der Hupe", "Auch die Hupe darf innerorts nicht zur Überholankündigung eingesetzt werden.")],
    explanation: "Außerhalb geschlossener Ortschaften darf das Überholen mit Schall- oder Leuchtzeichen angekündigt werden. Innerorts sind Hupe und Lichthupe nur erlaubt, wenn jemand vor einer Gefahr gewarnt werden muss.",
    legalReference: "§ 16 Abs. 1 StVO; § 5 Abs. 5 StVO",
  }),
  q({
    code: "own-beleuchtung-022", topic: "beleuchtung", points: 3, difficulty: 0.6, tags: ["daemmerung", "abblendlicht", "sehen_und_gesehen_werden"],
    text: "In der Abenddämmerung ist es noch relativ hell, viele Fahrzeuge fahren ohne Licht. Was ist richtig?",
    answers: [t("Das Abblendlicht rechtzeitig einschalten, weil Fahrzeuge in der Dämmerung ohne Licht mit der Umgebung verschmelzen"), t("Mit Fußgängern und Radfahrenden in dunkler Kleidung rechnen, die schlecht zu erkennen sind"), f("Warten, bis es vollständig dunkel ist, um die Batterie zu schonen", "Die Batterie wird beim Fahren vom Generator geladen; das Licht kostet praktisch nichts."), f("Tagfahrlicht reicht in der Dämmerung bis zur völligen Dunkelheit aus", "In der Dämmerung ist die vorgeschriebene Beleuchtung, also Abblendlicht, zu benutzen.")],
    explanation: "Während der Dämmerung, bei Dunkelheit oder wenn die Sichtverhältnisse es sonst erfordern, sind die vorgeschriebenen Beleuchtungseinrichtungen zu benutzen. Es geht nicht nur um das eigene Sehen, sondern vor allem darum, von anderen gesehen zu werden.",
    legalReference: "§ 17 Abs. 1 StVO",
  }),
  q({
    code: "own-beleuchtung-023", topic: "beleuchtung", points: 3, difficulty: 0.6, tags: ["blenden", "innenraumbeleuchtung", "sicht", "nachtfahrt"],
    text: "Welche Maßnahmen verbessern bei Nachtfahrten die Sicht und vermeiden Blendung?",
    answers: [t("Innenraumbeleuchtung und helle Displays dimmen oder ausschalten, damit sich die Augen an die Dunkelheit anpassen"), t("Windschutzscheibe innen und außen sauber halten, weil Schlieren das Licht des Gegenverkehrs streuen"), t("Den Innenspiegel auf Nachtstellung kippen oder den automatisch abblendenden Spiegel nutzen"), f("Eine getönte Sonnenbrille tragen, um weniger geblendet zu werden", "Getönte Brillen verschlechtern das Sehen bei Nacht erheblich.")],
    explanation: "Bei Nacht sinkt die Sehleistung, Blendung wirkt lange nach. Eine saubere Scheibe, gedimmte Instrumente und der abgeblendete Innenspiegel helfen. Getönte Brillen sind nachts ungeeignet; wer nachts schlecht sieht, sollte die Augen prüfen lassen.",
  }),
  q({
    code: "own-beleuchtung-024", topic: "beleuchtung", points: 3, difficulty: 0.6, tags: ["parken", "ausserorts", "anhaenger", "standlicht"],
    text: "Sie stellen außerorts nachts einen Pkw mit Anhänger am Fahrbahnrand ab. Was gilt für die Beleuchtung?",
    answers: [t("Der Zug muss mit Standlicht vorn und Schlussleuchten hinten am Anhänger kenntlich gemacht werden"), f("Es genügt das Standlicht des Pkw, der Anhänger braucht kein Licht", "Das hintere Ende des Zuges, also der Anhänger, muss beleuchtet sein."), f("Außerorts abgestellte Fahrzeuge brauchen keine Beleuchtung", "Außerorts ist die Beleuchtungspflicht bei Dunkelheit besonders wichtig.")],
    explanation: "Beim Parken bei Dunkelheit muss das Fahrzeug nach vorn und hinten durch eigene Lichtquellen erkennbar sein, sofern keine ausreichende Straßenbeleuchtung vorhanden ist. Bei einem Zug ist das hintere Ende der Anhänger, dessen Schlussleuchten mitleuchten müssen.",
    legalReference: "§ 17 Abs. 4 StVO",
  }),
  q({
    code: "own-beleuchtung-025", topic: "beleuchtung", points: 3, difficulty: 0.55, tags: ["bremsleuchte", "defekt", "auffahrunfall"],
    text: "Ein Bekannter weist Sie darauf hin, dass beide Bremsleuchten Ihres Pkw nicht funktionieren. Was gilt?",
    answers: [t("Das Fahrzeug darf so nicht weiter am Verkehr teilnehmen; der Mangel ist sofort zu beheben, weil nachfolgende Fahrer Ihr Bremsen nicht erkennen"), f("Die Weiterfahrt ist erlaubt, wenn Sie besonders sanft bremsen", "Ohne Bremslicht drohen Auffahrunfälle; die Bremsleuchten sind vorgeschrieben."), f("Das dritte Bremslicht in der Heckscheibe reicht aus", "Die beiden seitlichen Bremsleuchten sind Pflicht.")],
    explanation: "Bremsleuchten gehören zur vorgeschriebenen Beleuchtung und müssen jederzeit funktionieren. Ohne sie fehlt dem nachfolgenden Verkehr das wichtigste Signal für Verzögerungen. Ersatzlampen gehören deshalb ins Fahrzeug.",
    legalReference: "§ 53 StVZO; § 23 Abs. 1 StVO",
  }),
  q({
    code: "own-beleuchtung-026", topic: "beleuchtung", points: 3, difficulty: 0.55, tags: ["kraftrad", "tagfahrlicht", "abblendlicht", "tag"],
    text: "Was gilt für die Beleuchtung von Krafträdern am Tag?",
    answers: [t("Krafträder müssen auch am Tag mit Abblendlicht oder Tagfahrlicht fahren"), f("Für Krafträder gelten die gleichen Regeln wie für Pkw, am Tag ist kein Licht nötig", "Für Krafträder ist Licht am Tag vorgeschrieben."), f("Krafträder müssen am Tag mit Fernlicht fahren", "Fernlicht blendet; vorgeschrieben ist Abblendlicht oder Tagfahrlicht.")],
    explanation: "Krafträder sind schmal und werden leicht übersehen. Deshalb müssen sie auch bei Tageslicht mit Abblendlicht oder Tagfahrlicht fahren. Für Pkw besteht am Tag keine Lichtpflicht, Tagfahrlicht ist aber empfehlenswert.",
    legalReference: "§ 17 Abs. 2a StVO",
  }),
  q({
    code: "own-beleuchtung-027", topic: "beleuchtung", points: 3, difficulty: 0.6, tags: ["schneefall", "abblendlicht", "tag", "sichtbehinderung"],
    text: "Am Tag setzt dichter Schneefall ein, die Sicht sinkt auf etwa 80 Meter. Welche Beleuchtung ist vorgeschrieben und welche erlaubt?",
    answers: [t("Vorgeschrieben ist Abblendlicht"), t("Erlaubt sind zusätzlich Nebelscheinwerfer"), f("Vorgeschrieben ist die Nebelschlussleuchte", "Sie ist nur bei Nebel unter 50 m Sicht erlaubt, nicht bei Schneefall mit 80 m Sicht."), f("Es reicht das Tagfahrlicht", "Bei Sichtbehinderung muss auch am Tag Abblendlicht eingeschaltet werden.")],
    explanation: "Bei erheblicher Sichtbehinderung durch Schneefall muss auch am Tag mit Abblendlicht gefahren werden; Nebelscheinwerfer sind zusätzlich erlaubt. Die Nebelschlussleuchte bleibt Nebel mit Sichtweiten unter 50 Metern vorbehalten.",
    legalReference: "§ 17 Abs. 3 StVO",
  }),
  q({
    code: "own-beleuchtung-028", topic: "beleuchtung", points: 3, difficulty: 0.6, tags: ["fernlicht", "innerorts", "beleuchtet", "unbeleuchtet"],
    text: "Sie fahren nachts innerorts durch ein Gewerbegebiet ohne Straßenbeleuchtung, kein anderer Verkehr ist zu sehen. Dürfen Sie Fernlicht einschalten?",
    answers: [t("Ja, das Verbot des Fernlichts innerorts gilt nur auf ausreichend beleuchteten Straßen"), f("Nein, innerorts ist Fernlicht ausnahmslos verboten", "Auf unbeleuchteten Straßen innerorts darf Fernlicht benutzt werden, solange niemand geblendet wird."), f("Ja, aber nur zusammen mit der Nebelschlussleuchte", "Die Nebelschlussleuchte hat damit nichts zu tun.")],
    explanation: "Fernlicht darf nicht auf Straßen mit ausreichender Beleuchtung benutzt werden und nie, wenn andere geblendet werden. Auf unbeleuchteten Straßen innerorts ist es erlaubt und sinnvoll, sobald kein anderer Verkehrsteilnehmer geblendet werden kann.",
    legalReference: "§ 17 Abs. 2 StVO",
  }),
  q({
    code: "own-beleuchtung-029", topic: "beleuchtung", points: 3, difficulty: 0.55, tags: ["blaulicht", "gelbes_blinklicht", "sonderrechte", "verwendung"],
    text: "Welche Aussagen zu blauem und gelbem Blinklicht treffen zu?",
    answers: [t("Blaues Blinklicht zusammen mit dem Einsatzhorn bedeutet: sofort freie Bahn schaffen"), t("Blaues Blinklicht allein warnt vor Unfall- oder Einsatzstellen oder kündigt geschlossene Verbände und Schwertransporte an"), t("Gelbes Blinklicht warnt vor Gefahren, etwa Arbeitsstellen oder ungewöhnlich langsamen Fahrzeugen, ohne Sonderrechte zu gewähren"), f("Privatfahrzeuge dürfen gelbes Blinklicht anbringen, um bei Pannen besser gesehen zu werden", "Gelbe Rundumleuchten sind nur bestimmten Fahrzeugen erlaubt; Privatfahrzeuge nutzen das Warnblinklicht.")],
    explanation: "Blaulicht mit Einsatzhorn verpflichtet alle, sofort Platz zu machen. Blaulicht ohne Horn warnt oder kündigt an. Gelbes Blinklicht warnt vor Gefahren, gibt aber keine Sonderrechte. Rundumkennleuchten dürfen nur an dafür zugelassenen Fahrzeugen angebracht sein.",
    legalReference: "§ 38 StVO; § 52 StVZO",
  }),
  q({
    code: "own-beleuchtung-030", topic: "beleuchtung", points: 3, difficulty: 0.55, tags: ["leuchtweite", "blenden", "scheinwerfereinstellung"],
    text: "Entgegenkommende Fahrer betätigen häufig die Lichthupe, obwohl Sie mit Abblendlicht fahren. Was ist eine wahrscheinliche Ursache?",
    answers: [t("Ihre Scheinwerfer sind zu hoch eingestellt oder die Leuchtweitenregulierung ist bei Beladung nicht angepasst"), f("Das Abblendlicht ist zu schwach", "Zu schwaches Licht blendet nicht."), f("Ihr Tagfahrlicht ist eingeschaltet", "Tagfahrlicht ist so gestaltet, dass es nicht blendet.")],
    explanation: "Falsch eingestellte oder bei Beladung nicht abgesenkte Scheinwerfer blenden den Gegenverkehr, obwohl nur Abblendlicht leuchtet. Die Scheinwerfereinstellung sollte regelmäßig geprüft und die Leuchtweitenregulierung bei Beladung korrigiert werden.",
    legalReference: "§ 50 StVZO",
  }),
  q({
    code: "own-beleuchtung-031", topic: "beleuchtung", points: 3, difficulty: 0.6, tags: ["nebelscheinwerfer", "standlicht", "einsatz", "blenden"],
    text: "Bei klarer Nacht auf der Landstraße fahren Sie mit Abblendlicht und zusätzlich eingeschalteten Nebelscheinwerfern. Was gilt?",
    answers: [t("Das ist unzulässig, weil Nebelscheinwerfer nur bei erheblicher Sichtbehinderung durch Nebel, Schneefall oder Regen eingeschaltet werden dürfen"), f("Das ist erlaubt, weil mehr Licht die Sicherheit erhöht", "Ohne Sichtbehinderung sind Nebelscheinwerfer verboten und können blenden."), f("Das ist erlaubt, solange kein Gegenverkehr kommt", "Die Erlaubnis hängt von der Sichtbehinderung ab, nicht vom Gegenverkehr.")],
    explanation: "Nebelscheinwerfer sind für erhebliche Sichtbehinderung bestimmt. Bei klarer Sicht sind sie auszuschalten, weil sie andere blenden können und ihr Einsatz eine Ordnungswidrigkeit ist.",
    legalReference: "§ 17 Abs. 3 StVO",
  }),
  q({
    code: "own-beleuchtung-032", topic: "beleuchtung", points: 3, difficulty: 0.55, tags: ["tunnel", "abblendlicht", "sonnenbrille"],
    text: "Welche Beleuchtung müssen Sie beim Durchfahren eines Tunnels (Zeichen 327) am Tag einschalten, und warum?",
    answers: [t("Abblendlicht, damit Sie sichtbar sind und die Rückleuchten leuchten; Tagfahrlicht reicht nicht"), f("Nur Standlicht, weil der Tunnel beleuchtet ist", "Standlicht ist während der Fahrt nie ausreichend."), f("Fernlicht, um die Tunnelwände auszuleuchten", "Fernlicht blendet im Tunnel besonders stark.")],
    explanation: "Im Tunnel ist auch am Tag mit Abblendlicht zu fahren. Tagfahrlicht schaltet die Rückleuchten meist nicht ein, sodass das Fahrzeug von hinten schlecht zu erkennen wäre. Vor der Einfahrt sollte die Sonnenbrille abgenommen werden.",
    legalReference: "Anlage 3 StVO, Zeichen 327; § 17 Abs. 1 StVO",
  }),
  q({
    code: "own-beleuchtung-033", topic: "beleuchtung", points: 2, difficulty: 0.45, tags: ["warnblinklicht", "liegenbleiben", "absichern"],
    text: "Ihr Fahrzeug bleibt in einer Kurve auf der Landstraße stehen. Welche Beleuchtung muss eingeschaltet werden?",
    answers: [t("Das Warnblinklicht, weil das Fahrzeug an dieser Stelle nicht rechtzeitig als Hindernis erkannt werden kann"), f("Nur das Standlicht", "Standlicht allein warnt nicht ausreichend an einer unübersichtlichen Stelle."), f("Das Fernlicht, damit das Fahrzeug weit sichtbar ist", "Fernlicht blendet und warnt nicht den nachfolgenden Verkehr.")],
    explanation: "Bleibt ein Fahrzeug an einer Stelle liegen, an der es nicht rechtzeitig erkannt werden kann, ist sofort das Warnblinklicht einzuschalten und ein Warndreieck in ausreichender Entfernung aufzustellen.",
    legalReference: "§ 15 Abs. 1 StVO",
  }),
  q({
    code: "own-beleuchtung-034", topic: "beleuchtung", points: 2, difficulty: 0.4, tags: ["nebelschlussleuchte", "kontrollleuchte", "farbe"],
    text: "Woran erkennen Sie im Armaturenbrett, dass die Nebelschlussleuchte eingeschaltet ist?",
    answers: [t("An einer gelben Kontrollleuchte mit dem Symbol einer Leuchte, deren Strahlen nach rechts zeigen und von einer Wellenlinie durchbrochen sind"), f("An einer blauen Kontrollleuchte", "Blau steht für das Fernlicht."), f("An einer roten Kontrollleuchte", "Rote Leuchten zeigen Störungen oder Warnungen an.")],
    explanation: "Die Kontrollleuchte der Nebelschlussleuchte ist gelb, die des Fernlichts blau. Wer die Symbole kennt, erkennt sofort, wenn die Nebelschlussleuchte versehentlich eingeschaltet geblieben ist und andere blendet.",
  }),
  q({
    code: "own-beleuchtung-035", topic: "beleuchtung", points: 2, difficulty: 0.4, tags: ["lichthupe", "warnzeichen", "gefahr"],
    text: "Ein Kind läuft auf die Straße zu, ohne Sie zu bemerken. Dürfen Sie Hupe oder Lichthupe benutzen?",
    answers: [t("Ja, als Warnzeichen zur Abwehr einer Gefahr sind beide innerorts und außerorts erlaubt"), f("Nein, innerorts ist Hupen generell verboten", "Innerorts ist die Hupe als Warnzeichen erlaubt."), f("Nur die Lichthupe, weil die Hupe Kinder erschreckt", "Beide Warnzeichen sind zulässig; vor allem aber bremsen.")],
    explanation: "Schall- und Leuchtzeichen dürfen gegeben werden, wenn man sich oder andere gefährdet sieht. Wichtiger als das Warnzeichen ist jedoch, die Geschwindigkeit sofort zu verringern und bremsbereit zu sein.",
    legalReference: "§ 16 Abs. 1 StVO",
  }),
  q({
    code: "own-beleuchtung-036", topic: "beleuchtung", points: 2, difficulty: 0.4, tags: ["abblendlicht", "regen", "tag", "rueckleuchten"],
    text: "Warum genügt bei Regen am Tag das Tagfahrlicht nicht?",
    answers: [t("Weil beim Tagfahrlicht die Schlussleuchten in der Regel ausgeschaltet bleiben und das Fahrzeug von hinten schlecht erkennbar ist"), f("Weil Tagfahrlicht bei Regen Kurzschlüsse verursacht", "Das ist technisch nicht der Fall."), f("Weil Tagfahrlicht zu hell ist und blendet", "Tagfahrlicht ist blendfrei ausgelegt.")],
    explanation: "Tagfahrlicht leuchtet nur nach vorn. Bei Regen, Nebel oder Schneefall ist deshalb Abblendlicht Pflicht, damit auch die Rückleuchten leuchten und das Fahrzeug in der Gischt von hinten erkennbar bleibt.",
    legalReference: "§ 17 Abs. 3 StVO",
  }),
  q({
    code: "own-beleuchtung-037", topic: "beleuchtung", points: 2, difficulty: 0.35, tags: ["ersatzlampen", "ausruestung", "defekt"],
    text: "Warum ist es sinnvoll, Ersatzlampen für die Fahrzeugbeleuchtung mitzuführen?",
    answers: [t("Weil eine ausgefallene Leuchte sofort ersetzt werden muss und der Wechsel bei vielen Fahrzeugen an Ort und Stelle möglich ist"), f("Weil Ersatzlampen in Deutschland für Pkw vorgeschrieben sind", "Für Pkw sind Ersatzlampen in Deutschland nicht vorgeschrieben, aber sinnvoll."), f("Weil die Werkstatt sonst keine Lampen wechselt", "Werkstätten wechseln Lampen selbstverständlich.")],
    explanation: "Die vorgeschriebene Beleuchtung muss funktionieren. Mit einem Ersatzlampenset lässt sich ein Defekt oft sofort beheben. Im Ausland ist das Mitführen teilweise vorgeschrieben.",
    legalReference: "§ 49a StVZO",
  }),
  q({
    code: "own-beleuchtung-038", topic: "beleuchtung", points: 2, difficulty: 0.4, tags: ["fernlicht", "sichtweite", "geschwindigkeit", "dunkelheit"],
    text: "Nachts auf unbeleuchteter Landstraße müssen Sie wegen Gegenverkehr dauerhaft mit Abblendlicht fahren. Was folgt daraus für Ihre Geschwindigkeit?",
    answers: [t("Sie dürfen nur so schnell fahren, dass Sie innerhalb der vom Abblendlicht ausgeleuchteten Strecke anhalten können"), f("Die Höchstgeschwindigkeit von 100 km/h darf immer ausgefahren werden", "Die zulässige Höchstgeschwindigkeit ist eine Obergrenze; bei Dunkelheit ist die Sichtweite maßgeblich."), f("Die Geschwindigkeit spielt bei Abblendlicht keine Rolle", "Die Sichtweite mit Abblendlicht ist begrenzt; der Anhalteweg muss hineinpassen.")],
    explanation: "Die Geschwindigkeit muss den Sichtverhältnissen angepasst sein. Mit Abblendlicht ist die ausgeleuchtete Strecke begrenzt, bei 100 km/h reicht der Anhalteweg oft darüber hinaus. Hindernisse auf der Fahrbahn würden zu spät erkannt.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-beleuchtung-039", topic: "beleuchtung", points: 2, difficulty: 0.4, tags: ["rueckfahrscheinwerfer", "rueckwaertsfahren", "sicht"],
    text: "Welche Funktion hat der Rückfahrscheinwerfer?",
    answers: [t("Er leuchtet beim Einlegen des Rückwärtsgangs weiß und zeigt anderen an, dass das Fahrzeug rückwärts fährt oder fahren will"), f("Er dient als zusätzliches Bremslicht", "Bremsleuchten sind rot; der Rückfahrscheinwerfer ist weiß."), f("Er darf zum Ausleuchten beim Parken dauerhaft eingeschaltet werden", "Er leuchtet nur bei eingelegtem Rückwärtsgang.")],
    explanation: "Der weiße Rückfahrscheinwerfer leuchtet automatisch beim Einlegen des Rückwärtsgangs. Er warnt andere und leuchtet den Bereich hinter dem Fahrzeug aus. Vor dem Rückwärtsfahren muss sich der Fahrer trotzdem selbst vergewissern, dass der Raum frei ist.",
    legalReference: "§ 52a StVZO; § 9 Abs. 5 StVO",
  }),
];
