// Übungsfragen zum Thema "besondere_situationen" (eigene Formulierungen, kein amtlicher Prüfungsinhalt).
import type { Question } from "../types";
import { q, t, f } from "./_helpers";

export const besondereSituationen: readonly Question[] = [
  q({
    code: "own-besondere_situationen-001", topic: "besondere_situationen", points: 4, difficulty: 0.4, tags: ["aquaplaning", "naesse", "hohes_risiko"],
    text: "Ihr Fahrzeug gerät bei starkem Regen ins Aquaplaning. Wie verhalten Sie sich?",
    answers: [t("Gas wegnehmen, bei Schaltgetriebe auskuppeln, Lenkrad ruhig halten und nicht stark bremsen"), f("Sofort eine Vollbremsung einleiten", "Ohne Bodenkontakt kann das Fahrzeug bei Bremsen und Lenken unkontrollierbar werden."), f("Kräftig gegenlenken, um in der Spur zu bleiben", "Bei Aquaplaning haben die Räder keinen Kontakt; ein starker Lenkeinschlag wirkt erst wieder bei Bodenkontakt und kann das Fahrzeug ausbrechen lassen.")],
    explanation: "Bei Aquaplaning schwimmen die Reifen auf einem Wasserfilm. Ruhig bleiben, Gas wegnehmen, auskuppeln und das Lenkrad geradehalten, bis die Reifen wieder greifen.",
  }),
  q({
    code: "own-besondere_situationen-002", topic: "besondere_situationen", points: 3, difficulty: 0.3, tags: ["wildwechsel", "ausserorts", "dunkelheit"],
    text: "Nachts auf der Landstraße taucht plötzlich ein Reh am Fahrbahnrand auf. Wie verhalten Sie sich?",
    answers: [t("Abblenden, hupen, kontrolliert bremsen und das Lenkrad festhalten, nicht ausweichen"), f("Fernlicht einschalten, damit das Tier flüchtet", "Fernlicht blendet das Tier, es bleibt eher stehen."), f("Stark ausweichen, um das Tier zu schonen", "Ausweichmanöver enden oft an Bäumen oder im Gegenverkehr und sind gefährlicher als der Aufprall.")],
    explanation: "Bei Wildwechsel: Abblenden, hupen, bremsen und die Spur halten. Mit weiteren Tieren rechnen, denn Wild ist selten allein unterwegs.",
    mnemonic: "Abblenden, hupen, bremsen, Spur halten.",
  }),
  q({
    code: "own-besondere_situationen-003", topic: "besondere_situationen", points: 3, difficulty: 0.3, tags: ["glaette", "bruecke", "winter"],
    text: "Bei Temperaturen um den Gefrierpunkt fahren Sie über eine Brücke. Womit müssen Sie rechnen?",
    answers: [t("Auf Brücken bildet sich Glätte früher als auf der übrigen Strecke"), f("Brücken sind wegen des Verkehrs immer eisfrei", "Brücken kühlen von allen Seiten aus und frieren zuerst zu."), f("Glätte gibt es nur bei Schneefall", "Auch bei Nässe und Frost ohne Schnee entsteht Glätte.")],
    explanation: "Brücken und schattige Waldstücke vereisen zuerst, weil ihnen die Wärme des Bodens fehlt. Dort Geschwindigkeit reduzieren und weiche Lenk- und Bremsbewegungen ausführen.",
  }),
  q({
    code: "own-besondere_situationen-004", topic: "besondere_situationen", points: 3, difficulty: 0.2, tags: ["stau", "warnblinklicht", "autobahn"],
    text: "Sie nähern sich auf der Autobahn einem Stauende. Was tun Sie?",
    answers: [t("Warnblinklicht einschalten, Geschwindigkeit deutlich verringern und den nachfolgenden Verkehr im Spiegel beobachten"), f("Auf den Seitenstreifen ausweichen und am Stau vorbeifahren", "Der Seitenstreifen ist kein Fahrstreifen."), f("Das Warnblinklicht erst am Stillstand einschalten", "Es soll den nachfolgenden Verkehr rechtzeitig warnen.")],
    explanation: "Das Warnblinklicht darf und soll eingeschaltet werden, um vor einem Stauende oder einer plötzlichen Gefahr zu warnen. So vermeiden Sie Auffahrunfälle.",
    legalReference: "§ 16 Abs. 2 StVO",
  }),
  q({
    code: "own-besondere_situationen-005", topic: "besondere_situationen", points: 4, difficulty: 0.3, tags: ["einsatzfahrzeug", "blaulicht", "innerorts"],
    text: "Hinter Ihnen nähert sich innerorts ein Einsatzfahrzeug mit Blaulicht und Einsatzhorn. Wie verhalten Sie sich?",
    answers: [t("Sofort freie Bahn schaffen, nach rechts fahren und wenn nötig anhalten"), f("Mit gleicher Geschwindigkeit weiterfahren, damit der Verkehr fließt", "Das Einsatzfahrzeug braucht freie Bahn."), f("Auf die Gegenfahrbahn ausweichen, um Platz zu machen", "Das gefährdet den Gegenverkehr; nach rechts ausweichen.")],
    explanation: "Blaulicht mit Einsatzhorn verpflichtet alle, sofort freie Bahn zu schaffen. Dabei ruhig bleiben, nach rechts fahren und keine anderen gefährden.",
    legalReference: "§ 38 Abs. 1 StVO",
  }),
  q({
    code: "own-besondere_situationen-006", topic: "besondere_situationen", points: 3, difficulty: 0.3, tags: ["tunnel", "beleuchtung", "abblendlicht"],
    text: "Was ist beim Durchfahren eines Tunnels richtig?",
    answers: [t("Abblendlicht einschalten, auch am Tag"), t("Nicht wenden und nicht rückwärtsfahren"), t("Sonnenbrille vor der Einfahrt abnehmen"), f("Nebelschlussleuchte einschalten, um besser gesehen zu werden", "Die Nebelschlussleuchte blendet und ist nur bei Nebel mit Sicht unter 50 Metern erlaubt.")],
    explanation: "In Tunneln muss auch tagsüber mit Abblendlicht gefahren werden. Wenden und Rückwärtsfahren sind verboten; ausreichender Abstand und Beachtung der Notausgänge erhöhen die Sicherheit.",
    legalReference: "§ 17 Abs. 1 StVO; Zeichen 327",
  }),
  q({
    code: "own-besondere_situationen-007", topic: "besondere_situationen", points: 2, difficulty: 0.3, tags: ["seitenwind", "ausserorts"],
    text: "Wo müssen Sie besonders mit starkem Seitenwind rechnen?",
    answers: [t("Auf Brücken, in Waldschneisen und beim Überholen von Lkw"), f("Nur auf Autobahnen", "Seitenwind tritt überall auf, besonders an exponierten Stellen."), f("Nur bei Regen", "Seitenwind ist unabhängig vom Niederschlag.")],
    explanation: "An Brücken, Waldrändern, Schneisen und beim Passieren großer Fahrzeuge kann der Wind plötzlich angreifen oder wegfallen. Lenkrad fest halten und Geschwindigkeit anpassen.",
  }),
  q({
    code: "own-besondere_situationen-008", topic: "besondere_situationen", points: 3, difficulty: 0.4, tags: ["bahnuebergang", "baken", "ausserorts", "ueberholen"],
    text: "Sie nähern sich außerorts einem Bahnübergang, vor dem Baken aufgestellt sind. Was gilt?",
    answers: [t("Zwischen den Baken und dem Bahnübergang dürfen Kraftfahrzeuge nicht überholt werden"), t("Sie dürfen sich dem Übergang nur mit mäßiger Geschwindigkeit nähern"), f("Sie sollten hupen, um den Zug zu warnen", "Hupen ist sinnlos; der Schienenverkehr hat Vorrang.")],
    explanation: "Ab der ersten Bake gilt bis zum Bahnübergang ein Überholverbot für Kraftfahrzeuge. Wer sich einem Bahnübergang nähert, muss mit mäßiger Geschwindigkeit fahren und auf Signale achten.",
    legalReference: "§ 19 Abs. 1 StVO",
  }),
  q({
    code: "own-besondere_situationen-009", topic: "besondere_situationen", points: 2, difficulty: 0.2, tags: ["blendung", "sonne"],
    text: "Die tiefstehende Sonne blendet Sie stark. Wie reagieren Sie?",
    answers: [t("Geschwindigkeit verringern, Sonnenblende nutzen und den Abstand vergrößern"), f("Weiterfahren wie bisher, die Blendung ist nur kurz", "Auch kurze Blendung kann Fußgänger und Radfahrer unsichtbar machen."), f("Fernlicht einschalten, um besser zu sehen", "Fernlicht hilft nicht gegen Blendung und blendet andere.")],
    explanation: "Bei Blendung sinkt die Sichtweite drastisch. Nur so schnell fahren, dass innerhalb der noch übersehbaren Strecke angehalten werden kann.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-besondere_situationen-010", topic: "besondere_situationen", points: 4, difficulty: 0.4, tags: ["reifenplatzer", "autobahn", "hohes_risiko"],
    text: "Auf der Autobahn platzt ein Reifen. Wie verhalten Sie sich?",
    answers: [t("Lenkrad mit beiden Händen festhalten, Gas wegnehmen, vorsichtig abbremsen, Warnblinklicht einschalten und auf den Seitenstreifen fahren"), f("Sofort eine Vollbremsung machen", "Eine abrupte Bremsung kann das Fahrzeug ausbrechen lassen."), f("Sofort auf den linken Fahrstreifen wechseln und anhalten", "Angehalten wird rechts auf dem Seitenstreifen.")],
    explanation: "Nach einem Reifenplatzer zieht das Fahrzeug zur Seite. Lenkrad festhalten, sanft verzögern und kontrolliert auf den Seitenstreifen fahren, dann absichern.",
  }),
  q({
    code: "own-besondere_situationen-011", topic: "besondere_situationen", points: 3, difficulty: 0.6, tags: ["nebel", "sichtweite", "geschwindigkeit", "nebelschlussleuchte"], kind: "numeric", numericAnswer: 50, tolerance: 0, unit: "km/h",
    text: "Dichter Nebel senkt die Sichtweite auf 40 Meter. Wie schnell dürfen Sie höchstens fahren, unabhängig von der beschilderten Höchstgeschwindigkeit? Angabe in km/h.",
    answers: [],
    explanation: "Beträgt die Sichtweite durch Nebel, Schneefall oder Regen weniger als 50 Meter, darf nicht schneller als 50 km/h gefahren werden. Zugleich darf in dieser Situation die Nebelschlussleuchte eingeschaltet werden. Oft ist deutlich langsameres Fahren nötig, weil innerhalb der Sichtweite angehalten werden können muss.",
    legalReference: "§ 3 Abs. 1 StVO; § 17 Abs. 3 StVO",
  }),
  q({
    code: "own-besondere_situationen-012", topic: "besondere_situationen", points: 3, difficulty: 0.6, tags: ["nebel", "sichtweite", "leitpfosten", "ausserorts"], kind: "numeric", numericAnswer: 50, tolerance: 0, unit: "m",
    text: "Außerorts stehen die Leitpfosten in der Regel in einem festen Abstand, mit dem Sie bei Nebel die Sichtweite abschätzen können. Wie groß ist dieser Abstand? Angabe in Metern.",
    answers: [],
    explanation: "Leitpfosten stehen auf gerader Strecke in der Regel im Abstand von 50 Metern. Sehen Sie bei Nebel nur den nächsten Leitpfosten, liegt die Sichtweite unter 50 Metern; dann gilt höchstens 50 km/h und die Nebelschlussleuchte darf eingeschaltet werden.",
    legalReference: "§ 3 Abs. 1 StVO; § 17 Abs. 3 StVO",
  }),
  q({
    code: "own-besondere_situationen-013", topic: "besondere_situationen", points: 4, difficulty: 0.7, tags: ["tunnel", "brand", "notausgang", "hohes_risiko"],
    text: "Im Tunnel bricht bei einem vorausfahrenden Fahrzeug ein Brand aus, Sie stehen dahinter im Stau. Wie verhalten Sie sich richtig?",
    answers: [t("Motor abstellen, Fahrzeug stehen lassen und den Schlüssel stecken lassen"), t("Über die Notrufstation oder die 112 Alarm auslösen"), t("Zu Fuß über die gekennzeichneten Notausgänge den Tunnel verlassen"), f("Im Fahrzeug bleiben, Fenster schließen und auf die Feuerwehr warten", "Rauch breitet sich im Tunnel schnell aus; das Fahrzeug bietet keinen Schutz.")],
    explanation: "Bei Feuer im Tunnel zählt jede Minute. Das Fahrzeug wird mit steckendem Schlüssel verlassen, damit Einsatzkräfte es bewegen können. Alarm über die Notrufstation auslösen und über die grün gekennzeichneten Notausgänge fliehen, nicht zurück zum Tunnelportal laufen, wenn ein Notausgang näher ist.",
  }),
  q({
    code: "own-besondere_situationen-014", topic: "besondere_situationen", points: 3, difficulty: 0.6, tags: ["tunnel", "stau", "abstand"],
    text: "Im Tunnel gerät der Verkehr ins Stocken. Was ist richtig?",
    answers: [t("Warnblinklicht einschalten, um den nachfolgenden Verkehr zu warnen"), t("Auch im Stillstand ausreichenden Abstand zum Vordermann halten"), t("Bei längerem Stillstand den Motor abstellen"), f("Wenden und den Tunnel gegen die Fahrtrichtung verlassen", "Wenden ist im Tunnel verboten und lebensgefährlich.")],
    explanation: "Bei Stau im Tunnel warnt das Warnblinklicht die Nachfolgenden. Abstand halten, damit im Notfall Rettungsfahrzeuge durchkommen und Fluchtwege frei bleiben. Bei längerem Stillstand den Motor abstellen, um die Abgasbelastung gering zu halten. Wenden und Rückwärtsfahren sind verboten.",
    legalReference: "§ 16 Abs. 2 StVO; Anlage 3 StVO, Zeichen 327",
  }),
  q({
    code: "own-besondere_situationen-015", topic: "besondere_situationen", points: 3, difficulty: 0.55, tags: ["schulbus", "warnblinklicht", "haltestelle", "schrittgeschwindigkeit"],
    text: "Ein Schulbus steht mit eingeschaltetem Warnblinklicht an einer Haltestelle auf Ihrer Straßenseite. Wie verhalten Sie sich?",
    answers: [t("Nur mit Schrittgeschwindigkeit und mit ausreichendem Abstand vorbeifahren, notfalls warten"), t("Mit Kindern rechnen, die plötzlich vor oder hinter dem Bus die Fahrbahn betreten"), f("Wie bei jedem haltenden Fahrzeug zügig vorbeifahren", "Das Warnblinklicht verlangt Schrittgeschwindigkeit."), f("Hupen, um die Kinder zu warnen", "Hupen erschreckt Kinder und ersetzt nicht das langsame Fahren.")],
    explanation: "An einem Bus mit eingeschaltetem Warnblinklicht darf nur mit Schrittgeschwindigkeit und ausreichendem Abstand vorbeigefahren werden, sodass eine Gefährdung von Fahrgästen ausgeschlossen ist. Das gilt auch für den Gegenverkehr. Wenn nötig, muss gewartet werden.",
    legalReference: "§ 20 Abs. 4 StVO",
  }),
  q({
    code: "own-besondere_situationen-016", topic: "besondere_situationen", points: 3, difficulty: 0.65, tags: ["schulbus", "warnblinklicht", "gegenverkehr", "haltestelle"],
    text: "Auf der Gegenfahrbahn steht ein Linienbus mit Warnblinklicht an einer Haltestelle. Was gilt für Sie?",
    answers: [t("Auch im Gegenverkehr dürfen Sie nur mit Schrittgeschwindigkeit vorbeifahren"), f("Für den Gegenverkehr gilt keine Beschränkung", "Die Schrittgeschwindigkeit gilt ausdrücklich auch für den Gegenverkehr."), f("Sie müssen anhalten, bis der Bus weiterfährt", "Anhalten ist nur nötig, wenn Fahrgäste anders nicht sicher passiert werden können."), f("Sie dürfen mit höchstens 30 km/h vorbeifahren", "Vorgeschrieben ist Schrittgeschwindigkeit.")],
    explanation: "Steht ein Linien- oder Schulbus mit Warnblinklicht an einer Haltestelle, darf auch der Gegenverkehr nur mit Schrittgeschwindigkeit vorbeifahren. Fahrgäste überqueren die Fahrbahn häufig vor oder hinter dem Bus.",
    legalReference: "§ 20 Abs. 4 StVO",
  }),
  q({
    code: "own-besondere_situationen-017", topic: "besondere_situationen", points: 3, difficulty: 0.6, tags: ["schulbus", "warnblinklicht", "haltestelle", "ueberholen"],
    text: "Ein Linienbus mit eingeschaltetem Warnblinklicht fährt vor Ihnen auf eine Haltestelle zu. Was gilt?",
    answers: [t("Der Bus darf nicht überholt werden, solange er sich mit Warnblinklicht der Haltestelle nähert"), f("Der Bus darf links überholt werden, wenn kein Gegenverkehr kommt", "Ein Bus, der mit Warnblinklicht eine Haltestelle anfährt, darf nicht überholt werden."), f("Der Bus darf rechts überholt werden", "Überholen ist in dieser Situation verboten.")],
    explanation: "An Bussen, die sich mit eingeschaltetem Warnblinklicht einer Haltestelle nähern, darf nicht vorbeigefahren werden. Erst wenn der Bus steht, darf mit Schrittgeschwindigkeit und ausreichendem Abstand vorbeigefahren werden.",
    legalReference: "§ 20 Abs. 3 und 4 StVO",
  }),
  q({
    code: "own-besondere_situationen-018", topic: "besondere_situationen", points: 3, difficulty: 0.6, tags: ["strassenbahn", "haltestelle", "fahrgaeste"],
    text: "Eine Straßenbahn hält an einer Haltestelle ohne Haltestelleninsel, die Fahrgäste steigen direkt auf die Fahrbahn aus. Was gilt?",
    answers: [t("Rechts darf nur mit Schrittgeschwindigkeit und nur in einem solchen Abstand vorbeigefahren werden, dass Fahrgäste nicht gefährdet werden"), t("Fahrgäste dürfen nicht behindert werden; wenn nötig muss gewartet werden"), f("Mit Schrittgeschwindigkeit darf immer vorbeigefahren werden, auch wenn Fahrgäste dabei behindert werden", "Wer Fahrgäste behindern oder gefährden würde, muss warten."), f("Links darf an der Straßenbahn vorbeigefahren werden", "Straßenbahnen werden grundsätzlich rechts überholt; links nur, wenn die Schienen zu weit rechts liegen.")],
    explanation: "Steigen an einer haltenden Straßenbahn Fahrgäste ein oder aus, darf rechts nur mit Schrittgeschwindigkeit und mit so großem Abstand vorbeigefahren werden, dass niemand gefährdet wird. Fahrgäste dürfen nicht behindert werden; wenn nötig, muss gewartet werden.",
    legalReference: "§ 20 Abs. 2 StVO",
  }),
  q({
    code: "own-besondere_situationen-019", topic: "besondere_situationen", points: 4, difficulty: 0.7, tags: ["bahnuebergang", "stau", "andreaskreuz", "hohes_risiko"],
    text: "Vor Ihnen staut sich der Verkehr direkt hinter einem Bahnübergang. Die Schranken sind offen, kein Zug ist zu sehen. Wie verhalten Sie sich?",
    answers: [t("Vor dem Andreaskreuz warten, bis Sie den Übergang in einem Zug vollständig überqueren können"), f("Auf den Übergang fahren und dort warten, bis es weitergeht", "Auf dem Bahnübergang darf niemals angehalten werden."), f("Bis zur Schranke vorfahren und die Gleise erst bei Zugannäherung räumen", "Ein Fahrzeug im Gleisbereich kann bei Zugannäherung nicht mehr rechtzeitig weg."), f("Zügig über den Übergang fahren und dicht auffahren, damit der Stau nicht länger wird", "Wer nicht sicher hinter dem Übergang Platz findet, darf nicht einfahren.")],
    explanation: "Wer bei stockendem Verkehr in einer Kreuzung oder Einmündung warten müsste, darf nicht einfahren. Erst recht gilt das am Bahnübergang: Auf den Gleisen darf nie gehalten werden. Deshalb ist vor dem Andreaskreuz zu warten, bis die Weiterfahrt ohne Halt auf dem Übergang möglich ist.",
    legalReference: "§ 11 Abs. 1 StVO; § 12 Abs. 1 Nr. 4 StVO; § 19 StVO",
  }),
  q({
    code: "own-besondere_situationen-020", topic: "besondere_situationen", points: 4, difficulty: 0.7, tags: ["bahnuebergang", "rotlicht", "schranke", "hohes_risiko"],
    text: "Am Bahnübergang beginnt das rote Blinklicht, die Halbschranke senkt sich noch nicht. Was ist richtig?",
    answers: [t("Sie müssen vor dem Andreaskreuz beziehungsweise der Haltlinie anhalten"), t("Warten Sie, bis das rote Licht erlischt und die Schranke wieder vollständig geöffnet ist"), f("Solange die Schranke oben ist, dürfen Sie noch zügig hinüberfahren", "Rotes Blinklicht bedeutet Halt, unabhängig von der Schranke."), f("Sie dürfen weiterfahren, wenn kein Zug zu sehen ist", "Das Lichtzeichen ist verbindlich; Züge sind oft erst spät zu sehen.")],
    explanation: "Rotes Blinklicht oder rotes Licht am Bahnübergang bedeutet Halt. Es muss vor dem Andreaskreuz, an einer Haltlinie oder vor der Schranke gewartet werden. Erst wenn das Rotlicht erloschen ist und die Schranken vollständig geöffnet sind, darf weitergefahren werden.",
    legalReference: "§ 19 Abs. 2 StVO",
  }),
  q({
    code: "own-besondere_situationen-021", topic: "besondere_situationen", points: 3, difficulty: 0.6, tags: ["gefaelle", "motorbremse", "bremsen", "berg"],
    text: "Sie fahren mit einem beladenen Pkw ein langes, steiles Gefälle hinab. Was ist richtig?",
    answers: [t("Frühzeitig in einen niedrigen Gang schalten und die Motorbremswirkung nutzen"), t("Die Betriebsbremse nur in Intervallen einsetzen, um Überhitzung zu vermeiden"), f("Im Leerlauf rollen, damit der Motor nicht unnötig belastet wird", "Ohne eingelegten Gang fehlt die Motorbremse; die Betriebsbremse kann überhitzen."), f("Den Gang wählen, in dem Sie bergauf gefahren sind, aber die Kupplung getreten halten", "Mit getretener Kupplung wirkt keine Motorbremse.")],
    explanation: "Bei langen Gefällestrecken kann die Betriebsbremse durch Dauerbelastung überhitzen und an Wirkung verlieren (Fading). Deshalb einen niedrigen Gang einlegen, sodass der Motor bremst, und die Bremse nur ergänzend einsetzen. Faustregel: Bergab im gleichen Gang wie bergauf.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-besondere_situationen-022", topic: "besondere_situationen", points: 3, difficulty: 0.6, tags: ["winter", "sicht", "schnee", "fahrzeug"],
    text: "Nach starkem Schneefall wollen Sie losfahren. Was müssen Sie vor Fahrtbeginn tun?",
    answers: [t("Alle Scheiben vollständig von Schnee und Eis befreien, nicht nur ein Guckloch"), t("Schnee vom Dach entfernen, damit er nicht auf die Fahrbahn oder auf nachfolgende Fahrzeuge rutscht"), t("Scheinwerfer, Leuchten und Kennzeichen freimachen"), f("Den Motor im Stand warmlaufen lassen, bis die Scheiben von innen abgetaut sind", "Warmlaufenlassen im Stand ist verboten und wirkungslos.")],
    explanation: "Wer fährt, muss dafür sorgen, dass die Sicht nicht beeinträchtigt ist und Beleuchtung sowie Kennzeichen erkennbar bleiben. Schnee auf dem Dach ist Ladung, die verrutschen und andere gefährden kann. Ein Guckloch reicht nicht.",
    legalReference: "§ 23 Abs. 1 StVO; § 30 Abs. 1 StVO",
  }),
  q({
    code: "own-besondere_situationen-023", topic: "besondere_situationen", points: 3, difficulty: 0.55, tags: ["glaette", "winter", "schneeketten"],
    text: "Auf einer verschneiten Bergstraße steht das Zeichen 268 (Schneeketten vorgeschrieben). Was gilt?",
    answers: [t("Sie dürfen die Strecke nur mit montierten Schneeketten befahren"), t("Mit Schneeketten dürfen Sie höchstens 50 km/h fahren"), f("Winterreifen mit Alpine-Symbol ersetzen die Schneeketten", "Das Zeichen verlangt tatsächlich montierte Ketten."), f("Sie dürfen weiterfahren, wenn die Straße geräumt aussieht", "Das Gebot gilt unabhängig vom eigenen Eindruck.")],
    explanation: "Zeichen 268 schreibt Schneeketten vor; Winterreifen allein genügen dann nicht. Mit Schneeketten darf höchstens 50 km/h gefahren werden, auch wenn Verkehrszeichen mehr erlauben.",
    legalReference: "Anlage 2 StVO, Zeichen 268; § 3 Abs. 4 StVO",
  }),
  q({
    code: "own-besondere_situationen-024", topic: "besondere_situationen", points: 4, difficulty: 0.7, tags: ["falschfahrer", "autobahn", "hohes_risiko"],
    text: "Im Radio wird ein Falschfahrer auf Ihrer Autobahn in Ihrem Streckenabschnitt gemeldet. Wie verhalten Sie sich?",
    answers: [t("Äußerst rechts fahren und nicht überholen"), t("Geschwindigkeit deutlich verringern und den Abstand vergrößern"), t("An der nächsten Möglichkeit die Autobahn verlassen oder auf einem Parkplatz abwarten"), f("Mit Lichthupe und Hupe auf dem linken Fahrstreifen weiterfahren, um den Falschfahrer zu warnen", "Falschfahrer benutzen aus ihrer Sicht meist den rechten Streifen, also Ihren linken; dort ist die Gefahr am größten.")],
    explanation: "Falschfahrer fahren aus ihrer Sicht rechts, also auf dem linken Fahrstreifen der richtigen Fahrtrichtung. Deshalb ganz rechts fahren, nicht überholen, langsam werden und möglichst die Autobahn verlassen. Der Seitenstreifen sollte frei bleiben.",
  }),
  q({
    code: "own-besondere_situationen-025", topic: "besondere_situationen", points: 3, difficulty: 0.55, tags: ["ueberflutung", "wasser", "bremsen", "naesse"],
    text: "Sie sind durch eine tiefe Wasserlache gefahren. Was sollten Sie danach tun?",
    answers: [t("Die Bremsen bei geringer Geschwindigkeit vorsichtig betätigen, um sie trocken zu bremsen"), f("Sofort stark beschleunigen, damit das Wasser abfließt", "Beschleunigen trocknet die Bremsen nicht."), f("Nichts, moderne Bremsen sind wasserunempfindlich", "Nasse Bremsscheiben und -beläge wirken zunächst schwächer.")],
    explanation: "Nach Fahrten durch tiefes Wasser verzögern nasse Bremsen deutlich schlechter. Durch mehrmaliges leichtes Bremsen bei niedriger Geschwindigkeit werden Beläge und Scheiben getrocknet, bevor die volle Bremswirkung wieder gebraucht wird.",
  }),
  q({
    code: "own-besondere_situationen-026", topic: "besondere_situationen", points: 3, difficulty: 0.6, tags: ["aquaplaning", "naesse", "spurrillen", "geschwindigkeit"],
    text: "Wo und wann ist die Gefahr von Aquaplaning besonders groß?",
    answers: [t("In Spurrillen und Senken, in denen sich Wasser sammelt"), t("Bei hoher Geschwindigkeit und geringer Profiltiefe"), t("Bei zu niedrigem Reifendruck"), f("Nur bei Geschwindigkeiten über 130 km/h", "Aquaplaning kann je nach Wassertiefe und Profil schon bei deutlich niedrigeren Geschwindigkeiten auftreten.")],
    explanation: "Aquaplaning entsteht, wenn das Profil das Wasser nicht mehr schnell genug verdrängen kann. Begünstigt wird es durch tiefes Wasser in Spurrillen, hohe Geschwindigkeit, abgefahrenes Profil und zu niedrigen Reifendruck. Anzeichen sind lautes Rauschen der Reifen und eine leichte Lenkung.",
  }),
  q({
    code: "own-besondere_situationen-027", topic: "besondere_situationen", points: 3, difficulty: 0.6, tags: ["seitenwind", "lkw", "ueberholen", "autobahn"],
    text: "Bei starkem Seitenwind überholen Sie auf der Autobahn einen Lkw. Womit müssen Sie rechnen?",
    answers: [t("Im Windschatten des Lkw lässt der Winddruck nach, beim Verlassen des Windschattens setzt er plötzlich wieder ein"), t("Der Lkw selbst kann durch Windböen seitlich versetzt werden"), f("Neben dem Lkw ist der Seitenwind am stärksten", "Neben dem Lkw ist man im Windschatten; gefährlich ist der Übergang."), f("Seitenwind wirkt sich beim Überholen nicht aus, weil die Geschwindigkeit hoch ist", "Gerade bei hoher Geschwindigkeit sind Windeinflüsse gefährlich.")],
    explanation: "Beim Überholen großer Fahrzeuge fällt der Seitenwind im Windschatten weg und greift beim Herausfahren plötzlich wieder an. Deshalb das Lenkrad fest halten, die Geschwindigkeit anpassen und auf Lenkkorrekturen gefasst sein. Auch der Lkw kann von einer Böe versetzt werden.",
  }),
  q({
    code: "own-besondere_situationen-028", topic: "besondere_situationen", points: 3, difficulty: 0.55, tags: ["baustelle", "gelbe_markierung", "fahrstreifen"],
    text: "In einer Baustelle sind gelbe und weiße Fahrbahnmarkierungen gleichzeitig zu sehen. Was gilt?",
    answers: [t("Die gelben Markierungen gehen vor und heben die weißen auf"), f("Die weißen Markierungen gelten, weil sie dauerhaft sind", "Gelbe Markierungen sind vorübergehend und gehen vor."), f("Beide gelten gleichzeitig, es ist der breitere Fahrstreifen zu nutzen", "Die gelben Markierungen bestimmen allein die Verkehrsführung.")],
    explanation: "Gelbe Markierungen kennzeichnen eine vorübergehende Verkehrsführung, etwa in Baustellen, und haben Vorrang vor den weißen Markierungen. Hinzu kommen oft verengte Fahrstreifen, für die Breitenbeschränkungen gelten.",
    legalReference: "§ 39 Abs. 5 StVO",
  }),
  q({
    code: "own-besondere_situationen-029", topic: "besondere_situationen", points: 3, difficulty: 0.6, tags: ["baustelle", "breite", "fahrstreifen", "lkw"],
    text: "In einer Autobahnbaustelle ist der linke Fahrstreifen mit dem Zeichen 264 auf 2 Meter Breite beschränkt. Was ist zu beachten?",
    answers: [t("Fahrzeuge, die einschließlich Ladung und Außenspiegeln breiter als 2 Meter sind, dürfen diesen Streifen nicht benutzen"), t("Sie müssen die tatsächliche Breite Ihres Fahrzeugs kennen, bevor Sie den Streifen wählen"), f("Die Beschränkung gilt nur für Lkw", "Sie gilt für alle Fahrzeuge, deren tatsächliche Breite den Wert überschreitet."), f("Die Breite wird ohne Außenspiegel gemessen, daher passt jeder Pkw", "Maßgeblich ist die tatsächliche Breite einschließlich Anbauten.")],
    explanation: "Zeichen 264 verbietet Fahrzeugen, deren tatsächliche Breite einschließlich Ladung den angegebenen Wert überschreitet, die Benutzung. In Baustellen wird die Breite oft auf 2 Meter begrenzt; viele Pkw und Wohnmobile mit Spiegeln liegen darüber und müssen rechts bleiben.",
    legalReference: "Anlage 2 StVO, Zeichen 264", reviewStatus: "needs_verification",
  }),
  q({
    code: "own-besondere_situationen-030", topic: "besondere_situationen", points: 3, difficulty: 0.6, tags: ["oelspur", "gefahrzeichen", "schleudergefahr"],
    text: "Das Zeichen 114 (Schleudergefahr) steht mit dem Zusatzzeichen Ölspur. Wie verhalten Sie sich?",
    answers: [t("Geschwindigkeit deutlich verringern und heftige Lenk- und Bremsmanöver vermeiden"), t("Den Abstand zum Vordermann vergrößern"), f("Mit gleichbleibender Geschwindigkeit durchfahren, damit die Reifen nicht rutschen", "Auf Öl haften Reifen kaum; hohe Geschwindigkeit ist gefährlich."), f("Sofort stark bremsen, um vor der Ölspur zum Stehen zu kommen", "Abruptes Bremsen auf Öl führt zum Blockieren und Schleudern.")],
    explanation: "Auf einer Ölspur ist die Reibung zwischen Reifen und Fahrbahn stark verringert. Sanft und rechtzeitig verzögern, gleichmäßig lenken und den Abstand vergrößern. Das Zusatzzeichen erklärt, warum die Fahrbahn rutschig ist.",
    legalReference: "Anlage 1 StVO, Zeichen 114; Zusatzzeichen 1006-30",
  }),
  q({
    code: "own-besondere_situationen-031", topic: "besondere_situationen", points: 3, difficulty: 0.55, tags: ["blendung", "gegenverkehr", "dunkelheit", "fernlicht"],
    text: "Nachts blendet Sie ein entgegenkommendes Fahrzeug mit Fernlicht. Was ist richtig?",
    answers: [t("Blick auf den rechten Fahrbahnrand richten und sich an der Fahrbahnbegrenzung orientieren"), t("Geschwindigkeit verringern und notfalls anhalten, wenn Sie nichts mehr erkennen"), f("Selbst das Fernlicht einschalten, damit der andere abblendet", "Gegenseitiges Blenden verdoppelt die Gefahr."), f("Den Blick fest auf das entgegenkommende Fahrzeug richten, um die Spur zu halten", "Der Blick ins Licht verstärkt die Blendung.")],
    explanation: "Bei Blendung nicht in die Scheinwerfer sehen, sondern am rechten Fahrbahnrand orientieren, langsamer fahren und im Zweifel anhalten. Zurückblenden ist verboten und gefährdet beide Fahrzeuge. Kurzes Betätigen der Lichthupe als Hinweis ist erlaubt, wenn es nicht blendet.",
    legalReference: "§ 17 Abs. 2 StVO; § 3 Abs. 1 StVO",
  }),
  q({
    code: "own-besondere_situationen-032", topic: "besondere_situationen", points: 3, difficulty: 0.6, tags: ["einsatzfahrzeug", "blaulicht", "kolonne", "ueberholen"],
    text: "Vor Ihnen fährt eine geschlossene Kolonne von Einsatzfahrzeugen mit Blaulicht ohne Einsatzhorn. Was gilt?",
    answers: [t("Sie dürfen nicht in die Kolonne einscheren und sie nicht unterbrechen"), t("Blaulicht ohne Einsatzhorn kann auch vor einer Unfallstelle warnen oder einen begleiteten Schwertransport ankündigen; erhöhte Aufmerksamkeit ist nötig"), f("Ohne Einsatzhorn haben die Fahrzeuge keine Sonderrechte, deshalb dürfen Sie normal überholen", "Geschlossene Verbände dürfen nicht unterbrochen werden."), f("Sie müssen sofort anhalten und den Motor abstellen", "Anhalten ist nur nötig, wenn freie Bahn anders nicht möglich ist.")],
    explanation: "Blaues Blinklicht allein warnt vor einer Unfall- oder Einsatzstelle, kündigt einen geschlossenen Verband an oder begleitet Schwertransporte. Geschlossene Verbände dürfen nicht unterbrochen werden. Nur Blaulicht zusammen mit Einsatzhorn verpflichtet zum sofortigen Freimachen der Bahn.",
    legalReference: "§ 38 Abs. 1 und 2 StVO; § 27 Abs. 2 StVO",
  }),
  q({
    code: "own-besondere_situationen-033", topic: "besondere_situationen", points: 3, difficulty: 0.55, tags: ["gelbes_blinklicht", "winterdienst", "raeumfahrzeug"],
    text: "Vor Ihnen fährt ein Winterdienstfahrzeug mit gelbem Blinklicht und streut Salz. Was gilt?",
    answers: [t("Gelbes Blinklicht warnt vor einer Gefahr; Sie müssen Abstand halten und mit Streugut sowie glatten Stellen rechnen"), f("Gelbes Blinklicht verpflichtet Sie, sofort anzuhalten", "Gelbes Blinklicht warnt nur, es ordnet nichts an."), f("Winterdienstfahrzeuge dürfen nie überholt werden", "Ein allgemeines Überholverbot besteht nicht; Überholen ist nur bei ausreichender Sicht und ohne Gefährdung sinnvoll.")],
    explanation: "Gelbes Blinklicht warnt vor Arbeits- und Unfallstellen, ungewöhnlich langsamen Fahrzeugen oder ungewöhnlich breiten Fahrzeugen. Es gibt keine Sonderrechte, verlangt aber Aufmerksamkeit. Hinter Räumfahrzeugen ist die Fahrbahn zunächst glatter und mit Streugut bedeckt.",
    legalReference: "§ 38 Abs. 3 StVO",
  }),
  q({
    code: "own-besondere_situationen-034", topic: "besondere_situationen", points: 3, difficulty: 0.6, tags: ["landwirtschaft", "verschmutzung", "ausserorts", "herbst"],
    text: "Im Herbst fahren Sie außerorts an Feldern vorbei, von denen Traktoren auf die Straße fahren. Womit müssen Sie rechnen?",
    answers: [t("Mit verschmutzter, rutschiger Fahrbahn durch Erde und nasses Laub"), t("Mit sehr langsamen, breiten Fahrzeugen, die unvermittelt abbiegen oder einfahren"), t("Mit schlechter Sicht durch Nebel und tief stehende Sonne"), f("Mit einem generellen Überholverbot für landwirtschaftliche Fahrzeuge", "Ein solches Verbot gibt es nicht; Überholen verlangt aber besondere Vorsicht.")],
    explanation: "In der Erntezeit bringen landwirtschaftliche Fahrzeuge Erde auf die Fahrbahn, die bei Nässe wie Schmierseife wirkt. Diese Fahrzeuge sind langsam, breit und schwenken beim Abbiegen weit aus. Herbstliche Sicht- und Wetterbedingungen verschärfen die Lage.",
  }),
  q({
    code: "own-besondere_situationen-035", topic: "besondere_situationen", points: 3, difficulty: 0.6, tags: ["kuppe", "unuebersichtlich", "ueberholen", "geschwindigkeit"],
    text: "Sie nähern sich außerorts einer Bergkuppe. Was gilt?",
    answers: [t("Überholen ist verboten, weil die Strecke nicht übersehbar ist"), t("Die Geschwindigkeit muss so gewählt werden, dass Sie innerhalb der übersehbaren Strecke anhalten können"), f("Sie dürfen überholen, wenn Sie schneller als 100 km/h fahren können", "Die Geschwindigkeit ändert nichts an der fehlenden Sicht."), f("Auf Kuppen gelten keine besonderen Regeln", "Unübersichtliche Stellen erfordern angepasste Geschwindigkeit und Überholverzicht.")],
    explanation: "Vor Kuppen und in unübersichtlichen Kurven ist Überholen verboten, weil der Gegenverkehr nicht erkennbar ist. Zugleich muss die Geschwindigkeit so gewählt werden, dass innerhalb der übersehbaren Strecke angehalten werden kann.",
    legalReference: "§ 5 Abs. 2 StVO; § 3 Abs. 1 StVO",
  }),
  q({
    code: "own-besondere_situationen-036", topic: "besondere_situationen", points: 3, difficulty: 0.4, tags: ["stau", "autobahn", "warnblinklicht", "rettungsgasse"],
    text: "Sie stehen auf der Autobahn im Stau. Was ist richtig?",
    answers: [t("Die Rettungsgasse bilden und den Seitenstreifen freihalten"), t("Nicht aussteigen und nicht zwischen den Fahrzeugen umhergehen"), f("Den Seitenstreifen nutzen, um zur nächsten Ausfahrt zu gelangen", "Der Seitenstreifen ist für Notfälle und Einsatzfahrzeuge bestimmt."), f("Wenden und gegen die Fahrtrichtung zur letzten Auffahrt zurückfahren", "Wenden und Rückwärtsfahren sind auf der Autobahn verboten.")],
    explanation: "Im Stau auf der Autobahn ist die Rettungsgasse zwischen dem linken und den übrigen Fahrstreifen zu bilden. Der Seitenstreifen bleibt frei. Aussteigen ist gefährlich und nur in Notfällen zulässig; Wenden und Rückwärtsfahren sind verboten.",
    legalReference: "§ 11 Abs. 2 StVO; § 18 StVO",
  }),
  q({
    code: "own-besondere_situationen-037", topic: "besondere_situationen", points: 3, difficulty: 0.45, tags: ["gewitter", "sturm", "hagel"],
    text: "Während der Fahrt setzt ein heftiges Gewitter mit Hagel und Sturmböen ein. Wie verhalten Sie sich?",
    answers: [t("Geschwindigkeit stark verringern, Abstand vergrößern und Abblendlicht einschalten"), t("Wenn möglich sicher anhalten, aber nicht unter Bäumen oder Brücken mit Gefahr durch herabfallende Teile"), f("Auf der Autobahn auf dem Seitenstreifen anhalten und das Gewitter abwarten", "Der Seitenstreifen ist nur für Notfälle; ein Gewitter ist keiner."), f("Fernlicht einschalten, um im Hagel besser zu sehen", "Fernlicht wird von Niederschlag reflektiert und verschlechtert die Sicht.")],
    explanation: "Bei Hagel und Sturm sinken Sicht und Haftung stark, zudem können Äste oder Gegenstände auf die Fahrbahn geweht werden. Langsam fahren, Abstand halten, Abblendlicht einschalten und nur an sicheren Stellen anhalten, etwa auf einem Parkplatz.",
    legalReference: "§ 3 Abs. 1 StVO; § 17 Abs. 3 StVO",
  }),
  q({
    code: "own-besondere_situationen-038", topic: "besondere_situationen", points: 2, difficulty: 0.4, tags: ["glaette", "winter", "blitzeis"],
    text: "Woran erkennen Sie während der Fahrt, dass die Fahrbahn vereist sein könnte?",
    answers: [t("Die Reifengeräusche werden plötzlich leiser und die Lenkung fühlt sich leichter an"), t("Die Außentemperatur liegt um den Gefrierpunkt und die Fahrbahn glänzt"), f("Der Motor läuft unruhig", "Der Motorlauf hängt nicht von der Fahrbahn ab."), f("Das Fahrzeug bremst besser als sonst", "Auf Eis verlängert sich der Bremsweg um ein Vielfaches.")],
    explanation: "Auf Eis rollen die Reifen fast geräuschlos und die Lenkung wird leichtgängig, weil die Seitenführung fehlt. Glänzende Fahrbahn bei Temperaturen um null Grad ist ein Warnzeichen. Dann besonders sanft fahren und Abstand vergrößern.",
  }),
  q({
    code: "own-besondere_situationen-039", topic: "besondere_situationen", points: 2, difficulty: 0.4, tags: ["wildwechsel", "ausserorts", "daemmerung"],
    text: "Wann und wo ist die Gefahr von Wildwechsel am größten?",
    answers: [t("In der Dämmerung und nachts an Wald- und Feldrändern"), f("Mittags auf Autobahnen", "Wild ist vor allem in der Dämmerung und nachts unterwegs, Autobahnen sind meist eingezäunt."), f("Nur im Winter", "Wildwechsel gibt es das ganze Jahr, besonders im Frühjahr und Herbst.")],
    explanation: "Wild ist vor allem in der Morgen- und Abenddämmerung sowie nachts aktiv, besonders an Waldrändern und zwischen Feldern und Wald. Dort Geschwindigkeit reduzieren, Fahrbahnränder beobachten und bremsbereit bleiben.",
  }),
  q({
    code: "own-besondere_situationen-040", topic: "besondere_situationen", points: 2, difficulty: 0.4, tags: ["bewegliche_bruecke", "gefahrzeichen", "ufer"],
    text: "Sie sehen das Gefahrzeichen 128 (Bewegliche Brücke). Womit müssen Sie rechnen?",
    answers: [t("Die Brücke kann für den Schiffsverkehr geöffnet sein; vor Schranken oder Lichtzeichen ist anzuhalten"), f("Die Brücke schwankt bei Wind stark", "Das Zeichen warnt vor dem Öffnen der Brücke, nicht vor Schwanken."), f("Die Brücke ist nur für Fußgänger freigegeben", "Das Zeichen sagt nichts über die zugelassenen Verkehrsarten aus.")],
    explanation: "Zeichen 128 warnt vor einer Klapp- oder Drehbrücke. Sie kann für die Schifffahrt geöffnet werden, dann sperren Schranken und Lichtzeichen die Zufahrt. Bremsbereit annähern und Signale beachten.",
    legalReference: "Anlage 1 StVO, Zeichen 128",
  }),
];
