// Übungsfragen zum Thema "fahrphysik" (eigene Formulierungen, kein amtlicher Prüfungsinhalt).
import type { Question } from "../types";
import { q, t, f } from "./_helpers";

export const fahrphysik: readonly Question[] = [
  q({
    code: "own-fahrphysik-001", topic: "fahrphysik", points: 3, difficulty: 0.3, tags: ["fliehkraft", "kurve"],
    text: "Sie fahren eine Kurve mit doppelter Geschwindigkeit. Wie verändert sich die Fliehkraft?",
    answers: [t("Sie wird viermal so groß"), f("Sie verdoppelt sich", "Die Fliehkraft wächst mit dem Quadrat der Geschwindigkeit."), f("Sie bleibt gleich, nur der Kurvenradius ändert sich", "Bei gleichem Radius steigt die Fliehkraft deutlich.")],
    explanation: "Die Fliehkraft in der Kurve wächst mit dem Quadrat der Geschwindigkeit. Doppeltes Tempo bedeutet vierfache Fliehkraft; deshalb vor der Kurve bremsen, nicht in der Kurve.",
  }),
  q({
    code: "own-fahrphysik-002", topic: "fahrphysik", points: 3, difficulty: 0.3, tags: ["abs", "bremsen", "gefahrenbremsung"],
    text: "Was gilt für das Antiblockiersystem (ABS)?",
    answers: [t("Das Fahrzeug bleibt bei einer Vollbremsung lenkbar"), t("Bei einer Gefahrenbremsung wird das Bremspedal voll durchgetreten und gehalten, nicht gepumpt"), f("ABS verkürzt den Bremsweg auf jedem Untergrund", "Auf losem Untergrund wie Schotter kann der Bremsweg mit ABS sogar länger sein.")],
    explanation: "ABS verhindert das Blockieren der Räder und erhält die Lenkfähigkeit. Bei der Gefahrenbremsung voll bremsen und das Pulsieren im Pedal ignorieren.",
  }),
  q({
    code: "own-fahrphysik-003", topic: "fahrphysik", points: 2, difficulty: 0.3, tags: ["esp", "assistenzsysteme", "schleudern"],
    text: "Wie wirkt das Elektronische Stabilitätsprogramm (ESP)?",
    answers: [t("Es erkennt beginnendes Schleudern und bremst einzelne Räder gezielt ab, um das Fahrzeug zu stabilisieren"), f("Es erhöht die Motorleistung in Kurven", "ESP greift bremsend und leistungsreduzierend ein."), f("Es ersetzt die Winterreifen", "ESP kann fehlende Reifenhaftung nicht ersetzen.")],
    explanation: "ESP vergleicht die gewünschte mit der tatsächlichen Fahrtrichtung und bremst bei Abweichung einzelne Räder ab. Die physikalischen Grenzen der Haftung kann es nicht verschieben.",
  }),
  q({
    code: "own-fahrphysik-004", topic: "fahrphysik", points: 3, difficulty: 0.3, tags: ["gefahrenbremsung", "bremsen", "kupplung"],
    text: "Wie führen Sie mit einem Schaltwagen eine Gefahrenbremsung durch?",
    answers: [t("Bremspedal sofort voll durchtreten und gleichzeitig die Kupplung treten"), f("Zuerst herunterschalten, dann bremsen", "Schalten kostet wertvolle Zeit."), f("Nur leicht bremsen, um ein Blockieren zu vermeiden", "Mit ABS darf und muss voll gebremst werden.")],
    explanation: "Bei der Gefahrenbremsung zählt jeder Meter: Bremse voll durchtreten, Kupplung treten, damit der Motor nicht abwürgt, und mit ABS weiter lenken.",
  }),
  q({
    code: "own-fahrphysik-005", topic: "fahrphysik", points: 2, difficulty: 0.2, tags: ["naesse", "bremsweg", "haftung"],
    text: "Wie verändert sich das Fahrverhalten auf nasser Fahrbahn?",
    answers: [t("Der Bremsweg wird länger und die Haftung in Kurven nimmt ab"), f("Der Bremsweg bleibt gleich, nur die Sicht ist schlechter", "Nässe verringert die Reibung zwischen Reifen und Fahrbahn."), f("Die Haftung wird durch den Wasserfilm besser", "Der Wasserfilm trennt Reifen und Fahrbahn.")],
    explanation: "Auf nasser Fahrbahn sinkt die Reibung zwischen Reifen und Straße. Bremsweg und Kurvenradius wachsen, deshalb Geschwindigkeit und Abstand anpassen.",
  }),
  q({
    code: "own-fahrphysik-006", topic: "fahrphysik", points: 2, difficulty: 0.3, tags: ["assistenzsysteme", "notbremsassistent"],
    text: "Was gilt für Fahrerassistenzsysteme wie Notbremsassistent oder Abstandsregeltempomat?",
    answers: [t("Sie unterstützen den Fahrer, ersetzen aber nicht seine Aufmerksamkeit und Verantwortung"), f("Mit Notbremsassistent muss der Fahrer nicht mehr selbst bremsen", "Das System kann Situationen übersehen; der Fahrer bleibt verantwortlich."), f("Der Abstandsregeltempomat erkennt alle Hindernisse zuverlässig", "Stehende Hindernisse und Querverkehr werden nicht immer erkannt.")],
    explanation: "Assistenzsysteme haben Systemgrenzen und reagieren nicht in jeder Situation. Der Fahrer muss jederzeit eingreifen können und bleibt verantwortlich.",
  }),
  q({
    code: "own-fahrphysik-007", topic: "fahrphysik", points: 2, difficulty: 0.3, tags: ["beladung", "schwerpunkt", "dachlast"],
    text: "Wie wirkt sich eine schwere Dachlast auf das Fahrverhalten aus?",
    answers: [t("Der Schwerpunkt liegt höher, das Fahrzeug neigt sich in Kurven stärker und kippt leichter"), f("Das Fahrzeug liegt durch das Gewicht besser auf der Straße", "Hoch liegende Lasten verschlechtern die Fahrstabilität."), f("Die Dachlast hat keinen Einfluss, solange die zulässige Gesamtmasse eingehalten wird", "Neben dem Gewicht zählt die Lage des Schwerpunkts.")],
    explanation: "Dachlasten heben den Schwerpunkt an und verändern das Kurven- und Bremsverhalten. Die zulässige Dachlast beachten und die Geschwindigkeit anpassen.",
  }),
  q({
    code: "own-fahrphysik-008", topic: "fahrphysik", points: 3, difficulty: 0.5, tags: ["untersteuern", "kurve"],
    text: "In einer Kurve schiebt Ihr Fahrzeug über die Vorderräder geradeaus (Untersteuern). Wie reagieren Sie?",
    answers: [t("Gas wegnehmen und den Lenkeinschlag nicht weiter vergrößern, damit die Vorderräder wieder Haftung finden"), f("Stärker einlenken und Gas geben", "Mehr Lenkwinkel und mehr Tempo verschlimmern das Untersteuern."), f("Die Feststellbremse ziehen", "Das führt zum Schleudern.")],
    explanation: "Beim Untersteuern haben die Vorderräder die Haftung verloren. Gas wegnehmen verlagert Gewicht nach vorn und verbessert die Haftung; der Lenkwinkel wird nicht vergrößert.",
  }),
  q({
    code: "own-fahrphysik-009", topic: "fahrphysik", points: 2, difficulty: 0.4, tags: ["kammscher_kreis", "haftung"],
    text: "Was besagt der Kammsche Kreis für das Fahren?",
    answers: [t("Ein Reifen kann nur eine begrenzte Gesamtkraft übertragen; wer gleichzeitig stark bremst und lenkt, teilt diese Kraft auf"), f("Reifen können Brems- und Seitenkraft unabhängig voneinander unbegrenzt übertragen", "Genau das Gegenteil ist der Fall."), f("Der Kreis beschreibt den Wendekreis des Fahrzeugs", "Er beschreibt die Kraftübertragung des Reifens.")],
    explanation: "Die Haftung eines Reifens ist begrenzt. Wird sie beim Bremsen voll genutzt, bleibt keine Reserve für das Lenken. Deshalb: vor der Kurve bremsen, in der Kurve rollen.",
  }),
  q({
    code: "own-fahrphysik-010", topic: "fahrphysik", points: 3, difficulty: 0.3, tags: ["bremsweg", "faustformel", "ausserorts"], kind: "numeric", numericAnswer: 100, tolerance: 0, unit: "m",
    text: "Wie lang ist der Bremsweg bei 100 km/h bei einer normalen Bremsung nach der Faustformel? Angabe in Metern.",
    answers: [],
    explanation: "Bremsweg = (100 / 10)² = 100 Meter. Erst bei einer Gefahrenbremsung halbiert sich dieser Wert auf etwa 50 Meter.",
  }),
  q({
    code: "own-fahrphysik-011", topic: "fahrphysik", points: 3, difficulty: 0.55, tags: ["anhalteweg", "reaktionsweg", "bremsweg", "faustformel"], kind: "numeric", numericAnswer: 88, tolerance: 0, unit: "m",
    text: "Wie lang ist der Anhalteweg bei 80 km/h nach den Faustformeln bei einer normalen Bremsung? Angabe in Metern.",
    answers: [],
    explanation: "Reaktionsweg = (80 / 10) × 3 = 24 Meter, Bremsweg = (80 / 10)² = 64 Meter. Der Anhalteweg ist die Summe: 24 + 64 = 88 Meter. Die Faustformeln gehen von einer Reaktionszeit von etwa einer Sekunde und trockener Fahrbahn aus.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-fahrphysik-012", topic: "fahrphysik", points: 3, difficulty: 0.6, tags: ["anhalteweg", "gefahrenbremsung", "faustformel", "reaktionsweg"], kind: "numeric", numericAnswer: 36, tolerance: 0, unit: "m",
    text: "Sie fahren 60 km/h und müssen eine Gefahrbremsung durchführen. Wie lang ist der Anhalteweg nach den Faustformeln? Angabe in Metern.",
    answers: [],
    explanation: "Reaktionsweg = (60 / 10) × 3 = 18 Meter. Bremsweg bei Gefahrbremsung = (60 / 10)² / 2 = 36 / 2 = 18 Meter. Anhalteweg = 18 + 18 = 36 Meter. Der Reaktionsweg bleibt bei der Gefahrbremsung unverändert, nur der Bremsweg halbiert sich.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-fahrphysik-013", topic: "fahrphysik", points: 2, difficulty: 0.5, tags: ["reaktionsweg", "faustformel", "autobahn"], kind: "numeric", numericAnswer: 36, tolerance: 0, unit: "m",
    text: "Wie lang ist der Reaktionsweg bei 120 km/h nach der Faustformel? Angabe in Metern.",
    answers: [],
    explanation: "Reaktionsweg = (120 / 10) × 3 = 36 Meter. In der Reaktionszeit von etwa einer Sekunde legt das Fahrzeug diese Strecke ungebremst zurück; erst danach beginnt der Bremsweg.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-fahrphysik-014", topic: "fahrphysik", points: 3, difficulty: 0.6, tags: ["bremsweg", "gefahrenbremsung", "faustformel", "autobahn"], kind: "numeric", numericAnswer: 72, tolerance: 0, unit: "m",
    text: "Wie lang ist der Bremsweg bei 120 km/h bei einer Gefahrbremsung nach der Faustformel? Angabe in Metern.",
    answers: [],
    explanation: "Bremsweg bei Gefahrbremsung = (120 / 10)² / 2 = 144 / 2 = 72 Meter. Bei normaler Bremsung wären es 144 Meter. Der Reaktionsweg von 36 Metern kommt beim Anhalteweg noch hinzu.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-fahrphysik-015", topic: "fahrphysik", points: 3, difficulty: 0.65, tags: ["bremsweg", "faustformel", "innerorts", "tempo_30"], kind: "numeric", numericAnswer: 16, tolerance: 0, unit: "m",
    text: "Um wie viele Meter ist der Bremsweg bei 50 km/h länger als bei 30 km/h (normale Bremsung, Faustformel)? Angabe in Metern.",
    answers: [],
    explanation: "Bremsweg bei 50 km/h = (50 / 10)² = 25 Meter, bei 30 km/h = (30 / 10)² = 9 Meter. Die Differenz beträgt 16 Meter. Der Bremsweg wächst mit dem Quadrat der Geschwindigkeit; deshalb wirkt Tempo 30 in Wohngebieten so stark.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-fahrphysik-016", topic: "fahrphysik", points: 3, difficulty: 0.6, tags: ["fliehkraft", "kurve", "geschwindigkeit"], kind: "numeric", numericAnswer: 9, tolerance: 0,
    text: "Sie durchfahren dieselbe Kurve mit dreifacher Geschwindigkeit. Um welchen Faktor wächst die Fliehkraft? Angabe als Zahl.",
    answers: [],
    explanation: "Die Fliehkraft wächst mit dem Quadrat der Geschwindigkeit: dreifache Geschwindigkeit ergibt 3² = 9-fache Fliehkraft. Weil die Reifen nur begrenzt Seitenkraft übertragen können, muss die Geschwindigkeit vor der Kurve angepasst werden.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-fahrphysik-017", topic: "fahrphysik", points: 3, difficulty: 0.6, tags: ["reaktionsweg", "reaktionszeit", "ablenkung"],
    text: "Durch einen Blick auf das Mobiltelefon verdoppelt sich Ihre Reaktionszeit von einer auf zwei Sekunden. Wie verändert sich der Reaktionsweg bei 100 km/h?",
    answers: [t("Er verdoppelt sich, von rund 30 auf rund 60 Meter"), f("Er vervierfacht sich", "Der Reaktionsweg wächst linear mit der Reaktionszeit, nicht quadratisch."), f("Er bleibt gleich, nur der Bremsweg wird länger", "Der Bremsweg hängt nicht von der Reaktionszeit ab; verlängert wird der Reaktionsweg.")],
    explanation: "Der Reaktionsweg ist das Produkt aus Geschwindigkeit und Reaktionszeit. Bei 100 km/h legt das Fahrzeug in einer Sekunde rund 28 Meter zurück, nach der Faustformel 30 Meter. Verdoppelt sich die Reaktionszeit durch Ablenkung, verdoppelt sich auch der Reaktionsweg.",
    legalReference: "§ 23 Abs. 1a StVO",
  }),
  q({
    code: "own-fahrphysik-018", topic: "fahrphysik", points: 3, difficulty: 0.65, tags: ["anhalteweg", "reaktionsweg", "bremsweg", "faustformel"],
    text: "Sie erhöhen Ihre Geschwindigkeit von 50 auf 100 km/h. Wie verändern sich Reaktionsweg und Bremsweg nach den Faustformeln?",
    answers: [t("Der Reaktionsweg verdoppelt sich von 15 auf 30 Meter, der Bremsweg vervierfacht sich von 25 auf 100 Meter"), f("Beide Wege verdoppeln sich", "Der Bremsweg wächst quadratisch mit der Geschwindigkeit und vervierfacht sich."), f("Beide Wege vervierfachen sich", "Der Reaktionsweg wächst nur linear und verdoppelt sich."), f("Der Anhalteweg verdoppelt sich genau", "Der Anhalteweg steigt von 40 auf 130 Meter, also auf mehr als das Dreifache.")],
    explanation: "Reaktionsweg = (v / 10) × 3 wächst linear: 15 Meter bei 50 km/h, 30 Meter bei 100 km/h. Bremsweg = (v / 10)² wächst quadratisch: 25 Meter bei 50 km/h, 100 Meter bei 100 km/h. Der Anhalteweg steigt damit von 40 auf 130 Meter.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-fahrphysik-019", topic: "fahrphysik", points: 3, difficulty: 0.6, tags: ["kammscher_kreis", "kurve", "bremsen", "haftung"],
    text: "Welche Aussagen folgen aus dem Kammschen Kreis für das Bremsen in Kurven?",
    answers: [t("Wer in der Kurve stark bremst, hat kaum noch Seitenführungskraft; das Fahrzeug schiebt geradeaus oder das Heck bricht aus"), t("Vor der Kurve bremsen, in der Kurve mit gleichmäßiger Geschwindigkeit rollen und erst am Kurvenausgang beschleunigen"), f("In der Kurve darf voll gebremst werden, weil ABS die Seitenführung immer sicherstellt", "ABS erhält die Lenkfähigkeit, kann aber die begrenzte Gesamtkraft des Reifens nicht vergrößern."), f("Gasgeben in der Kurve erhöht die Seitenführungskraft", "Auch Antriebskraft verbraucht einen Teil der begrenzten Reifenkraft.")],
    explanation: "Ein Reifen kann nur eine begrenzte Gesamtkraft übertragen, die sich aus Längskraft (Bremsen, Beschleunigen) und Seitenkraft (Lenken) zusammensetzt. Je mehr davon zum Bremsen genutzt wird, desto weniger bleibt für die Kurvenführung. Deshalb gilt: vor der Kurve bremsen, in der Kurve rollen, am Ausgang beschleunigen.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-fahrphysik-020", topic: "fahrphysik", points: 3, difficulty: 0.6, tags: ["reibung", "haftreibung", "gleitreibung", "blockieren"],
    text: "Welche Aussage zur Reibung zwischen Reifen und Fahrbahn ist richtig?",
    answers: [t("Ein rollendes Rad nutzt die Haftreibung; ein blockiertes Rad überträgt nur die geringere Gleitreibung und keine Seitenführungskraft"), f("Blockierte Räder bremsen am kürzesten, weil der Reifen am stärksten über die Fahrbahn reibt", "Beim Blockieren geht die Haftreibung in die geringere Gleitreibung über; der Bremsweg wird länger und das Fahrzeug ist nicht mehr lenkbar."), f("Die Reibung hängt nur von der Geschwindigkeit ab, nicht vom Reifenzustand", "Profiltiefe, Gummimischung, Luftdruck und Fahrbahnzustand bestimmen die Reibung wesentlich.")],
    explanation: "Haftreibung ist größer als Gleitreibung. Solange das Rad rollt, haftet der Reifen und kann Brems- und Seitenkräfte übertragen. Blockiert es, rutscht der Reifen, die Bremswirkung sinkt und das Fahrzeug lässt sich nicht mehr lenken. ABS hält die Räder deshalb an der Blockiergrenze.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-fahrphysik-021", topic: "fahrphysik", points: 3, difficulty: 0.6, tags: ["reibung", "haftung", "glaette", "naesse"],
    text: "Auf welchen Fahrbahnen ist die Haftung der Reifen besonders gering?",
    answers: [t("Auf Eis und festgefahrenem Schnee"), t("Auf nassem Laub, Ölspuren und nassem Kopfsteinpflaster"), f("Auf trockenem, rauem Asphalt", "Trockener rauer Asphalt bietet die beste Haftung."), f("Nach längerem Regen, weil die Fahrbahn dann glatter ist als bei Regenbeginn", "Bei Regenbeginn bilden Staub und Ölreste einen Schmierfilm; nach längerem Regen ist dieser weggespült.")],
    explanation: "Die Haftung sinkt auf Eis, Schnee, nassem Laub, Ölspuren und poliertem Kopfsteinpflaster drastisch, teils auf ein Zehntel des Wertes auf trockenem Asphalt. Besonders tückisch ist der Beginn eines Regens, wenn Staub und Öl auf der Fahrbahn einen Schmierfilm bilden.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-fahrphysik-022", topic: "fahrphysik", points: 3, difficulty: 0.65, tags: ["aquaplaning", "naesse", "reifen", "profiltiefe"],
    text: "Welche Faktoren erhöhen die Gefahr von Aquaplaning?",
    answers: [t("Tiefes Wasser in Spurrillen, hohe Geschwindigkeit und geringe Profiltiefe"), t("Breite Reifen und zu niedriger Reifendruck"), f("Schmale Reifen mit tiefem Profil", "Schmale Reifen mit gutem Profil verdrängen das Wasser besser und schwimmen später auf."), f("Aquaplaning tritt erst über 130 km/h auf", "Je nach Wassertiefe und Reifen kann Aquaplaning schon deutlich unter 80 km/h auftreten.")],
    explanation: "Aquaplaning entsteht, wenn der Reifen das Wasser nicht mehr schnell genug verdrängen kann und auf einem Wasserkeil aufschwimmt. Begünstigt wird das durch hohe Wasserstände, hohe Geschwindigkeit, wenig Profil, breite Reifen und zu geringen Luftdruck. Unter etwa 3 mm Profiltiefe nimmt die Wasserverdrängung spürbar ab.",
    legalReference: "§ 3 Abs. 1 StVO; § 36 StVZO",
  }),
  q({
    code: "own-fahrphysik-023", topic: "fahrphysik", points: 4, difficulty: 0.65, tags: ["aquaplaning", "naesse", "lenken", "bremsen"],
    text: "Ihr Fahrzeug schwimmt bei starkem Regen plötzlich auf (Aquaplaning), die Lenkung wird leicht. Wie reagieren Sie richtig?",
    answers: [t("Gas wegnehmen, bei Schaltwagen auskuppeln, Lenkrad ruhig geradeaus halten und nicht bremsen, bis die Räder wieder greifen"), f("Kräftig bremsen, um schnell langsamer zu werden", "Bremsen auf dem Wasserfilm bringt keine Verzögerung; greifen die Räder wieder, kann das Fahrzeug ausbrechen."), f("Stark gegenlenken, um die Spur zu halten", "Die Räder haben keinen Kontakt; ein großer Lenkeinschlag lässt das Fahrzeug beim Wiedergreifen ausbrechen."), f("Beschleunigen, um schneller aus der Wasserlache herauszukommen", "Höhere Geschwindigkeit verstärkt das Aufschwimmen.")],
    explanation: "Beim Aquaplaning haben die Reifen keinen Kontakt zur Fahrbahn, Bremsen und Lenken wirken nicht. Richtig ist, den Fuß vom Gas zu nehmen, auszukuppeln und das Lenkrad ruhig in Geradeausstellung zu halten, damit das Fahrzeug beim Wiedergreifen nicht ausbricht. Vorbeugend gilt: bei Nässe langsamer fahren und Spurrillen meiden.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-fahrphysik-024", topic: "fahrphysik", points: 3, difficulty: 0.6, tags: ["abs", "bremsweg", "schotter", "schnee"],
    text: "Welche Aussagen zum ABS treffen zu?",
    answers: [t("Auf losem Untergrund wie Schotter oder Neuschnee kann der Bremsweg mit ABS länger sein, weil sich vor blockierten Rädern ein bremsender Keil bilden würde"), t("Das Fahrzeug bleibt während der Vollbremsung lenkbar, weil die Räder nicht blockieren"), f("ABS verkürzt den Bremsweg auf jedem Untergrund", "Auf festem Untergrund ist der Bremsweg meist kürzer, auf losem kann er länger sein; der Hauptnutzen ist die Lenkbarkeit."), f("Wenn das Bremspedal pulsiert, sollten Sie den Druck verringern", "Das Pulsieren zeigt die Regelung an; das Pedal bleibt voll durchgetreten.")],
    explanation: "ABS hält die Räder an der Blockiergrenze und sichert die Lenkfähigkeit. Auf festem Untergrund verkürzt es meist den Bremsweg; auf Schotter, Splitt oder Neuschnee kann ein blockiertes Rad durch den sich aufschiebenden Keil stärker bremsen, sodass der Bremsweg mit ABS länger wird. Bei der Gefahrbremsung bleibt das Pedal trotz Pulsieren voll durchgetreten.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-fahrphysik-025", topic: "fahrphysik", points: 3, difficulty: 0.6, tags: ["asr", "antriebsschlupf", "assistenzsysteme", "schnee"],
    text: "Welche Aussagen zur Antriebsschlupfregelung (ASR) treffen zu?",
    answers: [t("ASR verhindert das Durchdrehen der Antriebsräder beim Anfahren und Beschleunigen durch Eingriffe in Motor und Bremse"), t("Beim Freischaukeln aus tiefem Schnee kann es sinnvoll sein, ASR vorübergehend abzuschalten"), f("ASR verkürzt den Bremsweg", "ASR wirkt beim Beschleunigen; beim Bremsen greift das ABS."), f("Mit ASR kann jede Kurve schneller durchfahren werden", "ASR verhindert Antriebsschlupf, erhöht aber nicht die übertragbare Seitenkraft.")],
    explanation: "Die Antriebsschlupfregelung erkennt durchdrehende Antriebsräder und reduziert das Motormoment oder bremst das durchdrehende Rad ab. Das verbessert Traktion und Spurstabilität beim Anfahren. Nur im tiefen Schnee oder Sand kann gezieltes Durchdrehen beim Freischaukeln helfen, dann darf ASR kurz abgeschaltet werden.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-fahrphysik-026", topic: "fahrphysik", points: 3, difficulty: 0.65, tags: ["esp", "assistenzsysteme", "fliehkraft", "grenzen"],
    text: "Welche Aussagen zu den Möglichkeiten und Grenzen des ESP treffen zu?",
    answers: [t("ESP kann die Fliehkraft nicht aufheben; bei zu hoher Kurvengeschwindigkeit rutscht auch ein Fahrzeug mit ESP nach außen"), t("ESP stabilisiert durch gezieltes Abbremsen einzelner Räder und durch Reduzierung des Motormoments"), f("Mit ESP darf jede Kurve deutlich schneller gefahren werden", "ESP verschiebt die physikalischen Grenzen nicht; es hilft nur, sie im Grenzbereich besser zu nutzen."), f("ESP arbeitet nur oberhalb von 80 km/h", "ESP greift in jedem Geschwindigkeitsbereich ein, auch bei langsamen Ausweichmanövern.")],
    explanation: "ESP vergleicht ständig die vom Fahrer gewünschte mit der tatsächlichen Fahrtrichtung. Weicht das Fahrzeug ab, bremst es einzelne Räder und nimmt Motorleistung zurück. Die Haftung der Reifen kann es nicht erhöhen; wer zu schnell in die Kurve fährt, rutscht trotz ESP.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-fahrphysik-027", topic: "fahrphysik", points: 3, difficulty: 0.6, tags: ["uebersteuern", "kurve", "schleudern", "gegenlenken"],
    text: "In einer Kurve bricht das Heck Ihres Fahrzeugs nach außen aus (Übersteuern). Wie reagieren Sie?",
    answers: [t("Gas wegnehmen beziehungsweise auskuppeln, in die Richtung gegenlenken, in die das Heck ausbricht, und den Lenkeinschlag zurücknehmen, sobald das Fahrzeug wieder greift"), f("Voll bremsen", "Eine Vollbremsung verlagert noch mehr Last nach vorn und verstärkt das Ausbrechen des Hecks."), f("Stärker in die Kurve einlenken", "Mehr Lenkeinschlag in Kurvenrichtung lässt das Fahrzeug weiter eindrehen und schleudern.")],
    explanation: "Beim Übersteuern verlieren die Hinterräder die Seitenführung. Gegenlenken heißt, in die Richtung zu lenken, in die das Heck ausbricht, und den Blick dorthin zu richten, wo man hin will. Lenken und Gaswegnehmen müssen dosiert erfolgen, sonst schwingt das Fahrzeug in die andere Richtung.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-fahrphysik-028", topic: "fahrphysik", points: 3, difficulty: 0.55, tags: ["schwerpunkt", "beladung", "dachlast", "untersteuern"],
    text: "Wie wirkt sich die Beladung auf das Fahrverhalten aus?",
    answers: [t("Eine schwere Dachlast hebt den Schwerpunkt: das Fahrzeug neigt sich in Kurven stärker, kippt leichter und reagiert empfindlicher auf Seitenwind"), t("Schwere Ladung im Kofferraum entlastet die Vorderachse: die Lenkung wird leichter, das Fahrzeug untersteuert eher und die Scheinwerfer blenden"), f("Beladung verkürzt den Bremsweg, weil die Reifen stärker angepresst werden", "Die höhere Masse erhöht die Bewegungsenergie; der Bremsweg wird länger."), f("Die Lage des Schwerpunkts spielt keine Rolle, solange die zulässige Gesamtmasse eingehalten wird", "Neben der Masse ist die Verteilung entscheidend für Kurven- und Bremsverhalten.")],
    explanation: "Zusätzliche Masse erhöht Bremsweg und Fliehkraft, und die Verteilung der Ladung verschiebt den Schwerpunkt. Hoch liegende Lasten fördern Wanken und Kippen, hecklastige Beladung entlastet die Vorderachse und verschlechtert Lenkung und Kurvenverhalten. Deshalb schwere Ladung tief und möglichst weit vorn verstauen.",
    legalReference: "§ 22 Abs. 1 StVO",
  }),
  q({
    code: "own-fahrphysik-029", topic: "fahrphysik", points: 3, difficulty: 0.6, tags: ["beladung", "reifenluftdruck", "leuchtweite", "bremsweg"],
    text: "Sie fahren mit voll beladenem Pkw in den Urlaub. Was passen Sie an?",
    answers: [t("Den Reifendruck nach der Tabelle des Herstellers auf die Werte für volle Beladung erhöhen"), t("Die Leuchtweite der Scheinwerfer einstellen, damit der Gegenverkehr nicht geblendet wird"), t("Größeren Sicherheitsabstand und geringere Kurvengeschwindigkeit wählen, weil Bremsweg und Fliehkraft zunehmen"), f("Den Reifendruck senken, damit die Reifen bei hoher Last weicher abrollen", "Zu niedriger Druck lässt die belasteten Reifen überhitzen und verschlechtert die Fahrstabilität.")],
    explanation: "Volle Beladung erhöht die Masse und verändert die Fahrzeuglage. Deshalb Reifendruck nach Herstellertabelle erhöhen, Leuchtweite anpassen, Ladung sichern und die Fahrweise auf längere Bremswege und höhere Fliehkräfte einstellen.",
    legalReference: "§ 22 StVO; § 23 Abs. 1 StVO",
  }),
  q({
    code: "own-fahrphysik-030", topic: "fahrphysik", points: 4, difficulty: 0.65, tags: ["anhaenger", "pendeln", "gespann", "bremsen"],
    text: "Ihr Wohnanhänger beginnt bei 90 km/h auf der Autobahn zu pendeln. Wie reagieren Sie richtig?",
    answers: [t("Kurz und kräftig bremsen und das Lenkrad dabei gerade halten, damit sich das Gespann streckt"), f("Beschleunigen, um den Anhänger wieder zu strecken", "Höhere Geschwindigkeit verstärkt das Pendeln bis zum Umkippen."), f("Kräftig gegenlenken, um jede Pendelbewegung auszugleichen", "Lenkbewegungen schaukeln das Gespann weiter auf."), f("Auskuppeln und ohne zu bremsen abwarten, bis sich der Anhänger beruhigt", "Ohne Bremsen kann sich das Pendeln aufschaukeln; ein beherzter Bremsstoß ist wirksamer.")],
    explanation: "Beim Pendeln zieht der Anhänger das Heck des Zugfahrzeugs abwechselnd nach links und rechts. Wirksam ist ein kräftiger Bremsstoß mit geradem Lenkrad: die Zugkraft am Haken streckt das Gespann. Eine Gespannstabilisierung im ESP macht das automatisch. Vorbeugend helfen ausreichende Stützlast, richtige Beladung und angepasste Geschwindigkeit.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-fahrphysik-031", topic: "fahrphysik", points: 3, difficulty: 0.6, tags: ["anhaenger", "pendeln", "stuetzlast", "seitenwind"],
    text: "Welche Ursachen begünstigen das Pendeln eines Anhängers?",
    answers: [t("Zu hohe Geschwindigkeit, besonders bergab"), t("Zu geringe Stützlast oder hecklastige Beladung des Anhängers"), t("Seitenwind und Luftverwirbelungen beim Überholen oder Überholtwerden von Lkw"), f("Ein zu hoher Reifendruck am Anhänger", "Zu niedriger Reifendruck macht den Anhänger instabil; ein etwas höherer Druck nach Herstellerangabe verbessert die Stabilität.")],
    explanation: "Ein Gespann pendelt, wenn die Seitenführung des Anhängers nicht mehr ausreicht. Hohe Geschwindigkeit, Gefälle, geringe Stützlast, Ladung weit hinten sowie Seitenwind und Lkw-Verwirbelungen sind die typischen Auslöser. Richtige Beladung und angepasste Geschwindigkeit verhindern das Pendeln am wirksamsten.",
    legalReference: "§ 3 Abs. 1 StVO; § 44 Abs. 3 StVZO",
  }),
  q({
    code: "own-fahrphysik-032", topic: "fahrphysik", points: 3, difficulty: 0.6, tags: ["seitenwind", "zeichen_117", "lkw", "bruecke"],
    text: "Das Gefahrzeichen 117 warnt vor Seitenwind. Welche Aussagen treffen zu?",
    answers: [t("Besonders gefährdet sind leichte und hohe Fahrzeuge, Gespanne und Motorräder; kritische Stellen sind Brücken, Waldschneisen und Dämme"), t("Lenkrad mit beiden Händen festhalten, Geschwindigkeit verringern und Windstöße durch leichtes Gegenlenken ausgleichen"), f("Beim Verlassen des Windschattens eines Lkw lässt der Seitenwind nach", "Beim Verlassen des Windschattens trifft der Wind plötzlich mit voller Kraft; damit muss gerechnet werden."), f("Bei Seitenwind schneller fahren, um den Gefahrenbereich rasch zu verlassen", "Je höher die Geschwindigkeit, desto stärker versetzt eine Böe das Fahrzeug.")],
    explanation: "Seitenwind versetzt das Fahrzeug seitlich, umso stärker, je schneller es fährt und je größer die Angriffsfläche ist. An Brücken, Waldrändern und beim Überholen von Lkw ändert sich die Windwirkung plötzlich. Richtig sind reduzierte Geschwindigkeit, festes Halten des Lenkrads und sanftes Gegenlenken.",
    legalReference: "§ 3 Abs. 1 StVO; Anlage 1 StVO, Zeichen 117",
  }),
  q({
    code: "own-fahrphysik-033", topic: "fahrphysik", points: 3, difficulty: 0.6, tags: ["reifenluftdruck", "reifen", "reifenplatzer", "aquaplaning"],
    text: "Welche Folgen hat ein zu niedriger Reifenluftdruck?",
    answers: [t("Der Reifen walkt stärker, erwärmt sich und kann zerstört werden; die Gefahr eines Reifenplatzers steigt"), t("Die Kurvenstabilität sinkt, die Aquaplaninggefahr und der Kraftstoffverbrauch steigen"), f("Der Bremsweg verkürzt sich, weil die Aufstandsfläche größer wird", "Der Reifen verformt sich ungleichmäßig, die Bremswirkung und die Seitenführung nehmen ab."), f("Der Reifen nutzt sich vor allem in der Laufflächenmitte ab", "Das ist typisch für zu hohen Druck; bei zu niedrigem Druck verschleißen die Schultern.")],
    explanation: "Zu wenig Luft lässt den Reifen stark walken; er erhitzt sich und kann bei hoher Geschwindigkeit platzen. Gleichzeitig werden Lenkung und Seitenführung schwammig, der Rollwiderstand und der Verbrauch steigen, und das Wasser wird schlechter verdrängt. Der Reifendruck ist deshalb regelmäßig bei kalten Reifen zu prüfen.",
    legalReference: "§ 36 StVZO; § 23 Abs. 1 StVO",
  }),
  q({
    code: "own-fahrphysik-034", topic: "fahrphysik", points: 2, difficulty: 0.45, tags: ["reifenluftdruck", "reifen", "kontrolle"],
    text: "Wann und wie prüfen Sie den Reifenluftdruck richtig?",
    answers: [t("Bei kalten Reifen, regelmäßig etwa alle zwei Wochen und vor längeren Fahrten; bei voller Beladung die höheren Werte aus der Herstellertabelle wählen"), f("Nach einer längeren Fahrt bei warmen Reifen und den Druck dann auf den Sollwert ablassen", "Warme Reifen zeigen einen höheren Druck; wer dann ablässt, fährt anschließend mit zu wenig Luft."), f("Nur bei Winterreifen, weil Sommerreifen den Druck besser halten", "Alle Reifen verlieren langsam Luft; die Kontrolle gilt für jede Bereifung.")],
    explanation: "Der Solldruck des Herstellers gilt für kalte Reifen. Nach längerer Fahrt liegt der Druck durch die Erwärmung höher und darf nicht abgelassen werden. Für hohe Beladung gibt die Tabelle im Tankdeckel oder Türholm erhöhte Werte an. Auch das Reserverad gehört zur Kontrolle.",
    legalReference: "§ 36 StVZO; § 23 Abs. 1 StVO",
  }),
  q({
    code: "own-fahrphysik-035", topic: "fahrphysik", points: 2, difficulty: 0.5, tags: ["bremsassistent", "gefahrenbremsung", "assistenzsysteme"],
    text: "Was leistet der Bremsassistent bei einer Gefahrbremsung?",
    answers: [t("Er erkennt am schnellen, kräftigen Tritt auf das Bremspedal eine Notbremsung und baut sofort den vollen Bremsdruck auf, auch wenn der Fahrer nicht fest genug tritt"), f("Er bremst das Fahrzeug selbstständig ab, ohne dass der Fahrer das Pedal betätigt", "Das ist die Aufgabe eines Notbremsassistenten mit Umfeldsensoren; der Bremsassistent verstärkt die Bremsung des Fahrers."), f("Er ersetzt das ABS", "Der Bremsassistent arbeitet zusammen mit ABS; das ABS verhindert weiterhin das Blockieren der Räder.")],
    explanation: "Viele Fahrer treten im Notfall zu zögerlich auf die Bremse. Der Bremsassistent erkennt die Notsituation an der Geschwindigkeit des Pedaltritts und stellt sofort die maximale Bremskraft bereit. Dadurch wird der Bremsweg deutlich kürzer; das ABS hält die Räder dabei lenkbar.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-fahrphysik-036", topic: "fahrphysik", points: 3, difficulty: 0.6, tags: ["bewegungsenergie", "aufprall", "geschwindigkeit"],
    text: "Welche Aussagen zur Bewegungsenergie bei einem Aufprall treffen zu?",
    answers: [t("Die Bewegungsenergie wächst mit dem Quadrat der Geschwindigkeit; ein Aufprall mit 50 km/h entspricht etwa einem Sturz aus 10 Metern Höhe"), t("Bei 70 km/h ist die Bewegungsenergie etwa doppelt so groß wie bei 50 km/h"), f("Die Bewegungsenergie wächst gleichmäßig mit der Geschwindigkeit", "Sie wächst quadratisch: doppelte Geschwindigkeit bedeutet vierfache Energie."), f("Ein Aufprall mit 100 km/h ist doppelt so heftig wie einer mit 50 km/h", "Bei doppelter Geschwindigkeit ist die Energie viermal so groß.")],
    explanation: "Die Bewegungsenergie hängt vom Quadrat der Geschwindigkeit ab: (70 / 50)² ergibt rund das Doppelte, (100 / 50)² das Vierfache. Beim Aufprall muss diese Energie von Fahrzeug und Insassen abgebaut werden. Deshalb entscheiden schon wenige km/h über die Schwere eines Unfalls.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-fahrphysik-037", topic: "fahrphysik", points: 3, difficulty: 0.6, tags: ["untersteuern", "uebersteuern", "kurve", "esp"],
    text: "Welche Aussagen zu Untersteuern und Übersteuern treffen zu?",
    answers: [t("Untersteuern: Die Vorderräder verlieren die Haftung, das Fahrzeug schiebt über die Vorderräder nach außen"), t("Übersteuern: Die Hinterräder verlieren die Haftung, das Heck drängt nach außen und das Fahrzeug dreht sich in die Kurve ein"), f("Untersteuern tritt nur bei Fahrzeugen mit Heckantrieb auf", "Untersteuern ist bei zu schneller Kurvenfahrt bei jedem Antrieb möglich und bei Frontantrieb sogar typisch."), f("ESP kann nur Übersteuern korrigieren", "ESP bremst je nach Situation Räder an der Innen- oder Außenseite ab und wirkt beiden Zuständen entgegen.")],
    explanation: "Beim Untersteuern reicht die Seitenführung vorn nicht aus, beim Übersteuern fehlt sie hinten. In beiden Fällen ist die Kurvengeschwindigkeit zu hoch für die verfügbare Haftung. ESP erkennt die Abweichung und stabilisiert durch gezieltes Abbremsen einzelner Räder.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-fahrphysik-038", topic: "fahrphysik", points: 2, difficulty: 0.5, tags: ["gefaelle", "motorbremse", "fading", "zeichen_108"],
    text: "Vor einem langen Gefälle steht das Zeichen 108 (Gefälle 10 %). Wie fahren Sie mit einem Schaltwagen richtig hinab?",
    answers: [t("Rechtzeitig herunterschalten und die Motorbremse nutzen, damit die Betriebsbremse nicht überhitzt"), f("Im Leerlauf rollen, um Kraftstoff zu sparen", "Ohne Motorbremse muss die Betriebsbremse die gesamte Energie abbauen und kann überhitzen; außerdem ist Leerlaufrollen unsicher."), f("Dauerhaft leicht auf der Bremse bleiben", "Dauerbremsen erhitzt die Bremsen; nachlassende Bremswirkung (Fading) ist die Folge.")],
    explanation: "Bergab wandelt die Bremse Bewegungsenergie in Wärme um. Wer im kleinen Gang mit Motorbremse fährt und nur kurz und kräftig nachbremst, hält die Bremsen kühl. Dauerhaftes Schleifenlassen führt zum Fading, also zum Nachlassen der Bremswirkung durch Überhitzung.",
    legalReference: "§ 3 Abs. 1 StVO; Anlage 1 StVO, Zeichen 108",
  }),
  q({
    code: "own-fahrphysik-039", topic: "fahrphysik", points: 3, difficulty: 0.55, tags: ["anhalteweg", "reaktionsweg", "bremsweg", "beladung"],
    text: "Welche Faktoren verlängern den Anhalteweg?",
    answers: [t("Ablenkung, Müdigkeit oder Alkohol, weil sie die Reaktionszeit und damit den Reaktionsweg verlängern"), t("Nässe, Glätte und abgefahrene Reifen, weil sie den Bremsweg verlängern"), t("Hohe Beladung und Gefälle, weil mehr Bewegungsenergie abgebaut werden muss"), f("Ein fast leerer Kraftstofftank", "Die geringe Masseänderung durch den Tankinhalt ist für den Anhalteweg unerheblich.")],
    explanation: "Der Anhalteweg setzt sich aus Reaktionsweg und Bremsweg zusammen. Der Reaktionsweg hängt vom Zustand des Fahrers ab, der Bremsweg von Geschwindigkeit, Fahrbahn, Reifen, Bremsanlage, Beladung und Gefälle. Nur wer alle Faktoren kennt, wählt eine angemessene Geschwindigkeit.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-fahrphysik-040", topic: "fahrphysik", points: 3, difficulty: 0.65, tags: ["anhalteweg", "gefahrenbremsung", "faustformel", "ausserorts"], kind: "numeric", numericAnswer: 80, tolerance: 0, unit: "m",
    text: "Wie lang ist der Anhalteweg bei 100 km/h nach den Faustformeln, wenn Sie eine Gefahrbremsung durchführen? Angabe in Metern.",
    answers: [],
    explanation: "Reaktionsweg = (100 / 10) × 3 = 30 Meter. Bremsweg bei Gefahrbremsung = (100 / 10)² / 2 = 50 Meter. Anhalteweg = 30 + 50 = 80 Meter. Gegenüber der normalen Bremsung mit 130 Metern spart die Gefahrbremsung 50 Meter, der Reaktionsweg bleibt aber gleich.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
];
