// Übungsfragen zum Thema "fahrmanoever" (eigene Formulierungen, kein amtlicher Prüfungsinhalt).
import type { Question } from "../types";
import { q, t, f } from "./_helpers";

export const fahrmanoever: readonly Question[] = [
  q({
    code: "own-fahrmanoever-001", topic: "fahrmanoever", points: 3, difficulty: 0.2, tags: ["rechtsabbiegen", "blinken", "schulterblick"],
    text: "Wie bereiten Sie das Rechtsabbiegen richtig vor?",
    answers: [t("Rechtzeitig blinken, möglichst weit rechts einordnen, Geschwindigkeit verringern und vor dem Abbiegen den Schulterblick nach rechts machen"), f("Erst abbiegen und dann blinken", "Der Blinker muss vorher gesetzt werden."), f("Zur Fahrbahnmitte hin einordnen, um eine weite Kurve fahren zu können", "Rechtsabbieger ordnen sich möglichst weit rechts ein.")],
    explanation: "Rechtsabbiegen bedeutet: Spiegel, blinken, rechts einordnen, langsam fahren, Schulterblick. So werden Radfahrende und zu Fuß Gehende im toten Winkel erkannt.",
    legalReference: "§ 9 Abs. 1 StVO",
  }),
  q({
    code: "own-fahrmanoever-002", topic: "fahrmanoever", points: 3, difficulty: 0.3, tags: ["linksabbiegen", "einordnen", "einbahnstrasse"],
    text: "Was gilt beim Linksabbiegen?",
    answers: [t("Bis zur Fahrbahnmitte einordnen, bei Fahrbahnen für eine Richtung möglichst weit links"), t("Der Gegenverkehr muss durchfahren gelassen werden"), f("Immer möglichst weit rechts einordnen", "Das gilt für Rechtsabbieger.")],
    explanation: "Linksabbieger ordnen sich zur Mitte hin ein, in Einbahnstraßen ganz links. Vor dem Abbiegen ist der Gegenverkehr durchzulassen, und der Schulterblick nach links ist Pflicht.",
    legalReference: "§ 9 Abs. 1 und 3 StVO",
  }),
  q({
    code: "own-fahrmanoever-003", topic: "fahrmanoever", points: 3, difficulty: 0.5, tags: ["linksabbiegen", "gegenverkehr", "kreuzung"],
    text: "Sie und ein entgegenkommendes Fahrzeug wollen beide an derselben Kreuzung links abbiegen. Wie biegen Sie ab?",
    answers: [t("Voreinander, sofern Markierungen oder die Verkehrsführung nichts anderes verlangen"), f("Grundsätzlich hintereinander", "Die Regel ist voreinander; nur bei entsprechender Verkehrsführung wird hintereinander abgebogen."), f("Wer zuerst blinkt, biegt zuerst ab", "Die Reihenfolge des Blinkens spielt keine Rolle.")],
    explanation: "Entgegenkommende Linksabbieger biegen voreinander ab, es sei denn, Markierungen oder die Verkehrslage sehen ein Abbiegen hintereinander vor.",
    legalReference: "§ 9 Abs. 4 StVO",
  }),
  q({
    code: "own-fahrmanoever-004", topic: "fahrmanoever", points: 3, difficulty: 0.3, tags: ["ueberholen", "gegenverkehr"],
    text: "Unter welchen Voraussetzungen dürfen Sie überholen?",
    answers: [t("Wenn Gegenverkehr während des gesamten Überholvorgangs ausgeschlossen ist"), t("Wenn Sie mit wesentlich höherer Geschwindigkeit als der Überholte fahren können"), t("Wenn niemand behindert oder gefährdet wird"), f("Innerorts nur nach vorherigem Hupen", "Hupen ist innerorts zum Ankündigen des Überholens nicht erlaubt.")],
    explanation: "Überholt werden darf nur, wenn die Übersicht reicht, Gegenverkehr ausgeschlossen ist, eine deutlich höhere Geschwindigkeit möglich ist und niemand gefährdet wird. Der Überholvorgang muss zügig abgeschlossen werden.",
    legalReference: "§ 5 Abs. 2 StVO",
  }),
  q({
    code: "own-fahrmanoever-005", topic: "fahrmanoever", points: 3, difficulty: 0.3, tags: ["ueberholverbot", "ueberholen", "fussgaengerueberweg"],
    text: "Wo ist das Überholen verboten?",
    answers: [t("An unübersichtlichen Stellen wie Kuppen und Kurven"), t("An Fußgängerüberwegen"), t("Wo es durch Zeichen 276 oder eine durchgezogene Linie ausgeschlossen ist"), f("Grundsätzlich auf Autobahnen", "Auf Autobahnen ist Überholen erlaubt.")],
    explanation: "Überholverbote gelten bei unklarer Verkehrslage, an unübersichtlichen Stellen, an Fußgängerüberwegen, an Bahnübergängen und überall dort, wo Zeichen oder Markierungen es verbieten.",
    legalReference: "§ 5 Abs. 3 StVO; § 26 Abs. 3 StVO",
  }),
  q({
    code: "own-fahrmanoever-006", topic: "fahrmanoever", points: 3, difficulty: 0.2, tags: ["fahrstreifenwechsel", "blinken", "schulterblick"],
    text: "Wie führen Sie einen Fahrstreifenwechsel richtig durch?",
    answers: [t("Innen- und Außenspiegel prüfen, rechtzeitig blinken, Schulterblick machen und nur wechseln, wenn niemand gefährdet wird"), f("Blinken genügt, der nachfolgende Verkehr muss dann Platz machen", "Blinken gibt kein Vorrecht; die Gefährdung anderer muss ausgeschlossen sein."), f("Erst wechseln und dann blinken", "Der Blinker gehört vor den Wechsel.")],
    explanation: "Beim Fahrstreifenwechsel muss jede Gefährdung anderer ausgeschlossen sein. Reihenfolge: Spiegel, Blinker, Schulterblick, dann wechseln.",
    legalReference: "§ 7 Abs. 5 StVO",
  }),
  q({
    code: "own-fahrmanoever-007", topic: "fahrmanoever", points: 3, difficulty: 0.4, tags: ["wenden", "autobahn", "einbahnstrasse"],
    text: "Wo ist das Wenden verboten?",
    answers: [t("Auf Autobahnen"), t("Auf Kraftfahrstraßen"), t("In Einbahnstraßen"), f("In Sackgassen", "In Sackgassen muss man in der Regel wenden; verboten ist es dort nicht.")],
    explanation: "Wenden ist auf Autobahnen und Kraftfahrstraßen verboten. In Einbahnstraßen ist es ebenfalls unzulässig, weil man anschließend gegen die Fahrtrichtung fahren würde.",
    legalReference: "§ 18 Abs. 7 StVO; § 9 Abs. 5 StVO",
  }),
  q({
    code: "own-fahrmanoever-008", topic: "fahrmanoever", points: 2, difficulty: 0.2, tags: ["rueckwaertsfahren", "einweiser"],
    text: "Was ist beim Rückwärtsfahren zu beachten?",
    answers: [t("Nur langsam fahren, Gefährdung anderer ausschließen und sich nötigenfalls einweisen lassen"), f("Rückwärtsfahren ist auf allen Straßen ohne Einschränkung erlaubt", "Auf Autobahnen und Kraftfahrstraßen ist es verboten, und immer muss eine Gefährdung ausgeschlossen sein."), f("Andere Verkehrsteilnehmer müssen dem rückwärtsfahrenden Fahrzeug Platz machen", "Wer rückwärtsfährt, hat keinen Vorrang.")],
    explanation: "Beim Rückwärtsfahren ist die Sicht eingeschränkt. Deshalb nur mit Schrittgeschwindigkeit fahren, notfalls einweisen lassen und jede Gefährdung ausschließen.",
    legalReference: "§ 9 Abs. 5 StVO",
  }),
  q({
    code: "own-fahrmanoever-009", topic: "fahrmanoever", points: 4, difficulty: 0.4, tags: ["hindernis", "gegenverkehr", "vorbeifahren"],
    text: "Auf Ihrer Fahrbahnseite steht ein parkendes Fahrzeug, das Sie nur über die Gegenfahrbahn umfahren können. Gegenverkehr nähert sich. Wer muss warten?",
    answers: [t("Sie, denn wer an einem Hindernis auf seiner Seite vorbeifahren will, muss den Gegenverkehr durchfahren lassen"), f("Der Gegenverkehr, weil Sie zuerst da waren", "Das Hindernis befindet sich auf Ihrer Seite, also müssen Sie warten."), f("Wer schneller ist", "Geschwindigkeit begründet keinen Vorrang.")],
    explanation: "Wer an einem Hindernis auf seiner Fahrbahnseite vorbeifahren will, muss entgegenkommende Fahrzeuge durchfahren lassen und gegebenenfalls warten.",
    legalReference: "§ 6 StVO",
  }),
  q({
    code: "own-fahrmanoever-010", topic: "fahrmanoever", points: 3, difficulty: 0.5, tags: ["rechts_ueberholen", "innerorts", "fahrstreifen"],
    text: "Sie fahren innerorts auf einer Straße mit zwei markierten Fahrstreifen je Richtung. Dürfen Sie mit dem Pkw rechts schneller fahren als die Fahrzeuge links?",
    answers: [t("Ja, innerorts dürfen Kraftfahrzeuge bis 3,5 t bei mehreren Fahrstreifen für eine Richtung rechts schneller fahren als links"), f("Nein, rechts überholen ist immer verboten", "Innerorts gilt bei mehreren Fahrstreifen eine Ausnahme."), f("Nur wenn links ein Lkw fährt", "Die Ausnahme ist nicht auf bestimmte Fahrzeuge links beschränkt.")],
    explanation: "Innerhalb geschlossener Ortschaften dürfen Kraftfahrzeuge bis 3,5 t auf Fahrbahnen mit mehreren markierten Fahrstreifen für eine Richtung den Fahrstreifen frei wählen und rechts schneller fahren als links.",
    legalReference: "§ 7 Abs. 3 StVO",
  }),
  q({
    code: "own-fahrmanoever-011", topic: "fahrmanoever", points: 3, difficulty: 0.4, tags: ["strassenbahn", "ueberholen"],
    text: "Auf welcher Seite überholen Sie eine Straßenbahn?",
    answers: [t("Grundsätzlich rechts; links nur, wenn die Schienen so weit rechts liegen, dass rechts kein Platz ist, oder in Einbahnstraßen"), f("Grundsätzlich links wie bei allen Fahrzeugen", "Straßenbahnen bilden eine Ausnahme von der Linksüberholregel."), f("Straßenbahnen dürfen nie überholt werden", "Sie dürfen überholt werden, wenn es sicher ist.")],
    explanation: "Schienenfahrzeuge werden rechts überholt. Liegen die Schienen zu weit rechts oder handelt es sich um eine Einbahnstraße, darf links überholt werden.",
    legalReference: "§ 5 Abs. 7 StVO",
  }),
  q({
    code: "own-fahrmanoever-012", topic: "fahrmanoever", points: 3, difficulty: 0.65, tags: ["linksabbiegen", "einbahnstrasse", "einordnen", "rechts_ueberholen"],
    text: "Sie wollen in einer Einbahnstraße links abbiegen. Wie ordnen Sie sich ein und was gilt für den Verkehr hinter Ihnen?",
    answers: [t("Möglichst weit links, weil in Einbahnstraßen kein Gegenverkehr kommt"), t("Nachfolgende Fahrzeuge dürfen rechts an Ihnen vorbeifahren, wenn Sie sich als Linksabbieger eingeordnet haben"), f("In der Fahrbahnmitte wie auf jeder anderen Straße", "In Einbahnstraßen wird ganz links eingeordnet."), f("Nachfolgende Fahrzeuge müssen hinter Ihnen warten, weil rechts überholen verboten ist", "An eingeordneten Linksabbiegern darf rechts vorbeigefahren werden.")],
    explanation: "In Einbahnstraßen ordnen sich Linksabbieger möglichst weit links ein. Wer sich zum Linksabbiegen eingeordnet und das angekündigt hat, darf rechts überholt werden.",
    legalReference: "§ 9 Abs. 1 StVO; § 5 Abs. 7 StVO",
  }),
  q({
    code: "own-fahrmanoever-013", topic: "fahrmanoever", points: 3, difficulty: 0.6, tags: ["ueberholen", "ankuendigen", "lichthupe", "ausserorts", "innerorts"],
    text: "Dürfen Sie einen Überholvorgang mit der Lichthupe oder der Hupe ankündigen?",
    answers: [t("Außerorts ja, mit kurzen Schall- oder Leuchtzeichen"), t("Innerorts nur mit dem Blinker; Hupe und Lichthupe sind dort zum Ankündigen nicht erlaubt"), f("Innerorts und außerorts immer mit der Hupe", "Innerorts ist die Hupe nur bei Gefahr zulässig."), f("Nie, Lichthupe ist grundsätzlich Nötigung", "Außerorts ist die kurze Lichthupe zum Ankündigen ausdrücklich erlaubt; nur dauerhaftes Blenden und Drängeln sind unzulässig.")],
    explanation: "Außerhalb geschlossener Ortschaften darf das Überholen durch kurze Schall- oder Leuchtzeichen angekündigt werden. Innerorts sind Hupe und Lichthupe nur als Warnung bei Gefahr erlaubt; das Überholen wird dort allein mit dem Blinker angekündigt.",
    legalReference: "§ 5 Abs. 5 StVO; § 16 Abs. 1 StVO",
  }),
  q({
    code: "own-fahrmanoever-014", topic: "fahrmanoever", points: 3, difficulty: 0.6, tags: ["ueberholen", "ueberholt_werden", "rechtsfahren"],
    text: "Ein Fahrzeug setzt zum Überholen an und fährt neben Ihnen. Was müssen Sie als Überholter tun?",
    answers: [t("Die Geschwindigkeit nicht erhöhen"), t("Möglichst weit rechts fahren, um das Überholen zu erleichtern"), f("Beschleunigen, damit der Überholvorgang schneller vorbei ist", "Wer überholt wird, darf die Geschwindigkeit nicht erhöhen."), f("Abrupt bremsen, damit der Überholer schneller wieder einscheren kann", "Starkes Bremsen ohne Grund ist verboten und gefährdet den Nachfolgenden.")],
    explanation: "Wer überholt wird, darf seine Geschwindigkeit nicht erhöhen und muss rechts fahren. So bleibt der Überholweg kurz und der Überholende kann sicher wieder einscheren.",
    legalReference: "§ 5 Abs. 6 StVO",
  }),
  q({
    code: "own-fahrmanoever-015", topic: "fahrmanoever", points: 3, difficulty: 0.6, tags: ["ueberholen", "wiedereinscheren", "abstand", "blinken"],
    text: "Wann dürfen Sie nach dem Überholen wieder nach rechts einscheren?",
    answers: [t("Erst wenn Sie das überholte Fahrzeug vollständig im Innenspiegel sehen und es dadurch nicht behindert wird"), t("Das Einscheren ist rechtzeitig durch Blinken nach rechts anzukündigen"), f("Sobald Ihr Fahrzeug knapp vor dem überholten Fahrzeug ist, um den Überholvorgang zu verkürzen", "Zu frühes Einscheren schneidet den Überholten und ist verboten."), f("Erst nach mindestens 100 Metern", "Es gibt keine feste Strecke; maßgeblich ist der ausreichende Abstand.")],
    explanation: "Nach dem Überholen wird rechts geblinkt und erst dann eingeschert, wenn das überholte Fahrzeug nicht behindert wird. Als Faustregel gilt: Es muss vollständig im Innenspiegel sichtbar sein.",
    legalReference: "§ 5 Abs. 4 und 4a StVO",
  }),
  q({
    code: "own-fahrmanoever-016", topic: "fahrmanoever", points: 3, difficulty: 0.65, tags: ["ueberholverbot", "unklare_verkehrslage", "ueberholen"],
    text: "In welchen Situationen liegt eine unklare Verkehrslage vor, bei der nicht überholt werden darf?",
    answers: [t("Der Vorausfahrende fährt ohne erkennbaren Grund langsamer und fährt zur Fahrbahnmitte"), t("Der Vorausfahrende blinkt links"), f("Der Vorausfahrende fährt gleichmäßig weit rechts", "Das ist eine klare Lage; Überholen ist möglich, wenn die übrigen Voraussetzungen vorliegen."), f("Auf der Gegenfahrbahn ist in weiter Entfernung ein Fahrzeug zu sehen", "Das betrifft die Frage, ob Gegenverkehr ausgeschlossen ist, nicht die Unklarheit der Lage.")],
    explanation: "Unklar ist die Verkehrslage, wenn nicht abzusehen ist, was der Vorausfahrende tun wird, etwa bei Linksblinken, grundlosem Verlangsamen oder Einordnen zur Mitte. Dann ist das Überholen verboten.",
    legalReference: "§ 5 Abs. 3 Nr. 1 StVO",
  }),
  q({
    code: "own-fahrmanoever-017", topic: "fahrmanoever", points: 3, difficulty: 0.65, tags: ["ueberholverbot", "bahnuebergang", "ueberholen", "andreaskreuz"],
    text: "Vor einem Bahnübergang mit Andreaskreuz fährt ein langsamer Traktor. Dürfen Sie ihn dort überholen?",
    answers: [t("Nein, zwischen dem Gefahrzeichen Bahnübergang und dem Übergang selbst ist das Überholen mehrspuriger Kraftfahrzeuge verboten"), f("Ja, wenn kein Zug kommt", "Das Überholverbot vor Bahnübergängen gilt unabhängig vom Zugverkehr."), f("Ja, weil der Traktor langsamer als 25 km/h fährt", "Das Überholverbot gilt für alle Kraftfahrzeuge; Ausnahmen für langsame Fahrzeuge gibt es dort nicht.")],
    explanation: "Vor Bahnübergängen darf ab dem Gefahrzeichen Bahnübergang bis zum Übergang nicht überholt werden. Der Traktor muss hinter dem Übergang überholt werden, wenn es dann sicher ist.",
    legalReference: "§ 19 Abs. 1 StVO",
  }),
  q({
    code: "own-fahrmanoever-018", topic: "fahrmanoever", points: 3, difficulty: 0.55, tags: ["ueberholen", "durchgezogene_linie", "markierung"],
    text: "Die Fahrbahnmitte ist mit einer einseitigen Fahrstreifenbegrenzung markiert: Auf Ihrer Seite ist die Linie gestrichelt, auf der Gegenseite durchgezogen. Dürfen Sie überholen?",
    answers: [t("Ja, wenn die übrigen Voraussetzungen für das Überholen erfüllt sind; die durchgezogene Linie gilt für den Gegenverkehr"), f("Nein, die durchgezogene Linie verbietet das Überholen für beide Richtungen", "Bei einseitiger Begrenzung gilt die durchgezogene Linie nur für die Seite, auf der sie liegt."), f("Nur wenn kein Fahrzeug auf der Gegenfahrbahn fährt, weil dieses die Linie nicht überfahren darf", "Gegenverkehr muss beim Überholen immer ausgeschlossen sein; das ist keine Besonderheit dieser Markierung.")],
    explanation: "Bei einer einseitigen Fahrstreifenbegrenzung gilt die durchgezogene Linie nur für den Verkehr, auf dessen Seite sie liegt. Wer die gestrichelte Linie auf seiner Seite hat, darf sie zum Überholen überfahren, wenn es sicher ist.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 296)",
  }),
  q({
    code: "own-fahrmanoever-019", topic: "fahrmanoever", points: 3, difficulty: 0.6, tags: ["ueberholverbot", "verkehrszeichen", "zusatzzeichen", "lkw"],
    text: "Auf einer Landstraße steht das Zeichen 277 (Überholverbot für Kraftfahrzeuge über 3,5 t). Was gilt für Ihren Pkw?",
    answers: [t("Sie dürfen weiterhin überholen, wenn die allgemeinen Voraussetzungen erfüllt sind"), t("Sie müssen damit rechnen, dass Lkw hinter langsamen Fahrzeugen bleiben und Kolonnen bilden"), f("Auch Sie dürfen nicht überholen", "Das Zeichen richtet sich nur an Kraftfahrzeuge über 3,5 t."), f("Sie dürfen nur Lkw überholen", "Das Zeichen schränkt Pkw nicht ein.")],
    explanation: "Zeichen 277 verbietet nur Kraftfahrzeugen über 3,5 t das Überholen. Für Pkw gelten die allgemeinen Regeln. Weil Lkw nicht überholen dürfen, entstehen oft Kolonnen, deren Überholen gut geplant sein muss.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 277)",
  }),
  q({
    code: "own-fahrmanoever-020", topic: "fahrmanoever", points: 3, difficulty: 0.7, tags: ["ueberholen", "kolonne", "ausserorts", "gegenverkehr"],
    text: "Auf der Landstraße wollen Sie eine Kolonne aus drei Lkw überholen. Worauf müssen Sie achten?",
    answers: [t("Der Überholweg ist sehr lang; die übersehbare Strecke muss für den gesamten Vorgang ausreichen und Gegenverkehr ausgeschlossen sein"), t("Zwischen den Lkw müssen Lücken zum Einscheren vorhanden sein, falls Sie abbrechen müssen"), f("Die Lkw müssen anhalten, damit Sie überholen können", "Eine solche Pflicht gibt es nicht."), f("Sie dürfen bei Gegenverkehr überholen, wenn dieser ausweichen kann", "Gegenverkehr muss während des gesamten Überholvorgangs ausgeschlossen sein.")],
    explanation: "Beim Überholen einer Kolonne wird die benötigte Strecke oft unterschätzt. Überholt werden darf nur, wenn Sicht und Strecke für den gesamten Vorgang reichen und notfalls ein Einscheren in eine Lücke möglich ist.",
    legalReference: "§ 5 Abs. 2 StVO",
  }),
  q({
    code: "own-fahrmanoever-021", topic: "fahrmanoever", points: 3, difficulty: 0.6, tags: ["rechts_ueberholen", "linksabbieger", "vorbeifahren"],
    text: "Vor Ihnen hat sich ein Fahrzeug zum Linksabbiegen eingeordnet und blinkt links. Dürfen Sie rechts an ihm vorbeifahren?",
    answers: [t("Ja, wenn rechts genug Platz ist und niemand gefährdet wird, insbesondere keine Radfahrenden oder Fußgänger"), f("Nein, rechts überholen ist immer verboten", "An eingeordneten Linksabbiegern darf rechts vorbeigefahren werden."), f("Nur, wenn der Linksabbieger steht", "Das Vorbeifahren ist auch erlaubt, wenn er langsam fährt und eingeordnet ist.")],
    explanation: "Wer sich zum Linksabbiegen eingeordnet und das angekündigt hat, darf rechts überholt werden. Dabei ist besonders auf Radfahrende und Fußgänger rechts zu achten.",
    legalReference: "§ 5 Abs. 7 StVO",
  }),
  q({
    code: "own-fahrmanoever-022", topic: "fahrmanoever", points: 3, difficulty: 0.6, tags: ["wenden", "kreuzung", "verbot_des_wendens", "verkehrszeichen"],
    text: "Sie wollen an einer Kreuzung mit Ampel wenden. Was gilt?",
    answers: [t("Wenden ist erlaubt, wenn kein Zeichen 272 es verbietet und niemand gefährdet oder behindert wird"), t("Sie müssen sich wie ein Linksabbieger verhalten, blinken und dem Gegenverkehr Vorrang lassen"), f("Wenden an Ampelkreuzungen ist grundsätzlich verboten", "Ein allgemeines Verbot gibt es nicht; nur Zeichen 272 oder die Verkehrsführung verbieten es."), f("Sie haben beim Wenden Vorrang vor dem Gegenverkehr", "Wer wendet, muss jede Gefährdung ausschließen und hat keinen Vorrang.")],
    explanation: "Wenden ist überall dort erlaubt, wo es nicht durch Zeichen 272 oder die Verkehrsführung ausgeschlossen ist und niemand gefährdet oder behindert wird. An Kreuzungen gelten die Pflichten des Linksabbiegers.",
    legalReference: "§ 9 Abs. 5 StVO; Zeichen 272",
  }),
  q({
    code: "own-fahrmanoever-023", topic: "fahrmanoever", points: 3, difficulty: 0.55, tags: ["wenden", "innerorts", "sicherheit"],
    text: "Sie wollen in einer Wohnstraße mit geringem Verkehr wenden. Welche Möglichkeiten sind sicher und erlaubt?",
    answers: [t("Über eine Grundstückseinfahrt rückwärts hineinsetzen und vorwärts herausfahren, wenn niemand behindert wird"), t("Um den nächsten Block fahren"), f("Rückwärts aus der Nebenstraße in die Hauptstraße einbiegen", "Rückwärts in eine Vorfahrtstraße einzubiegen ist besonders gefährlich."), f("Direkt vor einer unübersichtlichen Kurve wenden", "An unübersichtlichen Stellen ist Wenden verboten.")],
    explanation: "Beim Wenden muss jede Gefährdung anderer ausgeschlossen sein. Sicher ist es, eine Einfahrt zu nutzen oder um den Block zu fahren. An unübersichtlichen Stellen und rückwärts in Vorfahrtstraßen ist es gefährlich und unzulässig.",
    legalReference: "§ 9 Abs. 5 StVO",
  }),
  q({
    code: "own-fahrmanoever-024", topic: "fahrmanoever", points: 3, difficulty: 0.6, tags: ["anfahren", "fahrbahnrand", "blinken", "vorrang"],
    text: "Sie wollen vom Fahrbahnrand anfahren. Was müssen Sie beachten?",
    answers: [t("Rechtzeitig blinken, Spiegel und Schulterblick nutzen und nur anfahren, wenn niemand gefährdet wird"), t("Der fließende Verkehr hat Vorrang; Sie dürfen ihn nicht zum Bremsen zwingen"), f("Nach dem Blinken haben Sie Vorrang und dürfen sofort anfahren", "Blinken begründet keinen Vorrang."), f("Ein Schulterblick ist beim Anfahren nicht nötig, weil die Spiegel ausreichen", "Radfahrende und Motorräder im toten Winkel werden nur durch den Schulterblick erkannt.")],
    explanation: "Wer vom Fahrbahnrand anfährt, muss jede Gefährdung anderer ausschließen und das Anfahren rechtzeitig anzeigen. Der fließende Verkehr hat Vorrang.",
    legalReference: "§ 10 StVO",
  }),
  q({
    code: "own-fahrmanoever-025", topic: "fahrmanoever", points: 3, difficulty: 0.65, tags: ["rechtsabbiegen", "strassenbahn", "schienenfahrzeuge", "innerorts"],
    text: "Sie wollen rechts abbiegen. Rechts neben Ihnen verlaufen Straßenbahnschienen, und eine Straßenbahn fährt in gleicher Richtung geradeaus. Was gilt?",
    answers: [t("Sie müssen die Straßenbahn durchfahren lassen, bevor Sie abbiegen"), f("Die Straßenbahn muss warten, weil Sie den Blinker gesetzt haben", "Schienenfahrzeuge, die in gleicher Richtung fahren, sind beim Abbiegen durchzulassen."), f("Sie dürfen vor der Straßenbahn abbiegen, weil sie langsam ist", "Straßenbahnen haben lange Bremswege; das Kreuzen vor ihnen ist gefährlich und verboten.")],
    explanation: "Beim Abbiegen müssen Schienenfahrzeuge, die in gleicher Richtung fahren oder entgegenkommen, durchfahren gelassen werden. Das gilt für Rechtsabbieger mit Schienen rechts ebenso wie für Linksabbieger.",
    legalReference: "§ 9 Abs. 3 StVO",
  }),
  q({
    code: "own-fahrmanoever-026", topic: "fahrmanoever", points: 3, difficulty: 0.6, tags: ["rechtsabbiegen", "fussgaenger", "abbiegen", "vorrang"],
    text: "Sie biegen an einer Kreuzung ohne Ampel rechts ab. Ein Fußgänger überquert die Straße, in die Sie einbiegen, ohne Zebrastreifen. Was gilt?",
    answers: [t("Sie müssen den Fußgänger durchgehen lassen, weil Abbieger auf Fußgänger, die die Fahrbahn der Zielstraße überqueren, besondere Rücksicht nehmen müssen"), f("Der Fußgänger muss warten, weil ohne Zebrastreifen Fahrzeuge Vorrang haben", "Beim Abbiegen sind querende Fußgänger durchzulassen, auch ohne Zebrastreifen."), f("Sie dürfen hupen, damit der Fußgänger stehen bleibt", "Hupen ist hier unzulässig.")],
    explanation: "Wer abbiegt, muss auf zu Fuß Gehende besondere Rücksicht nehmen und sie, wenn nötig, durchgehen lassen. Das gilt beim Abbiegen unabhängig davon, ob ein Fußgängerüberweg vorhanden ist.",
    legalReference: "§ 9 Abs. 3 StVO",
  }),
  q({
    code: "own-fahrmanoever-027", topic: "fahrmanoever", points: 3, difficulty: 0.65, tags: ["fahrstreifenwechsel", "autobahn", "einscheren", "abstand"],
    text: "Auf der Autobahn wollen Sie vom rechten auf den linken Fahrstreifen wechseln, um einen Lkw zu überholen. Von hinten nähert sich auf dem linken Streifen schnell ein Pkw. Was ist richtig?",
    answers: [t("Sie dürfen nur wechseln, wenn der Pkw dadurch nicht zum starken Bremsen gezwungen wird; im Zweifel warten Sie hinter dem Lkw"), t("Vor dem Wechsel: Innenspiegel, Außenspiegel, Blinker, Schulterblick"), f("Sie dürfen wechseln, sobald Sie blinken; der Pkw muss dann bremsen", "Der Fahrstreifenwechsel darf andere nicht gefährden; Blinken gibt kein Vorrecht."), f("Der Pkw muss Ihnen Platz machen, weil Sie den Lkw überholen wollen", "Wer den Fahrstreifen wechselt, muss sich einordnen, ohne andere zu behindern.")],
    explanation: "Beim Fahrstreifenwechsel muss eine Gefährdung anderer ausgeschlossen sein. Auf der Autobahn nähern sich Fahrzeuge oft mit hoher Geschwindigkeitsdifferenz; ihre Entfernung wird leicht unterschätzt. Im Zweifel abwarten.",
    legalReference: "§ 7 Abs. 5 StVO",
  }),
  q({
    code: "own-fahrmanoever-028", topic: "fahrmanoever", points: 3, difficulty: 0.55, tags: ["vorbeifahren", "parkende_fahrzeuge", "abstand", "innerorts"],
    text: "Sie fahren innerorts an einer Reihe parkender Autos vorbei. Welchen Seitenabstand halten Sie und warum?",
    answers: [t("Etwa eine Türbreite, weil Türen plötzlich geöffnet werden können und Personen zwischen den Fahrzeugen hervortreten können"), f("So wenig wie möglich, damit der Gegenverkehr Platz hat", "Ein zu geringer Abstand führt zu Unfällen mit sich öffnenden Türen."), f("Der Abstand ist unerheblich, weil Aussteigende sich vergewissern müssen", "Aussteigende müssen zwar aufpassen, aber Sie müssen mit ihren Fehlern rechnen.")],
    explanation: "Beim Vorbeifahren an parkenden Fahrzeugen ist ein ausreichender Seitenabstand, etwa eine geöffnete Türbreite, einzuhalten. Damit werden sich öffnende Türen und hervortretende Personen berücksichtigt.",
    legalReference: "§ 1 StVO; § 6 StVO",
  }),
  q({
    code: "own-fahrmanoever-029", topic: "fahrmanoever", points: 3, difficulty: 0.6, tags: ["hindernis", "gegenverkehr", "vorbeifahren", "baustelle"],
    text: "Eine Baustelle blockiert die Gegenfahrbahn. Ein entgegenkommendes Fahrzeug muss auf Ihre Seite ausweichen. Wer muss warten?",
    answers: [t("Das entgegenkommende Fahrzeug, weil sich das Hindernis auf seiner Fahrbahnseite befindet"), t("Sind Verkehrszeichen 208 und 308 aufgestellt, gelten diese"), f("Sie, weil Baustellenverkehr immer Vorrang hat", "Wer an einem Hindernis auf seiner Seite vorbeifahren will, muss warten."), f("Wer zuerst da ist", "Die Ankunftsreihenfolge ist unerheblich.")],
    explanation: "Wer an einem Hindernis auf seiner Fahrbahnseite vorbeifahren muss, hat den Gegenverkehr durchfahren zu lassen. Nur wenn Zeichen 208 und 308 etwas anderes anordnen, gilt deren Regelung.",
    legalReference: "§ 6 StVO; Zeichen 208 und 308",
  }),
  q({
    code: "own-fahrmanoever-030", topic: "fahrmanoever", points: 3, difficulty: 0.6, tags: ["rueckwaertsfahren", "einparken", "einweiser", "sicherheit"],
    text: "Sie wollen rückwärts in eine Parklücke einparken, in der Nähe spielen Kinder. Was ist richtig?",
    answers: [t("Vor dem Rückwärtsfahren nach hinten schauen und sich bei fehlender Sicht einweisen lassen"), t("Nur mit Schrittgeschwindigkeit und bremsbereit rückwärtsfahren"), f("Rückfahrkamera und Parksensoren machen den Blick nach hinten überflüssig", "Assistenzsysteme unterstützen, ersetzen aber nicht die eigene Verkehrsbeobachtung."), f("Kinder müssen dem rückwärtsfahrenden Fahrzeug ausweichen", "Der Fahrer muss jede Gefährdung ausschließen.")],
    explanation: "Beim Rückwärtsfahren ist die Sicht eingeschränkt; kleine Kinder sind hinter dem Fahrzeug oft nicht zu sehen. Deshalb langsam, mit Blick nach hinten und notfalls mit Einweiser fahren.",
    legalReference: "§ 9 Abs. 5 StVO",
  }),
  q({
    code: "own-fahrmanoever-031", topic: "fahrmanoever", points: 3, difficulty: 0.65, tags: ["linksabbiegen", "schulterblick", "ueberholt_werden", "innerorts"],
    text: "Sie wollen innerorts links in eine Einfahrt abbiegen und haben geblinkt. Warum ist der Schulterblick nach links unmittelbar vor dem Abbiegen so wichtig?",
    answers: [t("Ein Motorrad oder Pkw könnte trotz Ihres Blinkers bereits zum Überholen angesetzt haben"), t("Radfahrende auf einem linksseitigen Radweg oder Fußgänger könnten sich neben Ihnen befinden"), f("Der Schulterblick ist nur beim Rechtsabbiegen erforderlich", "Auch beim Linksabbiegen ist der Schulterblick Pflicht."), f("Der Schulterblick ersetzt den Blinker", "Blinken und Schulterblick sind beide nötig.")],
    explanation: "Vor dem Linksabbiegen muss auf den nachfolgenden Verkehr geachtet werden: Ein Überholer könnte trotz Blinkers bereits neben Ihnen sein. Der Schulterblick deckt den Bereich ab, den die Spiegel nicht zeigen.",
    legalReference: "§ 9 Abs. 1 StVO",
  }),
  q({
    code: "own-fahrmanoever-032", topic: "fahrmanoever", points: 3, difficulty: 0.6, tags: ["ueberholen", "nebel", "sichtweite", "ausserorts"],
    text: "Bei dichtem Nebel fahren Sie auf der Landstraße hinter einem langsamen Lkw. Dürfen Sie überholen?",
    answers: [t("Nein, wenn die übersehbare Strecke nicht ausreicht, um Gegenverkehr für den gesamten Überholvorgang auszuschließen"), f("Ja, wenn Sie schnell genug beschleunigen", "Die eigene Beschleunigung ersetzt nicht die fehlende Sicht."), f("Ja, mit eingeschaltetem Fernlicht", "Fernlicht verschlechtert bei Nebel die Sicht und ändert nichts an der fehlenden Übersicht.")],
    explanation: "Überholt werden darf nur, wenn übersehbar ist, dass während des gesamten Vorgangs jede Behinderung des Gegenverkehrs ausgeschlossen ist. Bei Nebel fehlt diese Übersicht meist völlig.",
    legalReference: "§ 5 Abs. 2 StVO",
  }),
  q({
    code: "own-fahrmanoever-033", topic: "fahrmanoever", points: 2, difficulty: 0.5, tags: ["ueberholen", "fussgaenger", "ueberholabstand", "ausserorts"], kind: "numeric", numericAnswer: 2, tolerance: 0, unit: "m",
    text: "Welchen seitlichen Mindestabstand müssen Sie außerorts beim Überholen von Fußgängern, Radfahrenden und E-Scooter-Fahrern einhalten? Angabe in Metern.",
    answers: [],
    explanation: "Außerorts beträgt der seitliche Mindestabstand beim Überholen von zu Fuß Gehenden, Radfahrenden und Elektrokleinstfahrzeugen 2 m, innerorts 1,5 m. Kann er nicht eingehalten werden, darf nicht überholt werden.",
    legalReference: "§ 5 Abs. 4 StVO",
  }),
  q({
    code: "own-fahrmanoever-034", topic: "fahrmanoever", points: 3, difficulty: 0.6, tags: ["abbiegen", "blinken", "rechtzeitig", "fahrtrichtungsanzeiger"],
    text: "Wann und wie lange müssen Sie vor dem Abbiegen blinken?",
    answers: [t("Rechtzeitig und deutlich vor dem Abbiegen, sodass andere sich darauf einstellen können, und bis der Abbiegevorgang abgeschlossen ist"), f("Erst beim Einlenken, damit niemand verwirrt wird", "Zu spätes Blinken nimmt anderen die Möglichkeit zu reagieren."), f("Nur wenn andere Verkehrsteilnehmer in der Nähe sind", "Die Blinkpflicht gilt immer, auch wenn scheinbar niemand da ist.")],
    explanation: "Die Absicht abzubiegen ist rechtzeitig und deutlich anzukündigen. Das Blinken ist keine Ermessensfrage, sondern gilt bei jedem Abbiegen, auch ohne erkennbaren anderen Verkehr.",
    legalReference: "§ 9 Abs. 1 StVO",
  }),
  q({
    code: "own-fahrmanoever-035", topic: "fahrmanoever", points: 3, difficulty: 0.6, tags: ["linksabbiegen", "gegenverkehr", "hintereinander", "markierung"],
    text: "An einer großen Kreuzung sind Abbiegespuren für Linksabbieger so markiert, dass entgegenkommende Linksabbieger hintereinander abbiegen müssen. Was gilt?",
    answers: [t("Sie folgen der Markierung und biegen hinter dem entgegenkommenden Linksabbieger ab"), f("Sie biegen trotzdem voreinander ab, weil das die Grundregel ist", "Die Grundregel gilt nur, wenn Markierungen oder die Verkehrsführung nichts anderes vorsehen."), f("Der Linksabbieger von rechts hat Vorrang", "Zwischen entgegenkommenden Linksabbiegern gibt es keinen Vorrang; es gilt die Verkehrsführung.")],
    explanation: "Entgegenkommende Linksabbieger biegen voreinander ab, es sei denn, Markierungen oder die Verkehrsführung sehen das Abbiegen hintereinander vor. Dann ist der Markierung zu folgen.",
    legalReference: "§ 9 Abs. 4 StVO",
  }),
  q({
    code: "own-fahrmanoever-036", topic: "fahrmanoever", points: 3, difficulty: 0.6, tags: ["ueberholen", "innerorts", "fahrstreifen", "rechts_ueberholen"],
    text: "Innerorts fahren Sie auf einer Straße mit zwei Fahrstreifen je Richtung auf dem rechten Streifen. Links neben Ihnen fährt ein Pkw langsamer. Dürfen Sie vorbeifahren?",
    answers: [t("Ja, innerorts dürfen Kraftfahrzeuge bis 3,5 t bei mehreren Fahrstreifen für eine Richtung rechts schneller fahren als links"), f("Nein, das wäre verbotenes Rechtsüberholen", "Innerorts gilt bei mehreren markierten Fahrstreifen eine Ausnahme."), f("Nur, wenn der linke Pkw blinkt", "Das Vorbeifahren ist unabhängig vom Blinker erlaubt.")],
    explanation: "Innerorts darf bei mehreren markierten Fahrstreifen für eine Richtung rechts schneller gefahren werden als links. Das ist kein verbotenes Rechtsüberholen.",
    legalReference: "§ 7 Abs. 3 StVO",
  }),
  q({
    code: "own-fahrmanoever-037", topic: "fahrmanoever", points: 3, difficulty: 0.7, tags: ["ueberholen", "ueberholweg", "geschwindigkeit", "ausserorts"],
    text: "Sie fahren mit 100 km/h und wollen einen Lkw mit 80 km/h überholen. Warum ist das Überholen mit dieser Geschwindigkeitsdifferenz problematisch?",
    answers: [t("Bei nur 20 km/h Differenz ist der Überholweg sehr lang, weil Sie sich nur langsam am Lkw vorbeischieben"), t("Überholt werden darf nur mit wesentlich höherer Geschwindigkeit; ist das wegen der Höchstgeschwindigkeit nicht möglich, sollte auf das Überholen verzichtet werden"), f("Das Überholen ist unproblematisch, weil 100 km/h die Höchstgeschwindigkeit ist", "Die zulässige Höchstgeschwindigkeit ändert nichts an der langen Überholstrecke."), f("Sie dürfen zum Überholen kurzzeitig 130 km/h fahren", "Die Höchstgeschwindigkeit gilt auch beim Überholen.")],
    explanation: "Je geringer die Geschwindigkeitsdifferenz, desto länger der Überholweg. Bei 20 km/h Differenz dauert das Überholen eines Lkw mehrere hundert Meter. Die Höchstgeschwindigkeit darf dabei nicht überschritten werden.",
    legalReference: "§ 5 Abs. 2 StVO; § 3 Abs. 3 StVO",
  }),
  q({
    code: "own-fahrmanoever-038", topic: "fahrmanoever", points: 3, difficulty: 0.55, tags: ["abbiegen", "grosse_fahrzeuge", "ausschwenken", "lkw"],
    text: "Ein Lkw mit Anhänger vor Ihnen blinkt rechts, fährt aber vor dem Abbiegen nach links aus. Wie verhalten Sie sich?",
    answers: [t("Abstand halten und nicht rechts vorbeifahren, weil der Lkw beim Abbiegen weit ausholt und der Anhänger die Kurve schneidet"), f("Rechts am Lkw vorbeifahren, weil er nach links fährt", "Der Lkw holt aus, um rechts abbiegen zu können; rechts neben ihm droht der Zusammenstoß."), f("Hupen, damit der Lkw seinen Fehler korrigiert", "Das Ausholen ist kein Fehler, sondern nötig.")],
    explanation: "Lange Fahrzeuge müssen vor engen Rechtskurven nach links ausholen, damit der Anhänger die Kurve schafft. Wer in diesem Moment rechts vorbeifahren will, wird eingeklemmt.",
    legalReference: "§ 1 StVO; § 5 Abs. 3 Nr. 1 StVO",
  }),
  q({
    code: "own-fahrmanoever-039", topic: "fahrmanoever", points: 3, difficulty: 0.6, tags: ["fahrstreifenwechsel", "reissverschluss", "einordnen", "innerorts"],
    text: "Innerorts endet Ihr Fahrstreifen. Sie ordnen sich im Reißverschlussverfahren ein. Wer hat Vorrang?",
    answers: [t("Die Fahrzeuge auf dem durchgehenden Fahrstreifen; sie müssen aber das Einfädeln unmittelbar an der Engstelle abwechselnd ermöglichen"), f("Sie, weil Sie den Blinker gesetzt haben", "Blinken begründet keinen Vorrang."), f("Niemand, es fahren einfach alle gleichzeitig", "Das Reißverschlussverfahren regelt den Wechsel: erst ein Fahrzeug des durchgehenden Streifens, dann eines des endenden.")],
    explanation: "Beim Fahrstreifenwechsel muss der Wechselnde jede Gefährdung ausschließen. Beim Reißverschlussverfahren sind die Fahrzeuge des durchgehenden Fahrstreifens verpflichtet, das abwechselnde Einfädeln an der Engstelle zu ermöglichen.",
    legalReference: "§ 7 Abs. 4 und 5 StVO",
  }),
  q({
    code: "own-fahrmanoever-040", topic: "fahrmanoever", points: 3, difficulty: 0.55, tags: ["ueberholen", "abbrechen", "gegenverkehr", "notsituation"],
    text: "Während des Überholens auf der Landstraße taucht plötzlich Gegenverkehr auf. Was ist richtig?",
    answers: [t("Den Überholvorgang abbrechen, bremsen und sich hinter dem überholten Fahrzeug wieder einordnen, wenn das noch möglich ist"), f("Immer beschleunigen, um den Vorgang abzuschließen", "Beschleunigen ist nur sinnvoll, wenn das Einscheren vor dem Überholten sicher möglich ist; sonst ist der Abbruch die richtige Wahl."), f("Auf die Fahrbahnmitte fahren und hoffen, dass beide ausweichen", "Das führt zu einem Frontalzusammenstoß.")],
    explanation: "Beim Auftauchen von Gegenverkehr ist in der Regel der Abbruch des Überholvorgangs die sicherste Entscheidung: bremsen und hinter dem überholten Fahrzeug einscheren. Wer überholt wird, darf dann nicht beschleunigen.",
    legalReference: "§ 5 Abs. 2 und 6 StVO",
  }),
  q({
    code: "own-fahrmanoever-041", topic: "fahrmanoever", points: 3, difficulty: 0.5, tags: ["rechtsabbiegen", "gehweg", "grundstueck", "fussgaenger"],
    text: "Sie wollen rechts über den Gehweg in eine Grundstückseinfahrt abbiegen. Ein Fußgänger geht auf dem Gehweg. Was gilt?",
    answers: [t("Der Fußgänger hat Vorrang; Sie müssen warten, bis er die Einfahrt passiert hat"), f("Der Fußgänger muss warten, weil Sie abbiegen", "Beim Abbiegen in ein Grundstück sind Fußgänger auf dem Gehweg durchzulassen."), f("Sie dürfen langsam auf den Gehweg fahren, um den Fußgänger zum Warten zu bewegen", "Das gefährdet und behindert den Fußgänger.")],
    explanation: "Beim Abbiegen in ein Grundstück gelten dieselben Regeln wie beim Abbiegen an Kreuzungen: Fußgänger auf dem Gehweg und Radfahrende auf dem Radweg müssen durchgelassen werden.",
    legalReference: "§ 9 Abs. 3 StVO",
  }),
];
