// Übungsfragen zum Thema "fahrzeugtechnik" (eigene Formulierungen, kein amtlicher Prüfungsinhalt).
import type { Question } from "../types";
import { q, t, f } from "./_helpers";

export const fahrzeugtechnik: readonly Question[] = [
  q({
    code: "own-fahrzeugtechnik-001", topic: "fahrzeugtechnik", points: 3, difficulty: 0.2, tags: ["reifen", "profiltiefe"], kind: "numeric", numericAnswer: 1.6, tolerance: 0, unit: "mm",
    text: "Welche Mindestprofiltiefe schreibt der Gesetzgeber für Pkw-Reifen vor? Angabe in Millimetern.",
    answers: [],
    explanation: "Die gesetzliche Mindestprofiltiefe beträgt 1,6 mm. Aus Sicherheitsgründen werden mindestens 3 mm bei Sommerreifen und 4 mm bei Winterreifen empfohlen.",
    legalReference: "§ 36 Abs. 2 StVZO",
  }),
  q({
    code: "own-fahrzeugtechnik-002", topic: "fahrzeugtechnik", points: 3, difficulty: 0.3, tags: ["winterreifen", "alpine_symbol", "winter"],
    text: "Welche Reifen erfüllen bei winterlichen Straßenverhältnissen die Winterreifenpflicht?",
    answers: [t("Nur Reifen mit dem Alpine-Symbol (Bergpiktogramm mit Schneeflocke)"), f("Auch Reifen, die nur mit M+S gekennzeichnet sind", "Seit dem 1. Oktober 2024 reicht die M+S-Kennzeichnung allein nicht mehr aus."), f("Alle Reifen mit mindestens 4 mm Profil", "Die Profiltiefe ersetzt nicht die Wintertauglichkeit.")],
    explanation: "Bei Glatteis, Schneeglätte, Schneematsch, Eis- oder Reifglätte dürfen nur Reifen mit Alpine-Symbol gefahren werden. Die Übergangsfrist für reine M+S-Reifen endete am 30. September 2024.",
    legalReference: "§ 2 Abs. 3a StVO; § 36 StVZO",
  }),
  q({
    code: "own-fahrzeugtechnik-003", topic: "fahrzeugtechnik", points: 2, difficulty: 0.2, tags: ["hauptuntersuchung", "hu"],
    text: "In welchen Abständen muss ein Pkw zur Hauptuntersuchung?",
    answers: [t("Alle zwei Jahre, bei einem Neuwagen erstmals nach drei Jahren"), f("Jedes Jahr", "Pkw müssen nur alle zwei Jahre vorgeführt werden."), f("Alle fünf Jahre", "Das Intervall ist deutlich kürzer.")],
    explanation: "Pkw müssen alle 24 Monate zur Hauptuntersuchung, Neuwagen erstmals nach 36 Monaten. Die Plakette am hinteren Kennzeichen zeigt den nächsten Termin.",
    legalReference: "§ 29 StVZO, Anlage VIII",
  }),
  q({
    code: "own-fahrzeugtechnik-004", topic: "fahrzeugtechnik", points: 3, difficulty: 0.3, tags: ["kontrollleuchte", "oeldruck"],
    text: "Während der Fahrt leuchtet die rote Öldruck-Kontrollleuchte auf. Was tun Sie?",
    answers: [t("Sofort sicher anhalten und den Motor abstellen; Ölstand prüfen und im Zweifel den Pannendienst rufen"), f("Bis zur nächsten Werkstatt weiterfahren", "Ohne Öldruck kann der Motor innerhalb kurzer Zeit schwer beschädigt werden."), f("Motor laufen lassen und Öl nachfüllen", "Der Motor muss zuerst abgestellt werden.")],
    explanation: "Die rote Öldruckleuchte bedeutet, dass der Motor nicht mehr ausreichend geschmiert wird. Weiterfahren kann zum Motorschaden führen; sofort anhalten und Motor abstellen.",
  }),
  q({
    code: "own-fahrzeugtechnik-005", topic: "fahrzeugtechnik", points: 2, difficulty: 0.2, tags: ["motoroel", "sicherheitskontrolle"],
    text: "Wie prüfen Sie den Motorölstand richtig?",
    answers: [t("Fahrzeug auf ebener Fläche, Motor betriebswarm und einige Minuten abgestellt, Peilstab abwischen, einstecken und erneut ablesen"), f("Bei laufendem Motor an einer Steigung", "Auf einer Steigung und bei laufendem Motor ist der Wert falsch."), f("Nur nach einer längeren Autobahnfahrt direkt am Peilstab ablesen", "Direkt nach dem Abstellen ist das Öl noch nicht in die Wanne zurückgelaufen.")],
    explanation: "Der Ölstand wird auf ebener Fläche bei abgestelltem, warmem Motor nach kurzer Wartezeit gemessen. Der Stand muss zwischen der Minimal- und Maximalmarkierung liegen.",
  }),
  q({
    code: "own-fahrzeugtechnik-006", topic: "fahrzeugtechnik", points: 2, difficulty: 0.2, tags: ["reifendruck", "sicherheitskontrolle"],
    text: "Wann und wo prüfen Sie den Reifendruck richtig?",
    answers: [t("Bei kalten Reifen; die richtigen Werte stehen in der Betriebsanleitung, im Tankdeckel oder im Türholm"), f("Nur bei warmen Reifen nach längerer Fahrt", "Warme Reifen zeigen einen zu hohen Druck an."), f("Immer auf 3,5 bar unabhängig vom Fahrzeug", "Der richtige Druck hängt von Fahrzeug und Beladung ab.")],
    explanation: "Der Reifendruck wird bei kalten Reifen geprüft, mindestens alle 14 Tage und vor längeren Fahrten. Bei voller Beladung gilt der höhere Wert aus der Tabelle des Herstellers.",
  }),
  q({
    code: "own-fahrzeugtechnik-007", topic: "fahrzeugtechnik", points: 2, difficulty: 0.4, tags: ["bremsfluessigkeit", "bremsen"],
    text: "Warum muss die Bremsflüssigkeit regelmäßig gewechselt werden?",
    answers: [t("Sie nimmt mit der Zeit Wasser auf, wodurch der Siedepunkt sinkt und die Bremse bei starker Beanspruchung versagen kann"), f("Weil sie sich mit dem Motoröl vermischt", "Bremsflüssigkeit und Motoröl sind getrennte Systeme."), f("Sie muss nie gewechselt werden", "Die meisten Hersteller empfehlen einen Wechsel etwa alle zwei Jahre.")],
    explanation: "Bremsflüssigkeit ist hygroskopisch und zieht Wasser an. Bei hohen Temperaturen können sich Dampfblasen bilden, dann fällt die Bremswirkung aus. Wechsel nach Herstellervorgabe, meist etwa alle zwei Jahre.",
  }),
  q({
    code: "own-fahrzeugtechnik-008", topic: "fahrzeugtechnik", points: 2, difficulty: 0.3, tags: ["schneeketten", "winter", "geschwindigkeit"],
    text: "Wie schnell dürfen Sie mit montierten Schneeketten höchstens fahren?",
    answers: [t("50 km/h"), f("80 km/h", "Mit Schneeketten gilt eine niedrigere Grenze."), f("30 km/h", "Erlaubt sind bis zu 50 km/h.")],
    explanation: "Mit Schneeketten darf höchstens 50 km/h gefahren werden, auch wenn Verkehrszeichen mehr erlauben würden.",
    legalReference: "§ 3 Abs. 4 StVO",
  }),
  q({
    code: "own-fahrzeugtechnik-009", topic: "fahrzeugtechnik", points: 2, difficulty: 0.2, tags: ["fahrzeugpapiere", "zulassung"],
    text: "Welches Dokument müssen Sie beim Fahren neben dem Führerschein mitführen?",
    answers: [t("Die Zulassungsbescheinigung Teil I (Fahrzeugschein)"), f("Die Zulassungsbescheinigung Teil II (Fahrzeugbrief)", "Teil II gehört sicher verwahrt, nicht ins Fahrzeug."), f("Den Kaufvertrag des Fahrzeugs", "Der Kaufvertrag ist keine Fahrzeugurkunde.")],
    explanation: "Die Zulassungsbescheinigung Teil I muss mitgeführt und auf Verlangen vorgezeigt werden. Teil II bleibt zu Hause, weil er das Eigentum dokumentiert.",
    legalReference: "§ 11 FZV",
  }),
  q({
    code: "own-fahrzeugtechnik-010", topic: "fahrzeugtechnik", points: 2, difficulty: 0.3, tags: ["stossdaempfer", "fahrwerk"],
    text: "Woran erkennen Sie verschlissene Stoßdämpfer und welche Folgen haben sie?",
    answers: [t("Das Fahrzeug schaukelt nach Bodenwellen nach; der Bremsweg wird länger und die Kurvenstabilität sinkt"), f("Der Motor läuft unrund", "Stoßdämpfer haben mit dem Motorlauf nichts zu tun."), f("Es gibt keine Folgen, solange die Federn intakt sind", "Ohne wirksame Dämpfung verlieren die Räder Bodenkontakt.")],
    explanation: "Defekte Stoßdämpfer lassen die Räder springen, verlängern den Bremsweg und verschlechtern das Kurvenverhalten. Nachschwingen der Karosserie ist ein typisches Anzeichen.",
  }),
  q({
    code: "own-fahrzeugtechnik-011", topic: "fahrzeugtechnik", points: 3, difficulty: 0.6, tags: ["reifen", "reifenbezeichnung", "breite"], kind: "numeric", numericAnswer: 205, tolerance: 0, unit: "mm",
    text: "Auf dem Reifen steht die Bezeichnung 205/55 R 16 91 V. Wie breit ist der Reifen? Angabe in Millimetern.",
    answers: [],
    explanation: "Die erste Zahl der Reifenbezeichnung gibt die Reifenbreite in Millimetern an, hier 205 mm. Es folgen das Verhältnis von Höhe zu Breite in Prozent, die Bauart R für Radial, der Felgendurchmesser in Zoll, der Tragfähigkeitsindex und der Geschwindigkeitsindex.",
  }),
  q({
    code: "own-fahrzeugtechnik-012", topic: "fahrzeugtechnik", points: 3, difficulty: 0.65, tags: ["reifen", "reifenbezeichnung", "felge"], kind: "numeric", numericAnswer: 16, tolerance: 0, unit: "Zoll",
    text: "Ein Reifen trägt die Bezeichnung 205/55 R 16 91 V. Welchen Felgendurchmesser benötigt er? Angabe in Zoll.",
    answers: [],
    explanation: "Die Zahl nach dem R gibt den Felgendurchmesser in Zoll an, hier 16 Zoll. Die 55 bezeichnet das Höhen-Breiten-Verhältnis in Prozent, 91 den Tragfähigkeitsindex und V den Geschwindigkeitsindex.",
  }),
  q({
    code: "own-fahrzeugtechnik-013", topic: "fahrzeugtechnik", points: 3, difficulty: 0.65, tags: ["reifen", "geschwindigkeitsindex", "winterreifen"],
    text: "Ihr Pkw erreicht 220 km/h. Sie montieren Winterreifen mit dem Geschwindigkeitsindex T (bis 190 km/h). Was gilt?",
    answers: [t("Das ist zulässig, wenn ein Hinweis auf die niedrigere zulässige Höchstgeschwindigkeit im Sichtfeld des Fahrers angebracht ist"), t("Sie dürfen mit diesen Reifen nicht schneller als 190 km/h fahren"), f("Winterreifen müssen immer den gleichen Geschwindigkeitsindex wie Sommerreifen haben", "Bei Winterreifen ist ein niedrigerer Index zulässig, wenn ein Hinweisschild angebracht wird."), f("Der Geschwindigkeitsindex spielt bei Winterreifen keine Rolle", "Die Reifen dürfen nicht über ihrer zugelassenen Geschwindigkeit betrieben werden.")],
    explanation: "Winterreifen dürfen einen niedrigeren Geschwindigkeitsindex haben als die Höchstgeschwindigkeit des Fahrzeugs. Dann muss ein Hinweisschild mit der zulässigen Höchstgeschwindigkeit der Reifen im Blickfeld des Fahrers angebracht werden, und diese Geschwindigkeit darf nicht überschritten werden.",
    legalReference: "§ 36 StVZO",
  }),
  q({
    code: "own-fahrzeugtechnik-014", topic: "fahrzeugtechnik", points: 3, difficulty: 0.6, tags: ["reifen", "geschwindigkeitsindex"],
    text: "Welche Höchstgeschwindigkeit ist für einen Reifen mit dem Geschwindigkeitsindex V zugelassen?",
    answers: [t("240 km/h"), f("190 km/h", "190 km/h entspricht dem Index T."), f("210 km/h", "210 km/h entspricht dem Index H."), f("270 km/h", "270 km/h entspricht dem Index W.")],
    explanation: "Die Geschwindigkeitsindizes lauten unter anderem T für 190, H für 210, V für 240 und W für 270 km/h. Die Reifen müssen mindestens für die Höchstgeschwindigkeit des Fahrzeugs zugelassen sein; Ausnahmen gelten für Winterreifen mit Hinweisschild.",
    mnemonic: "T 190, H 210, V 240, W 270.",
  }),
  q({
    code: "own-fahrzeugtechnik-015", topic: "fahrzeugtechnik", points: 3, difficulty: 0.6, tags: ["hauptuntersuchung", "hu", "frist", "punkte"],
    text: "Die Hauptuntersuchung Ihres Pkw ist seit neun Monaten überfällig. Was gilt?",
    answers: [t("Es droht ein Bußgeld mit einem Punkt im Fahreignungsregister"), t("Bei der nachgeholten Hauptuntersuchung wird eine erweiterte Prüfung gegen Aufpreis fällig"), f("Die neue Plakette gilt ab dem Tag der nachgeholten Untersuchung wieder zwei volle Jahre", "Die Plakette wird nur bis zum ursprünglich fälligen Termin plus Intervall ausgestellt; die Überziehung wird nicht gutgeschrieben."), f("Solange das Fahrzeug fahrbereit ist, hat das keine Folgen", "Das Überziehen der HU ist eine Ordnungswidrigkeit.")],
    explanation: "Wer die Hauptuntersuchung um mehr als acht Monate überzieht, muss mit Bußgeld und einem Punkt rechnen. Bereits ab zwei Monaten Überziehung wird eine vertiefte Prüfung mit Aufpreis fällig. Die neue Plakette knüpft an den alten Fälligkeitstermin an, die Überziehung geht verloren.",
    legalReference: "§ 29 StVZO; Anlage VIII StVZO; BKatV",
  }),
  q({
    code: "own-fahrzeugtechnik-016", topic: "fahrzeugtechnik", points: 3, difficulty: 0.6, tags: ["hauptuntersuchung", "hu", "plakette"], kind: "numeric", numericAnswer: 36, tolerance: 0, unit: "Monate",
    text: "Nach wie vielen Monaten muss ein neu zugelassener Pkw erstmals zur Hauptuntersuchung?",
    answers: [],
    explanation: "Neue Pkw müssen erstmals nach 36 Monaten zur Hauptuntersuchung, danach alle 24 Monate. Die Prüfplakette am hinteren Kennzeichen zeigt Monat und Jahr der nächsten Fälligkeit.",
    legalReference: "§ 29 StVZO; Anlage VIII StVZO",
  }),
  q({
    code: "own-fahrzeugtechnik-017", topic: "fahrzeugtechnik", points: 3, difficulty: 0.65, tags: ["kontrollleuchte", "ladekontrolle", "generator", "keilriemen"],
    text: "Während der Fahrt leuchtet die rote Ladekontrollleuchte (Batteriesymbol) auf. Was bedeutet das und was tun Sie?",
    answers: [t("Der Generator lädt die Batterie nicht mehr; unnötige elektrische Verbraucher ausschalten und die nächste Werkstatt anfahren"), t("Ursache kann ein gerissener Keilrippenriemen sein; dann kann auch die Wasserpumpe ausfallen, weshalb die Kühlmitteltemperatur zu beobachten ist"), f("Die Batterie ist voll geladen, die Leuchte ist eine Bestätigung", "Die Leuchte zeigt einen Fehler im Ladesystem an."), f("Der Motor muss sofort abgestellt werden, weil er sonst explodiert", "Die Fahrt kann kurz fortgesetzt werden, solange die Batterie Strom liefert und der Motor nicht überhitzt.")],
    explanation: "Die Ladekontrollleuchte zeigt an, dass der Generator keine Spannung liefert. Das Fahrzeug fährt noch mit der Batterie, aber nur begrenzt lange. Ist der Riemen gerissen, treibt er oft auch Wasserpumpe und Servopumpe an, sodass Überhitzung und schwere Lenkung drohen.",
  }),
  q({
    code: "own-fahrzeugtechnik-018", topic: "fahrzeugtechnik", points: 3, difficulty: 0.6, tags: ["kontrollleuchte", "motorkontrollleuchte", "abgas"],
    text: "Die gelbe Motorkontrollleuchte leuchtet dauerhaft, der Motor läuft normal. Was ist richtig?",
    answers: [t("Ein Fehler in Motorsteuerung oder Abgasreinigung ist gespeichert; die Werkstatt sollte bald aufgesucht werden"), t("Blinkt die Leuchte, ist die Weiterfahrt zu vermeiden, weil der Katalysator beschädigt werden kann"), f("Die Leuchte zeigt fälligen Ölwechsel an", "Der Ölwechsel wird über die Serviceanzeige angezeigt."), f("Die Leuchte kann ignoriert werden, wenn der Motor rund läuft", "Auch ohne spürbare Symptome können Emissionen und Verbrauch stark erhöht sein.")],
    explanation: "Die Motorkontrollleuchte meldet einen Fehler in der Motorsteuerung oder Abgasanlage. Dauerleuchten erlaubt die vorsichtige Weiterfahrt bis zur Werkstatt, Blinken weist auf Zündaussetzer hin, die den Katalysator zerstören können. Bei der Hauptuntersuchung führt eine leuchtende Motorkontrollleuchte zum Mangel.",
  }),
  q({
    code: "own-fahrzeugtechnik-019", topic: "fahrzeugtechnik", points: 3, difficulty: 0.6, tags: ["kontrollleuchte", "abs", "bremsen"],
    text: "Die gelbe ABS-Kontrollleuchte bleibt nach dem Start dauerhaft an. Was bedeutet das?",
    answers: [t("Das ABS ist abgeschaltet; die normale Bremse funktioniert, bei Vollbremsung können die Räder aber blockieren"), t("Meist ist auch das ESP ohne Funktion, weil es die gleichen Sensoren nutzt"), f("Die Bremsanlage ist vollständig ausgefallen", "Die Betriebsbremse arbeitet weiter; nur die Blockierverhinderung fehlt."), f("Die Leuchte zeigt an, dass das ABS gerade regelt", "Beim Regeln leuchtet keine Kontrollleuchte, man spürt ein Pulsieren im Pedal.")],
    explanation: "Leuchtet die ABS-Kontrollleuchte dauerhaft, hat das System einen Fehler und ist inaktiv. Gebremst werden kann weiterhin, aber ohne Blockierschutz und meist auch ohne ESP. Die Fahrweise ist anzupassen und der Fehler zeitnah zu beheben.",
  }),
  q({
    code: "own-fahrzeugtechnik-020", topic: "fahrzeugtechnik", points: 3, difficulty: 0.6, tags: ["bremsen", "sicherheitskontrolle", "bremspedal"],
    text: "Welche Beobachtungen deuten auf einen Mangel an der Bremsanlage hin?",
    answers: [t("Das Bremspedal lässt sich weit und federnd durchtreten"), t("Das Fahrzeug zieht beim Bremsen zur Seite"), t("Das Lenkrad flattert oder das Pedal pulsiert bei jeder normalen Bremsung"), f("Das Bremspedal wird bei einer Vollbremsung mit ABS hart und pulsiert", "Das ist die normale Regelung des ABS.")],
    explanation: "Ein weicher oder nachgebender Pedalweg deutet auf Luft oder eine Undichtigkeit im System hin, einseitiges Ziehen auf ungleich wirkende Bremsen, Pulsieren bei normalen Bremsungen auf verzogene Bremsscheiben. Solche Mängel sind sofort in der Werkstatt zu beheben.",
    legalReference: "§ 41 StVZO",
  }),
  q({
    code: "own-fahrzeugtechnik-021", topic: "fahrzeugtechnik", points: 3, difficulty: 0.65, tags: ["bremsen", "zweikreisbremsanlage", "kontrollleuchte"],
    text: "Während der Fahrt leuchtet die rote Bremsen-Warnleuchte, obwohl die Feststellbremse gelöst ist. Das Pedal fühlt sich anders an als sonst. Was gilt?",
    answers: [t("Möglicherweise ist ein Bremskreis ausgefallen; die Zweikreisbremsanlage lässt noch eine verringerte Bremswirkung zu"), t("Vorsichtig weiterfahren und sofort die nächste Werkstatt oder den Pannendienst aufsuchen; mit längerem Bremsweg rechnen"), f("Die Leuchte bedeutet nur, dass die Bremsbeläge bald gewechselt werden müssen", "Die rote Warnleuchte weist auf Bremsflüssigkeitsmangel oder Kreisausfall hin."), f("Die Bremsanlage arbeitet normal, die Leuchte ist ein Sensorfehler", "Eine rote Warnleuchte ist immer ernst zu nehmen.")],
    explanation: "Die rote Bremsen-Warnleuchte zeigt bei gelöster Feststellbremse einen zu niedrigen Bremsflüssigkeitsstand oder den Ausfall eines Bremskreises an. Dank Zweikreisbremsanlage bleibt eine Restbremswirkung erhalten, der Bremsweg wird aber deutlich länger. Die Fahrt darf nur bis zur nächsten Hilfe fortgesetzt werden.",
    legalReference: "§ 41 StVZO",
  }),
  q({
    code: "own-fahrzeugtechnik-022", topic: "fahrzeugtechnik", points: 3, difficulty: 0.6, tags: ["reifen", "reifendruck", "rdks", "beladung"],
    text: "Welche Aussagen zum Reifendruck treffen zu?",
    answers: [t("Bei voller Beladung und Anhängerbetrieb gilt der höhere Druckwert aus der Herstellertabelle"), t("Zu hoher Druck verkleinert die Aufstandsfläche und verschlechtert die Haftung"), t("Das Reifendruckkontrollsystem warnt bei Druckverlust, ersetzt aber nicht die regelmäßige Prüfung"), f("Der Druck sollte nach längerer Autobahnfahrt auf den Sollwert abgesenkt werden", "Warme Reifen haben einen höheren Druck; Ablassen führt zu Unterdruck nach dem Abkühlen.")],
    explanation: "Der richtige Reifendruck hängt von Beladung und Fahrzeug ab und wird bei kalten Reifen geprüft. Zu wenig Druck erhöht Verbrauch und Verschleiß und kann zum Reifenplatzer führen, zu viel Druck verringert die Aufstandsfläche. RDKS-Warnungen sind ernst zu nehmen.",
  }),
  q({
    code: "own-fahrzeugtechnik-023", topic: "fahrzeugtechnik", points: 3, difficulty: 0.6, tags: ["reifen", "verschleiss", "achsgeometrie"],
    text: "Die Vorderreifen Ihres Pkw sind nur an der Innenseite stark abgefahren. Was ist die wahrscheinliche Ursache?",
    answers: [t("Eine verstellte Achsgeometrie, etwa falsche Spur oder falscher Sturz"), f("Zu hoher Reifendruck", "Zu hoher Druck nutzt die Lauffläche in der Mitte ab."), f("Zu niedriger Reifendruck", "Zu niedriger Druck nutzt beide Schultern ab, nicht nur eine Seite."), f("Normaler Verschleiß bei Vorderradantrieb", "Einseitiger Verschleiß ist nie normal.")],
    explanation: "Einseitig abgefahrene Reifen deuten auf eine falsche Achseinstellung hin, oft nach einem Bordsteinkontakt oder Schlagloch. Abnutzung in der Mitte spricht für zu hohen, an beiden Schultern für zu niedrigen Reifendruck. Die Achsvermessung gehört in die Werkstatt.",
  }),
  q({
    code: "own-fahrzeugtechnik-024", topic: "fahrzeugtechnik", points: 3, difficulty: 0.6, tags: ["betriebserlaubnis", "tuning", "aenderung", "felgen"],
    text: "Sie wollen an Ihrem Pkw andere Felgen und ein Sportfahrwerk montieren. Was gilt?",
    answers: [t("Änderungen, durch die eine Gefährdung zu erwarten ist oder die Fahrzeugart oder das Abgas- und Geräuschverhalten ändern, lassen die Betriebserlaubnis erlöschen, wenn sie nicht abgenommen werden"), t("Teile mit Allgemeiner Betriebserlaubnis oder Teilegutachten müssen nach den Auflagen montiert und gegebenenfalls von einem Prüfer abgenommen und eingetragen werden"), f("Alle im Handel erhältlichen Teile dürfen ohne weiteres montiert werden", "Nur Teile mit entsprechender Genehmigung und unter Einhaltung der Auflagen sind zulässig."), f("Änderungen müssen nur der Versicherung gemeldet werden", "Zusätzlich sind die Vorschriften zur Betriebserlaubnis einzuhalten.")],
    explanation: "Die Betriebserlaubnis erlischt, wenn Änderungen vorgenommen werden, durch die eine Gefährdung von Verkehrsteilnehmern zu erwarten ist oder Abgas- oder Geräuschverhalten sich verschlechtern. Wer ohne Betriebserlaubnis fährt, riskiert Bußgeld und Versicherungsprobleme. Genehmigte Teile mit Abnahme und Eintragung sind der sichere Weg.",
    legalReference: "§ 19 Abs. 2 und 3 StVZO",
  }),
  q({
    code: "own-fahrzeugtechnik-025", topic: "fahrzeugtechnik", points: 3, difficulty: 0.6, tags: ["halter", "verantwortung", "verkehrssicherheit"],
    text: "Welche Pflichten hat der Halter eines Fahrzeugs?",
    answers: [t("Er darf die Inbetriebnahme nicht anordnen oder zulassen, wenn das Fahrzeug nicht vorschriftsmäßig ist"), t("Er muss dafür sorgen, dass das Fahrzeug fristgerecht zur Hauptuntersuchung vorgeführt wird"), t("Er darf das Fahrzeug nur Personen überlassen, die zum Führen berechtigt sind"), f("Er haftet nicht, wenn ein anderer Fahrer mit dem mangelhaften Fahrzeug einen Unfall verursacht", "Der Halter haftet aus der Betriebsgefahr und für zugelassene Mängel.")],
    explanation: "Der Halter trägt die Verantwortung für den vorschriftsmäßigen Zustand seines Fahrzeugs und dafür, wem er es überlässt. Verstöße, etwa das Überlassen an Fahrer ohne Fahrerlaubnis, sind für den Halter strafbar; für Betriebsgefahr haftet er unabhängig vom Verschulden.",
    legalReference: "§ 31 Abs. 2 StVZO; § 21 StVG; § 7 StVG",
  }),
  q({
    code: "own-fahrzeugtechnik-026", topic: "fahrzeugtechnik", points: 3, difficulty: 0.6, tags: ["zulassung", "fzv", "umzug", "verkauf"],
    text: "Welche Meldepflichten nach der Fahrzeug-Zulassungsverordnung treffen zu?",
    answers: [t("Nach einem Umzug ist die neue Anschrift unverzüglich der Zulassungsbehörde mitzuteilen"), t("Beim Verkauf muss der bisherige Halter unverzüglich Zulassungsbehörde und Versicherer informieren und dem Käufer die Fahrzeugpapiere aushändigen"), f("Ein Umzug innerhalb derselben Stadt muss nicht gemeldet werden", "Jede Änderung der Anschrift ist meldepflichtig."), f("Nach dem Verkauf reicht es, wenn der Käufer das Fahrzeug irgendwann ummeldet", "Der Verkäufer muss selbst melden, sonst haftet er weiter für Steuern und Verstöße.")],
    explanation: "Halter müssen Änderungen von Name und Anschrift sowie den Halterwechsel unverzüglich melden. Die Verkaufsanzeige an Zulassungsbehörde und Versicherer schützt den Verkäufer, weil sonst Steuern, Bußgelder und Versicherungsbeiträge weiter auf ihn zukommen können.",
    legalReference: "§ 13 FZV",
  }),
  q({
    code: "own-fahrzeugtechnik-027", topic: "fahrzeugtechnik", points: 3, difficulty: 0.6, tags: ["kennzeichen", "saisonkennzeichen", "zulassung"],
    text: "Ihr Cabrio hat ein Saisonkennzeichen mit dem Zeitraum April bis Oktober. Was gilt im November?",
    answers: [t("Das Fahrzeug darf weder auf öffentlichen Straßen gefahren noch dort abgestellt werden"), f("Es darf gefahren werden, wenn das Wetter gut ist", "Außerhalb des Zeitraums besteht kein Versicherungs- und Zulassungsschutz für den öffentlichen Verkehr."), f("Es darf auf der Straße geparkt, aber nicht gefahren werden", "Auch das Abstellen auf öffentlichen Straßen ist außerhalb des Zeitraums verboten.")],
    explanation: "Ein Fahrzeug mit Saisonkennzeichen ist nur innerhalb des angegebenen Zeitraums zugelassen. Außerhalb davon darf es auf öffentlichen Straßen weder in Betrieb genommen noch abgestellt werden; es gehört auf ein Privatgrundstück.",
    legalReference: "§ 9 FZV",
  }),
  q({
    code: "own-fahrzeugtechnik-028", topic: "fahrzeugtechnik", points: 3, difficulty: 0.6, tags: ["sicherheitskontrolle", "abfahrtkontrolle", "fahrtantritt"],
    text: "Welche Kontrollen gehören vor Fahrtantritt zur Verantwortung des Fahrers?",
    answers: [t("Sichtprüfung der Reifen auf Beschädigungen, Luftdruck und Profil"), t("Funktion von Beleuchtung, Blinkern und Bremsleuchten"), t("Saubere Scheiben, Spiegel und Kennzeichen sowie ausreichend Waschwasser"), f("Kontrolle des Zahnriemens", "Der Zahnriemen wird nach Herstellerintervall in der Werkstatt gewechselt und ist nicht Teil der Abfahrtkontrolle.")],
    explanation: "Der Fahrer muss sich vor der Fahrt vom verkehrssicheren Zustand des Fahrzeugs überzeugen. Reifen, Beleuchtung, Sicht und die wichtigsten Flüssigkeitsstände lassen sich in wenigen Minuten prüfen. Der Fahrer ist für die Verkehrssicherheit während der Fahrt verantwortlich.",
    legalReference: "§ 23 Abs. 1 StVO; § 31 Abs. 1 StVZO",
  }),
  q({
    code: "own-fahrzeugtechnik-029", topic: "fahrzeugtechnik", points: 3, difficulty: 0.6, tags: ["motoroel", "oelstand", "katalysator"],
    text: "Beim Ölnachfüllen haben Sie deutlich über die Maximalmarkierung hinaus eingefüllt. Welche Folgen kann das haben?",
    answers: [t("Öl kann in den Brennraum und in die Abgasanlage gelangen und den Katalysator beschädigen"), t("Dichtungen können durch den erhöhten Druck undicht werden"), f("Keine, mehr Öl schmiert besser", "Zu viel Öl ist schädlich; der Stand muss zwischen den Markierungen liegen."), f("Der Motor läuft dadurch kühler", "Überfüllung führt eher zu Schaumbildung und schlechterer Schmierung.")],
    explanation: "Ein überfüllter Motor schäumt das Öl auf, verschlechtert die Schmierung und drückt Öl in Abgasanlage und Katalysator. Zu viel Öl muss vor der Weiterfahrt abgelassen oder abgesaugt werden. Der Ölstand gehört zwischen die Minimal- und Maximalmarkierung.",
  }),
  q({
    code: "own-fahrzeugtechnik-030", topic: "fahrzeugtechnik", points: 3, difficulty: 0.55, tags: ["kuehlmittel", "frostschutz", "winter"],
    text: "Was ist beim Kühlmittel des Motors zu beachten?",
    answers: [t("Der Stand im Ausgleichsbehälter muss bei kaltem Motor zwischen den Markierungen liegen"), t("Das Kühlmittel muss ausreichend Frostschutz enthalten, sonst kann der Motorblock bei Frost reißen"), t("Nur vom Hersteller freigegebenes Kühlmittel verwenden, weil verschiedene Sorten unverträglich sein können"), f("Bei heißem Motor sofort den Deckel öffnen und kaltes Wasser nachfüllen", "Der Kreislauf steht unter Druck; es droht Verbrühung und ein Thermoschock für den Motor.")],
    explanation: "Das Kühlmittel schützt den Motor vor Überhitzung und Frost. Der Stand wird am Ausgleichsbehälter bei kaltem Motor abgelesen. Frostschutz und Korrosionsschutz müssen dem Herstellervorgaben entsprechen. Der Verschluss wird nie am heißen Motor geöffnet.",
  }),
  q({
    code: "own-fahrzeugtechnik-031", topic: "fahrzeugtechnik", points: 3, difficulty: 0.6, tags: ["elektrofahrzeug", "hochvolt", "avas", "technik"],
    text: "Welche Aussagen zu Elektrofahrzeugen treffen zu?",
    answers: [t("Hochvoltleitungen sind orange gekennzeichnet und dürfen nur von geschultem Personal geöffnet werden"), t("Neue Elektrofahrzeuge müssen bei niedriger Geschwindigkeit ein künstliches Fahrgeräusch (AVAS) erzeugen, damit Fußgänger sie hören"), t("Beim Ausrollen und Bremsen wird durch Rekuperation Energie zurückgewonnen"), f("Elektrofahrzeuge benötigen keine Hauptuntersuchung", "Auch Elektrofahrzeuge müssen regelmäßig zur Hauptuntersuchung.")],
    explanation: "Elektrofahrzeuge arbeiten mit Hochvoltsystemen, die orange gekennzeichnet sind. Weil sie bei niedriger Geschwindigkeit sehr leise sind, ist für neue Fahrzeuge ein akustisches Warnsystem vorgeschrieben. Die Hauptuntersuchung gilt wie für alle anderen Pkw.",
  }),
  q({
    code: "own-fahrzeugtechnik-032", topic: "fahrzeugtechnik", points: 3, difficulty: 0.55, tags: ["lenkung", "servolenkung", "ausfall"],
    text: "Während der Fahrt fällt die Servolenkung aus. Was gilt?",
    answers: [t("Das Fahrzeug bleibt lenkbar, die Lenkung wird aber deutlich schwergängiger, besonders bei niedriger Geschwindigkeit"), f("Das Fahrzeug ist nicht mehr lenkbar und muss sofort mit der Feststellbremse gestoppt werden", "Die mechanische Verbindung zur Lenkung bleibt erhalten."), f("Die Lenkung wird leichter, weil die Hydraulik nicht mehr bremst", "Ohne Unterstützung ist mehr Kraft nötig.")],
    explanation: "Bei einem Ausfall der Servolenkung, etwa durch Motorstillstand oder Riemenriss, muss der Fahrer die gesamte Lenkkraft selbst aufbringen. Das Fahrzeug bleibt beherrschbar, sollte aber kontrolliert abgestellt und repariert werden.",
  }),
  q({
    code: "own-fahrzeugtechnik-033", topic: "fahrzeugtechnik", points: 3, difficulty: 0.55, tags: ["abgasanlage", "kohlenmonoxid", "sicherheit"],
    text: "Die Abgasanlage Ihres Pkw ist undicht und deutlich lauter geworden. Welche Gefahren bestehen?",
    answers: [t("Abgase mit Kohlenmonoxid können in den Innenraum gelangen und zu Müdigkeit bis hin zu Bewusstlosigkeit führen"), t("Das erhöhte Geräusch verstößt gegen die Vorschriften und kann die Betriebserlaubnis in Frage stellen"), f("Keine, die Abgasanlage hat nur Einfluss auf das Geräusch", "Undichte Anlagen sind gesundheitsgefährdend."), f("Der Motor leistet dadurch mehr", "Undichtigkeiten verschlechtern die Leistung eher.")],
    explanation: "Kohlenmonoxid ist geruchlos und kann bei undichter Abgasanlage in den Fahrgastraum gelangen. Zudem überschreitet ein lauter Auspuff die zulässigen Geräuschwerte. Der Schaden ist umgehend zu beheben.",
    legalReference: "§ 47 StVZO; § 49 StVZO",
  }),
  q({
    code: "own-fahrzeugtechnik-034", topic: "fahrzeugtechnik", points: 3, difficulty: 0.55, tags: ["sitzposition", "kopfstuetze", "sicherheit"],
    text: "Wie stellen Sie Sitz, Kopfstütze und Lenkrad richtig ein?",
    answers: [t("Sitz so weit nach vorn, dass die Pedale voll durchgetreten werden können, ohne dass das Bein ganz gestreckt ist"), t("Kopfstütze so hoch, dass ihre Oberkante mindestens auf Höhe der Kopfoberkante liegt"), t("Bei aufliegender Schulter am Sitz sollte das Handgelenk mit gestrecktem Arm auf dem Lenkradkranz liegen"), f("Rückenlehne möglichst weit nach hinten neigen, damit man bequem sitzt", "Eine zu flache Lehne verschlechtert Kontrolle und Gurtwirkung.")],
    explanation: "Eine gute Sitzposition ermöglicht volle Pedalwege und ausreichenden Abstand zum Lenkrad. Die Kopfstütze verhindert bei einem Auffahrunfall das Überstrecken des Halses nur, wenn sie hoch genug steht. Die Lehne bleibt fast aufrecht, damit der Gurt richtig anliegt.",
  }),
  q({
    code: "own-fahrzeugtechnik-035", topic: "fahrzeugtechnik", points: 3, difficulty: 0.55, tags: ["reifen", "alter", "beschaedigung"],
    text: "Wann sollten Reifen ersetzt werden, auch wenn die gesetzliche Mindestprofiltiefe noch nicht erreicht ist?",
    answers: [t("Bei Rissen, Beulen oder sichtbaren Beschädigungen der Flanke"), t("Bei hohem Alter, weil das Gummi aushärtet und die Haftung nachlässt"), t("Wenn das Profil ungleichmäßig oder einseitig abgefahren ist"), f("Nach jedem Winter grundsätzlich", "Die Reifen werden je nach Zustand ersetzt, nicht nach festem Kalender.")],
    explanation: "Beschädigungen an der Flanke können zum plötzlichen Reifenplatzer führen. Alte Reifen härten aus und verlieren Haftung, erkennbar am DOT-Datum. Ungleichmäßiger Verschleiß verschlechtert Brems- und Kurvenverhalten und deutet auf Fahrwerksmängel hin.",
  }),
  q({
    code: "own-fahrzeugtechnik-036", topic: "fahrzeugtechnik", points: 2, difficulty: 0.45, tags: ["scheibenwischer", "sicht", "frostschutz"],
    text: "Was ist für die Scheibenwaschanlage im Winter zu beachten?",
    answers: [t("Frostschutzmittel zugeben, damit die Düsen nicht einfrieren und die Scheibe bei Fahrtwind nicht vereist"), f("Nur klares Wasser verwenden, weil Zusätze den Lack angreifen", "Ohne Frostschutz friert das Wasser ein."), f("Die Waschanlage im Winter nicht benutzen", "Gerade im Winter wird die Scheibe durch Salz und Schmutz schnell blind.")],
    explanation: "Ohne Frostschutz kann das Waschwasser in den Leitungen und auf der Scheibe gefrieren und die Sicht plötzlich blockieren. Frostschutz und intakte Wischerblätter sind im Winter unverzichtbar für die Sicht.",
    legalReference: "§ 23 Abs. 1 StVO; § 40 StVZO",
  }),
  q({
    code: "own-fahrzeugtechnik-037", topic: "fahrzeugtechnik", points: 2, difficulty: 0.4, tags: ["kontrollleuchte", "kuehlmittel", "temperatur"],
    text: "Die rote Kühlmittel-Warnleuchte leuchtet während der Fahrt auf. Was tun Sie?",
    answers: [t("Sicher anhalten, Motor abstellen und abkühlen lassen; Ursache prüfen, bevor die Fahrt fortgesetzt wird"), f("Weiterfahren und die Heizung ausschalten", "Die Heizung würde sogar Wärme abführen; Weiterfahren droht Motorschaden."), f("Sofort kaltes Wasser in den Kühler füllen", "Am heißen Motor droht Verbrühung und Thermoschock.")],
    explanation: "Die Warnleuchte zeigt Überhitzung oder Kühlmittelmangel an. Weiterfahren kann zum Motorschaden führen. Anhalten, Motor aus, abkühlen lassen und erst dann Kühlmittelstand und Undichtigkeiten prüfen.",
  }),
  q({
    code: "own-fahrzeugtechnik-038", topic: "fahrzeugtechnik", points: 2, difficulty: 0.4, tags: ["reifen", "profiltiefe", "verschleissanzeiger"],
    text: "Woran erkennen Sie ohne Messgerät, dass die Mindestprofiltiefe erreicht ist?",
    answers: [t("An den Verschleißanzeigern (kleine Stege) in den Profilrillen, die dann mit der Lauffläche bündig sind"), f("Daran, dass der Reifen glänzt", "Glanz sagt nichts über die Profiltiefe aus."), f("Am Reifendruck, der dann sinkt", "Der Druck hängt nicht vom Profil ab.")],
    explanation: "In den Hauptprofilrillen befinden sich Verschleißanzeiger von 1,6 mm Höhe. Sind sie mit der Lauffläche bündig, ist die gesetzliche Mindestprofiltiefe erreicht. Aus Sicherheitsgründen sollten Reifen deutlich früher gewechselt werden.",
    legalReference: "§ 36 Abs. 2 StVZO",
  }),
  q({
    code: "own-fahrzeugtechnik-039", topic: "fahrzeugtechnik", points: 2, difficulty: 0.4, tags: ["batterie", "starterbatterie", "winter"],
    text: "Warum versagt die Starterbatterie besonders oft im Winter?",
    answers: [t("Bei Kälte sinkt die Leistungsfähigkeit der Batterie, während der kalte Motor mehr Startstrom benötigt"), f("Weil die Batteriesäure im Winter verdunstet", "Verdunstung ist bei Kälte geringer."), f("Weil Winterreifen mehr Strom verbrauchen", "Reifen verbrauchen keinen Strom.")],
    explanation: "Kälte verringert die Kapazität der Batterie, gleichzeitig ist das Motoröl zäh und der Anlasser braucht mehr Strom. Zusätzlich laufen im Winter viele Verbraucher wie Licht, Heizung und Heckscheibenheizung. Eine schwache Batterie sollte vor dem Winter geprüft werden.",
  }),
  q({
    code: "own-fahrzeugtechnik-040", topic: "fahrzeugtechnik", points: 2, difficulty: 0.4, tags: ["winterreifen", "alpine_symbol", "bussgeld"],
    text: "Sie fahren bei Schneeglätte mit Sommerreifen und werden kontrolliert. Welche Folgen hat das?",
    answers: [t("Bußgeld und ein Punkt; bei Behinderung oder Gefährdung höhere Sanktionen"), f("Keine, solange kein Unfall passiert", "Die situative Winterreifenpflicht gilt unabhängig vom Unfall."), f("Nur eine mündliche Verwarnung", "Der Verstoß ist bußgeldbewehrt und wird mit einem Punkt eingetragen.")],
    explanation: "Wer bei winterlichen Straßenverhältnissen ohne Reifen mit Alpine-Symbol fährt, handelt ordnungswidrig. Es drohen Bußgeld und ein Punkt, bei Behinderung, Gefährdung oder Unfall entsprechend mehr. Auch der Halter kann belangt werden, wenn er die Fahrt anordnet oder zulässt.",
    legalReference: "§ 2 Abs. 3a StVO; BKatV",
  }),
];
