// Übungsfragen zum Thema "gefahrenlehre" (eigene Formulierungen, kein amtlicher Prüfungsinhalt).
import type { Question } from "../types";
import { q, t, f } from "./_helpers";

export const gefahrenlehre: readonly Question[] = [
  q({
    code: "own-gefahrenlehre-001", topic: "gefahrenlehre", points: 2, difficulty: 0.2, tags: ["reaktionszeit", "anhalteweg"],
    text: "Mit welcher Reaktionszeit rechnet die Faustformel für den Reaktionsweg bei einem aufmerksamen Fahrer?",
    answers: [t("Etwa 1 Sekunde"), f("Etwa 0,1 Sekunden", "So schnell reagiert kein Mensch; allein die Wahrnehmung braucht länger."), f("Etwa 3 Sekunden", "Das wäre eine stark verlängerte Reaktionszeit, etwa bei Müdigkeit oder Ablenkung.")],
    explanation: "Die Faustformel für den Reaktionsweg geht von rund einer Sekunde Reaktionszeit aus. In dieser Zeit legt das Fahrzeug bei 50 km/h bereits etwa 15 Meter zurück.",
    mnemonic: "Eine Sekunde Schrecksekunde.",
  }),
  q({
    code: "own-gefahrenlehre-002", topic: "gefahrenlehre", points: 3, difficulty: 0.3, tags: ["reaktionszeit", "ablenkung", "muedigkeit"],
    text: "Wodurch verlängert sich die Reaktionszeit beim Fahren?",
    answers: [t("Durch Müdigkeit"), t("Durch Alkohol"), t("Durch Ablenkung mit dem Smartphone"), f("Durch eingeschaltetes Tagfahrlicht", "Das Tagfahrlicht hat keinen Einfluss auf die Reaktionszeit.")],
    explanation: "Müdigkeit, Alkohol und Ablenkung verlängern die Reaktionszeit deutlich. Damit wächst der Reaktionsweg und der gesamte Anhalteweg.",
  }),
  q({
    code: "own-gefahrenlehre-003", topic: "gefahrenlehre", points: 3, difficulty: 0.4, tags: ["ablenkung", "handy", "innerorts"],
    text: "Sie stehen mit laufendem Motor an einer roten Ampel. Dürfen Sie das Smartphone in die Hand nehmen, um eine Nachricht zu lesen?",
    answers: [t("Nein, das Aufnehmen und Halten des Geräts ist bei laufendem Motor verboten"), f("Ja, weil das Fahrzeug steht", "Das Verbot gilt auch im Stand, solange der Motor läuft."), f("Ja, wenn es weniger als zehn Sekunden dauert", "Eine zeitliche Ausnahme gibt es nicht.")],
    explanation: "Ein elektronisches Gerät darf nur benutzt werden, wenn es dafür weder aufgenommen noch gehalten wird. Nur bei stehendem Fahrzeug mit vollständig ausgeschaltetem Motor ist das Halten erlaubt. Ein von der Start-Stopp-Automatik nur vorübergehend abgeschalteter Motor gilt dabei nicht als ausgeschaltet.",
    legalReference: "§ 23 Abs. 1a und 1b StVO",
  }),
  q({
    code: "own-gefahrenlehre-004", topic: "gefahrenlehre", points: 2, difficulty: 0.2, tags: ["anhalteweg", "reaktionsweg", "bremsweg"],
    text: "Woraus setzt sich der Anhalteweg zusammen?",
    answers: [t("Aus Reaktionsweg und Bremsweg"), f("Nur aus dem Bremsweg", "Der Weg während der Reaktionszeit kommt hinzu."), f("Aus Bremsweg und Überholweg", "Der Überholweg hat mit dem Anhalten nichts zu tun.")],
    explanation: "Der Anhalteweg ist die Summe aus dem Reaktionsweg, den das Fahrzeug während der Reaktionszeit zurücklegt, und dem eigentlichen Bremsweg.",
    mnemonic: "Anhalten = Reagieren + Bremsen.",
  }),
  q({
    code: "own-gefahrenlehre-005", topic: "gefahrenlehre", points: 3, difficulty: 0.3, tags: ["toter_winkel", "fahrstreifenwechsel", "verkehrsbeobachtung"],
    text: "Wie stellen Sie vor einem Fahrstreifenwechsel sicher, dass sich kein Fahrzeug im toten Winkel befindet?",
    answers: [t("Durch einen Schulterblick zusätzlich zum Blick in die Spiegel"), f("Nur durch einen Blick in den Innenspiegel", "Der Innenspiegel zeigt den toten Winkel nicht."), f("Durch kurzes Hupen vor dem Wechsel", "Hupen ersetzt keine Verkehrsbeobachtung.")],
    explanation: "Spiegel decken den Bereich schräg neben dem Fahrzeug nicht vollständig ab. Der Schulterblick schließt diese Lücke und gehört zu jedem Fahrstreifenwechsel und Abbiegen.",
  }),
  q({
    code: "own-gefahrenlehre-006", topic: "gefahrenlehre", points: 3, difficulty: 0.4, tags: ["fahranfaenger", "selbstueberschaetzung"],
    text: "Warum haben Fahranfänger ein deutlich erhöhtes Unfallrisiko?",
    answers: [t("Fahraufgaben binden noch viel Aufmerksamkeit, weil die Routine fehlt"), t("Das eigene Können wird häufig überschätzt"), f("Junge Menschen sehen in der Regel schlechter als ältere", "Das Sehvermögen junger Menschen ist im Durchschnitt gut; das Risiko liegt in Erfahrung und Verhalten.")],
    explanation: "Fehlende Routine und Selbstüberschätzung sind die wichtigsten Gründe für das erhöhte Risiko in den ersten Jahren. Deshalb gibt es Probezeit und die Null-Promille-Grenze für Fahranfänger.",
  }),
  q({
    code: "own-gefahrenlehre-007", topic: "gefahrenlehre", points: 3, difficulty: 0.2, tags: ["muedigkeit", "autobahn"],
    text: "Auf einer langen Autobahnfahrt gähnen Sie häufig und die Augenlider werden schwer. Was ist richtig?",
    answers: [t("Die nächste Rastanlage anfahren und eine Pause machen oder schlafen"), f("Fenster öffnen, Radio lauter stellen und weiterfahren", "Das wirkt höchstens kurz und beseitigt die Müdigkeit nicht."), f("Schneller fahren, um früher anzukommen", "Höhere Geschwindigkeit bei Müdigkeit erhöht das Risiko erheblich.")],
    explanation: "Gegen Müdigkeit hilft nur Schlaf oder eine echte Pause. Sekundenschlaf ist eine der häufigsten Ursachen schwerer Unfälle auf Autobahnen.",
  }),
  q({
    code: "own-gefahrenlehre-008", topic: "gefahrenlehre", points: 2, difficulty: 0.2, tags: ["emotionen", "risikofaktor_mensch"],
    text: "Sie setzen sich nach einem heftigen Streit wütend ans Steuer. Wie wirkt sich starke Wut auf das Fahren aus?",
    answers: [t("Die Risikobereitschaft steigt und die Aufmerksamkeit für den Verkehr sinkt"), f("Wut verbessert die Konzentration", "Starke Gefühle lenken von der Fahraufgabe ab."), f("Wut hat keinen Einfluss auf das Fahrverhalten", "Emotionen beeinflussen Wahrnehmung und Entscheidungen deutlich.")],
    explanation: "Starke Emotionen wie Wut oder Trauer verengen die Wahrnehmung und verleiten zu aggressivem Fahren. Besser erst zur Ruhe kommen und dann losfahren.",
  }),
  q({
    code: "own-gefahrenlehre-009", topic: "gefahrenlehre", points: 2, difficulty: 0.3, tags: ["reaktionsweg", "innerorts", "faustformel"], kind: "numeric", numericAnswer: 9, tolerance: 0, unit: "m",
    text: "Wie lang ist der Reaktionsweg bei 30 km/h nach der Faustformel (Geschwindigkeit geteilt durch 10, mal 3)? Angabe in Metern.",
    answers: [],
    explanation: "Reaktionsweg = (30 / 10) × 3 = 9 Meter. In einer Sekunde Reaktionszeit legt das Fahrzeug bei 30 km/h also rund 9 Meter zurück.",
    mnemonic: "Reaktionsweg: Tempo durch 10, mal 3.",
  }),
  q({
    code: "own-gefahrenlehre-010", topic: "gefahrenlehre", points: 2, difficulty: 0.2, tags: ["verkehrsbeobachtung", "blickfuehrung"],
    text: "Wie führen Sie beim Fahren den Blick richtig?",
    answers: [t("Weit voraus, mit regelmäßigem Blick in die Spiegel und zu den Seiten"), f("Ständig auf die Motorhaube und den Fahrbahnrand", "So erkennen Sie Gefahren viel zu spät."), f("Nur auf das Fahrzeug unmittelbar vor Ihnen", "Dann bleibt der weitere Verkehr unbeobachtet.")],
    explanation: "Wer weit vorausschaut, erkennt Gefahren früh und kann rechtzeitig reagieren. Regelmäßige Spiegelblicke halten das Bild vom Verkehr hinter und neben dem Fahrzeug aktuell.",
  }),
  q({
    code: "own-gefahrenlehre-011", topic: "gefahrenlehre", points: 3, difficulty: 0.6, tags: ["anhalteweg", "reaktionsweg", "bremsweg", "faustformel", "innerorts"], kind: "numeric", numericAnswer: 40, tolerance: 0, unit: "m",
    text: "Sie fahren innerorts 50 km/h. Wie lang ist der Anhalteweg nach den Faustformeln bei einer normalen Bremsung? Angabe in Metern.",
    answers: [],
    explanation: "Reaktionsweg = (50 / 10) × 3 = 15 Meter, Bremsweg = (50 / 10)² = 25 Meter. Der Anhalteweg ist die Summe, also 40 Meter. Das ist deutlich mehr als die Länge eines üblichen Zebrastreifenbereichs.",
    mnemonic: "Anhalteweg = Reaktionsweg + Bremsweg.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-gefahrenlehre-012", topic: "gefahrenlehre", points: 3, difficulty: 0.7, tags: ["anhalteweg", "gefahrenbremsung", "faustformel", "ausserorts"], kind: "numeric", numericAnswer: 56, tolerance: 0, unit: "m",
    text: "Sie fahren 80 km/h und müssen eine Gefahrenbremsung durchführen. Wie lang ist der Anhalteweg nach den Faustformeln? Angabe in Metern.",
    answers: [],
    explanation: "Reaktionsweg = (80 / 10) × 3 = 24 Meter. Bremsweg bei Gefahrenbremsung = (80 / 10)² / 2 = 32 Meter. Zusammen ergibt das 56 Meter. Der Reaktionsweg wird durch die Gefahrenbremsung nicht kürzer.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-gefahrenlehre-013", topic: "gefahrenlehre", points: 3, difficulty: 0.65, tags: ["reaktionsweg", "reaktionszeit", "ablenkung", "faustformel"], kind: "numeric", numericAnswer: 60, tolerance: 0, unit: "m",
    text: "Sie fahren 100 km/h. Durch einen Blick auf das Smartphone verlängert sich Ihre Reaktionszeit von 1 auf 2 Sekunden. Wie lang ist dann der Reaktionsweg nach der Faustformel? Angabe in Metern.",
    answers: [],
    explanation: "Die Faustformel (100 / 10) × 3 = 30 Meter gilt für eine Sekunde Reaktionszeit. Bei zwei Sekunden verdoppelt sich der Reaktionsweg auf 60 Meter. Ein kurzer Blick aufs Handy kostet also mehrere Fahrzeuglängen ungebremster Fahrt.",
    legalReference: "§ 3 Abs. 1 StVO; § 23 Abs. 1a StVO",
  }),
  q({
    code: "own-gefahrenlehre-014", topic: "gefahrenlehre", points: 3, difficulty: 0.6, tags: ["bremsweg", "faustformel", "fahrphysik"], kind: "numeric", numericAnswer: 64, tolerance: 0, unit: "m",
    text: "Wie lang ist der Bremsweg bei 80 km/h nach der Faustformel für eine normale Bremsung? Angabe in Metern.",
    answers: [],
    explanation: "Bremsweg = (80 / 10)² = 8 × 8 = 64 Meter. Gegenüber 40 km/h (16 Meter) ist der Bremsweg bei doppelter Geschwindigkeit viermal so lang.",
    mnemonic: "Tempo durch 10, dann mit sich selbst malnehmen.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-gefahrenlehre-015", topic: "gefahrenlehre", points: 3, difficulty: 0.6, tags: ["ablenkung", "handy", "sprachsteuerung"],
    text: "Wie dürfen Sie während der Fahrt ein Smartphone benutzen?",
    answers: [t("Über eine Sprachsteuerung oder Vorlesefunktion, ohne das Gerät aufzunehmen"), t("In einer Halterung, wenn nur eine kurze, den Verkehrsverhältnissen angepasste Blickzuwendung nötig ist"), f("In der Hand, solange Sie nicht telefonieren, sondern nur navigieren", "Aufnehmen oder Halten ist unabhängig vom Zweck verboten."), f("In der Hand, wenn Sie langsamer als 30 km/h fahren", "Eine Geschwindigkeitsgrenze gibt es dafür nicht.")],
    explanation: "Elektronische Geräte dürfen nur benutzt werden, wenn sie weder aufgenommen noch gehalten werden. Zusätzlich muss die Bedienung per Sprachsteuerung oder Vorlesefunktion erfolgen oder nur eine kurze Blickzuwendung erfordern. Das gilt für Handy, Navi und Tablet gleichermaßen.",
    legalReference: "§ 23 Abs. 1a StVO",
  }),
  q({
    code: "own-gefahrenlehre-016", topic: "gefahrenlehre", points: 3, difficulty: 0.7, tags: ["ablenkung", "handy", "probezeit", "punktesystem"],
    text: "Sie befinden sich in der Probezeit und werden mit dem Handy in der Hand am Steuer erwischt. Welche Folgen sind zu erwarten?",
    answers: [t("Ein Bußgeld und ein Punkt im Fahreignungsregister"), t("Die Anordnung eines Aufbauseminars"), t("Die Verlängerung der Probezeit um zwei Jahre auf insgesamt vier Jahre"), f("Der sofortige Entzug der Fahrerlaubnis", "Ein Entzug erfolgt beim ersten Verstoß nicht; er droht erst bei weiteren Verstößen in der Probezeit.")],
    explanation: "Die verbotene Handynutzung kostet 100 Euro und einen Punkt. In der Probezeit zählt sie als schwerwiegender Verstoß (A-Verstoß): Es wird ein Aufbauseminar angeordnet und die Probezeit verlängert sich auf vier Jahre.",
    legalReference: "§ 23 Abs. 1a StVO; § 2a Abs. 2a StVG; BKatV",
  }),
  q({
    code: "own-gefahrenlehre-017", topic: "gefahrenlehre", points: 3, difficulty: 0.55, tags: ["ablenkung", "handy", "start_stopp"],
    text: "Ihr Fahrzeug hat eine Start-Stopp-Automatik. An einer roten Ampel geht der Motor automatisch aus. Dürfen Sie jetzt das Smartphone in die Hand nehmen?",
    answers: [t("Nein, der von der Start-Stopp-Automatik abgeschaltete Motor gilt nicht als ausgeschaltet"), f("Ja, weil der Motor nicht läuft", "Die Ausnahme gilt nur bei vollständig ausgeschaltetem Motor, nicht bei automatischer Abschaltung."), f("Ja, wenn die Ampel länger als eine Minute Rot zeigt", "Eine zeitliche Ausnahme gibt es nicht.")],
    explanation: "Das Handyverbot entfällt nur bei stehendem Fahrzeug mit ausgeschaltetem Motor. Ein Motor, den die Start-Stopp-Automatik nur vorübergehend abschaltet, gilt ausdrücklich nicht als ausgeschaltet.",
    legalReference: "§ 23 Abs. 1b StVO",
  }),
  q({
    code: "own-gefahrenlehre-018", topic: "gefahrenlehre", points: 3, difficulty: 0.6, tags: ["muedigkeit", "sekundenschlaf", "autobahn"],
    text: "Welche Anzeichen deuten auf beginnenden Sekundenschlaf hin?",
    answers: [t("Sie können sich an die letzten Kilometer nicht mehr erinnern"), t("Sie halten die Spur nicht mehr sauber und erschrecken, wenn Sie über die Randmarkierung fahren"), t("Häufiges Gähnen, brennende Augen und Frösteln"), f("Erhöhte Aufmerksamkeit und schnellere Reaktionen", "Müdigkeit verlangsamt die Reaktion und verengt die Wahrnehmung.")],
    explanation: "Erinnerungslücken, Schlangenlinien, Gähnen, brennende Augen und Frösteln sind Warnsignale. Wer sie bemerkt, sollte sofort die nächste Möglichkeit zum Anhalten nutzen und schlafen; Fahrtwind und laute Musik helfen nicht.",
    legalReference: "§ 2 FeV; § 315c StGB",
  }),
  q({
    code: "own-gefahrenlehre-019", topic: "gefahrenlehre", points: 2, difficulty: 0.5, tags: ["muedigkeit", "pause", "risikofaktor_mensch"],
    text: "Welche Maßnahmen beugen Müdigkeit auf langen Fahrten wirksam vor?",
    answers: [t("Ausgeschlafen starten und etwa alle zwei Stunden eine Pause mit Bewegung machen"), t("Schwere Mahlzeiten und Alkohol vor der Fahrt vermeiden"), f("Beim ersten Anzeichen von Müdigkeit das Tempo erhöhen, um schneller anzukommen", "Höhere Geschwindigkeit bei Müdigkeit vergrößert das Risiko erheblich."), f("Die Heizung hoch stellen, damit es gemütlich ist", "Warme, stickige Luft macht zusätzlich müde.")],
    explanation: "Gegen Müdigkeit hilft nur Vorbeugung durch ausreichenden Schlaf und regelmäßige Pausen. Schwere Mahlzeiten, Alkohol und warme Luft im Fahrzeug verstärken die Ermüdung.",
    legalReference: "§ 2 FeV; § 1 StVO",
  }),
  q({
    code: "own-gefahrenlehre-020", topic: "gefahrenlehre", points: 3, difficulty: 0.6, tags: ["sehvermoegen", "nacht", "blendung"],
    text: "Bei Nachtfahrten werden Sie von einem entgegenkommenden Fahrzeug geblendet. Wie verhalten Sie sich?",
    answers: [t("Den Blick auf den rechten Fahrbahnrand richten und die Geschwindigkeit verringern"), t("Bremsbereit bleiben, weil Sie in diesem Moment Hindernisse kaum erkennen können"), f("Direkt in die Scheinwerfer sehen, um den Gegenverkehr besser einschätzen zu können", "Der direkte Blick verstärkt die Blendung."), f("Mit dem Fernlicht zurückblenden", "Zurückblenden blendet den anderen ebenfalls und erhöht die Gefahr für beide.")],
    explanation: "Bei Blendung sollte man den Blick nach rechts unten an den Fahrbahnrand lenken und langsamer werden. Die Augen brauchen nach der Blendung mehrere Sekunden, bis sie sich wieder an die Dunkelheit angepasst haben.",
    legalReference: "§ 17 Abs. 2 StVO; § 3 Abs. 1 StVO",
  }),
  q({
    code: "own-gefahrenlehre-021", topic: "gefahrenlehre", points: 3, difficulty: 0.65, tags: ["sehvermoegen", "nacht", "geschwindigkeit", "abblendlicht"],
    text: "Sie fahren nachts außerorts mit Abblendlicht. Was müssen Sie bei der Wahl der Geschwindigkeit beachten?",
    answers: [t("Sie dürfen nur so schnell fahren, dass Sie innerhalb der ausgeleuchteten Strecke anhalten können"), t("Auf der rechten Fahrbahnseite reicht das Abblendlicht deutlich weiter als auf der linken"), f("Bei Abblendlicht dürfen Sie immer die zulässige Höchstgeschwindigkeit ausfahren", "Die Sichtweite begrenzt die Geschwindigkeit, nicht nur das Verkehrszeichen."), f("Dunkel gekleidete Fußgänger sind mit Abblendlicht ebenso früh erkennbar wie am Tag", "Dunkle Kleidung ist oft erst auf wenige Meter zu erkennen.")],
    explanation: "Grundregel: Nur so schnell fahren, dass innerhalb der übersehbaren Strecke angehalten werden kann. Das Abblendlicht leuchtet die rechte Seite weiter aus als die linke, und unbeleuchtete Hindernisse werden oft erst sehr spät sichtbar.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-gefahrenlehre-022", topic: "gefahrenlehre", points: 3, difficulty: 0.7, tags: ["sehvermoegen", "wahrnehmung", "geschwindigkeit", "tunnelblick"],
    text: "Wie verändert sich die Wahrnehmung mit steigender Geschwindigkeit?",
    answers: [t("Das Blickfeld verengt sich; Vorgänge am Straßenrand werden schlechter wahrgenommen"), t("Der Blick richtet sich weiter nach vorn, Nahbereich und Seiten werden vernachlässigt"), f("Das Blickfeld erweitert sich, weil mehr Reize auf den Fahrer einwirken", "Es ist umgekehrt: Das nutzbare Blickfeld wird kleiner."), f("Entfernungen werden bei hoher Geschwindigkeit genauer eingeschätzt", "Gerade bei hohem Tempo werden Entfernungen und Geschwindigkeiten häufig unterschätzt.")],
    explanation: "Mit steigender Geschwindigkeit verengt sich das nutzbare Blickfeld zum sogenannten Tunnelblick. Der Fahrer sieht weiter nach vorn, nimmt aber Gefahren an den Seiten später oder gar nicht wahr.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-gefahrenlehre-023", topic: "gefahrenlehre", points: 2, difficulty: 0.55, tags: ["sehvermoegen", "sehtest", "fahrerlaubnis"],
    text: "Was gilt für den Sehtest zur Fahrerlaubnis der Klasse B?",
    answers: [t("Er darf bei Antragstellung nicht älter als zwei Jahre sein"), t("Er gilt als bestanden, wenn die Tagessehschärfe mit oder ohne Sehhilfe mindestens 0,7 auf jedem Auge beträgt"), f("Eine Sehhilfe darf beim Sehtest nicht getragen werden", "Der Test darf mit Sehhilfe abgelegt werden; sie ist dann beim Fahren zu tragen."), f("Der Sehtest muss alle fünf Jahre wiederholt werden", "Für Klasse B ist keine regelmäßige Wiederholung vorgeschrieben.")],
    explanation: "Für die Klasse B ist ein Sehtest erforderlich, der bei Antragstellung höchstens zwei Jahre alt sein darf. Bestanden ist er bei einer Tagessehschärfe von mindestens 0,7 auf jedem Auge, mit oder ohne Sehhilfe. Wer nur mit Sehhilfe besteht, muss sie beim Fahren tragen.",
    legalReference: "§ 12 FeV; Anlage 6 FeV",
  }),
  q({
    code: "own-gefahrenlehre-024", topic: "gefahrenlehre", points: 3, difficulty: 0.6, tags: ["daemmerung", "sehvermoegen", "wildwechsel", "ausserorts"],
    text: "Warum ist die Dämmerung für Autofahrer besonders gefährlich?",
    answers: [t("Das Auge muss sich ständig zwischen hellen und dunklen Bereichen umstellen"), t("Kontraste nehmen ab, sodass unbeleuchtete Verkehrsteilnehmer spät erkannt werden"), t("Wild ist in der Dämmerung besonders aktiv"), f("Weil in der Dämmerung immer Nebel entsteht", "Nebel ist von der Wetterlage abhängig, nicht von der Tageszeit.")],
    explanation: "In der Dämmerung sinken Kontraste und die Augen adaptieren ständig. Fußgänger und Radfahrende ohne Licht werden übersehen, und Wildwechsel ist in den Dämmerungsstunden besonders häufig. Deshalb rechtzeitig Licht einschalten und langsamer fahren.",
    legalReference: "§ 17 Abs. 1 StVO",
  }),
  q({
    code: "own-gefahrenlehre-025", topic: "gefahrenlehre", points: 2, difficulty: 0.5, tags: ["hoeren", "musik", "kopfhoerer", "einsatzhorn"],
    text: "Sie hören während der Fahrt sehr laut Musik. Welche Gefahr besteht?",
    answers: [t("Einsatzhorn, Hupen oder ungewöhnliche Fahrzeuggeräusche werden überhört"), f("Keine, weil im Straßenverkehr nur das Sehen zählt", "Auch das Gehör liefert wichtige Warnsignale."), f("Die Musik verkürzt die Reaktionszeit", "Laute Musik lenkt ab und verlängert eher die Reaktionszeit.")],
    explanation: "Das Gehör warnt vor Einsatzfahrzeugen, Hupsignalen und technischen Problemen. Wer das Gehör durch laute Musik oder Kopfhörer beeinträchtigt, nimmt diese Signale zu spät oder gar nicht wahr.",
    legalReference: "§ 23 Abs. 1 StVO",
  }),
  q({
    code: "own-gefahrenlehre-026", topic: "gefahrenlehre", points: 3, difficulty: 0.65, tags: ["gruppendruck", "fahranfaenger", "risikofaktor_mensch", "selbstueberschaetzung"],
    text: "Sie fahren mit drei Freunden im Auto. Diese fordern Sie auf, bei Gelb noch schnell über die Kreuzung zu fahren und danach den Vordermann zu überholen. Wie verhalten Sie sich?",
    answers: [t("Sie fahren so, wie Sie es ohne Mitfahrer auch tun würden, und lassen sich nicht drängen"), t("Sie erklären, dass Sie als Fahrer allein die Verantwortung tragen"), f("Sie fahren schneller, damit die Stimmung nicht kippt", "Gruppendruck ist eine typische Ursache schwerer Unfälle junger Fahrer."), f("Sie bitten den Beifahrer, das Lenkrad kurz zu übernehmen", "Der Fahrer darf die Fahrzeugführung nicht abgeben.")],
    explanation: "Mitfahrer erhöhen bei jungen Fahrern das Unfallrisiko deutlich, wenn sie zu riskantem Fahren animieren. Der Fahrer trägt allein die Verantwortung und muss sich von Gruppendruck freimachen.",
    legalReference: "§ 1 StVO; § 2a StVG",
  }),
  q({
    code: "own-gefahrenlehre-027", topic: "gefahrenlehre", points: 3, difficulty: 0.55, tags: ["fahranfaenger", "probezeit", "alkohol", "risikofaktor_mensch"],
    text: "Welche Regelungen sollen das erhöhte Risiko von Fahranfängern verringern?",
    answers: [t("Die zweijährige Probezeit mit Aufbauseminar bei schwerwiegenden Verstößen"), t("Das Alkoholverbot für Fahranfänger in der Probezeit und für Fahrer unter 21 Jahren"), t("Das Begleitete Fahren ab 17"), f("Eine allgemeine Höchstgeschwindigkeit von 80 km/h für Fahranfänger", "Eine solche Regelung gibt es in Deutschland nicht.")],
    explanation: "Probezeit, Alkoholverbot für Fahranfänger und das Begleitete Fahren ab 17 sollen die besonders unfallträchtigen ersten Jahre sicherer machen. Ein gesondertes Tempolimit für Fahranfänger existiert nicht.",
    legalReference: "§ 2a StVG; § 24c StVG; § 48a FeV",
  }),
  q({
    code: "own-gefahrenlehre-028", topic: "gefahrenlehre", points: 3, difficulty: 0.6, tags: ["toter_winkel", "lkw", "radverkehr", "rechtsabbiegen"],
    text: "Warum ist der tote Winkel bei Lkw besonders gefährlich?",
    answers: [t("Der Bereich rechts neben und direkt vor dem Fahrerhaus ist im Spiegel nicht oder kaum einsehbar"), t("Beim Rechtsabbiegen können Radfahrende und Fußgänger dort übersehen werden"), f("Lkw haben keine Außenspiegel", "Lkw haben mehrere Spiegel, dennoch bleiben Bereiche unsichtbar."), f("Der tote Winkel liegt bei Lkw nur hinter dem Fahrzeug", "Vor allem rechts neben dem Fahrerhaus ist die Sicht eingeschränkt.")],
    explanation: "Trotz mehrerer Spiegel bleiben bei Lkw große Bereiche rechts neben dem Fahrerhaus unsichtbar. Wer als Radfahrer oder Pkw-Fahrer dort steht, wird beim Rechtsabbiegen leicht übersehen. Deshalb Abstand halten und Blickkontakt suchen.",
    legalReference: "§ 9 Abs. 6 StVO; § 1 StVO",
  }),
  q({
    code: "own-gefahrenlehre-029", topic: "gefahrenlehre", points: 3, difficulty: 0.6, tags: ["stress", "zeitdruck", "risikofaktor_mensch"],
    text: "Sie sind spät dran und stehen unter Zeitdruck. Wie wirkt sich das typischerweise auf Ihr Fahren aus?",
    answers: [t("Sie neigen zu knapperen Abständen und riskanteren Überholvorgängen"), t("Sie unterschätzen Gefahren und überschätzen die Zeitersparnis"), f("Zeitdruck verbessert die Konzentration auf das Wesentliche", "Stress verengt die Wahrnehmung und führt zu Fehlentscheidungen."), f("Schnelles Fahren spart innerorts sehr viel Zeit", "Innerorts bestimmen Ampeln und Verkehr die Fahrzeit; Rasen bringt fast nichts.")],
    explanation: "Zeitdruck erhöht die Risikobereitschaft und verschlechtert die Wahrnehmung. Die tatsächliche Zeitersparnis durch schnelleres Fahren ist gerade innerorts minimal, das Unfallrisiko steigt aber erheblich.",
    legalReference: "§ 1 StVO; § 3 Abs. 1 StVO",
  }),
  q({
    code: "own-gefahrenlehre-030", topic: "gefahrenlehre", points: 3, difficulty: 0.7, tags: ["reaktionszeit", "schrecksekunde", "bremsbereitschaft"],
    text: "Sie fahren vorausschauend und haben den Fuß bereits über dem Bremspedal, als ein Kind hinter einem parkenden Auto hervortritt. Welche Wirkung hat die Bremsbereitschaft?",
    answers: [t("Die Reaktionszeit und damit der Reaktionsweg verkürzen sich deutlich"), t("Die Bremsung beginnt früher, sodass die Aufprallgeschwindigkeit sinkt oder der Unfall ganz vermieden wird"), f("Der Bremsweg wird kürzer, weil die Bremsen schneller ansprechen", "Der Bremsweg selbst hängt von Geschwindigkeit, Bremse und Fahrbahn ab, nicht von der Fußstellung."), f("Keine, weil die Reaktionszeit unveränderlich ist", "Bremsbereitschaft spart wertvolle Zehntelsekunden.")],
    explanation: "Bremsbereitschaft verkürzt die Zeit zwischen Erkennen der Gefahr und Beginn der Bremsung. Der Reaktionsweg wird kürzer, die Bremsung setzt früher ein. Der Bremsweg als solcher bleibt bei gleicher Geschwindigkeit gleich.",
    legalReference: "§ 3 Abs. 2a StVO",
  }),
  q({
    code: "own-gefahrenlehre-031", topic: "gefahrenlehre", points: 3, difficulty: 0.55, tags: ["ablenkung", "navigationsgeraet", "beifahrer"],
    text: "Wie vermeiden Sie Ablenkung durch das Navigationsgerät?",
    answers: [t("Das Ziel vor Fahrtbeginn eingeben und unterwegs nur Sprachansagen nutzen"), t("Bei nötigen Änderungen anhalten oder den Beifahrer bedienen lassen"), f("Während der Fahrt das Ziel eingeben, wenn die Straße gerade ist", "Auch auf gerader Straße legt das Fahrzeug bei kurzer Blickabwendung viele Meter blind zurück."), f("Das Gerät auf dem Schoß ablegen, damit es nicht die Sicht behindert", "Es muss so befestigt sein, dass keine Aufnahme nötig ist und der Blick kurz bleibt.")],
    explanation: "Das Navi wird vor der Fahrt programmiert. Unterwegs gelten die gleichen Regeln wie für das Handy: keine Aufnahme, nur kurze Blickzuwendung. Bei längerer Bedienung anhalten.",
    legalReference: "§ 23 Abs. 1a StVO",
  }),
  q({
    code: "own-gefahrenlehre-032", topic: "gefahrenlehre", points: 3, difficulty: 0.6, tags: ["wahrnehmung", "geschwindigkeit", "einschaetzung"],
    text: "Warum wird die eigene Geschwindigkeit nach längerer schneller Autobahnfahrt an der Ausfahrt häufig unterschätzt?",
    answers: [t("Das Geschwindigkeitsgefühl hat sich an das hohe Tempo gewöhnt"), t("Ein Blick auf den Tacho ist deshalb beim Verlassen der Autobahn besonders wichtig"), f("Weil der Tacho bei hoher Geschwindigkeit ungenau wird", "Der Tacho zeigt eher etwas zu viel an, nie zu wenig."), f("Weil die Ausfahrt immer bergab führt", "Das Gefälle spielt für die Gewöhnung keine Rolle.")],
    explanation: "Nach langer schneller Fahrt fühlen sich 80 km/h wie 50 an. Diese Gewöhnung führt in Ausfahrten und auf der anschließenden Landstraße oft zu deutlich überhöhter Geschwindigkeit. Der Tacho ist der einzige verlässliche Maßstab.",
    legalReference: "§ 3 Abs. 1 und 3 StVO",
  }),
  q({
    code: "own-gefahrenlehre-033", topic: "gefahrenlehre", points: 2, difficulty: 0.4, tags: ["medikamente", "risikofaktor_mensch", "reaktionszeit"],
    text: "Sie nehmen ein neues Medikament ein. Worauf müssen Sie vor Fahrtantritt achten?",
    answers: [t("Auf Hinweise im Beipackzettel zur Verkehrstüchtigkeit und auf eigene Reaktionen wie Schläfrigkeit oder Schwindel"), f("Auf nichts, weil ärztlich verordnete Medikamente das Fahren nie beeinträchtigen", "Auch verordnete Mittel wie Schmerz- oder Beruhigungsmittel können die Fahrtüchtigkeit beeinträchtigen."), f("Nur darauf, dass Sie das Medikament nicht mit Alkohol einnehmen", "Auch ohne Alkohol können Nebenwirkungen die Fahrtüchtigkeit beeinträchtigen.")],
    explanation: "Viele Medikamente, auch frei verkäufliche, verlängern die Reaktionszeit oder machen müde. Der Fahrer ist selbst dafür verantwortlich, nur fahrtüchtig zu fahren; im Zweifel den Arzt oder Apotheker fragen.",
    legalReference: "§ 2 FeV; § 24a StVG",
  }),
  q({
    code: "own-gefahrenlehre-034", topic: "gefahrenlehre", points: 3, difficulty: 0.5, tags: ["verkehrsbeobachtung", "spiegel", "blickfuehrung"],
    text: "Wie oft sollten Sie beim Fahren in die Spiegel schauen?",
    answers: [t("Regelmäßig alle paar Sekunden, zusätzlich immer vor dem Bremsen, Abbiegen und Fahrstreifenwechsel"), f("Nur vor dem Abbiegen", "Die Verkehrslage hinter dem Fahrzeug ändert sich ständig."), f("Nur wenn ein Fahrzeug hinter Ihnen hupt", "Dann ist es zu spät für eine vorausschauende Reaktion.")],
    explanation: "Die Verkehrsbeobachtung umfasst auch den Raum hinter und neben dem Fahrzeug. Regelmäßige Spiegelblicke und ein Kontrollblick vor jedem Bremsen, Abbiegen und Wechseln halten das Lagebild aktuell.",
    legalReference: "§ 1 StVO; § 7 Abs. 5 StVO",
  }),
  q({
    code: "own-gefahrenlehre-035", topic: "gefahrenlehre", points: 3, difficulty: 0.6, tags: ["emotionen", "aggression", "risikofaktor_mensch"],
    text: "Ein anderer Fahrer drängelt dicht hinter Ihnen und blendet mit der Lichthupe. Wie verhalten Sie sich richtig?",
    answers: [t("Ruhig bleiben, die Geschwindigkeit beibehalten und bei nächster Gelegenheit vorbeilassen"), f("Abrupt bremsen, um den Drängler zu erziehen", "Absichtliches Ausbremsen ist gefährlich und kann als Nötigung strafbar sein."), f("Beschleunigen, damit der Abstand größer wird", "Sie würden Regeln verletzen und das Risiko für sich erhöhen.")],
    explanation: "Auf Provokationen im Verkehr sollte man nicht mit Gegenaggression reagieren. Gelassen bleiben, Regeln einhalten und den Drängler vorbeilassen ist die sicherste Lösung. Ausbremsen kann eine Straftat sein.",
    legalReference: "§ 1 StVO; § 240 StGB",
  }),
  q({
    code: "own-gefahrenlehre-036", topic: "gefahrenlehre", points: 3, difficulty: 0.65, tags: ["gefahrenbremsung", "abs", "reaktionszeit"],
    text: "Wie führen Sie mit einem Fahrzeug mit ABS eine Gefahrenbremsung richtig durch?",
    answers: [t("Bremspedal sofort mit voller Kraft treten und gedrückt halten"), t("Gleichzeitig kuppeln, damit der Motor nicht abwürgt und die Bremskraft voll wirkt"), t("Dabei weiter lenken, weil das Fahrzeug mit ABS lenkbar bleibt"), f("Das Bremspedal mehrfach kurz antippen, um ein Blockieren zu verhindern", "Das Stotterbremsen ist mit ABS falsch; das System regelt selbst.")],
    explanation: "Bei der Gefahrenbremsung wird mit voller Kraft gebremst und gekuppelt. Das ABS verhindert das Blockieren der Räder, sodass das Fahrzeug lenkbar bleibt. Ein Pulsieren im Pedal ist normal und kein Grund, den Druck zu verringern.",
    legalReference: "§ 1 Abs. 2 StVO",
  }),
  q({
    code: "own-gefahrenlehre-037", topic: "gefahrenlehre", points: 3, difficulty: 0.7, tags: ["bremsweg", "geschwindigkeit", "aufprallgeschwindigkeit", "fahrphysik"],
    text: "Zwei Fahrzeuge fahren nebeneinander, eines mit 50 km/h, eines mit 70 km/h. Beide bremsen im selben Moment gleich stark. Das langsamere kommt gerade noch vor einem Hindernis zum Stehen. Was gilt für das schnellere Fahrzeug?",
    answers: [t("Es trifft das Hindernis mit einer noch sehr hohen Geschwindigkeit, weil der Bremsweg mit dem Quadrat der Geschwindigkeit wächst"), f("Es kommt ebenfalls gerade noch zum Stehen, weil die Differenz nur 20 km/h beträgt", "Bei 70 km/h beträgt allein der Bremsweg 49 Meter statt 25 Meter bei 50 km/h."), f("Es trifft das Hindernis mit etwa 20 km/h", "Die Aufprallgeschwindigkeit ist deutlich höher, weil auch der Reaktionsweg länger ist.")],
    explanation: "Bei 50 km/h beträgt der Anhalteweg nach Faustformel 40 Meter, bei 70 km/h dagegen 70 Meter. Nach 40 Metern hat das schnellere Fahrzeug erst 19 Meter seines 49 Meter langen Bremswegs zurückgelegt und trifft das Hindernis noch mit über 50 km/h. Kleine Tempounterschiede haben große Folgen.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-gefahrenlehre-038", topic: "gefahrenlehre", points: 3, difficulty: 0.55, tags: ["verkehrsbeobachtung", "defensiv", "vorausschauend"],
    text: "Was bedeutet vorausschauendes und defensives Fahren?",
    answers: [t("Mit Fehlern anderer rechnen und sich Handlungsspielraum für eigene Reaktionen bewahren"), t("Auf das eigene Recht verzichten, wenn dadurch eine gefährliche Situation vermieden wird"), f("Immer langsamer als erlaubt fahren", "Defensiv heißt angepasst, nicht grundsätzlich langsam; unnötig langsames Fahren behindert."), f("Andere durch Hupen auf ihre Fehler aufmerksam machen", "Das ist weder defensiv noch erlaubt.")],
    explanation: "Defensives Fahren heißt, Gefahren früh zu erkennen, Reserven einzuplanen und notfalls auf die eigene Vorfahrt zu verzichten. Wer so fährt, vermeidet Unfälle, auch wenn andere Fehler machen.",
    legalReference: "§ 1 StVO",
  }),
  q({
    code: "own-gefahrenlehre-039", topic: "gefahrenlehre", points: 3, difficulty: 0.6, tags: ["kinder", "wahrnehmung", "innerorts", "bremsbereitschaft"],
    text: "Warum müssen Sie bei Kindern am Fahrbahnrand mit ganz anderem Verhalten rechnen als bei Erwachsenen?",
    answers: [t("Kinder können Geschwindigkeiten und Entfernungen noch nicht sicher einschätzen"), t("Kinder sind klein und werden hinter parkenden Fahrzeugen leicht übersehen"), t("Kinder reagieren spontan, etwa wenn ein Ball auf die Straße rollt"), f("Kinder haben ein besseres Gehör und hören Fahrzeuge deshalb früher", "Kinder können Geräusche im Verkehr schlechter zuordnen und lassen sich leicht ablenken.")],
    explanation: "Kinder nehmen den Verkehr anders wahr, handeln spontan und sind wegen ihrer Körpergröße schlecht sichtbar. Gegenüber Kindern muss sich der Fahrer durch Geschwindigkeitsverringerung und Bremsbereitschaft so verhalten, dass eine Gefährdung ausgeschlossen ist.",
    legalReference: "§ 3 Abs. 2a StVO",
  }),
  q({
    code: "own-gefahrenlehre-040", topic: "gefahrenlehre", points: 3, difficulty: 0.75, tags: ["anhalteweg", "faustformel", "gefahrenbremsung", "innerorts"], kind: "numeric", numericAnswer: 36, tolerance: 0, unit: "m",
    text: "Sie fahren 60 km/h und führen eine Gefahrenbremsung durch. Wie lang ist der Anhalteweg nach den Faustformeln? Angabe in Metern.",
    answers: [],
    explanation: "Reaktionsweg = (60 / 10) × 3 = 18 Meter. Bremsweg bei Gefahrenbremsung = (60 / 10)² / 2 = 36 / 2 = 18 Meter. Der Anhalteweg beträgt somit 36 Meter.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
];
