// Übungsfragen zum Thema "geschwindigkeit" (eigene Formulierungen, kein amtlicher Prüfungsinhalt).
import type { Question } from "../types";
import { q, t, f } from "./_helpers";

export const geschwindigkeit: readonly Question[] = [
  q({
    code: "own-geschwindigkeit-001", topic: "geschwindigkeit", points: 2, difficulty: 0.1, tags: ["innerorts", "hoechstgeschwindigkeit"],
    text: "Welche Höchstgeschwindigkeit gilt innerhalb geschlossener Ortschaften für Pkw, wenn keine Verkehrszeichen etwas anderes anordnen?",
    answers: [t("50 km/h"), f("30 km/h", "Das gilt nur in ausgeschilderten Zonen oder Abschnitten."), f("60 km/h", "Die allgemeine Grenze innerorts liegt niedriger.")],
    explanation: "Innerhalb geschlossener Ortschaften gilt für alle Kraftfahrzeuge eine Höchstgeschwindigkeit von 50 km/h, sofern keine Zeichen etwas anderes anordnen.",
    legalReference: "§ 3 Abs. 3 Nr. 1 StVO",
  }),
  q({
    code: "own-geschwindigkeit-002", topic: "geschwindigkeit", points: 2, difficulty: 0.1, tags: ["ausserorts", "hoechstgeschwindigkeit"],
    text: "Welche Höchstgeschwindigkeit gilt für Pkw ohne Anhänger auf Landstraßen außerhalb geschlossener Ortschaften?",
    answers: [t("100 km/h"), f("80 km/h", "Das gilt für Pkw mit Anhänger und für Lkw."), f("130 km/h", "Das ist die Richtgeschwindigkeit auf Autobahnen.")],
    explanation: "Außerhalb geschlossener Ortschaften dürfen Pkw ohne Anhänger höchstens 100 km/h fahren, wenn keine Zeichen etwas anderes anordnen.",
    legalReference: "§ 3 Abs. 3 Nr. 2 StVO",
  }),
  q({
    code: "own-geschwindigkeit-003", topic: "geschwindigkeit", points: 3, difficulty: 0.4, tags: ["anhaenger", "ausserorts", "autobahn"],
    text: "Wie schnell dürfen Sie mit einem Pkw mit Anhänger außerorts und auf der Autobahn höchstens fahren?",
    answers: [t("80 km/h; 100 km/h nur mit entsprechender Zulassung des Gespanns (Tempo-100-Plakette)"), f("Immer 100 km/h", "Ohne besondere Zulassung gilt 80 km/h."), f("130 km/h auf der Autobahn", "Für Gespanne gilt auch auf der Autobahn eine feste Grenze.")],
    explanation: "Pkw mit Anhänger dürfen außerorts und auf Autobahnen höchstens 80 km/h fahren. 100 km/h sind nur erlaubt, wenn das Gespann dafür zugelassen ist und die Plakette am Anhänger angebracht ist.",
    legalReference: "§ 3 Abs. 3 Nr. 2 StVO; § 18 Abs. 5 StVO",
  }),
  q({
    code: "own-geschwindigkeit-004", topic: "geschwindigkeit", points: 3, difficulty: 0.2, tags: ["abstand", "halber_tacho", "autobahn"], kind: "numeric", numericAnswer: 50, tolerance: 0, unit: "m",
    text: "Sie fahren 100 km/h. Wie groß sollte der Sicherheitsabstand nach der Regel halber Tacho mindestens sein? Angabe in Metern.",
    answers: [],
    explanation: "Halber Tacho bedeutet: Bei 100 km/h mindestens 50 Meter Abstand. Das entspricht dem Abstand zweier Leitpfosten auf der Autobahn.",
    mnemonic: "Abstand halber Tacho.",
    legalReference: "§ 4 Abs. 1 StVO",
  }),
  q({
    code: "own-geschwindigkeit-005", topic: "geschwindigkeit", points: 3, difficulty: 0.3, tags: ["bremsweg", "innerorts", "faustformel"], kind: "numeric", numericAnswer: 25, tolerance: 0, unit: "m",
    text: "Wie lang ist der Bremsweg bei 50 km/h nach der Faustformel für eine normale Bremsung? Angabe in Metern.",
    answers: [],
    explanation: "Bremsweg = (50 / 10)² = 5 × 5 = 25 Meter. Bei doppelter Geschwindigkeit wird der Bremsweg viermal so lang.",
    mnemonic: "Bremsweg: Tempo durch 10, dann quadrieren.",
  }),
  q({
    code: "own-geschwindigkeit-006", topic: "geschwindigkeit", points: 3, difficulty: 0.4, tags: ["anhalteweg", "reaktionsweg", "bremsweg", "ausserorts"], kind: "numeric", numericAnswer: 130, tolerance: 0, unit: "m",
    text: "Wie lang ist der Anhalteweg bei 100 km/h nach den Faustformeln (normale Bremsung)? Angabe in Metern.",
    answers: [],
    explanation: "Reaktionsweg = (100 / 10) × 3 = 30 Meter, Bremsweg = (100 / 10)² = 100 Meter. Zusammen ergibt das einen Anhalteweg von 130 Metern.",
  }),
  q({
    code: "own-geschwindigkeit-007", topic: "geschwindigkeit", points: 3, difficulty: 0.4, tags: ["bremsweg", "gefahrenbremsung", "faustformel"], kind: "numeric", numericAnswer: 50, tolerance: 0, unit: "m",
    text: "Wie lang ist der Bremsweg bei 100 km/h bei einer Gefahrenbremsung nach der Faustformel? Angabe in Metern.",
    answers: [],
    explanation: "Bei der Gefahrenbremsung wird der normale Bremsweg halbiert: (100 / 10)² / 2 = 50 Meter. Der Reaktionsweg von 30 Metern kommt beim Anhalteweg noch hinzu.",
  }),
  q({
    code: "own-geschwindigkeit-008", topic: "geschwindigkeit", points: 3, difficulty: 0.3, tags: ["bremsweg", "fahrphysik"],
    text: "Sie verdoppeln Ihre Geschwindigkeit. Wie verändert sich der Bremsweg?",
    answers: [t("Er wird etwa viermal so lang"), f("Er wird doppelt so lang", "Der Bremsweg wächst mit dem Quadrat der Geschwindigkeit."), f("Er bleibt gleich, nur der Reaktionsweg wächst", "Beide Teile des Anhaltewegs wachsen.")],
    explanation: "Der Bremsweg wächst mit dem Quadrat der Geschwindigkeit. Doppelte Geschwindigkeit bedeutet vierfacher Bremsweg, der Reaktionsweg verdoppelt sich nur.",
  }),
  q({
    code: "own-geschwindigkeit-009", topic: "geschwindigkeit", points: 3, difficulty: 0.3, tags: ["nebel", "sichtweite", "hoechstgeschwindigkeit"],
    text: "Bei Nebel beträgt die Sichtweite weniger als 50 Meter. Wie schnell dürfen Sie höchstens fahren?",
    answers: [t("Höchstens 50 km/h, wenn nicht eine noch geringere Geschwindigkeit geboten ist"), f("Höchstens 80 km/h", "Bei so geringer Sicht ist die Grenze niedriger."), f("Die allgemeine Höchstgeschwindigkeit gilt unverändert", "Bei Sichtweiten unter 50 Metern gilt eine besondere Grenze.")],
    explanation: "Beträgt die Sichtweite durch Nebel, Schneefall oder Regen weniger als 50 Meter, darf nicht schneller als 50 km/h gefahren werden. Grundsätzlich darf man nur so schnell fahren, dass man innerhalb der übersehbaren Strecke anhalten kann.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-geschwindigkeit-010", topic: "geschwindigkeit", points: 2, difficulty: 0.2, tags: ["abstand", "ausserorts", "zwei_sekunden"],
    text: "Welche Faustregel hilft außerorts, den Sicherheitsabstand zum Vorausfahrenden zu prüfen?",
    answers: [t("Die Zwei-Sekunden-Regel: Mindestens zwei Sekunden Abstand zu einem festen Punkt, den das vorausfahrende Fahrzeug passiert hat"), f("Die Halbe-Sekunde-Regel", "Eine halbe Sekunde reicht nicht einmal für die Reaktionszeit."), f("Die Fünf-Sekunden-Regel für alle Geschwindigkeiten", "Fünf Sekunden sind eine Empfehlung bei schlechten Bedingungen, nicht die allgemeine Regel.")],
    explanation: "Passiert der Vorausfahrende einen festen Punkt, sollten mindestens zwei Sekunden vergehen, bis man selbst dort ankommt. Bei Nässe oder Glätte deutlich mehr.",
    legalReference: "§ 4 Abs. 1 StVO",
  }),
  q({
    code: "own-geschwindigkeit-011", topic: "geschwindigkeit", points: 2, difficulty: 0.4, tags: ["abstand", "lkw", "autobahn"],
    text: "Welchen Mindestabstand müssen Lkw über 3,5 t auf Autobahnen bei mehr als 50 km/h zum Vorausfahrenden einhalten?",
    answers: [t("50 Meter"), f("25 Meter", "Für schwere Fahrzeuge ist der vorgeschriebene Abstand größer."), f("100 Meter", "Der gesetzliche Mindestabstand ist geringer.")],
    explanation: "Lkw über 3,5 t und Kraftomnibusse müssen auf Autobahnen bei mehr als 50 km/h einen Abstand von mindestens 50 Metern halten. Das hilft auch Pkw-Fahrern, Lkw-Kolonnen richtig einzuschätzen.",
    legalReference: "§ 4 Abs. 3 StVO",
  }),
  q({
    code: "own-geschwindigkeit-012", topic: "geschwindigkeit", points: 2, difficulty: 0.2, tags: ["reaktionsweg", "ausserorts", "faustformel"], kind: "numeric", numericAnswer: 30, tolerance: 0, unit: "m",
    text: "Wie lang ist der Reaktionsweg bei 100 km/h nach der Faustformel? Angabe in Metern.",
    answers: [],
    explanation: "Reaktionsweg = (100 / 10) × 3 = 30 Meter. Diese Strecke legt das Fahrzeug zurück, bevor die Bremsung überhaupt beginnt.",
  }),
  q({
    code: "own-geschwindigkeit-013", topic: "geschwindigkeit", points: 3, difficulty: 0.65, tags: ["zusatzzeichen", "naesse", "hoechstgeschwindigkeit", "autobahn"],
    text: "Auf der Autobahn steht das Zeichen 274 mit 80 km/h und dem Zusatzzeichen „bei Nässe“. Es hat vor einer Stunde geregnet, die Fahrbahn ist noch feucht, aber ohne Wasserfilm. Was gilt?",
    answers: [t("Die Beschränkung gilt nicht, weil Nässe erst vorliegt, wenn die Fahrbahn mit einem Wasserfilm bedeckt ist"), t("Trotzdem sollten Sie die Geschwindigkeit an die verminderte Haftung der feuchten Fahrbahn anpassen"), f("Die Beschränkung gilt, weil die Fahrbahn nicht trocken ist", "Feuchtigkeit allein ist keine Nässe im Sinne des Zusatzzeichens."), f("Die Beschränkung gilt immer, wenn es am selben Tag geregnet hat", "Maßgeblich ist der Zustand der Fahrbahn, nicht das Wetter des Tages.")],
    explanation: "Nässe im Sinne des Zusatzzeichens liegt vor, wenn die Fahrbahn mit einem durchgehenden Wasserfilm bedeckt ist. Eine nur feuchte Fahrbahn löst die Beschränkung nicht aus, verlangt aber trotzdem angepasste Geschwindigkeit nach § 3.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 274 mit Zusatzzeichen 1053-35); § 3 Abs. 1 StVO",
  }),
  q({
    code: "own-geschwindigkeit-014", topic: "geschwindigkeit", points: 3, difficulty: 0.6, tags: ["zusatzzeichen", "zeitliche_beschraenkung", "hoechstgeschwindigkeit", "innerorts"],
    text: "Vor einer Schule steht das Zeichen 274 mit 30 km/h und dem Zusatzzeichen „Mo-Fr 7-17 h“. Sie fahren am Samstag um 10 Uhr vorbei. Wie schnell dürfen Sie fahren?",
    answers: [t("Höchstens 50 km/h, weil die Beschränkung am Wochenende nicht gilt und innerorts 50 km/h die Grenze ist"), f("Höchstens 30 km/h, weil das Zeichen dort steht", "Das Zusatzzeichen beschränkt die Geltung auf die angegebenen Zeiten."), f("Höchstens 30 km/h, weil vor Schulen immer 30 gilt", "Ein solches allgemeines Gesetz gibt es nicht.")],
    explanation: "Zusatzzeichen mit Zeitangaben beschränken die Geltung des Hauptzeichens auf diese Zeiten. Außerhalb davon gilt die allgemeine Regel, innerorts also 50 km/h. Vorsicht bleibt geboten, weil Kinder auch am Wochenende unterwegs sind.",
    legalReference: "§ 39 Abs. 3 StVO; § 41 StVO (Zeichen 274); § 3 Abs. 3 Nr. 1 StVO",
  }),
  q({
    code: "own-geschwindigkeit-015", topic: "geschwindigkeit", points: 3, difficulty: 0.65, tags: ["gefahrzeichen", "baustelle", "ende_der_beschraenkung", "hoechstgeschwindigkeit"],
    text: "Vor einer Baustelle stehen das Gefahrzeichen 123 (Arbeitsstelle) und darunter das Zeichen 274 mit 30 km/h. Hinter der Baustelle steht kein Aufhebungszeichen. Wie lange gilt die Beschränkung?",
    answers: [t("Bis zum Ende der Baustelle, weil sie mit dem Gefahrzeichen zusammen angeordnet ist"), f("Bis zur nächsten Kreuzung oder Einmündung", "Kreuzungen beenden eine Beschränkung nicht automatisch."), f("Bis zum nächsten Ortsschild", "Das Ende ergibt sich hier aus dem Ende der Gefahrstelle."), f("Sie gilt unbegrenzt weiter, weil kein Aufhebungszeichen steht", "Bei Anordnung mit einem Gefahrzeichen endet die Beschränkung mit der Gefahr.")],
    explanation: "Wird eine Geschwindigkeitsbeschränkung zusammen mit einem Gefahrzeichen angeordnet, gilt sie nur für die Gefahrstelle und endet, wo die Gefahr erkennbar nicht mehr besteht. Ein Aufhebungszeichen ist dann nicht nötig.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 274); § 40 StVO",
  }),
  q({
    code: "own-geschwindigkeit-016", topic: "geschwindigkeit", points: 3, difficulty: 0.6, tags: ["zusatzzeichen", "streckenlaenge", "ende_der_beschraenkung"],
    text: "Ein Zeichen 274 mit 70 km/h trägt das Zusatzzeichen „2 km“. Was bedeutet das?",
    answers: [t("Die Beschränkung gilt ab dem Zeichen auf einer Strecke von 2 km und endet dann ohne Aufhebungszeichen"), f("Die Beschränkung beginnt erst in 2 km Entfernung", "Ein Entfernungshinweis würde „in 2 km“ oder ein Zusatzzeichen mit Pfeil verwenden; „2 km“ gibt die Länge an."), f("Nach 2 km wird die Beschränkung wiederholt", "Die Angabe beschreibt die Länge der Strecke.")],
    explanation: "Ein Zusatzzeichen mit Längenangabe legt fest, wie lang die Strecke ist, für die das Verbot gilt. Danach endet die Beschränkung automatisch. Ein Zusatzzeichen „in 2 km“ würde dagegen die Entfernung bis zum Beginn angeben.",
    legalReference: "§ 39 Abs. 3 StVO; § 41 StVO (Zeichen 274 mit Zusatzzeichen zur Streckenlänge)",
  }),
  q({
    code: "own-geschwindigkeit-017", topic: "geschwindigkeit", points: 3, difficulty: 0.55, tags: ["ende_der_beschraenkung", "aufhebung", "verkehrszeichen"],
    text: "Wodurch kann eine durch Zeichen 274 angeordnete Geschwindigkeitsbeschränkung enden?",
    answers: [t("Durch das Zeichen 278 (Ende der Höchstgeschwindigkeit) oder das Zeichen 282 (Ende aller Streckenverbote)"), t("Durch ein neues Zeichen 274 mit anderem Wert"), t("Durch die Ortstafel, hinter der die allgemeine Grenze von 50 km/h gilt, wenn sie niedriger ist"), f("Automatisch nach 500 Metern", "Ohne Längenangabe gibt es keine feste Strecke.")],
    explanation: "Streckenverbote enden durch das zugehörige Aufhebungszeichen, durch das Zeichen Ende aller Streckenverbote oder durch eine neue Anordnung. An der Ortstafel gilt anschließend die innerörtliche Grenze von 50 km/h, sofern kein Zeichen etwas anderes anordnet.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 274, 278, 282); § 3 Abs. 3 StVO",
  }),
  q({
    code: "own-geschwindigkeit-018", topic: "geschwindigkeit", points: 3, difficulty: 0.7, tags: ["schmale_fahrbahn", "sichtweite", "gegenverkehr", "ausserorts"],
    text: "Sie fahren auf einer schmalen Landstraße, auf der Ihnen entgegenkommende Fahrzeuge nur mit Mühe ausweichen können. Was gilt für Ihre Geschwindigkeit?",
    answers: [t("Sie müssen innerhalb der Hälfte der übersehbaren Strecke anhalten können"), f("Sie müssen innerhalb der übersehbaren Strecke anhalten können", "Auf schmalen Fahrbahnen gilt die strengere Regel der halben Sichtweite."), f("Es gilt ohne Einschränkung die zulässige Höchstgeschwindigkeit von 100 km/h", "Die Sichtweite kann eine deutlich niedrigere Geschwindigkeit erfordern.")],
    explanation: "Auf so schmalen Fahrbahnen, dass entgegenkommende Fahrzeuge gefährdet werden könnten, muss innerhalb der Hälfte der übersehbaren Strecke angehalten werden können. So können beide Fahrzeuge rechtzeitig anhalten, bevor sie sich treffen.",
    legalReference: "§ 3 Abs. 1 Satz 5 StVO",
  }),
  q({
    code: "own-geschwindigkeit-019", topic: "geschwindigkeit", points: 3, difficulty: 0.6, tags: ["abstand", "halber_tacho", "autobahn"], kind: "numeric", numericAnswer: 65, tolerance: 0, unit: "m",
    text: "Sie fahren auf der Autobahn 130 km/h. Wie groß sollte der Sicherheitsabstand nach der Regel halber Tacho mindestens sein? Angabe in Metern.",
    answers: [],
    explanation: "Halber Tacho: 130 / 2 = 65 Meter. Das entspricht etwas mehr als dem Abstand zweier Leitpfosten. Bei Nässe oder schlechter Sicht ist der Abstand zu vergrößern.",
    legalReference: "§ 4 Abs. 1 StVO",
  }),
  q({
    code: "own-geschwindigkeit-020", topic: "geschwindigkeit", points: 3, difficulty: 0.65, tags: ["anhalteweg", "gefahrenbremsung", "faustformel", "ausserorts"], kind: "numeric", numericAnswer: 80, tolerance: 0, unit: "m",
    text: "Sie fahren 100 km/h und führen eine Gefahrenbremsung durch. Wie lang ist der gesamte Anhalteweg nach den Faustformeln? Angabe in Metern.",
    answers: [],
    explanation: "Reaktionsweg = (100 / 10) × 3 = 30 Meter. Bremsweg bei Gefahrenbremsung = (100 / 10)² / 2 = 50 Meter. Zusammen 80 Meter. Auch bei einer Vollbremsung legt das Fahrzeug also weit mehr als die Länge eines Fußballfelds zurück.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-geschwindigkeit-021", topic: "geschwindigkeit", points: 2, difficulty: 0.5, tags: ["anhalteweg", "faustformel", "innerorts", "zone_30"], kind: "numeric", numericAnswer: 18, tolerance: 0, unit: "m",
    text: "In einer Tempo-30-Zone fahren Sie 30 km/h. Wie lang ist der Anhalteweg bei normaler Bremsung nach den Faustformeln? Angabe in Metern.",
    answers: [],
    explanation: "Reaktionsweg = (30 / 10) × 3 = 9 Meter, Bremsweg = (30 / 10)² = 9 Meter. Der Anhalteweg beträgt 18 Meter, bei 50 km/h wären es bereits 40 Meter. Deshalb ist Tempo 30 in Wohngebieten so wirksam.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-geschwindigkeit-022", topic: "geschwindigkeit", points: 3, difficulty: 0.7, tags: ["anhalteweg", "faustformel", "vergleich", "innerorts"],
    text: "Ein Kind läuft 25 Meter vor Ihnen auf die Straße. Mit 30 km/h könnten Sie bei normaler Bremsung rechtzeitig anhalten. Was passiert bei 50 km/h?",
    answers: [t("Sie erreichen das Kind noch mit fast unverminderter Geschwindigkeit, weil bei 50 km/h allein der Reaktionsweg 15 Meter beträgt und der Bremsweg 25 Meter"), f("Sie kommen ebenfalls rechtzeitig zum Stehen, weil der Unterschied nur 20 km/h beträgt", "Der Anhalteweg bei 50 km/h beträgt 40 Meter, also deutlich mehr als 25 Meter."), f("Sie treffen das Kind mit etwa 10 km/h", "Nach 25 Metern haben Sie erst 10 Meter gebremst und sind noch sehr schnell.")],
    explanation: "Bei 30 km/h beträgt der Anhalteweg 18 Meter, bei 50 km/h 40 Meter. Nach 25 Metern hat das Fahrzeug bei 50 km/h gerade erst 10 Meter gebremst und ist noch sehr schnell. Kleine Unterschiede in der Geschwindigkeit entscheiden über schwere Verletzungen.",
    legalReference: "§ 3 Abs. 1 und 2a StVO",
  }),
  q({
    code: "own-geschwindigkeit-023", topic: "geschwindigkeit", points: 3, difficulty: 0.6, tags: ["mindestgeschwindigkeit", "verkehrszeichen", "autobahn"],
    text: "Was bedeutet das Zeichen 275 (Vorgeschriebene Mindestgeschwindigkeit, blauer Kreis mit weißer Zahl)?",
    answers: [t("Sie dürfen nicht langsamer als die angegebene Geschwindigkeit fahren, sofern Straßen-, Verkehrs-, Sicht- und Wetterverhältnisse das zulassen"), t("Fahrzeuge, die diese Geschwindigkeit nicht erreichen können, dürfen den Fahrstreifen oder die Straße nicht benutzen"), f("Sie müssen die angegebene Geschwindigkeit immer einhalten, auch bei Glätte", "Bei schlechten Bedingungen geht die angepasste Geschwindigkeit vor."), f("Es handelt sich um eine Höchstgeschwindigkeit", "Die Höchstgeschwindigkeit wird durch das rote Zeichen 274 angeordnet.")],
    explanation: "Das blaue Zeichen 275 schreibt eine Mindestgeschwindigkeit vor, damit langsame Fahrzeuge den Verkehr nicht behindern. Es gilt nur, soweit die Verhältnisse das sichere Fahren mit dieser Geschwindigkeit erlauben.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 275)",
  }),
  q({
    code: "own-geschwindigkeit-024", topic: "geschwindigkeit", points: 3, difficulty: 0.65, tags: ["abstand", "mindestabstand", "lkw", "verkehrszeichen"],
    text: "Das Zeichen 273 zeigt zwei Fahrzeuge hintereinander mit der Angabe „70 m“. Für wen gilt es?",
    answers: [t("Für Kraftfahrzeuge über 3,5 t und für Kraftomnibusse; sie dürfen den Abstand von 70 m nicht unterschreiten"), f("Für alle Fahrzeuge, auch Pkw", "Das Zeichen richtet sich nur an schwere Fahrzeuge."), f("Nur für Fahrzeuge mit gefährlicher Ladung", "Es gilt für alle Kraftfahrzeuge über 3,5 t und Busse.")],
    explanation: "Zeichen 273 verbietet Kraftfahrzeugen über 3,5 t und Kraftomnibussen, den angegebenen Mindestabstand zu unterschreiten. Für Pkw gilt weiterhin der allgemeine Sicherheitsabstand, zum Beispiel halber Tacho.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 273); § 4 StVO",
  }),
  q({
    code: "own-geschwindigkeit-025", topic: "geschwindigkeit", points: 3, difficulty: 0.6, tags: ["abstand", "bremsen", "vorausfahren", "auffahrunfall"],
    text: "Welche Pflichten haben Sie beim Fahren in einer Kolonne?",
    answers: [t("Der Abstand zum Vorausfahrenden muss so groß sein, dass Sie auch bei plötzlichem Bremsen dahinter anhalten können"), t("Als Vorausfahrender dürfen Sie nicht ohne zwingenden Grund stark bremsen"), f("Bei dichtem Verkehr darf der Sicherheitsabstand unterschritten werden, damit niemand einschert", "Der Abstand ist unabhängig vom Verkehrsaufkommen einzuhalten."), f("Der Hintermann ist bei einem Auffahrunfall nie schuld, wenn der Vordermann stark bremst", "Der Hintermann muss mit plötzlichem Bremsen rechnen; nur grundloses starkes Bremsen kann eine Mithaftung des Vordermanns auslösen.")],
    explanation: "Der Abstand muss so groß sein, dass auch bei plötzlichem Bremsen des Vorausfahrenden hinter ihm angehalten werden kann. Umgekehrt darf der Vorausfahrende nicht ohne zwingenden Grund stark bremsen.",
    legalReference: "§ 4 Abs. 1 StVO",
  }),
  q({
    code: "own-geschwindigkeit-026", topic: "geschwindigkeit", points: 3, difficulty: 0.6, tags: ["nebel", "nebelschlussleuchte", "sichtweite", "hoechstgeschwindigkeit"],
    text: "Sie haben wegen Nebels die Nebelschlussleuchte eingeschaltet. Was folgt daraus für Ihre Geschwindigkeit?",
    answers: [t("Sie dürfen höchstens 50 km/h fahren, weil die Nebelschlussleuchte nur bei Sichtweite unter 50 m eingeschaltet werden darf"), f("Es gilt die normale Höchstgeschwindigkeit", "Bei Sichtweiten unter 50 Metern gilt die Grenze von 50 km/h."), f("Sie dürfen höchstens 80 km/h fahren", "Die Grenze liegt bei 50 km/h.")],
    explanation: "Die Nebelschlussleuchte darf nur bei Sichtweiten unter 50 Metern benutzt werden. Bei so geringer Sicht gilt zugleich die Höchstgeschwindigkeit von 50 km/h. Wer die Leuchte eingeschaltet hat, darf also nicht schneller fahren.",
    legalReference: "§ 17 Abs. 3 StVO; § 3 Abs. 1 StVO",
  }),
  q({
    code: "own-geschwindigkeit-027", topic: "geschwindigkeit", points: 3, difficulty: 0.55, tags: ["schneeketten", "winter", "hoechstgeschwindigkeit"],
    text: "Sie haben Schneeketten aufgezogen. Wie schnell dürfen Sie höchstens fahren?",
    answers: [t("Höchstens 50 km/h, auch wenn Verkehrszeichen mehr erlauben"), f("So schnell, wie die Verkehrszeichen es zulassen", "Für Fahrzeuge mit Schneeketten gilt eine eigene Grenze."), f("Höchstens 30 km/h", "Die Grenze liegt bei 50 km/h.")],
    explanation: "Mit Schneeketten darf nicht schneller als 50 km/h gefahren werden. Das gilt auch, wenn Verkehrszeichen eine höhere Geschwindigkeit erlauben. Die Ketten müssen abgenommen werden, sobald die Straße schneefrei ist.",
    legalReference: "§ 3 Abs. 4 StVO",
  }),
  q({
    code: "own-geschwindigkeit-028", topic: "geschwindigkeit", points: 3, difficulty: 0.65, tags: ["anhaenger", "innerorts", "ausserorts", "hoechstgeschwindigkeit"],
    text: "Sie fahren mit Pkw und Anhänger. Welche Höchstgeschwindigkeiten gelten, wenn keine Zeichen etwas anderes anordnen?",
    answers: [t("Innerorts 50 km/h"), t("Außerorts und auf Autobahnen 80 km/h"), t("100 km/h auf Autobahnen und Kraftfahrstraßen nur mit Tempo-100-Zulassung und Plakette"), f("Auf Autobahnen die Richtgeschwindigkeit 130 km/h", "Für Gespanne gelten feste Höchstgeschwindigkeiten.")],
    explanation: "Gespanne aus Pkw und Anhänger dürfen innerorts 50 km/h und außerorts sowie auf Autobahnen 80 km/h fahren. Nur mit Tempo-100-Zulassung dürfen sie auf Autobahnen und Kraftfahrstraßen 100 km/h fahren.",
    legalReference: "§ 3 Abs. 3 StVO; § 18 Abs. 5 StVO",
  }),
  q({
    code: "own-geschwindigkeit-029", topic: "geschwindigkeit", points: 3, difficulty: 0.6, tags: ["ortstafel", "innerorts", "ausserorts", "hoechstgeschwindigkeit"],
    text: "Vor der Ortstafel gilt durch Zeichen 274 eine Beschränkung auf 70 km/h. Sie passieren die Ortstafel; dahinter steht kein weiteres Zeichen. Wie schnell dürfen Sie fahren?",
    answers: [t("Höchstens 50 km/h, weil ab der Ortstafel die innerörtliche Grenze gilt"), f("Weiterhin 70 km/h, weil kein Aufhebungszeichen stand", "Die Ortstafel setzt die innerörtliche Grenze von 50 km/h in Kraft, die niedriger ist."), f("100 km/h, weil die Beschränkung endet", "Innerorts gilt 50 km/h.")],
    explanation: "Ab der Ortstafel gilt innerorts die allgemeine Höchstgeschwindigkeit von 50 km/h. Sie ist niedriger als die vorher angeordneten 70 km/h und gilt daher ab dem Ortseingang.",
    legalReference: "§ 3 Abs. 3 Nr. 1 StVO; Zeichen 310",
  }),
  q({
    code: "own-geschwindigkeit-030", topic: "geschwindigkeit", points: 3, difficulty: 0.6, tags: ["ortstafel", "ausserorts", "hoechstgeschwindigkeit", "ortsausgang"],
    text: "Sie passieren die Rückseite der Ortstafel (Zeichen 311, Ortsausgang). Dahinter steht kein Geschwindigkeitszeichen. Was gilt für Ihren Pkw?",
    answers: [t("Sie dürfen jetzt höchstens 100 km/h fahren, wenn die Verhältnisse das zulassen"), f("Es gelten weiterhin 50 km/h bis zum nächsten Zeichen", "Mit dem Ortsausgang endet die innerörtliche Grenze."), f("Es gilt die Richtgeschwindigkeit 130 km/h", "Auf Landstraßen gilt für Pkw 100 km/h.")],
    explanation: "Mit der Rückseite der Ortstafel endet die geschlossene Ortschaft. Für Pkw gilt außerorts die allgemeine Grenze von 100 km/h, sofern kein Zeichen etwas anderes anordnet und Straße, Sicht und Wetter es zulassen.",
    legalReference: "§ 3 Abs. 3 Nr. 2 StVO; Zeichen 311",
  }),
  q({
    code: "own-geschwindigkeit-031", topic: "geschwindigkeit", points: 3, difficulty: 0.7, tags: ["bussgeld", "fahrverbot", "innerorts", "punktesystem"],
    text: "Sie werden innerorts mit 31 km/h zu viel gemessen. Welche Folgen sind nach dem Bußgeldkatalog zu erwarten?",
    answers: [t("Ein Bußgeld, zwei Punkte und ein Monat Fahrverbot"), f("Nur ein Verwarnungsgeld ohne Punkte", "Ab 21 km/h zu viel gibt es innerorts mindestens einen Punkt."), f("Ein Punkt, aber kein Fahrverbot", "Ab 31 km/h zu viel innerorts ist ein Fahrverbot vorgesehen.")],
    explanation: "Innerorts droht ab 31 km/h Überschreitung ein Monat Fahrverbot, zwei Punkte und ein Bußgeld. Außerorts liegt die Schwelle für das Fahrverbot bei 41 km/h. In der Probezeit ist bereits eine Überschreitung ab 21 km/h ein A-Verstoß.",
    legalReference: "BKatV; § 25 StVG",
  }),
  q({
    code: "own-geschwindigkeit-032", topic: "geschwindigkeit", points: 3, difficulty: 0.65, tags: ["probezeit", "bussgeld", "punktesystem", "hoechstgeschwindigkeit"],
    text: "Sie befinden sich in der Probezeit und überschreiten die Höchstgeschwindigkeit außerorts um 25 km/h. Welche Folgen hat das?",
    answers: [t("Ein Bußgeld und ein Punkt"), t("Ein Aufbauseminar und die Verlängerung der Probezeit, weil eine Überschreitung ab 21 km/h ein A-Verstoß ist"), f("Nur ein Verwarnungsgeld, weil 25 km/h eine geringe Überschreitung ist", "Ab 21 km/h gibt es einen Punkt."), f("Ein Fahrverbot von einem Monat", "Außerorts droht ein Fahrverbot erst ab 41 km/h Überschreitung.")],
    explanation: "Eine Überschreitung um mehr als 20 km/h wird mit Bußgeld und einem Punkt geahndet. In der Probezeit zählt sie als schwerwiegender Verstoß: Aufbauseminar und Verlängerung der Probezeit um zwei Jahre.",
    legalReference: "BKatV; § 2a StVG; Anlage 12 FeV",
  }),
  q({
    code: "own-geschwindigkeit-033", topic: "geschwindigkeit", points: 3, difficulty: 0.55, tags: ["richtgeschwindigkeit", "autobahn", "verkehrszeichen"],
    text: "Auf einer Autobahn steht das blaue Zeichen 380 mit der Zahl 130. Was bedeutet es?",
    answers: [t("Eine Richtgeschwindigkeit: Es wird empfohlen, nicht schneller als 130 km/h zu fahren"), f("Eine Mindestgeschwindigkeit von 130 km/h", "Mindestgeschwindigkeiten stehen im blauen Kreis, nicht im Quadrat."), f("Eine verbindliche Höchstgeschwindigkeit", "Höchstgeschwindigkeiten stehen im roten Ring.")],
    explanation: "Das quadratische blaue Zeichen 380 zeigt eine Richtgeschwindigkeit an. Sie ist eine Empfehlung, keine Grenze. Auf Autobahnen gilt die Richtgeschwindigkeit 130 km/h auch ohne dieses Zeichen.",
    legalReference: "§ 42 StVO, Anlage 3 (Zeichen 380); Autobahn-Richtgeschwindigkeits-Verordnung",
  }),
  q({
    code: "own-geschwindigkeit-034", topic: "geschwindigkeit", points: 3, difficulty: 0.6, tags: ["zone_30", "rechts_vor_links", "innerorts", "verkehrszeichen"],
    text: "Sie fahren in eine Tempo-30-Zone (Zeichen 274.1) ein. Was ist richtig?",
    answers: [t("Die Beschränkung auf 30 km/h gilt für alle Straßen innerhalb der Zone bis zum Zeichen 274.2"), t("An den Kreuzungen in der Zone gilt in der Regel rechts vor links"), f("Die Beschränkung endet an jeder Kreuzung und muss neu angeordnet werden", "Zonenregelungen gelten flächendeckend bis zum Ende der Zone."), f("Es gilt Schrittgeschwindigkeit", "Schrittgeschwindigkeit gilt nur im verkehrsberuhigten Bereich.")],
    explanation: "Die Tempo-30-Zone gilt ab dem Zeichen 274.1 für das gesamte Gebiet bis zum Zeichen 274.2. Innerhalb der Zone sind die Kreuzungen in der Regel nicht durch Vorfahrtzeichen geregelt, sodass rechts vor links gilt.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 274.1 und 274.2); § 8 StVO",
  }),
  q({
    code: "own-geschwindigkeit-035", topic: "geschwindigkeit", points: 3, difficulty: 0.6, tags: ["angepasste_geschwindigkeit", "kinder", "bremsbereitschaft", "innerorts"],
    text: "Innerorts gilt 50 km/h. In welchen Situationen müssen Sie trotzdem deutlich langsamer fahren?",
    answers: [t("Wenn Kinder oder ältere Menschen am Fahrbahnrand sind"), t("Wenn parkende Fahrzeuge die Sicht auf den Gehweg verdecken"), t("Bei Nässe, Glätte oder schlechter Sicht"), f("Nie, weil 50 km/h die vorgeschriebene Geschwindigkeit ist", "50 km/h ist eine Höchstgrenze, keine Vorgabe; die angepasste Geschwindigkeit geht vor.")],
    explanation: "Die zulässige Höchstgeschwindigkeit ist eine Obergrenze. Die Geschwindigkeit muss immer den Straßen-, Verkehrs-, Sicht- und Wetterverhältnissen angepasst sein; gegenüber Kindern und älteren Menschen gilt besondere Rücksicht durch Verringerung der Geschwindigkeit und Bremsbereitschaft.",
    legalReference: "§ 3 Abs. 1 und 2a StVO",
  }),
  q({
    code: "own-geschwindigkeit-036", topic: "geschwindigkeit", points: 3, difficulty: 0.55, tags: ["langsam_fahren", "behinderung", "ausserorts"],
    text: "Dürfen Sie auf einer Landstraße ohne Grund mit 40 km/h fahren, obwohl 100 km/h erlaubt sind?",
    answers: [t("Nein, ohne triftigen Grund darf nicht so langsam gefahren werden, dass der Verkehrsfluss behindert wird"), f("Ja, langsames Fahren ist immer sicher und deshalb erlaubt", "Grundloses Langsamfahren provoziert riskante Überholmanöver."), f("Ja, solange Sie den Warnblinker einschalten", "Der Warnblinker rechtfertigt kein grundloses Langsamfahren.")],
    explanation: "Wer ohne triftigen Grund so langsam fährt, dass er den Verkehrsfluss behindert, handelt ordnungswidrig. Wer aus gutem Grund langsam fahren muss, sollte nachfolgenden Fahrzeugen das Überholen erleichtern.",
    legalReference: "§ 3 Abs. 2 StVO",
  }),
  q({
    code: "own-geschwindigkeit-037", topic: "geschwindigkeit", points: 3, difficulty: 0.65, tags: ["lkw", "ausserorts", "hoechstgeschwindigkeit", "andere_fahrzeuge"],
    text: "Welche Höchstgeschwindigkeit gilt außerorts (außer auf Autobahnen) für Lkw mit einer zulässigen Gesamtmasse über 7,5 t?",
    answers: [t("60 km/h"), f("80 km/h", "80 km/h gilt außerorts für Lkw über 3,5 t bis 7,5 t sowie für Pkw mit Anhänger."), f("100 km/h", "Das gilt nur für Pkw und Kraftfahrzeuge bis 3,5 t ohne Anhänger.")],
    explanation: "Außerhalb geschlossener Ortschaften gelten für Lkw über 3,5 t bis 7,5 t 80 km/h und für Lkw über 7,5 t 60 km/h. Das ist auch für Pkw-Fahrer wichtig, um Überholvorgänge und Kolonnen richtig einzuschätzen.",
    legalReference: "§ 3 Abs. 3 Nr. 2 StVO",
  }),
  q({
    code: "own-geschwindigkeit-038", topic: "geschwindigkeit", points: 3, difficulty: 0.6, tags: ["abstand", "zwei_sekunden", "naesse", "ausserorts"],
    text: "Sie fahren bei starkem Regen auf einer Landstraße hinter einem Lkw. Welcher Abstand ist angemessen?",
    answers: [t("Deutlich mehr als bei trockener Fahrbahn, weil der Bremsweg auf nasser Fahrbahn länger ist und die Gischt die Sicht verschlechtert"), t("Mindestens der Abstand, den Sie in zwei Sekunden zurücklegen; bei Nässe eher drei Sekunden"), f("Der gleiche Abstand wie bei trockener Fahrbahn, weil der Lkw ohnehin langsamer bremst", "Nässe verlängert auch Ihren Bremsweg; die Gischt verschlechtert die Sicht."), f("Ein möglichst geringer Abstand, um im Windschatten Kraftstoff zu sparen", "Zu dichtes Auffahren ist gefährlich und verboten.")],
    explanation: "Bei Nässe verlängert sich der Bremsweg, und die Gischt des Vorausfahrenden verringert die Sicht. Der Sicherheitsabstand muss deshalb größer sein als bei trockener Fahrbahn. Die Zwei-Sekunden-Regel ist das Minimum.",
    legalReference: "§ 4 Abs. 1 StVO; § 3 Abs. 1 StVO",
  }),
  q({
    code: "own-geschwindigkeit-039", topic: "geschwindigkeit", points: 3, difficulty: 0.55, tags: ["fahrradstrasse", "innerorts", "hoechstgeschwindigkeit"],
    text: "Sie dürfen mit dem Pkw eine Fahrradstraße befahren, weil ein Zusatzzeichen das erlaubt. Wie schnell dürfen Sie höchstens fahren?",
    answers: [t("30 km/h, und Sie müssen sich bei Bedarf dem Tempo des Radverkehrs anpassen"), f("50 km/h wie sonst innerorts", "In Fahrradstraßen gilt eine Höchstgeschwindigkeit von 30 km/h."), f("Schrittgeschwindigkeit", "Schrittgeschwindigkeit gilt im verkehrsberuhigten Bereich, nicht in der Fahrradstraße.")],
    explanation: "In Fahrradstraßen gilt für alle Fahrzeuge 30 km/h. Der Radverkehr darf weder gefährdet noch behindert werden; wenn nötig, muss der Kraftfahrzeugverkehr die Geschwindigkeit weiter verringern.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 244.1)",
  }),
  q({
    code: "own-geschwindigkeit-040", topic: "geschwindigkeit", points: 3, difficulty: 0.7, tags: ["reaktionsweg", "bremsweg", "verdopplung", "fahrphysik"],
    text: "Sie erhöhen Ihre Geschwindigkeit von 50 km/h auf 100 km/h. Welche Aussagen zu den Faustformeln sind richtig?",
    answers: [t("Der Reaktionsweg verdoppelt sich von 15 auf 30 Meter"), t("Der Bremsweg vervierfacht sich von 25 auf 100 Meter"), t("Der Anhalteweg steigt von 40 auf 130 Meter, also auf mehr als das Dreifache"), f("Der Anhalteweg verdoppelt sich genau", "Wegen des quadratisch wachsenden Bremswegs steigt der Anhalteweg stärker als die Geschwindigkeit.")],
    explanation: "Der Reaktionsweg wächst proportional zur Geschwindigkeit, der Bremsweg mit ihrem Quadrat. Bei Verdopplung von 50 auf 100 km/h steigt der Anhalteweg von 40 auf 130 Meter.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-geschwindigkeit-041", topic: "geschwindigkeit", points: 3, difficulty: 0.6, tags: ["zusatzzeichen", "lkw", "hoechstgeschwindigkeit", "verkehrszeichen"],
    text: "Ein Zeichen 274 mit 60 km/h trägt ein Zusatzzeichen mit einem Lkw-Symbol und der Angabe „3,5 t“. Was gilt für Ihren Pkw?",
    answers: [t("Die Beschränkung gilt nur für Kraftfahrzeuge über 3,5 t; für Ihren Pkw gilt die allgemeine Grenze"), f("Auch Ihr Pkw darf höchstens 60 km/h fahren", "Das Zusatzzeichen beschränkt die Geltung auf schwere Fahrzeuge."), f("Ihr Pkw darf die Straße nicht befahren", "Das Zeichen ist kein Verbot, sondern eine Geschwindigkeitsbeschränkung.")],
    explanation: "Ein Zusatzzeichen mit Fahrzeugsymbol beschränkt die Geltung des Hauptzeichens auf die dargestellte Fahrzeugart. Für Pkw bleibt die allgemeine Höchstgeschwindigkeit maßgeblich, angepasst an die Verhältnisse.",
    legalReference: "§ 39 Abs. 3 StVO; § 41 StVO (Zeichen 274)",
  }),
  q({
    code: "own-geschwindigkeit-042", topic: "geschwindigkeit", points: 2, difficulty: 0.45, tags: ["bremsweg", "faustformel", "innerorts"], kind: "numeric", numericAnswer: 9, tolerance: 0, unit: "m",
    text: "Wie lang ist der Bremsweg bei 30 km/h nach der Faustformel für eine normale Bremsung? Angabe in Metern.",
    answers: [],
    explanation: "Bremsweg = (30 / 10)² = 3 × 3 = 9 Meter. Bei 50 km/h sind es bereits 25 Meter, fast das Dreifache.",
    mnemonic: "Tempo durch 10, dann quadrieren.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
];
