// Übungsfragen zum Thema "halten_parken" (eigene Formulierungen, kein amtlicher Prüfungsinhalt).
import type { Question } from "../types";
import { q, t, f } from "./_helpers";

export const haltenParken: readonly Question[] = [
  q({
    code: "own-halten_parken-001", topic: "halten_parken", points: 2, difficulty: 0.2, tags: ["halten", "parken"],
    text: "Wann gilt das Abstellen eines Fahrzeugs als Parken?",
    answers: [t("Wenn das Fahrzeug verlassen wird oder länger als drei Minuten hält"), f("Erst ab 15 Minuten", "Die Grenze liegt bei drei Minuten."), f("Nur wenn der Motor abgestellt wird", "Entscheidend sind Dauer und Verlassen des Fahrzeugs, nicht der Motor.")],
    explanation: "Wer sein Fahrzeug verlässt oder länger als drei Minuten hält, parkt. Halten ist eine gewollte Fahrtunterbrechung, die nicht durch die Verkehrslage oder eine Anordnung veranlasst ist.",
    legalReference: "§ 12 Abs. 2 StVO",
  }),
  q({
    code: "own-halten_parken-002", topic: "halten_parken", points: 3, difficulty: 0.2, tags: ["parken", "kreuzung", "innerorts"], kind: "numeric", numericAnswer: 5, tolerance: 0, unit: "m",
    text: "Bis zu wie viel Meter vor und hinter den Schnittpunkten der Fahrbahnkanten einer Kreuzung ist das Parken verboten? Angabe in Metern.",
    answers: [],
    explanation: "Das Parken ist bis zu fünf Meter von den Schnittpunkten der Fahrbahnkanten an Kreuzungen und Einmündungen unzulässig, damit die Sicht frei bleibt.",
    legalReference: "§ 12 Abs. 3 Nr. 1 StVO",
  }),
  q({
    code: "own-halten_parken-003", topic: "halten_parken", points: 3, difficulty: 0.4, tags: ["parken", "kreuzung", "radweg"], kind: "numeric", numericAnswer: 8, tolerance: 0, unit: "m",
    text: "Neben der Fahrbahn ist ein Radweg baulich angelegt. Bis zu wie viel Meter vor der Kreuzung ist das Parken dann verboten? Angabe in Metern.",
    answers: [],
    explanation: "Ist neben der Fahrbahn ein Radweg baulich angelegt, gilt seit 2020 ein Parkverbot bis acht Meter vor den Schnittpunkten der Fahrbahnkanten, damit Radfahrende besser gesehen werden.",
    legalReference: "§ 12 Abs. 3 Nr. 1 StVO",
  }),
  q({
    code: "own-halten_parken-004", topic: "halten_parken", points: 3, difficulty: 0.3, tags: ["halten", "halteverbot"],
    text: "Wo ist bereits das Halten verboten?",
    answers: [t("An engen und an unübersichtlichen Straßenstellen"), t("Im Bereich scharfer Kurven"), t("Auf Bahnübergängen"), f("In Tempo-30-Zonen", "Dort gelten nur die allgemeinen Halte- und Parkregeln.")],
    explanation: "Das Halten ist unter anderem an engen und unübersichtlichen Stellen, in scharfen Kurven, auf Bahnübergängen, auf Fußgängerüberwegen und bis fünf Meter davor sowie vor und in Feuerwehrzufahrten verboten.",
    legalReference: "§ 12 Abs. 1 StVO",
  }),
  q({
    code: "own-halten_parken-005", topic: "halten_parken", points: 2, difficulty: 0.3, tags: ["parken", "haltestelle"], kind: "numeric", numericAnswer: 15, tolerance: 0, unit: "m",
    text: "Bis zu wie viel Meter vor und hinter dem Haltestellenschild (Zeichen 224) ist das Parken verboten? Angabe in Metern.",
    answers: [],
    explanation: "Vor und hinter dem Haltestellenzeichen ist das Parken jeweils bis 15 Meter verboten, damit Busse und Straßenbahnen die Haltestelle anfahren können.",
    legalReference: "§ 12 Abs. 3 Nr. 4 StVO",
  }),
  q({
    code: "own-halten_parken-006", topic: "halten_parken", points: 2, difficulty: 0.3, tags: ["parkscheibe", "parken"],
    text: "Sie kommen um 10:10 Uhr an einem Parkplatz mit Parkscheibenpflicht an. Welche Zeit stellen Sie ein?",
    answers: [t("10:30 Uhr, also die auf die Ankunft folgende halbe Stunde"), f("10:00 Uhr, abgerundet", "Es wird auf die nächste halbe Stunde aufgerundet, nicht abgerundet."), f("Genau 10:10 Uhr", "Die Parkscheibe wird auf halbe Stunden eingestellt.")],
    explanation: "Der Zeiger der Parkscheibe ist auf den Strich der halben Stunde zu stellen, die dem Ankunftszeitpunkt folgt. Bei Ankunft um 10:10 Uhr also auf 10:30 Uhr.",
    legalReference: "§ 13 Abs. 2 StVO",
  }),
  q({
    code: "own-halten_parken-007", topic: "halten_parken", points: 3, difficulty: 0.3, tags: ["parken", "sichern", "gefaelle"],
    text: "Wie sichern Sie Ihr Fahrzeug beim Parken an einem Gefälle gegen Wegrollen?",
    answers: [t("Feststellbremse anziehen"), t("Gang einlegen beziehungsweise Wählhebel auf P stellen"), t("Lenkung zum Bordstein hin einschlagen"), f("Warnblinklicht einschalten", "Das Warnblinklicht sichert nicht gegen Wegrollen.")],
    explanation: "Beim Verlassen des Fahrzeugs muss es gegen Wegrollen gesichert werden: Feststellbremse, eingelegter Gang oder Stellung P, und an Gefälle oder Steigung zusätzlich eingeschlagene Lenkung.",
    legalReference: "§ 14 Abs. 2 StVO",
  }),
  q({
    code: "own-halten_parken-008", topic: "halten_parken", points: 3, difficulty: 0.4, tags: ["parken", "linke_seite", "einbahnstrasse"],
    text: "Wann dürfen Sie am linken Fahrbahnrand halten oder parken?",
    answers: [t("In Einbahnstraßen"), t("Wenn rechts Schienen liegen"), f("Immer, wenn rechts kein Platz ist", "Platzmangel rechts erlaubt kein Linksparken.")],
    explanation: "Grundsätzlich wird rechts gehalten und geparkt. Links ist es nur in Einbahnstraßen erlaubt oder wenn auf der rechten Seite Schienen liegen.",
    legalReference: "§ 12 Abs. 4 StVO",
  }),
  q({
    code: "own-halten_parken-009", topic: "halten_parken", points: 3, difficulty: 0.3, tags: ["parken", "grundstuecksausfahrt"],
    text: "Was gilt für das Parken vor Grundstücksein- und -ausfahrten?",
    answers: [t("Davor ist das Parken verboten; auf schmalen Fahrbahnen auch gegenüber"), f("Parken ist erlaubt, wenn die Ausfahrt zum eigenen Grundstück gehört", "Auch der Berechtigte darf dort nicht parken, wenn dadurch andere Ausfahrten blockiert werden; die Regel gilt allgemein."), f("Nur das Halten ist verboten", "Halten ist erlaubt, das Parken ist verboten.")],
    explanation: "Vor Grundstücksein- und -ausfahrten darf nicht geparkt werden, auf schmalen Fahrbahnen auch nicht gegenüber. Kurzes Halten bleibt erlaubt.",
    legalReference: "§ 12 Abs. 3 Nr. 3 StVO",
  }),
  q({
    code: "own-halten_parken-010", topic: "halten_parken", points: 3, difficulty: 0.4, tags: ["halten", "schutzstreifen", "radverkehr"],
    text: "Dürfen Sie auf einem Schutzstreifen für den Radverkehr (gestrichelte Linie mit Fahrradsymbol) halten?",
    answers: [t("Nein, auf Schutzstreifen ist das Halten verboten"), f("Ja, bis zu drei Minuten", "Seit 2020 ist auf Schutzstreifen jedes Halten verboten."), f("Ja, zum Be- und Entladen", "Auch dafür darf der Schutzstreifen nicht genutzt werden.")],
    explanation: "Auf Schutzstreifen für den Radverkehr ist das Halten verboten. Bei Bedarf dürfen Kraftfahrzeuge nur vorübergehend auf den Schutzstreifen ausweichen, etwa bei Gegenverkehr.",
    legalReference: "§ 12 Abs. 1 StVO; Zeichen 340",
  }),
  q({
    code: "own-halten_parken-011", topic: "halten_parken", points: 2, difficulty: 0.2, tags: ["parken", "behindertenparkplatz"],
    text: "Wer darf auf einem mit Rollstuhlsymbol gekennzeichneten Parkplatz parken?",
    answers: [t("Nur Personen mit einem gültigen, sichtbar ausgelegten blauen Parkausweis für schwerbehinderte Menschen"), f("Jeder, wenn der Platz kurz genutzt wird", "Auch kurzes Parken ist dort unzulässig."), f("Jeder mit einem Schwerbehindertenausweis, auch ohne Parkausweis", "Entscheidend ist der spezielle Parkausweis, nicht der Schwerbehindertenausweis.")],
    explanation: "Behindertenparkplätze sind ausschließlich für Inhaber des blauen EU-Parkausweises. Der Ausweis muss gut lesbar hinter der Windschutzscheibe liegen.",
    legalReference: "§ 45 Abs. 1b StVO; § 46 StVO",
  }),
  q({
    code: "own-halten_parken-012", topic: "halten_parken", points: 2, difficulty: 0.4, tags: ["parken", "bahnuebergang", "andreaskreuz", "innerorts", "ausserorts"],
    text: "In welchem Abstand vor und hinter dem Andreaskreuz ist das Parken verboten?",
    answers: [t("Innerorts bis 5 Meter, außerorts bis 50 Meter"), f("Innerorts und außerorts jeweils 10 Meter", "Die Abstände unterscheiden sich je nach Ortslage."), f("Innerorts bis 15 Meter, außerorts bis 100 Meter", "Diese Werte sind zu groß.")],
    explanation: "Vor und hinter Andreaskreuzen ist das Parken innerorts bis fünf Meter und außerorts bis 50 Meter verboten, damit das Zeichen sichtbar bleibt.",
    legalReference: "§ 12 Abs. 3 Nr. 7 StVO",
  }),
  q({
    code: "own-halten_parken-013", topic: "halten_parken", points: 3, difficulty: 0.6, tags: ["halten", "halteverbot", "zeichen_283", "panne"],
    text: "Im Bereich des Zeichens 283 (absolutes Halteverbot) bleibt Ihr Fahrzeug mit einem Motorschaden liegen. Was gilt?",
    answers: [t("Das ist kein Halten im Sinne der StVO, weil die Fahrtunterbrechung nicht gewollt ist"), t("Sie müssen das Fahrzeug unverzüglich absichern und so schnell wie möglich entfernen lassen"), f("Sie begehen einen Halteverstoß und müssen mit einem Bußgeld rechnen", "Halten ist eine gewollte Fahrtunterbrechung; eine Panne ist es nicht."), f("Sie dürfen das Fahrzeug bis zum nächsten Werktag stehen lassen", "Ein liegen gebliebenes Fahrzeug im Halteverbot muss so schnell wie möglich entfernt werden.")],
    explanation: "Halten ist eine gewollte Fahrtunterbrechung, die nicht durch die Verkehrslage oder eine Anordnung veranlasst ist. Eine Panne erzwingt den Stillstand und ist deshalb kein Halten. Das Fahrzeug ist aber abzusichern und ohne Verzögerung zu entfernen, weil es an dieser Stelle behindert oder gefährdet.",
    legalReference: "§ 12 Abs. 1 StVO; § 15 StVO; Zeichen 283",
  }),
  q({
    code: "own-halten_parken-014", topic: "halten_parken", points: 3, difficulty: 0.6, tags: ["halten", "zeichen_286", "beladen"],
    text: "Bei Zeichen 286 (eingeschränktes Halteverbot) tragen Sie zehn Minuten lang ohne Unterbrechung Umzugskartons aus dem Auto in das Haus. Ist das erlaubt?",
    answers: [t("Ja, Be- und Entladen ist auch länger als drei Minuten erlaubt, wenn es ohne Verzögerung erfolgt"), f("Nein, im eingeschränkten Halteverbot gilt eine feste Grenze von drei Minuten für jeden Zweck", "Ein- und Aussteigen sowie Be- und Entladen dürfen auch länger dauern, solange keine Unterbrechung entsteht."), f("Ja, aber nur mit eingeschaltetem Warnblinklicht", "Das Warnblinklicht ist hier weder nötig noch vorgesehen.")],
    explanation: "Im eingeschränkten Halteverbot darf bis zu drei Minuten gehalten werden. Zum Ein- oder Aussteigen und zum Be- oder Entladen darf auch länger gehalten werden, wenn dies ohne Verzögerung geschieht. Wer zwischendurch die Kartons auspackt oder einen Kaffee trinkt, parkt unzulässig.",
    legalReference: "Anlage 2 StVO, Zeichen 286",
  }),
  q({
    code: "own-halten_parken-015", topic: "halten_parken", points: 3, difficulty: 0.6, tags: ["halten", "halteverbot", "fussgaengerueberweg"], kind: "numeric", numericAnswer: 5, tolerance: 0, unit: "m",
    text: "Bis zu wie viel Meter vor einem Fußgängerüberweg (Zebrastreifen) ist bereits das Halten verboten? Angabe in Metern.",
    answers: [],
    explanation: "Auf dem Fußgängerüberweg und bis zu fünf Meter davor ist das Halten verboten, damit wartende Fußgänger und der Überweg für den Verkehr sichtbar bleiben. Hinter dem Überweg gibt es keine besondere Halteverbotsstrecke.",
    legalReference: "Anlage 2 StVO, Zeichen 293",
  }),
  q({
    code: "own-halten_parken-016", topic: "halten_parken", points: 3, difficulty: 0.7, tags: ["parken", "lichtzeichen", "sicht"], kind: "numeric", numericAnswer: 10, tolerance: 0, unit: "m",
    text: "Ihr Fahrzeug würde eine Ampel für den nachfolgenden Verkehr verdecken. Bis zu wie viel Meter vor dem Lichtzeichen ist das Parken dann verboten? Angabe in Metern.",
    answers: [],
    explanation: "Vor Lichtzeichen sowie vor den Zeichen 205, 206, 229 und 350 ist das Parken bis zu zehn Meter verboten, wenn das Zeichen durch das parkende Fahrzeug verdeckt würde. Entscheidend ist also die Verdeckung, nicht allein die Entfernung.",
    legalReference: "§ 12 Abs. 3 StVO",
  }),
  q({
    code: "own-halten_parken-017", topic: "halten_parken", points: 3, difficulty: 0.6, tags: ["parken", "gehweg", "zeichen_315"], kind: "numeric", numericAnswer: 2.8, tolerance: 0, unit: "t",
    text: "Bis zu welcher zulässigen Gesamtmasse dürfen Kraftfahrzeuge auf dem Gehweg parken, wenn dies durch Zeichen 315 erlaubt ist? Angabe in Tonnen.",
    answers: [],
    explanation: "Gehwegparken ist nur dort erlaubt, wo es durch Zeichen 315 oder eine Parkflächenmarkierung freigegeben ist, und dann nur für Kraftfahrzeuge mit einer zulässigen Gesamtmasse bis 2,8 Tonnen. Schwerere Fahrzeuge würden den Gehweg beschädigen.",
    legalReference: "§ 12 Abs. 4a StVO; Zeichen 315",
  }),
  q({
    code: "own-halten_parken-018", topic: "halten_parken", points: 3, difficulty: 0.65, tags: ["parken", "anhaenger", "frist"],
    text: "Sie stellen Ihren Wohnwagen ohne Zugfahrzeug am Straßenrand vor dem Haus ab. Was gilt?",
    answers: [t("Der Anhänger darf dort höchstens zwei Wochen ohne Zugfahrzeug parken"), f("Der Anhänger darf unbegrenzt stehen, solange er angemeldet ist", "Für Anhänger ohne Zugfahrzeug gilt eine Frist von zwei Wochen."), f("Anhänger dürfen ohne Zugfahrzeug grundsätzlich nicht auf öffentlichen Straßen parken", "Sie dürfen parken, aber nicht länger als zwei Wochen."), f("Die Frist beträgt drei Tage", "Die Frist beträgt zwei Wochen.")],
    explanation: "Anhänger ohne Zugfahrzeug dürfen nicht länger als zwei Wochen geparkt werden. Das gilt nicht auf entsprechend gekennzeichneten Parkplätzen. Ein kurzes Wegfahren und Wiederabstellen umgeht die Regel nicht, wenn es nur zum Schein erfolgt.",
    legalReference: "§ 12 Abs. 3b StVO",
  }),
  q({
    code: "own-halten_parken-019", topic: "halten_parken", points: 3, difficulty: 0.55, tags: ["parken", "parklücke", "vorrang"],
    text: "Sie fahren an einer Parklücke vorbei, um rückwärts einzuparken. Ein nachfolgender Fahrer fährt vorwärts hinein. Wer hatte Vorrang?",
    answers: [t("Sie, weil der Vorrang erhalten bleibt, wenn man an der Lücke vorbeifährt, um rückwärts einzuparken"), f("Der andere Fahrer, weil er die Lücke zuerst tatsächlich belegt hat", "Wer die Lücke zuerst unmittelbar erreicht, hat Vorrang, auch wenn er zum Rückwärtseinparken vorbeifährt."), f("Niemand, an Parklücken gilt kein Vorrang", "Die StVO regelt den Vorrang an Parklücken ausdrücklich.")],
    explanation: "An einer Parklücke hat Vorrang, wer sie zuerst unmittelbar erreicht. Der Vorrang bleibt erhalten, wenn der Berechtigte an der Lücke vorbeifährt, um rückwärts einzuparken oder zusätzliche Fahrbewegungen zum Einparken ausführt.",
    legalReference: "§ 12 Abs. 5 StVO",
  }),
  q({
    code: "own-halten_parken-020", topic: "halten_parken", points: 4, difficulty: 0.7, tags: ["halten", "halteverbot", "autobahn", "radfahrstreifen"],
    text: "Wo ist bereits das Halten verboten?",
    answers: [t("Auf Einfädelungs- und Ausfädelungsstreifen"), t("Auf der Autobahn, auch auf dem Seitenstreifen"), t("Vor und in amtlich gekennzeichneten Feuerwehrzufahrten"), f("Bis zu 15 Meter vor und hinter einem Haltestellenzeichen", "Dort ist nur das Parken verboten; kurzes Halten ist erlaubt, wenn der Linienverkehr nicht behindert wird.")],
    explanation: "Halteverbote gelten unter anderem an engen und unübersichtlichen Stellen, in scharfen Kurven, auf Einfädelungs- und Ausfädelungsstreifen, auf Bahnübergängen, vor und in Feuerwehrzufahrten und auf Schutzstreifen. Auf der Autobahn ist Halten grundsätzlich verboten, auch auf dem Seitenstreifen. An Haltestellen ist nur das Parken bis 15 Meter untersagt.",
    legalReference: "§ 12 Abs. 1 StVO; § 18 Abs. 8 StVO; Zeichen 224",
  }),
  q({
    code: "own-halten_parken-021", topic: "halten_parken", points: 3, difficulty: 0.6, tags: ["parken", "vorfahrtstrasse", "ausserorts"],
    text: "Sie fahren außerorts auf einer Vorfahrtstraße (Zeichen 306). Dürfen Sie am Fahrbahnrand parken?",
    answers: [t("Nein, außerorts ist auf der Fahrbahn einer Vorfahrtstraße das Parken verboten"), t("Ja, auf einem befestigten Seitenstreifen neben der Fahrbahn"), f("Ja, auf der Fahrbahn, wenn die Straße breit genug ist", "Außerorts darf auf der Fahrbahn einer Vorfahrtstraße nicht geparkt werden."), f("Ja, aber nur mit eingeschaltetem Standlicht", "Die Beleuchtung ändert nichts am Parkverbot auf der Fahrbahn.")],
    explanation: "Auf Vorfahrtstraßen außerorts darf auf der Fahrbahn nicht geparkt werden, weil dort schnell gefahren wird und parkende Fahrzeuge ein hohes Risiko darstellen. Ein befestigter Seitenstreifen gehört nicht zur Fahrbahn und darf zum Parken benutzt werden, wenn kein anderes Verbot gilt.",
    legalReference: "Anlage 3 StVO, Zeichen 306; § 12 Abs. 4 StVO",
  }),
  q({
    code: "own-halten_parken-022", topic: "halten_parken", points: 3, difficulty: 0.65, tags: ["parken", "parkscheinautomat", "parkscheibe"],
    text: "Der Parkscheinautomat auf einem gebührenpflichtigen Parkplatz mit Höchstparkdauer von zwei Stunden ist defekt. Was gilt?",
    answers: [t("Sie dürfen ohne Parkschein parken, müssen aber eine Parkscheibe auslegen"), t("Es darf höchstens bis zur angegebenen Höchstparkdauer geparkt werden"), f("Sie dürfen dort gar nicht parken", "Bei defektem Automaten ist das Parken mit Parkscheibe erlaubt."), f("Sie dürfen unbegrenzt kostenlos parken", "Die Höchstparkdauer bleibt bestehen.")],
    explanation: "Ist ein Parkscheinautomat oder eine Parkuhr nicht funktionsfähig, darf nur bis zur angegebenen Höchstparkdauer geparkt werden. In diesem Fall ist die Parkscheibe zu verwenden und gut lesbar auszulegen.",
    legalReference: "§ 13 Abs. 1 StVO",
  }),
  q({
    code: "own-halten_parken-023", topic: "halten_parken", points: 3, difficulty: 0.6, tags: ["parken", "parkscheibe", "zusatzzeichen"],
    text: "Ein Parkplatz mit Zeichen 314 trägt das Zusatzzeichen mit Parkscheibe und der Angabe 2 Stunden. Sie kommen um 17:20 Uhr an. Bis wann dürfen Sie höchstens parken?",
    answers: [t("Bis 19:30 Uhr, weil die Parkscheibe auf 17:30 Uhr eingestellt wird und die zwei Stunden ab dann laufen"), f("Bis 19:20 Uhr, weil die Ankunftszeit zählt", "Die Parkscheibe wird auf die folgende halbe Stunde eingestellt, also auf 17:30 Uhr."), f("Bis 19:00 Uhr, weil auf die vorangehende volle Stunde abgerundet wird", "Eingestellt wird auf die halbe Stunde, die der Ankunft folgt, nicht auf eine frühere Zeit."), f("Bis 20:00 Uhr, weil auf die nächste volle Stunde aufgerundet wird", "Eingestellt wird auf die nächste halbe Stunde, also 17:30 Uhr.")],
    explanation: "Die Parkscheibe wird so eingestellt, dass der Pfeil auf den Strich der halben Stunde zeigt, die dem Zeitpunkt der Ankunft folgt, hier 17:30 Uhr. Ab dann darf zwei Stunden geparkt werden, also bis 19:30 Uhr.",
    legalReference: "§ 13 Abs. 2 StVO; Zusatzzeichen 1040-32",
  }),
  q({
    code: "own-halten_parken-024", topic: "halten_parken", points: 3, difficulty: 0.55, tags: ["parken", "einbahnstrasse", "linke_seite", "gehweg"],
    text: "In einer Einbahnstraße wollen Sie am linken Fahrbahnrand parken. Was müssen Sie beachten?",
    answers: [t("Auch links gilt: Parken nur am Fahrbahnrand, nicht auf dem Gehweg, und nicht vor Grundstücksausfahrten"), t("Auch links gelten die fünf Meter Abstand zu Kreuzungen und Einmündungen"), f("Links darf in Einbahnstraßen nur gehalten, nicht geparkt werden", "In Einbahnstraßen ist auch das Parken links erlaubt."), f("Links parkende Fahrzeuge müssen bei Dunkelheit innerorts immer beleuchtet sein", "Innerorts genügt ausreichende Straßenbeleuchtung.")],
    explanation: "In Einbahnstraßen darf links gehalten und geparkt werden. Alle übrigen Halte- und Parkverbote gelten auf der linken Seite genauso, insbesondere die Abstände zu Kreuzungen, das Verbot vor Grundstücksausfahrten und das Verbot des Gehwegparkens.",
    legalReference: "§ 12 Abs. 3 und 4 StVO",
  }),
  q({
    code: "own-halten_parken-025", topic: "halten_parken", points: 4, difficulty: 0.7, tags: ["parken", "wohngebiet", "lkw", "nachtparkverbot"],
    text: "Welche Fahrzeuge dürfen innerorts in reinen und allgemeinen Wohngebieten zwischen 22 und 6 Uhr sowie an Sonn- und Feiertagen nicht regelmäßig geparkt werden?",
    answers: [t("Kraftfahrzeuge mit einer zulässigen Gesamtmasse über 7,5 Tonnen"), t("Anhänger mit einer zulässigen Gesamtmasse über 2 Tonnen"), f("Pkw mit Anhänger bis 750 kg", "Kleine Anhänger sind von der Regel nicht betroffen."), f("Alle Wohnmobile unabhängig von der Masse", "Betroffen sind nur Kraftfahrzeuge über 7,5 Tonnen zulässiger Gesamtmasse.")],
    explanation: "Mit Kraftfahrzeugen über 7,5 Tonnen zulässiger Gesamtmasse und mit Anhängern über 2 Tonnen darf innerorts in Wohngebieten, Kurgebieten und Klinikgebieten in der Zeit von 22 bis 6 Uhr und an Sonn- und Feiertagen nicht regelmäßig geparkt werden. Die Regel schützt Anwohner vor Lärm und verstellten Straßen.",
    legalReference: "§ 12 Abs. 3a StVO",
  }),
  q({
    code: "own-halten_parken-026", topic: "halten_parken", points: 3, difficulty: 0.6, tags: ["halten", "zweite_reihe", "taxi"],
    text: "Ein Taxi hält kurz in zweiter Reihe, damit ein Fahrgast aussteigen kann. Ist das zulässig?",
    answers: [t("Ja, Taxen dürfen zum Ein- und Aussteigen in zweiter Reihe halten, wenn die Verkehrslage es zulässt"), f("Nein, Halten in zweiter Reihe ist ausnahmslos verboten", "Für Taxen gibt es eine ausdrückliche Ausnahme."), f("Ja, das gilt für alle Fahrzeuge zum Ein- und Aussteigen", "Für andere Fahrzeuge ist das Halten in zweiter Reihe nicht erlaubt.")],
    explanation: "Gehalten und geparkt wird am rechten Fahrbahnrand oder auf dem Seitenstreifen. Taxen dürfen, wenn die Verkehrslage es zulässt, neben anderen Fahrzeugen halten, damit Fahrgäste ein- oder aussteigen können. Für Privatfahrzeuge gilt diese Ausnahme nicht.",
    legalReference: "§ 12 Abs. 4 StVO",
  }),
  q({
    code: "own-halten_parken-027", topic: "halten_parken", points: 4, difficulty: 0.75, tags: ["parken", "kreuzung", "radweg", "grundstuecksausfahrt"],
    text: "Innerorts wollen Sie am rechten Fahrbahnrand parken. Neben der Fahrbahn verläuft ein baulich angelegter Radweg, 6 Meter hinter Ihrer Wunschposition beginnt eine Einmündung, gegenüber liegt eine Grundstücksausfahrt an einer schmalen Fahrbahn. Was gilt?",
    answers: [t("Das Parken ist verboten, weil wegen des Radwegs 8 Meter Abstand zur Einmündung nötig sind"), t("Das Parken ist auch wegen der gegenüberliegenden Ausfahrt auf der schmalen Fahrbahn verboten"), f("Das Parken ist erlaubt, weil 5 Meter Abstand eingehalten sind", "Bei baulich angelegtem Radweg gilt ein Abstand von 8 Metern."), f("Das Parken ist erlaubt, weil Ausfahrten nur auf der eigenen Straßenseite zählen", "Auf schmalen Fahrbahnen gilt das Verbot auch gegenüber der Ausfahrt.")],
    explanation: "Ist neben der Fahrbahn ein Radweg baulich angelegt, ist das Parken bis zu acht Meter vor und hinter den Schnittpunkten der Fahrbahnkanten verboten. Zusätzlich darf auf schmalen Fahrbahnen auch gegenüber von Grundstücksein- und -ausfahrten nicht geparkt werden. Beide Verbote greifen hier.",
    legalReference: "§ 12 Abs. 3 StVO",
  }),
  q({
    code: "own-halten_parken-028", topic: "halten_parken", points: 3, difficulty: 0.6, tags: ["parken", "verkehrsberuhigter_bereich", "zeichen_325"],
    text: "In einem verkehrsberuhigten Bereich (Zeichen 325.1) gibt es keine markierten Parkflächen. Was dürfen Sie?",
    answers: [t("Kurz halten zum Ein- oder Aussteigen und zum Be- oder Entladen"), f("Am Rand parken, solange Fußgänger noch vorbeikommen", "Parken ist nur in gekennzeichneten Flächen erlaubt."), f("Parken, wenn Sie Anwohner sind", "Auch für Anwohner gilt: Parken nur in gekennzeichneten Flächen."), f("Bis zu drei Stunden mit Parkscheibe parken", "Eine solche Regel gibt es im verkehrsberuhigten Bereich nicht.")],
    explanation: "Im verkehrsberuhigten Bereich ist das Parken außerhalb der dafür gekennzeichneten Flächen unzulässig. Ausgenommen ist das Halten zum Ein- oder Aussteigen sowie zum Be- oder Entladen.",
    legalReference: "Anlage 3 StVO, Zeichen 325.1",
  }),
  q({
    code: "own-halten_parken-029", topic: "halten_parken", points: 3, difficulty: 0.6, tags: ["parken", "halteverbotszone", "zeichen_290"],
    text: "Sie fahren in eine Zone mit Zeichen 290.1 ein. Wo dürfen Sie in dieser Zone parken?",
    answers: [t("Nur auf Flächen, die durch Zeichen 314 oder 315 oder Parkflächenmarkierung gekennzeichnet sind, oder wo ein Zusatzzeichen das Parken mit Parkscheibe oder Parkschein erlaubt"), f("Überall, wo kein einzelnes Halteverbotsschild steht", "In der Zone gilt flächendeckend eingeschränktes Halteverbot."), f("Nirgends, in der Zone ist jedes Halten verboten", "Halten bis drei Minuten und Parken auf gekennzeichneten Flächen sind erlaubt.")],
    explanation: "Zeichen 290.1 ordnet für die gesamte Zone ein eingeschränktes Halteverbot an. Parken ist nur dort erlaubt, wo es durch Zeichen 314, 315, Parkflächenmarkierungen oder ein Zusatzzeichen ausdrücklich zugelassen ist. Das Zeichen gilt bis zum Zeichen 290.2.",
    legalReference: "Anlage 2 StVO, Zeichen 290.1",
  }),
  q({
    code: "own-halten_parken-030", topic: "halten_parken", points: 3, difficulty: 0.55, tags: ["parken", "bewohnerparken", "parkausweis"],
    text: "Ein Parkplatz mit Zeichen 314 trägt das Zusatzzeichen Bewohner mit Parkausweis (Nr. 1044-30). Sie besuchen einen Freund, der dort wohnt. Dürfen Sie parken?",
    answers: [t("Nein, die Parkfläche ist den Inhabern des angegebenen Bewohnerparkausweises vorbehalten"), f("Ja, wenn der Freund Ihnen seinen Ausweis leiht", "Der Parkausweis ist an das eingetragene Fahrzeug gebunden und nicht übertragbar."), f("Ja, Besucher von Bewohnern sind gleichgestellt", "Besucher haben keinen Bewohnerparkausweis.")],
    explanation: "Bewohnerparkplätze dürfen nur mit einem gültigen, gut sichtbar ausgelegten Bewohnerparkausweis für das jeweilige Gebiet genutzt werden. Wer ohne Ausweis parkt, handelt ordnungswidrig und muss mit dem Abschleppen rechnen.",
    legalReference: "§ 45 Abs. 1b StVO; Zusatzzeichen 1044-30",
  }),
  q({
    code: "own-halten_parken-031", topic: "halten_parken", points: 3, difficulty: 0.55, tags: ["parken", "elektrofahrzeug", "ladesaeule"],
    text: "Ein Parkplatz mit Zeichen 314 trägt das Zusatzzeichen für elektrisch betriebene Fahrzeuge (Nr. 1010-66). Sie fahren einen Pkw mit Benzinmotor. Was gilt?",
    answers: [t("Sie dürfen dort nicht parken, die Fläche ist Fahrzeugen mit E-Kennzeichen vorbehalten"), f("Sie dürfen parken, wenn gerade kein Elektrofahrzeug laden möchte", "Die Fläche ist unabhängig von der Nachfrage reserviert."), f("Sie dürfen bis zu 30 Minuten parken", "Eine solche Ausnahme gibt es nicht.")],
    explanation: "Das Zusatzzeichen beschränkt das Parken auf elektrisch betriebene Fahrzeuge, die mit dem E-Kennzeichen gekennzeichnet sind. Fahrzeuge mit Verbrennungsmotor dürfen dort nicht parken und können abgeschleppt werden.",
    legalReference: "Zusatzzeichen 1010-66; § 12 StVO; Elektromobilitätsgesetz",
  }),
  q({
    code: "own-halten_parken-032", topic: "halten_parken", points: 3, difficulty: 0.6, tags: ["parken", "sperrflaeche", "zickzacklinie"],
    text: "Was gilt für Sperrflächen (Zeichen 298) und Grenzmarkierungen für Halt- oder Parkverbote (Zeichen 299)?",
    answers: [t("Sperrflächen dürfen weder befahren noch zum Halten oder Parken benutzt werden"), t("Die Zickzacklinie kennzeichnet den Bereich, in dem ein Halt- oder Parkverbot gilt"), f("Auf Sperrflächen darf gehalten, aber nicht geparkt werden", "Sperrflächen dürfen überhaupt nicht benutzt werden."), f("Die Zickzacklinie markiert einen Fußgängerüberweg", "Fußgängerüberwege werden mit Zeichen 293 markiert.")],
    explanation: "Sperrflächen sind vollständig gesperrt: Sie dürfen nicht befahren werden, und Halten oder Parken darauf ist verboten. Die Zickzacklinie (Zeichen 299) grenzt den Bereich eines Halt- oder Parkverbots ab, etwa an Haltestellen oder vor Einfahrten.",
    legalReference: "Anlage 2 StVO, Zeichen 298 und 299",
  }),
  q({
    code: "own-halten_parken-033", topic: "halten_parken", points: 3, difficulty: 0.55, tags: ["halten", "taxenstand", "zeichen_229"],
    text: "Sie wollen an einem Taxenstand (Zeichen 229) kurz halten, um jemanden aussteigen zu lassen. Ist das erlaubt?",
    answers: [t("Nein, am Taxenstand dürfen andere Fahrzeuge als Taxen nicht halten"), f("Ja, bis zu drei Minuten", "Für andere Fahrzeuge gilt ein Halteverbot."), f("Ja, wenn gerade kein Taxi wartet", "Das Halteverbot gilt unabhängig davon, ob Taxen anwesend sind.")],
    explanation: "Ein Taxenstand ist den Taxen vorbehalten. Andere Fahrzeuge dürfen dort nicht halten, auch nicht kurz zum Aussteigenlassen. Eine Parkverbotsstrecke von zehn Metern gilt zusätzlich davor, wenn das Zeichen verdeckt würde.",
    legalReference: "Anlage 2 StVO, Zeichen 229; § 12 Abs. 3 StVO",
  }),
  q({
    code: "own-halten_parken-034", topic: "halten_parken", points: 3, difficulty: 0.65, tags: ["parken", "radfahrstreifen", "radweg", "halten"],
    text: "Welche Aussagen zum Halten und Parken bei Radverkehrsanlagen treffen zu?",
    answers: [t("Auf einem baulich angelegten Radweg (Zeichen 237) dürfen Kraftfahrzeuge weder halten noch parken"), t("Auf einem Schutzstreifen (Zeichen 340) ist das Halten verboten"), t("Auf einem Radfahrstreifen (Zeichen 237 mit durchgezogener Linie) ist das Halten verboten"), f("Auf Radwegen darf zum Be- und Entladen bis zu drei Minuten gehalten werden", "Radwege dürfen von anderen Fahrzeugen nicht benutzt werden, auch nicht zum Be- und Entladen.")],
    explanation: "Radwege, Radfahrstreifen und Schutzstreifen sind für den Radverkehr bestimmt. Kraftfahrzeuge dürfen dort nicht halten oder parken, weil Radfahrende sonst auf die Fahrbahn ausweichen müssen. Nur auf Schutzstreifen darf bei Bedarf kurz ausgewichen werden, etwa bei Gegenverkehr.",
    legalReference: "§ 12 Abs. 1 StVO; Anlage 2 StVO, Zeichen 237 und 340",
  }),
  q({
    code: "own-halten_parken-035", topic: "halten_parken", points: 3, difficulty: 0.6, tags: ["parken", "bordsteinabsenkung", "schachtdeckel"],
    text: "Wo ist das Parken auch dann verboten, wenn kein Verkehrszeichen darauf hinweist?",
    answers: [t("Vor Bordsteinabsenkungen"), t("Über Schachtdeckeln, wenn dort das Parken auf dem Gehweg erlaubt ist"), t("Wenn dadurch die Benutzung gekennzeichneter Parkflächen verhindert würde"), f("Vor jeder Hauseingangstür", "Vor Hauseingängen gibt es kein allgemeines Parkverbot.")],
    explanation: "Die StVO verbietet das Parken vor Bordsteinabsenkungen, über Schachtdeckeln auf freigegebenen Gehwegparkflächen und überall dort, wo gekennzeichnete Parkflächen blockiert würden. Diese Verbote gelten ohne Verkehrszeichen.",
    legalReference: "§ 12 Abs. 3 StVO",
  }),
  q({
    code: "own-halten_parken-036", topic: "halten_parken", points: 3, difficulty: 0.5, tags: ["halten", "parken", "sichern", "unbefugte_benutzung"],
    text: "Sie verlassen Ihr Fahrzeug für einen kurzen Einkauf. Was müssen Sie tun?",
    answers: [t("Das Fahrzeug gegen Wegrollen sichern"), t("Das Fahrzeug gegen unbefugte Benutzung sichern, etwa abschließen und den Schlüssel mitnehmen"), f("Den Motor laufen lassen, damit die Klimaanlage weiterarbeitet", "Ein Fahrzeug mit laufendem Motor ist nicht gegen unbefugte Benutzung gesichert und belastet die Umwelt unnötig."), f("Das Warnblinklicht einschalten", "Das Warnblinklicht ist für Gefahrensituationen bestimmt.")],
    explanation: "Wer sein Fahrzeug verlässt, muss es gegen Wegrollen und gegen unbefugte Benutzung sichern. Dazu gehören Feststellbremse, eingelegter Gang beziehungsweise Stellung P, abgezogener Schlüssel und verschlossene Türen.",
    legalReference: "§ 14 Abs. 2 StVO",
  }),
  q({
    code: "own-halten_parken-037", topic: "halten_parken", points: 3, difficulty: 0.5, tags: ["halten", "aussteigen", "gefaehrdung", "radverkehr"],
    text: "Sie halten am rechten Fahrbahnrand und wollen aussteigen. Worauf müssen Sie achten?",
    answers: [t("Vor dem Öffnen der Tür über Spiegel und Schulterblick prüfen, ob Radfahrende oder Fahrzeuge kommen"), t("Die Tür so öffnen, dass niemand gefährdet wird, zum Beispiel mit der fahrbahnfernen Hand"), f("Die Tür zügig öffnen, damit der Verkehr nicht aufgehalten wird", "Beim Ein- und Aussteigen darf niemand gefährdet werden; Vorsicht geht vor."), f("Mitfahrende dürfen ohne Umschau aussteigen, weil nur der Fahrer verantwortlich ist", "Alle Ein- und Aussteigenden müssen sich so verhalten, dass niemand gefährdet wird.")],
    explanation: "Beim Ein- und Aussteigen müssen sich alle Insassen so verhalten, dass andere nicht gefährdet werden. Der Griff mit der fahrbahnfernen Hand zwingt zum Schulterblick und verhindert, dass Radfahrende gegen die geöffnete Tür fahren.",
    legalReference: "§ 14 Abs. 1 StVO",
  }),
  q({
    code: "own-halten_parken-038", topic: "halten_parken", points: 2, difficulty: 0.4, tags: ["parken", "haltestelle", "halten"],
    text: "Sie halten unmittelbar neben dem Haltestellenzeichen (Zeichen 224), damit ein Mitfahrer aussteigen kann. Kein Bus ist in Sicht. Ist das erlaubt?",
    answers: [t("Ja, das Halten ist erlaubt, solange Busse oder Straßenbahnen nicht behindert werden"), f("Nein, 15 Meter vor und hinter dem Zeichen ist jedes Halten verboten", "Dort ist nur das Parken verboten."), f("Ja, auch das Parken bis zu 30 Minuten ist erlaubt", "Parken ist bis 15 Meter vor und hinter dem Zeichen verboten.")],
    explanation: "An Haltestellen ist das Parken bis 15 Meter vor und hinter dem Zeichen verboten. Kurzes Halten ist erlaubt, sofern der Linienverkehr nicht behindert wird. Nähert sich ein Bus, muss die Haltestelle sofort geräumt werden.",
    legalReference: "§ 12 Abs. 3 StVO; Anlage 2 StVO, Zeichen 224",
  }),
  q({
    code: "own-halten_parken-039", topic: "halten_parken", points: 2, difficulty: 0.4, tags: ["parken", "parkscheibe", "zusatzzeichen"],
    text: "Wann müssen Sie beim Parken eine Parkscheibe verwenden?",
    answers: [t("Wenn ein Zusatzzeichen die Parkscheibe vorschreibt oder ein Parkscheinautomat außer Betrieb ist"), f("Immer, wenn Sie länger als eine Stunde parken", "Die Parkscheibe ist nur bei entsprechender Anordnung nötig."), f("Auf allen Parkplätzen mit Zeichen 314", "Zeichen 314 allein verlangt keine Parkscheibe.")],
    explanation: "Die Parkscheibe ist nur nötig, wenn ein Zusatzzeichen sie vorschreibt oder wenn Parkuhr oder Parkscheinautomat nicht funktionieren. Sie muss von außen gut lesbar im Fahrzeug liegen und auf die halbe Stunde nach der Ankunft eingestellt sein.",
    legalReference: "§ 13 Abs. 1 und 2 StVO",
  }),
  q({
    code: "own-halten_parken-040", topic: "halten_parken", points: 2, difficulty: 0.35, tags: ["halten", "parken", "fahrbahnrand", "seitenstreifen"],
    text: "Wo müssen Sie halten oder parken, wenn rechts ein befestigter Seitenstreifen vorhanden ist?",
    answers: [t("Auf dem Seitenstreifen, wenn er dafür ausreichend befestigt ist"), f("Immer auf der Fahrbahn, damit der Seitenstreifen frei bleibt", "Zum Halten und Parken ist der befestigte Seitenstreifen zu benutzen."), f("Auf dem Gehweg, wenn der Seitenstreifen belegt ist", "Gehwegparken ist nur bei ausdrücklicher Freigabe erlaubt.")],
    explanation: "Zum Halten und Parken ist der rechte Seitenstreifen einschließlich entlang der Fahrbahn angelegter Parkstreifen zu benutzen, wenn er ausreichend befestigt ist. Sonst wird an den rechten Fahrbahnrand herangefahren. Auf Autobahnen und Kraftfahrstraßen ist das Halten ohnehin verboten.",
    legalReference: "§ 12 Abs. 4 StVO",
  }),
  q({
    code: "own-halten_parken-041", topic: "halten_parken", points: 2, difficulty: 0.4, tags: ["parken", "platzsparend", "parkflaeche"],
    text: "Was verlangt die StVO beim Abstellen des Fahrzeugs auf einem Parkplatz mit markierten Parkflächen?",
    answers: [t("Platzsparend parken und die Markierungen einhalten"), f("Möglichst schräg parken, um beim Ausfahren bessere Sicht zu haben", "Innerhalb markierter Flächen ist die Aufstellung vorgegeben."), f("Zwei Flächen belegen, wenn der Parkplatz leer ist", "Auch auf leeren Parkplätzen ist platzsparend zu parken.")],
    explanation: "Es ist platzsparend zu parken, das gilt in der Regel auch für das Halten. Auf markierten Parkflächen muss innerhalb der Markierung geparkt werden, sonst wird die Nutzung anderer Flächen verhindert.",
    legalReference: "§ 12 Abs. 3 und 6 StVO",
  }),
  q({
    code: "own-halten_parken-042", topic: "halten_parken", points: 3, difficulty: 0.45, tags: ["halten", "halteverbot", "zeichen_283", "zusatzzeichen"],
    text: "Ein Zeichen 283 (absolutes Halteverbot) trägt das Zusatzzeichen mit der Angabe werktags 7 bis 9 Uhr. Sie wollen am Samstag um 8 Uhr halten. Was gilt?",
    answers: [t("Das Halteverbot gilt, weil der Samstag ein Werktag ist"), f("Das Halteverbot gilt nicht, weil Samstag zum Wochenende gehört", "Werktage sind Montag bis Samstag; nur Sonn- und Feiertage sind keine Werktage."), f("Das Halteverbot gilt nur montags bis freitags", "Dafür müsste das Zusatzzeichen Mo bis Fr angeben.")],
    explanation: "Werktage sind alle Tage von Montag bis Samstag, sofern kein gesetzlicher Feiertag ist. Ein auf werktags beschränktes Halteverbot gilt deshalb auch am Samstag in der angegebenen Zeit.",
    legalReference: "Anlage 2 StVO, Zeichen 283; Zusatzzeichen 1042-33",
  }),
];
