// Übungsfragen zum Thema "kreisverkehr" (eigene Formulierungen, kein amtlicher Prüfungsinhalt).
import type { Question } from "../types";
import { q, t, f } from "./_helpers";

export const kreisverkehr: readonly Question[] = [
  q({
    code: "own-kreisverkehr-001", topic: "kreisverkehr", points: 4, difficulty: 0.2, tags: ["vorfahrt_beschildert", "einfahren"],
    text: "Vor einem Kreisverkehr stehen die Zeichen 215 (Kreisverkehr) und 205 (Vorfahrt gewähren). Wer hat Vorfahrt?",
    answers: [t("Die Fahrzeuge im Kreisverkehr; Einfahrende müssen Vorfahrt gewähren"), f("Die einfahrenden Fahrzeuge, weil sie von rechts kommen", "Das Zeichen 205 hebt rechts vor links auf."), f("Wer schneller ist", "Geschwindigkeit begründet keine Vorfahrt.")],
    explanation: "Bei dieser üblichen Beschilderung hat der Verkehr im Kreis Vorfahrt. Wer einfahren will, muss warten, bis eine ausreichende Lücke entsteht.",
    legalReference: "§ 8 Abs. 1a StVO; Zeichen 215 und 205",
  }),
  q({
    code: "own-kreisverkehr-002", topic: "kreisverkehr", points: 3, difficulty: 0.2, tags: ["blinken", "einfahren"],
    text: "Müssen Sie beim Einfahren in einen Kreisverkehr blinken?",
    answers: [t("Nein, beim Einfahren wird nicht geblinkt"), f("Ja, nach rechts", "Ein Blinker beim Einfahren ist nicht vorgesehen und kann andere irritieren."), f("Ja, nach links, um die Kreisfahrt anzuzeigen", "Beim Einfahren ist Blinken nicht erlaubt.")],
    explanation: "Beim Einfahren in einen Kreisverkehr darf nicht geblinkt werden. Geblinkt wird nur beim Verlassen des Kreisverkehrs nach rechts.",
    mnemonic: "Rein ohne Blinken, raus mit Blinken.",
    legalReference: "§ 8 Abs. 1a StVO",
  }),
  q({
    code: "own-kreisverkehr-003", topic: "kreisverkehr", points: 3, difficulty: 0.2, tags: ["blinken", "ausfahren"],
    text: "Wie zeigen Sie das Verlassen des Kreisverkehrs an?",
    answers: [t("Rechtzeitig vor der gewünschten Ausfahrt nach rechts blinken"), f("Gar nicht, im Kreisverkehr wird nicht geblinkt", "Beim Ausfahren ist Blinken vorgeschrieben."), f("Nach links blinken, solange Sie im Kreis bleiben", "Linksblinken ist im Kreisverkehr nicht vorgesehen.")],
    explanation: "Das Ausfahren aus dem Kreisverkehr ist ein Abbiegevorgang und muss durch Blinken nach rechts angekündigt werden. So wissen Wartende, ob sie einfahren können.",
    legalReference: "§ 9 Abs. 1 StVO; § 8 Abs. 1a StVO",
  }),
  q({
    code: "own-kreisverkehr-004", topic: "kreisverkehr", points: 2, difficulty: 0.3, tags: ["mittelinsel"],
    text: "Dürfen Sie die Mittelinsel eines Kreisverkehrs überfahren?",
    answers: [t("Nein, nur mit großen Fahrzeugen, wenn es wegen der Abmessungen unvermeidbar ist"), f("Ja, wenn der Kreisverkehr leer ist", "Die Mittelinsel darf nicht abgekürzt werden."), f("Ja, mit Pkw immer, mit Lkw nie", "Es ist umgekehrt: Nur große Fahrzeuge dürfen sie im Ausnahmefall überfahren.")],
    explanation: "Die Mittelinsel darf nicht überfahren werden, es sei denn, das Fahrzeug ist so groß, dass es anders nicht durch den Kreis kommt.",
    legalReference: "§ 9a Abs. 1 StVO",
  }),
  q({
    code: "own-kreisverkehr-005", topic: "kreisverkehr", points: 2, difficulty: 0.3, tags: ["halten"],
    text: "Dürfen Sie auf der Fahrbahn im Kreisverkehr halten?",
    answers: [t("Nein, das Halten auf der Fahrbahn im Kreisverkehr ist verboten"), f("Ja, bis zu drei Minuten", "Halten ist im Kreisverkehr generell verboten."), f("Ja, wenn der Warnblinker eingeschaltet ist", "Der Warnblinker erlaubt kein Halten.")],
    explanation: "Im Kreisverkehr ist das Halten auf der Fahrbahn verboten. Ausgenommen sind nur verkehrsbedingte Gründe, etwa Warten wegen Fußgängern an einer Ausfahrt.",
    legalReference: "§ 9a Abs. 2 StVO",
  }),
  q({
    code: "own-kreisverkehr-006", topic: "kreisverkehr", points: 4, difficulty: 0.5, tags: ["rechts_vor_links", "einfahren"],
    text: "Ein Kreisverkehr ist nicht durch Verkehrszeichen geregelt. Wer hat Vorfahrt?",
    answers: [t("Die einfahrenden Fahrzeuge, weil rechts vor links gilt"), f("Die Fahrzeuge im Kreis", "Ohne Zeichen 205 an den Zufahrten gilt die Grundregel rechts vor links."), f("Wer zuerst da war", "Ankunftszeit regelt keine Vorfahrt.")],
    explanation: "Ohne Beschilderung gilt an den Zufahrten die Grundregel rechts vor links: Wer in den Kreis einfahren will, kommt für die Fahrzeuge im Kreis von rechts und hat Vorfahrt.",
    legalReference: "§ 8 Abs. 1 StVO",
  }),
  q({
    code: "own-kreisverkehr-007", topic: "kreisverkehr", points: 4, difficulty: 0.4, tags: ["ausfahren", "fussgaenger", "radverkehr"],
    text: "Sie verlassen den Kreisverkehr. An der Ausfahrt überqueren Fußgänger einen Zebrastreifen und ein Radfahrer nutzt den umlaufenden Radweg. Was gilt?",
    answers: [t("Fußgänger am Zebrastreifen und Radfahrende auf dem Radweg müssen durchgelassen werden"), f("Sie haben Vorrang, weil Sie im Kreis fahren", "Beim Ausfahren gelten die Abbiegeregeln."), f("Nur Fußgänger müssen durchgelassen werden, nicht Radfahrende", "Auch Radfahrende sind beim Abbiegen durchzulassen.")],
    explanation: "Das Verlassen des Kreisverkehrs ist ein Abbiegevorgang. Fußgänger am Zebrastreifen und Radfahrende auf dem begleitenden Radweg sind durchzulassen.",
    legalReference: "§ 9 Abs. 3 StVO; § 26 StVO",
  }),
  q({
    code: "own-kreisverkehr-008", topic: "kreisverkehr", points: 2, difficulty: 0.1, tags: ["fahrtrichtung"],
    text: "In welche Richtung wird ein Kreisverkehr befahren?",
    answers: [t("Nur rechts herum, also entgegen dem Uhrzeigersinn"), f("Links herum, also im Uhrzeigersinn", "In Deutschland wird rechts herum gefahren."), f("In beliebiger Richtung, je nach Ziel", "Die Fahrtrichtung ist fest vorgegeben.")],
    explanation: "Das Zeichen 215 schreibt die Fahrtrichtung vor: Der Kreisverkehr wird rechts herum befahren, also entgegen dem Uhrzeigersinn.",
    legalReference: "Zeichen 215 StVO",
  }),
  q({
    code: "own-kreisverkehr-009", topic: "kreisverkehr", points: 2, difficulty: 0.2, tags: ["wenden"],
    text: "Dürfen Sie einen Kreisverkehr zum Wenden benutzen?",
    answers: [t("Ja, indem Sie den Kreis ganz durchfahren und die Zufahrtsstraße wieder verlassen"), f("Nein, Wenden ist im Kreisverkehr verboten", "Das vollständige Durchfahren ist erlaubt und sicherer als Wenden auf der Straße."), f("Nur wenn der Kreisverkehr leer ist", "Es gelten die normalen Regeln, keine besondere Bedingung.")],
    explanation: "Der Kreisverkehr kann zum sicheren Richtungswechsel genutzt werden, indem man ihn vollständig durchfährt. Beim Ausfahren gelten die normalen Regeln inklusive Blinken.",
    legalReference: "§ 9a StVO",
  }),
  q({
    code: "own-kreisverkehr-010", topic: "kreisverkehr", points: 4, difficulty: 0.65, tags: ["vorfahrt_beschildert", "rechts_vor_links", "einfahren"],
    text: "An den Zufahrten eines Kreisverkehrs steht nur das Zeichen 215 (Kreisverkehr), aber kein Zeichen 205. Wer hat Vorfahrt?",
    answers: [t("Die einfahrenden Fahrzeuge, weil ohne Zeichen 205 rechts vor links gilt"), t("Das Zeichen 215 allein schreibt nur die Fahrtrichtung rechts herum vor und verbietet das Halten auf der Kreisfahrbahn"), f("Der Verkehr im Kreis, weil das Zeichen 215 ihm Vorfahrt gibt", "Vorfahrt für den Kreisverkehr besteht nur zusammen mit dem Zeichen 205."), f("Wer zuerst da ist", "Die Ankunftsreihenfolge regelt keine Vorfahrt.")],
    explanation: "Vorfahrt für den Verkehr auf der Kreisfahrbahn besteht nur, wenn an der Zufahrt Zeichen 215 zusammen mit Zeichen 205 angeordnet ist. Fehlt Zeichen 205, gilt rechts vor links: Der Einfahrende kommt für den Verkehr im Kreis von rechts.",
    legalReference: "§ 8 Abs. 1 und 1a StVO; Zeichen 215",
  }),
  q({
    code: "own-kreisverkehr-011", topic: "kreisverkehr", points: 3, difficulty: 0.6, tags: ["blinken", "ausfahren", "rechtzeitig"],
    text: "Sie wollen den Kreisverkehr an der dritten Ausfahrt verlassen. Wann setzen Sie den Blinker?",
    answers: [t("Nach dem Passieren der zweiten Ausfahrt, rechtzeitig vor der dritten Ausfahrt nach rechts"), f("Bereits beim Einfahren nach links, um die lange Kreisfahrt anzuzeigen", "Beim Einfahren wird nicht geblinkt."), f("Erst beim Einlenken in die Ausfahrt", "Das ist zu spät; Wartende an der Zufahrt sollen sich rechtzeitig einstellen können.")],
    explanation: "Das Verlassen des Kreisverkehrs wird rechtzeitig, aber nicht zu früh nach rechts angezeigt: erst nach der vorletzten Ausfahrt, damit niemand ein früheres Ausfahren vermutet.",
    legalReference: "§ 9 Abs. 1 StVO; § 8 Abs. 1a StVO",
  }),
  q({
    code: "own-kreisverkehr-012", topic: "kreisverkehr", points: 4, difficulty: 0.7, tags: ["mehrstreifig", "fahrstreifenwechsel", "ausfahren"],
    text: "Sie fahren in einem zweistreifigen Kreisverkehr auf dem inneren Fahrstreifen und wollen ausfahren. Auf dem äußeren Fahrstreifen fährt ein Fahrzeug neben Ihnen weiter im Kreis. Was gilt?",
    answers: [t("Sie dürfen den äußeren Fahrstreifen nur kreuzen, wenn das Fahrzeug dort nicht gefährdet oder behindert wird; im Zweifel eine weitere Runde fahren"), t("Für das Ausfahren vom inneren Fahrstreifen gelten die Regeln des Fahrstreifenwechsels: Spiegel, Blinker, Schulterblick"), f("Sie haben Vorrang, weil Sie ausfahren und blinken", "Blinken gibt keinen Vorrang; wer den Fahrstreifen wechselt, muss andere durchfahren lassen."), f("Das Fahrzeug außen muss Ihnen Platz machen, weil Sie innen fahren", "Der innere Fahrstreifen hat keinen Vorrang beim Ausfahren.")],
    explanation: "Im mehrstreifigen Kreisverkehr ist das Ausfahren vom inneren Fahrstreifen ein Fahrstreifenwechsel. Der Verkehr auf dem äußeren Fahrstreifen darf dabei nicht behindert werden. Notfalls fährt man eine weitere Runde.",
    legalReference: "§ 7 Abs. 5 StVO; § 9a StVO",
  }),
  q({
    code: "own-kreisverkehr-013", topic: "kreisverkehr", points: 3, difficulty: 0.6, tags: ["radverkehr", "kreisfahrbahn", "ueberholen", "ueberholabstand"],
    text: "In einem einstreifigen Kreisverkehr fährt vor Ihnen ein Radfahrer auf der Kreisfahrbahn. Dürfen Sie ihn im Kreis überholen?",
    answers: [t("Nur, wenn Sie den seitlichen Mindestabstand von 1,5 m einhalten können; in der Regel bleibt man deshalb hinter dem Radfahrer"), f("Ja, immer, weil Radfahrende im Kreisverkehr den Radweg benutzen müssen", "Radfahrende dürfen die Kreisfahrbahn benutzen, wenn kein benutzungspflichtiger Radweg vorhanden ist."), f("Ja, mit geringem Abstand, weil der Kreis schmal ist", "Der Mindestabstand gilt auch im Kreisverkehr.")],
    explanation: "Radfahrende dürfen die Kreisfahrbahn nutzen. Beim Überholen gilt auch dort der Mindestabstand von 1,5 m innerorts. Da einstreifige Kreisverkehre schmal sind, ist das Überholen meist nicht möglich.",
    legalReference: "§ 5 Abs. 4 StVO; § 2 Abs. 4 StVO",
  }),
  q({
    code: "own-kreisverkehr-014", topic: "kreisverkehr", points: 2, difficulty: 0.5, tags: ["radverkehr", "ueberholabstand", "innerorts"], kind: "numeric", numericAnswer: 1.5, tolerance: 0, unit: "m",
    text: "Welchen seitlichen Mindestabstand müssen Sie einhalten, wenn Sie in einem innerörtlichen Kreisverkehr einen Radfahrer überholen? Angabe in Metern.",
    answers: [],
    explanation: "Innerorts beträgt der Mindestabstand beim Überholen von Radfahrenden 1,5 m, auch im Kreisverkehr. Wo das nicht möglich ist, darf nicht überholt werden.",
    legalReference: "§ 5 Abs. 4 StVO",
  }),
  q({
    code: "own-kreisverkehr-015", topic: "kreisverkehr", points: 3, difficulty: 0.6, tags: ["mittelinsel", "lkw", "grosse_fahrzeuge"],
    text: "Ein Sattelzug fährt vor Ihnen in einen kleinen Kreisverkehr und überfährt dabei die gepflasterte Mittelinsel. Was ist richtig?",
    answers: [t("Das ist erlaubt, wenn der Lkw wegen seiner Abmessungen sonst nicht durch den Kreis kommt"), t("Sie sollten Abstand halten, weil das Heck des Aufliegers weit ausschwenkt"), f("Der Lkw begeht eine Ordnungswidrigkeit, weil die Mittelinsel nie überfahren werden darf", "Für große Fahrzeuge gibt es eine Ausnahme."), f("Auch Sie dürfen mit dem Pkw die Mittelinsel abkürzen, wenn der Kreis leer ist", "Pkw dürfen die Mittelinsel nicht überfahren.")],
    explanation: "Die Mittelinsel darf nur von Fahrzeugen überfahren werden, die wegen ihrer Größe anders nicht durch den Kreisverkehr kommen. Für Pkw ist das Abkürzen über die Insel verboten.",
    legalReference: "§ 9a Abs. 1 StVO",
  }),
  q({
    code: "own-kreisverkehr-016", topic: "kreisverkehr", points: 3, difficulty: 0.55, tags: ["halten", "fussgaenger", "ausfahren", "verkehrsbedingt"],
    text: "Beim Ausfahren aus dem Kreisverkehr müssen Sie wegen Fußgängern auf dem Zebrastreifen an der Ausfahrt anhalten. Dadurch stehen Sie teilweise noch auf der Kreisfahrbahn. Ist das erlaubt?",
    answers: [t("Ja, verkehrsbedingtes Anhalten ist vom Haltverbot im Kreisverkehr nicht erfasst"), f("Nein, im Kreisverkehr darf niemals angehalten werden", "Das Haltverbot betrifft freiwilliges Halten, nicht das verkehrsbedingte Warten."), f("Ja, aber nur mit eingeschaltetem Warnblinklicht", "Das Warnblinklicht ist hier nicht vorgeschrieben.")],
    explanation: "Auf der Kreisfahrbahn darf nicht gehalten werden. Verkehrsbedingtes Anhalten, etwa um Fußgängern am Zebrastreifen das Überqueren zu ermöglichen, ist davon nicht betroffen.",
    legalReference: "§ 9a Abs. 2 StVO; § 26 StVO",
  }),
  q({
    code: "own-kreisverkehr-017", topic: "kreisverkehr", points: 4, difficulty: 0.6, tags: ["einsatzfahrzeug", "blaulicht", "freie_bahn"],
    text: "Sie fahren im Kreisverkehr, als sich ein Einsatzfahrzeug mit Blaulicht und Einsatzhorn nähert. Wie schaffen Sie freie Bahn?",
    answers: [t("Den Kreisverkehr zügig an der nächsten Ausfahrt verlassen oder, wenn das nicht geht, möglichst weit rechts fahren"), f("Sofort auf der Kreisfahrbahn anhalten", "Ein stehendes Fahrzeug im Kreis blockiert das Einsatzfahrzeug."), f("Weiterfahren wie bisher, weil im Kreisverkehr Vorfahrt besteht", "Einsatzfahrzeuge mit Blaulicht und Horn haben Vorrang vor allen Vorfahrtregeln.")],
    explanation: "Einsatzfahrzeugen mit Blaulicht und Horn ist sofort freie Bahn zu schaffen. Im Kreisverkehr geschieht das durch zügiges Räumen der Kreisfahrbahn oder Rechtsfahren, nicht durch Anhalten mitten im Kreis.",
    legalReference: "§ 38 Abs. 1 StVO",
  }),
  q({
    code: "own-kreisverkehr-018", topic: "kreisverkehr", points: 3, difficulty: 0.6, tags: ["einfahren", "geschwindigkeit", "verkehrsbeobachtung"],
    text: "Sie nähern sich einem beschilderten Kreisverkehr (Zeichen 215 mit 205). Wie fahren Sie ihn richtig an?",
    answers: [t("Geschwindigkeit deutlich verringern und nach links auf den Verkehr im Kreis achten"), t("Nur einfahren, wenn eine ausreichende Lücke vorhanden ist; sonst an der Wartelinie oder den Haifischzähnen warten"), f("Zügig einfahren, weil Fahrzeuge im Kreis ohnehin langsam sind", "Der Verkehr im Kreis hat Vorfahrt; das Einfahren ohne Lücke ist ein Vorfahrtverstoß."), f("Beim Einfahren links blinken, um die Kreisfahrt anzuzeigen", "Beim Einfahren wird nicht geblinkt.")],
    explanation: "An Kreisverkehren mit Zeichen 205 hat der Verkehr auf der Kreisfahrbahn Vorfahrt. Man nähert sich langsam, beobachtet den Verkehr von links und fährt nur in eine ausreichende Lücke ein.",
    legalReference: "§ 8 Abs. 1a StVO",
  }),
  q({
    code: "own-kreisverkehr-019", topic: "kreisverkehr", points: 3, difficulty: 0.6, tags: ["ausfahren", "radverkehr", "radweg", "abbiegen"],
    text: "Um den Kreisverkehr verläuft ein Radweg ohne Zebrastreifen. Beim Ausfahren kreuzt ein Radfahrer auf dem Radweg Ihre Ausfahrt. Wer hat Vorrang?",
    answers: [t("Der Radfahrer, weil das Ausfahren ein Abbiegevorgang ist und Radfahrende auf dem begleitenden Radweg durchgelassen werden müssen"), f("Sie, weil Sie sich noch im Kreisverkehr befinden und Vorfahrt haben", "Die Vorfahrt im Kreis gilt gegenüber Einfahrenden, nicht gegenüber Radfahrenden beim Ausfahren."), f("Sie, wenn keine Haifischzähne markiert sind", "Der Vorrang beim Abbiegen ergibt sich aus § 9 StVO, nicht aus der Markierung.")],
    explanation: "Das Verlassen des Kreisverkehrs ist ein Abbiegevorgang. Radfahrende auf dem den Kreis begleitenden Radweg sind durchzulassen, auch ohne Zebrastreifen oder Markierung.",
    legalReference: "§ 9 Abs. 3 StVO",
  }),
  q({
    code: "own-kreisverkehr-020", topic: "kreisverkehr", points: 3, difficulty: 0.65, tags: ["einfahren", "zebrastreifen", "fussgaenger", "vorrang"],
    text: "An der Zufahrt zum Kreisverkehr liegt ein Zebrastreifen. Ein Fußgänger will ihn überqueren, während Sie in den Kreis einfahren wollen. Was gilt?",
    answers: [t("Der Fußgänger hat am Zebrastreifen Vorrang; Sie müssen vor dem Zebrastreifen warten"), t("Sie dürfen nicht so anfahren, dass Sie auf dem Zebrastreifen warten müssen, wenn im Kreis keine Lücke ist"), f("Sie haben Vorrang, weil Sie sich bereits im Zufahrtsbereich befinden", "Am Fußgängerüberweg haben Fußgänger Vorrang."), f("Der Fußgänger muss warten, bis Sie eingefahren sind", "Das ist umgekehrt.")],
    explanation: "Am Zebrastreifen haben Fußgänger Vorrang, auch an der Zufahrt zum Kreisverkehr. Man darf außerdem nicht auf den Überweg fahren, wenn abzusehen ist, dass man dort wegen des Verkehrs im Kreis warten müsste.",
    legalReference: "§ 26 Abs. 1 und 2 StVO",
  }),
  q({
    code: "own-kreisverkehr-021", topic: "kreisverkehr", points: 3, difficulty: 0.55, tags: ["ampel", "rangfolge", "lichtzeichen"],
    text: "Ein großer Kreisverkehr ist mit Ampeln ausgestattet. An Ihrer Zufahrt steht das Zeichen 205, die Ampel zeigt Grün. Was gilt?",
    answers: [t("Sie dürfen einfahren, weil das Lichtzeichen dem Zeichen 205 vorgeht; Fahrzeuge im Kreis werden durch Rot angehalten"), f("Sie müssen trotz Grün dem Verkehr im Kreis Vorfahrt gewähren", "Bei funktionierender Ampel geht das Lichtzeichen dem Verkehrszeichen vor."), f("Ampeln sind an Kreisverkehren nicht zulässig", "Große Kreisverkehre werden durchaus mit Ampeln geregelt.")],
    explanation: "Lichtzeichen gehen Verkehrszeichen vor. Zeigt die Ampel an der Zufahrt Grün, darf eingefahren werden. Ist die Ampel ausgeschaltet, gilt wieder das Zeichen 205.",
    legalReference: "§ 37 Abs. 1 StVO; § 8 Abs. 1a StVO",
  }),
  q({
    code: "own-kreisverkehr-022", topic: "kreisverkehr", points: 3, difficulty: 0.6, tags: ["fahrtrichtung", "linksabbiegen", "verkehrszeichen"],
    text: "Sie wollen im Kreisverkehr die Ausfahrt nehmen, die für Sie links liegt. Dürfen Sie den Kreis links herum abkürzen?",
    answers: [t("Nein, der Kreisverkehr muss immer rechts herum durchfahren werden, auch zur linken Ausfahrt"), f("Ja, wenn kein Fahrzeug im Kreis ist", "Das Zeichen 215 schreibt die Fahrtrichtung rechts herum vor."), f("Ja, mit eingeschaltetem Blinker nach links", "Das Fahren links herum ist ein Verstoß gegen die vorgeschriebene Fahrtrichtung.")],
    explanation: "Das Zeichen 215 schreibt die Fahrtrichtung rechts herum vor. Auch zur linken Ausfahrt wird der Kreis in der vorgeschriebenen Richtung durchfahren; Abkürzen wäre Fahren gegen die Fahrtrichtung.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 215)",
  }),
  q({
    code: "own-kreisverkehr-023", topic: "kreisverkehr", points: 3, difficulty: 0.6, tags: ["einfahren", "vorfahrt_beschildert", "wartepflicht", "behinderung"],
    text: "Sie warten am beschilderten Kreisverkehr. Im Kreis fährt ein Fahrzeug, das rechts blinkt und offenbar an der Zufahrt vor Ihnen ausfahren will. Dürfen Sie einfahren?",
    answers: [t("Erst, wenn das Ausfahren durch Einlenken und Verlangsamen eindeutig erkennbar ist; auf den Blinker allein dürfen Sie nicht vertrauen"), f("Ja, sofort, weil der Blinker das Ausfahren ankündigt", "Ein irrtümlich gesetzter Blinker ist im Kreisverkehr häufig."), f("Nein, Sie müssen immer warten, bis der Kreis völlig leer ist", "Sie dürfen einfahren, sobald niemand gefährdet oder wesentlich behindert wird.")],
    explanation: "Wer wartepflichtig ist, darf nur einfahren, wenn niemand gefährdet oder wesentlich behindert wird. Ein Blinker allein ist kein verlässliches Zeichen; erst das erkennbare Ausfahren erlaubt das Einfahren.",
    legalReference: "§ 8 Abs. 2 StVO; § 8 Abs. 1a StVO",
  }),
  q({
    code: "own-kreisverkehr-024", topic: "kreisverkehr", points: 3, difficulty: 0.55, tags: ["mehrstreifig", "einfahren", "fahrstreifenwahl"],
    text: "Vor einem zweistreifigen Kreisverkehr sind auf der Zufahrt Richtungspfeile markiert: rechter Fahrstreifen für die erste Ausfahrt, linker Fahrstreifen für die weiteren Ausfahrten. Sie wollen die dritte Ausfahrt nehmen. Wie ordnen Sie sich ein?",
    answers: [t("Auf dem linken Fahrstreifen, wie es die Richtungspfeile vorgeben"), f("Auf dem rechten Fahrstreifen, weil im Kreisverkehr immer rechts gefahren wird", "Die Richtungspfeile sind verbindlich und ordnen den linken Fahrstreifen für die weiteren Ausfahrten an."), f("Beliebig, weil innerorts freie Fahrstreifenwahl gilt", "Die freie Fahrstreifenwahl gilt nicht, wenn Richtungspfeile die Fahrtrichtung vorschreiben.")],
    explanation: "Richtungspfeile auf der Fahrbahn (Zeichen 297) schreiben die Fahrtrichtung verbindlich vor. Wer sie missachtet, gefährdet an der Ausfahrt den Verkehr auf dem anderen Fahrstreifen.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 297)",
  }),
  q({
    code: "own-kreisverkehr-025", topic: "kreisverkehr", points: 3, difficulty: 0.6, tags: ["strassenbahn", "schienenfahrzeuge", "vorfahrt"],
    text: "Durch einen Kreisverkehr führen Straßenbahnschienen quer über die Kreisfahrbahn. Wer hat Vorrang, wenn keine Ampel vorhanden ist?",
    answers: [t("Das ergibt sich aus den aufgestellten Verkehrszeichen; in der Regel wird der Straßenbahn durch Zeichen 205 oder 206 Vorrang eingeräumt"), f("Immer die Fahrzeuge im Kreis, weil sie Vorfahrt haben", "Die Vorfahrt im Kreis gilt gegenüber Einfahrenden; für kreuzende Schienen gelten die dort aufgestellten Zeichen."), f("Immer die Straßenbahn, weil Schienenfahrzeuge überall Vorrang haben", "Einen allgemeinen Vorrang der Straßenbahn gibt es nicht.")],
    explanation: "Kreuzt eine Straßenbahn die Kreisfahrbahn, wird der Vorrang durch Verkehrszeichen oder Lichtzeichen geregelt. Meist erhält die Straßenbahn Vorrang, weil sie nicht ausweichen kann; entscheidend sind aber die konkreten Zeichen.",
    legalReference: "§ 8 StVO; § 9 Abs. 3 StVO",
  }),
  q({
    code: "own-kreisverkehr-026", topic: "kreisverkehr", points: 3, difficulty: 0.55, tags: ["rueckwaertsfahren", "ausfahrt_verpasst", "sicherheit"],
    text: "Sie haben Ihre Ausfahrt im Kreisverkehr verpasst. Was tun Sie?",
    answers: [t("Eine weitere Runde fahren und die Ausfahrt beim nächsten Mal nehmen"), f("Im Kreis anhalten und zur Ausfahrt zurücksetzen", "Rückwärtsfahren im Kreis ist gefährlich, und Halten auf der Kreisfahrbahn ist verboten."), f("Die Mittelinsel überfahren, um schneller zur Ausfahrt zu kommen", "Pkw dürfen die Mittelinsel nicht überfahren.")],
    explanation: "Eine verpasste Ausfahrt ist im Kreisverkehr harmlos: Man fährt einfach eine weitere Runde. Halten, Zurücksetzen oder Abkürzen über die Insel sind verboten und gefährlich.",
    legalReference: "§ 9a StVO",
  }),
  q({
    code: "own-kreisverkehr-027", topic: "kreisverkehr", points: 3, difficulty: 0.6, tags: ["geschwindigkeit", "kurve", "naesse", "fahrphysik"],
    text: "Warum sollten Sie einen Kreisverkehr bei Nässe besonders langsam durchfahren?",
    answers: [t("Die Kreisfahrbahn ist eine enge Dauerkurve; bei Nässe sinkt die Haftung und das Fahrzeug kann nach außen ausbrechen"), t("Radfahrende und Fußgänger an den Ausfahrten sind bei Regen schlechter erkennbar"), f("Bei Nässe gilt im Kreisverkehr automatisch Schrittgeschwindigkeit", "Eine solche Regel gibt es nicht; die Geschwindigkeit ist den Verhältnissen anzupassen."), f("Bei Nässe dürfen im Kreisverkehr nur Lkw fahren", "Das ist Unsinn.")],
    explanation: "Im Kreisverkehr wirkt die Fliehkraft dauerhaft. Bei Nässe reicht die Haftung der Reifen für weniger Kurvengeschwindigkeit, und andere Verkehrsteilnehmer sind schlechter zu sehen. Die Geschwindigkeit ist entsprechend anzupassen.",
    legalReference: "§ 3 Abs. 1 StVO",
  }),
  q({
    code: "own-kreisverkehr-028", topic: "kreisverkehr", points: 3, difficulty: 0.55, tags: ["blinken", "ausfahren", "einfahren", "fahrtrichtungsanzeiger"],
    text: "Welche Aussagen zum Blinken im Kreisverkehr sind richtig?",
    answers: [t("Beim Einfahren wird nicht geblinkt"), t("Beim Ausfahren wird rechts geblinkt"), f("Wer den Kreis vollständig durchfährt, blinkt links", "Linksblinken ist im Kreisverkehr nicht vorgesehen."), f("Blinken ist im Kreisverkehr generell freiwillig", "Das Ausfahren muss angezeigt werden.")],
    explanation: "Im Kreisverkehr gilt: Einfahren ohne Blinker, Ausfahren mit Blinker nach rechts. Linksblinken ist nicht vorgesehen und würde andere verwirren.",
    mnemonic: "Rein ohne Blinken, raus mit Blinken.",
    legalReference: "§ 8 Abs. 1a StVO; § 9 Abs. 1 StVO",
  }),
  q({
    code: "own-kreisverkehr-029", topic: "kreisverkehr", points: 4, difficulty: 0.65, tags: ["vorfahrt_beschildert", "einfahren", "gleichzeitig"],
    text: "Sie und ein Fahrzeug an der gegenüberliegenden Zufahrt wollen gleichzeitig in einen leeren, beschilderten Kreisverkehr (Zeichen 215 mit 205) einfahren. Wer fährt zuerst?",
    answers: [t("Beide dürfen einfahren, weil sich ihre Wege beim Einfahren an gegenüberliegenden Zufahrten zunächst nicht kreuzen; wer zuerst im Kreis ist, hat gegenüber dem anderen Vorfahrt"), f("Das Fahrzeug von rechts", "Rechts vor links gilt im beschilderten Kreisverkehr nicht."), f("Niemand, beide müssen warten, bis der andere gefahren ist", "Bei leerem Kreis dürfen beide einfahren.")],
    explanation: "Im beschilderten Kreisverkehr hat der Verkehr auf der Kreisfahrbahn Vorfahrt. Fahren zwei Fahrzeuge an gegenüberliegenden Zufahrten gleichzeitig ein, kreuzen sich ihre Wege zunächst nicht. Sobald eines im Kreis ist, muss das andere an der nächsten Zufahrt darauf achten.",
    legalReference: "§ 8 Abs. 1a StVO",
  }),
  q({
    code: "own-kreisverkehr-030", topic: "kreisverkehr", points: 3, difficulty: 0.55, tags: ["lkw", "grosse_fahrzeuge", "abstand", "einfahren"],
    text: "Vor Ihnen fährt ein Gelenkbus in den Kreisverkehr ein. Worauf achten Sie?",
    answers: [t("Der Bus braucht die gesamte Fahrbahnbreite und kann nach links ausholen; ausreichenden Abstand halten"), t("Nicht neben dem Bus in den Kreis einfahren, auch wenn ein zweiter Fahrstreifen vorhanden ist"), f("Der Bus muss warten, bis alle Pkw durchgefahren sind", "Große Fahrzeuge haben dieselben Rechte wie Pkw."), f("Sie dürfen den Bus im Kreis überholen", "Im engen Kreis ist das Überholen eines Busses gefährlich und meist unmöglich.")],
    explanation: "Lange Fahrzeuge schwenken im Kreisverkehr weit aus und beanspruchen oft beide Fahrstreifen. Wer daneben oder dicht dahinter fährt, riskiert einen Zusammenstoß.",
    legalReference: "§ 1 StVO; § 4 StVO",
  }),
  q({
    code: "own-kreisverkehr-031", topic: "kreisverkehr", points: 3, difficulty: 0.6, tags: ["parken", "halten", "kreisfahrbahn"],
    text: "Darf ein Lieferwagen zum Entladen kurz am Rand der Kreisfahrbahn halten?",
    answers: [t("Nein, auf der Kreisfahrbahn ist das Halten verboten, auch zum Be- oder Entladen"), f("Ja, bis zu drei Minuten wie im eingeschränkten Halteverbot", "Das Haltverbot im Kreisverkehr kennt diese Ausnahme nicht."), f("Ja, wenn das Warnblinklicht eingeschaltet ist", "Das Warnblinklicht erlaubt kein verbotenes Halten.")],
    explanation: "Auf der Kreisfahrbahn darf nicht gehalten werden; das Zeichen 215 ordnet das Haltverbot an. Ausgenommen ist nur verkehrsbedingtes Warten. Be- und Entladen muss außerhalb des Kreisverkehrs erfolgen.",
    legalReference: "§ 9a Abs. 2 StVO; Zeichen 215",
  }),
  q({
    code: "own-kreisverkehr-032", topic: "kreisverkehr", points: 4, difficulty: 0.7, tags: ["rechts_vor_links", "kreisfahrbahn", "einfahren", "ohne_zeichen"],
    text: "Sie fahren in einem unbeschilderten Kreisverkehr. An der nächsten Zufahrt von rechts will ein Fahrzeug einfahren. Was gilt?",
    answers: [t("Sie müssen dem einfahrenden Fahrzeug Vorfahrt gewähren, weil es von rechts kommt"), f("Sie haben Vorfahrt, weil Sie im Kreis fahren", "Ohne Zeichen 205 an der Zufahrt gilt keine Vorfahrt für den Kreis."), f("Wer schneller ist, fährt zuerst", "Geschwindigkeit begründet keine Vorfahrt.")],
    explanation: "Ohne Beschilderung gilt an jeder Zufahrt rechts vor links. Wer im Kreis fährt, muss den Einfahrenden von rechts durchfahren lassen. Solche Kreisverkehre sind selten, aber in Wohngebieten anzutreffen.",
    legalReference: "§ 8 Abs. 1 StVO",
  }),
  q({
    code: "own-kreisverkehr-033", topic: "kreisverkehr", points: 3, difficulty: 0.55, tags: ["ausfahren", "fussgaenger", "ohne_zebrastreifen", "abbiegen"],
    text: "An der Ausfahrt des Kreisverkehrs gibt es keinen Zebrastreifen. Ein Fußgänger überquert dort die Straße. Was gilt?",
    answers: [t("Sie müssen den Fußgänger durchgehen lassen, weil das Ausfahren ein Abbiegevorgang ist"), f("Der Fußgänger muss warten, weil ohne Zebrastreifen Fahrzeuge Vorrang haben", "Beim Abbiegen sind querende Fußgänger auch ohne Zebrastreifen durchzulassen."), f("Sie dürfen hupen, damit der Fußgänger stehen bleibt", "Hupen ist hier nicht zulässig.")],
    explanation: "Das Verlassen des Kreisverkehrs ist ein Abbiegevorgang. Wer abbiegt, muss auf Fußgänger, die die Fahrbahn der Ausfahrt überqueren, besondere Rücksicht nehmen und sie durchgehen lassen.",
    legalReference: "§ 9 Abs. 3 StVO",
  }),
  q({
    code: "own-kreisverkehr-034", topic: "kreisverkehr", points: 3, difficulty: 0.6, tags: ["radverkehr", "haifischzaehne", "radweg", "einfahren"],
    text: "Vor der Zufahrt zum Kreisverkehr kreuzt ein Radweg mit Vorrang; auf Ihrer Fahrbahn sind Haifischzähne markiert. Was gilt?",
    answers: [t("Sie müssen den Radfahrenden auf dem kreuzenden Radweg Vorfahrt gewähren, bevor Sie zur Kreisfahrbahn vorfahren"), t("Danach müssen Sie erneut dem Verkehr auf der Kreisfahrbahn Vorfahrt gewähren"), f("Die Haifischzähne bedeuten, dass Sie Vorfahrt haben", "Haifischzähne zeigen die Wartepflicht an."), f("Radfahrende müssen an Kreisverkehren immer warten", "Das hängt von der Beschilderung und Markierung ab; hier haben sie Vorrang.")],
    explanation: "Haifischzähne (Zeichen 342) markieren die Stelle, an der Vorfahrt zu gewähren ist. An Kreisverkehren mit umlaufendem Radweg müssen oft zuerst die Radfahrenden und dann der Verkehr im Kreis durchgelassen werden.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 342); § 8 Abs. 1a StVO",
  }),
  q({
    code: "own-kreisverkehr-035", topic: "kreisverkehr", points: 3, difficulty: 0.55, tags: ["einfahren", "gefahrzeichen", "verkehrszeichen"],
    text: "Außerorts sehen Sie auf einer Landstraße mit 100 km/h das Zeichen 215 als Vorankündigung mit Zusatzzeichen „in 300 m“. Was tun Sie?",
    answers: [t("Rechtzeitig die Geschwindigkeit deutlich verringern, weil Kreisverkehre nur langsam durchfahren werden können"), f("Mit 100 km/h weiterfahren und erst am Kreisverkehr bremsen", "Zu spätes Bremsen führt zu Auffahrunfällen und zum Ausbrechen im Kreis."), f("Das Zeichen ignorieren, weil es 300 m entfernt ist", "Bei 100 km/h sind 300 m in etwa elf Sekunden zurückgelegt.")],
    explanation: "Vorankündigungen dienen dazu, sich rechtzeitig auf den Kreisverkehr einzustellen. Bei hoher Geschwindigkeit muss die Verzögerung früh beginnen, damit die Einfahrt sicher gelingt.",
    legalReference: "§ 3 Abs. 1 StVO; § 39 Abs. 3 StVO",
  }),
  q({
    code: "own-kreisverkehr-036", topic: "kreisverkehr", points: 3, difficulty: 0.55, tags: ["mehrstreifig", "kreisfahrbahn", "fahrstreifenwechsel", "innerorts"],
    text: "Im zweistreifigen Kreisverkehr wollen Sie vom äußeren auf den inneren Fahrstreifen wechseln. Was gilt?",
    answers: [t("Der Wechsel ist ein normaler Fahrstreifenwechsel: blinken, Spiegel, Schulterblick und niemanden gefährden"), f("Fahrstreifenwechsel sind im Kreisverkehr verboten", "Sie sind erlaubt, wenn die Regeln des Fahrstreifenwechsels eingehalten werden."), f("Der innere Fahrstreifen ist nur für Fahrzeuge reserviert, die den Kreis ganz durchfahren", "Eine solche allgemeine Regel gibt es nicht; maßgeblich sind Markierungen und Zeichen.")],
    explanation: "Im mehrstreifigen Kreisverkehr gelten die allgemeinen Regeln für den Fahrstreifenwechsel. Er muss angekündigt werden und darf niemanden gefährden.",
    legalReference: "§ 7 Abs. 5 StVO",
  }),
  q({
    code: "own-kreisverkehr-037", topic: "kreisverkehr", points: 3, difficulty: 0.5, tags: ["vorfahrt_beschildert", "stoppschild", "einfahren"],
    text: "An der Zufahrt zu einem Kreisverkehr steht statt des Zeichens 205 das Stoppschild (Zeichen 206). Was gilt?",
    answers: [t("Sie müssen an der Haltlinie anhalten, auch wenn der Kreis leer ist, und dann dem Verkehr im Kreis Vorfahrt gewähren"), f("Sie dürfen ohne Anhalten einfahren, wenn der Kreis frei ist", "Das Stoppschild verlangt immer ein Anhalten."), f("Das Stoppschild gilt an Kreisverkehren nicht", "Es gilt wie an jeder anderen Einmündung.")],
    explanation: "Ein Stoppschild an der Zufahrt verlangt ein vollständiges Anhalten an der Haltlinie, unabhängig vom Verkehr. Anschließend ist dem Verkehr auf der Kreisfahrbahn Vorfahrt zu gewähren.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 206); § 8 Abs. 1a StVO",
  }),
  q({
    code: "own-kreisverkehr-038", topic: "kreisverkehr", points: 3, difficulty: 0.6, tags: ["ausfahren", "blinken", "fehlverhalten", "vertrauen"],
    text: "Sie fahren im Kreisverkehr weiter und blinken versehentlich rechts. Ein Wartender an der nächsten Zufahrt fährt daraufhin ein. Welche Aussagen sind richtig?",
    answers: [t("Falsches Blinken ist ein Verkehrsverstoß und kann zu einer Mithaftung bei einem Unfall führen"), t("Der Einfahrende durfte sich nicht allein auf den Blinker verlassen"), f("Der Einfahrende trägt die volle Verantwortung, weil Fahrzeuge im Kreis immer Vorfahrt haben", "Wer durch falsches Blinken eine Fehlreaktion auslöst, kann mithaften."), f("Falsches Blinken hat keine rechtliche Bedeutung", "Fahrtrichtungsanzeiger sind verbindliche Zeichen für andere.")],
    explanation: "Blinker sind verbindliche Ankündigungen. Wer falsch blinkt, verstößt gegen die StVO und kann bei einem Unfall mithaften. Wer wartepflichtig ist, darf sich dennoch nicht allein auf den Blinker verlassen, sondern muss das tatsächliche Ausfahren abwarten.",
    legalReference: "§ 9 Abs. 1 StVO; § 8 Abs. 2 StVO",
  }),
  q({
    code: "own-kreisverkehr-039", topic: "kreisverkehr", points: 2, difficulty: 0.4, tags: ["verkehrszeichen", "kreisverkehr", "halten"],
    text: "Welche Regelungen ordnet das Zeichen 215 (Kreisverkehr) an?",
    answers: [t("Die Fahrtrichtung rechts herum"), t("Das Verbot, auf der Kreisfahrbahn zu halten"), f("Die Vorfahrt des Verkehrs im Kreis, auch ohne Zeichen 205", "Die Vorfahrt des Kreisverkehrs besteht nur zusammen mit Zeichen 205."), f("Eine Höchstgeschwindigkeit von 30 km/h", "Das Zeichen regelt keine Geschwindigkeit.")],
    explanation: "Zeichen 215 schreibt die Fahrtrichtung rechts herum vor und verbietet das Halten auf der Kreisfahrbahn. Die Vorfahrt für den Kreis ergibt sich nur aus dem zusätzlich aufgestellten Zeichen 205.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 215); § 8 Abs. 1a StVO",
  }),
];
