// Übungsfragen zum Thema "recht" (eigene Formulierungen, kein amtlicher Prüfungsinhalt).
import type { Question } from "../types";
import { q, t, f } from "./_helpers";

export const recht: readonly Question[] = [
  q({
    code: "own-recht-001", topic: "recht", points: 2, difficulty: 0.1, tags: ["probezeit"],
    text: "Wie lange dauert die Probezeit nach dem erstmaligen Erwerb der Fahrerlaubnis?",
    answers: [t("2 Jahre"), f("1 Jahr", "Die Probezeit ist länger."), f("3 Jahre", "Regulär sind es zwei Jahre; eine Verlängerung gibt es nur nach bestimmten Verstößen.")],
    explanation: "Die Probezeit beträgt zwei Jahre. Bei einem schwerwiegenden Verstoß wird ein Aufbauseminar angeordnet und die Probezeit um zwei Jahre verlängert.",
    legalReference: "§ 2a StVG",
  }),
  q({
    code: "own-recht-002", topic: "recht", points: 3, difficulty: 0.4, tags: ["probezeit", "aufbauseminar"],
    text: "Welche Folgen hat ein schwerwiegender Verstoß (A-Verstoß) während der Probezeit?",
    answers: [t("Die Teilnahme an einem Aufbauseminar wird angeordnet"), t("Die Probezeit verlängert sich um zwei Jahre"), f("Die Fahrerlaubnis erlischt automatisch", "Ein Entzug erfolgt nicht automatisch; zunächst folgen Aufbauseminar und Verlängerung.")],
    explanation: "Ein schwerwiegender Verstoß in der Probezeit führt zur Anordnung eines Aufbauseminars und zur Verlängerung der Probezeit auf insgesamt vier Jahre.",
    legalReference: "§ 2a StVG",
  }),
  q({
    code: "own-recht-003", topic: "recht", points: 2, difficulty: 0.3, tags: ["theoriepruefung", "pruefung"],
    text: "Sie haben die theoretische Prüfung bestanden. Innerhalb welcher Frist müssen Sie die praktische Prüfung bestehen, damit die Theorieprüfung gültig bleibt?",
    answers: [t("Innerhalb von 12 Monaten"), f("Innerhalb von 6 Monaten", "Die Frist ist länger."), f("Es gibt keine Frist", "Die Theorieprüfung verliert nach Ablauf der Frist ihre Gültigkeit.")],
    explanation: "Die bestandene theoretische Prüfung ist zwölf Monate gültig. Wird die praktische Prüfung nicht innerhalb dieser Frist bestanden, muss die Theorie erneut abgelegt werden.",
    legalReference: "§ 18 FeV",
  }),
  q({
    code: "own-recht-004", topic: "recht", points: 2, difficulty: 0.3, tags: ["pruefung", "sperrfrist"],
    text: "Sie haben die praktische Prüfung nicht bestanden. Wann dürfen Sie frühestens erneut zur Prüfung antreten?",
    answers: [t("Frühestens nach zwei Wochen"), f("Bereits am nächsten Tag", "Nach dem Nichtbestehen gilt eine Wartefrist."), f("Frühestens nach drei Monaten", "Die Wartefrist ist deutlich kürzer.")],
    explanation: "Nach einer nicht bestandenen Prüfung gilt eine Sperrfrist von zwei Wochen. Die Zeit sollte für gezielte Nachschulung genutzt werden.",
    legalReference: "§ 18 FeV",
  }),
  q({
    code: "own-recht-005", topic: "recht", points: 3, difficulty: 0.4, tags: ["bf17", "begleitperson"],
    text: "Welche Voraussetzungen muss eine Begleitperson beim Begleiteten Fahren ab 17 (BF17) erfüllen?",
    answers: [t("Mindestens 30 Jahre alt"), t("Seit mindestens fünf Jahren im Besitz der Fahrerlaubnis Klasse B"), t("Höchstens ein Punkt im Fahreignungsregister"), f("Mindestens 21 Jahre alt", "Das Mindestalter der Begleitperson liegt höher.")],
    explanation: "Eine Begleitperson muss mindestens 30 Jahre alt sein, seit mindestens fünf Jahren die Klasse B besitzen und darf zum Zeitpunkt der Eintragung höchstens einen Punkt im Fahreignungsregister haben.",
    legalReference: "§ 48a FeV",
  }),
  q({
    code: "own-recht-006", topic: "recht", points: 3, difficulty: 0.5, tags: ["b197", "automatik", "schaltung"],
    text: "Was gilt für die Ausbildung mit der Schlüsselzahl B197 (Automatikprüfung ohne Automatikbeschränkung)?",
    answers: [t("Mindestens zehn Fahrstunden müssen auf einem Fahrzeug mit Schaltgetriebe absolviert werden"), t("Eine mindestens 15-minütige Testfahrt auf einem Schaltwagen wird von der Fahrschule bescheinigt"), f("Die praktische Prüfung muss auf einem Schaltwagen abgelegt werden", "Die Prüfung findet auf einem Automatikfahrzeug statt; die Schaltkompetenz wird vorher in der Fahrschule nachgewiesen.")],
    explanation: "Bei B197 wird die praktische Prüfung auf einem Automatikfahrzeug abgelegt. Voraussetzung sind mindestens zehn Fahrstunden auf einem Schaltwagen und eine bescheinigte Testfahrt von mindestens 15 Minuten; der Führerschein enthält dann keine Automatikbeschränkung.",
    legalReference: "Anlage 7 FeV, § 17 FeV",
  }),
  q({
    code: "own-recht-007", topic: "recht", points: 3, difficulty: 0.5, tags: ["b196", "kraftrad"],
    text: "Was trifft auf die Schlüsselzahl B196 zu?",
    answers: [t("Sie erlaubt das Führen von Krafträdern der Klasse A1 (bis 125 cm³ und 11 kW) mit einer Fahrerlaubnis der Klasse B"), t("Voraussetzung sind ein Mindestalter von 25 Jahren, mindestens fünf Jahre Klasse B und eine Fahrschulschulung ohne Prüfung"), f("Sie gilt auch im EU-Ausland", "B196 ist eine nationale Regelung und gilt nur in Deutschland.")],
    explanation: "Mit B196 dürfen Inhaber der Klasse B nach einer Schulung Leichtkrafträder bis 125 cm³ und 11 kW fahren. Es gibt keine Prüfung, dafür Mindestalter 25, fünf Jahre Klasse B und die Beschränkung auf Deutschland.",
    legalReference: "§ 6 Abs. 4 FeV; Anlage 7b FeV",
  }),
  q({
    code: "own-recht-008", topic: "recht", points: 2, difficulty: 0.3, tags: ["sonderfahrten", "ausbildung"],
    text: "Wie viele Sonderfahrten sind in der Ausbildung für Klasse B mindestens vorgeschrieben?",
    answers: [t("5 Überlandfahrten, 4 Autobahnfahrten und 3 Fahrten bei Dunkelheit"), f("3 Überlandfahrten, 3 Autobahnfahrten und 3 Nachtfahrten", "Die vorgeschriebenen Zahlen sind höher."), f("12 Autobahnfahrten", "Die Sonderfahrten verteilen sich auf drei Arten.")],
    explanation: "Die Fahrschüler-Ausbildungsordnung schreibt für Klasse B mindestens fünf Überlandfahrten, vier Autobahnfahrten und drei Fahrten bei Dunkelheit zu je 45 Minuten vor.",
    mnemonic: "5-4-3: Überland, Autobahn, Nacht.",
    legalReference: "§ 5 FahrschAusbO",
  }),
  q({
    code: "own-recht-009", topic: "recht", points: 3, difficulty: 0.4, tags: ["klasse_b", "fahrerlaubnisklassen"],
    text: "Welche Fahrzeuge dürfen Sie mit der Fahrerlaubnis der Klasse B führen?",
    answers: [t("Kraftfahrzeuge mit einer zulässigen Gesamtmasse bis 3.500 kg"), t("Fahrzeuge mit höchstens acht Sitzplätzen außer dem Fahrersitz"), t("Solche Fahrzeuge mit einem Anhänger bis 750 kg zulässiger Gesamtmasse"), f("Kraftomnibusse mit mehr als acht Fahrgastplätzen", "Dafür ist eine Busklasse erforderlich.")],
    explanation: "Klasse B umfasst Kraftfahrzeuge bis 3.500 kg zulässiger Gesamtmasse mit höchstens acht Sitzplätzen außer dem Fahrersitz. Ein Anhänger bis 750 kg darf immer mitgeführt werden, ein schwererer, wenn die Kombination 3.500 kg nicht überschreitet.",
    legalReference: "§ 6 FeV",
  }),
  q({
    code: "own-recht-010", topic: "recht", points: 2, difficulty: 0.2, tags: ["fuehrerschein", "mitfuehrpflicht"],
    text: "Sie haben Ihren Führerschein zu Hause vergessen und fahren trotzdem. Was gilt?",
    answers: [t("Das ist eine Ordnungswidrigkeit, denn der Führerschein muss beim Fahren mitgeführt werden"), f("Die Fahrerlaubnis erlischt dadurch", "Die Fahrerlaubnis bleibt bestehen; nur der Nachweis fehlt."), f("Ein Foto des Führerscheins auf dem Handy genügt", "Ein Foto ersetzt das Dokument nicht.")],
    explanation: "Der Führerschein ist beim Führen eines Kraftfahrzeugs mitzuführen und auf Verlangen vorzuzeigen. Wer ihn nicht dabeihat, handelt ordnungswidrig (Verwarnungsgeld 10 Euro), verliert aber nicht die Fahrerlaubnis.",
    legalReference: "§ 4 Abs. 2 FeV",
  }),
  q({
    code: "own-recht-011", topic: "recht", points: 2, difficulty: 0.3, tags: ["theoriepruefung", "fehlerpunkte"],
    text: "Wie viele Fehlerpunkte dürfen Sie in der theoretischen Prüfung für Klasse B (Ersterwerb) höchstens haben?",
    answers: [t("10 Fehlerpunkte, wobei nicht zwei Fragen mit je fünf Punkten falsch beantwortet sein dürfen"), f("5 Fehlerpunkte", "Die Grenze liegt höher."), f("15 Fehlerpunkte", "Die Grenze liegt niedriger.")],
    explanation: "Beim Ersterwerb der Klasse B werden 30 Fragen gestellt. Bestanden ist die Prüfung mit höchstens zehn Fehlerpunkten, sofern nicht zwei Fragen mit fünf Punkten falsch beantwortet wurden.",
    legalReference: "Anlage 7 FeV",
  }),
  q({
    code: "own-recht-012", topic: "recht", points: 2, difficulty: 0.3, tags: ["punktesystem", "fahreignungsregister"],
    text: "Ab wie vielen Punkten im Fahreignungsregister wird die Fahrerlaubnis entzogen?",
    answers: [t("Ab 8 Punkten"), f("Ab 18 Punkten", "Das war die Grenze im früheren Punktesystem; heute gilt eine niedrigere."), f("Ab 5 Punkten", "Bei sechs Punkten gibt es eine Verwarnung, der Entzug folgt erst später.")],
    explanation: "Im Fahreignungs-Bewertungssystem wird die Fahrerlaubnis bei acht Punkten entzogen. Vorher gibt es bei vier bis fünf Punkten eine Ermahnung und bei sechs bis sieben Punkten eine Verwarnung.",
    legalReference: "§ 4 StVG",
  }),
  q({
    code: "own-recht-013", topic: "recht", points: 3, difficulty: 0.6, tags: ["klasse_b", "anhaenger", "fahrerlaubnisklassen"],
    text: "Sie besitzen nur die Klasse B. Welche Kombinationen dürfen Sie fahren?",
    answers: [t("Pkw mit 2.000 kg zulässiger Gesamtmasse und Anhänger mit 750 kg zulässiger Gesamtmasse"), t("Pkw mit 2.000 kg zulässiger Gesamtmasse und Anhänger mit 1.500 kg zulässiger Gesamtmasse"), f("Pkw mit 2.500 kg zulässiger Gesamtmasse und Anhänger mit 1.500 kg zulässiger Gesamtmasse", "Die Kombination hätte 4.000 kg; über 3.500 kg ist mindestens B96 erforderlich."), f("Pkw mit 3.000 kg zulässiger Gesamtmasse und Anhänger mit 1.000 kg zulässiger Gesamtmasse", "Die Kombination hätte 4.000 kg und überschreitet damit die Grenze der Klasse B.")],
    explanation: "Mit Klasse B darf ein Anhänger bis 750 kg zulässiger Gesamtmasse immer gezogen werden. Ein schwererer Anhänger ist erlaubt, wenn die zulässige Gesamtmasse der Kombination 3.500 kg nicht überschreitet. Bis 4.250 kg genügt B96, darüber ist BE nötig.",
    legalReference: "§ 6 Abs. 1 FeV",
  }),
  q({
    code: "own-recht-014", topic: "recht", points: 3, difficulty: 0.65, tags: ["b96", "be", "anhaenger", "fahrerlaubnisklassen"],
    text: "Was unterscheidet die Schlüsselzahl B96 von der Klasse BE?",
    answers: [t("B96 erlaubt Kombinationen bis 4.250 kg zulässiger Gesamtmasse und wird nach einer Fahrschulschulung ohne Prüfung eingetragen"), t("BE erlaubt Anhänger bis 3.500 kg zulässiger Gesamtmasse und erfordert eine praktische Prüfung"), f("B96 erlaubt schwerere Anhänger als BE", "Es ist umgekehrt: BE ist die umfangreichere Berechtigung."), f("Für BE ist eine zusätzliche theoretische Prüfung erforderlich", "Beim Erwerb von BE zu vorhandener Klasse B entfällt die theoretische Prüfung.")],
    explanation: "B96 ist eine Erweiterung der Klasse B nach einer Schulung ohne Prüfung und hebt die Grenze der Kombination auf 4.250 kg an. BE erlaubt Anhänger bis 3.500 kg zulässiger Gesamtmasse hinter einem Zugfahrzeug der Klasse B und erfordert nur eine praktische Prüfung.",
    legalReference: "§ 6 FeV; Anlage 7a FeV",
  }),
  q({
    code: "own-recht-015", topic: "recht", points: 3, difficulty: 0.55, tags: ["klasse_b", "fahrerlaubnisklassen", "am", "l"],
    text: "Welche Klassen sind in der Fahrerlaubnis der Klasse B eingeschlossen?",
    answers: [t("Klasse AM"), t("Klasse L"), f("Klasse A1", "A1 ist nur über die Schlüsselzahl B196 nach einer Schulung und nur in Deutschland fahrbar."), f("Klasse T", "Klasse T für land- und forstwirtschaftliche Zugmaschinen ist nicht enthalten.")],
    explanation: "Die Klasse B schließt die Klassen AM (leichte zweirädrige Kraftfahrzeuge und Kleinkrafträder bis 45 km/h) und L (Zugmaschinen bis 40 km/h für Land- und Forstwirtschaft) ein. A1 wird nur mit B196 zugänglich.",
    legalReference: "§ 6 Abs. 3 FeV",
  }),
  q({
    code: "own-recht-016", topic: "recht", points: 3, difficulty: 0.6, tags: ["probezeit", "aufbauseminar", "b_verstoss"],
    text: "Welche Folgen haben zwei weniger schwerwiegende Verstöße (B-Verstöße) während der Probezeit?",
    answers: [t("Sie werden wie ein schwerwiegender Verstoß behandelt: Aufbauseminar und Verlängerung der Probezeit"), f("Keine, weil nur A-Verstöße in der Probezeit zählen", "Zwei B-Verstöße entsprechen einem A-Verstoß."), f("Der sofortige Entzug der Fahrerlaubnis", "Beim ersten Anlass wird zunächst ein Aufbauseminar angeordnet.")],
    explanation: "Ein A-Verstoß oder zwei B-Verstöße in der Probezeit führen zur Anordnung eines Aufbauseminars und zur Verlängerung der Probezeit um zwei Jahre. Weitere Verstöße führen zur Verwarnung mit Empfehlung einer verkehrspsychologischen Beratung und schließlich zum Entzug.",
    legalReference: "§ 2a StVG",
  }),
  q({
    code: "own-recht-017", topic: "recht", points: 3, difficulty: 0.7, tags: ["probezeit", "aufbauseminar", "entzug"],
    text: "Sie haben in der Probezeit bereits ein Aufbauseminar besucht und begehen erneut einen A-Verstoß. Was folgt?",
    answers: [t("Eine schriftliche Verwarnung mit der Empfehlung, an einer verkehrspsychologischen Beratung teilzunehmen"), f("Sofort der Entzug der Fahrerlaubnis", "Der Entzug folgt erst beim nächsten Verstoß nach der Verwarnung."), f("Ein zweites Aufbauseminar", "Ein Aufbauseminar wird nur einmal angeordnet.")],
    explanation: "Das Stufensystem der Probezeit: Erst Aufbauseminar und Verlängerung, dann bei erneutem Verstoß Verwarnung mit Empfehlung einer verkehrspsychologischen Beratung, dann bei einem weiteren Verstoß Entzug der Fahrerlaubnis.",
    legalReference: "§ 2a Abs. 2 StVG",
  }),
  q({
    code: "own-recht-018", topic: "recht", points: 3, difficulty: 0.6, tags: ["probezeit", "aufbauseminar", "frist"],
    text: "Die Behörde ordnet in der Probezeit ein Aufbauseminar an. Sie nehmen innerhalb der gesetzten Frist nicht teil. Was passiert?",
    answers: [t("Die Fahrerlaubnis wird entzogen, bis die Teilnahme nachgewiesen ist"), f("Es wird lediglich ein Bußgeld fällig", "Die Nichtteilnahme führt zum Entzug der Fahrerlaubnis."), f("Nichts, das Seminar ist eine freiwillige Empfehlung", "Ein angeordnetes Aufbauseminar ist verpflichtend.")],
    explanation: "Wird ein angeordnetes Aufbauseminar nicht innerhalb der Frist absolviert, entzieht die Fahrerlaubnisbehörde die Fahrerlaubnis. Erst mit dem Nachweis der Teilnahme kann sie neu erteilt werden.",
    legalReference: "§ 2a Abs. 3 StVG",
  }),
  q({
    code: "own-recht-019", topic: "recht", points: 3, difficulty: 0.55, tags: ["probezeit", "beginn", "bf17"],
    text: "Wann beginnt die Probezeit?",
    answers: [t("Mit der Aushändigung des Führerscheins nach bestandener Prüfung"), t("Beim Begleiteten Fahren ab 17 bereits mit der Aushändigung der Prüfungsbescheinigung"), f("Erst mit dem 18. Geburtstag", "Beim BF17 läuft die Probezeit schon ab 17."), f("Mit dem Beginn der Fahrschulausbildung", "Die Ausbildung zählt nicht zur Probezeit.")],
    explanation: "Die Probezeit beginnt mit der Erteilung der Fahrerlaubnis, also mit Aushändigung des Führerscheins beziehungsweise der Prüfungsbescheinigung beim BF17. Wer mit 17 beginnt, hat die Probezeit mit 19 in der Regel hinter sich.",
    legalReference: "§ 2a Abs. 1 StVG; § 48a FeV",
  }),
  q({
    code: "own-recht-020", topic: "recht", points: 3, difficulty: 0.7, tags: ["bf17", "begleitperson", "alkohol"],
    text: "Was gilt für die Fahrt beim Begleiteten Fahren ab 17?",
    answers: [t("Die Begleitperson darf nicht mit 0,5 Promille oder mehr begleiten und nicht unter Wirkung berauschender Mittel stehen"), t("Die Prüfungsbescheinigung ist mitzuführen und auf Verlangen auszuhändigen"), f("Die Begleitperson darf bei Bedarf selbst ins Lenkrad greifen", "Die Begleitperson ist kein Fahrlehrer; sie darf nur beraten."), f("Es dürfen mehrere Begleitpersonen gleichzeitig eingetragen sein, aber nur eine mitfahren", "Mehrere Begleitpersonen können eingetragen sein; mindestens eine eingetragene muss mitfahren.")],
    explanation: "Die Begleitperson unterstützt nur durch Rat; sie darf nicht selbst eingreifen. Für sie gilt die 0,5-Promille-Grenze und ein Verbot berauschender Mittel. Die Prüfungsbescheinigung muss mitgeführt werden.",
    legalReference: "§ 48a FeV",
  }),
  q({
    code: "own-recht-021", topic: "recht", points: 3, difficulty: 0.65, tags: ["bf17", "begleitperson", "entzug"],
    text: "Ein 17-Jähriger fährt mit der BF17-Prüfungsbescheinigung ohne eingetragene Begleitperson. Welche Folgen hat das?",
    answers: [t("Die Fahrerlaubnis wird widerrufen"), t("Es wird ein Bußgeld verhängt und ein Punkt eingetragen"), t("Vor der Neuerteilung ist die Teilnahme an einem Aufbauseminar erforderlich"), f("Es liegt Fahren ohne Fahrerlaubnis nach § 21 StVG vor", "Die Fahrerlaubnis besteht; die Auflage der Begleitung wurde verletzt, was eine Ordnungswidrigkeit ist.")],
    explanation: "Das Fahren ohne Begleitperson verstößt gegen die Auflage der Prüfungsbescheinigung. Die Fahrerlaubnis wird widerrufen, es gibt ein Bußgeld und einen Punkt, und die Fahrerlaubnis wird erst nach Teilnahme an einem Aufbauseminar wieder erteilt.",
    legalReference: "§ 48a FeV; § 2a StVG",
  }),
  q({
    code: "own-recht-022", topic: "recht", points: 3, difficulty: 0.6, tags: ["punktesystem", "fahreignungsregister", "massnahmen"],
    text: "Welche Maßnahmen sieht das Fahreignungs-Bewertungssystem in welcher Reihenfolge vor?",
    answers: [t("Bei 4 bis 5 Punkten eine Ermahnung, bei 6 bis 7 Punkten eine Verwarnung, bei 8 Punkten den Entzug der Fahrerlaubnis"), f("Bei 8 Punkten eine Verwarnung und bei 18 Punkten den Entzug", "18 Punkte gab es im alten System; heute wird bei 8 Punkten entzogen."), f("Bei 3 Punkten bereits ein Fahrverbot", "Punkte allein lösen kein Fahrverbot aus; Fahrverbote werden bei bestimmten Verstößen direkt verhängt.")],
    explanation: "Das Punktesystem hat drei Stufen: Ermahnung bei 4 bis 5 Punkten, Verwarnung bei 6 bis 7 Punkten, Entzug der Fahrerlaubnis bei 8 Punkten. Bei Ermahnung und Verwarnung wird auf das Fahreignungsseminar hingewiesen.",
    legalReference: "§ 4 Abs. 5 StVG",
  }),
  q({
    code: "own-recht-023", topic: "recht", points: 3, difficulty: 0.7, tags: ["punktesystem", "fahreignungsregister", "punkte"],
    text: "Wie viele Punkte werden für einzelne Verstöße im Fahreignungsregister eingetragen?",
    answers: [t("1 Punkt für eine verkehrssicherheitsbeeinträchtigende Ordnungswidrigkeit"), t("2 Punkte für eine besonders verkehrssicherheitsbeeinträchtigende Ordnungswidrigkeit, zum Beispiel mit Fahrverbot, oder eine Straftat ohne Entzug"), t("3 Punkte für eine Straftat mit Entzug der Fahrerlaubnis"), f("5 Punkte für Alkoholfahrten ab 1,1 Promille", "Mehr als 3 Punkte gibt es für einen Verstoß nicht.")],
    explanation: "Je nach Schwere gibt es 1, 2 oder 3 Punkte. Ein Punkt für einfache sicherheitsrelevante Ordnungswidrigkeiten, zwei für schwere Ordnungswidrigkeiten und Straftaten ohne Entzug, drei für Straftaten mit Entzug der Fahrerlaubnis.",
    legalReference: "§ 4 Abs. 2 StVG",
  }),
  q({
    code: "own-recht-024", topic: "recht", points: 2, difficulty: 0.6, tags: ["punktesystem", "tilgung", "fahreignungsregister"],
    text: "Nach welcher Zeit werden Punkte im Fahreignungsregister getilgt?",
    answers: [t("1-Punkt-Eintragungen nach 2,5 Jahren, 2-Punkt-Eintragungen nach 5 Jahren, 3-Punkt-Eintragungen nach 10 Jahren"), f("Alle Punkte nach 2 Jahren", "Die Tilgungsfrist hängt von der Schwere des Verstoßes ab."), f("Punkte werden nie getilgt, solange man eine Fahrerlaubnis besitzt", "Punkte verjähren nach festen Fristen.")],
    explanation: "Jede Eintragung hat eine eigene Tilgungsfrist: 2,5 Jahre bei einem Punkt, 5 Jahre bei zwei Punkten und 10 Jahre bei drei Punkten. Neue Verstöße hemmen die Tilgung älterer Eintragungen nicht mehr.",
    legalReference: "§ 29 StVG",
  }),
  q({
    code: "own-recht-025", topic: "recht", points: 2, difficulty: 0.55, tags: ["punktesystem", "fahreignungsseminar", "punkteabbau"],
    text: "Wie können Sie Punkte im Fahreignungsregister freiwillig abbauen?",
    answers: [t("Durch die Teilnahme an einem Fahreignungsseminar bei einem Stand von 1 bis 5 Punkten; abgebaut wird ein Punkt, höchstens einmal in fünf Jahren"), f("Durch eine freiwillige Nachschulung in der Fahrschule, die drei Punkte abbaut", "Der Abbau ist auf einen Punkt beschränkt und nur über das Fahreignungsseminar möglich."), f("Punkte können nicht freiwillig abgebaut werden", "Das Fahreignungsseminar ermöglicht den Abbau eines Punktes.")],
    explanation: "Wer 1 bis 5 Punkte hat, kann freiwillig ein Fahreignungsseminar besuchen und damit einen Punkt abbauen. Das ist nur alle fünf Jahre möglich; ab 6 Punkten ist kein Abbau mehr möglich.",
    legalReference: "§ 4 Abs. 7 StVG",
  }),
  q({
    code: "own-recht-026", topic: "recht", points: 3, difficulty: 0.65, tags: ["fahrverbot", "entzug", "sperrfrist"],
    text: "Worin unterscheiden sich Fahrverbot und Entzug der Fahrerlaubnis?",
    answers: [t("Das Fahrverbot ist zeitlich befristet, bei Ordnungswidrigkeiten auf einen bis drei Monate; danach wird der Führerschein ohne neue Prüfung zurückgegeben"), t("Beim Entzug erlischt die Fahrerlaubnis; nach der Sperrfrist muss sie neu beantragt werden, gegebenenfalls mit MPU"), f("Das Fahrverbot gilt nur für die Klasse, mit der der Verstoß begangen wurde", "Das Fahrverbot gilt in der Regel für Kraftfahrzeuge jeder Art."), f("Nach einem Entzug bekommt man den Führerschein nach Ablauf der Sperrfrist automatisch zurück", "Die Fahrerlaubnis muss neu beantragt werden; eine automatische Rückgabe gibt es nicht.")],
    explanation: "Das Fahrverbot ist zeitlich begrenzt (bei Ordnungswidrigkeiten ein bis drei Monate, als Nebenstrafe bei Straftaten bis zu sechs Monate); der Führerschein kommt in amtliche Verwahrung. Beim Entzug erlischt die Fahrerlaubnis vollständig und muss nach der Sperrfrist neu beantragt werden.",
    legalReference: "§ 25 StVG; § 44 StGB; § 69 StGB",
  }),
  q({
    code: "own-recht-027", topic: "recht", points: 3, difficulty: 0.6, tags: ["fahrverbot", "fuehrerschein", "abgabe"],
    text: "Gegen Sie wurde ein einmonatiges Fahrverbot rechtskräftig verhängt. Was gilt?",
    answers: [t("Der Führerschein muss für die Dauer des Fahrverbots in amtliche Verwahrung gegeben werden"), t("Wer während des Fahrverbots fährt, begeht die Straftat des Fahrens ohne Fahrerlaubnis"), f("Sie dürfen weiterhin Fahrzeuge der Klasse AM fahren", "Das Fahrverbot gilt für Kraftfahrzeuge aller Art."), f("Das Fahrverbot beginnt in jedem Fall am Tag der Rechtskraft", "Beim ersten Fahrverbot innerhalb von zwei Jahren kann der Beginn innerhalb von vier Monaten selbst gewählt werden.")],
    explanation: "Während des Fahrverbots wird der Führerschein amtlich verwahrt. Wer trotzdem fährt, macht sich wegen Fahrens ohne Fahrerlaubnis strafbar. Beim ersten Fahrverbot innerhalb von zwei Jahren kann der Antritt innerhalb von vier Monaten nach Rechtskraft frei gewählt werden.",
    legalReference: "§ 25 StVG; § 21 StVG",
  }),
  q({
    code: "own-recht-028", topic: "recht", points: 3, difficulty: 0.6, tags: ["fahren_ohne_fahrerlaubnis", "straftat", "halter"],
    text: "Sie überlassen Ihr Auto einem Freund, von dem Sie wissen, dass er keine Fahrerlaubnis hat. Was gilt?",
    answers: [t("Auch Sie als Halter machen sich strafbar"), t("Der Freund begeht die Straftat des Fahrens ohne Fahrerlaubnis"), f("Nur der Freund ist verantwortlich", "Wer als Halter das Fahren ohne Fahrerlaubnis anordnet oder zulässt, wird ebenfalls bestraft."), f("Es handelt sich um eine Ordnungswidrigkeit mit Verwarnungsgeld", "Fahren ohne Fahrerlaubnis ist eine Straftat.")],
    explanation: "Fahren ohne Fahrerlaubnis ist eine Straftat nach § 21 StVG. Strafbar ist auch der Halter, der das Führen des Fahrzeugs durch eine Person ohne Fahrerlaubnis anordnet oder zulässt.",
    legalReference: "§ 21 Abs. 1 StVG",
  }),
  q({
    code: "own-recht-029", topic: "recht", points: 3, difficulty: 0.55, tags: ["mitfuehrpflicht", "zulassungsbescheinigung", "fahrzeugpapiere"],
    text: "Welche Dokumente müssen Sie beim Fahren eines Pkw mitführen?",
    answers: [t("Den Führerschein"), t("Die Zulassungsbescheinigung Teil I im Original"), f("Die Zulassungsbescheinigung Teil II", "Teil II (früher Fahrzeugbrief) gehört sicher verwahrt nach Hause, nicht ins Fahrzeug."), f("Den Kaufvertrag des Fahrzeugs", "Der Kaufvertrag ist keine Pflichtunterlage.")],
    explanation: "Beim Fahren sind Führerschein und Zulassungsbescheinigung Teil I mitzuführen und auf Verlangen zur Prüfung auszuhändigen. Eine Kopie genügt nicht. Die Zulassungsbescheinigung Teil II sollte nicht im Fahrzeug aufbewahrt werden.",
    legalReference: "§ 4 Abs. 2 FeV; § 11 FZV",
  }),
  q({
    code: "own-recht-030", topic: "recht", points: 2, difficulty: 0.5, tags: ["fuehrerschein", "gueltigkeit", "kartenfuehrerschein"],
    text: "Ein neu ausgestellter Kartenführerschein trägt ein Ablaufdatum. Was bedeutet das?",
    answers: [t("Nur das Dokument ist 15 Jahre gültig und muss dann umgetauscht werden; die Fahrerlaubnis der Klasse B bleibt unbefristet"), f("Nach Ablauf muss eine neue Prüfung abgelegt werden", "Für Klasse B ist beim Umtausch keine Prüfung und keine Untersuchung nötig."), f("Nach Ablauf erlischt die Fahrerlaubnis", "Die Fahrerlaubnis selbst ist unbefristet; nur das Dokument läuft ab.")],
    explanation: "Kartenführerscheine werden auf 15 Jahre befristet ausgestellt, damit Foto und Sicherheitsmerkmale aktuell bleiben. Die Fahrerlaubnis der Klasse B bleibt davon unberührt und unbefristet.",
    legalReference: "§ 24a FeV",
  }),
  q({
    code: "own-recht-031", topic: "recht", points: 2, difficulty: 0.45, tags: ["theoriepruefung", "pruefung", "fragen"],
    text: "Wie ist die theoretische Prüfung für den Ersterwerb der Klasse B aufgebaut?",
    answers: [t("30 Fragen, davon 20 aus dem Grundstoff und 10 aus dem klassenspezifischen Zusatzstoff"), f("40 Fragen ausschließlich aus dem Grundstoff", "Es sind 30 Fragen, darunter auch Zusatzstoff."), f("20 Fragen, davon 10 mit Videosequenzen", "Die Prüfung umfasst 30 Fragen; die Zahl der Videofragen ist nicht festgelegt.")],
    explanation: "Beim Ersterwerb der Klasse B werden 30 Fragen gestellt, 20 aus dem Grundstoff und 10 aus dem Zusatzstoff. Bestanden ist die Prüfung bis 10 Fehlerpunkte, sofern nicht zwei Fragen mit je 5 Punkten falsch beantwortet wurden.",
    legalReference: "Anlage 7 FeV",
  }),
  q({
    code: "own-recht-032", topic: "recht", points: 3, difficulty: 0.7, tags: ["theoriepruefung", "fehlerpunkte", "pruefung"],
    text: "In der theoretischen Prüfung für Klasse B (Ersterwerb) beantworten Sie zwei Fragen mit je 5 Punkten falsch, sonst alles richtig. Sie haben also 10 Fehlerpunkte. Haben Sie bestanden?",
    answers: [t("Nein, weil zwei Fragen mit je 5 Punkten falsch beantwortet wurden"), f("Ja, weil 10 Fehlerpunkte noch zulässig sind", "Die Grenze von 10 Fehlerpunkten gilt nur, wenn nicht zwei 5-Punkte-Fragen falsch sind."), f("Ja, weil nur Fragen mit 2 und 3 Punkten zählen", "Alle Fragen zählen mit ihrer Punktzahl.")],
    explanation: "Die Prüfung ist nicht bestanden, wenn mehr als 10 Fehlerpunkte erreicht werden oder wenn zwei Fragen mit je 5 Punkten falsch beantwortet wurden. Im zweiten Fall reichen genau 10 Fehlerpunkte für das Nichtbestehen.",
    legalReference: "Anlage 7 FeV",
  }),
  q({
    code: "own-recht-033", topic: "recht", points: 2, difficulty: 0.55, tags: ["pruefung", "mindestalter", "antrag"],
    text: "Wie früh vor Erreichen des Mindestalters dürfen die Prüfungen abgelegt werden?",
    answers: [t("Die theoretische Prüfung frühestens drei Monate, die praktische Prüfung frühestens einen Monat vor Erreichen des Mindestalters"), f("Beide Prüfungen frühestens am Tag des Geburtstags", "Beide Prüfungen dürfen vorher abgelegt werden."), f("Beide Prüfungen frühestens sechs Monate vorher", "Sechs Monate vorher darf nur der Antrag gestellt werden.")],
    explanation: "Der Antrag kann frühestens sechs Monate vor dem Mindestalter gestellt werden, die Theorieprüfung drei Monate und die praktische Prüfung einen Monat davor. Der Führerschein wird erst mit Erreichen des Mindestalters ausgehändigt.",
    legalReference: "§ 16 Abs. 1 FeV; § 17 Abs. 1 FeV",
  }),
  q({
    code: "own-recht-034", topic: "recht", points: 2, difficulty: 0.5, tags: ["ausbildung", "theorieunterricht", "fahrschule"],
    text: "Wie viele Theoriestunden sind für den Ersterwerb der Klasse B mindestens vorgeschrieben?",
    answers: [t("12 Doppelstunden Grundstoff und 2 Doppelstunden klassenspezifischer Zusatzstoff zu je 90 Minuten"), f("14 Doppelstunden Grundstoff ohne Zusatzstoff", "Der Zusatzstoff Klasse B umfasst 2 eigene Doppelstunden."), f("Es gibt keine Mindestzahl, nur die Prüfung zählt", "Die Fahrschüler-Ausbildungsordnung schreibt Mindeststunden vor.")],
    explanation: "Der theoretische Unterricht besteht aus 12 Doppelstunden Grundstoff und 2 Doppelstunden Zusatzstoff für Klasse B. Eine Doppelstunde dauert 90 Minuten.",
    legalReference: "§ 4 FahrschAusbO",
  }),
  q({
    code: "own-recht-035", topic: "recht", points: 2, difficulty: 0.55, tags: ["ausbildung", "sonderfahrten", "fahrschule"], kind: "numeric", numericAnswer: 12, tolerance: 0, unit: "Fahrten",
    text: "Wie viele Sonderfahrten zu je 45 Minuten sind für Klasse B insgesamt mindestens vorgeschrieben (Überland, Autobahn und Dunkelheit zusammen)?",
    answers: [],
    explanation: "Vorgeschrieben sind 5 Überlandfahrten, 4 Autobahnfahrten und 3 Fahrten bei Dunkelheit, also zusammen 12 Sonderfahrten zu je 45 Minuten. Die Zahl der übrigen Übungsstunden hängt vom Fortschritt des Fahrschülers ab.",
    mnemonic: "5 + 4 + 3 = 12.",
    legalReference: "§ 5 FahrschAusbO",
  }),
  q({
    code: "own-recht-036", topic: "recht", points: 2, difficulty: 0.5, tags: ["erste_hilfe", "antrag", "fahrerlaubnis"],
    text: "Welche Unterlagen sind für den Antrag auf Erteilung der Fahrerlaubnis Klasse B erforderlich?",
    answers: [t("Ein Nachweis über eine Schulung in Erster Hilfe mit 9 Unterrichtseinheiten"), t("Ein Sehtest, der nicht älter als zwei Jahre ist"), t("Ein Lichtbild"), f("Ein ärztliches Gutachten über die Fahrtauglichkeit", "Ein ärztliches Gutachten ist für Klasse B nur in Ausnahmefällen erforderlich.")],
    explanation: "Für Klasse B werden Erste-Hilfe-Nachweis (9 Unterrichtseinheiten), Sehtest und Lichtbild benötigt. Ein ärztliches Gutachten ist nur bei bestimmten Erkrankungen oder für Bus- und Lkw-Klassen vorgeschrieben.",
    legalReference: "§ 12 FeV; § 19 FeV; § 21 FeV",
  }),
  q({
    code: "own-recht-037", topic: "recht", points: 3, difficulty: 0.6, tags: ["haftpflichtversicherung", "straftat", "versicherung"],
    text: "Sie fahren mit einem Pkw, dessen Kfz-Haftpflichtversicherung erloschen ist. Was gilt?",
    answers: [t("Das Fahren ohne Haftpflichtversicherung ist eine Straftat"), t("Auch der Halter macht sich strafbar, wenn er die Benutzung gestattet"), f("Es ist eine Ordnungswidrigkeit mit Verwarnungsgeld", "Ein Verstoß gegen die Versicherungspflicht ist strafbar."), f("Es ist unproblematisch, solange kein Unfall passiert", "Die Versicherungspflicht gilt unabhängig davon, ob ein Unfall passiert.")],
    explanation: "Für jedes Kraftfahrzeug muss eine Haftpflichtversicherung bestehen. Wer ohne Versicherungsschutz fährt oder das Fahren zulässt, macht sich strafbar; die Zulassungsbehörde kann das Fahrzeug außer Betrieb setzen.",
    legalReference: "§ 1 und § 6 PflVG",
  }),
  q({
    code: "own-recht-038", topic: "recht", points: 3, difficulty: 0.65, tags: ["versicherung", "haftpflicht", "kasko", "unfall"],
    text: "Welche Schäden übernimmt die Kfz-Haftpflichtversicherung nach einem von Ihnen verschuldeten Unfall?",
    answers: [t("Die Schäden, die Sie anderen zufügen, also am fremden Fahrzeug und bei verletzten Personen"), f("Den Schaden an Ihrem eigenen Fahrzeug", "Dafür ist eine Vollkaskoversicherung nötig."), f("Bußgelder, die gegen Sie verhängt werden", "Bußgelder werden von keiner Versicherung übernommen.")],
    explanation: "Die Haftpflichtversicherung deckt die berechtigten Ansprüche Dritter ab, nicht den eigenen Schaden. Eigene Fahrzeugschäden bei selbst verschuldeten Unfällen trägt nur die Vollkasko.",
    legalReference: "§ 1 PflVG; § 115 VVG",
  }),
  q({
    code: "own-recht-039", topic: "recht", points: 2, difficulty: 0.55, tags: ["hauptuntersuchung", "hu", "fristen"],
    text: "In welchen Abständen muss ein Pkw zur Hauptuntersuchung?",
    answers: [t("Erstmals 36 Monate nach der Erstzulassung, danach alle 24 Monate"), f("Jährlich ab der Erstzulassung", "Für Pkw gelten längere Fristen."), f("Erstmals nach 24 Monaten, danach alle 12 Monate", "Die Fristen sind 36 und dann 24 Monate.")],
    explanation: "Neue Pkw müssen erstmals nach 36 Monaten zur Hauptuntersuchung, anschließend alle 24 Monate. Die Frist ist an der Plakette auf dem hinteren Kennzeichen ablesbar.",
    legalReference: "§ 29 StVZO; Anlage VIII StVZO",
  }),
  q({
    code: "own-recht-040", topic: "recht", points: 3, difficulty: 0.6, tags: ["hauptuntersuchung", "hu", "halter", "pflichten"],
    text: "Sie haben den Termin der Hauptuntersuchung um mehr als acht Monate überschritten. Was gilt?",
    answers: [t("Es droht ein Bußgeld mit Eintragung eines Punktes"), t("Die Hauptuntersuchung wird um eine vertiefte Untersuchung erweitert"), f("Nichts, solange das Fahrzeug technisch in Ordnung ist", "Die Fristüberschreitung selbst ist ordnungswidrig."), f("Die Zulassung erlischt automatisch", "Die Zulassung bleibt bestehen; die Behörde kann aber die Vorführung anordnen.")],
    explanation: "Wer die Hauptuntersuchung überzieht, handelt ordnungswidrig. Ab mehr als acht Monaten Überschreitung gibt es neben dem Bußgeld einen Punkt. Schon ab mehr als zwei Monaten Überschreitung wird die Untersuchung um eine vertiefte Prüfung erweitert, die zusätzlich kostet.",
    legalReference: "§ 29 StVZO; BKatV",
  }),
  q({
    code: "own-recht-041", topic: "recht", points: 3, difficulty: 0.75, tags: ["alkohol", "probezeit", "straftat", "ordnungswidrigkeit"],
    text: "Ein 20-jähriger Fahranfänger fährt mit 0,4 Promille ohne Ausfallerscheinungen. Welche Folgen hat das?",
    answers: [t("Ein Bußgeld und ein Punkt wegen Verstoßes gegen das Alkoholverbot für Fahranfänger"), t("Ein Aufbauseminar und die Verlängerung der Probezeit, weil es sich um einen A-Verstoß handelt"), f("Keine, weil 0,5 Promille nicht erreicht sind", "Für Fahranfänger in der Probezeit und unter 21 Jahren gilt ein absolutes Alkoholverbot."), f("Ein Strafverfahren wegen Trunkenheit im Verkehr", "Ohne Ausfallerscheinungen unter 1,1 Promille liegt keine Straftat vor.")],
    explanation: "In der Probezeit und unter 21 Jahren ist jeder Alkohol am Steuer verboten. Der Verstoß kostet ein Bußgeld und einen Punkt und gilt in der Probezeit als schwerwiegender Verstoß mit Aufbauseminar und Probezeitverlängerung.",
    legalReference: "§ 24c StVG; § 2a StVG",
  }),
  q({
    code: "own-recht-042", topic: "recht", points: 3, difficulty: 0.6, tags: ["mpu", "entzug", "neuerteilung", "alkohol"],
    text: "In welchen Fällen ordnet die Fahrerlaubnisbehörde in der Regel eine medizinisch-psychologische Untersuchung (MPU) an?",
    answers: [t("Nach einer Fahrt mit 1,6 Promille oder mehr"), t("Bei Erreichen von 8 Punkten vor der Neuerteilung der Fahrerlaubnis"), t("Nach wiederholten Alkoholfahrten"), f("Nach jedem Verkehrsunfall mit Sachschaden", "Ein Unfall allein ist kein Grund für eine MPU.")],
    explanation: "Die MPU klärt Zweifel an der Fahreignung. Sie wird unter anderem nach Alkoholfahrten ab 1,6 Promille, bei wiederholten Alkoholverstößen, bei Drogenkonsum und vor einer Neuerteilung nach Entzug wegen 8 Punkten angeordnet.",
    legalReference: "§ 13 FeV; § 4 Abs. 10 StVG",
  }),
];
