// Übungsfragen zum Thema "strassenbenutzung" (eigene Formulierungen, kein amtlicher Prüfungsinhalt).
import type { Question } from "../types";
import { q, t, f } from "./_helpers";

export const strassenbenutzung: readonly Question[] = [
  q({
    code: "own-strassenbenutzung-001", topic: "strassenbenutzung", points: 4, difficulty: 0.3, tags: ["rettungsgasse", "autobahn", "stau"],
    text: "Wo ist die Rettungsgasse auf einer Autobahn mit drei Fahrstreifen je Richtung zu bilden?",
    answers: [t("Zwischen dem linken und dem unmittelbar rechts daneben liegenden Fahrstreifen"), f("Zwischen dem mittleren und dem rechten Fahrstreifen", "Die Gasse liegt weiter links."), f("Erst, wenn ein Einsatzfahrzeug zu sehen ist", "Die Gasse ist zu bilden, sobald der Verkehr stockt.")],
    explanation: "Bei stockendem Verkehr weichen die Fahrzeuge auf dem linken Fahrstreifen nach links aus, alle anderen nach rechts. So entsteht die Gasse zwischen dem ganz linken und dem rechts daneben liegenden Fahrstreifen.",
    mnemonic: "Rechte-Hand-Regel: Daumen links, alle anderen Finger rechts.",
    legalReference: "§ 11 Abs. 2 StVO",
  }),
  q({
    code: "own-strassenbenutzung-002", topic: "strassenbenutzung", points: 3, difficulty: 0.3, tags: ["rettungsgasse", "stau"],
    text: "Wann muss die Rettungsgasse gebildet werden?",
    answers: [t("Sobald Fahrzeuge mit Schrittgeschwindigkeit fahren oder stehen"), f("Erst wenn Blaulicht oder Martinshorn wahrnehmbar sind", "Dann ist es oft zu spät, weil sich die Fahrzeuge nicht mehr bewegen können."), f("Nur wenn die Polizei dazu auffordert", "Die Pflicht besteht ohne Aufforderung.")],
    explanation: "Die Rettungsgasse ist auf Autobahnen und Außerortsstraßen mit mindestens zwei Fahrstreifen je Richtung zu bilden, sobald der Verkehr stockt, also spätestens bei Schrittgeschwindigkeit.",
    legalReference: "§ 11 Abs. 2 StVO",
  }),
  q({
    code: "own-strassenbenutzung-003", topic: "strassenbenutzung", points: 3, difficulty: 0.3, tags: ["autobahn", "einfaedeln", "beschleunigungsstreifen"],
    text: "Sie fahren auf die Autobahn auf. Wie verhalten Sie sich richtig?",
    answers: [t("Auf dem Beschleunigungsstreifen zügig beschleunigen und in eine ausreichende Lücke einfädeln"), f("Am Ende des Beschleunigungsstreifens anhalten und auf eine Lücke warten", "Anhalten ist gefährlich, weil nachfolgende Fahrzeuge damit nicht rechnen."), f("Einfach einscheren, weil der Auffahrende Vorrang hat", "Der Verkehr auf der durchgehenden Fahrbahn hat Vorfahrt.")],
    explanation: "Wer auf die Autobahn auffährt, hat keine Vorfahrt. Der Beschleunigungsstreifen dient dazu, die Geschwindigkeit an den fließenden Verkehr anzupassen und sicher einzufädeln.",
    legalReference: "§ 18 Abs. 3 StVO",
  }),
  q({
    code: "own-strassenbenutzung-004", topic: "strassenbenutzung", points: 2, difficulty: 0.3, tags: ["autobahn", "kraftfahrstrasse"],
    text: "Welche Fahrzeuge dürfen Autobahnen und Kraftfahrstraßen benutzen?",
    answers: [t("Nur Kraftfahrzeuge, deren bauartbedingte Höchstgeschwindigkeit mehr als 60 km/h beträgt"), f("Alle Kraftfahrzeuge", "Langsame Fahrzeuge sind ausgeschlossen."), f("Auch Mofas und Fahrräder, wenn sie den Seitenstreifen benutzen", "Sie dürfen Autobahnen nicht benutzen.")],
    explanation: "Autobahnen und Kraftfahrstraßen dürfen nur mit Kraftfahrzeugen benutzt werden, deren bauartbedingte Höchstgeschwindigkeit über 60 km/h liegt.",
    legalReference: "§ 18 Abs. 1 StVO",
  }),
  q({
    code: "own-strassenbenutzung-005", topic: "strassenbenutzung", points: 3, difficulty: 0.2, tags: ["autobahn", "wenden", "standstreifen"],
    text: "Was ist auf der Autobahn verboten?",
    answers: [t("Wenden"), t("Rückwärtsfahren"), t("Halten auf dem Seitenstreifen ohne Notfall"), f("Überholen", "Überholen ist auf der Autobahn grundsätzlich erlaubt.")],
    explanation: "Auf Autobahnen sind Wenden, Rückwärtsfahren und Halten verboten. Der Seitenstreifen darf nur in Notfällen oder bei Freigabe durch Verkehrszeichen benutzt werden.",
    legalReference: "§ 18 Abs. 7 und 8 StVO",
  }),
  q({
    code: "own-strassenbenutzung-006", topic: "strassenbenutzung", points: 2, difficulty: 0.3, tags: ["autobahn", "richtgeschwindigkeit"],
    text: "Was bedeutet die Richtgeschwindigkeit von 130 km/h auf Autobahnen?",
    answers: [t("Eine Empfehlung; wer schneller fährt, kann bei einem Unfall mithaften, auch ohne Verstoß gegen ein Tempolimit"), f("Eine verbindliche Höchstgeschwindigkeit", "Ohne Beschilderung gibt es auf Autobahnen für Pkw keine allgemeine Höchstgeschwindigkeit."), f("Sie gilt nur für Lkw", "Für Lkw gelten eigene, niedrigere Grenzen.")],
    explanation: "Die Richtgeschwindigkeit empfiehlt, auf Autobahnen nicht schneller als 130 km/h zu fahren. Wer deutlich schneller fährt, trägt bei einem Unfall eine erhöhte Betriebsgefahr und kann mithaften.",
    legalReference: "Autobahn-Richtgeschwindigkeits-Verordnung",
  }),
  q({
    code: "own-strassenbenutzung-007", topic: "strassenbenutzung", points: 3, difficulty: 0.3, tags: ["reissverschluss", "fahrstreifenwechsel"],
    text: "Ein Fahrstreifen endet. Wie funktioniert das Reißverschlussverfahren richtig?",
    answers: [t("Erst unmittelbar vor der Verengung einordnen; die Fahrzeuge wechseln sich dabei ab"), f("Möglichst frühzeitig auf den durchgehenden Fahrstreifen wechseln", "Frühes Einordnen verschenkt Fahrbahnfläche und verlängert den Stau."), f("Fahrzeuge auf dem durchgehenden Fahrstreifen müssen niemanden einfädeln lassen", "Sie müssen das abwechselnde Einordnen ermöglichen.")],
    explanation: "Beim Reißverschlussverfahren nutzen beide Fahrstreifen bis zur Verengung, dann fädeln die Fahrzeuge abwechselnd ein. Die Fahrzeuge auf dem durchgehenden Streifen müssen das ermöglichen.",
    legalReference: "§ 7 Abs. 4 StVO",
  }),
  q({
    code: "own-strassenbenutzung-008", topic: "strassenbenutzung", points: 3, difficulty: 0.5, tags: ["autobahn", "rechts_ueberholen", "stau"],
    text: "Auf der Autobahn hat sich auf dem linken Fahrstreifen eine langsam fahrende Fahrzeugschlange gebildet. Dürfen Sie auf dem rechten Fahrstreifen schneller fahren?",
    answers: [t("Ja, aber nur mit geringfügig höherer Geschwindigkeit als die Schlange"), f("Ja, mit beliebiger Geschwindigkeit", "Das Rechtsüberholen ist nur mit geringer Geschwindigkeitsdifferenz erlaubt."), f("Nein, niemals", "Bei einer Schlange auf dem linken Fahrstreifen ist es in engen Grenzen erlaubt.")],
    explanation: "Grundsätzlich wird links überholt. Steht oder fährt auf dem linken Fahrstreifen eine Fahrzeugschlange, darf rechts nur mit geringfügig höherer Geschwindigkeit vorbeigefahren werden.",
    legalReference: "§ 7 Abs. 2a StVO",
  }),
  q({
    code: "own-strassenbenutzung-009", topic: "strassenbenutzung", points: 4, difficulty: 0.2, tags: ["autobahn", "ausfahrt", "hohes_risiko"],
    text: "Sie haben Ihre Autobahnausfahrt verpasst. Was tun Sie?",
    answers: [t("Bis zur nächsten Ausfahrt weiterfahren"), f("Auf dem Seitenstreifen vorsichtig zurücksetzen", "Rückwärtsfahren ist auf der Autobahn verboten und lebensgefährlich."), f("Auf dem Verzögerungsstreifen anhalten und warten", "Halten ist dort verboten.")],
    explanation: "Eine verpasste Ausfahrt kostet nur Zeit. Rückwärtsfahren oder Wenden auf der Autobahn ist verboten und zählt zu den gefährlichsten Fahrfehlern überhaupt.",
    legalReference: "§ 18 Abs. 7 StVO",
  }),
  q({
    code: "own-strassenbenutzung-010", topic: "strassenbenutzung", points: 3, difficulty: 0.4, tags: ["gehweg", "radverkehr", "kinder"],
    text: "Welche Regeln gelten für Kinder, die mit dem Fahrrad unterwegs sind?",
    answers: [t("Kinder bis zum vollendeten achten Lebensjahr müssen den Gehweg benutzen"), t("Kinder bis zum vollendeten zehnten Lebensjahr dürfen den Gehweg benutzen"), f("Erwachsene dürfen ein Kind bis acht Jahre auf dem Gehweg nicht begleiten", "Eine geeignete Aufsichtsperson ab 16 Jahren darf das Kind auf dem Gehweg begleiten.")],
    explanation: "Kinder unter acht Jahren müssen mit dem Rad auf dem Gehweg fahren, Kinder unter zehn dürfen es. Eine Aufsichtsperson ab 16 Jahren darf ein Kind bis acht Jahre auf dem Gehweg begleiten.",
    legalReference: "§ 2 Abs. 5 StVO",
  }),
  q({
    code: "own-strassenbenutzung-011", topic: "strassenbenutzung", points: 3, difficulty: 0.3, tags: ["standstreifen", "autobahn"],
    text: "Wann dürfen Sie den Seitenstreifen der Autobahn zum Fahren benutzen?",
    answers: [t("Nur wenn er durch Verkehrszeichen zum Befahren freigegeben ist"), f("Immer, wenn auf den Fahrstreifen Stau ist", "Der Seitenstreifen ist kein Fahrstreifen."), f("Wenn Sie die nächste Ausfahrt erreichen wollen", "Auch dann bleibt das Befahren verboten.")],
    explanation: "Der Seitenstreifen ist für Notfälle und Pannenfahrzeuge da. Nur wenn Verkehrszeichen ihn ausdrücklich freigeben, darf er als Fahrstreifen genutzt werden.",
    legalReference: "§ 2 Abs. 1 StVO; Zeichen 223.1",
  }),
  q({
    code: "own-strassenbenutzung-012", topic: "strassenbenutzung", points: 4, difficulty: 0.6, tags: ["rettungsgasse", "autobahn", "stau"],
    text: "Auf einer Autobahn mit zwei Fahrstreifen je Richtung stockt der Verkehr. Wo bilden Sie die Rettungsgasse und was gilt für den Seitenstreifen?",
    answers: [t("Zwischen dem linken und dem rechten Fahrstreifen"), t("Der Seitenstreifen ist frei zu halten und darf nicht als Ausweichfläche für die Rettungsgasse missbraucht werden"), f("Auf dem Seitenstreifen, damit beide Fahrstreifen frei bleiben", "Der Seitenstreifen ist für Pannenfahrzeuge da; die Gasse liegt zwischen den Fahrstreifen."), f("Erst wenn ein Einsatzfahrzeug von hinten zu hören ist", "Die Gasse ist bereits zu bilden, sobald der Verkehr stockt.")],
    explanation: "Bei zwei Fahrstreifen weichen die Fahrzeuge links nach links und rechts nach rechts aus, sodass die Gasse in der Mitte entsteht. Der Seitenstreifen bleibt frei für Pannenfahrzeuge und Einsatzkräfte.",
    legalReference: "§ 11 Abs. 2 StVO",
  }),
  q({
    code: "own-strassenbenutzung-013", topic: "strassenbenutzung", points: 4, difficulty: 0.65, tags: ["rettungsgasse", "autobahn", "ausserorts"],
    text: "Wo muss außer auf Autobahnen ebenfalls eine Rettungsgasse gebildet werden?",
    answers: [t("Auf Außerortsstraßen mit mindestens zwei Fahrstreifen für eine Richtung"), f("Auf allen Straßen innerorts mit mehreren Fahrstreifen", "Innerorts gilt die Pflicht zur Rettungsgasse nicht; dort muss Einsatzfahrzeugen anders freie Bahn geschaffen werden."), f("Nur auf Autobahnen", "Auch mehrstreifige Außerortsstraßen sind erfasst."), f("Auf Landstraßen mit einem Fahrstreifen je Richtung", "Dort ist keine Gasse möglich; Einsatzfahrzeugen ist durch Rechtsfahren Platz zu machen.")],
    explanation: "Die Rettungsgasse ist auf Autobahnen und Außerortsstraßen mit mindestens zwei Fahrstreifen je Richtung zu bilden, sobald der Verkehr stockt. Innerorts und auf einstreifigen Straßen gilt die allgemeine Pflicht, Einsatzfahrzeugen sofort freie Bahn zu schaffen.",
    legalReference: "§ 11 Abs. 2 StVO; § 38 Abs. 1 StVO",
  }),
  q({
    code: "own-strassenbenutzung-014", topic: "strassenbenutzung", points: 4, difficulty: 0.7, tags: ["rettungsgasse", "autobahn", "hohes_risiko"],
    text: "Ein Fahrer nutzt im Stau die gebildete Rettungsgasse, um schneller zur nächsten Ausfahrt zu kommen. Welche Folgen hat das?",
    answers: [t("Ein hohes Bußgeld, Punkte und in der Regel ein Fahrverbot"), t("Bei Behinderung von Rettungskräften kann das Verhalten zusätzlich strafrechtliche Folgen haben"), f("Ein Verwarnungsgeld wie beim Falschparken", "Das Befahren der Rettungsgasse wird deutlich härter geahndet."), f("Keine, wenn die Gasse gerade nicht von einem Einsatzfahrzeug benötigt wird", "Das Befahren ist unabhängig davon verboten, ob gerade ein Einsatzfahrzeug kommt.")],
    explanation: "Wer die Rettungsgasse unbefugt befährt oder nicht bildet, riskiert ein hohes Bußgeld, Punkte und ein Fahrverbot. Werden Rettungskräfte behindert, kommen Straftatbestände wie die Behinderung von hilfeleistenden Personen in Betracht.",
    legalReference: "§ 11 Abs. 2 StVO; BKatV; § 323c StGB",
  }),
  q({
    code: "own-strassenbenutzung-015", topic: "strassenbenutzung", points: 3, difficulty: 0.6, tags: ["autobahn", "beschleunigungsstreifen", "einfaedeln", "geschwindigkeit"],
    text: "Sie fahren auf den Beschleunigungsstreifen einer Autobahn, auf der Richtgeschwindigkeit gilt. Was ist richtig?",
    answers: [t("Auf dem Beschleunigungsstreifen dürfen Sie schneller fahren als die Fahrzeuge auf der durchgehenden Fahrbahn"), t("Der Verkehr auf der durchgehenden Fahrbahn hat Vorfahrt"), f("Die Fahrzeuge auf dem rechten Fahrstreifen müssen Ihnen das Einfädeln durch Bremsen ermöglichen", "Sie sind zur Rücksicht verpflichtet, müssen aber keinen Vorrang gewähren."), f("Sie müssen am Ende des Streifens anhalten, wenn keine Lücke frei ist", "Anhalten ist gefährlich; besser die Länge des Streifens nutzen und die Geschwindigkeit anpassen.")],
    explanation: "Auf dem Beschleunigungsstreifen darf schneller gefahren werden als auf der durchgehenden Fahrbahn, damit das Einfädeln gelingt. Vorfahrt hat der Verkehr auf der Autobahn; der Auffahrende darf niemanden gefährden.",
    legalReference: "§ 18 Abs. 3 StVO",
  }),
  q({
    code: "own-strassenbenutzung-016", topic: "strassenbenutzung", points: 3, difficulty: 0.65, tags: ["autobahn", "ausfahrt", "verzoegerungsstreifen"],
    text: "Sie wollen die Autobahn verlassen. Wie verhalten Sie sich richtig?",
    answers: [t("Rechtzeitig auf dem rechten Fahrstreifen einordnen und den Blinker setzen"), t("Erst auf dem Verzögerungsstreifen deutlich abbremsen"), f("Bereits auf dem rechten Fahrstreifen stark abbremsen, um langsam auf den Verzögerungsstreifen zu fahren", "Starkes Bremsen auf der durchgehenden Fahrbahn gefährdet den nachfolgenden Verkehr."), f("Vom linken Fahrstreifen direkt auf den Verzögerungsstreifen wechseln", "Der Wechsel über mehrere Fahrstreifen unmittelbar vor der Ausfahrt ist gefährlich und unzulässig.")],
    explanation: "Das Verlassen der Autobahn wird rechtzeitig vorbereitet: rechts einordnen, blinken, auf den Verzögerungsstreifen wechseln und erst dort die Geschwindigkeit deutlich verringern. So bleibt der fließende Verkehr ungestört.",
    legalReference: "§ 18 StVO; § 7 Abs. 5 StVO",
  }),
  q({
    code: "own-strassenbenutzung-017", topic: "strassenbenutzung", points: 2, difficulty: 0.6, tags: ["autobahn", "ausfahrt", "ankuendigungsbake"], kind: "numeric", numericAnswer: 300, tolerance: 0, unit: "m",
    text: "Vor einer Autobahnausfahrt stehen Ankündigungsbaken mit drei, zwei und einem Schrägstreifen. Wie viele Meter vor dem Beginn der Ausfahrt steht die Bake mit drei Streifen?",
    answers: [],
    explanation: "Die Ankündigungsbaken (Zeichen 450) stehen 300, 200 und 100 Meter vor der Ausfahrt. Jeder Schrägstreifen steht für 100 Meter. Wer die Bake mit drei Streifen sieht, sollte spätestens jetzt rechts eingeordnet sein.",
    legalReference: "Zeichen 450 StVO",
  }),
  q({
    code: "own-strassenbenutzung-018", topic: "strassenbenutzung", points: 3, difficulty: 0.7, tags: ["autobahn", "rechtsfahrgebot", "fahrstreifen"],
    text: "Auf einer dreistreifigen Autobahn fahren Sie auf dem mittleren Fahrstreifen. Auf dem rechten Fahrstreifen fährt nur hin und wieder ein Fahrzeug. Dürfen Sie in der Mitte bleiben?",
    answers: [t("Ja, wenn auf dem rechten Fahrstreifen hin und wieder Fahrzeuge fahren, dürfen Sie durchgehend in der Mitte bleiben"), f("Nein, nach jedem Überholvorgang müssen Sie sofort nach rechts wechseln", "Bei nur vereinzelt fahrenden Fahrzeugen rechts ist das Durchfahren in der Mitte ausdrücklich erlaubt."), f("Ja, Sie dürfen auf der Autobahn jeden Fahrstreifen frei wählen", "Auf Autobahnen gilt das Rechtsfahrgebot; die freie Fahrstreifenwahl gilt nur innerorts.")],
    explanation: "Auf Autobahnen mit drei Fahrstreifen je Richtung darf auf dem mittleren Fahrstreifen durchgehend gefahren werden, wenn rechts hin und wieder ein Fahrzeug fährt. Der linke Fahrstreifen dient nur zum Überholen.",
    legalReference: "§ 7 Abs. 3c StVO; § 2 Abs. 2 StVO",
  }),
  q({
    code: "own-strassenbenutzung-019", topic: "strassenbenutzung", points: 3, difficulty: 0.55, tags: ["autobahn", "fussgaenger", "panne", "hohes_risiko"],
    text: "Dürfen Sie als Fußgänger die Autobahn betreten?",
    answers: [t("Nein, Fußgänger dürfen Autobahnen nicht betreten; bei einer Panne ist nur der Weg hinter die Schutzplanke und zur Notrufsäule vertretbar"), f("Ja, um nach einer Panne den Verkehr mit Handzeichen zu warnen", "Das Betreten der Fahrbahn ist lebensgefährlich; gewarnt wird mit Warnblinklicht und Warndreieck."), f("Ja, auf dem Seitenstreifen ist das Gehen erlaubt", "Auch der Seitenstreifen gehört zur Autobahn und darf nicht begangen werden.")],
    explanation: "Fußgänger dürfen Autobahnen nicht betreten. Bei einer Panne verlassen die Insassen das Fahrzeug nach rechts, stellen sich hinter die Schutzplanke und gehen nur dort entlang zur Notrufsäule.",
    legalReference: "§ 18 Abs. 9 StVO",
  }),
  q({
    code: "own-strassenbenutzung-020", topic: "strassenbenutzung", points: 3, difficulty: 0.65, tags: ["kraftfahrstrasse", "auffahren", "halten"],
    text: "Was gilt auf einer Kraftfahrstraße (Zeichen 331.1)?",
    answers: [t("Sie darf nur mit Kraftfahrzeugen befahren werden, deren bauartbedingte Höchstgeschwindigkeit mehr als 60 km/h beträgt"), t("Eingefahren werden darf nur an Kreuzungen oder Einmündungen"), t("Wenden, Rückwärtsfahren und Halten sind verboten"), f("Es gilt immer eine Höchstgeschwindigkeit von 100 km/h", "Bei baulich getrennten Richtungsfahrbahnen oder zwei Fahrstreifen je Richtung gibt es für Pkw keine allgemeine Grenze, es gilt die Richtgeschwindigkeit.")],
    explanation: "Auf Kraftfahrstraßen gelten die wichtigsten Autobahnregeln: nur Kraftfahrzeuge über 60 km/h Bauartgeschwindigkeit, Einfahren nur an Kreuzungen und Einmündungen, Wenden, Rückwärtsfahren und Halten verboten. Die Geschwindigkeit hängt vom Ausbau der Straße ab.",
    legalReference: "§ 18 Abs. 1, 2, 7 und 8 StVO; § 3 Abs. 3 StVO",
  }),
  q({
    code: "own-strassenbenutzung-021", topic: "strassenbenutzung", points: 3, difficulty: 0.7, tags: ["kraftfahrstrasse", "hoechstgeschwindigkeit", "richtgeschwindigkeit", "ausserorts"],
    text: "Sie fahren mit dem Pkw auf einer Kraftfahrstraße mit zwei markierten Fahrstreifen je Richtung und baulicher Trennung. Es sind keine Geschwindigkeitszeichen aufgestellt. Wie schnell dürfen Sie fahren?",
    answers: [t("Es gilt keine allgemeine Höchstgeschwindigkeit, aber die Richtgeschwindigkeit von 130 km/h"), f("Höchstens 100 km/h wie auf jeder Außerortsstraße", "Bei baulicher Trennung oder zwei Fahrstreifen je Richtung entfällt die 100-km/h-Grenze für Pkw."), f("Höchstens 80 km/h", "Das gilt nur für Pkw mit Anhänger und Lkw.")],
    explanation: "Die Grenze von 100 km/h außerorts gilt für Pkw nicht auf Straßen mit baulich getrennten Richtungsfahrbahnen oder mindestens zwei markierten Fahrstreifen je Richtung. Dort gilt wie auf der Autobahn die Richtgeschwindigkeit von 130 km/h.",
    legalReference: "§ 3 Abs. 3 Nr. 2 StVO; Autobahn-Richtgeschwindigkeits-Verordnung",
  }),
  q({
    code: "own-strassenbenutzung-022", topic: "strassenbenutzung", points: 3, difficulty: 0.6, tags: ["autobahn", "anhaenger", "hoechstgeschwindigkeit", "lkw"],
    text: "Welche Fahrzeuge dürfen auf der Autobahn ohne besondere Zulassung höchstens 80 km/h fahren?",
    answers: [t("Pkw mit Anhänger"), t("Lkw mit einer zulässigen Gesamtmasse über 3,5 t"), t("Kraftomnibusse ohne Tempo-100-Zulassung"), f("Pkw mit Dachgepäckträger", "Ein Dachgepäckträger ändert die zulässige Geschwindigkeit nicht; nur die Ladung muss sicher sein.")],
    explanation: "Auf Autobahnen gilt für Pkw mit Anhänger, Lkw über 3,5 t und Kraftomnibusse eine Höchstgeschwindigkeit von 80 km/h. 100 km/h sind für Gespanne und Busse nur mit besonderer Zulassung und Plakette erlaubt.",
    legalReference: "§ 18 Abs. 5 StVO; § 3 Abs. 3 Nr. 2 StVO",
  }),
  q({
    code: "own-strassenbenutzung-023", topic: "strassenbenutzung", points: 3, difficulty: 0.55, tags: ["autobahn", "mindestgeschwindigkeit", "bauartgeschwindigkeit"],
    text: "Gibt es auf der Autobahn eine allgemeine Mindestgeschwindigkeit?",
    answers: [t("Nein; das Fahrzeug muss aber bauartbedingt schneller als 60 km/h fahren können, und ohne triftigen Grund darf nicht so langsam gefahren werden, dass der Verkehr behindert wird"), f("Ja, es müssen immer mindestens 60 km/h gefahren werden", "Die 60 km/h beziehen sich auf die Bauart des Fahrzeugs, nicht auf die tatsächliche Fahrgeschwindigkeit."), f("Ja, mindestens 80 km/h auf dem linken Fahrstreifen", "Eine feste Mindestgeschwindigkeit gibt es nur bei Zeichen 275.")],
    explanation: "Auf Autobahnen gibt es keine allgemeine Mindestgeschwindigkeit. Zugelassen sind nur Fahrzeuge, die bauartbedingt mehr als 60 km/h fahren können, und grundloses Langsamfahren ist verboten. Eine Mindestgeschwindigkeit gilt nur, wo Zeichen 275 sie anordnet.",
    legalReference: "§ 18 Abs. 1 StVO; § 3 Abs. 2 StVO; Zeichen 275",
  }),
  q({
    code: "own-strassenbenutzung-024", topic: "strassenbenutzung", points: 3, difficulty: 0.65, tags: ["autobahn", "standstreifen", "seitenstreifen", "verkehrszeichen"],
    text: "Auf der Autobahn zeigt ein Zeichen den Seitenstreifen als befahrbar an (Zeichen 223.1). Was gilt?",
    answers: [t("Der Seitenstreifen darf jetzt wie ein Fahrstreifen befahren werden"), t("Beim Zeichen 223.3 muss der Seitenstreifen wieder geräumt werden"), f("Der Seitenstreifen darf nur von Lkw befahren werden", "Die Freigabe gilt für alle Fahrzeuge."), f("Auf dem Seitenstreifen darf schneller gefahren werden als auf den übrigen Fahrstreifen", "Der Seitenstreifen ist der rechte Streifen; rechts darf grundsätzlich nicht schneller gefahren werden.")],
    explanation: "Mit Zeichen 223.1 wird der Seitenstreifen vorübergehend als Fahrstreifen freigegeben. Zeichen 223.2 hebt die Freigabe auf, Zeichen 223.3 fordert zum Räumen des Seitenstreifens auf. Der Seitenstreifen bleibt der rechte Streifen mit allen Regeln des Rechtsfahrens.",
    legalReference: "Zeichen 223.1 bis 223.3 StVO",
  }),
  q({
    code: "own-strassenbenutzung-025", topic: "strassenbenutzung", points: 3, difficulty: 0.6, tags: ["tunnel", "abblendlicht", "wenden"],
    text: "Sie fahren in einen Tunnel (Zeichen 327). Was müssen Sie beachten?",
    answers: [t("Abblendlicht einschalten, auch wenn der Tunnel beleuchtet ist"), t("Wenden ist verboten"), t("Ausreichenden Abstand halten und sich die Lage von Notausgängen einprägen"), f("Sonnenbrille aufsetzen, weil die Tunnelbeleuchtung blendet", "Eine Sonnenbrille verschlechtert die Sicht im Tunnel erheblich.")],
    explanation: "Im Tunnel ist mit Abblendlicht zu fahren und Wenden verboten. Vor der Einfahrt sollte die Sonnenbrille abgenommen werden. Ausreichender Abstand und Kenntnis der Notausgänge sind wichtig, falls es zu einem Unfall oder Brand kommt.",
    legalReference: "Zeichen 327 StVO; § 17 Abs. 1 StVO",
  }),
  q({
    code: "own-strassenbenutzung-026", topic: "strassenbenutzung", points: 3, difficulty: 0.6, tags: ["einbahnstrasse", "radverkehr", "zusatzzeichen", "parken"],
    text: "Sie fahren in eine Einbahnstraße ein. Unter dem Zeichen 220 ist ein Zusatzzeichen angebracht, das Radverkehr in Gegenrichtung freigibt. Was ist richtig?",
    answers: [t("Sie müssen mit entgegenkommenden Radfahrenden rechnen, vor allem beim Abbiegen und beim Öffnen der Tür"), t("Am linken Fahrbahnrand darf in der Einbahnstraße geparkt werden"), f("Radfahrende dürfen die Straße nur in Fahrtrichtung der Einbahnstraße befahren", "Das Zusatzzeichen erlaubt dem Radverkehr ausdrücklich die Gegenrichtung."), f("Sie dürfen in der Einbahnstraße wenden, weil Radverkehr ohnehin entgegenkommt", "Wenden bleibt in der Einbahnstraße verboten.")],
    explanation: "Mit dem Zusatzzeichen dürfen Radfahrende die Einbahnstraße in Gegenrichtung befahren. Autofahrer müssen an Kreuzungen und beim Ausparken damit rechnen. Parken ist in Einbahnstraßen auch links erlaubt.",
    legalReference: "Zeichen 220 mit Zusatzzeichen 1000-32; § 12 Abs. 4 StVO",
  }),
  q({
    code: "own-strassenbenutzung-027", topic: "strassenbenutzung", points: 3, difficulty: 0.7, tags: ["radweg", "benutzungspflicht", "radverkehr", "verkehrszeichen"],
    text: "Wann müssen Radfahrende einen Radweg benutzen und was bedeutet das für Sie als Autofahrer?",
    answers: [t("Nur wenn er mit Zeichen 237, 240 oder 241 gekennzeichnet ist"), t("Ohne diese Zeichen dürfen Radfahrende auch die Fahrbahn benutzen; Sie müssen damit rechnen und beim Überholen den Mindestabstand einhalten"), f("Immer, wenn ein Radweg baulich vorhanden ist", "Ohne blaues Zeichen besteht keine Benutzungspflicht."), f("Nie, die Benutzung von Radwegen ist stets freiwillig", "Mit den blauen Radwegzeichen ist die Benutzung verpflichtend.")],
    explanation: "Radwege müssen nur benutzt werden, wenn sie mit den blauen Zeichen 237, 240 oder 241 gekennzeichnet sind. Sonst dürfen Radfahrende auf der Fahrbahn fahren. Autofahrer müssen auch dann mit ihnen rechnen und beim Überholen 1,5 m innerorts beziehungsweise 2 m außerorts Abstand halten.",
    legalReference: "§ 2 Abs. 4 StVO; § 5 Abs. 4 StVO",
  }),
  q({
    code: "own-strassenbenutzung-028", topic: "strassenbenutzung", points: 3, difficulty: 0.65, tags: ["schutzstreifen", "radverkehr", "innerorts"],
    text: "Auf der Fahrbahn ist rechts ein Schutzstreifen für den Radverkehr (gestrichelte Linie mit Fahrradsymbol) markiert. Was gilt für Sie?",
    answers: [t("Sie dürfen den Schutzstreifen nur bei Bedarf befahren, zum Beispiel bei Gegenverkehr, und dürfen dabei Radfahrende nicht gefährden"), t("Parken auf dem Schutzstreifen ist verboten"), f("Der Schutzstreifen ist ein Radweg; Radfahrende müssen ihn benutzen", "Der Schutzstreifen ist Teil der Fahrbahn und kein Radweg im Sinne der Benutzungspflicht."), f("Sie dürfen den Schutzstreifen jederzeit mitbenutzen, um Platz zu sparen", "Das Befahren ist nur bei Bedarf und ohne Gefährdung erlaubt.")],
    explanation: "Der Schutzstreifen gehört zur Fahrbahn und darf von Kraftfahrzeugen nur bei Bedarf überfahren werden, wenn kein Radverkehr gefährdet wird. Parken ist dort verboten. Ein durchgezogener Radfahrstreifen dagegen darf gar nicht befahren werden.",
    legalReference: "§ 42 StVO, Anlage 3 (Zeichen 340); § 12 StVO",
  }),
  q({
    code: "own-strassenbenutzung-029", topic: "strassenbenutzung", points: 3, difficulty: 0.6, tags: ["bussonderfahrstreifen", "zusatzzeichen", "innerorts"],
    text: "Wer darf einen Bussonderfahrstreifen (Zeichen 245) benutzen?",
    answers: [t("Linienbusse; andere Fahrzeuge wie Taxis oder Radfahrende nur, wenn ein Zusatzzeichen sie zulässt"), t("Andere Fahrzeuge dürfen ihn zum Erreichen einer Grundstückseinfahrt oder zum Rechtsabbiegen kurz befahren, ohne den Busverkehr zu behindern"), f("Alle Kraftfahrzeuge mit mindestens drei Insassen", "Eine solche Regelung gibt es in Deutschland nicht."), f("Pkw, wenn die übrigen Fahrstreifen verstopft sind", "Stau berechtigt nicht zur Nutzung des Sonderfahrstreifens.")],
    explanation: "Der Sonderfahrstreifen ist für Linienbusse reserviert. Andere Verkehrsarten dürfen ihn nur mit Zusatzzeichen nutzen. Ein kurzes Überqueren oder Befahren zum Abbiegen oder zum Erreichen eines Grundstücks ist erlaubt, wenn Busse nicht behindert werden.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 245)",
  }),
  q({
    code: "own-strassenbenutzung-030", topic: "strassenbenutzung", points: 3, difficulty: 0.55, tags: ["fussgaenger", "ausserorts", "gehweg"],
    text: "Auf einer Landstraße ohne Gehweg gehen bei Dunkelheit Fußgänger. Auf welcher Seite müssen sie gehen und worauf müssen Sie sich einstellen?",
    answers: [t("Außerorts müssen Fußgänger am linken Fahrbahnrand gehen, Ihnen also entgegenkommen"), t("Sie müssen die Geschwindigkeit an die Sichtweite anpassen, weil dunkel gekleidete Fußgänger erst spät erkennbar sind"), f("Fußgänger müssen rechts gehen wie Fahrzeuge", "Außerorts ist der linke Rand vorgeschrieben, damit Fußgänger den Verkehr sehen."), f("Fußgänger dürfen Landstraßen bei Dunkelheit nicht benutzen", "Ein solches Verbot gibt es nicht.")],
    explanation: "Außerhalb geschlossener Ortschaften müssen Fußgänger ohne Gehweg am linken Fahrbahnrand gehen, damit sie den Verkehr kommen sehen. Für Autofahrer gilt: nachts nur so schnell fahren, dass innerhalb der Sichtweite angehalten werden kann.",
    legalReference: "§ 25 Abs. 1 StVO; § 3 Abs. 1 StVO",
  }),
  q({
    code: "own-strassenbenutzung-031", topic: "strassenbenutzung", points: 3, difficulty: 0.6, tags: ["gehweg", "e_scooter", "inline_skates", "elektrokleinstfahrzeuge"],
    text: "Welche Verkehrsteilnehmer dürfen den Gehweg benutzen?",
    answers: [t("Fußgänger sowie Inline-Skater und Rollschuhfahrer"), t("Kinder bis zum vollendeten zehnten Lebensjahr mit dem Fahrrad"), f("E-Scooter-Fahrer, wenn kein Radweg vorhanden ist", "E-Scooter müssen ohne Radweg die Fahrbahn benutzen; der Gehweg ist tabu."), f("Mofafahrer mit ausgeschaltetem Motor", "Ein Mofa darf auf dem Gehweg nur geschoben werden.")],
    explanation: "Der Gehweg ist für Fußgänger da; Inline-Skater und Rollschuhfahrer gelten als Fußgänger. Kinder bis zehn Jahre dürfen mit dem Rad auf dem Gehweg fahren. E-Scooter gehören auf den Radweg oder die Fahrbahn.",
    legalReference: "§ 24 Abs. 1 StVO; § 2 Abs. 5 StVO; § 10 eKFV",
  }),
  q({
    code: "own-strassenbenutzung-032", topic: "strassenbenutzung", points: 3, difficulty: 0.5, tags: ["rechtsfahrgebot", "ausserorts", "landstrasse"],
    text: "Wie weit rechts müssen Sie auf einer Landstraße fahren?",
    answers: [t("Möglichst weit rechts, besonders bei Gegenverkehr, beim Überholtwerden, an Kuppen und in Kurven"), f("Genau in der Mitte des eigenen Fahrstreifens, unabhängig von der Situation", "Das Rechtsfahrgebot verlangt in den genannten Situationen ausdrücklich, möglichst weit rechts zu fahren."), f("Auf der Fahrbahnmitte, um Abstand zum Fahrbahnrand zu halten", "Das gefährdet den Gegenverkehr.")],
    explanation: "Es ist möglichst weit rechts zu fahren, nicht nur bei Gegenverkehr, beim Überholtwerden, an Kuppen, in Kurven oder bei Unübersichtlichkeit. Innerorts bei mehreren Fahrstreifen gilt dagegen die freie Fahrstreifenwahl.",
    legalReference: "§ 2 Abs. 2 StVO",
  }),
  q({
    code: "own-strassenbenutzung-033", topic: "strassenbenutzung", points: 3, difficulty: 0.65, tags: ["fahrstreifen", "innerorts", "fahrstreifenwahl", "lkw"],
    text: "Innerorts gibt es zwei markierte Fahrstreifen für Ihre Richtung. Was gilt für die Fahrstreifenwahl?",
    answers: [t("Kraftfahrzeuge bis 3,5 t dürfen den Fahrstreifen frei wählen und dürfen auch links fahren, ohne zu überholen"), t("Fahrzeuge über 3,5 t dürfen den linken Fahrstreifen nur zum Überholen, Linksabbiegen oder bei entsprechender Verkehrsdichte benutzen"), f("Alle Fahrzeuge müssen rechts fahren und den linken Streifen nur zum Überholen nutzen", "Innerorts gilt für Kraftfahrzeuge bis 3,5 t die freie Fahrstreifenwahl."), f("Der linke Fahrstreifen ist nur für den Linienverkehr bestimmt", "Das gilt nur bei einem Bussonderfahrstreifen.")],
    explanation: "Innerorts dürfen Kraftfahrzeuge bis 3,5 t bei mehreren markierten Fahrstreifen für eine Richtung den Fahrstreifen frei wählen und auch rechts schneller fahren als links. Schwerere Fahrzeuge unterliegen weiterhin dem Rechtsfahrgebot.",
    legalReference: "§ 7 Abs. 3 StVO",
  }),
  q({
    code: "own-strassenbenutzung-034", topic: "strassenbenutzung", points: 3, difficulty: 0.6, tags: ["fahrstreifenwechsel", "reissverschluss", "baustelle"],
    text: "In einer Baustelle auf der Autobahn endet der linke Fahrstreifen. Ein Fahrer auf dem rechten Fahrstreifen schließt die Lücke, damit niemand einfädeln kann. Was ist richtig?",
    answers: [t("Der Fahrer auf dem durchgehenden Fahrstreifen muss das Einfädeln im Reißverschlussverfahren ermöglichen"), t("Die Fahrzeuge auf dem endenden Streifen dürfen bis zur Engstelle vorfahren und dort abwechselnd einfädeln"), f("Wer auf dem endenden Streifen bis zur Engstelle vorfährt, verhält sich verkehrswidrig", "Das Reißverschlussverfahren sieht genau das vor."), f("Die Fahrzeuge auf dem durchgehenden Fahrstreifen haben Vorrang und müssen niemanden hereinlassen", "Beim Reißverschluss muss das Einfädeln ermöglicht werden.")],
    explanation: "Beim Reißverschlussverfahren fahren beide Streifen bis zur Engstelle, dort wechseln sich die Fahrzeuge ab. Wer auf dem durchgehenden Fahrstreifen das Einfädeln verhindert, handelt ordnungswidrig.",
    legalReference: "§ 7 Abs. 4 StVO",
  }),
  q({
    code: "own-strassenbenutzung-035", topic: "strassenbenutzung", points: 3, difficulty: 0.7, tags: ["autobahn", "stau", "warnblinklicht", "hohes_risiko"],
    text: "Auf der Autobahn erkennen Sie vor sich ein Stauende. Wie verhalten Sie sich?",
    answers: [t("Warnblinklicht einschalten, um den nachfolgenden Verkehr zu warnen"), t("Geschwindigkeit frühzeitig verringern und den Rückspiegel beobachten"), t("Rechtzeitig die Rettungsgasse bilden, sobald der Verkehr stockt"), f("Auf den Seitenstreifen ausweichen, um am Stau vorbeizufahren", "Der Seitenstreifen darf nicht zum Fahren benutzt werden.")],
    explanation: "Am Stauende darf das Warnblinklicht eingeschaltet werden, um andere zu warnen. Wichtig sind frühes Bremsen, der Blick in den Spiegel und das rechtzeitige Bilden der Rettungsgasse. Der Seitenstreifen bleibt frei.",
    legalReference: "§ 16 Abs. 2 StVO; § 11 Abs. 2 StVO",
  }),
  q({
    code: "own-strassenbenutzung-036", topic: "strassenbenutzung", points: 3, difficulty: 0.55, tags: ["autobahn", "nothaltebucht", "halten"],
    text: "Wofür ist eine Nothalte- oder Pannenbucht (Zeichen 328) bestimmt?",
    answers: [t("Nur für das Anhalten in Notfällen, etwa bei einer Panne"), f("Für kurze Pausen und zum Telefonieren", "Halten ist dort nur im Notfall erlaubt."), f("Zum Wenden, wenn man die Ausfahrt verpasst hat", "Wenden ist auf der Autobahn verboten.")],
    explanation: "Nothaltebuchten dienen ausschließlich Notfällen. Wer dort ohne Not hält, blockiert die Bucht für Pannenfahrzeuge und verhält sich ordnungswidrig. Für Pausen sind Rastplätze und Parkplätze da.",
    legalReference: "§ 18 Abs. 8 StVO; Zeichen 328",
  }),
  q({
    code: "own-strassenbenutzung-037", topic: "strassenbenutzung", points: 3, difficulty: 0.6, tags: ["autobahn", "ende_der_autobahn", "hoechstgeschwindigkeit"],
    text: "Sie passieren das Zeichen Ende der Autobahn (Zeichen 330.2) und fahren auf einer Landstraße weiter. Es sind keine weiteren Zeichen aufgestellt. Was gilt?",
    answers: [t("Für Pkw gilt jetzt die Höchstgeschwindigkeit von 100 km/h"), t("Es gilt wieder die Grundregel: Fahren ist auch mit langsamen Fahrzeugen und Fahrrädern erlaubt"), f("Die Richtgeschwindigkeit von 130 km/h gilt weiter", "Nach dem Ende der Autobahn gelten die Regeln für Außerortsstraßen."), f("Es gilt 50 km/h", "Ohne Ortstafel gilt die Außerortsgrenze von 100 km/h.")],
    explanation: "Mit dem Ende der Autobahn enden die Autobahnregeln. Auf der anschließenden Landstraße gilt für Pkw 100 km/h, und es darf wieder mit allen Fahrzeugen inklusive Fahrrädern und langsamen Fahrzeugen gerechnet werden.",
    legalReference: "Zeichen 330.2 StVO; § 3 Abs. 3 Nr. 2 StVO",
  }),
  q({
    code: "own-strassenbenutzung-038", topic: "strassenbenutzung", points: 3, difficulty: 0.65, tags: ["autobahn", "ueberholen", "rechts_ueberholen", "beschleunigungsstreifen"],
    text: "Auf der Autobahn fährt links neben Ihnen ein Lkw mit 80 km/h. Sie befinden sich auf dem Beschleunigungsstreifen und sind schneller. Dürfen Sie rechts an ihm vorbeifahren?",
    answers: [t("Ja, auf dem Beschleunigungsstreifen darf rechts an Fahrzeugen auf der durchgehenden Fahrbahn vorbeigefahren werden"), f("Nein, rechts überholen ist auf der Autobahn ausnahmslos verboten", "Der Beschleunigungsstreifen bildet eine ausdrückliche Ausnahme."), f("Nur, wenn der Lkw das Warnblinklicht eingeschaltet hat", "Das Warnblinklicht spielt dafür keine Rolle.")],
    explanation: "Auf dem Beschleunigungsstreifen darf schneller gefahren werden als auf den durchgehenden Fahrstreifen; das Vorbeifahren rechts an Fahrzeugen der durchgehenden Fahrbahn ist dort erlaubt. Das Einfädeln erfolgt dann in eine ausreichende Lücke.",
    legalReference: "§ 18 Abs. 3 StVO",
  }),
  q({
    code: "own-strassenbenutzung-039", topic: "strassenbenutzung", points: 2, difficulty: 0.45, tags: ["autobahn", "leitpfosten", "abstand"], kind: "numeric", numericAnswer: 50, tolerance: 0, unit: "m",
    text: "In welchem Abstand stehen die Leitpfosten am Rand der Autobahn in der Regel? Angabe in Metern.",
    answers: [],
    explanation: "Leitpfosten stehen auf geraden Strecken in der Regel im Abstand von 50 Metern. Damit lässt sich der Sicherheitsabstand nach der Regel halber Tacho bei 100 km/h leicht abschätzen: mindestens ein Leitpfostenabstand.",
    legalReference: "§ 43 StVO, Anlage 4 (Zeichen 620)",
  }),
  q({
    code: "own-strassenbenutzung-040", topic: "strassenbenutzung", points: 3, difficulty: 0.5, tags: ["verkehrsberuhigter_bereich", "einfahren", "innerorts"],
    text: "Sie verlassen einen verkehrsberuhigten Bereich (Zeichen 325.2) und fahren auf die Straße. Was gilt?",
    answers: [t("Sie müssen allen anderen Verkehrsteilnehmern Vorfahrt gewähren, weil das Ausfahren wie das Einfahren aus einem Grundstück behandelt wird"), f("Es gilt rechts vor links", "Wer aus einem verkehrsberuhigten Bereich ausfährt, ist wartepflichtig."), f("Sie haben Vorfahrt, weil Sie sich bereits auf einer Straße befinden", "Die Ausfahrt aus einem verkehrsberuhigten Bereich begründet keine Vorfahrt.")],
    explanation: "Wer aus einem verkehrsberuhigten Bereich auf eine Straße einfährt, muss sich wie beim Einfahren aus einem Grundstück verhalten: jede Gefährdung ausschließen und alle anderen durchfahren lassen.",
    legalReference: "§ 10 StVO",
  }),
  q({
    code: "own-strassenbenutzung-041", topic: "strassenbenutzung", points: 3, difficulty: 0.65, tags: ["autobahn", "auffahrt", "ausserorts", "anhaenger"],
    text: "Sie fahren mit Pkw und Wohnwagen (ohne Tempo-100-Zulassung) auf die Autobahn. Was müssen Sie beachten?",
    answers: [t("Höchstens 80 km/h fahren, auch wenn Richtgeschwindigkeit gilt"), t("Auf dem Beschleunigungsstreifen zügig beschleunigen, um sich der Geschwindigkeit des Verkehrs anzunähern"), t("Größere Lücken zum Einfädeln abwarten, weil das Gespann länger und träger ist"), f("Vom Beschleunigungsstreifen aus direkt auf den mittleren Fahrstreifen wechseln, um Platz zu haben", "Eingefädelt wird auf den rechten Fahrstreifen.")],
    explanation: "Gespanne ohne Tempo-100-Zulassung dürfen höchstens 80 km/h fahren. Beim Auffahren gilt trotzdem: zügig beschleunigen und in eine ausreichend große Lücke auf dem rechten Fahrstreifen einfädeln.",
    legalReference: "§ 18 Abs. 3 und 5 StVO",
  }),
];
