// Übungsfragen zum Thema "umwelt" (eigene Formulierungen, kein amtlicher Prüfungsinhalt).
import type { Question } from "../types";
import { q, t, f } from "./_helpers";

export const umwelt: readonly Question[] = [
  q({
    code: "own-umwelt-001", topic: "umwelt", points: 2, difficulty: 0.2, tags: ["kraftstoff", "schalten"],
    text: "Wie fahren Sie mit einem Schaltwagen kraftstoffsparend?",
    answers: [t("Frühzeitig hochschalten, etwa bei 2.000 Umdrehungen pro Minute, und im hohen Gang mit niedriger Drehzahl fahren"), f("Jeden Gang bis in den roten Drehzahlbereich ausfahren", "Hohe Drehzahlen erhöhen Verbrauch, Lärm und Verschleiß."), f("Möglichst lange im ersten und zweiten Gang bleiben", "Niedrige Gänge bei hoher Drehzahl verbrauchen am meisten.")],
    explanation: "Niedrige Drehzahlen in hohen Gängen sparen Kraftstoff. Moderne Motoren laufen bei etwa 2.000 Umdrehungen pro Minute effizient und ruckelfrei.",
  }),
  q({
    code: "own-umwelt-002", topic: "umwelt", points: 2, difficulty: 0.2, tags: ["motor_abstellen", "bahnuebergang", "laerm"],
    text: "Sie warten längere Zeit an einem geschlossenen Bahnübergang. Was ist richtig?",
    answers: [t("Motor abstellen, um Abgase und Lärm zu vermeiden"), f("Motor laufen lassen, damit die Batterie geladen bleibt", "Der kurze Neustart verbraucht weniger als der Leerlauf."), f("Im Leerlauf zwischendurch Gas geben", "Das erzeugt nur Lärm und Abgase.")],
    explanation: "Unnötiger Lärm und vermeidbare Abgase sind verboten. Bei längerem Warten, etwa an Bahnübergängen, wird der Motor abgestellt.",
    legalReference: "§ 30 Abs. 1 StVO",
  }),
  q({
    code: "own-umwelt-003", topic: "umwelt", points: 2, difficulty: 0.2, tags: ["reifendruck", "kraftstoff"],
    text: "Wie wirkt sich zu niedriger Reifendruck aus?",
    answers: [t("Höherer Kraftstoffverbrauch, stärkerer Reifenverschleiß und schlechteres Fahrverhalten"), f("Geringerer Verbrauch durch weichere Reifen", "Zu wenig Druck erhöht den Rollwiderstand."), f("Keine Auswirkung, solange der Reifen nicht platt ist", "Schon geringer Unterdruck erhöht Verbrauch und Verschleiß.")],
    explanation: "Zu niedriger Reifendruck erhöht den Rollwiderstand und damit den Verbrauch. Zudem verschleißen die Reifen schneller und das Fahrzeug reagiert schwammiger.",
  }),
  q({
    code: "own-umwelt-004", topic: "umwelt", points: 2, difficulty: 0.1, tags: ["luftwiderstand", "dachgepaecktraeger"],
    text: "Der Dachgepäckträger wird nicht mehr gebraucht. Was ist umweltbewusst?",
    answers: [t("Abnehmen, weil er den Luftwiderstand und damit den Verbrauch erhöht"), f("Montiert lassen, weil er nur bei Beladung Kraftstoff kostet", "Auch leer erhöht er den Luftwiderstand."), f("Montiert lassen, weil die Montage dem Dach schadet", "Regelmäßiges Abnehmen schadet nicht.")],
    explanation: "Dachträger, Boxen und Fahrradträger erhöhen den Luftwiderstand deutlich, besonders bei höheren Geschwindigkeiten. Nicht benötigte Anbauten abnehmen.",
  }),
  q({
    code: "own-umwelt-005", topic: "umwelt", points: 2, difficulty: 0.3, tags: ["umweltzone", "plakette"],
    text: "Was gilt in einer Umweltzone (Zeichen 270.1)?",
    answers: [t("Nur Fahrzeuge mit der auf dem Zusatzzeichen angegebenen Plakette dürfen einfahren"), f("Alle Fahrzeuge dürfen einfahren, wenn sie langsam fahren", "Die Einfahrt hängt von der Plakette ab."), f("Es gilt ein generelles Fahrverbot", "Fahrzeuge mit passender Plakette dürfen fahren.")],
    explanation: "In Umweltzonen dürfen nur Kraftfahrzeuge fahren, die mit der entsprechenden Feinstaubplakette gekennzeichnet sind. Welche Plakette nötig ist, zeigt das Zusatzzeichen.",
    legalReference: "§ 40 BImSchG; Zeichen 270.1 StVO",
  }),
  q({
    code: "own-umwelt-006", topic: "umwelt", points: 2, difficulty: 0.2, tags: ["warmlaufen", "laerm", "winter"],
    text: "Dürfen Sie den Motor im Winter vor der Abfahrt im Stand warmlaufen lassen?",
    answers: [t("Nein, das ist als unnötiger Lärm und vermeidbare Abgasbelästigung verboten"), f("Ja, bis die Betriebstemperatur erreicht ist", "Der Motor wird im Stand nur langsam warm und erzeugt unnötige Emissionen."), f("Ja, aber höchstens fünf Minuten", "Eine zeitliche Erlaubnis gibt es nicht.")],
    explanation: "Motoren im Stand warmlaufen zu lassen ist verboten. Besser: Scheiben freikratzen, losfahren und die ersten Kilometer mit niedriger Drehzahl fahren.",
    legalReference: "§ 30 Abs. 1 StVO",
  }),
  q({
    code: "own-umwelt-007", topic: "umwelt", points: 2, difficulty: 0.2, tags: ["vorausschauend", "schubabschaltung"],
    text: "Sie sehen von weitem, dass die Ampel auf Rot steht. Wie fahren Sie umweltschonend?",
    answers: [t("Früh vom Gas gehen und das Fahrzeug im eingelegten Gang ausrollen lassen"), f("Bis kurz vor die Ampel beschleunigen und dann stark bremsen", "Das verschwendet Energie und Bremsbeläge."), f("Auskuppeln und im Leerlauf rollen", "Im Leerlauf verbraucht der Motor Kraftstoff; im eingelegten Gang greift die Schubabschaltung.")],
    explanation: "Beim Ausrollen im eingelegten Gang schaltet die Schubabschaltung die Kraftstoffzufuhr ab. Vorausschauendes Fahren spart Kraftstoff und schont die Bremsen.",
  }),
  q({
    code: "own-umwelt-008", topic: "umwelt", points: 2, difficulty: 0.3, tags: ["klimaanlage", "kraftstoff"],
    text: "Was erhöht den Kraftstoffverbrauch?",
    answers: [t("Eingeschaltete Klimaanlage"), t("Geöffnete Fenster bei hoher Geschwindigkeit"), f("Eingeschaltetes Abblendlicht bei Tag in nennenswertem Umfang", "Der Einfluss der Beleuchtung ist sehr gering.")],
    explanation: "Klimaanlage, Heckscheibenheizung und offene Fenster bei hoher Geschwindigkeit kosten spürbar Kraftstoff. Verbraucher nur einschalten, wenn sie gebraucht werden.",
  }),
  q({
    code: "own-umwelt-009", topic: "umwelt", points: 2, difficulty: 0.2, tags: ["altoel", "entsorgung"],
    text: "Wie entsorgen Sie Altöl nach einem selbst durchgeführten Ölwechsel?",
    answers: [t("Bei der Verkaufsstelle des neuen Öls oder einer Sammelstelle abgeben"), f("Über den Hausmüll", "Altöl ist Sondermüll."), f("In kleinen Mengen in die Kanalisation", "Schon geringe Ölmengen verschmutzen große Mengen Wasser.")],
    explanation: "Altöl muss an Sammelstellen oder bei der Verkaufsstelle abgegeben werden, die es zurücknehmen muss. Ins Grundwasser oder die Kanalisation darf es nie gelangen.",
    legalReference: "Altölverordnung",
  }),
  q({
    code: "own-umwelt-010", topic: "umwelt", points: 2, difficulty: 0.2, tags: ["kurzstrecke", "kraftstoff"],
    text: "Warum sind Kurzstrecken mit dem Auto besonders umweltbelastend?",
    answers: [t("Der kalte Motor verbraucht deutlich mehr Kraftstoff und stößt mehr Schadstoffe aus, bis er Betriebstemperatur hat"), f("Weil kurze Strecken immer mit hoher Geschwindigkeit gefahren werden", "Die Geschwindigkeit ist nicht der Grund."), f("Kurzstrecken sind nicht umweltbelastend", "Gerade Kurzstrecken sind pro Kilometer besonders belastend.")],
    explanation: "Auf den ersten Kilometern arbeitet der Motor mit erhöhtem Verbrauch und der Katalysator noch nicht mit voller Wirkung. Kurze Wege besser zu Fuß oder mit dem Rad zurücklegen.",
  }),
  q({
    code: "own-umwelt-011", topic: "umwelt", points: 3, difficulty: 0.6, tags: ["laerm", "sonntagsfahrverbot", "lkw"], kind: "numeric", numericAnswer: 7.5, tolerance: 0, unit: "t",
    text: "Ab welcher zulässigen Gesamtmasse gilt für Lastkraftwagen das Sonn- und Feiertagsfahrverbot? Angabe in Tonnen (Fahrverbot für Lkw über dieser Masse).",
    answers: [],
    explanation: "An Sonn- und Feiertagen dürfen Lastkraftwagen mit einer zulässigen Gesamtmasse über 7,5 Tonnen sowie Anhänger hinter Lastkraftwagen in der Zeit von 0 bis 22 Uhr nicht fahren. Das dient dem Schutz vor Lärm und Abgasen sowie der Entlastung der Straßen an Wochenenden.",
    legalReference: "§ 30 Abs. 3 StVO",
  }),
  q({
    code: "own-umwelt-012", topic: "umwelt", points: 3, difficulty: 0.6, tags: ["laerm", "sonntagsfahrverbot", "lkw", "uhrzeit"], kind: "numeric", numericAnswer: 22, tolerance: 0, unit: "Uhr",
    text: "Bis zu welcher Uhrzeit gilt an Sonn- und Feiertagen das Fahrverbot für Lkw über 7,5 Tonnen? Angabe der Uhrzeit (Stunde).",
    answers: [],
    explanation: "Das Sonn- und Feiertagsfahrverbot gilt von 0 bis 22 Uhr. Ausgenommen sind unter anderem der kombinierte Verkehr Schiene-Straße in bestimmten Grenzen sowie Transporte leicht verderblicher Waren.",
    legalReference: "§ 30 Abs. 3 StVO",
  }),
  q({
    code: "own-umwelt-013", topic: "umwelt", points: 3, difficulty: 0.6, tags: ["laerm", "abgase", "innerorts", "hin_und_herfahren"],
    text: "Welche Verhaltensweisen sind nach der StVO wegen unnötigen Lärms oder vermeidbarer Abgase verboten?",
    answers: [t("Unnützes Hin- und Herfahren innerhalb geschlossener Ortschaften, wenn andere dadurch belästigt werden"), t("Den Motor beim Warten vor einer geschlossenen Bahnschranke laufen zu lassen"), t("Türen und Klappen des Fahrzeugs nachts laut zuzuschlagen oder im Stand hoch zu drehen"), f("Mit eingeschaltetem Tagfahrlicht zu fahren", "Tagfahrlicht verursacht weder Lärm noch Abgase.")],
    explanation: "Bei der Benutzung von Fahrzeugen sind unnötiger Lärm und vermeidbare Abgasbelästigungen verboten. Dazu gehören unnötiges Laufenlassen des Motors, hohes Drehen im Stand, lautes Türenschlagen und das unnütze Hin- und Herfahren innerorts, das andere belästigt.",
    legalReference: "§ 30 Abs. 1 StVO",
  }),
  q({
    code: "own-umwelt-014", topic: "umwelt", points: 3, difficulty: 0.6, tags: ["umweltzone", "plakette", "zusatzzeichen"],
    text: "Am Beginn einer Umweltzone (Zeichen 270.1) zeigt das Zusatzzeichen nur die grüne Plakette. Ihr Fahrzeug hat eine gelbe Plakette. Was gilt?",
    answers: [t("Sie dürfen nicht einfahren, weil nur Fahrzeuge mit grüner Plakette freigestellt sind"), f("Sie dürfen einfahren, weil gelb besser als rot ist", "Freigestellt sind nur die auf dem Zusatzzeichen abgebildeten Plaketten."), f("Sie dürfen einfahren, wenn Sie innerhalb der Zone wohnen", "Für Bewohner gibt es keine allgemeine Ausnahme; Ausnahmegenehmigungen erteilt die Behörde im Einzelfall."), f("Sie dürfen einfahren, wenn Sie höchstens 30 km/h fahren", "Die Geschwindigkeit spielt keine Rolle.")],
    explanation: "In eine Umweltzone dürfen nur Kraftfahrzeuge einfahren, die eine der auf dem Zusatzzeichen abgebildeten Plaketten tragen. Zeigt das Zusatzzeichen nur grün, sind gelbe und rote Plaketten ausgeschlossen. Fahren ohne passende Plakette ist eine Ordnungswidrigkeit mit Bußgeld.",
    legalReference: "§ 40 BImSchG; 35. BImSchV; Anlage 2 StVO, Zeichen 270.1; Zusatzzeichen 1031-52",
  }),
  q({
    code: "own-umwelt-015", topic: "umwelt", points: 3, difficulty: 0.6, tags: ["umweltzone", "plakette", "kennzeichen"],
    text: "Welche Aussagen zur Feinstaubplakette treffen zu?",
    answers: [t("Die Plakette trägt das Kennzeichen des Fahrzeugs und gilt nur für dieses Fahrzeug"), t("Sie muss gut sichtbar an der Innenseite der Windschutzscheibe angebracht sein"), t("Auch Fahrzeuge mit ausländischem Kennzeichen benötigen in der Umweltzone eine Plakette"), f("Elektrofahrzeuge brauchen zwar eine Plakette, dürfen aber trotzdem nur mit Genehmigung in die Umweltzone", "Elektrofahrzeuge erhalten die grüne Plakette und dürfen einfahren.")],
    explanation: "Die Feinstaubplakette wird für ein bestimmtes Fahrzeug ausgestellt, trägt dessen Kennzeichen und wird innen an der Windschutzscheibe angebracht. Bei einem Kennzeichenwechsel ist eine neue Plakette nötig. Die Pflicht gilt auch für ausländische Fahrzeuge.",
    legalReference: "35. BImSchV",
  }),
  q({
    code: "own-umwelt-016", topic: "umwelt", points: 3, difficulty: 0.55, tags: ["kraftstoff", "luftwiderstand", "geschwindigkeit", "autobahn"],
    text: "Warum steigt der Kraftstoffverbrauch bei hoher Geschwindigkeit auf der Autobahn überproportional?",
    answers: [t("Der Luftwiderstand wächst mit dem Quadrat der Geschwindigkeit; die dafür nötige Leistung steigt noch stärker"), f("Der Motor läuft bei hoher Geschwindigkeit immer im ungünstigsten Gang", "Der Gang ist nicht die Ursache; der Luftwiderstand ist entscheidend."), f("Die Reifen erhitzen sich und bremsen dadurch das Fahrzeug", "Der Rollwiderstand ändert sich mit der Geschwindigkeit nur wenig.")],
    explanation: "Der Luftwiderstand nimmt mit dem Quadrat der Geschwindigkeit zu. Wer statt 130 km/h nur 110 km/h fährt, spart deutlich Kraftstoff und verliert auf typischen Strecken nur wenige Minuten. Gleichmäßiges Fahren mit Tempomat hilft zusätzlich.",
  }),
  q({
    code: "own-umwelt-017", topic: "umwelt", points: 3, difficulty: 0.6, tags: ["kraftstoff", "start_stopp", "motor_abstellen"],
    text: "Ihr Fahrzeug hat eine Start-Stopp-Automatik. Welche Aussagen sind richtig?",
    answers: [t("Das System stellt den Motor bei Stillstand selbsttätig ab und startet ihn beim Anfahren wieder"), t("Das Abschalten spart Kraftstoff und vermeidet Abgase im Leerlauf"), f("Häufige Neustarts verbrauchen mehr Kraftstoff, als das Abstellen spart", "Der Neustart eines betriebswarmen Motors verbraucht sehr wenig; der Leerlauf verbraucht laufend."), f("Das System darf im Stadtverkehr nicht benutzt werden", "Gerade im Stadtverkehr mit vielen Halten ist der Nutzen am größten.")],
    explanation: "Die Start-Stopp-Automatik schaltet den Motor bei Stillstand ab, etwa an Ampeln, und startet ihn beim Lösen der Bremse oder Treten der Kupplung. Der Neustart eines warmen Motors verbraucht kaum Kraftstoff, während der Leerlauf dauerhaft verbraucht und Abgase erzeugt.",
  }),
  q({
    code: "own-umwelt-018", topic: "umwelt", points: 3, difficulty: 0.55, tags: ["reifen", "reifenlabel", "kraftstoff", "laerm"],
    text: "Welche Angaben finden Sie auf dem EU-Reifenlabel?",
    answers: [t("Kraftstoffeffizienz, also der Rollwiderstand"), t("Nasshaftung, also die Bremsleistung auf nasser Fahrbahn"), t("Externes Rollgeräusch in Dezibel"), f("Die Mindestprofiltiefe des Reifens", "Die Mindestprofiltiefe ist gesetzlich vorgegeben und steht nicht auf dem Label.")],
    explanation: "Das EU-Reifenlabel bewertet Kraftstoffeffizienz und Nasshaftung in Klassen und nennt das Rollgeräusch. Reifen mit niedrigem Rollwiderstand senken den Verbrauch, ohne dass die Sicherheit leiden muss, wenn die Nasshaftung gut ist.",
  }),
  q({
    code: "own-umwelt-019", topic: "umwelt", points: 3, difficulty: 0.6, tags: ["abgase", "katalysator", "kaltstart"],
    text: "Warum sind die Schadstoffemissionen in den ersten Minuten nach einem Kaltstart besonders hoch?",
    answers: [t("Der Katalysator erreicht seine Betriebstemperatur erst nach einiger Zeit und wandelt bis dahin kaum Schadstoffe um"), t("Der kalte Motor läuft mit angereichertem Gemisch und verbraucht mehr"), f("Das Motoröl ist kalt und verbrennt im Motor", "Öl wird beim Kaltstart nicht verbrannt; die höheren Emissionen entstehen im Abgassystem und durch die Gemischanreicherung."), f("Die Batterie gibt beim Start giftige Gase ab", "Die Batterie ist keine Abgasquelle.")],
    explanation: "Katalysatoren arbeiten erst ab einer bestimmten Temperatur wirksam. Zusätzlich läuft der kalte Motor mit angereichertem Gemisch. Deshalb sind Kurzstrecken pro Kilometer besonders belastend; nach dem Start sollte zügig, aber mit niedriger Drehzahl losgefahren werden.",
  }),
  q({
    code: "own-umwelt-020", topic: "umwelt", points: 3, difficulty: 0.55, tags: ["fahrzeugpflege", "wasser", "entsorgung"],
    text: "Sie wollen Ihr Auto gründlich waschen und den Motorraum reinigen. Was ist umweltgerecht?",
    answers: [t("Fahrzeug in einer Waschanlage oder auf einem dafür zugelassenen Waschplatz mit Ölabscheider waschen"), t("Motorwäsche nur in einem Fachbetrieb mit geeigneter Abwasserbehandlung durchführen lassen"), f("Auf der Straße vor dem Haus mit Schlauch und Reiniger waschen", "Abwasser mit Öl und Reinigern darf nicht in den Boden oder in die Kanalisation gelangen; viele Gemeinden verbieten das Waschen auf der Straße."), f("Den Motor mit einem Hochdruckreiniger auf dem Rasen waschen", "Ölhaltiges Wasser versickert und gefährdet das Grundwasser.")],
    explanation: "Beim Waschen lösen sich Öl, Bremsstaub und Reiniger, die nicht ins Grundwasser oder in Gewässer gelangen dürfen. Waschanlagen und zugelassene Waschplätze verfügen über Ölabscheider. Motorwäschen gehören in Fachbetriebe.",
    legalReference: "Wasserhaushaltsgesetz; kommunale Satzungen",
  }),
  q({
    code: "own-umwelt-021", topic: "umwelt", points: 3, difficulty: 0.6, tags: ["entsorgung", "batterie", "reifen", "sondermuell"],
    text: "Wie entsorgen Sie Altteile Ihres Fahrzeugs richtig?",
    answers: [t("Die alte Starterbatterie beim Händler oder an einer Sammelstelle abgeben; darauf wird beim Kauf ein Pfand erhoben"), t("Altreifen beim Reifenhändler oder Wertstoffhof abgeben"), t("Bremsflüssigkeit und Kühlmittel als Sonderabfall zur Schadstoffsammelstelle bringen"), f("Kühlmittel in den Gartenboden gießen, weil es überwiegend aus Wasser besteht", "Kühlmittel enthält giftiges Frostschutzmittel und ist Sonderabfall.")],
    explanation: "Starterbatterien enthalten Blei und Säure und werden gegen Pfand zurückgenommen. Reifen, Bremsflüssigkeit, Kühlmittel und Altöl gehören zu Sammelstellen oder Händlern, nie in den Hausmüll, in den Boden oder in die Kanalisation.",
    legalReference: "Batteriegesetz; Altölverordnung; Kreislaufwirtschaftsgesetz",
  }),
  q({
    code: "own-umwelt-022", topic: "umwelt", points: 3, difficulty: 0.6, tags: ["kraftstoff", "beladung", "gewicht", "reifendruck"],
    text: "Welche Maßnahmen senken den Kraftstoffverbrauch Ihres Fahrzeugs dauerhaft?",
    answers: [t("Unnötigen Ballast wie Getränkekisten oder Werkzeug aus dem Kofferraum entfernen"), t("Den Reifendruck regelmäßig prüfen und eher am oberen Wert der Herstellerangabe halten"), t("Regelmäßige Wartung mit Ölwechsel und sauberem Luftfilter"), f("Den Tank immer nur halb füllen, damit das Gewicht sinkt", "Die Ersparnis ist minimal und die zusätzlichen Tankfahrten verbrauchen mehr.")],
    explanation: "Zusätzliches Gewicht erhöht besonders im Stadtverkehr den Verbrauch. Richtiger Reifendruck senkt den Rollwiderstand, und ein gewarteter Motor arbeitet effizienter. Unnötige Anbauten wie Dachträger sollten abgenommen werden.",
  }),
  q({
    code: "own-umwelt-023", topic: "umwelt", points: 3, difficulty: 0.55, tags: ["abgase", "auspuff", "rauch", "sicherheitskontrolle"],
    text: "Aus dem Auspuff Ihres Fahrzeugs kommt nach dem Warmfahren dauerhaft bläulicher Rauch. Was bedeutet das?",
    answers: [t("Der Motor verbrennt Öl; die Ursache sollte in der Werkstatt geprüft werden"), f("Das ist normaler Wasserdampf bei kaltem Wetter", "Wasserdampf ist weiß und verschwindet nach dem Warmfahren."), f("Der Kraftstoff ist zu gut, das Gemisch zu fett", "Zu fettes Gemisch erzeugt schwarzen Rauch.")],
    explanation: "Blauer Rauch weist auf verbranntes Motoröl hin, schwarzer Rauch auf unvollständige Verbrennung durch zu fettes Gemisch, weißer Rauch bei warmem Motor kann auf Kühlmittel im Brennraum hindeuten. Alle drei sind Fälle für die Werkstatt, weil sie Umwelt und Motor belasten.",
  }),
  q({
    code: "own-umwelt-024", topic: "umwelt", points: 3, difficulty: 0.55, tags: ["tanken", "kraftstoff", "abgase"],
    text: "Was ist beim Tanken umweltbewusst?",
    answers: [t("Nach dem automatischen Abschalten der Zapfpistole nicht weiter nachtanken"), t("Den Motor beim Tanken abstellen"), f("Den Tank bis zum Einfüllstutzen randvoll machen, damit die Fahrt länger reicht", "Kraftstoff dehnt sich bei Wärme aus und kann austreten; das Aktivkohlefilter-System wird überlastet."), f("Verschütteten Kraftstoff mit Wasser wegspülen", "Kraftstoff darf nicht in die Kanalisation gelangen; er ist mit Bindemittel aufzunehmen.")],
    explanation: "Nach dem Abschalten der Zapfpistole ist der Tank ausreichend gefüllt. Überfüllen führt zu austretendem Kraftstoff, der Boden und Luft belastet. Verschütteter Kraftstoff wird mit Bindemittel aufgenommen, und der Motor bleibt beim Tanken aus.",
  }),
  q({
    code: "own-umwelt-025", topic: "umwelt", points: 3, difficulty: 0.6, tags: ["elektrofahrzeug", "rekuperation", "energie"],
    text: "Wie fahren Sie ein Elektrofahrzeug energiesparend?",
    answers: [t("Vorausschauend fahren und die Rekuperation nutzen, damit beim Verzögern Energie in die Batterie zurückfließt"), t("Heizung und Klimaanlage bewusst einsetzen, weil sie die Reichweite deutlich verringern"), f("Möglichst stark beschleunigen, weil Elektromotoren dabei besonders effizient arbeiten", "Starkes Beschleunigen kostet auch beim Elektroantrieb viel Energie."), f("Die Rekuperation abschalten, weil sie die Batterie schädigt", "Rekuperation ist ein normaler Betriebszustand und schont die Bremsen.")],
    explanation: "Beim Verzögern arbeitet der Elektromotor als Generator und lädt die Batterie. Vorausschauendes Fahren mit frühem Gaswegnehmen nutzt das aus. Heizung und Klimaanlage werden elektrisch betrieben und kosten spürbar Reichweite, besonders im Winter.",
  }),
  q({
    code: "own-umwelt-026", topic: "umwelt", points: 3, difficulty: 0.55, tags: ["verkehrsmittel", "park_and_ride", "oepnv"],
    text: "Welche Verhaltensweisen reduzieren die Umweltbelastung durch Ihre Mobilität am wirksamsten?",
    answers: [t("Kurze Strecken zu Fuß oder mit dem Rad zurücklegen"), t("Park-and-Ride-Plätze nutzen und in der Stadt auf öffentliche Verkehrsmittel umsteigen"), t("Fahrgemeinschaften bilden"), f("Innerorts immer den kürzesten Weg mit vielen Ampeln wählen", "Häufiges Anfahren verbraucht viel; eine flüssige Route ist oft sparsamer, auch wenn sie etwas länger ist.")],
    explanation: "Die größte Einsparung bringt es, Fahrten zu vermeiden oder auf umweltfreundliche Verkehrsmittel zu verlagern. Park-and-Ride-Plätze (Zeichen 316) verbinden Auto und öffentlichen Verkehr. Fahrgemeinschaften teilen Verbrauch und Kosten.",
  }),
  q({
    code: "own-umwelt-027", topic: "umwelt", points: 3, difficulty: 0.6, tags: ["kraftstoff", "schalten", "drehzahl", "stadt"],
    text: "Sie fahren mit einem Schaltwagen in einer Tempo-30-Zone. Welche Fahrweise ist umweltschonend und zulässig?",
    answers: [t("Im dritten oder vierten Gang mit niedriger Drehzahl rollen, sofern der Motor rund läuft"), t("Beim Beschleunigen zügig Gas geben und früh hochschalten, dabei Gänge überspringen, wenn es passt"), f("Im zweiten Gang bleiben, damit der Motor genug Kraft hat", "Der zweite Gang bedeutet bei 30 km/h unnötig hohe Drehzahl und Verbrauch."), f("Vor jeder Kreuzung auskuppeln und rollen", "Im Leerlauf wird Kraftstoff verbraucht; im Gang greift die Schubabschaltung.")],
    explanation: "Niedrige Drehzahl in einem hohen Gang spart Kraftstoff und Lärm. Moderne Motoren laufen bei 30 km/h im dritten oder vierten Gang ruhig. Zügiges Beschleunigen mit frühem Hochschalten ist sparsamer als langsames Hochdrehen in niedrigen Gängen.",
  }),
  q({
    code: "own-umwelt-028", topic: "umwelt", points: 3, difficulty: 0.55, tags: ["laerm", "hupe", "musik", "innerorts"],
    text: "Welche Lärmquellen am Fahrzeug sind vermeidbar und deshalb unzulässig?",
    answers: [t("Hupen, um Bekannte zu grüßen oder sich zu verabschieden"), t("Sehr laute Musik bei geöffneten Fenstern, die andere belästigt"), t("Ein nachträglich veränderter Auspuff, der lauter ist als zugelassen"), f("Das Warnzeichen mit der Hupe, wenn ein Kind auf die Fahrbahn zu laufen droht", "Warnzeichen zur Abwehr einer Gefahr sind erlaubt und geboten.")],
    explanation: "Die Hupe darf nur als Warnzeichen bei Gefahr und außerorts zur Überholankündigung benutzt werden. Laute Musik und unzulässig veränderte Auspuffanlagen sind vermeidbarer Lärm; letztere führen zudem zum Erlöschen der Betriebserlaubnis.",
    legalReference: "§ 16 StVO; § 30 Abs. 1 StVO; § 19 StVZO",
  }),
  q({
    code: "own-umwelt-029", topic: "umwelt", points: 3, difficulty: 0.55, tags: ["klimaanlage", "heizung", "verbraucher"],
    text: "Wie nutzen Sie Klimaanlage und Heizung verbrauchsbewusst?",
    answers: [t("Bei kurzer Fahrt an heißen Tagen zuerst kurz lüften, dann Fenster schließen und die Klimaanlage moderat einstellen"), t("Heckscheibenheizung und Sitzheizung ausschalten, sobald sie nicht mehr gebraucht werden"), f("Bei Autobahnfahrt die Fenster öffnen statt die Klimaanlage zu nutzen", "Offene Fenster erhöhen bei hoher Geschwindigkeit den Luftwiderstand stärker als die Klimaanlage verbraucht."), f("Die Klimaanlage auf die tiefste Temperatur stellen, damit sie schneller fertig ist", "Sehr niedrige Temperaturen kosten dauerhaft mehr Energie und sind ungesund.")],
    explanation: "Die Klimaanlage verbraucht Energie, besonders bei großer Temperaturdifferenz. Kurzes Lüften vor der Fahrt senkt die Innentemperatur ohne Kraftstoff. Bei hoher Geschwindigkeit ist die Klimaanlage sparsamer als offene Fenster. Elektrische Verbraucher nur bei Bedarf einschalten.",
  }),
  q({
    code: "own-umwelt-030", topic: "umwelt", points: 3, difficulty: 0.6, tags: ["kraftstoff", "vorausschauend", "abstand", "verkehrsfluss"],
    text: "Wie wirkt sich vorausschauendes Fahren mit großem Abstand im dichten Stadtverkehr aus?",
    answers: [t("Sie müssen seltener anhalten und wieder anfahren, was Kraftstoff und Bremsen schont"), t("Der Verkehr fließt gleichmäßiger, weil Stop-and-go-Wellen abgeschwächt werden"), f("Sie kommen deutlich später an, weil andere die Lücke nutzen", "Im dichten Verkehr ist die Ankunftszeit fast gleich; das Anfahren kostet nur Energie."), f("Der Verbrauch steigt, weil das Fahrzeug länger unterwegs ist", "Weniger Anfahrvorgänge sparen mehr, als die kaum längere Fahrzeit kostet.")],
    explanation: "Wer mit Abstand rollt, statt aufzuschließen und zu bremsen, vermeidet die verbrauchsintensiven Anfahrvorgänge. Das glättet zugleich den Verkehrsfluss für alle. Vorausschauendes Fahren ist die wirksamste einzelne Maßnahme für Sparsamkeit und Sicherheit.",
  }),
  q({
    code: "own-umwelt-031", topic: "umwelt", points: 2, difficulty: 0.45, tags: ["motor_abstellen", "wartezeit", "abgase"],
    text: "Sie holen jemanden ab und warten voraussichtlich mehrere Minuten vor dem Haus. Was ist richtig?",
    answers: [t("Motor abstellen; auch bei kurzen Wartezeiten spart das Kraftstoff und vermeidet Abgase und Lärm"), f("Motor laufen lassen, damit der Innenraum warm bleibt", "Das Laufenlassen zum Heizen ist verboten und belastet die Umwelt."), f("Im Leerlauf gelegentlich Gas geben, damit die Zündkerzen nicht verrußen", "Das ist unnötig und erzeugt nur Lärm und Abgase.")],
    explanation: "Ein laufender Motor im Stand verbraucht Kraftstoff, erzeugt Abgase und Lärm, ohne dass das Fahrzeug fährt. Wer wartet, stellt den Motor ab. Der Neustart eines warmen Motors verbraucht nur sehr wenig.",
    legalReference: "§ 30 Abs. 1 StVO",
  }),
  q({
    code: "own-umwelt-032", topic: "umwelt", points: 2, difficulty: 0.4, tags: ["umweltzone", "zeichen_270"],
    text: "Was zeigt das Zeichen 270.2 an?",
    answers: [t("Das Ende der Umweltzone; ab hier dürfen auch Fahrzeuge ohne freigegebene Plakette fahren"), f("Den Beginn einer Umweltzone mit strengeren Regeln", "Der Beginn wird mit Zeichen 270.1 gekennzeichnet."), f("Eine Zone mit Fahrverbot für Dieselfahrzeuge", "Zeichen 270.2 hebt die Umweltzone auf.")],
    explanation: "Zeichen 270.1 markiert den Beginn der Umweltzone, Zeichen 270.2 ihr Ende. Innerhalb der Zone gilt das Verkehrsverbot für Fahrzeuge ohne die auf dem Zusatzzeichen freigegebene Plakette.",
    legalReference: "Anlage 2 StVO, Zeichen 270.2",
  }),
  q({
    code: "own-umwelt-033", topic: "umwelt", points: 2, difficulty: 0.4, tags: ["kraftstoff", "tempomat", "gleichmaessig"],
    text: "Warum senkt eine gleichmäßige Fahrweise den Kraftstoffverbrauch?",
    answers: [t("Jedes Beschleunigen kostet Energie, die beim anschließenden Bremsen wieder vernichtet wird"), f("Der Motor läuft bei gleicher Geschwindigkeit immer im kleinsten Gang", "Der Gang hängt von der Fahrweise ab, nicht allein von der Geschwindigkeit."), f("Die Reifen nutzen sich bei gleichmäßiger Fahrt gar nicht ab", "Der Verschleiß ist geringer, aber nicht null.")],
    explanation: "Beschleunigen wandelt Kraftstoff in Bewegungsenergie um, die beim Bremsen in Wärme verloren geht. Wer gleichmäßig fährt und Tempomat oder vorausschauendes Rollen nutzt, vermeidet diesen Kreislauf und spart Kraftstoff.",
  }),
  q({
    code: "own-umwelt-034", topic: "umwelt", points: 2, difficulty: 0.4, tags: ["reifen", "mikroplastik", "abrieb"],
    text: "Welche Umweltbelastung entsteht auch bei einem Elektrofahrzeug beim Fahren?",
    answers: [t("Feinstaub durch Reifen- und Bremsabrieb sowie Aufwirbelung von Straßenstaub"), f("Keine, weil Elektrofahrzeuge lokal emissionsfrei sind", "Ohne Auspuff entfallen Abgase, Abrieb und Lärm bleiben."), f("Stickoxide aus dem Elektromotor", "Elektromotoren erzeugen keine Stickoxide.")],
    explanation: "Elektrofahrzeuge stoßen lokal keine Abgase aus. Feinstaub durch Reifenabrieb, Bremsstaub und aufgewirbelten Straßenstaub entsteht aber bei jedem Fahrzeug. Sanfte Fahrweise und Rekuperation verringern den Abrieb.",
  }),
  q({
    code: "own-umwelt-035", topic: "umwelt", points: 2, difficulty: 0.35, tags: ["wartung", "abgasuntersuchung", "hauptuntersuchung"],
    text: "Welche Bedeutung hat die regelmäßige Wartung des Fahrzeugs für die Umwelt?",
    answers: [t("Ein gut gewarteter Motor mit sauberem Luftfilter und richtig eingestellter Zündung verbraucht weniger und stößt weniger Schadstoffe aus"), f("Keine, Emissionen hängen nur vom Fahrstil ab", "Auch der technische Zustand beeinflusst die Emissionen erheblich."), f("Die Wartung erhöht den Verbrauch, weil frisches Öl dickflüssiger ist", "Frisches Öl senkt die Reibung.")],
    explanation: "Verschmutzte Filter, alte Zündkerzen oder falsch eingestellte Motoren erhöhen Verbrauch und Emissionen. Die Abgasuntersuchung als Teil der Hauptuntersuchung prüft, ob die Abgaswerte eingehalten werden.",
    legalReference: "§ 29 StVZO",
  }),
  q({
    code: "own-umwelt-036", topic: "umwelt", points: 2, difficulty: 0.4, tags: ["kraftstoff", "reifen", "winterreifen", "sommer"],
    text: "Sie fahren im Sommer weiter mit Winterreifen. Welche Folgen hat das?",
    answers: [t("Höherer Verbrauch, stärkerer Verschleiß und längerer Bremsweg auf warmer, trockener Fahrbahn"), f("Keine, Winterreifen sind Allwetterreifen", "Die weiche Wintermischung ist für hohe Temperaturen ungeeignet."), f("Der Bremsweg wird kürzer, weil die Reifen weicher sind", "Auf warmem Asphalt verlängert sich der Bremsweg mit Winterreifen.")],
    explanation: "Winterreifen haben eine weiche Gummimischung und Lamellen, die bei Wärme schneller verschleißen, den Rollwiderstand erhöhen und schlechter bremsen. Ein rechtzeitiger Wechsel spart Kraftstoff und erhöht die Sicherheit.",
  }),
  q({
    code: "own-umwelt-037", topic: "umwelt", points: 3, difficulty: 0.6, tags: ["kraftstoff", "faustformel", "verbrauch"], kind: "numeric", numericAnswer: 6, tolerance: 0, unit: "l/100 km",
    text: "Ihr Fahrzeug verbraucht auf einer Strecke von 250 km insgesamt 15 Liter Kraftstoff. Wie hoch ist der Durchschnittsverbrauch in Litern je 100 Kilometer?",
    answers: [],
    explanation: "Der Verbrauch je 100 Kilometer ergibt sich aus Kraftstoffmenge geteilt durch Strecke mal 100: 15 Liter geteilt durch 250 km mal 100 ergibt 6 Liter je 100 km. Wer seinen Verbrauch kennt, erkennt Veränderungen durch Fahrweise oder technische Mängel frühzeitig.",
  }),
  q({
    code: "own-umwelt-038", topic: "umwelt", points: 3, difficulty: 0.6, tags: ["kraftstoff", "faustformel", "verbrauch", "kosten"], kind: "numeric", numericAnswer: 40, tolerance: 0, unit: "l",
    text: "Ein Fahrzeug verbraucht 5 Liter je 100 Kilometer. Wie viele Liter Kraftstoff werden für eine Fahrt von 800 km benötigt?",
    answers: [],
    explanation: "800 km entsprechen 8 mal 100 km. Bei 5 Litern je 100 km werden 8 mal 5, also 40 Liter benötigt. Wer sparsamer fährt, senkt Kosten und Emissionen im gleichen Verhältnis.",
  }),
  q({
    code: "own-umwelt-039", topic: "umwelt", points: 3, difficulty: 0.55, tags: ["laerm", "nachtfahrverbot", "verkehrszeichen", "zusatzzeichen"],
    text: "Ein Verbot für Kraftfahrzeuge über 3,5 t (Zeichen 253) trägt das Zusatzzeichen 22 bis 6 Uhr. Was bedeutet das?",
    answers: [t("Lkw über 3,5 t dürfen die Straße nachts nicht befahren, tagsüber schon"), t("Solche Regelungen dienen meist dem Lärmschutz für Anwohner"), f("Alle Fahrzeuge dürfen nachts nicht einfahren", "Das Verbot gilt nur für die auf dem Hauptzeichen genannten Fahrzeuge."), f("Das Zusatzzeichen hebt das Verbot nachts auf", "Das Zusatzzeichen beschränkt das Verbot auf die Nachtzeit.")],
    explanation: "Zusatzzeichen mit Zeitangabe beschränken das Hauptzeichen auf den genannten Zeitraum. Nachtfahrverbote für schwere Kraftfahrzeuge schützen Wohngebiete vor Lärm. Außerhalb der Zeit gilt das Verbot nicht.",
    legalReference: "§ 39 Abs. 3 StVO; Anlage 2 StVO, Zeichen 253; Zusatzzeichen 1040-30",
  }),
  q({
    code: "own-umwelt-040", topic: "umwelt", points: 2, difficulty: 0.35, tags: ["kraftstoff", "navigation", "routenwahl"],
    text: "Wie kann die Routenplanung zur Umweltentlastung beitragen?",
    answers: [t("Fahrten bündeln und Routen mit gleichmäßigem Verkehrsfluss wählen, auch wenn sie etwas länger sind"), t("Staus mithilfe aktueller Verkehrsinformationen umfahren"), f("Immer die Route mit den meisten Ampeln wählen, weil man dort langsamer fährt", "Häufiges Anfahren verbraucht viel Kraftstoff."), f("Grundsätzlich die schnellste Autobahnroute mit hoher Geschwindigkeit wählen", "Hohe Geschwindigkeit erhöht den Verbrauch stark.")],
    explanation: "Gebündelte Fahrten vermeiden Kaltstarts, und flüssige Strecken sparen Anfahrvorgänge. Aktuelle Verkehrsinformationen helfen, Stop-and-go zu umgehen. Die Fahrzeit unterscheidet sich oft kaum, der Verbrauch deutlich.",
  }),
];
