// Übungsfragen zum Thema "unfall_panne" (eigene Formulierungen, kein amtlicher Prüfungsinhalt).
import type { Question } from "../types";
import { q, t, f } from "./_helpers";

export const unfallPanne: readonly Question[] = [
  q({
    code: "own-unfall_panne-001", topic: "unfall_panne", points: 3, difficulty: 0.3, tags: ["warndreieck", "autobahn", "absichern"],
    text: "In welcher Entfernung stellen Sie das Warndreieck auf der Autobahn nach der üblichen Faustregel auf?",
    answers: [t("Etwa 150 bis 200 Meter hinter dem Fahrzeug"), f("Etwa 50 Meter hinter dem Fahrzeug", "Das reicht auf der Autobahn bei hohen Geschwindigkeiten nicht aus."), f("Etwa 400 Meter hinter dem Fahrzeug", "So weit ist nicht nötig; üblich sind 150 bis 200 Meter.")],
    explanation: "Die StVO verlangt nur, das Warndreieck in ausreichender Entfernung aufzustellen; feste Meterangaben nennt sie nicht. Als Faustregel aus der Fahrpraxis gelten auf der Autobahn etwa 150 bis 200 Meter, auf Landstraßen etwa 100 Meter, innerorts etwa 50 Meter. Vor Kurven und Kuppen entsprechend weiter.",
    legalReference: "§ 15 Abs. 1 StVO (ausreichende Entfernung); Meterangaben sind Praxisempfehlung",
  }),
  q({
    code: "own-unfall_panne-002", topic: "unfall_panne", points: 2, difficulty: 0.3, tags: ["warndreieck", "ausserorts", "absichern"],
    text: "In welcher Entfernung stellen Sie das Warndreieck auf einer Landstraße nach der üblichen Faustregel auf?",
    answers: [t("Etwa 100 Meter hinter dem Fahrzeug"), f("Etwa 20 Meter hinter dem Fahrzeug", "Das ist zu nah, um nachfolgende Fahrzeuge rechtzeitig zu warnen."), f("Etwa 300 Meter hinter dem Fahrzeug", "Auf Landstraßen sind etwa 100 Meter üblich.")],
    explanation: "Die StVO schreibt nur eine ausreichende Entfernung vor, keine feste Meterzahl. Als Faustregel aus der Fahrpraxis gelten auf Landstraßen etwa 100 Meter. Wichtig ist, dass das Dreieck vor Kurven oder Kuppen für den nachfolgenden Verkehr rechtzeitig sichtbar ist.",
    legalReference: "§ 15 Abs. 1 StVO (ausreichende Entfernung); Meterangaben sind Praxisempfehlung",
  }),
  q({
    code: "own-unfall_panne-003", topic: "unfall_panne", points: 3, difficulty: 0.2, tags: ["unfall", "absichern", "rettungskette"],
    text: "Sie kommen als Erster an eine Unfallstelle mit Verletzten. Was ist die erste Maßnahme?",
    answers: [t("Die Unfallstelle absichern: Warnblinklicht, Warnweste, Warndreieck"), f("Sofort die Verletzten aus dem Fahrzeug ziehen", "Ohne Absicherung gefährden Sie sich und andere; Verletzte nur bei akuter Gefahr bewegen."), f("Erst die Versicherung anrufen", "Die Versicherung ist später an der Reihe.")],
    explanation: "Die Rettungskette beginnt mit dem Absichern der Unfallstelle, dann folgt der Notruf, dann die Erste Hilfe. Eigenschutz geht vor.",
    mnemonic: "Absichern, Notruf, Erste Hilfe.",
    legalReference: "§ 34 StVO; § 323c StGB",
  }),
  q({
    code: "own-unfall_panne-004", topic: "unfall_panne", points: 2, difficulty: 0.2, tags: ["notruf"],
    text: "Welche Angaben gehören zu einem vollständigen Notruf unter 112?",
    answers: [t("Wo ist es passiert?"), t("Was ist passiert und wie viele Verletzte gibt es?"), t("Warten auf Rückfragen der Leitstelle"), f("Eigene Versicherungsnummer", "Diese Angabe ist für den Rettungsdienst ohne Bedeutung.")],
    explanation: "Beim Notruf zählen die W-Fragen: Wo, Was, Wie viele Verletzte, Welche Verletzungen, und Warten auf Rückfragen. Die 112 ist europaweit die Notrufnummer.",
    mnemonic: "Wo, Was, Wie viele, Welche, Warten.",
  }),
  q({
    code: "own-unfall_panne-005", topic: "unfall_panne", points: 3, difficulty: 0.4, tags: ["unfallflucht", "parken", "sachschaden"],
    text: "Beim Ausparken beschädigen Sie ein geparktes Auto. Der Halter ist nicht auffindbar. Was müssen Sie tun?",
    answers: [t("Eine angemessene Zeit warten und danach unverzüglich die Polizei oder den Halter verständigen"), f("Einen Zettel mit Ihrer Telefonnummer hinterlassen und wegfahren", "Ein Zettel allein erfüllt die Pflichten nicht und kann als Unfallflucht gewertet werden."), f("Wegfahren, weil es nur ein kleiner Schaden ist", "Auch bei kleinen Schäden ist das unerlaubtes Entfernen vom Unfallort.")],
    explanation: "Nach einem Unfall müssen Sie eine angemessene Zeit am Unfallort warten. Trifft niemand ein, sind unverzüglich der Geschädigte oder die Polizei zu informieren.",
    legalReference: "§ 142 StGB; § 34 StVO",
  }),
  q({
    code: "own-unfall_panne-006", topic: "unfall_panne", points: 2, difficulty: 0.2, tags: ["warnweste", "ausruestung"],
    text: "Was muss in einem Pkw neben Warndreieck und Verbandkasten mitgeführt werden?",
    answers: [t("Mindestens eine Warnweste"), f("Ein Feuerlöscher", "Ein Feuerlöscher ist im Pkw nicht vorgeschrieben."), f("Ein Abschleppseil", "Ein Abschleppseil ist sinnvoll, aber nicht Pflicht.")],
    explanation: "In Pkw muss eine Warnweste mitgeführt werden, zusätzlich zu Warndreieck und Verbandkasten. Bei einer Panne oder einem Unfall sollte sie vor dem Aussteigen angelegt werden.",
    legalReference: "§ 53a StVZO; § 35h StVZO",
  }),
  q({
    code: "own-unfall_panne-007", topic: "unfall_panne", points: 4, difficulty: 0.3, tags: ["panne", "autobahn", "absichern"],
    text: "Sie haben eine Panne auf der Autobahn. Wie verhalten Sie sich richtig?",
    answers: [t("Auf den Seitenstreifen fahren und das Warnblinklicht einschalten"), t("Warnweste anziehen und das Warndreieck aufstellen"), t("Sich und Mitfahrende hinter der Schutzplanke in Sicherheit bringen"), f("Im Fahrzeug bleiben und auf den Pannendienst warten", "Im Fahrzeug auf dem Seitenstreifen besteht Lebensgefahr durch auffahrende Fahrzeuge.")],
    explanation: "Bei einer Panne auf der Autobahn: Seitenstreifen, Warnblinklicht, Warnweste, Warndreieck, dann hinter die Schutzplanke. Hilfe über die Notrufsäule oder die 112 anfordern.",
    legalReference: "§ 15 StVO",
  }),
  q({
    code: "own-unfall_panne-008", topic: "unfall_panne", points: 3, difficulty: 0.3, tags: ["erste_hilfe", "seitenlage"],
    text: "Eine verunglückte Person ist bewusstlos, atmet aber normal. Was tun Sie?",
    answers: [t("Die Person in die stabile Seitenlage bringen und die Atmung weiter überwachen"), f("Die Person auf den Rücken legen und den Kopf hochlagern", "In Rückenlage kann die Zunge die Atemwege verschließen."), f("Sofort mit der Herzdruckmassage beginnen", "Die Herzdruckmassage ist nur bei fehlender normaler Atmung angezeigt.")],
    explanation: "Bewusstlose mit normaler Atmung kommen in die stabile Seitenlage, damit die Atemwege frei bleiben. Atmet die Person nicht normal, beginnt die Wiederbelebung.",
  }),
  q({
    code: "own-unfall_panne-009", topic: "unfall_panne", points: 2, difficulty: 0.2, tags: ["hilfeleistung", "recht"],
    text: "Sie fahren an einem Unfall mit Verletzten vorbei, ohne zu helfen, obwohl es Ihnen zumutbar wäre. Was gilt?",
    answers: [t("Unterlassene Hilfeleistung ist eine Straftat"), f("Es ist eine Ordnungswidrigkeit mit Verwarnungsgeld", "Unterlassene Hilfeleistung ist im Strafgesetzbuch geregelt."), f("Es hat keine rechtlichen Folgen, wenn andere helfen könnten", "Jeder ist zur zumutbaren Hilfe verpflichtet.")],
    explanation: "Wer bei Unglücksfällen nicht hilft, obwohl es erforderlich und zumutbar ist, macht sich strafbar. Absichern und Notruf sind jedem zumutbar.",
    legalReference: "§ 323c StGB",
  }),
  q({
    code: "own-unfall_panne-010", topic: "unfall_panne", points: 2, difficulty: 0.3, tags: ["notrufsaeule", "autobahn"],
    text: "Woran erkennen Sie auf der Autobahn die Richtung zur nächsten Notrufsäule?",
    answers: [t("An den schwarzen Pfeilen auf den Leitpfosten"), f("An der Farbe der Leitplanken", "Die Leitplanken geben keine Richtung an."), f("Notrufsäulen stehen immer in Fahrtrichtung rechts nach jeder Ausfahrt", "Es gibt keine solche feste Regel; die Pfeile weisen den Weg.")],
    explanation: "Die kleinen Pfeile auf den Leitpfosten zeigen die Richtung zur nächsten Notrufsäule. Alternativ kann der Notruf über die 112 abgesetzt werden.",
  }),
  q({
    code: "own-unfall_panne-011", topic: "unfall_panne", points: 3, difficulty: 0.4, tags: ["erste_hilfe", "motorrad", "helm"],
    text: "Ein verunglückter Motorradfahrer ist bewusstlos und trägt einen Helm. Was ist richtig?",
    answers: [t("Den Helm vorsichtig abnehmen, um Atmung zu prüfen und die Atemwege freizuhalten"), f("Den Helm niemals abnehmen, das darf nur der Notarzt", "Bei Bewusstlosigkeit muss der Helm ab, sonst kann die Atmung nicht gesichert werden."), f("Den Helm aufsetzen lassen und den Fahrer aufrecht setzen", "Bewusstlose werden nicht aufgesetzt.")],
    explanation: "Bei bewusstlosen Motorradfahrern wird der Helm vorsichtig abgenommen, möglichst zu zweit und mit stabilisiertem Kopf. Danach Atmung prüfen und stabile Seitenlage.",
  }),
  q({
    code: "own-unfall_panne-012", topic: "unfall_panne", points: 4, difficulty: 0.7, tags: ["unfall", "pflichten", "sachschaden", "absichern"],
    text: "Sie sind an einem Unfall mit geringem Sachschaden beteiligt, es gibt keine Verletzten. Beide Fahrzeuge stehen fahrbereit auf der Fahrbahn einer stark befahrenen Straße. Was ist richtig?",
    answers: [t("Unfallstelle kurz absichern und die Fahrzeuge unverzüglich zur Seite fahren, damit der Verkehr fließen kann"), t("Vorher die Endstellung der Fahrzeuge fotografieren oder markieren, um den Hergang belegen zu können"), t("Name, Anschrift und Kennzeichen mit dem anderen Beteiligten austauschen"), f("Die Fahrzeuge unbedingt stehen lassen, bis die Polizei den Unfall aufgenommen hat", "Bei geringfügigem Schaden müssen die Fahrzeuge unverzüglich beiseite gefahren werden.")],
    explanation: "Bei geringfügigem Sachschaden sind die Beteiligten verpflichtet, unverzüglich beiseite zu fahren, damit der Verkehr nicht unnötig behindert wird. Zuvor Beweise sichern, etwa durch Fotos. Personalien und Kennzeichen müssen ausgetauscht werden; die Polizei muss bei reinem Bagatellschaden nicht kommen.",
    legalReference: "§ 34 Abs. 1 StVO",
  }),
  q({
    code: "own-unfall_panne-013", topic: "unfall_panne", points: 4, difficulty: 0.7, tags: ["unfall", "pflichten", "verletzte", "polizei"],
    text: "Bei einem Unfall wurde eine Person verletzt. Welche Pflichten haben Sie als Beteiligter?",
    answers: [t("Sofort anhalten, die Unfallstelle absichern und Erste Hilfe leisten"), t("Den Notruf absetzen und am Unfallort bleiben, bis die Feststellungen getroffen sind"), t("Unfallspuren nicht beseitigen, bevor die Polizei sie festgestellt hat"), f("Die Fahrzeuge sofort beiseite fahren, damit der Verkehr nicht behindert wird", "Bei Verletzten bleibt die Unfallstelle unverändert, bis die Polizei die Spuren gesichert hat; nur Absichern ist Pflicht.")],
    explanation: "Bei einem Unfall mit Verletzten müssen Beteiligte anhalten, sichern, Hilfe leisten und die Polizei verständigen. Die Fahrzeuge bleiben stehen, bis die Feststellungen getroffen sind; nur bei reinem Bagatellschaden gilt die Pflicht zum sofortigen Beiseitefahren.",
    legalReference: "§ 34 Abs. 1 StVO; § 323c StGB",
  }),
  q({
    code: "own-unfall_panne-014", topic: "unfall_panne", points: 3, difficulty: 0.65, tags: ["unfallflucht", "sachschaden", "recht"],
    text: "Sie streifen nachts auf einem Parkplatz ein geparktes Auto und fahren nach Hause, weil niemand da ist. Was gilt?",
    answers: [t("Sie haben sich unerlaubt vom Unfallort entfernt und damit eine Straftat begangen"), t("Wer sich bei nicht bedeutendem Sachschaden außerhalb des fließenden Verkehrs innerhalb von 24 Stunden freiwillig meldet, kann milder bestraft werden oder straffrei bleiben"), f("Auf Parkplätzen gilt die Pflicht zum Warten nicht", "Auch auf öffentlich zugänglichen Parkplätzen gilt § 142 StGB."), f("Ein Zettel an der Windschutzscheibe hätte alle Pflichten erfüllt", "Ein Zettel kann verloren gehen; er ersetzt weder Wartezeit noch Meldung.")],
    explanation: "Wer sich nach einem Unfall entfernt, ohne eine angemessene Zeit zu warten oder die Feststellungen zu ermöglichen, macht sich strafbar. Bei geringem Sachschaden außerhalb des fließenden Verkehrs sieht das Gesetz eine Strafmilderung oder das Absehen von Strafe vor, wenn die Meldung freiwillig innerhalb von 24 Stunden nachgeholt wird.",
    legalReference: "§ 142 Abs. 1 und 4 StGB", reviewStatus: "needs_verification",
  }),
  q({
    code: "own-unfall_panne-015", topic: "unfall_panne", points: 3, difficulty: 0.6, tags: ["wildunfall", "wild", "polizei", "versicherung"],
    text: "Sie haben nachts ein Reh angefahren, das Tier liegt tot am Straßenrand. Was ist richtig?",
    answers: [t("Unfallstelle absichern und Polizei oder Jagdpächter verständigen"), t("Das Tier nicht mitnehmen; das wäre Wilderei"), t("Für die Versicherung eine Wildunfallbescheinigung ausstellen lassen"), f("Das tote Tier in den Kofferraum legen und selbst entsorgen", "Wild gehört dem Jagdausübungsberechtigten; Mitnehmen ist strafbar.")],
    explanation: "Nach einem Wildunfall wird die Unfallstelle gesichert, verletztes Wild nicht angefasst und die Polizei oder der Jagdpächter informiert. Der Wildunfall wird bescheinigt, was die Teilkaskoversicherung verlangt. Das Tier darf nicht mitgenommen werden.",
  }),
  q({
    code: "own-unfall_panne-016", topic: "unfall_panne", points: 4, difficulty: 0.75, tags: ["abschleppen", "autobahn", "warnblinklicht"],
    text: "Ihr Fahrzeug ist auf der Autobahn liegen geblieben und ein Bekannter will es mit seinem Pkw abschleppen. Was gilt?",
    answers: [t("Die Autobahn muss an der nächsten Ausfahrt verlassen werden"), t("Beide Fahrzeuge müssen das Warnblinklicht einschalten"), f("Das Abschleppen darf bis zur Heimatwerkstatt fortgesetzt werden, auch über mehrere Ausfahrten", "Auf der Autobahn muss an der nächsten Ausfahrt abgefahren werden."), f("Der Bekannte darf zum Abschleppen auf die Autobahn auffahren", "Zum Abschleppen darf nicht auf die Autobahn aufgefahren werden.")],
    explanation: "Beim Abschleppen ist die Autobahn an der nächsten Ausfahrt zu verlassen, und ein Fahrzeug darf zum Abschleppen nicht auf die Autobahn auffahren. Beide Fahrzeuge müssen das Warnblinklicht eingeschaltet haben. Abgeschleppt werden darf nur ein liegen gebliebenes Fahrzeug bis zur nächsten geeigneten Werkstatt.",
    legalReference: "§ 15a StVO",
  }),
  q({
    code: "own-unfall_panne-017", topic: "unfall_panne", points: 3, difficulty: 0.65, tags: ["abschleppen", "lenkung", "bremsen", "technik"],
    text: "Sie sitzen im abgeschleppten Fahrzeug mit abgestelltem Motor. Womit müssen Sie rechnen?",
    answers: [t("Lenkung und Bremse erfordern deutlich mehr Kraft, weil Servolenkung und Bremskraftverstärker nicht arbeiten"), t("Die Zündung muss eingeschaltet sein, damit das Lenkradschloss nicht einrastet und Blinker sowie Bremslicht funktionieren"), f("Das Fahrzeug bremst von selbst mit, wenn das Zugfahrzeug bremst", "Nur der Fahrer im abgeschleppten Fahrzeug kann bremsen; das Seil muss straff bleiben."), f("Der Blinker funktioniert nur beim Zugfahrzeug, das genügt", "Beide Fahrzeuge müssen Fahrtrichtungsänderungen anzeigen.")],
    explanation: "Ohne laufenden Motor fehlen Servolenkung und Bremskraftverstärker, deshalb sind Lenken und Bremsen kraftaufwendig. Die Zündung bleibt eingeschaltet, damit das Lenkradschloss frei bleibt und die Lichtanlage funktioniert. Der Fahrer im abgeschleppten Fahrzeug muss das Seil durch leichtes Bremsen straff halten.",
    legalReference: "§ 15a StVO",
  }),
  q({
    code: "own-unfall_panne-018", topic: "unfall_panne", points: 3, difficulty: 0.55, tags: ["starthilfe", "batterie", "technik"],
    text: "Sie geben mit Ihrem Pkw Starthilfe. In welcher Reihenfolge werden die Kabel angeschlossen?",
    answers: [t("Rotes Kabel an den Pluspol der leeren Batterie, dann an den Pluspol der Spenderbatterie; schwarzes Kabel an den Minuspol der Spenderbatterie, dann an einen Massepunkt am Motorblock des Empfängerfahrzeugs"), f("Schwarzes Kabel zuerst an beide Minuspole, dann rotes Kabel an beide Pluspole", "Der letzte Anschluss soll ein Massepunkt fern der Batterie sein, um Funken an der Batterie zu vermeiden."), f("Beide Kabel gleichzeitig an die Pole der leeren Batterie, dann an die Spenderbatterie", "Die Reihenfolge Plus vor Minus und Masse zuletzt ist wichtig.")],
    explanation: "Zuerst wird das rote Kabel an die Pluspole angeschlossen, dann das schwarze an den Minuspol der Spenderbatterie und zuletzt an einen blanken Massepunkt am Empfängermotor. So entstehen keine Funken an der Batterie, aus der Knallgas austreten kann. Abgeklemmt wird in umgekehrter Reihenfolge.",
  }),
  q({
    code: "own-unfall_panne-019", topic: "unfall_panne", points: 3, difficulty: 0.6, tags: ["reifenpanne", "radwechsel", "notrad"],
    text: "Sie wechseln nach einer Reifenpanne am Straßenrand das Rad. Was ist richtig?",
    answers: [t("Fahrzeug absichern, Feststellbremse anziehen und Gang beziehungsweise Stellung P einlegen"), t("Radmuttern bereits vor dem Anheben lösen und nach dem Absenken über Kreuz festziehen"), t("Ein Notrad nur mit der darauf angegebenen Höchstgeschwindigkeit und nur bis zur Werkstatt fahren"), f("Den Wagenheber auf weichem Boden mit einem Brett stabilisieren und unter das Fahrzeug kriechen", "Unter ein nur mit dem Wagenheber angehobenes Fahrzeug darf man sich nie legen.")],
    explanation: "Vor dem Radwechsel das Fahrzeug gegen Wegrollen sichern und den Verkehr warnen. Die Radmuttern werden am stehenden Rad gelöst, nach dem Wechsel über Kreuz angezogen und nach kurzer Fahrstrecke nachgezogen. Für Noträder gilt die auf dem Rad angegebene Höchstgeschwindigkeit; sie sind nur für kurze Strecken gedacht.",
  }),
  q({
    code: "own-unfall_panne-020", topic: "unfall_panne", points: 3, difficulty: 0.55, tags: ["ueberhitzung", "kuehlwasser", "technik"],
    text: "Die Kühlmitteltemperatur steigt in den roten Bereich und Dampf tritt aus der Motorhaube. Was tun Sie?",
    answers: [t("Sicher anhalten, Motor abstellen und den Kühler abkühlen lassen, bevor der Verschluss vorsichtig geöffnet wird"), f("Sofort den Kühlerverschluss öffnen und kaltes Wasser nachfüllen", "Das heiße System steht unter Druck; es droht Verbrühung. Kaltes Wasser in den heißen Motor kann Risse verursachen."), f("Mit hoher Drehzahl weiterfahren, damit mehr Fahrtwind kühlt", "Weiterfahren führt zum Motorschaden.")],
    explanation: "Bei Überhitzung ist der Motor sofort abzustellen. Der Kühlkreislauf steht unter Druck, deshalb den Verschluss erst nach dem Abkühlen und mit einem Lappen geschützt öffnen. Nachgefüllt wird langsam und nur bei nicht mehr heißem Motor.",
  }),
  q({
    code: "own-unfall_panne-021", topic: "unfall_panne", points: 3, difficulty: 0.55, tags: ["erste_hilfe", "wiederbelebung", "herzdruckmassage"], kind: "numeric", numericAnswer: 30, tolerance: 0, unit: "Kompressionen",
    text: "Bei der Wiederbelebung eines Erwachsenen wechseln Sie zwischen Herzdruckmassage und Beatmung. Wie viele Kompressionen folgen auf jeweils zwei Beatmungen?",
    answers: [],
    explanation: "Die Wiederbelebung erfolgt im Rhythmus 30 zu 2: dreißig Kompressionen in der Brustmitte, dann zwei Beatmungen. Wer nicht beatmen kann oder will, führt die Herzdruckmassage ohne Unterbrechung fort. Die Frequenz liegt bei 100 bis 120 Kompressionen pro Minute.",
  }),
  q({
    code: "own-unfall_panne-022", topic: "unfall_panne", points: 3, difficulty: 0.6, tags: ["erste_hilfe", "wiederbelebung", "aed"],
    text: "Eine verunglückte Person reagiert nicht und atmet nicht normal. Was ist richtig?",
    answers: [t("Notruf absetzen und sofort mit der Herzdruckmassage beginnen"), t("Einen automatisierten externen Defibrillator (AED) einsetzen, sobald er verfügbar ist, und den Sprachanweisungen folgen"), t("Die Herzdruckmassage bis zum Eintreffen des Rettungsdienstes nicht unterbrechen, außer der AED verlangt es"), f("Zuerst die stabile Seitenlage herstellen und dann die Atmung beobachten", "Die stabile Seitenlage ist nur bei normaler Atmung richtig.")],
    explanation: "Fehlt die normale Atmung, zählt jede Sekunde: Notruf, Herzdruckmassage in der Brustmitte, wenn möglich Beatmung, und Einsatz eines AED. Schnappatmung ist keine normale Atmung. Die Maßnahmen werden bis zur Übernahme durch den Rettungsdienst fortgesetzt.",
  }),
  q({
    code: "own-unfall_panne-023", topic: "unfall_panne", points: 3, difficulty: 0.6, tags: ["erste_hilfe", "blutung", "druckverband"],
    text: "Eine Person hat eine stark blutende Wunde am Unterarm. Was ist richtig?",
    answers: [t("Einmalhandschuhe anziehen, den Arm hochhalten und einen Druckverband anlegen"), t("Die Person hinlegen und Beine leicht erhöht lagern, um einem Schock vorzubeugen"), f("Die Wunde mit Wasser auswaschen und desinfizieren", "Bei starker Blutung geht es zuerst um das Stillen der Blutung."), f("Den Arm mit einem Gürtel fest abbinden", "Abbinden schädigt Gewebe und ist nur im äußersten Notfall vorgesehen.")],
    explanation: "Starke Blutungen werden mit einem Druckverband gestillt: sterile Wundauflage, darüber ein Druckpolster, alles fest umwickeln. Handschuhe schützen vor Infektionen. Der Verletzte wird liegend betreut und zugedeckt, weil Blutverlust zum Schock führen kann.",
  }),
  q({
    code: "own-unfall_panne-024", topic: "unfall_panne", points: 3, difficulty: 0.6, tags: ["erste_hilfe", "schock"],
    text: "Eine Unfallbeteiligte ist blass, hat kalten Schweiß auf der Stirn, zittert und wirkt teilnahmslos. Woran denken Sie und was tun Sie?",
    answers: [t("Anzeichen eines Schocks: hinlegen, Beine erhöht lagern, zudecken und beruhigend ansprechen"), f("Anzeichen von Unterzuckerung: ein süßes Getränk geben", "Verletzten nichts zu essen oder zu trinken geben."), f("Erschöpfung: aufrecht hinsetzen und allein zur Ruhe kommen lassen", "Schockpatienten dürfen nicht allein gelassen werden und gehören in Schocklage.")],
    explanation: "Blasse, kalte Haut, Zittern, Unruhe oder Teilnahmslosigkeit sind Zeichen eines Schocks. In der Schocklage mit erhöhten Beinen fließt das Blut zu den lebenswichtigen Organen. Wärmeerhalt und Zuwendung sind wichtig; bei Bewusstlosigkeit gilt stattdessen die stabile Seitenlage.",
  }),
  q({
    code: "own-unfall_panne-025", topic: "unfall_panne", points: 4, difficulty: 0.7, tags: ["erste_hilfe", "rettungsgriff", "unfall", "hohes_risiko"],
    text: "Nach einem Unfall sitzt ein Verletzter benommen im Fahrzeug, aus dem Motorraum steigt Rauch auf. Was ist richtig?",
    answers: [t("Die Person wegen der akuten Gefahr mit dem Rettungsgriff aus dem Fahrzeug retten"), t("Zündung ausschalten, wenn dies gefahrlos möglich ist"), f("Die Person im Fahrzeug lassen, weil Verletzte niemals bewegt werden dürfen", "Bei akuter Gefahr wie Feuer geht die Rettung aus dem Gefahrenbereich vor."), f("Zuerst den Motorbrand mit Wasser löschen", "Ohne Feuerlöscher kein Löschversuch; zuerst Menschen retten.")],
    explanation: "Verletzte werden grundsätzlich nur bewegt, wenn eine akute Gefahr besteht, etwa durch Feuer, Rauch oder Verkehr. Dann kommt der Rettungsgriff zum Einsatz: von hinten unter den Achseln durchgreifen, einen Unterarm fassen und die Person rückwärts herausziehen. Eigenschutz beachten.",
  }),
  q({
    code: "own-unfall_panne-026", topic: "unfall_panne", points: 3, difficulty: 0.55, tags: ["erste_hilfe", "wirbelsaeule", "bewusstsein"],
    text: "Ein Motorradfahrer liegt nach einem Sturz auf dem Rücken, ist ansprechbar und klagt über Schmerzen im Nacken. Was ist richtig?",
    answers: [t("Die Person möglichst nicht bewegen, beruhigen, zudecken und den Notruf absetzen"), t("Den Helm aufgesetzt lassen, weil die Person bei Bewusstsein ist und normal atmet"), f("Die Person aufsetzen, damit sie besser atmen kann", "Bei Verdacht auf Wirbelsäulenverletzung wird die Lage nicht verändert."), f("Den Helm sofort abnehmen", "Bei ansprechbaren Verletzten bleibt der Helm auf; abgenommen wird er nur bei Bewusstlosigkeit.")],
    explanation: "Bei Verdacht auf eine Wirbelsäulenverletzung wird der Verletzte nur bewegt, wenn Lebensgefahr besteht. Der Helm wird bei ansprechbaren Personen mit normaler Atmung belassen. Wärmeerhalt, Zuwendung und der Notruf sind die wichtigsten Maßnahmen.",
  }),
  q({
    code: "own-unfall_panne-027", topic: "unfall_panne", points: 3, difficulty: 0.55, tags: ["erste_hilfe", "verbrennung"],
    text: "Bei einem Unfall hat sich eine Person am Unterarm eine kleinflächige Verbrennung zugezogen. Was ist richtig?",
    answers: [t("Die betroffene Stelle mit handwarmem Wasser kühlen und danach keimfrei abdecken"), f("Brandblasen öffnen, damit die Flüssigkeit abfließen kann", "Blasen schützen die Wunde vor Infektionen und bleiben geschlossen."), f("Mehl, Öl oder Salbe auftragen", "Hausmittel verunreinigen die Wunde und erschweren die Behandlung.")],
    explanation: "Kleinflächige Verbrennungen werden kurz mit handwarmem Wasser gekühlt, um den Schmerz zu lindern, und anschließend keimfrei abgedeckt. Große Flächen werden nicht gekühlt, weil Unterkühlung droht. Kleidung, die mit der Haut verklebt ist, bleibt an Ort und Stelle.",
  }),
  q({
    code: "own-unfall_panne-028", topic: "unfall_panne", points: 3, difficulty: 0.6, tags: ["notruf", "ecall", "notrufsaeule"],
    text: "Welche Aussagen zum Notruf treffen zu?",
    answers: [t("Die 112 ist in allen EU-Staaten die Notrufnummer und vom Mobiltelefon kostenlos erreichbar"), t("Über die Notrufsäule an der Autobahn wird Ihr Standort der Leitstelle automatisch übermittelt"), t("Neue Pkw haben ein eCall-System, das nach einem schweren Unfall automatisch einen Notruf mit Position absetzt"), f("Die 110 ist ausschließlich für Verkehrsunfälle vorgesehen", "Die 110 ist der Polizeinotruf; bei Verletzten wählen Sie die 112.")],
    explanation: "Die 112 erreicht europaweit Feuerwehr und Rettungsdienst. Notrufsäulen übermitteln den Standort automatisch, was auf der Autobahn wertvolle Zeit spart. Seit 2018 müssen neue Pkw-Typen mit eCall ausgerüstet sein, das bei einem schweren Aufprall selbsttätig die 112 anruft und die Position übermittelt.",
  }),
  q({
    code: "own-unfall_panne-029", topic: "unfall_panne", points: 3, difficulty: 0.6, tags: ["panne", "ausserorts", "kurve", "warndreieck", "dunkelheit"],
    text: "Ihr Fahrzeug bleibt nachts auf einer Landstraße kurz hinter einer unübersichtlichen Kurve liegen. Was ist richtig?",
    answers: [t("Warnblinklicht einschalten und das Warndreieck vor der Kurve aufstellen, sodass es rechtzeitig zu sehen ist"), t("Warnweste anlegen, bevor Sie das Fahrzeug verlassen, und das Warndreieck aufgeklappt vor dem Körper tragen"), t("Mitfahrende hinter die Leitplanke oder außerhalb der Fahrbahn in Sicherheit bringen"), f("Das Warndreieck genau 100 Meter hinter dem Fahrzeug aufstellen, auch wenn es dann in der Kurve steht", "Das Dreieck muss vor der Kurve stehen, damit es rechtzeitig sichtbar ist; die 100 Meter sind nur eine Faustregel.")],
    explanation: "Das Warndreieck muss in ausreichender Entfernung stehen, damit der nachfolgende Verkehr rechtzeitig gewarnt wird. Vor Kurven und Kuppen bedeutet das: vor der Sichtbehinderung, nicht dahinter. Warnweste anlegen und das Dreieck sichtbar vor dem Körper tragen, damit man selbst gesehen wird.",
    legalReference: "§ 15 StVO",
  }),
  q({
    code: "own-unfall_panne-030", topic: "unfall_panne", points: 3, difficulty: 0.6, tags: ["panne", "autobahn", "notrufsaeule", "absichern"],
    text: "Auf der Autobahn bleibt Ihr Fahrzeug mit Motorschaden liegen. In welcher Reihenfolge handeln Sie richtig?",
    answers: [t("Warnblinklicht einschalten, auf den Seitenstreifen rollen, Warnweste anlegen, Warndreieck aufstellen, hinter die Schutzplanke gehen, Hilfe rufen"), f("Hilfe rufen, dann Warndreieck aufstellen und im Fahrzeug warten", "Erst sichern, dann Hilfe rufen; im Fahrzeug auf dem Seitenstreifen ist es lebensgefährlich."), f("Warndreieck aufstellen, danach Warnweste anlegen und das Fahrzeug auf den Seitenstreifen schieben", "Die Warnweste wird vor dem Aussteigen angelegt; erst das Fahrzeug aus dem Verkehr bringen.")],
    explanation: "Zuerst den Verkehr mit dem Warnblinklicht warnen und das Fahrzeug so weit wie möglich rechts auf den Seitenstreifen bringen. Dann Warnweste anlegen, das Warndreieck in ausreichender Entfernung aufstellen, alle Personen hinter die Schutzplanke bringen und Hilfe über Notrufsäule oder 112 anfordern.",
    legalReference: "§ 15 StVO; § 53a StVZO",
  }),
  q({
    code: "own-unfall_panne-031", topic: "unfall_panne", points: 3, difficulty: 0.55, tags: ["warnweste", "ausruestung", "norm"],
    text: "Welche Anforderungen gelten für die im Pkw mitzuführende Warnweste?",
    answers: [t("Sie muss der Norm EN ISO 20471 oder EN 471 entsprechen und rot, gelb oder orange sein"), t("Sie sollte im Fahrgastraum griffbereit liegen, nicht im Kofferraum"), f("Es genügt jede reflektierende Jacke", "Nur genormte Warnwesten erfüllen die Vorschrift."), f("Vorgeschrieben ist eine Weste je Sitzplatz", "Vorgeschrieben ist mindestens eine Weste; mehr sind empfehlenswert.")],
    explanation: "In Pkw ist mindestens eine Warnweste mitzuführen, die der Norm EN ISO 20471 oder EN 471 entspricht und in den Farben rot, gelb oder orange fluoresziert. Sie sollte vor dem Aussteigen angelegt werden, deshalb gehört sie in Reichweite des Fahrers.",
    legalReference: "§ 53a Abs. 2 StVZO",
  }),
  q({
    code: "own-unfall_panne-032", topic: "unfall_panne", points: 3, difficulty: 0.55, tags: ["verbandkasten", "ausruestung", "norm"],
    text: "Was gilt für den Verbandkasten im Pkw?",
    answers: [t("Er muss der Norm DIN 13164 entsprechen und vollständig sein"), t("Abgelaufene sterile Bestandteile müssen ersetzt werden"), f("Er darf durch eine Hausapotheke ersetzt werden", "Vorgeschrieben ist Erste-Hilfe-Material nach DIN 13164."), f("Er ist in Pkw nur empfohlen, nicht vorgeschrieben", "Erste-Hilfe-Material ist in Pkw vorgeschrieben.")],
    explanation: "Pkw müssen Erste-Hilfe-Material nach DIN 13164 mitführen. Der Kasten muss vollständig und die sterilen Teile innerhalb ihres Haltbarkeitsdatums sein. Ein fehlender oder unvollständiger Verbandkasten ist eine Ordnungswidrigkeit.",
    legalReference: "§ 35h StVZO",
  }),
  q({
    code: "own-unfall_panne-033", topic: "unfall_panne", points: 3, difficulty: 0.6, tags: ["unfall", "unfallbericht", "versicherung", "schuldanerkenntnis"],
    text: "Nach einem Unfall mit Sachschaden verlangt der andere Beteiligte, dass Sie ein Schuldanerkenntnis unterschreiben. Was ist richtig?",
    answers: [t("Kein Schuldanerkenntnis unterschreiben; den Hergang mit dem Europäischen Unfallbericht dokumentieren und die Versicherung informieren"), t("Fotos, Skizze und Zeugen sichern"), f("Ein Schuldanerkenntnis beschleunigt die Regulierung und ist unproblematisch", "Ein Anerkenntnis kann den Versicherungsschutz gefährden und die Schuldfrage vorwegnehmen."), f("Ohne Polizei darf der Unfall nicht gemeldet werden", "Bei reinem Sachschaden ist die Polizei nicht zwingend erforderlich.")],
    explanation: "Die Schuldfrage klären die Versicherungen anhand der Fakten. Ein vorschnelles Schuldanerkenntnis kann Nachteile bringen. Der Europäische Unfallbericht hält den Hergang neutral fest; Fotos und Zeugen belegen die Angaben. Der eigene Versicherer ist zeitnah zu informieren.",
  }),
  q({
    code: "own-unfall_panne-034", topic: "unfall_panne", points: 3, difficulty: 0.55, tags: ["unfall", "zeuge", "hilfeleistung", "absichern"],
    text: "Sie kommen als unbeteiligter Fahrer an eine Unfallstelle, an der bereits mehrere Helfer sind. Was ist richtig?",
    answers: [t("Langsam und mit Abstand vorbeifahren, wenn Ihre Hilfe nicht mehr benötigt wird, und den Verkehr nicht durch Anhalten und Gaffen behindern"), t("Wenn Sie anhalten, das eigene Fahrzeug so abstellen, dass Rettungsfahrzeuge nicht behindert werden"), f("Fotos von den Verletzten machen, um sie als Beweismittel weiterzugeben", "Das Fotografieren von Verletzten ist verboten und strafbar."), f("Auf der Autobahn zum Helfen auf dem linken Fahrstreifen anhalten", "Auf der Autobahn wird nur auf dem Seitenstreifen angehalten.")],
    explanation: "Wenn ausreichend Helfer vor Ort sind, ist die beste Hilfe, die Unfallstelle nicht zusätzlich zu blockieren. Wer hilft, sichert zuerst sich selbst und stellt das Fahrzeug so ab, dass Rettungskräfte durchkommen. Das Fotografieren Verunglückter verletzt deren Persönlichkeitsrechte und ist strafbar.",
    legalReference: "§ 201a StGB; § 323c StGB",
  }),
  q({
    code: "own-unfall_panne-035", topic: "unfall_panne", points: 3, difficulty: 0.6, tags: ["unfall", "airbag", "gurt", "technik"],
    text: "Nach einem Auffahrunfall haben die Airbags ausgelöst. Was ist zu beachten?",
    answers: [t("Das Fahrzeug nach Möglichkeit nicht mehr im Verkehr benutzen, weil Rückhaltesysteme und Sicherheitsstruktur beschädigt sein können"), t("Ausgelöste Gurtstraffer und Airbags müssen in der Werkstatt ersetzt werden"), f("Die Airbags lassen sich zusammenfalten und wiederverwenden", "Ausgelöste Airbags sind verbraucht und müssen ersetzt werden."), f("Nach dem Auslösen ist der Motor automatisch zerstört", "Der Motor ist vom Airbagsystem unabhängig.")],
    explanation: "Airbags und Gurtstraffer sind Einwegsysteme. Nach dem Auslösen ist der Insassenschutz nicht mehr gegeben, und die Karosserie kann verformt sein. Das Fahrzeug sollte abgeschleppt und in einer Fachwerkstatt instand gesetzt werden.",
  }),
  q({
    code: "own-unfall_panne-036", topic: "unfall_panne", points: 3, difficulty: 0.65, tags: ["unfall", "elektrofahrzeug", "hochvolt", "brand"],
    text: "Ein verunfalltes Elektroauto steht mit beschädigter Batterie am Straßenrand. Worauf müssen Sie als Ersthelfer achten?",
    answers: [t("Abstand zu beschädigten orangefarbenen Hochvoltleitungen halten und diese nicht berühren"), t("Auf Rauch, Zischen oder Geruch achten, die auf einen beginnenden Batteriebrand hinweisen, und Einsatzkräfte über den Elektroantrieb informieren"), t("Verletzte wie bei jedem Unfall versorgen, wenn keine akute Gefahr durch Strom oder Feuer besteht"), f("Das Fahrzeug an der Karosserie berühren ist immer lebensgefährlich, deshalb keinesfalls Hilfe leisten", "Die Hochvoltanlage ist isoliert; bei intakter Karosserie ist Hilfe möglich. Nur beschädigte orangefarbene Leitungen sind gefährlich.")],
    explanation: "Hochvoltleitungen sind orange gekennzeichnet und dürfen bei Beschädigung nicht berührt werden. Ein Batteriebrand kann verzögert beginnen; Rauch oder Geräusche sind Warnzeichen. Ersthelfer versorgen Verletzte wie sonst auch, halten aber Abstand zu beschädigten Bauteilen und melden den Antrieb beim Notruf.",
  }),
  q({
    code: "own-unfall_panne-037", topic: "unfall_panne", points: 2, difficulty: 0.45, tags: ["erste_hilfe", "kurs", "fahrerlaubnis"], kind: "numeric", numericAnswer: 9, tolerance: 0, unit: "Unterrichtseinheiten",
    text: "Wie viele Unterrichtseinheiten umfasst der für den Führerscheinerwerb vorgeschriebene Erste-Hilfe-Kurs?",
    answers: [],
    explanation: "Für die Erteilung der Fahrerlaubnis ist die Teilnahme an einem Erste-Hilfe-Kurs mit neun Unterrichtseinheiten nachzuweisen. Der Kurs vermittelt unter anderem Absichern, Notruf, stabile Seitenlage und Wiederbelebung.",
    legalReference: "§ 19 FeV",
  }),
  q({
    code: "own-unfall_panne-038", topic: "unfall_panne", points: 2, difficulty: 0.4, tags: ["panne", "pannenbucht", "zeichen_328"],
    text: "Wofür ist eine Nothalte- und Pannenbucht (Zeichen 328) bestimmt?",
    answers: [t("Nur für das Halten in Notfällen und bei Pannen"), f("Für kurze Pausen und Telefonate", "Die Bucht ist ausschließlich für Not- und Pannenhalte vorgesehen."), f("Zum Wenden auf Autobahnen", "Wenden ist auf Autobahnen verboten.")],
    explanation: "Nothalte- und Pannenbuchten dürfen nur bei einer Panne oder in einem Notfall benutzt werden. Wer dort ohne Not hält, blockiert die Bucht für Fahrzeuge, die sie wirklich brauchen.",
    legalReference: "Anlage 3 StVO, Zeichen 328",
  }),
  q({
    code: "own-unfall_panne-039", topic: "unfall_panne", points: 2, difficulty: 0.4, tags: ["erste_hilfe", "betreuung", "psychische_hilfe"],
    text: "Ein leicht verletzter Unfallbeteiligter steht unter Schock und ist verwirrt. Was gehört zur Ersten Hilfe?",
    answers: [t("Bei der Person bleiben, sie ansprechen, beruhigen und vor Kälte schützen"), t("Sie nicht allein umherlaufen lassen, weil sie in den Verkehr geraten könnte"), f("Sie zur Beruhigung eine Zigarette rauchen oder Alkohol trinken lassen", "Alkohol und Nikotin verschlechtern den Zustand; Verletzten nichts geben."), f("Sie sich selbst überlassen, weil sie nur leicht verletzt ist", "Auch leicht Verletzte brauchen Betreuung.")],
    explanation: "Zur Ersten Hilfe gehört auch die seelische Betreuung: ansprechen, Blickkontakt halten, zudecken und nicht allein lassen. Verwirrte Personen können sich selbst gefährden, etwa indem sie auf die Fahrbahn laufen.",
  }),
  q({
    code: "own-unfall_panne-040", topic: "unfall_panne", points: 2, difficulty: 0.35, tags: ["panne", "warnblinklicht", "absichern"],
    text: "Wann müssen Sie bei einem liegen gebliebenen Fahrzeug das Warnblinklicht einschalten?",
    answers: [t("Sobald das Fahrzeug an einer Stelle steht, an der es nicht rechtzeitig als stehendes Hindernis erkannt werden kann"), f("Nur bei Dunkelheit", "Die Pflicht gilt unabhängig von der Tageszeit, wenn das Fahrzeug nicht rechtzeitig erkennbar ist."), f("Nur auf der Autobahn", "Sie gilt auf allen Straßen.")],
    explanation: "Bleibt ein mehrspuriges Fahrzeug an einer Stelle liegen, an der es nicht rechtzeitig als Hindernis erkannt werden kann, ist sofort das Warnblinklicht einzuschalten. Zusätzlich muss mindestens ein Warndreieck in ausreichender Entfernung aufgestellt werden.",
    legalReference: "§ 15 Abs. 1 StVO",
  }),
  q({
    code: "own-unfall_panne-041", topic: "unfall_panne", points: 2, difficulty: 0.4, tags: ["unfall", "personalien", "pflichten"],
    text: "Welche Angaben müssen Sie einem anderen Unfallbeteiligten auf Verlangen machen?",
    answers: [t("Name und Anschrift sowie Angaben zur Beteiligung am Unfall"), t("Kennzeichen des Fahrzeugs und auf Verlangen Führerschein und Fahrzeugpapiere vorzeigen"), f("Die eigene Steuernummer", "Die Steuernummer ist für die Unfallabwicklung ohne Bedeutung."), f("Keine Angaben, solange die Polizei nicht da ist", "Beteiligte müssen anderen Beteiligten Personalien und Versicherungsangaben ermöglichen.")],
    explanation: "Unfallbeteiligte müssen den anderen Beteiligten und Geschädigten auf Verlangen Name und Anschrift nennen, mitteilen, dass sie beteiligt sind, sowie Führerschein und Fahrzeugschein vorzeigen. Angaben zum Haftpflichtversicherer ermöglichen die Schadenregulierung.",
    legalReference: "§ 34 Abs. 1 StVO",
  }),
];
