// Übungsfragen zum Thema "verkehrsregelung" (eigene Formulierungen, kein amtlicher Prüfungsinhalt).
import type { Question } from "../types";
import { q, t, f } from "./_helpers";

export const verkehrsregelung: readonly Question[] = [
  q({
    code: "own-verkehrsregelung-001", topic: "verkehrsregelung", points: 3, difficulty: 0.3, tags: ["ampel", "gelb", "halten"],
    text: "Die Ampel schaltet auf Gelb, während Sie sich der Kreuzung nähern. Was ist richtig?",
    answers: [t("Vor der Kreuzung anhalten, wenn das noch gefahrlos möglich ist"), f("Beschleunigen, um die Kreuzung noch bei Gelb zu passieren", "Gelb bedeutet warten, nicht beschleunigen."), f("Nur bei Rot anhalten, Gelb kann ignoriert werden", "Gelb verlangt bereits das Anhalten vor der Kreuzung.")],
    explanation: "Gelb bedeutet: Vor der Kreuzung auf das nächste Zeichen warten. Nur wer so nah ist, dass ein gefahrloses Anhalten nicht mehr möglich wäre, darf noch weiterfahren.",
    legalReference: "§ 37 Abs. 2 StVO",
  }),
  q({
    code: "own-verkehrsregelung-002", topic: "verkehrsregelung", points: 2, difficulty: 0.2, tags: ["ampel", "rot_gelb"],
    text: "Was bedeutet Rot und Gelb gleichzeitig an einer Ampel?",
    answers: [t("Fahrbereit machen, aber noch nicht anfahren; es folgt Grün"), f("Sofort anfahren", "Gefahren werden darf erst bei Grün."), f("Die Ampel ist außer Betrieb", "Rot-Gelb ist eine reguläre Phase.")],
    explanation: "Rot und Gelb zusammen kündigen das Grünlicht an. Man macht sich zum Anfahren bereit, fährt aber erst bei Grün los.",
    legalReference: "§ 37 Abs. 2 StVO",
  }),
  q({
    code: "own-verkehrsregelung-003", topic: "verkehrsregelung", points: 4, difficulty: 0.4, tags: ["gruenpfeil", "rechtsabbiegen", "halten"],
    text: "An einer roten Ampel ist ein Schild mit grünem Pfeil (Grünpfeilschild, Zeichen 720) angebracht. Was gilt für das Rechtsabbiegen?",
    answers: [t("Erst an der Haltlinie anhalten, dann rechts abbiegen, wenn niemand behindert oder gefährdet wird"), f("Sie dürfen ohne Anhalten rechts abbiegen wie bei Grün", "Vor dem Abbiegen muss immer angehalten werden."), f("Der Pfeil gilt nur für Radfahrer", "Das Zeichen 720 gilt für alle Fahrzeuge; für Radfahrer gibt es ein eigenes Zeichen 721.")],
    explanation: "Das Grünpfeilschild erlaubt das Rechtsabbiegen bei Rot, aber nur nach vollständigem Anhalten an der Haltlinie und nur, wenn weder Fußgänger noch der freigegebene Verkehr behindert oder gefährdet werden.",
    legalReference: "§ 37 Abs. 2 Nr. 1 StVO",
  }),
  q({
    code: "own-verkehrsregelung-004", topic: "verkehrsregelung", points: 3, difficulty: 0.4, tags: ["gruener_pfeil", "lichtzeichen"],
    text: "Die Ampel zeigt einen grün leuchtenden Pfeil nach links. Was bedeutet das?",
    answers: [t("Sie dürfen nach links abbiegen; der kreuzende Verkehr und der Gegenverkehr haben in dieser Phase Rot"), f("Sie müssen zunächst anhalten und den Gegenverkehr durchlassen", "Das ist die Regel beim Grünpfeilschild, nicht beim leuchtenden Pfeil."), f("Sie dürfen in alle Richtungen fahren", "Der Pfeil gibt nur die angezeigte Richtung frei.")],
    explanation: "Ein grün leuchtender Pfeil gibt ausschließlich die angezeigte Richtung frei. Der Verkehr, der diese Richtung kreuzen würde, wird in dieser Phase angehalten; trotzdem bleibt aufmerksames Fahren Pflicht.",
    legalReference: "§ 37 Abs. 2 StVO",
  }),
  q({
    code: "own-verkehrsregelung-005", topic: "verkehrsregelung", points: 3, difficulty: 0.4, tags: ["polizei", "handzeichen"],
    text: "Ein Polizeibeamter regelt den Verkehr. Ihnen ist seine Brust zugewandt, beide Arme sind seitlich ausgestreckt, also quer zu Ihrer Fahrtrichtung. Was bedeutet das für Sie?",
    answers: [t("Halt vor der Kreuzung, entsprechend Rot"), f("Freie Fahrt, entsprechend Grün", "Freie Fahrt gilt für den Verkehr, der in Richtung der ausgestreckten Arme fährt, also von der Seite kommt."), f("Achtung, die Regelung wird gewechselt", "Das entspricht dem hoch erhobenen Arm.")],
    explanation: "Seitlich ausgestreckte Arme quer zu Ihrer Fahrtrichtung bedeuten Halt wie Rot: Sie sehen Brust oder Rücken des Beamten. Wer in Richtung der Arme fährt, also den Beamten von der Seite sieht, hat freie Fahrt wie Grün. Ein hoch erhobener Arm bedeutet: Achtung, die Freigabe wechselt.",
    mnemonic: "Seite = Grün, Brust und Rücken = Rot, Arm hoch = Gelb.",
    legalReference: "§ 36 StVO",
  }),
  q({
    code: "own-verkehrsregelung-006", topic: "verkehrsregelung", points: 3, difficulty: 0.3, tags: ["rangfolge", "polizei", "lichtzeichen"],
    text: "In welcher Rangfolge gelten Verkehrsregelungen an einer Kreuzung?",
    answers: [t("Zeichen von Polizeibeamten vor Lichtzeichen, Lichtzeichen vor Verkehrszeichen, Verkehrszeichen vor der Grundregel rechts vor links"), f("Verkehrszeichen vor Lichtzeichen", "Lichtzeichen gehen den Verkehrszeichen vor."), f("Rechts vor links gilt immer, auch bei Ampeln", "Die Grundregel gilt nur, wenn keine andere Regelung besteht.")],
    explanation: "Weisungen der Polizei gehen allen anderen Regelungen vor. Danach folgen Lichtzeichen, dann Verkehrszeichen und zuletzt die allgemeine Regel rechts vor links.",
    legalReference: "§ 36, § 37 und § 8 StVO",
  }),
  q({
    code: "own-verkehrsregelung-007", topic: "verkehrsregelung", points: 3, difficulty: 0.3, tags: ["dauerlichtzeichen", "fahrstreifen", "autobahn"],
    text: "Über einem Fahrstreifen leuchtet ein rotes Kreuz (Dauerlichtzeichen). Was bedeutet das?",
    answers: [t("Der Fahrstreifen darf nicht benutzt werden"), f("Der Fahrstreifen darf nur mit Vorsicht benutzt werden", "Ein rotes Kreuz sperrt den Fahrstreifen vollständig."), f("Auf dem Fahrstreifen gilt ein Überholverbot", "Das Zeichen sperrt, es regelt nicht das Überholen.")],
    explanation: "Dauerlichtzeichen über Fahrstreifen sperren (rotes Kreuz) oder geben frei (grüner Pfeil nach unten). Ein gelb blinkender Schrägpfeil kündigt an, dass der Fahrstreifen gewechselt werden muss.",
    legalReference: "§ 37 Abs. 3 StVO",
  }),
  q({
    code: "own-verkehrsregelung-008", topic: "verkehrsregelung", points: 2, difficulty: 0.2, tags: ["blinklicht", "gelb"],
    text: "Was bedeutet ein gelbes Blinklicht, zum Beispiel an einer Baustelle?",
    answers: [t("Warnung vor einer Gefahr; es besteht keine Anhaltepflicht"), f("Anhalten und warten", "Anhaltepflicht besteht nur bei Rot."), f("Vorfahrt für den Baustellenverkehr", "Das Blinklicht regelt keine Vorfahrt.")],
    explanation: "Gelbes Blinklicht warnt vor Gefahren oder weist auf Hindernisse hin. Man muss die Geschwindigkeit anpassen und aufmerksam sein, aber nicht anhalten.",
    legalReference: "§ 38 Abs. 3 StVO",
  }),
  q({
    code: "own-verkehrsregelung-009", topic: "verkehrsregelung", points: 4, difficulty: 0.3, tags: ["bahnuebergang", "rotlicht", "halten"],
    text: "Am Bahnübergang leuchtet rotes Licht, die Schranke ist noch offen. Was gilt?",
    answers: [t("Anhalten und warten, bis das Rotlicht erlischt"), f("Schnell noch vor der Schranke hinüberfahren", "Rotes Licht bedeutet Halt, auch bei offener Schranke."), f("Langsam weiterfahren, wenn kein Zug zu sehen ist", "Züge nähern sich schnell und lautlos; Rot verpflichtet zum Anhalten.")],
    explanation: "Rotes Licht oder rotes Blinklicht am Bahnübergang bedeutet Halt, unabhängig von der Stellung der Schranke. Es darf erst weitergefahren werden, wenn das Licht erloschen und die Schranke offen ist.",
    legalReference: "§ 19 Abs. 2 StVO; § 37 Abs. 2 Nr. 3 StVO",
  }),
  q({
    code: "own-verkehrsregelung-010", topic: "verkehrsregelung", points: 3, difficulty: 0.3, tags: ["ampel", "fussgaenger", "gruen"],
    text: "Die Ampel schaltet für Sie auf Grün, aber ein Fußgänger befindet sich noch auf der Fahrbahn. Wie verhalten Sie sich?",
    answers: [t("Warten und den Fußgänger die Fahrbahn räumen lassen"), f("Anfahren, weil Sie Grün haben", "Grün gibt keine Erlaubnis, Fußgänger zu gefährden."), f("Hupen, damit der Fußgänger schneller geht", "Hupen ist hier weder erlaubt noch sinnvoll.")],
    explanation: "Wer bei Grün Fußgänger noch auf der Fahrbahn antrifft, muss sie zügig, aber ungefährdet die Fahrbahn räumen lassen. Grün bedeutet Freigabe, nicht Vorrang um jeden Preis.",
    legalReference: "§ 37 Abs. 2 StVO; § 1 StVO",
  }),
  q({
    code: "own-verkehrsregelung-011", topic: "verkehrsregelung", points: 4, difficulty: 0.65, tags: ["rangfolge", "polizei", "lichtzeichen", "handzeichen"],
    text: "Die Ampel zeigt für Sie Grün. Ein Polizeibeamter steht in der Kreuzung und Ihnen ist seine Brust zugewandt, die Arme sind seitlich ausgestreckt. Was gilt?",
    answers: [t("Sie müssen anhalten, weil die Zeichen des Polizeibeamten der Ampel vorgehen"), f("Sie dürfen fahren, weil die Ampel Grün zeigt", "Weisungen der Polizei gehen den Lichtzeichen vor."), f("Sie dürfen fahren, weil sich Polizeizeichen und Ampel widersprechen und dann die Ampel gilt", "Bei Widerspruch gilt immer das Zeichen des Polizeibeamten."), f("Sie dürfen langsam weiterfahren, wenn kein Querverkehr kommt", "Brust oder Rücken zugewandt bedeutet Halt, unabhängig vom Querverkehr.")],
    explanation: "Zeichen und Weisungen der Polizei gehen allen anderen Regelungen vor, auch einer grünen Ampel. Sehen Sie Brust oder Rücken des Beamten bei seitlich ausgestreckten Armen, bedeutet das Halt.",
    legalReference: "§ 36 Abs. 1 StVO",
  }),
  q({
    code: "own-verkehrsregelung-012", topic: "verkehrsregelung", points: 3, difficulty: 0.6, tags: ["polizei", "handzeichen", "arm_hoch"],
    text: "Ein Polizeibeamter regelt den Verkehr und hebt einen Arm hoch. Was bedeutet das?",
    answers: [t("Für Fahrzeuge vor der Kreuzung: Halt, auf das nächste Zeichen warten"), t("Für Fahrzeuge, die sich bereits in der Kreuzung befinden: Kreuzung räumen"), f("Freie Fahrt für alle Richtungen", "Der erhobene Arm entspricht Gelb, nicht Grün."), f("Nur der Verkehr von links darf fahren", "Der erhobene Arm gibt keine Richtung frei.")],
    explanation: "Der hoch erhobene Arm entspricht dem gelben Licht: Wer vor der Kreuzung ist, wartet auf das nächste Zeichen; wer bereits in der Kreuzung ist, räumt sie zügig. Danach folgt in der Regel der Wechsel der Freigabe.",
    mnemonic: "Arm hoch = Gelb.",
    legalReference: "§ 36 Abs. 2 StVO",
  }),
  q({
    code: "own-verkehrsregelung-013", topic: "verkehrsregelung", points: 4, difficulty: 0.7, tags: ["polizei", "handzeichen", "linksabbiegen", "gegenverkehr"],
    text: "Ein Polizeibeamter steht seitlich zu Ihnen mit seitlich ausgestreckten Armen. Sie wollen links abbiegen; aus der Gegenrichtung kommt ein Fahrzeug, das geradeaus fährt. Was gilt?",
    answers: [t("Sie haben freie Fahrt wie bei Grün, müssen aber als Linksabbieger den Gegenverkehr durchfahren lassen"), f("Sie dürfen vor dem Gegenverkehr abbiegen, weil der Beamte Ihnen freie Fahrt gibt", "Die Freigabe gilt für beide Richtungen; die Abbiegeregel bleibt bestehen."), f("Sie müssen warten, weil Linksabbiegen bei Polizeiregelung verboten ist", "Ein solches Verbot gibt es nicht.")],
    explanation: "Sieht man den Beamten von der Seite, hat man freie Fahrt wie bei Grün. Das gilt aber ebenso für den Gegenverkehr. Deshalb muss ein Linksabbieger den entgegenkommenden Geradeausverkehr wie bei einer grünen Ampel durchfahren lassen.",
    legalReference: "§ 36 Abs. 2 StVO; § 9 Abs. 3 StVO",
  }),
  q({
    code: "own-verkehrsregelung-014", topic: "verkehrsregelung", points: 3, difficulty: 0.6, tags: ["polizei", "anhalten", "weisung"],
    text: "Ein Polizeifahrzeug fährt vor Ihnen und zeigt im Heckfenster die Aufschrift „Bitte folgen“. Was müssen Sie tun?",
    answers: [t("Dem Polizeifahrzeug folgen, bis es anhält und Sie zum Halten aufgefordert werden"), f("Weiterfahren, weil Zeichen aus Fahrzeugen nicht verbindlich sind", "Auch Zeichen und Weisungen aus Polizeifahrzeugen sind zu befolgen."), f("Sofort auf der Fahrbahn anhalten", "Angehalten wird erst dort, wo es gefahrlos möglich ist und die Polizei es anordnet.")],
    explanation: "Polizeibeamte dürfen Verkehrsteilnehmer auch aus fahrenden Fahrzeugen heraus anhalten, zum Beispiel durch die Aufschrift „Bitte folgen“ oder einen Anhaltestab. Diesen Weisungen ist Folge zu leisten.",
    legalReference: "§ 36 Abs. 5 StVO",
  }),
  q({
    code: "own-verkehrsregelung-015", topic: "verkehrsregelung", points: 4, difficulty: 0.6, tags: ["ampel", "rot", "haltlinie", "halten"],
    text: "Die Ampel zeigt Rot. Wo müssen Sie anhalten?",
    answers: [t("An der Haltlinie, wenn eine vorhanden ist"), t("Ohne Haltlinie vor der Ampel an einer Stelle, von der Sie die Lichtzeichen noch sehen können"), f("Immer unmittelbar an der Ampel, auch wenn die Haltlinie weiter davor liegt", "Die Haltlinie ist maßgeblich; wer sie überfährt, begeht einen Rotlichtverstoß."), f("Unmittelbar vor der Fahrbahn der kreuzenden Straße, um die Ampelphase auszunutzen", "Fußgängerfurten und die Haltlinie dürfen nicht überfahren werden.")],
    explanation: "Bei Rot wird an der Haltlinie angehalten. Ist keine markiert, hält man vor der Ampel so, dass man sie noch sehen kann und weder Fußgängerfurten noch die Kreuzung blockiert.",
    legalReference: "§ 37 Abs. 2 StVO; Zeichen 294",
  }),
  q({
    code: "own-verkehrsregelung-016", topic: "verkehrsregelung", points: 3, difficulty: 0.65, tags: ["ampel", "rot", "rotlichtverstoss", "fahrverbot"], kind: "numeric", numericAnswer: 1, tolerance: 0, unit: "s",
    text: "Nach wie vielen Sekunden Rotlicht gilt das Überfahren der Haltlinie als qualifizierter Rotlichtverstoß, für den regelmäßig ein Fahrverbot verhängt wird? Angabe in Sekunden.",
    answers: [],
    explanation: "Zeigt die Ampel bereits länger als eine Sekunde Rot, liegt ein qualifizierter Rotlichtverstoß vor. Dafür sind ein hohes Bußgeld, zwei Punkte und in der Regel ein Monat Fahrverbot vorgesehen. Auch ein einfacher Rotlichtverstoß bringt Bußgeld und einen Punkt.",
    legalReference: "BKatV",
  }),
  q({
    code: "own-verkehrsregelung-017", topic: "verkehrsregelung", points: 4, difficulty: 0.65, tags: ["gruenpfeil", "rechtsabbiegen", "radverkehr", "fussgaenger"],
    text: "Sie stehen bei Rot vor einem Grünpfeilschild (Zeichen 720) und wollen rechts abbiegen. Von links kommt auf dem Radweg der Querstraße ein Radfahrer, für den die Ampel Grün zeigt. Was gilt?",
    answers: [t("Sie müssen zunächst an der Haltlinie anhalten"), t("Sie dürfen erst abbiegen, wenn Sie den Radfahrer und Fußgänger der freigegebenen Richtung weder behindern noch gefährden"), f("Der Radfahrer muss warten, weil Sie mit dem Grünpfeil abbiegen dürfen", "Der freigegebene Verkehr hat Vorrang; der Grünpfeil erlaubt nur ein Abbiegen ohne Behinderung anderer."), f("Sie dürfen ohne Anhalten abbiegen, wenn der Radfahrer noch weit entfernt ist", "Das Anhalten an der Haltlinie ist beim Grünpfeil immer Pflicht.")],
    explanation: "Beim Grünpfeilschild muss immer zuerst an der Haltlinie angehalten werden. Abgebogen wird nur, wenn der Verkehr der freigegebenen Richtung, einschließlich Radfahrenden und Fußgängern, weder behindert noch gefährdet wird.",
    legalReference: "§ 37 Abs. 2 Nr. 1 StVO",
  }),
  q({
    code: "own-verkehrsregelung-018", topic: "verkehrsregelung", points: 3, difficulty: 0.6, tags: ["gruenpfeil", "radverkehr", "zeichen_721"],
    text: "Ein Grünpfeilschild trägt zusätzlich ein Fahrradsymbol (Zeichen 721). Für wen gilt es?",
    answers: [t("Nur für den Radverkehr; Kraftfahrzeuge müssen bei Rot warten"), f("Für alle Fahrzeuge, das Fahrrad ist nur ein Hinweis", "Das Zeichen 721 gilt ausschließlich für Radfahrende."), f("Für Radfahrende und Fahrzeuge bis 3,5 t", "Kraftfahrzeuge sind nicht erfasst.")],
    explanation: "Zeichen 721 ist der Grünpfeil für den Radverkehr. Radfahrende dürfen nach Anhalten bei Rot rechts abbiegen, wenn sie niemanden behindern oder gefährden. Für Kraftfahrzeuge gilt weiterhin Rot.",
    legalReference: "§ 37 Abs. 2 Nr. 1 StVO; Zeichen 721",
  }),
  q({
    code: "own-verkehrsregelung-019", topic: "verkehrsregelung", points: 3, difficulty: 0.55, tags: ["gruener_pfeil", "lichtzeichen", "rechtsabbiegen", "fussgaenger"],
    text: "Die Ampel zeigt einen grünen Pfeil nach rechts (Pfeil im Lichtzeichen selbst). Was gilt?",
    answers: [t("Sie dürfen rechts abbiegen, ohne vorher anzuhalten"), t("Fußgänger und Radfahrende, die in der Zielstraße queren, müssen Sie trotzdem durchlassen, falls sie Grün haben"), f("Sie müssen wie beim Grünpfeilschild zuerst anhalten", "Die Anhaltepflicht gilt nur für das Schild neben der roten Ampel."), f("Sie dürfen auch geradeaus fahren", "Der Pfeil gibt nur die angezeigte Richtung frei.")],
    explanation: "Ein grün leuchtender Pfeil gibt die Richtung ohne Anhaltepflicht frei; der kreuzende Fahrzeugverkehr ist angehalten. Trotzdem gilt beim Abbiegen besondere Rücksicht auf Fußgänger und Radfahrende, sofern diese ebenfalls Grün haben.",
    legalReference: "§ 37 Abs. 2 StVO; § 9 Abs. 3 StVO",
  }),
  q({
    code: "own-verkehrsregelung-020", topic: "verkehrsregelung", points: 4, difficulty: 0.65, tags: ["ampel", "gruen", "linksabbiegen", "gegenverkehr", "kreuzung_raeumen"],
    text: "Sie sind bei Grün als Linksabbieger in die Kreuzung eingefahren und warten auf eine Lücke im Gegenverkehr. Die Ampel schaltet auf Gelb und dann auf Rot. Was ist richtig?",
    answers: [t("Sie müssen die Kreuzung räumen, sobald der Gegenverkehr anhält"), t("Das Abbiegen bei Rot ist in diesem Fall kein Rotlichtverstoß, weil Sie bei Grün eingefahren sind"), f("Sie müssen in der Kreuzung stehen bleiben, bis die Ampel wieder Grün zeigt", "Das würde den Querverkehr blockieren."), f("Sie müssen rückwärts hinter die Haltlinie zurücksetzen", "Rückwärtsfahren in der Kreuzung ist gefährlich und nicht vorgesehen.")],
    explanation: "Wer bei Grün eingefahren ist, darf und muss die Kreuzung beim Umschalten auf Rot räumen. Der Linksabbieger biegt ab, sobald der Gegenverkehr anhält. Der Querverkehr muss wartenden Fahrzeugen das Räumen ermöglichen.",
    legalReference: "§ 37 Abs. 2 StVO; § 11 Abs. 3 StVO",
  }),
  q({
    code: "own-verkehrsregelung-021", topic: "verkehrsregelung", points: 3, difficulty: 0.6, tags: ["ampel", "gelb", "anhalten", "reaktionsweg"],
    text: "Sie fahren innerorts 50 km/h und sind noch etwa 10 Meter von der Haltlinie entfernt, als die Ampel auf Gelb springt. Was ist richtig?",
    answers: [t("Sie dürfen weiterfahren, weil ein gefahrloses Anhalten auf dieser Strecke nicht mehr möglich ist"), f("Sie müssen eine Gefahrenbremsung machen, um vor der Haltlinie zu stehen", "Der Anhalteweg bei 50 km/h liegt weit über 10 Metern; eine Vollbremsung gefährdet den nachfolgenden Verkehr."), f("Sie müssen die Kreuzung mit erhöhter Geschwindigkeit räumen", "Beschleunigen ist bei Gelb nicht erlaubt; es wird mit unveränderter Geschwindigkeit weitergefahren.")],
    explanation: "Gelb bedeutet warten, aber nur, wenn das Anhalten noch gefahrlos möglich ist. Bei 50 km/h beträgt allein der Reaktionsweg 15 Meter; 10 Meter vor der Haltlinie ist ein sicheres Anhalten nicht mehr möglich, also darf weitergefahren werden.",
    legalReference: "§ 37 Abs. 2 StVO",
  }),
  q({
    code: "own-verkehrsregelung-022", topic: "verkehrsregelung", points: 4, difficulty: 0.7, tags: ["ampel", "stoppschild", "rangfolge", "vorfahrt_beschildert"],
    text: "An einer Kreuzung stehen für Sie sowohl eine Ampel als auch das Zeichen 206 (Stoppschild). Die Ampel zeigt Grün. Müssen Sie anhalten?",
    answers: [t("Nein, bei Grün dürfen Sie ohne Anhalten fahren, weil Lichtzeichen den Verkehrszeichen vorgehen"), t("Ist die Ampel ausgeschaltet oder blinkt sie gelb, gilt das Stoppschild mit Anhaltepflicht"), f("Ja, das Stoppschild verlangt immer ein Anhalten, auch bei Grün", "Solange die Ampel in Betrieb ist, hat sie Vorrang vor dem Verkehrszeichen."), f("Ja, aber nur wenn Querverkehr kommt", "Bei Grün ist der Querverkehr durch Rot angehalten.")],
    explanation: "Lichtzeichen gehen Vorschriftzeichen vor. Bei Grün darf ohne Anhalten gefahren werden. Fällt die Ampel aus oder blinkt sie gelb, gilt das Stoppschild und es muss angehalten und Vorfahrt gewährt werden.",
    legalReference: "§ 37 Abs. 1 StVO; Zeichen 206",
  }),
  q({
    code: "own-verkehrsregelung-023", topic: "verkehrsregelung", points: 3, difficulty: 0.55, tags: ["ampel", "rot_gelb", "anfahren"],
    text: "Die Ampel zeigt Rot und Gelb gleichzeitig. Das Fahrzeug hinter Ihnen hupt. Dürfen Sie schon losfahren?",
    answers: [t("Nein, Rot-Gelb bedeutet weiterhin Halt; gefahren wird erst bei Grün"), f("Ja, Rot-Gelb gibt die Fahrt frei", "Rot-Gelb kündigt Grün nur an."), f("Ja, wenn die Kreuzung frei ist", "Auch bei freier Kreuzung darf erst bei Grün angefahren werden.")],
    explanation: "Rot und Gelb zusammen bedeuten: Halt, aber Grün folgt. Man macht sich fahrbereit, fährt jedoch erst bei Grün an. Das Hupen anderer ändert daran nichts.",
    legalReference: "§ 37 Abs. 2 Nr. 1 StVO",
  }),
  q({
    code: "own-verkehrsregelung-024", topic: "verkehrsregelung", points: 3, difficulty: 0.65, tags: ["ampel", "fahrstreifen", "pfeilsignale", "linksabbiegen"],
    text: "An einer Kreuzung gibt es für jeden Fahrstreifen eine eigene Ampel mit Pfeilen. Die Ampel für Geradeaus zeigt Grün, die für Linksabbieger Rot. Sie stehen auf dem Linksabbiegerstreifen. Was gilt?",
    answers: [t("Sie müssen warten, weil für Ihren Fahrstreifen Rot gilt"), f("Sie dürfen fahren, weil die Kreuzung für Ihre Fahrtrichtung insgesamt freigegeben ist", "Bei Pfeilsignalen gilt für jeden Fahrstreifen nur die eigene Ampel."), f("Sie dürfen auf den Geradeausstreifen wechseln und dann links abbiegen", "Von einem Geradeausstreifen darf nicht links abgebogen werden; außerdem ist der Wechsel im Kreuzungsbereich gefährlich.")],
    explanation: "Sind Lichtzeichen mit Pfeilen für einzelne Fahrstreifen angebracht, gilt jedes Zeichen nur für den zugeordneten Fahrstreifen. Auf dem Linksabbiegerstreifen ist bei Rot zu warten, auch wenn der Geradeausverkehr Grün hat.",
    legalReference: "§ 37 Abs. 2 StVO",
  }),
  q({
    code: "own-verkehrsregelung-025", topic: "verkehrsregelung", points: 3, difficulty: 0.6, tags: ["ampel", "gruen", "fussgaenger", "rechtsabbiegen"],
    text: "Sie haben Grün und wollen rechts abbiegen. Fußgänger überqueren mit Grün die Straße, in die Sie einbiegen. Was gilt?",
    answers: [t("Die Fußgänger haben Vorrang; Sie müssen sie durchlassen und nötigenfalls warten"), t("Sie dürfen bis zur Fußgängerfurt vorfahren, sofern Sie niemanden behindern oder gefährden"), f("Sie haben Vorrang, weil Sie Grün haben", "Fußgänger und Abbieger können gleichzeitig Grün haben; der Abbieger muss Rücksicht nehmen."), f("Sie dürfen hupen, um die Fußgänger zum Warten zu bewegen", "Hupen ist hier nicht zulässig.")],
    explanation: "Beim Abbiegen müssen Fußgänger, die die Straße überqueren, durchgelassen werden, auch wenn beide Grün haben. Der Abbieger muss auf sie besondere Rücksicht nehmen und wenn nötig warten.",
    legalReference: "§ 9 Abs. 3 StVO; § 37 Abs. 2 StVO",
  }),
  q({
    code: "own-verkehrsregelung-026", topic: "verkehrsregelung", points: 3, difficulty: 0.6, tags: ["dauerlichtzeichen", "fahrstreifen", "gelber_pfeil", "autobahn"],
    text: "Über Ihrem Fahrstreifen blinkt ein gelber Pfeil, der schräg nach rechts unten zeigt. Was bedeutet das?",
    answers: [t("Sie müssen den Fahrstreifen in Pfeilrichtung, also nach rechts, wechseln"), f("Sie dürfen den Fahrstreifen weiter benutzen, aber nur mit Vorsicht", "Der gelbe Blinkpfeil kündigt die Sperrung des Fahrstreifens an."), f("Der rechte Fahrstreifen ist gesperrt", "Gesperrt wird der eigene Fahrstreifen; der Pfeil zeigt die Ausweichrichtung.")],
    explanation: "Ein gelb blinkender, schräg nach unten zeigender Pfeil über dem Fahrstreifen kündigt an, dass der Fahrstreifen gesperrt wird. Er ist in Pfeilrichtung zu verlassen. Ein rotes Kreuz sperrt, ein grüner Pfeil gibt frei.",
    legalReference: "§ 37 Abs. 3 StVO",
  }),
  q({
    code: "own-verkehrsregelung-027", topic: "verkehrsregelung", points: 3, difficulty: 0.65, tags: ["dauerlichtzeichen", "wechselverkehrszeichen", "autobahn", "geschwindigkeit"],
    text: "Auf einer Schilderbrücke über der Autobahn leuchtet ein Wechselverkehrszeichen mit der Zahl 80 im roten Ring, obwohl am Fahrbahnrand kein Tempolimit-Schild steht. Was gilt?",
    answers: [t("Die angezeigten 80 km/h sind eine verbindliche Höchstgeschwindigkeit wie ein festes Verkehrszeichen"), f("Es handelt sich nur um eine Empfehlung", "Wechselverkehrszeichen haben dieselbe Wirkung wie fest aufgestellte Zeichen."), f("Es gilt nur für Lkw", "Ohne Einschränkung gilt das Zeichen für alle Fahrzeuge.")],
    explanation: "Wechselverkehrszeichen auf Schilderbrücken und Anzeigetafeln sind Verkehrszeichen mit voller Verbindlichkeit. Sie dienen der Verkehrsbeeinflussung bei Stau, Nässe oder Unfällen und ändern sich mit der Lage.",
    legalReference: "§ 39 Abs. 1 StVO; § 41 StVO",
  }),
  q({
    code: "own-verkehrsregelung-028", topic: "verkehrsregelung", points: 4, difficulty: 0.6, tags: ["bahnuebergang", "gelblicht", "rotlicht", "halten"],
    text: "Am Bahnübergang schaltet das Lichtzeichen von Gelb auf Rot, während Sie sich nähern. Die Halbschranke beginnt sich zu senken. Was ist richtig?",
    answers: [t("Anhalten und warten, bis das Rotlicht erlischt und die Schranke wieder offen ist"), t("Gelb bedeutet bereits: Vor dem Andreaskreuz anhalten, wenn es gefahrlos möglich ist"), f("Schnell noch hinüberfahren, bevor die Schranke unten ist", "Das ist lebensgefährlich und ein schwerer Verstoß."), f("Um die halbe Schranke herumfahren, wenn kein Zug zu sehen ist", "Das Umfahren geschlossener Halbschranken ist verboten.")],
    explanation: "Am Bahnübergang bedeutet Gelb wie an der Ampel: anhalten, wenn möglich. Bei Rot ist das Warten Pflicht, unabhängig von der Schrankenstellung. Halbschranken dürfen nicht umfahren werden.",
    legalReference: "§ 19 Abs. 2 StVO; § 37 Abs. 2 StVO",
  }),
  q({
    code: "own-verkehrsregelung-029", topic: "verkehrsregelung", points: 3, difficulty: 0.65, tags: ["strassenbahn", "lichtzeichen", "sondersignale"],
    text: "An einer Kreuzung sehen Sie ein Lichtzeichen mit weißen Balken auf schwarzem Grund. Was bedeutet es für Sie als Autofahrer?",
    answers: [t("Nichts, diese Signale gelten nur für Straßenbahnen und Linienbusse"), f("Ein waagerechter Balken bedeutet für Sie Halt", "Die Balkensignale richten sich ausschließlich an Schienenfahrzeuge und Busse des Linienverkehrs."), f("Ein senkrechter Balken gibt Ihnen die Fahrt frei", "Für Sie gelten nur die farbigen Lichtzeichen.")],
    explanation: "Weiße Balkensignale sind Lichtzeichen für Straßenbahnen und Linienbusse. Für den übrigen Verkehr gelten nur die roten, gelben und grünen Lichtzeichen. Man sollte die Balkensignale aber kennen, um das Verhalten der Straßenbahn vorherzusehen.",
    legalReference: "§ 37 Abs. 2 StVO; § 51 BOStrab",
  }),
  q({
    code: "own-verkehrsregelung-030", topic: "verkehrsregelung", points: 3, difficulty: 0.6, tags: ["fussgaengerampel", "fussgaenger", "rot", "kreuzung_raeumen"],
    text: "Die Fußgängerampel schaltet auf Rot, während sich ein Fußgänger noch mitten auf der Fahrbahn befindet. Ihre Ampel zeigt Grün. Was gilt?",
    answers: [t("Der Fußgänger darf und muss die Überquerung zügig beenden; Sie müssen ihn durchlassen"), f("Der Fußgänger muss auf der Fahrbahn stehen bleiben", "Fußgänger, die bei Grün gestartet sind, dürfen bei Rot die Straße noch zügig verlassen."), f("Sie dürfen anfahren, weil Sie Grün haben und der Fußgänger Rot", "Grün berechtigt nicht dazu, Fußgänger zu gefährden.")],
    explanation: "Wer als Fußgänger bei Grün die Fahrbahn betreten hat, darf sie bei Rot zügig zu Ende überqueren. Fahrzeuge müssen das ermöglichen, auch wenn ihre Ampel bereits Grün zeigt.",
    legalReference: "§ 37 Abs. 2 Nr. 5 StVO; § 1 StVO",
  }),
  q({
    code: "own-verkehrsregelung-031", topic: "verkehrsregelung", points: 3, difficulty: 0.6, tags: ["haifischzaehne", "wartelinie", "vorfahrt_gewaehren", "markierung"],
    text: "Auf der Fahrbahn vor einer Einmündung sind weiße Dreiecke quer zur Fahrbahn markiert (Haifischzähne, Zeichen 342). Was bedeutet das?",
    answers: [t("Sie müssen dem Verkehr auf der kreuzenden Straße Vorfahrt gewähren"), f("Sie haben Vorfahrt und die anderen müssen warten", "Die Dreiecke weisen auf Ihre Wartepflicht hin."), f("Sie müssen immer anhalten wie am Stoppschild", "Angehalten wird nur, wenn es die Verkehrslage erfordert.")],
    explanation: "Die Haifischzähne kennzeichnen die Stelle, an der Vorfahrt zu gewähren ist. Sie haben die gleiche Bedeutung wie das Zeichen 205 und werden oft zusätzlich zu diesem angebracht, zum Beispiel an Radwegen oder Kreisverkehren.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 342)",
  }),
  q({
    code: "own-verkehrsregelung-032", topic: "verkehrsregelung", points: 3, difficulty: 0.55, tags: ["wartelinie", "markierung", "halten"],
    text: "Was bedeutet eine Wartelinie (Zeichen 341, unterbrochene breite Querlinie) vor einer Kreuzung?",
    answers: [t("Sie empfiehlt, wo bei Wartepflicht gehalten werden sollte; sie verpflichtet nicht zum Anhalten"), f("Sie verpflichtet immer zum Anhalten wie eine Haltlinie", "Anhaltepflicht besteht nur an der durchgezogenen Haltlinie oder wenn es die Verkehrslage erfordert."), f("Sie markiert die Grenze, bis zu der geparkt werden darf", "Die Wartelinie regelt nur das Warten bei Vorfahrt.")],
    explanation: "Die Wartelinie zeigt, wo man bei Wartepflicht am besten hält. Anders als die Haltlinie verpflichtet sie nicht zum Anhalten; ist die Kreuzung frei, darf ohne Halt weitergefahren werden.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 341)",
  }),
  q({
    code: "own-verkehrsregelung-033", topic: "verkehrsregelung", points: 3, difficulty: 0.6, tags: ["gefahrzeichen", "lichtzeichenanlage", "ausserorts"],
    text: "Außerorts sehen Sie das Gefahrzeichen 131 (Lichtzeichenanlage). Warum steht es dort und wie verhalten Sie sich?",
    answers: [t("Es warnt vor einer Ampel, die überraschend kommt oder schlecht zu sehen ist"), t("Sie sollten die Geschwindigkeit verringern und mit einem Halt rechnen"), f("Es zeigt an, dass die nächste Ampel außer Betrieb ist", "Das Zeichen warnt vor einer Ampel; ihre Betriebsbereitschaft ist nicht Gegenstand des Zeichens."), f("Es bedeutet, dass Sie an der nächsten Ampel Vorfahrt haben", "Vorfahrt ergibt sich nur aus den Lichtzeichen selbst.")],
    explanation: "Zeichen 131 kündigt eine Ampel an, mit der außerorts nicht gerechnet wird, etwa nach einer Kuppe oder in einer Kurve. Es ist vorausschauend abzubremsen, weil Ampeln außerorts oft bei hohem Tempo erreicht werden.",
    legalReference: "§ 40 StVO, Anlage 1 (Zeichen 131)",
  }),
  q({
    code: "own-verkehrsregelung-034", topic: "verkehrsregelung", points: 3, difficulty: 0.55, tags: ["blinklicht", "rot", "einsatzfahrzeug", "feuerwehr"],
    text: "Vor einer Feuerwehrausfahrt blinkt ein rotes Licht. Was bedeutet das?",
    answers: [t("Halt; ein Einsatzfahrzeug wird ausfahren"), f("Nur eine Warnung, es besteht keine Anhaltepflicht", "Rotes Blinklicht bedeutet Halt, gelbes Blinklicht nur Warnung."), f("Die Fahrbahn ist dauerhaft gesperrt", "Das Signal gilt nur, solange es blinkt.")],
    explanation: "Rotes Blinklicht, etwa vor Feuerwehrausfahrten oder an Bahnübergängen, bedeutet Halt. Gelbes Blinklicht dagegen mahnt nur zur Vorsicht.",
    legalReference: "§ 37 Abs. 2 StVO; § 38 Abs. 3 StVO",
  }),
  q({
    code: "own-verkehrsregelung-035", topic: "verkehrsregelung", points: 4, difficulty: 0.7, tags: ["rangfolge", "polizei", "lichtzeichen", "verkehrszeichen", "rechts_vor_links"],
    text: "Ordnen Sie die Regelungen an einer Kreuzung nach ihrem Rang. Welche Aussagen sind richtig?",
    answers: [t("Weisungen von Polizeibeamten gehen Lichtzeichen und Verkehrszeichen vor"), t("Lichtzeichen gehen Vorschrift- und Richtzeichen vor, auch einem Stoppschild"), t("Rechts vor links gilt nur, wenn weder Polizei noch Ampel noch Verkehrszeichen die Vorfahrt regeln"), f("Verkehrszeichen gehen Lichtzeichen vor, wenn sie auf demselben Mast angebracht sind", "Auch dann haben in Betrieb befindliche Lichtzeichen Vorrang.")],
    explanation: "Die Rangfolge lautet: Polizei vor Lichtzeichen, Lichtzeichen vor Verkehrszeichen, Verkehrszeichen vor der Grundregel rechts vor links. Ein Stoppschild unter einer funktionierenden Ampel greift nur, wenn die Ampel ausgeschaltet ist.",
    legalReference: "§ 36 Abs. 1 StVO; § 37 Abs. 1 StVO; § 8 Abs. 1 StVO",
  }),
  q({
    code: "own-verkehrsregelung-036", topic: "verkehrsregelung", points: 3, difficulty: 0.55, tags: ["ampel", "rot", "rechtsabbiegen", "ohne_gruenpfeil"],
    text: "Die Ampel zeigt Rot, es ist kein Grünpfeilschild angebracht und die Kreuzung ist völlig leer. Dürfen Sie rechts abbiegen?",
    answers: [t("Nein, ohne Grünpfeil ist das Abbiegen bei Rot ein Rotlichtverstoß"), f("Ja, wenn Sie vorher anhalten und niemanden behindern", "Das gilt nur mit Grünpfeilschild."), f("Ja, weil Rechtsabbieger den Querverkehr nicht kreuzen", "Rot gilt für alle Fahrtrichtungen, sofern kein Pfeil oder Grünpfeilschild etwas anderes erlaubt.")],
    explanation: "Rot bedeutet Halt für alle Fahrtrichtungen. Nur ein Grünpfeilschild (Zeichen 720) erlaubt nach dem Anhalten das Rechtsabbiegen. Ohne dieses Schild ist das Abbiegen bei Rot ein Rotlichtverstoß mit Bußgeld und Punkt.",
    legalReference: "§ 37 Abs. 2 Nr. 1 StVO",
  }),
  q({
    code: "own-verkehrsregelung-037", topic: "verkehrsregelung", points: 3, difficulty: 0.5, tags: ["gelbes_blinklicht", "ampel", "ausser_betrieb", "vorfahrt_beschildert"],
    text: "Eine Ampel blinkt in allen Richtungen nur gelb. Was gilt an dieser Kreuzung?",
    answers: [t("Die Ampel ist außer Betrieb; es gelten die aufgestellten Verkehrszeichen, sonst rechts vor links"), f("Alle Verkehrsteilnehmer müssen anhalten und sich verständigen", "Eine allgemeine Anhaltepflicht besteht nicht; es gelten die Verkehrszeichen."), f("Der Verkehr auf der breiteren Straße hat Vorfahrt", "Die Breite der Straße begründet keine Vorfahrt.")],
    explanation: "Gelbes Blinklicht an einer Ampel zeigt an, dass sie nicht regelt. Dann gelten die Verkehrszeichen an der Kreuzung; fehlen diese, greift rechts vor links. Besondere Vorsicht ist geboten, weil andere die Lage falsch einschätzen können.",
    legalReference: "§ 37 Abs. 1 StVO; § 38 Abs. 3 StVO; § 8 StVO",
  }),
  q({
    code: "own-verkehrsregelung-038", topic: "verkehrsregelung", points: 3, difficulty: 0.6, tags: ["haltlinie", "fussgaengerfurt", "rot", "halten"],
    text: "Bei Rot halten Sie versehentlich erst auf der Fußgängerfurt hinter der Haltlinie. Was ist richtig?",
    answers: [t("Das Überfahren der Haltlinie bei Rot ist bereits ein Rotlichtverstoß"), t("Fußgänger auf der Furt werden behindert; Sie hätten vor der Haltlinie halten müssen"), f("Das ist erlaubt, solange Sie die kreuzende Fahrbahn nicht erreichen", "Maßgeblich ist die Haltlinie, nicht die Fahrbahn der Querstraße."), f("Sie dürfen jetzt weiterfahren, weil Sie die Haltlinie ohnehin überfahren haben", "Auch danach ist bis Grün zu warten.")],
    explanation: "Bei Rot muss vor der Haltlinie angehalten werden. Wer sie überfährt, begeht einen Rotlichtverstoß, auch wenn er nicht in die Kreuzung einfährt. Auf der Fußgängerfurt behindert das Fahrzeug außerdem querende Fußgänger.",
    legalReference: "§ 37 Abs. 2 StVO; Zeichen 294",
  }),
  q({
    code: "own-verkehrsregelung-039", topic: "verkehrsregelung", points: 3, difficulty: 0.45, tags: ["ampel", "gruen", "anfahren", "verkehrsbeobachtung"],
    text: "Die Ampel schaltet auf Grün. Worauf achten Sie vor dem Anfahren?",
    answers: [t("Ob die Kreuzung frei ist, insbesondere ob noch Fahrzeuge oder Fußgänger die Kreuzung räumen"), t("Ob sich ein Einsatzfahrzeug mit Blaulicht und Horn nähert"), f("Nur auf die Ampel, weil Grün Vorrang bedeutet", "Grün bedeutet Freigabe, nicht Vorrang um jeden Preis."), f("Auf nichts, das Fahrzeug hinter Ihnen wartet ohnehin", "Die Verkehrsbeobachtung ist immer Pflicht.")],
    explanation: "Grün gibt den Verkehr frei, ersetzt aber nicht den Blick in die Kreuzung. Fahrzeuge, die sie noch räumen, Fußgänger und Einsatzfahrzeuge mit Sondersignal müssen berücksichtigt werden.",
    legalReference: "§ 37 Abs. 2 StVO; § 1 StVO; § 38 Abs. 1 StVO",
  }),
  q({
    code: "own-verkehrsregelung-040", topic: "verkehrsregelung", points: 3, difficulty: 0.45, tags: ["dauerlichtzeichen", "gruener_pfeil", "fahrstreifen"],
    text: "Über den Fahrstreifen einer Autobahn leuchten grüne, nach unten zeigende Pfeile. Was bedeutet das?",
    answers: [t("Die Fahrstreifen unter den grünen Pfeilen dürfen benutzt werden"), f("Sie müssen die Fahrstreifen in Pfeilrichtung verlassen", "Der grüne Pfeil gibt frei; der Wechsel wird durch gelbe Blinkpfeile angeordnet."), f("Auf diesen Fahrstreifen gilt Mindestgeschwindigkeit", "Der Pfeil sagt nichts über die Geschwindigkeit aus.")],
    explanation: "Dauerlichtzeichen über Fahrstreifen: Grüner Pfeil nach unten gibt den Fahrstreifen frei, rotes Kreuz sperrt ihn, gelber Blinkpfeil ordnet den Wechsel an.",
    legalReference: "§ 37 Abs. 3 StVO",
  }),
];
