// Übungsfragen zum Thema "verkehrszeichen" (eigene Formulierungen, kein amtlicher Prüfungsinhalt).
import type { Question } from "../types";
import { q, t, f } from "./_helpers";

export const verkehrszeichen: readonly Question[] = [
  q({
    code: "own-verkehrszeichen-001", topic: "verkehrszeichen", points: 2, difficulty: 0.1, tags: ["gefahrzeichen", "zeichenarten"],
    text: "Welche Art von Verkehrszeichen ist dreieckig mit rotem Rand und weißer Fläche?",
    answers: [t("Gefahrzeichen"), f("Vorschriftzeichen", "Vorschriftzeichen sind in der Regel rund."), f("Richtzeichen", "Richtzeichen sind meist rechteckig oder quadratisch und blau oder weiß.")],
    explanation: "Gefahrzeichen sind dreieckig mit rotem Rand und mahnen zu erhöhter Aufmerksamkeit. Vorschriftzeichen sind meist rund, Richtzeichen meist rechteckig.",
    legalReference: "§ 40 StVO, Anlage 1",
  }),
  q({
    code: "own-verkehrszeichen-002", topic: "verkehrszeichen", points: 4, difficulty: 0.2, tags: ["stoppschild", "vorfahrt_beschildert", "halten"],
    text: "Was müssen Sie am Stoppschild (Zeichen 206) tun?",
    answers: [t("Immer anhalten, und zwar an der Haltlinie oder, wenn keine vorhanden ist, dort, wo Sie die Kreuzung übersehen können"), f("Nur anhalten, wenn anderer Verkehr zu sehen ist", "Am Stoppschild besteht immer Anhaltepflicht."), f("Bei guter Sicht langsam heranrollen und weiterfahren", "Auch bei guter Übersicht muss das Fahrzeug zum Stillstand kommen.")],
    explanation: "Das Stoppschild verlangt immer ein vollständiges Anhalten, auch wenn kein Verkehr zu sehen ist. Anschließend ist Vorfahrt zu gewähren.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 206)",
  }),
  q({
    code: "own-verkehrszeichen-003", topic: "verkehrszeichen", points: 3, difficulty: 0.3, tags: ["vorfahrt_gewaehren", "vorfahrt_beschildert"],
    text: "Was bedeutet das Zeichen 205 (auf der Spitze stehendes Dreieck)?",
    answers: [t("Vorfahrt gewähren; anhalten müssen Sie nur, wenn es erforderlich ist"), f("Immer anhalten, auch ohne Verkehr", "Das ist die Regel am Stoppschild."), f("Sie haben Vorfahrt", "Das Zeichen bedeutet das Gegenteil.")],
    explanation: "Das Zeichen Vorfahrt gewähren verpflichtet zum Warten, wenn Fahrzeuge auf der bevorrechtigten Straße kommen. Ist die Kreuzung frei, dürfen Sie ohne Anhalten weiterfahren.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 205)",
  }),
  q({
    code: "own-verkehrszeichen-004", topic: "verkehrszeichen", points: 3, difficulty: 0.3, tags: ["verkehrsberuhigter_bereich", "innerorts", "parken"],
    text: "Was gilt in einem verkehrsberuhigten Bereich (Zeichen 325.1)?",
    answers: [t("Es darf nur mit Schrittgeschwindigkeit gefahren werden"), t("Kinderspiele sind überall erlaubt"), t("Parken ist nur auf gekennzeichneten Flächen erlaubt"), f("Fußgänger müssen den Gehweg benutzen", "Fußgänger dürfen die Straße in ganzer Breite benutzen.")],
    explanation: "Im verkehrsberuhigten Bereich gilt Schrittgeschwindigkeit, Fußgänger dürfen die gesamte Straße nutzen und Kinder überall spielen. Geparkt wird nur auf gekennzeichneten Flächen.",
    legalReference: "§ 42 StVO, Anlage 3 (Zeichen 325.1)",
  }),
  q({
    code: "own-verkehrszeichen-005", topic: "verkehrszeichen", points: 3, difficulty: 0.3, tags: ["halteverbot", "halten", "parken"],
    text: "Was ist im eingeschränkten Halteverbot (Zeichen 286) erlaubt?",
    answers: [t("Halten bis zu drei Minuten sowie zum Ein- oder Aussteigen und zum Be- oder Entladen"), f("Parken bis zu 30 Minuten", "Parken ist im eingeschränkten Halteverbot nicht erlaubt."), f("Gar nichts, auch kein kurzes Halten", "Das gilt im absoluten Halteverbot (Zeichen 283).")],
    explanation: "Im eingeschränkten Halteverbot darf bis zu drei Minuten gehalten werden, länger nur zum Ein- und Aussteigen oder zum Be- und Entladen. Im absoluten Halteverbot ist jedes Halten verboten.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 283 und 286)",
  }),
  q({
    code: "own-verkehrszeichen-006", topic: "verkehrszeichen", points: 3, difficulty: 0.4, tags: ["fahrradstrasse", "radverkehr"],
    text: "Was gilt in einer Fahrradstraße (Zeichen 244.1)?",
    answers: [t("Kraftfahrzeuge dürfen sie nur benutzen, wenn ein Zusatzzeichen das erlaubt"), t("Es gilt eine Höchstgeschwindigkeit von 30 km/h"), t("Radfahrende dürfen nebeneinander fahren"), f("Kraftfahrzeuge haben Vorrang vor dem Radverkehr", "Der Radverkehr darf weder gefährdet noch behindert werden.")],
    explanation: "In Fahrradstraßen gilt Tempo 30, Radfahrende dürfen nebeneinander fahren und anderer Verkehr ist nur mit Zusatzzeichen zugelassen. Wer dort fahren darf, muss sich dem Radverkehr anpassen.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 244.1)",
  }),
  q({
    code: "own-verkehrszeichen-007", topic: "verkehrszeichen", points: 2, difficulty: 0.3, tags: ["zone_30", "innerorts", "geschwindigkeit"],
    text: "Wie lange gilt die Geschwindigkeitsbeschränkung in einer Tempo-30-Zone?",
    answers: [t("Bis zum Zeichen, das das Ende der Zone anzeigt"), f("Nur bis zur nächsten Kreuzung", "Zonenregelungen gelten nicht nur bis zur nächsten Kreuzung."), f("Nur für 500 Meter ab dem Zeichen", "Es gibt keine feste Streckenlänge.")],
    explanation: "Zonenbeschränkungen gelten ab dem Zeichen für das gesamte Gebiet bis zum Aufhebungszeichen, auch über Kreuzungen hinweg.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 274.1)",
  }),
  q({
    code: "own-verkehrszeichen-008", topic: "verkehrszeichen", points: 3, difficulty: 0.3, tags: ["verbot_der_einfahrt", "einbahnstrasse"],
    text: "Was bedeutet das runde rote Zeichen mit weißem Querbalken (Zeichen 267)?",
    answers: [t("Verbot der Einfahrt; die Straße darf in dieser Richtung nicht befahren werden"), f("Durchfahrt für Anlieger frei", "Ohne Zusatzzeichen gilt das Verbot für alle."), f("Verbot nur für Lastkraftwagen", "Das Zeichen gilt für alle Fahrzeuge.")],
    explanation: "Das Zeichen Verbot der Einfahrt steht meist am Ende einer Einbahnstraße. Wer hier einfährt, fährt gegen die vorgeschriebene Fahrtrichtung.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 267)",
  }),
  q({
    code: "own-verkehrszeichen-009", topic: "verkehrszeichen", points: 2, difficulty: 0.4, tags: ["gefahrzeichen", "ausserorts"],
    text: "In welcher Entfernung vor der Gefahrstelle stehen Gefahrzeichen außerhalb geschlossener Ortschaften in der Regel?",
    answers: [t("Etwa 150 bis 250 Meter davor"), f("Unmittelbar an der Gefahrstelle", "Dann bliebe keine Zeit, sich darauf einzustellen."), f("Etwa einen Kilometer davor", "So weit im Voraus stehen sie normalerweise nicht.")],
    explanation: "Außerorts stehen Gefahrzeichen in der Regel 150 bis 250 Meter vor der Gefahrstelle, innerorts meist kurz davor. Abweichende Entfernungen werden per Zusatzzeichen angegeben.",
    legalReference: "VwV-StVO zu § 40",
  }),
  q({
    code: "own-verkehrszeichen-010", topic: "verkehrszeichen", points: 4, difficulty: 0.3, tags: ["andreaskreuz", "bahnuebergang"],
    text: "Was bedeutet das Andreaskreuz (Zeichen 201)?",
    answers: [t("Schienenfahrzeuge haben am Bahnübergang Vorrang"), f("Hier endet eine Vorfahrtstraße", "Das Andreaskreuz kennzeichnet einen Bahnübergang."), f("Hier darf im Schritttempo überholt werden", "Am Bahnübergang gilt ein Überholverbot.")],
    explanation: "Das Andreaskreuz steht unmittelbar vor dem Bahnübergang und weist auf den Vorrang des Schienenverkehrs hin. Vor dem Zeichen ist zu warten, wenn sich ein Schienenfahrzeug nähert.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 201); § 19 StVO",
  }),
  q({
    code: "own-verkehrszeichen-011", topic: "verkehrszeichen", points: 3, difficulty: 0.4, tags: ["vorfahrt_beschildert", "vorfahrt"],
    text: "Wofür gilt das Zeichen 301 „Vorfahrt“ (Dreieck mit rotem Rand und breitem schwarzem Pfeil)?",
    answers: [t("Nur für die nächste Kreuzung oder Einmündung"), f("Für die gesamte Straße bis zum Aufhebungszeichen", "Das ist die Wirkung der Vorfahrtstraße (Zeichen 306)."), f("Für eine Strecke von einem Kilometer", "Es gibt keine feste Streckenlänge.")],
    explanation: "Zeichen 301 gewährt Vorfahrt nur an der nächsten Kreuzung oder Einmündung. Dauerhaft bevorrechtigt ist man nur auf einer Vorfahrtstraße (Zeichen 306).",
    legalReference: "§ 42 StVO, Anlage 3 (Zeichen 301)",
  }),
  q({
    code: "own-verkehrszeichen-012", topic: "verkehrszeichen", points: 3, difficulty: 0.3, tags: ["ueberholverbot", "ueberholen"],
    text: "Was verbietet das Zeichen 276 (rotes und schwarzes Auto im roten Kreis)?",
    answers: [t("Das Überholen von mehrspurigen Kraftfahrzeugen und Krafträdern mit Beiwagen"), f("Das Überholen von Fahrrädern", "Einspurige Fahrzeuge dürfen bei ausreichendem Abstand überholt werden."), f("Das Fahren mit mehr als 60 km/h", "Das Zeichen regelt keine Geschwindigkeit.")],
    explanation: "Zeichen 276 verbietet Kraftfahrzeugen das Überholen mehrspuriger Kraftfahrzeuge und von Krafträdern mit Beiwagen. Einspurige Fahrzeuge wie Fahrräder dürfen weiterhin mit ausreichendem Abstand überholt werden.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 276)",
  }),
  q({
    code: "own-verkehrszeichen-013", topic: "verkehrszeichen", points: 3, difficulty: 0.6, tags: ["zusatzzeichen", "anlieger_frei", "verbot_fuer_fahrzeuge", "geltungsbereich"],
    text: "Das Zeichen 250 (Verbot für Fahrzeuge aller Art) trägt das Zusatzzeichen „Anlieger frei“. Wer darf einfahren?",
    answers: [t("Bewohner der Straße"), t("Besucher, Lieferanten und Handwerker, die zu einem Grundstück an dieser Straße wollen"), f("Jeder, der die Straße als Abkürzung nutzen möchte", "Durchgangsverkehr ist gerade ausgeschlossen."), f("Nur Fahrzeuge mit einem Parkausweis der Gemeinde", "Ein Parkausweis ist nicht erforderlich; entscheidend ist der Bezug zu einem Anliegergrundstück.")],
    explanation: "Anlieger sind alle, die zu einem Grundstück an dieser Straße wollen: Bewohner ebenso wie deren Besucher, Lieferanten und Handwerker. Wer die Straße nur durchfahren will, darf nicht einfahren.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 250); § 39 Abs. 3 StVO",
  }),
  q({
    code: "own-verkehrszeichen-014", topic: "verkehrszeichen", points: 3, difficulty: 0.6, tags: ["zusatzzeichen", "verbot_der_einfahrt", "radverkehr", "einbahnstrasse"],
    text: "Am Ende einer Einbahnstraße steht das Zeichen 267 (Verbot der Einfahrt) mit dem Zusatzzeichen „Radverkehr frei“. Was gilt?",
    answers: [t("Radfahrende dürfen hier entgegen der Einbahnstraße einfahren"), t("Wer die Einbahnstraße in der regulären Richtung befährt, muss mit entgegenkommenden Radfahrenden rechnen"), f("Auch Mofas dürfen entgegen der Einbahnstraße fahren", "Das Zusatzzeichen gibt nur den Radverkehr frei."), f("Radfahrende dürfen nur auf dem Gehweg entgegen der Einbahnstraße fahren", "Sie dürfen die Fahrbahn benutzen.")],
    explanation: "Das Zusatzzeichen „Radverkehr frei“ öffnet die Einbahnstraße für Radfahrende in Gegenrichtung. Autofahrer müssen deshalb in der ganzen Straße, besonders an Kreuzungen und beim Ausparken, mit Radverkehr aus beiden Richtungen rechnen.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 267 mit Zusatzzeichen 1022-10)",
  }),
  q({
    code: "own-verkehrszeichen-015", topic: "verkehrszeichen", points: 3, difficulty: 0.7, tags: ["verbot", "lkw", "anhaenger", "geltungsbereich"],
    text: "Sie fahren mit Pkw und Wohnwagen; das Gespann hat zusammen 4 t zulässige Gesamtmasse. Vor Ihnen steht das Zeichen 253 (Verbot für Kraftfahrzeuge über 3,5 t). Dürfen Sie weiterfahren?",
    answers: [t("Ja, das Verbot gilt für Kraftfahrzeuge über 3,5 t zulässiger Gesamtmasse einschließlich ihrer Anhänger sowie für Zugmaschinen, ausgenommen sind Pkw und Kraftomnibusse"), f("Nein, weil das Gespann über 3,5 t wiegt", "Pkw sind vom Verbot ausgenommen, auch mit Anhänger."), f("Nur ohne Wohnwagen", "Der Anhänger ändert nichts an der Ausnahme für Pkw.")],
    explanation: "Zeichen 253 richtet sich an Lkw über 3,5 t einschließlich ihrer Anhänger und an Zugmaschinen. Pkw und Kraftomnibusse sind ausdrücklich ausgenommen, auch wenn sie einen Anhänger ziehen.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 253)",
  }),
  q({
    code: "own-verkehrszeichen-016", topic: "verkehrszeichen", points: 3, difficulty: 0.65, tags: ["verbot", "tatsaechliche_masse", "bruecke", "geltungsbereich"],
    text: "Vor einer Brücke steht das Zeichen 262 mit der Angabe „5,5 t“. Ihr Pkw hat 2,5 t zulässige Gesamtmasse und wiegt aktuell mit Insassen und Gepäck 2,1 t. Dürfen Sie fahren?",
    answers: [t("Ja, das Zeichen bezieht sich auf die tatsächliche Masse, und die liegt unter 5,5 t"), f("Nur, wenn die zulässige Gesamtmasse unter der Angabe liegt", "Maßgeblich ist die tatsächliche Masse im Moment der Fahrt."), f("Nein, weil Pkw Brücken mit Massenbeschränkung nicht befahren dürfen", "Das Zeichen gilt für alle Fahrzeuge, aber nur oberhalb der angegebenen tatsächlichen Masse.")],
    explanation: "Zeichen 262 verbietet die Weiterfahrt für Fahrzeuge, deren tatsächliche Masse den angegebenen Wert überschreitet. Es kommt auf das aktuelle Gewicht mit Ladung und Insassen an, nicht auf die zulässige Gesamtmasse.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 262)",
  }),
  q({
    code: "own-verkehrszeichen-017", topic: "verkehrszeichen", points: 3, difficulty: 0.6, tags: ["verbot", "hoehe", "ladung", "geltungsbereich"],
    text: "Vor einer Unterführung steht das Zeichen 265 mit der Angabe „3,8 m“. Ihr Transporter ist laut Zulassungsbescheinigung 2,9 m hoch, mit Dachgepäckträger und Ladung 3,9 m. Was gilt?",
    answers: [t("Sie dürfen nicht durchfahren, weil die tatsächliche Höhe einschließlich Ladung und Dachaufbauten zählt"), f("Sie dürfen durchfahren, weil die Fahrzeughöhe laut Zulassungsbescheinigung unter 3,8 m liegt", "Maßgeblich ist die tatsächliche Höhe mit Dachgepäckträger und Ladung."), f("Sie dürfen langsam durchfahren, weil eine geringe Überschreitung geduldet wird", "Die angegebene Höhe darf nicht überschritten werden; Ladung und Unterführung würden beschädigt.")],
    explanation: "Zeichen 265 bezieht sich auf die tatsächliche Höhe des Fahrzeugs einschließlich Ladung, Dachbox oder Fahrradträger. Wer die Höhe nicht kennt, darf nicht auf gut Glück durchfahren.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 265)",
  }),
  q({
    code: "own-verkehrszeichen-018", topic: "verkehrszeichen", points: 3, difficulty: 0.6, tags: ["verbot", "breite", "ladung", "baustelle"],
    text: "In einer Baustelle steht über dem linken Fahrstreifen das Zeichen 264 mit der Angabe „2 m“. Was bedeutet das?",
    answers: [t("Fahrzeuge, die einschließlich Ladung tatsächlich breiter als 2 m sind, dürfen den linken Fahrstreifen nicht benutzen"), t("Als Pkw-Fahrer sollten Sie die Breite Ihres Fahrzeugs kennen; viele SUV und Transporter sind mit Spiegeln breiter als 2 m"), f("Der linke Fahrstreifen ist für alle Fahrzeuge gesperrt", "Nur breitere Fahrzeuge sind ausgeschlossen."), f("Auf dem linken Fahrstreifen gilt 20 km/h", "Das Zeichen regelt keine Geschwindigkeit.")],
    explanation: "Zeichen 264 verbietet Fahrzeugen über der angegebenen tatsächlichen Breite die Weiterfahrt auf dem betroffenen Fahrstreifen. In Baustellen dient es dazu, breite Fahrzeuge auf den rechten, breiteren Fahrstreifen zu lenken.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 264)",
  }),
  q({
    code: "own-verkehrszeichen-019", topic: "verkehrszeichen", points: 3, difficulty: 0.6, tags: ["umweltzone", "zone", "plakette", "geltungsbereich"],
    text: "Sie erreichen das Zeichen 270.1 (Umweltzone) mit einem Zusatzzeichen, das eine grüne Plakette zeigt. Was gilt?",
    answers: [t("In die Zone dürfen nur Kraftfahrzeuge einfahren, die die auf dem Zusatzzeichen gezeigte Plakette an der Windschutzscheibe tragen"), t("Die Regelung gilt für alle Straßen innerhalb der Zone bis zum Zeichen 270.2"), f("Das Zeichen gilt nur für Lkw", "Es gilt für alle Kraftfahrzeuge, die der Kennzeichnungspflicht unterliegen."), f("Ohne Plakette dürfen Sie einfahren, wenn Sie nicht länger als 30 Minuten bleiben", "Eine zeitliche Ausnahme gibt es nicht.")],
    explanation: "Die Umweltzone ist eine Verkehrsverbotszone: Einfahren dürfen nur Fahrzeuge mit der auf dem Zusatzzeichen genannten Plakette. Die Regelung gilt flächendeckend bis zum Ende der Zone; Ausnahmen bestehen nur mit Genehmigung oder für bestimmte Fahrzeuggruppen.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 270.1 und 270.2); 35. BImSchV",
  }),
  q({
    code: "own-verkehrszeichen-020", topic: "verkehrszeichen", points: 3, difficulty: 0.65, tags: ["zone", "halteverbot", "halten", "parken"],
    text: "Sie fahren in eine Zone mit eingeschränktem Halteverbot (Zeichen 290.1) ein. Was gilt in der gesamten Zone?",
    answers: [t("Halten bis zu drei Minuten sowie zum Ein- und Aussteigen und zum Be- und Entladen ist erlaubt"), t("Parken ist nur dort erlaubt, wo es durch Zeichen 314 oder 315 oder Markierungen ausdrücklich zugelassen ist"), f("Parken ist überall erlaubt, wo kein Halteverbotsschild steht", "Das Zonenzeichen gilt für alle Straßen der Zone ohne Wiederholung."), f("Auch das kurze Halten ist verboten", "Das gilt nur im absoluten Halteverbot.")],
    explanation: "In der Zone mit eingeschränktem Halteverbot gilt auf allen Straßen das eingeschränkte Halteverbot, ohne dass die Zeichen wiederholt werden. Geparkt werden darf nur auf ausdrücklich gekennzeichneten Flächen, oft mit Parkscheibe oder Parkschein.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 290.1 und 290.2)",
  }),
  q({
    code: "own-verkehrszeichen-021", topic: "verkehrszeichen", points: 3, difficulty: 0.55, tags: ["zone", "parken", "parkraumbewirtschaftung", "parkschein"],
    text: "Was bedeutet das Zeichen 314.1 (Beginn einer Parkraumbewirtschaftungszone)?",
    answers: [t("Innerhalb der Zone darf nur mit Parkschein oder Parkscheibe geparkt werden, wie es das Zusatzzeichen angibt"), f("In der Zone ist das Parken kostenlos und unbegrenzt erlaubt", "Die Zone regelt gerade die Bewirtschaftung, also Parkschein oder Parkscheibe."), f("In der Zone gilt absolutes Halteverbot", "Halten ist erlaubt; nur das Parken wird geregelt.")],
    explanation: "In einer Parkraumbewirtschaftungszone gilt auf allen Straßen die auf dem Zusatzzeichen angegebene Regelung, etwa Parkschein oder Parkscheibe mit Höchstparkdauer. Die Zeichen werden innerhalb der Zone nicht wiederholt.",
    legalReference: "§ 42 StVO, Anlage 3 (Zeichen 314.1 und 314.2); § 13 StVO",
  }),
  q({
    code: "own-verkehrszeichen-022", topic: "verkehrszeichen", points: 3, difficulty: 0.6, tags: ["fahrradzone", "zone", "radverkehr", "zusatzzeichen"],
    text: "Sie erreichen das Zeichen 244.3 (Beginn einer Fahrradzone). Darunter ist ein Zusatzzeichen „Anlieger frei“ angebracht. Was gilt?",
    answers: [t("Sie dürfen als Anlieger einfahren, höchstens 30 km/h fahren und müssen sich dem Radverkehr anpassen"), t("Die Regeln gelten für alle Straßen der Zone bis zum Zeichen 244.4"), f("Ohne das Zusatzzeichen dürften Pkw in der Fahrradzone frei fahren", "Ohne Zusatzzeichen ist anderer Fahrzeugverkehr ausgeschlossen."), f("Radfahrende müssen in der Fahrradzone hintereinander fahren", "Sie dürfen nebeneinander fahren.")],
    explanation: "In der Fahrradzone gelten die Regeln der Fahrradstraße flächendeckend: 30 km/h, Radverkehr darf nebeneinander fahren und hat Vorrang, anderer Verkehr nur mit Zusatzzeichen. Die Zone endet mit Zeichen 244.4.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 244.3 und 244.4)",
  }),
  q({
    code: "own-verkehrszeichen-023", topic: "verkehrszeichen", points: 3, difficulty: 0.6, tags: ["gehweg", "zusatzzeichen", "radverkehr", "fussgaenger"],
    text: "Das Zeichen 239 (Gehweg) trägt das Zusatzzeichen „Radverkehr frei“. Was bedeutet das für Radfahrende?",
    answers: [t("Sie dürfen den Gehweg benutzen, müssen aber Schrittgeschwindigkeit fahren und Fußgängern Vorrang geben"), t("Sie dürfen stattdessen auch auf der Fahrbahn fahren, weil keine Benutzungspflicht besteht"), f("Sie müssen den Gehweg benutzen", "Das Zusatzzeichen erlaubt die Benutzung, schreibt sie aber nicht vor."), f("Sie dürfen auf dem Gehweg so schnell fahren wie auf dem Radweg", "Auf freigegebenen Gehwegen gilt Schrittgeschwindigkeit.")],
    explanation: "„Radverkehr frei“ am Gehweg erlaubt Radfahrenden die Benutzung, verpflichtet sie aber nicht. Wer den Gehweg nutzt, muss Schrittgeschwindigkeit fahren und auf Fußgänger besondere Rücksicht nehmen.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 239 mit Zusatzzeichen 1022-10)",
  }),
  q({
    code: "own-verkehrszeichen-024", topic: "verkehrszeichen", points: 3, difficulty: 0.55, tags: ["radweg", "gehweg", "benutzungspflicht", "abbiegen"],
    text: "Neben der Fahrbahn verläuft ein Weg mit dem Zeichen 240 (Gemeinsamer Geh- und Radweg). Was gilt?",
    answers: [t("Radfahrende müssen diesen Weg benutzen und dürfen nicht auf der Fahrbahn fahren"), t("Als Autofahrer müssen Sie beim Abbiegen Radfahrende und Fußgänger auf diesem Weg durchlassen"), f("Radfahrende dürfen wählen, ob sie den Weg oder die Fahrbahn benutzen", "Das blaue Zeichen ordnet eine Benutzungspflicht an."), f("Fußgänger dürfen den Weg nicht benutzen", "Der Weg ist für Fußgänger und Radverkehr gemeinsam bestimmt.")],
    explanation: "Zeichen 240 ordnet einen gemeinsamen Geh- und Radweg mit Benutzungspflicht für den Radverkehr an. Beim Abbiegen müssen Autofahrer alle Benutzer dieses Weges durchlassen.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 240); § 9 Abs. 3 StVO",
  }),
  q({
    code: "own-verkehrszeichen-025", topic: "verkehrszeichen", points: 3, difficulty: 0.6, tags: ["halteverbot", "geltungsbereich", "pfeile", "halten"],
    text: "Ein absolutes Halteverbot (Zeichen 283) trägt zwei waagerechte Pfeile, einen nach links und einen nach rechts (Zeichen 283-30). Was bedeutet das?",
    answers: [t("Das Halteverbot gilt sowohl vor als auch hinter dem Zeichen; das Zeichen steht in der Mitte der Verbotsstrecke"), f("Das Halteverbot beginnt hier", "Der Beginn wird mit einem einzelnen Pfeil in Fahrtrichtung angezeigt."), f("Das Halteverbot endet hier", "Das Ende wird mit einem einzelnen Pfeil entgegen der Fahrtrichtung angezeigt.")],
    explanation: "Pfeile auf Haltverbotszeichen zeigen den Geltungsbereich: Ein Pfeil in Fahrtrichtung markiert den Anfang, ein Pfeil entgegen der Fahrtrichtung das Ende, zwei Pfeile die Mitte der Verbotsstrecke.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 283)",
  }),
  q({
    code: "own-verkehrszeichen-026", topic: "verkehrszeichen", points: 3, difficulty: 0.7, tags: ["halteverbot", "zusatzzeichen", "werktags", "parken"],
    text: "Ein eingeschränktes Halteverbot (Zeichen 286) trägt das Zusatzzeichen „werktags 8-18 h“. Dürfen Sie hier am Samstag um 15 Uhr parken?",
    answers: [t("Nein, weil der Samstag ein Werktag ist und das Halteverbot dann gilt"), f("Ja, weil das Wochenende nicht als werktags zählt", "Werktage sind Montag bis Samstag; nur Sonn- und Feiertage sind ausgenommen."), f("Ja, weil das eingeschränkte Halteverbot Parken nie verbietet", "Im eingeschränkten Halteverbot ist Parken verboten, nur kurzes Halten erlaubt.")],
    explanation: "Werktags umfasst Montag bis Samstag; nur Sonn- und Feiertage sind ausgenommen. Am Samstag um 15 Uhr gilt das Halteverbot, Parken ist also verboten. Sonntags oder werktags außerhalb der Zeiten darf geparkt werden, wenn nichts anderes entgegensteht.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 286); § 39 Abs. 3 StVO",
  }),
  q({
    code: "own-verkehrszeichen-027", topic: "verkehrszeichen", points: 3, difficulty: 0.65, tags: ["parken", "parkscheibe", "zusatzzeichen", "hoechstparkdauer"],
    text: "Das Zeichen 314 (Parken) trägt das Zusatzzeichen „2 Std. mit Parkscheibe“. Sie kommen um 10:10 Uhr an. Was ist richtig?",
    answers: [t("Sie stellen die Parkscheibe auf 10:30 Uhr, also auf die halbe Stunde, die der Ankunftszeit folgt"), t("Sie dürfen bis 12:30 Uhr parken"), f("Sie stellen die Parkscheibe auf 10:00 Uhr, weil abgerundet wird", "Es wird auf die nächste halbe Stunde nach der Ankunft eingestellt."), f("Ohne Parkscheibe dürfen Sie eine Stunde parken", "Ohne Parkscheibe ist das Parken hier nicht erlaubt.")],
    explanation: "Bei Parkscheibenpflicht wird die Scheibe auf die halbe Stunde eingestellt, die der Ankunftszeit folgt. Bei Ankunft um 10:10 Uhr also auf 10:30 Uhr; die Höchstparkdauer von zwei Stunden läuft dann bis 12:30 Uhr.",
    legalReference: "§ 13 Abs. 2 StVO; § 42 StVO, Anlage 3 (Zeichen 314)",
  }),
  q({
    code: "own-verkehrszeichen-028", topic: "verkehrszeichen", points: 3, difficulty: 0.65, tags: ["vorfahrtstrasse", "parken", "ausserorts", "geltungsbereich"],
    text: "Außerorts fahren Sie auf einer Vorfahrtstraße (Zeichen 306). Dürfen Sie am Fahrbahnrand parken, um eine Pause zu machen?",
    answers: [t("Nein, auf Vorfahrtstraßen außerhalb geschlossener Ortschaften darf auf der Fahrbahn nicht geparkt werden"), f("Ja, wenn der Warnblinker eingeschaltet ist", "Der Warnblinker erlaubt kein Parken."), f("Ja, weil das Zeichen nur die Vorfahrt regelt", "Zeichen 306 ordnet außerorts zusätzlich ein Parkverbot auf der Fahrbahn an.")],
    explanation: "Das Zeichen 306 regelt nicht nur die Vorfahrt: Außerhalb geschlossener Ortschaften darf auf der Fahrbahn der Vorfahrtstraße nicht geparkt werden, weil parkende Fahrzeuge dort bei hohen Geschwindigkeiten besonders gefährlich sind.",
    legalReference: "§ 42 StVO, Anlage 3 (Zeichen 306)",
  }),
  q({
    code: "own-verkehrszeichen-029", topic: "verkehrszeichen", points: 2, difficulty: 0.5, tags: ["sackgasse", "radverkehr", "fussgaenger", "richtzeichen"],
    text: "Am Beginn einer Straße steht das Zeichen 357-50 (Sackgasse mit Fußgänger- und Fahrradsymbol). Was bedeutet das?",
    answers: [t("Für Kraftfahrzeuge ist die Straße eine Sackgasse; für Fußgänger und Radfahrende ist sie am Ende durchlässig"), f("Die Straße ist für alle Verkehrsteilnehmer eine Sackgasse", "Fußgänger und Radfahrende kommen am Ende weiter."), f("Fußgänger und Radfahrende dürfen die Straße nicht benutzen", "Das Zeichen zeigt gerade, dass sie durchkommen.")],
    explanation: "Das Zeichen zeigt eine für den Fahrzeugverkehr geschlossene Straße an, die für Fußgänger und Radfahrende am Ende weiterführt. Autofahrer sollten deshalb mit Radverkehr rechnen, der am Ende der Sackgasse ein- oder ausfährt.",
    legalReference: "§ 42 StVO, Anlage 3 (Zeichen 357-50)",
  }),
  q({
    code: "own-verkehrszeichen-030", topic: "verkehrszeichen", points: 3, difficulty: 0.6, tags: ["gefahrzeichen", "fussgaengerueberweg", "ausserorts", "zebrastreifen"],
    text: "Außerorts sehen Sie das Gefahrzeichen 101 mit dem Sinnbild eines Fußgängerüberwegs. Was ist richtig?",
    answers: [t("Das Zeichen warnt vor einem Zebrastreifen, der etwa 150 bis 250 Meter weiter kommt"), t("Sie müssen sich so verhalten, dass Sie am Zebrastreifen rechtzeitig anhalten können"), f("An dieser Stelle befindet sich bereits der Zebrastreifen", "Der Überweg selbst wird mit Zeichen 350 und der Markierung gekennzeichnet."), f("Das Zeichen gilt nur bei Dunkelheit", "Gefahrzeichen gelten immer, wenn kein Zusatzzeichen etwas anderes angibt.")],
    explanation: "Das Gefahrzeichen mit dem Fußgängerüberweg kündigt außerorts einen Zebrastreifen in einiger Entfernung an. Weil dort mit hohen Geschwindigkeiten gefahren wird, ist die Vorwarnung wichtig, um rechtzeitig bremsbereit zu sein.",
    legalReference: "§ 40 StVO, Anlage 1 (Zeichen 101-11); § 26 StVO",
  }),
  q({
    code: "own-verkehrszeichen-031", topic: "verkehrszeichen", points: 2, difficulty: 0.55, tags: ["gefahrzeichen", "gefaelle", "bergab", "zahlenwert"], kind: "numeric", numericAnswer: 10, tolerance: 0, unit: "m",
    text: "Das Gefahrzeichen 108 zeigt ein Gefälle von 10 %. Um wie viele Meter fällt die Straße auf 100 Metern Fahrstrecke? Angabe in Metern.",
    answers: [],
    explanation: "10 % Gefälle bedeuten 10 Meter Höhenunterschied auf 100 Meter Strecke. Bei starkem Gefälle sollte ein kleiner Gang gewählt werden, damit die Motorbremswirkung genutzt wird und die Bremsen nicht überhitzen.",
    legalReference: "§ 40 StVO, Anlage 1 (Zeichen 108)",
  }),
  q({
    code: "own-verkehrszeichen-032", topic: "verkehrszeichen", points: 3, difficulty: 0.6, tags: ["gefahrzeichen", "steigung", "ueberholen", "kuppe"],
    text: "Sie sehen das Gefahrzeichen 110 (Steigung 12 %). Worauf müssen Sie sich einstellen?",
    answers: [t("Lkw und andere schwere Fahrzeuge werden deutlich langsamer"), t("Am Ende der Steigung liegt eine Kuppe, an der wegen fehlender Sicht nicht überholt werden darf"), t("Rechtzeitig zurückschalten, damit der Motor genug Kraft hat"), f("Bergauf dürfen Sie die Höchstgeschwindigkeit überschreiten, um Schwung zu holen", "Die Höchstgeschwindigkeit gilt auch am Berg.")],
    explanation: "Starke Steigungen bremsen schwere Fahrzeuge aus und enden oft an unübersichtlichen Kuppen. Wer langsame Fahrzeuge überholen will, braucht ausreichend Sicht; an Kuppen ist Überholen verboten.",
    legalReference: "§ 40 StVO, Anlage 1 (Zeichen 110); § 5 Abs. 2 StVO",
  }),
  q({
    code: "own-verkehrszeichen-033", topic: "verkehrszeichen", points: 3, difficulty: 0.55, tags: ["gefahrzeichen", "splitt", "abstand", "naesse"],
    text: "Das Gefahrzeichen 101-51 (Splitt, Schotter) warnt vor Rollsplitt auf der Fahrbahn. Wie verhalten Sie sich?",
    answers: [t("Geschwindigkeit verringern, weil die Haftung der Reifen auf Splitt deutlich geringer ist"), t("Größeren Abstand halten, weil aufgewirbelte Steine Scheiben und Lack beschädigen können"), f("Dicht auffahren, damit der Vordermann den Splitt wegräumt", "Das ist gefährlich und beschädigt Ihr Fahrzeug."), f("Stärker beschleunigen, um schnell durch den Splitt zu kommen", "Beim Beschleunigen drehen die Räder durch und schleudern Steine.")],
    explanation: "Auf Rollsplitt verlängern sich Bremswege, und in Kurven kann das Fahrzeug ausbrechen. Zusätzlich schleudern Vorausfahrende Steine hoch. Langsam fahren und Abstand halten.",
    legalReference: "§ 40 StVO, Anlage 1 (Zeichen 101-51); § 3 Abs. 1 StVO",
  }),
  q({
    code: "own-verkehrszeichen-034", topic: "verkehrszeichen", points: 3, difficulty: 0.65, tags: ["gefahrzeichen", "verengte_fahrbahn", "gegenverkehr", "vorrang"],
    text: "Das Gefahrzeichen 121 zeigt eine rechts verengte Fahrbahn an. Es sind keine weiteren Zeichen aufgestellt. Wer hat an der Engstelle Vorrang?",
    answers: [t("Das Gefahrzeichen selbst regelt keinen Vorrang; müssen Sie wegen der Verengung auf Ihrer Seite nach links ausweichen, müssen Sie den Gegenverkehr durchfahren lassen"), f("Sie haben Vorrang, weil das Gefahrzeichen auf Ihrer Seite steht", "Gefahrzeichen warnen nur; wer an einer Fahrbahnverengung links vorbeifahren will, muss nach § 6 StVO den Gegenverkehr durchfahren lassen."), f("Der Gegenverkehr muss warten, weil Sie das Zeichen zuerst gesehen haben", "Das Zeichen warnt nur und begründet keinen Vorrang.")],
    explanation: "Gefahrzeichen warnen, sie regeln keinen Vorrang. Wer an einer Fahrbahnverengung, einem Hindernis oder einem haltenden Fahrzeug links vorbeifahren will, muss nach § 6 StVO den Gegenverkehr durchfahren lassen. Nur die Zeichen 208 und 308 ordnen abweichend davon einen Vorrang an.",
    legalReference: "§ 40 StVO, Anlage 1 (Zeichen 121); § 6 StVO; § 1 StVO",
  }),
  q({
    code: "own-verkehrszeichen-035", topic: "verkehrszeichen", points: 2, difficulty: 0.55, tags: ["bahnuebergang", "bake", "gefahrzeichen", "zahlenwert"], kind: "numeric", numericAnswer: 240, tolerance: 0, unit: "m",
    text: "Außerorts steht das Zeichen 156 (Bahnübergang mit dreistreifiger Bake). In welcher Entfernung vor dem Bahnübergang steht es in der Regel? Angabe in Metern.",
    answers: [],
    explanation: "Die dreistreifige Bake steht in der Regel 240 Meter vor dem Bahnübergang, die zweistreifige 160 Meter und die einstreifige 80 Meter davor. Ab dem Gefahrzeichen gilt Überholverbot bis zum Übergang.",
    legalReference: "§ 40 StVO, Anlage 1 (Zeichen 156, 157, 159, 162); § 19 StVO",
  }),
  q({
    code: "own-verkehrszeichen-036", topic: "verkehrszeichen", points: 3, difficulty: 0.6, tags: ["andreaskreuz", "blitzpfeil", "oberleitung", "bahnuebergang"],
    text: "Das Andreaskreuz trägt einen roten Blitzpfeil (Zeichen 201-52). Was bedeutet das zusätzlich?",
    answers: [t("Über dem Bahnübergang verläuft eine elektrische Oberleitung; für hohe Fahrzeuge und Ladung besteht Lebensgefahr"), f("Der Bahnübergang wird von Schnellzügen befahren", "Der Blitzpfeil weist auf die Oberleitung hin, nicht auf die Zuggeschwindigkeit."), f("Der Bahnübergang ist mit Lichtzeichen gesichert", "Lichtzeichen werden getrennt angebracht.")],
    explanation: "Der Blitzpfeil am Andreaskreuz warnt vor der elektrischen Oberleitung der Bahn. Fahrzeuge mit hoher Ladung, Kipper oder Kranaufbauten dürfen sich der Leitung nicht nähern.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 201 mit Blitzpfeil)",
  }),
  q({
    code: "own-verkehrszeichen-037", topic: "verkehrszeichen", points: 3, difficulty: 0.55, tags: ["vorbeifahrt", "vorschriftzeichen", "baustelle", "verkehrsinsel"],
    text: "Vor einer Verkehrsinsel steht das Zeichen 222 mit einem Pfeil, der schräg nach links unten zeigt. Was müssen Sie tun?",
    answers: [t("Links an dem Zeichen beziehungsweise dem Hindernis vorbeifahren"), f("Rechts an dem Zeichen vorbeifahren", "Der Pfeil gibt die Seite der Vorbeifahrt vor: hier links."), f("Vor dem Zeichen anhalten und links abbiegen", "Das Zeichen ordnet nur die Vorbeifahrt an, kein Abbiegen.")],
    explanation: "Das Zeichen 222 schreibt vor, auf welcher Seite an einem Hindernis oder einer Verkehrsinsel vorbeizufahren ist. Zeigt der Pfeil nach links unten, ist links vorbeizufahren.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 222)",
  }),
  q({
    code: "own-verkehrszeichen-038", topic: "verkehrszeichen", points: 3, difficulty: 0.6, tags: ["vorgeschriebene_fahrtrichtung", "vorschriftzeichen", "abbiegen", "kreuzung"],
    text: "An einer Einmündung steht das Zeichen 211 (Vorgeschriebene Fahrtrichtung: hier rechts). Was gilt?",
    answers: [t("Sie müssen an dieser Stelle nach rechts abbiegen; Geradeausfahren, Linksabbiegen und Wenden sind verboten"), f("Sie dürfen auch geradeaus fahren, wenn das möglich ist", "Das Zeichen schreibt die Fahrtrichtung verbindlich vor."), f("Das Zeichen ist nur eine Empfehlung", "Vorschriftzeichen sind verbindlich.")],
    explanation: "Zeichen 211 schreibt die Fahrtrichtung an genau dieser Stelle vor. Andere Richtungen sind ausgeschlossen. Das Zeichen 209 mit geradem Pfeil ordnet dagegen das Abbiegen an der nächsten Kreuzung an.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 209 und 211)",
  }),
  q({
    code: "own-verkehrszeichen-039", topic: "verkehrszeichen", points: 3, difficulty: 0.55, tags: ["vorgeschriebene_fahrtrichtung", "linksabbiegen", "wenden", "vorschriftzeichen"],
    text: "Vor einer Kreuzung steht das Zeichen 214 mit Pfeilen geradeaus und nach rechts. Was ist verboten?",
    answers: [t("Linksabbiegen"), t("Wenden"), f("Geradeausfahren", "Geradeaus ist ausdrücklich erlaubt."), f("Rechtsabbiegen", "Rechtsabbiegen ist ausdrücklich erlaubt.")],
    explanation: "Zeichen 214 erlaubt nur die abgebildeten Fahrtrichtungen. Linksabbiegen und Wenden sind ausgeschlossen, auch wenn die Kreuzung das räumlich zuließe.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 214)",
  }),
  q({
    code: "own-verkehrszeichen-040", topic: "verkehrszeichen", points: 3, difficulty: 0.6, tags: ["verbot", "kraftwagen", "kraftraeder", "geltungsbereich"],
    text: "Vor Ihnen steht das Zeichen 251 (Verbot für Kraftwagen). Welche Fahrzeuge dürfen einfahren?",
    answers: [t("Motorräder und Mofas"), t("Fahrräder und E-Scooter"), f("Pkw mit Anhänger", "Pkw sind Kraftwagen und deshalb ausgeschlossen, mit und ohne Anhänger."), f("Kraftomnibusse", "Busse sind Kraftwagen.")],
    explanation: "Zeichen 251 verbietet Kraftwagen, also Pkw, Lkw und Bussen die Einfahrt. Einspurige Kraftfahrzeuge wie Motorräder und Mofas sowie Fahrräder und Elektrokleinstfahrzeuge sind nicht betroffen.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 251)",
  }),
  q({
    code: "own-verkehrszeichen-041", topic: "verkehrszeichen", points: 3, difficulty: 0.65, tags: ["ende_der_beschraenkung", "streckenverbot", "aufhebung", "zone"],
    text: "Sie passieren das Zeichen 282 (Ende aller Streckenverbote). Welche Regelungen sind damit aufgehoben?",
    answers: [t("Eine vorher angeordnete Geschwindigkeitsbeschränkung (Zeichen 274)"), t("Ein vorher angeordnetes Überholverbot (Zeichen 276 oder 277)"), f("Eine Tempo-30-Zone", "Zonen enden nur mit ihrem eigenen Zonen-Endezeichen."), f("Ein Haltverbot (Zeichen 283 oder 286)", "Haltverbote werden durch ihre eigenen Ende-Zeichen oder Pfeile aufgehoben.")],
    explanation: "Zeichen 282 hebt alle Streckenverbote auf, die durch Vorschriftzeichen wie Geschwindigkeitsbeschränkungen und Überholverbote angeordnet wurden. Zonenregelungen und Haltverbote sind davon nicht betroffen.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 282)",
  }),
  q({
    code: "own-verkehrszeichen-042", topic: "verkehrszeichen", points: 3, difficulty: 0.65, tags: ["ortshinweistafel", "ortstafel", "hoechstgeschwindigkeit", "ausserorts"],
    text: "Auf einer Landstraße passieren Sie die grüne Ortshinweistafel (Zeichen 385) mit einem Ortsnamen. Wie schnell dürfen Sie mit dem Pkw fahren?",
    answers: [t("Weiterhin höchstens 100 km/h, weil die Ortshinweistafel keine geschlossene Ortschaft beginnt"), f("Höchstens 50 km/h, weil ein Ortsname angezeigt wird", "Nur die gelbe Ortstafel (Zeichen 310) begründet die innerörtliche Grenze von 50 km/h."), f("Höchstens 70 km/h als Übergang", "Eine solche Regel gibt es nicht.")],
    explanation: "Die grüne Ortshinweistafel weist nur auf einen Ort hin, etwa an einer Durchgangsstraße, ohne dass eine geschlossene Ortschaft beginnt. Die innerörtliche Grenze von 50 km/h gilt erst ab der gelben Ortstafel (Zeichen 310).",
    legalReference: "§ 42 StVO, Anlage 3 (Zeichen 385 und 310); § 3 Abs. 3 StVO",
  }),
];
