// Übungsfragen zum Thema "vorfahrt" (eigene Formulierungen, kein amtlicher Prüfungsinhalt).
import type { Question } from "../types";
import { q, t, f } from "./_helpers";

export const vorfahrt: readonly Question[] = [
  q({
    code: "own-vorfahrt-001", topic: "vorfahrt", points: 5, difficulty: 0.2, tags: ["rechts_vor_links", "kreuzung"],
    text: "Sie erreichen eine Kreuzung ohne Verkehrszeichen und ohne Ampel. Wer hat Vorfahrt?",
    answers: [t("Wer von rechts kommt"), f("Wer schneller fährt", "Die Geschwindigkeit spielt für die Vorfahrt keine Rolle."), f("Wer auf der breiteren Straße fährt", "Die Straßenbreite ist ohne Bedeutung, solange keine Zeichen aufgestellt sind.")],
    explanation: "An Kreuzungen und Einmündungen ohne Regelung durch Zeichen gilt rechts vor links. Wer von rechts kommt, hat Vorfahrt.",
    mnemonic: "Rechts vor links, wenn keiner winkt und kein Schild blinkt.",
    legalReference: "§ 8 Abs. 1 StVO",
  }),
  q({
    code: "own-vorfahrt-002", topic: "vorfahrt", points: 5, difficulty: 0.4, tags: ["rechts_vor_links", "einmuendung"],
    text: "Sie fahren auf der durchgehenden Straße an einer T-Einmündung ohne Verkehrszeichen. Von rechts kommt aus der einmündenden Straße ein Pkw. Wer muss warten?",
    answers: [t("Sie, denn auch an einer T-Einmündung gilt rechts vor links"), f("Der Pkw, weil die durchgehende Straße Vorrang hat", "Ohne Beschilderung gibt es keinen Vorrang der durchgehenden Straße."), f("Wer zuerst an der Einmündung war", "Ankunftszeit regelt keine Vorfahrt.")],
    explanation: "Ohne Verkehrszeichen gilt auch an T-Einmündungen rechts vor links. Die durchgehende Straße hat keinen automatischen Vorrang.",
    legalReference: "§ 8 Abs. 1 StVO",
  }),
  q({
    code: "own-vorfahrt-003", topic: "vorfahrt", points: 4, difficulty: 0.3, tags: ["grundstuecksausfahrt", "einfahren"],
    text: "Sie fahren aus einer Grundstücksausfahrt auf die Straße. Ein Fahrzeug kommt von links. Wer hat Vorfahrt?",
    answers: [t("Das Fahrzeug auf der Straße; wer aus einem Grundstück ausfährt, muss alle anderen durchfahren lassen"), f("Sie, weil Sie von rechts kommen", "Rechts vor links gilt nicht beim Einfahren aus Grundstücken."), f("Wer zuerst blinkt", "Blinken begründet keine Vorfahrt.")],
    explanation: "Wer aus einem Grundstück, einem verkehrsberuhigten Bereich, einer Fußgängerzone oder über einen abgesenkten Bordstein einfährt, muss sich so verhalten, dass jede Gefährdung ausgeschlossen ist, und alle anderen durchfahren lassen.",
    legalReference: "§ 10 StVO",
  }),
  q({
    code: "own-vorfahrt-004", topic: "vorfahrt", points: 5, difficulty: 0.3, tags: ["linksabbiegen", "gegenverkehr"],
    text: "Sie wollen an einer Kreuzung links abbiegen. Ein entgegenkommendes Fahrzeug fährt geradeaus. Wie verhalten Sie sich?",
    answers: [t("Warten und den Gegenverkehr durchfahren lassen"), f("Zügig abbiegen, weil Sie zuerst an der Kreuzung waren", "Wer links abbiegt, muss entgegenkommende Fahrzeuge durchfahren lassen."), f("Hupen, damit der Gegenverkehr wartet", "Hupen begründet keinen Vorrang.")],
    explanation: "Linksabbieger müssen entgegenkommende Fahrzeuge, die geradeaus fahren oder rechts abbiegen, durchfahren lassen. Das gilt unabhängig davon, wer zuerst an der Kreuzung war.",
    legalReference: "§ 9 Abs. 3 StVO",
  }),
  q({
    code: "own-vorfahrt-005", topic: "vorfahrt", points: 4, difficulty: 0.3, tags: ["einsatzfahrzeug", "blaulicht", "vorfahrt_beschildert"],
    text: "Sie fahren auf einer Vorfahrtstraße. Von links nähert sich ein Einsatzfahrzeug mit blauem Blinklicht und Einsatzhorn. Was gilt?",
    answers: [t("Sie müssen sofort freie Bahn schaffen, obwohl Sie auf der Vorfahrtstraße fahren"), f("Sie haben Vorfahrt und fahren weiter", "Blaulicht mit Einsatzhorn geht der Vorfahrtregelung vor."), f("Das Einsatzfahrzeug muss an der Kreuzung warten", "Alle anderen müssen dem Einsatzfahrzeug freie Bahn schaffen.")],
    explanation: "Blaues Blinklicht zusammen mit dem Einsatzhorn bedeutet: Alle übrigen Verkehrsteilnehmer haben sofort freie Bahn zu schaffen. Das gilt auch auf Vorfahrtstraßen und bei Grün an einer Ampel.",
    legalReference: "§ 38 Abs. 1 StVO",
  }),
  q({
    code: "own-vorfahrt-006", topic: "vorfahrt", points: 3, difficulty: 0.4, tags: ["abknickende_vorfahrt", "blinken", "vorfahrt_beschildert"],
    text: "Sie folgen dem Verlauf einer abknickenden Vorfahrtstraße. Müssen Sie blinken?",
    answers: [t("Ja, denn das Folgen der abknickenden Vorfahrtstraße ist ein Abbiegevorgang"), f("Nein, weil Sie auf der Vorfahrtstraße bleiben", "Auch auf der bevorrechtigten Straße ändert sich die Fahrtrichtung, daher ist zu blinken."), f("Nur wenn andere Fahrzeuge in der Nähe sind", "Die Blinkpflicht gilt immer.")],
    explanation: "Wer der abknickenden Vorfahrtstraße folgt, ändert die Fahrtrichtung und muss dies rechtzeitig und deutlich mit dem Fahrtrichtungsanzeiger ankündigen. Die Vorfahrt bleibt dabei erhalten.",
    legalReference: "§ 9 Abs. 1 StVO; Zeichen 306 mit Zusatzzeichen",
  }),
  q({
    code: "own-vorfahrt-007", topic: "vorfahrt", points: 5, difficulty: 0.5, tags: ["rechts_vor_links", "kreuzung"],
    text: "An einer Kreuzung mit rechts vor links kommen gleichzeitig ein Fahrzeug von rechts und ein Fahrzeug von links. Sie wollen geradeaus fahren. Was gilt?",
    answers: [t("Sie müssen das Fahrzeug von rechts durchfahren lassen; das Fahrzeug von links muss Sie durchfahren lassen"), f("Sie dürfen als Erster fahren, weil Sie geradeaus fahren", "Die Fahrtrichtung geradeaus begründet keine Vorfahrt."), f("Beide Fahrzeuge müssen Ihnen Vorfahrt gewähren", "Nur das Fahrzeug von links muss warten.")],
    explanation: "Bei rechts vor links hat jeder gegenüber dem Fahrzeug von links Vorfahrt und muss dem Fahrzeug von rechts Vorfahrt gewähren. Deshalb fährt zuerst das Fahrzeug von rechts, dann Sie, dann das Fahrzeug von links.",
    legalReference: "§ 8 Abs. 1 StVO",
  }),
  q({
    code: "own-vorfahrt-008", topic: "vorfahrt", points: 4, difficulty: 0.4, tags: ["feldweg", "ausserorts", "rechts_vor_links"],
    text: "Ein Fahrzeug kommt von rechts aus einem Feldweg auf die Landstraße. Wer hat Vorfahrt?",
    answers: [t("Sie auf der Landstraße; wer aus einem Feld- oder Waldweg kommt, hat keine Vorfahrt"), f("Das Fahrzeug aus dem Feldweg, weil es von rechts kommt", "Rechts vor links gilt nicht für Feld- und Waldwege."), f("Wer schneller ist", "Geschwindigkeit begründet keine Vorfahrt.")],
    explanation: "Wer aus einem Feld- oder Waldweg auf eine andere Straße einfährt, hat keine Vorfahrt, auch wenn er von rechts kommt. Die Regel rechts vor links gilt hier nicht.",
    legalReference: "§ 8 Abs. 1 Nr. 2 StVO",
  }),
  q({
    code: "own-vorfahrt-009", topic: "vorfahrt", points: 3, difficulty: 0.4, tags: ["verzicht", "verstaendigung"],
    text: "Ein vorfahrtberechtigter Fahrer bleibt stehen und winkt Sie deutlich durch. Was gilt?",
    answers: [t("Sie dürfen fahren, wenn die Verständigung eindeutig ist und niemand gefährdet wird"), f("Sie müssen fahren, weil der andere verzichtet hat", "Ein Verzicht verpflichtet Sie nicht; Sie bleiben verantwortlich für die sichere Weiterfahrt."), f("Ein Verzicht auf die Vorfahrt ist nicht möglich", "Verzicht ist möglich, aber nur bei eindeutiger Verständigung.")],
    explanation: "Auf die Vorfahrt kann verzichtet werden. Wer den Verzicht annimmt, darf nur bei eindeutiger Verständigung und ohne Gefährdung anderer fahren; die Verantwortung bleibt bei ihm.",
    legalReference: "§ 8 StVO; § 1 StVO",
  }),
  q({
    code: "own-vorfahrt-010", topic: "vorfahrt", points: 4, difficulty: 0.4, tags: ["ampel_ausgefallen", "vorfahrt_beschildert", "rechts_vor_links"],
    text: "Die Ampel an einer Kreuzung ist ausgefallen und bleibt dunkel. Wie ist die Vorfahrt geregelt?",
    answers: [t("Es gelten die aufgestellten Verkehrszeichen; gibt es keine, gilt rechts vor links"), f("Immer rechts vor links, unabhängig von Verkehrszeichen", "Vorhandene Verkehrszeichen gehen der Grundregel vor."), f("Wer zuerst an der Kreuzung ist, darf fahren", "Ankunftszeit regelt keine Vorfahrt.")],
    explanation: "Fällt eine Ampel aus, gelten die Verkehrszeichen an der Kreuzung. Sind keine vorhanden, greift die Grundregel rechts vor links.",
    legalReference: "§ 37 Abs. 1 StVO; § 8 StVO",
  }),
  q({
    code: "own-vorfahrt-011", topic: "vorfahrt", points: 5, difficulty: 0.4, tags: ["rechtsabbiegen", "radverkehr", "radweg"],
    text: "Sie wollen rechts abbiegen. Auf dem Radweg neben Ihnen fährt ein Radfahrer geradeaus weiter. Wie verhalten Sie sich?",
    answers: [t("Den Radfahrer durchfahren lassen, notfalls anhalten"), f("Zügig vor dem Radfahrer abbiegen", "Das ist die klassische Ursache schwerer Abbiegeunfälle."), f("Hupen, damit der Radfahrer wartet", "Der Radfahrer hat Vorrang.")],
    explanation: "Beim Abbiegen müssen Radfahrende, die auf oder neben der Fahrbahn in gleicher Richtung fahren, durchfahren gelassen werden. Vor dem Abbiegen ist der Schulterblick zwingend.",
    legalReference: "§ 9 Abs. 3 StVO",
  }),
  q({
    code: "own-vorfahrt-012", topic: "vorfahrt", points: 5, difficulty: 0.55, tags: ["rechts_vor_links", "kreuzung", "verstaendigung"],
    text: "An einer Kreuzung ohne Verkehrszeichen kommen Sie deutlich vor dem Fahrzeug von rechts an. Sie wollen geradeaus fahren. Was gilt?",
    answers: [t("Das Fahrzeug von rechts hat Vorfahrt, auch wenn Sie zuerst da waren"), t("Sie dürfen nur fahren, wenn Sie die Kreuzung räumen können, ohne das Fahrzeug von rechts wesentlich zu behindern"), f("Wer zuerst an der Kreuzung ankommt, darf zuerst fahren", "Die Ankunftsreihenfolge spielt bei der Vorfahrt keine Rolle."), f("Sie haben Vorfahrt, weil Sie geradeaus fahren", "Die Fahrtrichtung begründet keine Vorfahrt.")],
    explanation: "Rechts vor links gilt unabhängig davon, wer zuerst ankommt. Wer wartepflichtig ist, darf nur fahren, wenn der Vorfahrtberechtigte weder gefährdet noch wesentlich behindert wird. Ist das Fahrzeug von rechts noch weit entfernt, dürfen Sie also fahren.",
    legalReference: "§ 8 Abs. 1 und 2 StVO",
  }),
  q({
    code: "own-vorfahrt-013", topic: "vorfahrt", points: 5, difficulty: 0.6, tags: ["rechts_vor_links", "einmuendung", "linksabbiegen"],
    text: "Sie fahren auf der durchgehenden Straße an einer T-Einmündung ohne Verkehrszeichen. Das Fahrzeug aus der Einmündung rechts von Ihnen blinkt links und will in Ihre Gegenrichtung abbiegen. Wer fährt zuerst?",
    answers: [t("Das Fahrzeug aus der Einmündung, weil es von rechts kommt"), f("Sie, weil das andere Fahrzeug Ihre Fahrbahn kreuzen muss", "Das Kreuzen der Fahrbahn ändert nichts an der Vorfahrt von rechts."), f("Sie, weil die durchgehende Straße Vorrang hat", "Ohne Verkehrszeichen hat die durchgehende Straße keinen Vorrang."), f("Wer zuerst da war", "Die Ankunftsreihenfolge regelt keine Vorfahrt.")],
    explanation: "Ohne Verkehrszeichen gilt an T-Einmündungen rechts vor links. Das Fahrzeug aus der Einmündung rechts hat Vorfahrt, auch wenn es Ihre Fahrbahn kreuzt, um nach links abzubiegen.",
    legalReference: "§ 8 Abs. 1 StVO",
  }),
  q({
    code: "own-vorfahrt-014", topic: "vorfahrt", points: 4, difficulty: 0.6, tags: ["grundstuecksausfahrt", "einfahren", "fussgaenger", "radverkehr"],
    text: "Sie fahren aus einer Grundstücksausfahrt über den Gehweg auf die Straße. Wem müssen Sie den Vorrang lassen?",
    answers: [t("Fußgängern auf dem Gehweg"), t("Radfahrenden auf dem Radweg"), t("Fahrzeugen auf der Fahrbahn, egal aus welcher Richtung"), f("Niemandem, wenn Sie nach rechts abbiegen", "Beim Einfahren aus einem Grundstück sind alle anderen durchzulassen, unabhängig von der Abbiegerichtung.")],
    explanation: "Wer aus einem Grundstück einfährt, muss jede Gefährdung anderer ausschließen. Das gilt für Fußgänger und Radfahrende auf Gehweg und Radweg ebenso wie für den Fahrzeugverkehr auf der Fahrbahn aus beiden Richtungen. Bei unübersichtlichen Ausfahrten ist ein Einweiser sinnvoll.",
    legalReference: "§ 10 StVO",
  }),
  q({
    code: "own-vorfahrt-015", topic: "vorfahrt", points: 5, difficulty: 0.65, tags: ["linksabbiegen", "gegenverkehr", "kreuzung", "einordnen"],
    text: "Sie wollen an einer Kreuzung ohne Ampel links abbiegen und müssen den Gegenverkehr durchfahren lassen. Dürfen Sie zum Warten bereits in die Kreuzung einfahren?",
    answers: [t("Ja, Sie dürfen bis zur Kreuzungsmitte vorfahren und dort warten, sofern Sie niemanden behindern"), t("Sie müssen dabei die Räder gerade halten, damit Sie bei einem Auffahrunfall nicht in den Gegenverkehr geschoben werden"), f("Nein, Sie müssen vor der Kreuzung warten, bis die Gegenfahrbahn frei ist", "Das Einfahren in die Kreuzung zum Warten ist erlaubt und erleichtert den Verkehrsfluss."), f("Sie dürfen den Gegenverkehr zwingen zu warten, sobald Sie in der Kreuzung stehen", "Der Gegenverkehr behält seinen Vorrang.")],
    explanation: "Linksabbieger dürfen in die Kreuzung einfahren und dort auf eine Lücke im Gegenverkehr warten, wenn sie niemanden behindern. Dabei sollten die Räder geradeaus stehen, damit das Fahrzeug bei einem Auffahrunfall nicht in den Gegenverkehr gedrückt wird.",
    legalReference: "§ 9 Abs. 3 StVO",
  }),
  q({
    code: "own-vorfahrt-016", topic: "vorfahrt", points: 4, difficulty: 0.7, tags: ["einsatzfahrzeug", "blaulicht", "vorfahrt_beschildert"],
    text: "Sie fahren auf einer Vorfahrtstraße. Von links nähert sich ein Einsatzfahrzeug mit blauem Blinklicht, aber ohne Einsatzhorn. Was gilt?",
    answers: [t("Sie behalten die Vorfahrt; nur Blaulicht zusammen mit Einsatzhorn verpflichtet, freie Bahn zu schaffen"), t("Blaues Blinklicht allein warnt vor Unfall- oder Einsatzstellen oder kündigt ein Fahrzeug an, das begleitet wird; Vorsicht ist geboten"), f("Sie müssen anhalten und das Einsatzfahrzeug durchlassen", "Ohne Einsatzhorn besteht kein Wegerecht."), f("Das Einsatzfahrzeug darf bei Blaulicht ohne Horn Vorfahrtregeln missachten", "Sonderrechte am Einsatzort ändern nichts daran, dass Wegerecht nur mit Horn besteht.")],
    explanation: "Wegerecht besteht nur bei blauem Blinklicht zusammen mit dem Einsatzhorn. Blaulicht allein weist auf Unfall- und Einsatzstellen oder begleitete Fahrzeuge hin und mahnt zur Vorsicht, ändert aber die Vorfahrt nicht. Trotzdem sollte man vorausschauend fahren und im Zweifel Rücksicht nehmen.",
    legalReference: "§ 38 Abs. 1 und 2 StVO",
  }),
  q({
    code: "own-vorfahrt-017", topic: "vorfahrt", points: 5, difficulty: 0.8, tags: ["abknickende_vorfahrt", "vorfahrt_beschildert", "linksabbiegen", "gegenverkehr"],
    text: "Sie folgen der nach links abknickenden Vorfahrtstraße. Ihnen kommt auf der Vorfahrtstraße ein Fahrzeug entgegen, das geradeaus in die nicht bevorrechtigte Straße weiterfahren will. Wer muss warten?",
    answers: [t("Sie, weil Sie nach links abbiegen und der Gegenverkehr auf der Vorfahrtstraße durchfahren gelassen werden muss"), f("Das entgegenkommende Fahrzeug, weil es die Vorfahrtstraße verlässt", "Beide befinden sich auf der Vorfahrtstraße; zwischen ihnen gilt die Abbiegeregel."), f("Niemand, beide dürfen gleichzeitig fahren", "Ihre Fahrlinien kreuzen sich; als Linksabbieger müssen Sie warten."), f("Das entgegenkommende Fahrzeug, weil es geradeaus fährt und rechts vor links gilt", "Rechts vor links gilt hier nicht; es handelt sich um eine beschilderte Vorfahrt.")],
    explanation: "Beide Fahrzeuge kommen von der Vorfahrtstraße und sind gegenüber den anderen Straßen bevorrechtigt. Untereinander gilt aber die Abbiegeregel: Wer der Vorfahrtstraße nach links folgt, biegt links ab und muss den Gegenverkehr auf der Vorfahrtstraße durchfahren lassen, auch wenn dieser sie geradeaus verlässt.",
    legalReference: "§ 9 Abs. 3 StVO; Zeichen 306 mit Zusatzzeichen 1002",
  }),
  q({
    code: "own-vorfahrt-018", topic: "vorfahrt", points: 5, difficulty: 0.65, tags: ["rechts_vor_links", "kreuzung"],
    text: "An einer Kreuzung mit rechts vor links kommen gleichzeitig ein Fahrzeug von rechts und ein Fahrzeug von links. Alle wollen geradeaus. Welche Aussagen sind richtig?",
    answers: [t("Sie müssen dem Fahrzeug von rechts Vorfahrt gewähren"), t("Das Fahrzeug von links muss Ihnen Vorfahrt gewähren"), t("Das Fahrzeug von links fährt als Letztes"), f("Das Fahrzeug von rechts muss dem Fahrzeug von links Vorfahrt gewähren", "Aus Sicht des Fahrzeugs von rechts kommt das Fahrzeug von links von links; es muss also nicht warten.")],
    explanation: "Bei rechts vor links betrachtet jeder das Fahrzeug zu seiner Rechten: Das Fahrzeug von rechts fährt zuerst, dann Sie, dann das Fahrzeug von links. Kommen alle drei gleichzeitig, ist die Reihenfolge damit eindeutig.",
    legalReference: "§ 8 Abs. 1 StVO",
  }),
  q({
    code: "own-vorfahrt-019", topic: "vorfahrt", points: 4, difficulty: 0.6, tags: ["feldweg", "ausserorts", "rechts_vor_links", "defensiv"],
    text: "Von rechts kommt ein Fahrzeug aus einem Feldweg und fährt bereits auf die Landstraße, obwohl Sie Vorfahrt haben. Wie verhalten Sie sich?",
    answers: [t("Bremsbereit sein und die Geschwindigkeit verringern, notfalls anhalten"), t("Auf die eigene Vorfahrt verzichten, um einen Unfall zu vermeiden"), f("Auf der Vorfahrt bestehen und mit unveränderter Geschwindigkeit weiterfahren", "Wer auf sein Recht besteht und einen Unfall verursacht, kann mithaften."), f("Hupen und knapp vorbeifahren", "Das gefährdet beide und ist unzulässig.")],
    explanation: "Wer aus einem Feldweg kommt, hat keine Vorfahrt. Trotzdem gilt § 1 StVO: Wer eine drohende Gefahr erkennt, muss reagieren. Auf die Vorfahrt zu bestehen und einen vermeidbaren Unfall zu riskieren, ist verkehrswidrig.",
    legalReference: "§ 8 Abs. 1 Nr. 2 StVO; § 1 Abs. 2 StVO",
  }),
  q({
    code: "own-vorfahrt-020", topic: "vorfahrt", points: 5, difficulty: 0.65, tags: ["ampel_ausgefallen", "vorfahrt_beschildert", "gelbes_blinklicht"],
    text: "An einer Kreuzung blinkt die Ampel nur noch gelb. An Ihrer Zufahrt steht das Zeichen 205. Von links kommt ein Fahrzeug auf der Vorfahrtstraße. Was gilt?",
    answers: [t("Sie müssen dem Fahrzeug von links Vorfahrt gewähren, weil das Zeichen 205 gilt"), t("Gelbes Blinklicht bedeutet: Die Ampel regelt nicht; es gelten die Verkehrszeichen"), f("Es gilt rechts vor links, weil die Ampel nicht funktioniert", "Rechts vor links gilt nur, wenn auch keine Verkehrszeichen aufgestellt sind."), f("Gelbes Blinklicht bedeutet für Sie freie Fahrt", "Gelbes Blinklicht ist nur ein Warnsignal.")],
    explanation: "Blinkt eine Ampel gelb, ist sie außer Betrieb; es gelten die Verkehrszeichen. Mit Zeichen 205 an Ihrer Zufahrt sind Sie wartepflichtig gegenüber dem Verkehr auf der Vorfahrtstraße, egal aus welcher Richtung er kommt.",
    legalReference: "§ 37 Abs. 1 StVO; § 38 Abs. 3 StVO; Zeichen 205",
  }),
  q({
    code: "own-vorfahrt-021", topic: "vorfahrt", points: 5, difficulty: 0.6, tags: ["rechtsabbiegen", "radverkehr", "radweg", "schulterblick"],
    text: "Sie wollen rechts abbiegen und haben bereits geblinkt. Auf dem Radweg neben Ihnen nähert sich von hinten schnell ein Radfahrer, der geradeaus weiterfahren will. Was gilt?",
    answers: [t("Sie müssen den Radfahrer durchfahren lassen, auch wenn er von hinten kommt und Sie vor ihm geblinkt haben"), t("Der Schulterblick unmittelbar vor dem Abbiegen ist zwingend, weil Radfahrer im toten Winkel leicht übersehen werden"), f("Der Radfahrer muss warten, weil Sie den Blinker gesetzt haben", "Der Blinker begründet keinen Vorrang gegenüber dem geradeaus fahrenden Radverkehr."), f("Der Radfahrer muss warten, weil er von hinten kommt", "Radfahrende, die in gleicher Richtung geradeaus fahren, sind beim Abbiegen durchzulassen.")],
    explanation: "Radfahrende, die auf oder neben der Fahrbahn in gleicher Richtung geradeaus fahren, haben beim Abbiegen Vorrang, auch wenn sie von hinten kommen. Blinken ändert daran nichts. Spiegel und Schulterblick sind Pflicht.",
    legalReference: "§ 9 Abs. 3 StVO",
  }),
  q({
    code: "own-vorfahrt-022", topic: "vorfahrt", points: 5, difficulty: 0.7, tags: ["vorfahrt_beschildert", "linksabbiegen", "gegenverkehr", "vorfahrtstrasse"],
    text: "Sie fahren auf einer Vorfahrtstraße (Zeichen 306) und wollen links abbiegen. Ihnen kommt auf der Vorfahrtstraße ein Fahrzeug entgegen, das geradeaus fährt. Von rechts wartet ein Fahrzeug an Zeichen 205. In welcher Reihenfolge wird gefahren?",
    answers: [t("Zuerst das entgegenkommende Fahrzeug, dann Sie, zuletzt das Fahrzeug von rechts"), f("Zuerst Sie, weil Sie auf der Vorfahrtstraße sind, dann der Gegenverkehr", "Als Linksabbieger müssen Sie den Gegenverkehr durchfahren lassen."), f("Zuerst das Fahrzeug von rechts, weil rechts vor links gilt", "Das Fahrzeug von rechts steht an Zeichen 205 und muss beiden Fahrzeugen auf der Vorfahrtstraße Vorfahrt gewähren."), f("Alle drei können gleichzeitig fahren", "Die Fahrlinien kreuzen sich; es ist nacheinander zu fahren.")],
    explanation: "Beide Fahrzeuge auf der Vorfahrtstraße sind gegenüber dem Fahrzeug an Zeichen 205 bevorrechtigt. Untereinander gilt: Der Linksabbieger lässt den Gegenverkehr durchfahren. Also fährt zuerst das entgegenkommende Fahrzeug, dann Sie, zuletzt das Fahrzeug von rechts.",
    legalReference: "§ 8 Abs. 1 StVO; § 9 Abs. 3 StVO",
  }),
  q({
    code: "own-vorfahrt-023", topic: "vorfahrt", points: 4, difficulty: 0.6, tags: ["vorfahrt_beschildert", "ende_vorfahrtstrasse", "rechts_vor_links"],
    text: "Sie passieren das Zeichen 307 (Ende der Vorfahrtstraße). Was gilt an der nächsten Kreuzung?",
    answers: [t("Es gilt die Regelung der dort aufgestellten Zeichen; sind keine vorhanden, gilt rechts vor links"), f("Sie müssen an der nächsten Kreuzung in jedem Fall anhalten", "Eine Anhaltepflicht besteht nur bei Zeichen 206 oder wenn es die Verkehrslage erfordert."), f("Sie haben an der nächsten Kreuzung noch einmal Vorfahrt", "Mit dem Zeichen 307 endet die Bevorrechtigung.")],
    explanation: "Zeichen 307 hebt die Vorfahrtstraße auf. Ab hier gelten wieder die allgemeinen Regeln: Verkehrszeichen an der nächsten Kreuzung oder, wenn keine vorhanden sind, rechts vor links. Aufmerksamkeit ist besonders wichtig, weil man an die Bevorrechtigung gewöhnt ist.",
    legalReference: "§ 42 StVO, Anlage 3 (Zeichen 307); § 8 Abs. 1 StVO",
  }),
  q({
    code: "own-vorfahrt-024", topic: "vorfahrt", points: 4, difficulty: 0.55, tags: ["rechts_vor_links", "gefahrzeichen", "kreuzung"],
    text: "Sie sehen das Gefahrzeichen 102 (Kreuzung mit Vorfahrt von rechts). Was bedeutet das für die nächste Kreuzung?",
    answers: [t("Dort gilt rechts vor links; das Zeichen warnt, weil die Kreuzung schwer erkennbar ist oder die Regelung dort unerwartet gilt"), t("Sie müssen die Geschwindigkeit so anpassen, dass Sie einem Fahrzeug von rechts Vorfahrt gewähren können"), f("Sie haben an der nächsten Kreuzung Vorfahrt", "Das Zeichen weist auf die Vorfahrt des Verkehrs von rechts hin."), f("Nur der Verkehr von rechts muss aufpassen", "Das Zeichen richtet sich an Sie: Sie müssen Vorfahrt gewähren.")],
    explanation: "Zeichen 102 kündigt eine Kreuzung oder Einmündung an, an der rechts vor links gilt. Es steht dort, wo die Regelung überraschend ist, etwa nach einer langen Vorfahrtstraße oder bei schlechter Erkennbarkeit der Einmündung.",
    legalReference: "§ 40 StVO, Anlage 1 (Zeichen 102); § 8 Abs. 1 StVO",
  }),
  q({
    code: "own-vorfahrt-025", topic: "vorfahrt", points: 5, difficulty: 0.7, tags: ["stoppschild", "vorfahrt_beschildert", "haltlinie", "halten"],
    text: "Am Stoppschild (Zeichen 206) ist eine Haltlinie markiert. Von der Haltlinie aus können Sie die Kreuzung wegen einer Hecke nicht einsehen. Was ist richtig?",
    answers: [t("Sie müssen an der Haltlinie anhalten"), t("Anschließend tasten Sie sich langsam bis zur Sichtlinie vor und halten dort erneut, wenn es die Verkehrslage erfordert"), f("Sie dürfen ohne Halt an der Haltlinie bis zur Sichtlinie vorfahren, weil Sie dort ohnehin halten", "Das Anhalten an der Haltlinie ist immer Pflicht."), f("Sie dürfen zügig in die Kreuzung einfahren, weil Sie an der Haltlinie gehalten haben", "Das Halten an der Haltlinie ersetzt nicht das Gewähren der Vorfahrt.")],
    explanation: "Am Stoppschild wird zuerst an der Haltlinie angehalten. Reicht die Sicht dort nicht aus, wird langsam bis zur Sichtlinie vorgefahren und bei Bedarf erneut angehalten. Die Vorfahrt der anderen bleibt in jedem Fall zu beachten.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 206); § 8 Abs. 2 StVO",
  }),
  q({
    code: "own-vorfahrt-026", topic: "vorfahrt", points: 4, difficulty: 0.6, tags: ["engstelle", "gegenverkehr", "vorfahrt_beschildert"],
    text: "Vor einer Engstelle steht das Zeichen 208 (Dem Gegenverkehr Vorrang gewähren). Es ist kein Gegenverkehr zu sehen. Dürfen Sie durchfahren?",
    answers: [t("Ja, Sie müssen nur warten, wenn Gegenverkehr kommt oder sich bereits in der Engstelle befindet"), f("Nein, Sie müssen immer anhalten und die Engstelle beobachten", "Eine Anhaltepflicht besteht nur, wenn Gegenverkehr das Durchfahren verlangt."), f("Ja, und Sie haben in der Engstelle gegenüber später einfahrendem Gegenverkehr Vorrang, weil Sie zuerst drin waren", "Wer bereits in der Engstelle ist, darf sie zwar beenden, das Zeichen bleibt aber eine Wartepflicht bei Gegenverkehr.")],
    explanation: "Zeichen 208 verpflichtet zum Warten, wenn Gegenverkehr die Engstelle benutzen will. Ist die Engstelle frei und kein Gegenverkehr in Sicht, darf ohne Anhalten durchgefahren werden. Auf der Gegenseite steht Zeichen 308.",
    legalReference: "§ 41 StVO, Anlage 2 (Zeichen 208)",
  }),
  q({
    code: "own-vorfahrt-027", topic: "vorfahrt", points: 4, difficulty: 0.65, tags: ["engstelle", "gegenverkehr", "vorfahrt_beschildert"],
    text: "Vor einer Engstelle steht für Sie das Zeichen 308 (Vorrang vor dem Gegenverkehr). Ein entgegenkommender Lkw ist bereits in die Engstelle eingefahren. Was gilt?",
    answers: [t("Sie müssen warten, bis der Lkw die Engstelle verlassen hat, obwohl Sie Vorrang haben"), f("Der Lkw muss zurücksetzen, weil Sie Vorrang haben", "Wer bereits in der Engstelle ist, darf sie durchfahren; Rückwärtsfahren wäre gefährlich."), f("Sie dürfen in die Engstelle einfahren und der Lkw muss ausweichen", "In einer Engstelle ist Ausweichen nicht möglich; das führt zum Stillstand oder Unfall.")],
    explanation: "Das Zeichen 308 gibt Ihnen Vorrang beim Einfahren in die Engstelle. Befindet sich aber schon ein Fahrzeug in der Engstelle, muss es sie durchfahren dürfen. Vorrang bedeutet nicht, dass andere zurücksetzen müssen.",
    legalReference: "§ 42 StVO, Anlage 3 (Zeichen 308); § 1 StVO",
  }),
  q({
    code: "own-vorfahrt-028", topic: "vorfahrt", points: 5, difficulty: 0.55, tags: ["vorfahrt_beschildert", "kreisverkehr", "einfahren"],
    text: "Sie sind an Zeichen 215 mit Zeichen 205 in einen Kreisverkehr eingefahren und fahren im Kreis. An der nächsten Zufahrt will ein Fahrzeug einfahren. Wer hat Vorfahrt?",
    answers: [t("Sie, weil an allen Zufahrten Zeichen 205 steht und der Verkehr im Kreis Vorfahrt hat"), f("Das einfahrende Fahrzeug, weil es von rechts kommt", "Rechts vor links gilt im beschilderten Kreisverkehr nicht."), f("Wer zuerst blinkt", "Beim Einfahren wird nicht geblinkt; Blinken begründet keine Vorfahrt.")],
    explanation: "Im beschilderten Kreisverkehr (Zeichen 215 mit Zeichen 205) hat der Verkehr auf der Kreisfahrbahn Vorfahrt vor allen Einfahrenden. Wer im Kreis fährt, muss aber Fußgänger und Radfahrende beim Ausfahren beachten.",
    legalReference: "§ 8 Abs. 1a StVO; Zeichen 215 und 205",
  }),
  q({
    code: "own-vorfahrt-029", topic: "vorfahrt", points: 5, difficulty: 0.6, tags: ["linksabbiegen", "gegenverkehr", "kreuzung"],
    text: "Sie und ein entgegenkommendes Fahrzeug wollen beide an derselben Kreuzung links abbiegen. Muss einer von Ihnen dem anderen die Vorfahrt gewähren?",
    answers: [t("Nein, beide können voreinander abbiegen, weil sich ihre Fahrlinien dabei nicht kreuzen"), t("Vor dem Abbiegen müssen beide auf Fußgänger und Radfahrende in der Straße achten, in die sie einbiegen"), f("Ja, Sie müssen warten, weil Linksabbieger dem Gegenverkehr Vorrang geben müssen", "Das gilt nur gegenüber Gegenverkehr, der geradeaus fährt oder rechts abbiegt."), f("Ja, das Fahrzeug, das zuerst blinkt, hat Vorrang", "Blinken begründet keinen Vorrang.")],
    explanation: "Zwei entgegenkommende Linksabbieger biegen voreinander ab; ihre Wege kreuzen sich nicht, sodass keiner warten muss. Nur wenn Markierungen oder die Verkehrsführung es vorsehen, wird hintereinander abgebogen. Fußgänger und Radfahrende in der Zielstraße sind durchzulassen.",
    legalReference: "§ 9 Abs. 3 und 4 StVO",
  }),
  q({
    code: "own-vorfahrt-030", topic: "vorfahrt", points: 5, difficulty: 0.6, tags: ["bahnuebergang", "andreaskreuz", "vorfahrt_beschildert", "schienenverkehr"],
    text: "Sie fahren auf einer Vorfahrtstraße auf einen Bahnübergang mit Andreaskreuz zu. Von rechts nähert sich eine Eisenbahn. Was gilt?",
    answers: [t("Der Schienenverkehr hat Vorrang, auch wenn Sie auf einer Vorfahrtstraße fahren"), t("Sie müssen vor dem Andreaskreuz warten und dürfen den Übergang nicht mehr befahren"), f("Sie haben Vorfahrt, weil Sie auf der Vorfahrtstraße fahren", "Das Andreaskreuz ordnet den Vorrang des Schienenverkehrs an, unabhängig von der Straßenvorfahrt."), f("Der Zug muss anhalten, weil Sie von links kommen", "Rechts vor links gilt für Bahnübergänge nicht.")],
    explanation: "Das Andreaskreuz zeigt an, dass Schienenfahrzeuge Vorrang haben. Das gilt unabhängig davon, ob die Straße bevorrechtigt ist. Wer sich einem Bahnübergang nähert, muss mit mäßiger Geschwindigkeit fahren und vor dem Andreaskreuz warten, wenn sich ein Zug nähert.",
    legalReference: "§ 19 Abs. 1 und 2 StVO; Zeichen 201",
  }),
  q({
    code: "own-vorfahrt-031", topic: "vorfahrt", points: 5, difficulty: 0.6, tags: ["fussgaengerueberweg", "zebrastreifen", "vorrang", "halten"],
    text: "Sie fahren auf einer Vorfahrtstraße auf einen Zebrastreifen zu. Eine Person steht am Rand und will erkennbar hinübergehen. Was gilt?",
    answers: [t("Die Person hat Vorrang; Sie müssen sich mit mäßiger Geschwindigkeit nähern und warten"), t("Sie dürfen vor dem Zebrastreifen nicht überholen"), f("Sie haben Vorrang, weil Sie auf der Vorfahrtstraße fahren", "Die Vorfahrtstraße regelt nur den Fahrzeugverkehr; am Zebrastreifen haben Fußgänger Vorrang."), f("Sie dürfen weiterfahren, solange die Person noch nicht auf der Fahrbahn ist", "Der Vorrang gilt bereits, wenn erkennbar ist, dass die Person hinüber will.")],
    explanation: "Am Fußgängerüberweg haben Fußgänger Vorrang, die ihn erkennbar benutzen wollen. Die Vorfahrtstraße ändert daran nichts. Fahrzeuge müssen sich mit mäßiger Geschwindigkeit nähern, dürfen dort nicht überholen und müssen nötigenfalls anhalten.",
    legalReference: "§ 26 Abs. 1 und 3 StVO",
  }),
  q({
    code: "own-vorfahrt-032", topic: "vorfahrt", points: 5, difficulty: 0.65, tags: ["vorfahrt_beschildert", "linksabbiegen", "gegenverkehr"],
    text: "Vor einer Kreuzung steht das Zeichen 301 (Vorfahrt). Sie wollen links abbiegen; aus der Gegenrichtung kommt ein Fahrzeug, das geradeaus fährt. Was gilt?",
    answers: [t("Sie müssen den Gegenverkehr durchfahren lassen, obwohl Sie an dieser Kreuzung Vorfahrt haben"), t("Gegenüber den Fahrzeugen aus den Seitenstraßen sind Sie bevorrechtigt"), f("Sie dürfen vor dem Gegenverkehr abbiegen, weil Zeichen 301 Ihnen Vorfahrt gibt", "Zeichen 301 regelt die Vorfahrt gegenüber den kreuzenden Straßen, nicht das Verhältnis zum Gegenverkehr."), f("Zeichen 301 gilt für die ganze Straße bis zum Aufhebungszeichen", "Das gilt nur für die Vorfahrtstraße mit Zeichen 306.")],
    explanation: "Zeichen 301 gewährt Vorfahrt an der nächsten Kreuzung gegenüber den einmündenden Straßen. Der Gegenverkehr kommt ebenfalls von der bevorrechtigten Straße; als Linksabbieger müssen Sie ihn durchfahren lassen.",
    legalReference: "§ 42 StVO, Anlage 3 (Zeichen 301); § 9 Abs. 3 StVO",
  }),
  q({
    code: "own-vorfahrt-033", topic: "vorfahrt", points: 5, difficulty: 0.75, tags: ["abknickende_vorfahrt", "vorfahrt_beschildert", "geradeaus"],
    text: "Das Zeichen 306 mit Zusatzzeichen zeigt: Die Vorfahrtstraße knickt nach links ab. Sie wollen geradeaus in die nicht bevorrechtigte Straße weiterfahren. Was gilt?",
    answers: [t("Gegenüber Fahrzeugen aus der nicht bevorrechtigten Straße haben Sie Vorfahrt"), t("Sie müssen entgegenkommende Fahrzeuge auf der Vorfahrtstraße, die der Vorfahrtstraße nach rechts folgen, nicht durchfahren lassen, weil sich Ihre Wege beim Rechtsabbiegen nicht kreuzen"), t("Sie müssen nicht blinken, weil Sie geradeaus fahren"), f("Sie müssen allen Fahrzeugen Vorfahrt gewähren, weil Sie die Vorfahrtstraße verlassen", "Wer geradeaus die Vorfahrtstraße verlässt, bleibt gegenüber den untergeordneten Straßen bevorrechtigt.")],
    explanation: "Wer die abknickende Vorfahrtstraße geradeaus verlässt, bleibt gegenüber der untergeordneten Straße bevorrechtigt und blinkt nicht. Gegenverkehr, der der Vorfahrtstraße nach rechts folgt, kreuzt Ihren Weg nicht. Nur ein Linksabbieger auf der Vorfahrtstraße müsste Sie durchfahren lassen.",
    legalReference: "§ 8 Abs. 1 StVO; § 9 Abs. 1 und 3 StVO; Zeichen 306 mit Zusatzzeichen 1002",
  }),
  q({
    code: "own-vorfahrt-034", topic: "vorfahrt", points: 5, difficulty: 0.6, tags: ["rechts_vor_links", "kreuzung", "unuebersichtlich"],
    text: "An einer Kreuzung mit rechts vor links ist die Straße von rechts durch eine hohe Hecke nicht einsehbar. Wie verhalten Sie sich?",
    answers: [t("Langsam bis zur Sichtlinie vortasten und nur weiterfahren, wenn kein Fahrzeug von rechts kommt"), t("Bremsbereit sein und die Geschwindigkeit deutlich verringern"), f("Mit unveränderter Geschwindigkeit weiterfahren, weil die anderen Sie sehen müssen", "Sie müssen dem Verkehr von rechts Vorfahrt gewähren und dazu die Einmündung einsehen können."), f("Hupen und zügig durchfahren", "Hupen ersetzt weder Sicht noch Vorfahrt.")],
    explanation: "Wer wartepflichtig ist, muss sich Sicht verschaffen. An unübersichtlichen Kreuzungen wird deshalb langsam bis zur Sichtlinie vorgetastet. Nur wenn sicher ist, dass niemand von rechts kommt, darf weitergefahren werden.",
    legalReference: "§ 8 Abs. 2 StVO",
  }),
  q({
    code: "own-vorfahrt-035", topic: "vorfahrt", points: 5, difficulty: 0.65, tags: ["rechts_vor_links", "einmuendung", "wartepflicht"],
    text: "Sie sind an einer Einmündung gegenüber einem Fahrzeug von rechts wartepflichtig. Das Fahrzeug ist noch etwa 100 Meter entfernt. Dürfen Sie fahren?",
    answers: [t("Ja, wenn Sie die Einmündung räumen können, ohne das Fahrzeug von rechts zu gefährden oder wesentlich zu behindern"), t("Im Zweifel müssen Sie warten, weil Geschwindigkeit und Entfernung schwer einzuschätzen sind"), f("Nein, wartepflichtige Fahrzeuge müssen immer anhalten, bis die Straße völlig frei ist", "Die Wartepflicht verlangt nur, dass der Berechtigte nicht gefährdet oder wesentlich behindert wird."), f("Ja, weil Sie zuerst da sind", "Die Ankunftsreihenfolge spielt keine Rolle.")],
    explanation: "Wer die Vorfahrt zu beachten hat, darf nur weiterfahren, wenn der Berechtigte weder gefährdet noch wesentlich behindert wird. Bei ausreichender Entfernung ist das möglich, bei Unsicherheit ist Warten Pflicht.",
    legalReference: "§ 8 Abs. 2 StVO",
  }),
  q({
    code: "own-vorfahrt-036", topic: "vorfahrt", points: 4, difficulty: 0.6, tags: ["einsatzfahrzeug", "blaulicht", "innerorts", "freie_bahn"],
    text: "Innerorts nähert sich hinter Ihnen ein Einsatzfahrzeug mit Blaulicht und Einsatzhorn. Wie schaffen Sie richtig freie Bahn?",
    answers: [t("Nach rechts ausweichen und die Geschwindigkeit verringern oder am rechten Rand anhalten"), t("Die Absicht durch Blinken ankündigen und nicht abrupt bremsen"), t("Nicht mitten in einer Kreuzung anhalten, sondern die Kreuzung erst räumen"), f("Sofort auf der Fahrbahn stehen bleiben, wo Sie gerade sind", "Ein plötzlicher Stopp mitten auf der Fahrbahn blockiert das Einsatzfahrzeug und gefährdet den nachfolgenden Verkehr.")],
    explanation: "Freie Bahn schaffen bedeutet: rechts ranfahren, Geschwindigkeit verringern oder anhalten, dabei blinken und nicht unvermittelt bremsen. In einer Kreuzung wird nicht angehalten, sondern sie wird zügig geräumt.",
    legalReference: "§ 38 Abs. 1 StVO",
  }),
  q({
    code: "own-vorfahrt-037", topic: "vorfahrt", points: 4, difficulty: 0.65, tags: ["grundstuecksausfahrt", "einfahren", "abgesenkter_bordstein"],
    text: "Sie fahren von einem Supermarktparkplatz über einen abgesenkten Bordstein auf die Straße. Die Ausfahrt ist breit und asphaltiert wie eine Straße. Gilt hier rechts vor links?",
    answers: [t("Nein, wer über einen abgesenkten Bordstein auf die Fahrbahn fährt, muss alle anderen durchfahren lassen"), f("Ja, weil die Ausfahrt wie eine Straße gebaut ist", "Der abgesenkte Bordstein zeigt, dass es sich um eine Grundstücksausfahrt handelt."), f("Ja, aber nur gegenüber Fahrzeugen von links", "Rechts vor links gilt hier gar nicht.")],
    explanation: "Wer aus einem Grundstück oder über einen abgesenkten Bordstein auf die Straße fährt, muss jede Gefährdung ausschließen und alle anderen durchfahren lassen. Die Breite oder der Belag der Ausfahrt spielen keine Rolle.",
    legalReference: "§ 10 StVO",
  }),
  q({
    code: "own-vorfahrt-038", topic: "vorfahrt", points: 5, difficulty: 0.55, tags: ["rechts_vor_links", "kreuzung", "defensiv"],
    text: "An einer Kreuzung mit rechts vor links fährt das Fahrzeug von links an, obwohl es Ihnen Vorfahrt gewähren müsste. Wie verhalten Sie sich?",
    answers: [t("Anhalten oder abbremsen und den Fehler des anderen ausgleichen"), f("Auf der Vorfahrt bestehen und weiterfahren; bei einem Unfall trägt der andere die volle Schuld", "Wer einen erkennbaren Fehler nicht ausgleicht, kann mithaften und riskiert einen Unfall."), f("Hupen und beschleunigen, damit der andere zurückweicht", "Das erhöht die Unfallgefahr.")],
    explanation: "Vorfahrt ist kein Recht, das um jeden Preis durchgesetzt werden darf. Wer erkennt, dass ein anderer seine Wartepflicht missachtet, muss reagieren und den Unfall vermeiden.",
    legalReference: "§ 1 Abs. 2 StVO; § 8 StVO",
  }),
  q({
    code: "own-vorfahrt-039", topic: "vorfahrt", points: 5, difficulty: 0.7, tags: ["vorfahrt_beschildert", "blinken", "vertrauen", "ampel_ausgefallen"],
    text: "Sie stehen mit Zeichen 205 an einer Kreuzung, deren Ampel ausgefallen ist. Von links nähert sich auf der Vorfahrtstraße ein Fahrzeug, das rechts blinkt und offenbar in Ihre Straße abbiegen will. Dürfen Sie losfahren?",
    answers: [t("Erst wenn das Fahrzeug erkennbar abbiegt, zum Beispiel durch deutliche Verlangsamung und Einlenken"), f("Ja, sofort, weil der Blinker das Abbiegen ankündigt", "Auf den Blinker allein darf nicht vertraut werden; er kann irrtümlich gesetzt sein."), f("Nein, Sie müssen in jedem Fall warten, bis das Fahrzeug abgebogen ist", "Sie dürfen fahren, sobald das Abbiegen eindeutig erkennbar ist.")],
    explanation: "Ein gesetzter Blinker allein rechtfertigt kein Vertrauen. Erst wenn das Abbiegen durch Verlangsamung und Einlenken eindeutig erkennbar ist, darf der Wartepflichtige fahren. Bei ausgefallener Ampel gelten die Verkehrszeichen.",
    legalReference: "§ 8 Abs. 2 StVO; § 37 Abs. 1 StVO",
  }),
  q({
    code: "own-vorfahrt-040", topic: "vorfahrt", points: 4, difficulty: 0.55, tags: ["feldweg", "ausserorts", "rechtsabbiegen"],
    text: "Sie wollen auf der Landstraße rechts in einen unbefestigten Feldweg abbiegen. Aus dem Feldweg kommt Ihnen ein Traktor entgegen, der auf die Landstraße einfahren will. Was gilt?",
    answers: [t("Der Traktor muss warten, weil er aus einem Feldweg auf die Straße einfährt"), t("Sie sollten trotzdem langsam und bremsbereit abbiegen, weil der Feldweg schmal ist"), f("Sie müssen dem Traktor Vorfahrt gewähren, weil er von rechts kommt", "Wer aus einem Feldweg kommt, hat keine Vorfahrt."), f("Sie müssen vor dem Abbiegen anhalten und den Traktor herauslassen", "Eine Pflicht dazu besteht nicht, auch wenn es aus Rücksicht sinnvoll sein kann.")],
    explanation: "Wer aus einem Feld- oder Waldweg auf eine Straße einfährt, muss allen anderen Vorfahrt gewähren. Beim Abbiegen in den schmalen Feldweg ist dennoch Vorsicht angebracht, damit es mit dem wartenden Traktor nicht eng wird.",
    legalReference: "§ 8 Abs. 1 Nr. 2 StVO",
  }),
  q({
    code: "own-vorfahrt-041", topic: "vorfahrt", points: 5, difficulty: 0.45, tags: ["linksabbiegen", "gegenverkehr", "kreuzung"],
    text: "Sie warten als Linksabbieger auf eine Lücke im Gegenverkehr. Hinter Ihnen hupt ein Fahrer ungeduldig. Was ist richtig?",
    answers: [t("Weiter warten, bis der Gegenverkehr das gefahrlose Abbiegen zulässt"), f("Zügig abbiegen, damit der Verkehr hinter Ihnen nicht aufgehalten wird", "Das Hupen anderer ändert nichts an Ihrer Wartepflicht gegenüber dem Gegenverkehr."), f("Aussteigen und den Fahrer hinter Ihnen zur Rede stellen", "Das behindert den Verkehr und ist unzulässig.")],
    explanation: "Der Gegenverkehr hat Vorrang, unabhängig davon, wie lange der nachfolgende Verkehr wartet. Wer sich zu einem riskanten Abbiegen drängen lässt, trägt bei einem Unfall die Verantwortung.",
    legalReference: "§ 9 Abs. 3 StVO",
  }),
];
